qbittorrent/qBittorrent

- src/base/bittorrent/torrentinfo.cpp
When fileSize == 0, the second index could be smaller than the first index, thus trigger the
assert check in IndexInterval constructor.
Closes #10611.
> Fix assertion fail

- src/base/algorithm.h
- src/base/bittorrent/session.cpp
- src/base/filesystemwatcher.cpp
- src/base/http/server.cpp
- src/base/preferences.cpp
- src/gui/properties/peerlistwidget.cpp
- src/webui/webapplication.cpp
We can now replace QMutable*Iterator by removeIf() which usage is more consistent with other
algorithm functions.
> Improve removeIf() to support other types

- src/base/bittorrent/trackerentry.cpp
- src/base/bittorrent/trackerentry.h
This commit covers trackerentry.cpp only.
This is should be the last (easy) one, to fix the rest of deprecate warnings require non-trivial refactor.
> Use newer libtorrent API (part 3)

- src/gui/transferlistfilterswidget.cpp
By changing to use natvie UI tree controls.
Closes #10709.
> Fix arrow too large on macOS

- src/base/utils/string.cpp
The QString::toInt() might overflow when the string is long.
Closes #10706.
Will backport to v4_1_x branch.
> Fix wrong comparison result

- src/base/utils/string.cpp
The QString::toInt() might overflow when the string is long.
Closes #10706.
> Backport to v4_1_x

- src/gui/torrentcontentmodel.cpp
This icon is used in content tree where all icons should come from OS native and not from qbt.
Before:
After:
> Use native folder icon in content tree

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
* Use alert's timestamp
This way has better accuracy than running our own timer.
* Remove unused stats_alert handler
Fixup 0fe9cd05c4aca8be9820cd489c8fa57173df6ed3.
> Use timestamp from alert

- src/base/rss/private/rss_parser.cpp
- src/base/rss/private/rss_parser.h
- src/base/rss/rss_feed.cpp
Currently RSS Feed that has duplicated item identifiers can cause application crash.
> Ignore RSS articles with non-unique identifiers

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
* Fix speed limit not applying to IPv6 peers
`TORRENT_USE_IPV6` is not used by libtorrent 1.2 anymore.
~~Will backport to v4_1_x.~~ This issue only affects libtorrent 1.2.
> Fix speed limit not applying to IPv6 peers

- src/base/bittorrent/session.cpp
Someone added "optimization" for a preloaded torrent so that it doesn't create any additional files, but forgot to disable it if such a torrent needs to continue downloading.
>  Disable "Upload mode" when start preloaded torrent. Closes #10751

- src/gui/addnewtorrentdialog.cpp
- src/gui/downloadfromurldialog.cpp
- src/gui/search/searchjobwidget.cpp
* Drop support for "BC Link" format
Fixup 19d6de7.
* Fix unable to control add torrent dialogs when opened simultaneously
Personally I would just make `AddNewTorrentDialog` default to non-modal rather than going this contrived way, however I guess that won't be accepted by others easily.
> Fix unable to control add torrent dialogs when opened simultaneously

- src/base/bittorrent/torrenthandle.cpp
- src/gui/addnewtorrentdialog.cpp
- src/gui/addnewtorrentdialog.h
- src/gui/properties/propertieswidget.cpp
- src/gui/properties/propertieswidget.h
- src/gui/torrentcontenttreeview.cpp
- src/gui/torrentcontenttreeview.h
* Add TorrentContentTreeView::renameAction(BitTorrent::TorrentHandle *) 
* Add TorrentContentTreeView::renameAction(BitTorrent::TorrentInfo &) 
* Fix unable to rename folder on Windows
* Log file rename failed errors
> Fix unable to rename folder on Windows. Closes #9151.

- src/gui/optionsdialog.ui
This PR focus Behavior row, when Options dialog is opened.
Closes #7957
> Focus behavior row in Options dialog

- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
- src/base/utils/string.cpp
- src/base/utils/string.h
- src/gui/torrentcontenttreeview.cpp
* Properly remove empty leftover folders after rename
TorrentInfo::origFilePath will return the very original path from .torrent file, not the most recent file path before the rename operation and thus the code would not be working as we expected.
* Don't remove parent directories 
QDir::rmpath removes *all* parent directories while QDir::rmdir removes the specified directory.
* Log save_resume_data_failed_alert 
* Fix updated save path not saved for paused torrents
> Remove empty leftover folders after rename properly

- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrentinfo.cpp
- src/base/preferences.cpp
- src/base/rss/rss_autodownloadrule.cpp
- src/base/rss/rss_feed.cpp
- src/base/scanfoldersmodel.cpp
- src/base/search/searchpluginmanager.cpp
- src/base/utils/fs.cpp
- src/base/utils/fs.h
- src/gui/fspathedit.cpp
- src/gui/mainwindow.cpp
- src/gui/search/pluginselectdialog.cpp
- src/gui/torrentcontentmodel.cpp
- src/gui/torrentcreatordialog.cpp
- src/gui/utils.cpp
- src/webui/api/appcontroller.cpp
Unlike "toNativePath" which name clearly reflects the function result "fromNativePath" has no such clear meaning. Since this function converts path into uniform format "toUniformPath" is better name.
> Rename "fromNativePath" to "toUniformPath"

- src/gui/addnewtorrentdialog.cpp
- src/gui/categoryfilterwidget.cpp
- src/gui/categoryfilterwidget.h
- src/gui/fspathedit_p.cpp
- src/gui/mainwindow.cpp
- src/gui/mainwindow.h
- src/gui/optionsdialog.cpp
- src/gui/properties/peerlistwidget.cpp
- src/gui/properties/propertieswidget.cpp
- src/gui/properties/propertieswidget.h
- src/gui/properties/speedwidget.cpp
- src/gui/properties/trackerlistwidget.cpp
- src/gui/properties/trackerlistwidget.h
- src/gui/rss/automatedrssdownloader.cpp
- src/gui/rss/rsswidget.cpp
- src/gui/search/pluginselectdialog.cpp
- src/gui/search/pluginselectdialog.h
- src/gui/search/searchjobwidget.cpp
- src/gui/tagfilterwidget.cpp
- src/gui/transferlistfilterswidget.cpp
- src/gui/transferlistfilterswidget.h
- src/gui/transferlistwidget.cpp
The `exec()` method will create another event loop and transfer control over there which might introduce unexpected bugs.
> Avoid creating unnecessary event loops

- src/webui/www/private/rename.html
Special characters would get html encoded (`&` -> `&amp;`). This has been tested against several payloads (e.g. `<script>alert(0)</script>`) to ensure it's not vulnerable to XSS.
Closes #10837 
If #10006 is backported to v4.1 then this should be as well.
> Fix WebUI encoding of special characters

- src/gui/addnewtorrentdialog.cpp
- src/gui/mainwindow.cpp
- src/gui/properties/propertieswidget.cpp
- src/gui/search/searchjobwidget.cpp
- src/gui/search/searchjobwidget.h
- src/gui/transferlistwidget.cpp
- src/gui/transferlistwidget.h
* Move copy actions under a submenu
* Avoid allocating a new menu/action manually
* Properly deallocate actions when menu closed 
* Add right click menu to SearchJobWidget
* Remove unused lambda capture
> Right click menu improvements

- src/gui/search/searchjobwidget.cpp
- src/gui/search/searchjobwidget.h
- src/gui/search/searchwidget.cpp
- src/gui/search/searchwidget.h
- src/gui/search/searchwidget.ui
* Rename label in search widget
* Add more copy field actions to search widget
Closes #10250.
* Remove buttons from search widget
These buttons are replaced by right-click menu actions.
* Replace QList by QVector
Screenshots:
> Improvements to search widget

- src/app/qtsingleapplication/qtlocalpeer.cpp
* Drop suspiciously large data
This is to avoid exhausting system memory.
* Restrict QLocalServer access
The default is world access which means even even unprivileged local accounts can connect to it too.
Tested on Windows & linux.
qtsingleapplication is outdated and I don't like to add local patches to it. We really should look into replacing it or consider maintaining it ourselves.
> Tighten up qtsingleapplication

- src/app/main.cpp
- src/base/search/searchdownloadhandler.cpp
- src/base/search/searchhandler.cpp
- src/gui/autoexpandabledialog.cpp
- src/gui/properties/speedplotview.cpp
* Replace obsoleted QFontMetrics::width()
Qt 5.13 marked QFontMetrics::width() obsolete.
* Replace obsoleted QProcess::finished(int)
It is replaced by QProcess::finished(int, QProcess::ExitStatus).
> Replace obsoleted Qt functions

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
* Use LogMsg() helper
* Add "Socket backlog size" option
The default value in libtorrent is 5 which is too small nowadays. The new default value 30 is chosen to be in line with QTcpServer::maxPendingConnections().
* Add "File pool size" option
> Add more libtorrent options to Advanced Settings

- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrenthandle.cpp
* Use newer libtorrent API
This should be the last part from me. The remaining are session settings that are still in use in libt 1.1.
Of course `#if` conditionals can be added to them, however the number is large and will greatly reduce readability. IMO better remove them when qbt drop libt 1.1 support.
* Fix torrent properties not saved for paused torrents
* ~~Remove duplicate "sequential download" key
libtorrent already records them so we don't need to handle them manually.~~
* Use proper log message when there are no error
> Use newer libtorrent API (part 5)

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
Start all torrents auto-managed to prevent simultaneous checking of multiple torrents.
Handle checking state of paused torrent to prevent it from being resumed when qBittorrent is closed until checking isn't complete.
> Fix torrent checking issues

- src/app/application.cpp
- src/base/preferences.cpp
- src/base/preferences.h
- src/gui/CMakeLists.txt
- src/gui/gui.pri
- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.h
- src/gui/optionsdialog.ui
- src/gui/uithememanager.cpp
- src/gui/uithememanager.h
searches *.qss in {config-folder}/styles, and use those as style-sheet with mainwindow
> Allow Styling through QSS

- src/webui/www/private/css/Layout.css
Previous:
After:
BTW, how about also applying this to the speed labels? i.e. replacing the `min-width: 18em;` in `td.speedLabel`.
> Avoid word wrap in webui footer

- src/gui/CMakeLists.txt
- src/gui/gui.pri
- src/gui/private/tristatewidget.cpp
- src/gui/private/tristatewidget.h
- src/gui/transferlistwidget.cpp
- src/gui/transferlistwidget.h
- src/gui/tristateaction.cpp
- src/gui/tristateaction.h
The new TriStateAction class is an improvement of the old one in the sense that:
1. Have public method to set states.
2. Can connect to the usual Qt slots.
3. Draws checkbox at the correct offset (where QAction draws) in menu
and better handling of mouse clicking and keyboard navigating.
old:
new:
> Implement tri-state checkbox action in menu

- src/webui/api/appcontroller.cpp
- src/webui/api/appcontroller.h
- src/webui/www/private/preferences.html
- src/webui/www/private/preferences_content.html
Therefore we can adjust advanced parameters via WebUI, I think it would be helpful especially for ``qbittorrent-nox``.
The qBittorrent section and libtorrent section are implemented, as shown below.
I have removed some settings in qBittorrent section (as below), because they are only related to the GUI, and may mislead users if we put them in WebUI.
* Confirm torrent recheck
* Check for software updates (it only notifies user in GUI)
* Transfer list refresh interval (currently it doesn't affect the WebUI)
* Resolve peer host names (it doesn't affect too)
* Display notifications
* Display notifications for added torrents
* Confirm removal of all tags
* Download tracker's favicon
* Save path history length
* Enable speed graphs
On MacBook:
On Windows:
There are still something we need to …
> Add advanced options in WebUI

- src/webui/www/private/index.html
WebUI implementation of #10850
Right click menu for search jobs (partially #10850 and #10852) will be in a different PR
> Move WebUI copy actions under a submenu

- src/webui/www/private/scripts/contextmenu.js
- src/webui/www/private/scripts/dynamicTable.js
Touching a table row for 600 milliseconds will trigger the table's context menu. This small tweak isn't perfect, but it makes the WebUI a lot more featureful on mobile.
> Add WebUI support for triggering context menus on mobile

- src/gui/torrentcontentmodelitem.cpp
Ignored folders have a remaining size of 0; ignored files should as well. Also fixes a bug with calculating the remaining size of ignored folders.
> Update remaining size of ignored files to 0

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
If fastresume data was rejected we need to save updated resume data after torrent finishes rechecking.
Also fixes handling of requested torrent resume data. Session should increase an appropriate counter each time the torrent resume data is requested to save.
> Save updated resume data for completed torrents 

- .gitignore
- src/webui/api/torrentscontroller.cpp
- src/webui/www/private/css/style.css
- src/webui/www/private/index.html
- src/webui/www/private/properties.html
- src/webui/www/private/scripts/client.js
- src/webui/www/private/scripts/dynamicTable.js
- src/webui/www/private/scripts/file-tree.js
- src/webui/www/private/scripts/filesystem.js
- src/webui/www/private/scripts/prop-files.js
- src/webui/www/webui.qrc
Rename functionality is going to take some more time so will be coming in a later PR.
Closes #974, closes #4476, closes #10162, closes #10484, closes #10729
Before:
After:
> Display files hierarchically in Web UI content tab

- src/gui/advancedsettings.cpp
The Qt bug is fixed in 5.7.1, while we require Qt >= 5.9.0.
Note: Several people should test PR to confirm the duplicate interface issue isn't reintroduced
> Remove Qt bug workaround

- src/webui/www/private/scripts/mocha-init.js
All windows should display their full content without a scroll bar, when possible. Using a max height of 600px to avoid unnecessarily tall windows.
> Increase WebUI window heights

- src/webui/www/private/scripts/dynamicTable.js
The name sort in gui is already case-insensitive, whereas webui not.
before:
after:
> Sort torrent names case-insensitively in webui

- src/base/bittorrent/session.cpp
Closes #10341.
Besides the issue, I can't think of any reason to use a fixed 8999 port.
> Use a randomized port number for the first run

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/optionsdialog.ui
- src/webui/www/private/preferences_content.html
When ratio/time limit is reached, ETA shows zero for affected torrents until qbt restart, after that, infinity. Thought i should point it out in case it's undesirable.
> Add option to enable Super Seeding mode once ratio/time limit is reached. Closes #7160.

- src/webui/www/private/scripts/dynamicTable.js
- src/webui/www/private/scripts/misc.js
This PR adds support for exclusions in the WebUI's table filters (torrents table, search table, torrent content table). It uses a `-` to indicate a term that should be excluded, and a `+` to include a term that should be included (e.g. you can search for a hypen with `+-`). Terms without a leading `+` are treated the same as terms with a leading `+`.
This feature has only been added to the WebUI due to the GUI already containing exclusion support via regex. The benefit of this syntax is that it's already commonly support by the web and doesn't require knowledge of regex.
Closes #10241
Examples:
> Support exclusions in WebUI table filters

- src/webui/api/appcontroller.cpp
New options have been added to this api, but the `apply()` logic was never moved down. The options should have been added before `apply()`.
> Don't save preferences until all options are processed

- src/gui/optionsdialog.ui
- src/webui/www/private/views/preferences.html
By using disambiguation field instead of comment field to differentiate translations.
Closes #11062.
> Fix translation issues

- src/gui/properties/peerlistwidget.h
This is related to a crash occurring (on Windows) at https://github.com/qbittorrent/qBittorrent/blob/7ce26435bd49ba5f74bb4de5f2b6e5d352faa152/src/gui/properties/peerlistwidget.cpp#L208 due to uninitialized `m_resolver`. Note that deleting a `nullptr` is guaranteed to have no effects.
Strange that it runs fine when I was testing on linux :(
> Initialize pointers

- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrenthandle.cpp
"Fix unable to remove web seeds" fixes the issue #11023 and other commits are for fixing bugs discovered along the way.
> Fix unable to remove web seeds

- src/webui/www/private/views/preferences.html
Disable port input when "Use different port on each startup" option is selected.
This follows the behavior in GUI.
> Conditionally disable port input field

- src/base/bittorrent/torrenthandle.cpp
> Always save info dict when saving fastresume (backport to v4_1_x)

- src/webui/www/private/setlocation.html
I changed maxlength because we couldn't modify the path of the location when he is more than 100 character.
> Remove max character limit of location path

- src/base/bittorrent/torrentcreatorthread.cpp
- src/base/bittorrent/torrentcreatorthread.h
- src/gui/torrentcreatordialog.cpp
- src/gui/torrentcreatordialog.h
- src/gui/torrentcreatordialog.ui
Alignment is achieved by adding dummy pad files between files which is handled by libtorrent.
Closes #10460.
See: [screenshot](https://user-images.githubusercontent.com/9395168/64578054-cedff780-d3b0-11e9-80c8-888a2d429add.png)
Ref: https://www.libtorrent.org/reference-Create_Torrents.html#create_torrent
> Add option to align file to piece boundary when creating new torrent

- src/base/bittorrent/session.cpp
Closes #10119.
Ref: https://www.libtorrent.org/reference-Alerts.html#url_seed_alert
> Improve error messages for url_seed_alert

- src/webui/www/private/scripts/dynamicTable.js
- src/webui/www/private/scripts/prop-files.js
- src/webui/www/private/scripts/prop-general.js
- src/webui/www/private/scripts/prop-peers.js
- src/webui/www/private/scripts/prop-trackers.js
JS code for torrent general properties, files, peers, trackers inconsistently
escaped HTML special characters, then the dynamicTable inconsistently escaped
again and then the value was set to HTML element text or html properties.
To fix this mess, don't escape any property values in the prop-*.js files.
Instead, make dynamicTable set HTML element text instead of html property by
default. This behavior can be overridden by setting a custom updateTd
function on the respective column, if needed. This is where the HTML escaping
should be done.
Also reordered existing updateTd functions to match column order, changed
custom updateTd functions from setting html to text property wherever possible,
removed custom updateTd functions that turned out to be redundant.
Closes #11209.
> WebUI: fix escaping of HTML special characters

- src/base/rss/rss_autodownloadrule.cpp
- src/base/tristatebool.h
~~IMO it is not really required that `TriStateBool` has an `operator int()`, especially when `int` is larger than the private variable's type `signed char`. An observer of type `signed char` is also suitable for `switch()` statements which takes an integer type.~~
> Revise TriStateBool class

- src/base/logger.cpp
- src/base/settingsstorage.cpp
The related classes doesn't really need recursive mutex so drop it. And if it is really required it usually indicates bad design and we should avoid it anyway.
Or they really are required... please let me know why.
> Use non-recursive mutex

- src/app/application.cpp
- src/app/qtlocalpeer/qtlocalpeer.cpp
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/utils/misc.cpp
- winconf.pri
* Call Windows API directly
We already bumped the OS requirement to Windows 7 and those functions can be called directly without the need to load them first.
* Revise SessionSettingsEnums wrapper
This simplify the wrapper to become a namespace.
* Change Session::deleteTorrent() first parameter to take InfoHash type
* Avoid redundant lookups
> Code clean up

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/transferlistwidget.cpp
- src/webui/api/torrentscontroller.cpp
* Use InfoHash type in queueing operations
This avoids redundant type conversions.
* Preserve relative order when moving to top/bottom in queue
Closes #11312.
> Preserve relative order when moving to top/bottom in queue

- src/gui/utils.cpp
Previously was using a hardcoded value which might lead to issues like #11234.
> Use screen real physical DPI on Windows

- src/gui/utils.cpp
Previously was using a hardcoded value which might lead to issues like #11234.
> Use screen real physical DPI on Windows (backport)

- cmake/Modules/FindLibtorrentRasterbar.cmake
- cmake/Modules/winconf.cmake
- winconf.pri
* `TORRENT_USE_LIBCRYPTO` replaced `TORRENT_USE_OPENSSL` since OpenSSL 1.1.
* `TORRENT_DISABLE_RESOLVE_COUNTRIES` has been removed since libtorrent 1.2.
> Update libtorrent build defines on Windows

- src/gui/utils.cpp
> Fix screen scaling factor calculation

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
This is to avoid Windows swapping out other application data from
OS cache and put in torrent data which hinders other program
responsiveness.
The default value "Below normal" is choosen because casual users have
other higher priority apps (such as browser) running and they don't
expect OS to swap out its data. Dedicated seeders most probably will not
have other app running on their system and would expect qbt has
priority over other background services.
The option only has effect on Windows >= 8.
Inspired by: https://github.com/arvidn/libtorrent/issues/4011#issuecomment-536151336
> Add option to control qBittorrent process memory priority

- src/app/application.cpp
- src/base/bittorrent/session.cpp
- src/base/search/searchpluginmanager.cpp
- src/base/utils/fs.cpp
- src/gui/downloadfromurldialog.cpp
- src/gui/transferlistmodel.cpp
- src/webui/api/serialize/serialize_torrent.cpp
From http://man7.org/linux/man-pages/man2/statfs.2.html
>The __fsword_t type used for various fields in the statfs structure definition is a glibc internal type, not intended for public use...
>Using unsigned int for such variables suffices on most systems.
> Fix integer narrowing on x86

- src/base/net/geoipmanager.cpp
English spelling is "Vietnam". Vietnamese spelling is "Việt Nam" or
"Viet Nam".
> Fix country name misspelling

- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
- src/gui/previewselectdialog.cpp
- src/gui/previewselectdialog.h
- src/gui/previewselectdialog.ui
- src/gui/transferlistwidget.cpp
* Clean up PreviewSelectDialog class
* Fix preview action not working
Root cause is the PreviewSelectDialog::readyToPreviewFile signal is emitted before it is connected to a slot.
Only single-file torrents are affected.
* Don't close preview dialog if selected file failed to open 
User may have made a mis-selection and this should not close the dialog (only when the torrent has multiple previewable files).
* Show torrent name in "preview file" related dialogs
> Fix "preview file" action not working

- dist/unix/systemd/qbittorrent-nox@.service.in
This ensures that `qbittorrent-nox` doesn't start while the network is not up yet.
`network-online.target `is also pulled in with `Wants=` per the systemd documentation—[`systemd.special(7)`](https://www.freedesktop.org/software/systemd/man/systemd.special.html#network-online.target).
> Order qbittorrent-nox@.service after network-online.target

- src/base/bittorrent/torrenthandle.cpp
Partially revert 87d98403f400674cc5d06853c167cc6472bcf20c
Closes #11076, closes #11400
> Reallow to pause checking torrents

- cmake/Modules/winconf-mingw.cmake
- cmake/Modules/winconf-msvc.cmake
Tested on MSVC and Msys2-mingw64
I think `qbt_base` is the only one which requires `iphlpapi` plus I don't find where windows libs are specified.
> Fix CMake Windows compilation

- src/base/rss/rss_autodownloader.cpp
- src/base/rss/rss_autodownloadrule.cpp
- src/base/rss/rss_autodownloadrule.h
- src/gui/rss/automatedrssdownloader.cpp
- src/gui/rss/automatedrssdownloader.ui
When adding a torrent through the "add a torrent" dialog, there's an option to enable/disable creating a subfolder (with the same name as the torrent) when the torrent contains multiple files. However, this option cannot be set when using auto-download RSS rules, and it always creates such folder.
This commit adds a new option to the RSS auto-download rule editing screen that allows specifying this setting (defaulting to the global setting value). It would also expose the setting to the [RSS Web API](https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation#set-auto-downloading-rule) (adding a "createSubfolder" bool field).
**Note**: I didn't change any localization files (for the new label text) as I'm unsure of the localization workflow in this project.
Closes #9414.
> Add "create subfolder" option to RSS auto-download rules

- src/gui/optionsdialog.h
- src/gui/optionsdialog.ui
- src/gui/transferlistwidget.cpp
Let's have an option for completed torrents to do preview on double-click, and if we can't, open destination folder so the user can choose the file they want.
Closes issues #6965, #486.
> Add "Preview file" double-click action

- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrenthandle.cpp
Now that the problem behind PR #11104 is correctly addressed via https://github.com/arvidn/libtorrent/pull/4112, let's go back to our original way of storing/loading fastresumes.
> Revert fastresume functionality

- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrentinfo.cpp
Today I noticed some build warnings, possibly started since this commit: https://github.com/arvidn/libtorrent/commit/78aefcc80648e81ff68a0cab258e7d2739c3ae79
> Migrate away from deprecated API

- src/base/rss/rss_feed.cpp
Users report about RSS feeds stop updating properly after some time for some reason. I can't reproduce it an it's impossible to understand what step (downloading or parsing) hangs.
> Log "RSS Feed successfully downloaded" event

- src/gui/addnewtorrentdialog.cpp
- src/gui/properties/propertieswidget.cpp
Expand single-item folders recursively in Content tab.
Closes #11525.
> Expand single-item folders in torrent content

- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrenthandle.cpp
- src/gui/transferlistdelegate.cpp
- src/gui/transferlistmodel.cpp
Before this patch, adding the torrent in https://github.com/qbittorrent/qBittorrent/issues/11511 and the torrent state will stay in torrent_status::checking_resume_data forever.
This is not the correct state since the `torrent_status.errc` field is non-zero and this commit fixes it.
I haven't got time to check if this breaks other use cases so maybe defer to post v4.2.0 release and testings are welcome.
> Fix stuck in wrong torrent state

- src/base/search/searchpluginmanager.cpp
- src/webui/www/private/scripts/dynamicTable.js
- src/webui/www/private/views/search.html
* Fix missing translations in search plugins dialog
* Unify HTML elements height
Specifying a height value might cut the displayed text, so let it auto decide.
Before: ![before](https://user-images.githubusercontent.com/9395168/70134920-ef73d100-16c3-11ea-81a6-ee6a747dfe82.png)
After: ![after](https://user-images.githubusercontent.com/9395168/70134919-ef73d100-16c3-11ea-9cfb-428d58ce04ea.png)
* Fix incorrect translation displayed after language change
It is expected in WebUI that the language change applies immediately (without a program restart) and this static caching prevents that.
> Fixes for WebUI

- src/webui/www/private/scripts/client.js
According to [Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler), `registerProtocolHandler()` is only available when using secure contexts (i.e. HTTPS for everything outside localhost).
The message "`Your browser does not support this feature`" does not make this obvious and can lead to confusion if the user is using a modern browser.
> Mention HTTPS in WebUI magnet link warning

- src/webui/www/private/scripts/client.js
Fix `alert()` I broke in #11615 .
> Fix quoting of alert() in client.js

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/settingsstorage.cpp
- src/base/utils/net.cpp
- src/base/utils/net.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/webui/api/appcontroller.cpp
- src/webui/www/private/views/preferences.html
Closes #11561
It started as a simple fix for #11561. But as I dug deeper I fixed more and more things. And it became a full blown refactor.
With this PR:
1. As per 1.2.x docs, the default setting (aka all interfaces + all addresses) is to also explicitly set the IPv6_ANY address
2. Now if a user chooses "all addresses" from a specific interface, we tell libtorrent to bind to that specific interface instead of listing to it all the addresses of the interface. This has the benefit that libtorrent will automatically follow any changes to that interface. This is of benefit to VPN users when their connection drops and then they get assigned a new "local" ip.
3. Two new options in the drop down menu for addresses. `All IPv4 Addresses` and `All IPv6 Addresses`.
4. Due to the above, the option …
> Rework the listening IP/interface selection code

- src/gui/properties/propertieswidget.cpp
> Align Properties tab bar correctly on window resize

- src/app/application.cpp
- src/app/application.h
- src/app/cmdoptions.cpp
- src/app/cmdoptions.h
Enable portable mode not only by adding command line option but also by checking if "profile" folder exists in the app dir. Closes #9445.
> Enable portable mode if "profile" folder exists

- src/base/bittorrent/session.cpp
Restored torrents already have the correct path saved in their fastresume. Don't override it.
Magnets and new torrents have to be set explicitly to the incomplete folder if it is enabled.
Closes #11552
**Extra info**
The issue rose from a subtle different in `add_torrent_params` object between libtorrent 1.1.x and 1.2.x. In 1.1.x the object had an additiona field which held the fastresume data as whole. Decoding of the fastresume was done after we added the torrent in the libtorrent session. So some fields in fastresume were used instead of their counterparts in the `add_torrent_params` object. (and this could be overriden by supplying extra flags).
In 1.2.x the fastresume data are decoded and an `add_torrent_params` object is generated. The `add_torrent_params` object doesn't hold …
> Use the incomplete folder where appropriate

- src/gui/addnewtorrentdialog.cpp
Closes #8772.
This will fix issue that "Free space on disk:" label in 
Add New Torrent dialog not updated on Category change
when Torrent Management Mode is on Auto mode.
> Update free disk space label on Category change in Auto Mode

- src/app/application.cpp
- src/base/preferences.cpp
- src/base/preferences.h
- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.ui
Windows only.
Closes #9592
Currently not sure if it works as intended. I am unable to run simple bat file.
This command `cmd.exe <path_to_bat> "%N" "" "%I"`, doesn't seem to run the bat file.
Does anyone know what is the correct invocation? Or does anyone want to test it himself?
I didn't wrap the new additions in Preferecences/WebAPI in ifdef because I assume it would be hard from a web-dev POV to code around this. Am I right?
> Option to show console when external program is run

- src/base/preferences.cpp
- src/base/preferences.h
- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.ui
- src/webui/api/appcontroller.cpp
- src/webui/webapplication.cpp
- src/webui/webapplication.h
- src/webui/www/private/views/preferences.html
Closes #11724.
Option is enabled by default for users using qBittorrent's built-in HTTPS capabilities. This flag will never be set if qBittorrent is using plain HTTP.
Users using HTTPS reverse proxies, like "qbt <-> (http) <-> proxy <-> (https) <-> user" should override the flag in the proxy in order to set it, if they wish to do so.
Testing:
- DONE Using HTTP: WebUI works unless secure cookie option is selected (which is expected, and hence the warning beside the option).
- DONE Using built-in HTTPS (with self-signed certs, real certs should not make a difference): works as expected; WebUI still works even if the secure cookie option is disabled (as previously).
- ~TODO~DONE: HTTPS with reverse proxy (like the drawing in https://github.com/qbittorrent/qBittorrent/wiki/Linux-WebUI-HTTPS-wi …
> WebUI: Implement "Secure" flag for session cookie. Closes #11724

- src/webui/www/private/scripts/client.js
~Don't update dynamic torrent table or send request to sync data on each selection change of category, tag, status, or setting of alternative speed limits. This prevents piling up of requests and bogging down slow/busy machines. Everything gets updated on the next scheduled request anyway (via the timeout mechanism).~
Don't sync main data if a request to do so is already in progress. This prevents piling up of requests and bogging down slow/busy machines, since the current implementation of `sync/maindata` is very computationally intensive, especially with lots of torrents. Everything gets updated on the next scheduled request anyway (via the timeout mechanism).
If this is merged, I think it is a good idea to backport this to 4_1_X
> WebUI: Prevent excessive requests to /api/v2/sync/maindata

- src/gui/transferlistdelegate.cpp
- src/gui/transferlistdelegate.h
- src/gui/transferlistmodel.cpp
- src/gui/transferlistmodel.h
- src/gui/transferlistsortmodel.cpp
- src/gui/transferlistsortmodel.h
Model returns string for DisplayRole.
Text alignment is set by Model (using TextAlignmentRole).
Delegate performs custom painting only where necessary (i.e. for Progress bar).
Use QStyledItemDelegate instead of QItemDelegate.
Use native progress bar on all platforms.
> Improve Transfer list architecture

- src/webui/www/private/scripts/client.js
- src/webui/www/private/views/statistics.html
Closes #11665
Problem fixed is unique to the statistics window (other windows, like `about.html ` were not affected).
> WebUI: fix populating statistics window

- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/trackerentry.cpp
> Tracker is errored only if all local endpoints fail

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/webui/api/appcontroller.cpp
- src/webui/www/private/views/preferences.html
Exposing the settings for stop_tracker_timeout so user can set it to higher value to ensure tracker announces go through when client is exited/torrent is paused.
> Expose stop tracker timeout in Advanced Settings (GUI + WebUI)

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/webui/api/appcontroller.cpp
- src/webui/www/private/views/preferences.html
New placement is below ANNOUNCE_IP.
> Change stop tracker timeout settings placement

- src/webui/www/private/scripts/prop-files.js
Ids started from zero and first row converts to false.
Closes #11826.
> WebUI: Fix first row renaming in files tab

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/webui/api/appcontroller.cpp
- src/webui/www/private/views/preferences.html
And expose option in WebUI settings.
More info:
https://libtorrent.org/single-page-ref.html#piece_extent_affinity
> 
>name | type | default
>-- | -- | --
>piece_extent_affinity | bool | false
>
>when this is true, create an affinity for downloading 4 MiB extents of adjacent pieces. This is an attempt to achieve better disk I/O throughput by downloading larger extents of bytes, for torrents with small piece sizes
> Add piece_extent_affinity to AdvancedSettings

- src/webui/www/private/scripts/dynamicTable.js
As suggested in https://github.com/qbittorrent/qBittorrent/pull/11825#discussion_r365557626
> WebUI: Use correct operators in logical expressions

- cmake/Modules/MacroQbtCompilerSettings.cmake
Our previous setup lead to two unintended consequences:
* Debug flags were included in both release and debug builds instead
of just debug builds
* Clang doesn't support -gX (where X is the level of debugging
optimization), but we checked for -Og support instead
This commit avoids both of these scenarios by removing the additional
flags altogether. Partial resolution to #11856.
> CMake: Remove additional debugging compiler flags

- src/base/bittorrent/session.cpp
Libtorrent has deprecated `upnp_ignore_nonrouters` in https://github.com/arvidn/libtorrent/pull/4251
> Migrate away from deprecated settings

- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.h
- src/gui/optionsdialog.ui
Old:
New: 
Why GroupBox?
I want to add an option for "Use default Icon set".
> Reorganize UI theme selection

- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/private/nativesessionextension.cpp
- src/base/bittorrent/private/nativesessionextension.h
- src/base/bittorrent/private/nativetorrentextension.cpp
- src/base/bittorrent/private/nativetorrentextension.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
Well, I finally managed to get rid of these terrible, hard to understand and maintain "torrent startup states".
Now we can just create torrent (both add new torrent or restore previously existing one) in its real state (paused, running or force running). If fastresume data will be rejected due to missing files torrent is paused by libtorrent session extension (in libtorrent working thread). We only need to handle an appropriate alert and mark torrent as "Missing files".
> Simplify torrent startup handling 

- src/gui/optionsdialog.ui
Instead of showing "-1" for unlimited, showing  "∞" for better understanding. Screenshot is given below:
I have used already existing code from speed section:
Closes #9236
> Show "∞" instead of " -1" in Preferences

- src/base/bittorrent/infohash.cpp
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/trackerentry.cpp
- src/base/net/downloadmanager.cpp
* Use faster hash function
qHash(QString) will need to hash/loop through all the data while the new code will only need one memcpy() and a few bit manipulations.
* Revise qHash function
Instead of xor and narrowing the integers ourselves, now we let qHash() from Qt do the job properly.
* Use systematic approach to generate hash
The basic idea is to hash each class member and then mix them with xor operation.
However the `seed` must be handled with care, it should only be introduced once when mixing the hashes of each class member, otherwise under some circumstances the `seed` might xor with itself and thus break the intended effect.
> Improve qHash functions

- src/base/bittorrent/peeraddress.cpp
- src/base/bittorrent/peeraddress.h
- src/gui/properties/peerlistwidget.cpp
- src/gui/properties/peerlistwidget.h
The uniqueness of peers is now determined by their IP and port
instead of just their IP.
closes #11845
> Show any multiple connections from the same IP in peer list

- src/base/bittorrent/session.cpp
- src/base/iconprovider.cpp
- src/base/logger.cpp
- src/base/net/downloadmanager.cpp
- src/base/net/geoipmanager.cpp
- src/base/net/private/downloadhandlerimpl.cpp
- src/base/net/proxyconfigurationmanager.cpp
- src/base/preferences.cpp
- src/base/scanfoldersmodel.cpp
- src/base/search/searchpluginmanager.cpp
- src/gui/mainwindow.cpp
- src/gui/private/fspathedit_p.cpp
- src/gui/uithememanager.cpp
- src/webui/webui.cpp
Attempting to delete a null pointer is a noop in C++.
Closes #2864.
[1] https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null
> Remove redundant null checks

- src/app/application.cpp
- src/base/scanfoldersmodel.cpp
- src/base/scanfoldersmodel.h
We shouldn't allow Qt parent ownership in here.
BTW I also evaluated using std::unique_ptr here but only to find it fail to compile due to the class destructor is private.
> Fix singleton class ownership

- src/webui/www/private/index.html
- src/webui/www/public/index.html
This will allow browsers to get high quality icon with required resolution
instead of resizing some small raster image.
Browsers can have even more benefit from it. For example, Firefox uses high
resolution icon to display it in "Top Sites" instead of page preview.
Nothing changes for browsers which doesn't support SVG favicons, older PNG
icon is set as fallback, so it will be used in such case.
P.S> I'm not Web developer and know too little about Web-related stuff. I just found [this interesting note](https://superuser.com/a/1495054) about Firefox' "Top Sites" and [this page demonstrating SVG favicons](http://dahlström.net/svg/favicon/favicon.html). so I decided to test this stuff, view attached screenshot to see what happened.
> Use SVG image for WebUI favicon

- src/base/net/downloadmanager.cpp
- src/base/net/private/downloadhandlerimpl.cpp
- src/base/net/private/downloadhandlerimpl.h
Qt doesn't support Magnet protocol so we need to handle all redirections
manually to allow redirections to Magnet URIs.
Closes #11894.
> Handle HTTP redirections manually

- src/app/application.cpp
- src/base/bittorrent/private/statistics.cpp
- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrenthandle.cpp
- src/base/profile.cpp
- src/base/profile.h
- src/base/rss/rss_autodownloader.cpp
- src/base/rss/rss_feed.cpp
- src/base/settingsstorage.cpp
1. Use unified function names `initInstance()` and `freeInstance()` and make them public.
2. Add `freeInstance()` to avoid noise from memory leak detectors. IMO we should not leak memory in any way.
3. Let `instance()`return a pointer directly to avoid unnecessary indirections when invoking functions.
> Unify singleton pattern in Profile class

- src/webui/www/private/css/style.css
Filter list (left side panel) in WebUI is implemented using <a> tags,
CSS defines default style for all <a> elements, and specific style for
filter list elements. Default style for <a> elements sets color, and
this color also used in list. This is looks not so well. So lets just
inherit text color from parent element, and as so as it is not set, so
default text color will be used.
This makes filter list looks like other UI elemets, making all UI more
consistent (like in desktop app).
P.S> I'm not web developer, I know too little in web-related stuff. This change was experimentally achieved using Firefox' web developer tools.
before:
after:
Note color change: orange -> dark gray. As for me, it looks much better, especially if a lot of torrents in the list.
> Inherit text color for filter list elements

- src/base/preferences.cpp
- src/base/preferences.h
- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.ui
- src/webui/api/appcontroller.cpp
- src/webui/api/authcontroller.cpp
- src/webui/api/authcontroller.h
- src/webui/www/private/views/preferences.html
* Expose WebUI ban counter to users
* Use QDeadlineTimer for tracking WebUI banned duration
It simplifies our code and the new timer is monotonic.
* Fix coding inconsistencies in preferences.html 
1. Format table tags properly
2. Add a proper label tag
3. Don't use abbreviation for seconds, we use full name everywhere else
* Expose WebUI ban duration to users
Screenshot: [GUI](https://user-images.githubusercontent.com/9395168/74413783-07619100-4e7b-11ea-97ac-cbf40cf760c9.png), [WebUI](https://user-images.githubusercontent.com/9395168/74413780-06306400-4e7b-11ea-9ce1-7c9100bf2680.png)
> Add configurable ban options for WebUI

- src/base/bittorrent/session.cpp
The message in RuntimeError exception will be displayed to the users and users would be clueless if we don't show the path.
> Include resume folder path in exception message

- src/base/bittorrent/torrenthandle.cpp
Qbt is listing "Not contacted" trackers as error. It shouldn't do that. Partially patches #11997
> Do not list not contacted trackers as error

- src/base/bittorrent/trackerentry.cpp
- src/base/bittorrent/trackerentry.h
This is an attempt to simplify `TrackerEntry::status()` which currently has convoluted logic.
Although it passed my rudimentary tests, more testing are appreciated! Just keep an eye on the Tracker Status column in Trackers tab, see if it shows the correct/usual status.
@thalieht
> Simplify TrackerEntry::status() logic

- README.md
- src/base/net/geoipmanager.cpp
- src/base/net/private/geoipdatabase.cpp
- src/base/net/private/geoipdatabase.h
- src/gui/aboutdialog.cpp
- src/gui/aboutdialog.ui
- src/gui/advancedsettings.cpp
- src/webui/www/private/views/about.html
- src/webui/www/private/views/aboutToolbar.html
- src/webui/www/private/views/preferences.html
> Use IP geolocation database by DB-IP instead of MaxMind

- .gitignore
Typically, CMake builds are executed in a folder named `build` inside the top-level directory directory.
Example: `mkdir build && cd build && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..`
This folder should be recursively ignored by git, so that build products don't pollute the unstaged files list.
> Git: Ignore "build" directory

- src/gui/rss/automatedrssdownloader.ui
- src/gui/torrentcreatordialog.ui
* Remove misleading translation comment
Also it was using the wrong field for translation comment.
* Fix wrong field for translation comment
The `comment` field is used for disambiguation between identical strings. Our case here should use the `extracomment` field which meant as comment for translators.
> Remove misleading translation comment

- src/base/bittorrent/tracker.cpp
Assorted changes to improve the embedded tracker.
Most likely will fix this issue: https://github.com/qbittorrent/qBittorrent/issues/11949, but I am not 100% sure. Further improvements may be needed.
Still, these changes are significant enough that they fixed my attempted reproduction of the issue outlined in https://github.com/qbittorrent/qBittorrent/issues/11949#issuecomment-581534535.
Some observations:
1. BEP-24 (tracker returns external ip) seems to be working for IPv4, but it does not seem to be working properly for IPv6. It will need further testing/improvements (e.g. NAT check and such) until we can claim full compliance. Without the "Embedded tracker: don't use IPv4-mapped v6" commit, for example, it was returning the IPv4-mapped IPv6 address, instead of the proper external IPv4 …
> Fix embedded tracker

- src/base/bittorrent/torrenthandle.cpp
When "user" resumes a torrent allow libtorrent decide whether to really resume it according to current limits.
> Let libtorrent decide whether to resume a torrent

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
Closes #11841
If you choose a wrong directory when using seed mode the torrent will now show an error and reset instead of seeding.
> Check if file exists in seed mode

- src/base/bittorrent/peerinfo.cpp
- src/base/bittorrent/torrenthandle.cpp
Before this change, qbt spent ~1% in these two functions, now it only spends about ~0.5% in my naive testing.
I also tested `QBitArray::fromBits()` which is even faster, but unfortunately libtorrent `bitfield` is incompatible with it.
Probably worth mentioning is that I observed no noticeable inefficiency in qbt code during my naive testing and these 2 functions here are the most outstanding ones (still insignificant but the changes are simple so I would commit it).
> Avoid unnecessary memory writes

- src/app/main.cpp
- src/gui/utils.cpp
First of all, this pull request was created only due to @FranciscoPombal  request after some our discussion in #8255 and @Chocobo1 confirmation that even such dirty pull request will be useful, see https://github.com/qbittorrent/qBittorrent/issues/8255#issuecomment-593131793 and few next for details.
All these changes are just quick and dirty fixes, and this pull request is intended to start the discussion how to improve them.
After that, issues like #8255 , #11234 , #11445 and many other related can be closed.
These changes make qBittorrent look much better on HiDPI screens, especially on Windows. Linux systems (at least X11-based) are also affected by these changes, see few screenshots below from my KDE system (2 first screenshots show qBittorrent installed from official PPA, another 2 …
> Delegate GUI scaling work to Qt

- src/app/application.cpp
- src/app/application.h
- src/app/cmdoptions.h
- src/app/main.cpp
> Allow single app instance per configuration

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
- src/gui/transferlistwidget.cpp
> Move torrent storages one by one

- src/app/cmdoptions.cpp
- src/base/utils/misc.cpp
- src/gui/executionlogwidget.cpp
- src/gui/mainwindow.cpp
- src/gui/statusbar.cpp
- src/gui/tagfiltermodel.cpp
- src/gui/transferlistmodel.cpp
- src/webui/webapplication.h
We mostly use boost in header-only mode, so it is a non-trivial job to get the version string at runtime.
> Get library version strings at runtime

- src/gui/loglistwidget.cpp
By not emitting the native signal, all other keypresses other than
the copy and select keysequences are ignored. This should reallow
keyboard navigation within LogListWidget objects.
Closes #12172.
> Allow other keypresses in LogListWidget

- src/app/main.cpp
Qt 5.14 introduced new feature related to HighDPI screens support,
this parameter is called "scale factor rounding policy", and it is
intended to improve fractional scale factor support (like 150%).
Qt::PassThrough value guarantee that no any rounding will applied to
scale factor, and will be used as is.
this is continuation and fixup of #12102 , based on https://github.com/qbittorrent/qBittorrent/issues/12248#issuecomment-603563053 and https://github.com/qbittorrent/qBittorrent/pull/12102#issuecomment-603625682
unfortunately, [documentation](https://doc.qt.io/qt-5/qt.html#HighDpiScaleFactorRoundingPolicy-enum) lies slightly, required values type is not just `enum`, it is [`enum class`](https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/global/qnamespace.h?h=v5.14.1#n1757), so such …
> Don't round scaling factor

- src/base/net/private/downloadhandlerimpl.cpp
- src/base/net/private/downloadhandlerimpl.h
The m_reply has already changed parent in `DownloadHandlerImpl::assignNetworkReply()` and thus we can rely on Qt ownership to delete the object.
> Rely on Qt ownership to free resources

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
Message example:
```
SOCKS5 proxy error. Message: SOCKS5 error. op: hostname_lookup ec: Host not found (authoritative) ep: 127.0.0.1:42380
```
> Add logging for SOCKS5 proxy errors

- src/base/net/private/geoipdatabase.cpp
clang static analyzer was emitting some warning about uninitialized variable usage and this patch fixes it. IMO it is a good idea to have default values anyway.
> Initialize struct variables

- src/webui/www/private/index.html
- src/webui/www/private/scripts/client.js
Closes #12219.
Adds title and related alt to connectionStatus.
Adds alt and title to alternativeSpeedLimits.
Adds alt to speedLabel.
I was unable to compile qBittorrent on my machine successfully so I tested this using the "AlternativeWebUI" option in v4.2.1 on Linux Mint. Everything works as expected.
Note: I have seen `QBT_TR()` and `QBT_TR[CONTEXT=MainWindow]` used in alts but could not figure out what they were used for and if I need them.
> Added alt and title tags for WebUI footer

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/webui/api/appcontroller.cpp
- src/webui/www/private/views/preferences.html
This is a new setting added that is pending addition to
libtorrent 1.2.6. This setting is important because some routers do
not support expiration times on port-maps and do not return an error
either, silently failing. The previous default of permanent leases is
retained.
> Add UPnP lease duration advanced option

- src/base/bittorrent/session.cpp
Closes #12245.
Tested normal and portable mode, and automatic torrent management. Seems to be working fine. Let me know if I should test any other cases.
> Fix regression when fastresume contains network path

- src/app/application.cpp
Since the paths in Windows are case-insensitive, it was possible to create multiple instances for the same configuration, given a configuration path that is different only in case characters.
> Prevent multiple instances for the same app config

- src/base/bittorrent/session.cpp
There was some leftover code from the previous one in libtorrent-1.1 branch...
Closes #12322.
> Fix unexpected torrent resume after app restart

- src/webui/www/private/views/installsearchplugin.html
- src/webui/www/private/views/preferences.html
- src/webui/www/private/views/search.html
- src/webui/www/private/views/searchplugins.html
* Fix mismatch ID
* Remove redundant type attribute
It already defaults to `text/css` if value is absent (in HTML5).
> Fix mismatch ID

- src/gui/transferlistsortmodel.cpp
Closes #12330.
Just a damn typo! Strange that no one had noticed this before... Apparently, sub-sorting isn't so popular.
> Fix sub-sorting of Transfer list

- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/torrentcreatorthread.cpp
- src/base/bittorrent/torrentinfo.cpp
- src/base/utils/io.cpp
- src/base/utils/io.h
Previously we need a file buffer that is as large as the file size and this could be a problem when user has less free memory available or having very large data. Now with the help of `FileOutputIterator`,
we can have a much smaller, fixed size immediate file buffer and also the code looks nice with `lt::bencode()`.
> Avoid holding entire file in memory

- src/gui/mainwindow.cpp
- src/gui/powermanagement/powermanagement.cpp
- src/gui/powermanagement/powermanagement.h
* Clean up coding style
* Fix wrong logic that disables "prevent sleeping" timer
Also update power management state early so we don't need to wait for the timer timeout to have the effect.
> Fix wrong logic that disables "prevent sleeping" timer

- src/base/bittorrent/session.cpp
Libtorrent versions older than 1.2.6 have a bug when setting disk cache size to auto.
See https://github.com/arvidn/libtorrent/commit/6c880159c927f87ae4013e32023eb89a5336b5a4.
> Set disk cache size for older libtorrent versions

- src/base/utils/io.cpp
Since the class needs to be copy-constructible, there may be many copies of an instance. So instead of writing to the device on every destructor call, only flush buffer on the last destructor call.
> Avoid inefficient behavior

- src/base/bittorrent/session.cpp
Fixes https://github.com/qbittorrent/qBittorrent/issues/12421
> Fix outgoing interfaces not getting assigned in case addr is not null.

- src/base/utils/foreignapps.cpp
This PR modifies the functions that look for the path of the Python executable on Windows by adding a special case for when both Python 2 and Python 3 are installed on the system*. In such environments, it's very common that `python` will point to the Python 2 executable and `python3` will, of course, point to Python 3. In the past, the function would only look for `python.exe` files, hence trying to use the unsupported Python 2 executable.
This PR introduces the following changes:
- After querying the Python path from the registry, it will first try to look for `python3.exe`. If it can't find it, it will look for `python.exe`.
- Same thing happens when looking into the `C:/Python*` folder
- `Utils::ForeignApps::pythonInfo()` will first try to retrieve the location of the Python …
> Better Python path detection on Windows

- src/base/bittorrent/private/resumedatasavingmanager.cpp
- src/base/bittorrent/private/resumedatasavingmanager.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrenthandle.cpp
- src/gui/mainwindow.cpp
* Avoid holding encoded resume data in memory
Now it the encoded resume data will be streamed to file instead of a temporary buffer holding the whole of it.
* Suppress unused variable warning on macOS
* Fix header inclusion order
* Preallocate output buffer
> Avoid holding encoded resume data in memory 

- src/webui/www/private/addpeers.html
The wrong delimiter was used which prevented adding multiple peers at once.
> Fix add multiple peers from webui

- src/base/bittorrent/session.cpp
Fixes #12443
Follow up to https://github.com/qbittorrent/qBittorrent/pull/12430
@Chocobo1  @FranciscoPombal 
I have reproduced the problem on my machine verify that this pull request fixes the problem.
> Do not use 0.0.0.0 or [::] for outgoing interfaces

- src/base/bittorrent/session.cpp
*This timeout applies for tracker announce made during pausing of torrents as well as closing of the client.
A 1 second timeout is too low for an announce request to go through for some use cases. 
Specially when your network usage is high and latency is increased. or when you use a TLS secured tracker which requires at least 3 round trips due to the handshake. 
The default should be a bit higher to allow the announces to go through for most use cases. But not high enough to stall the client closing process.
This was probably set to 1 second thinking it would fix delayed exit issue that some users face. 
But even then, qBt takes 3-5 seconds on average to close due to waiting on some other threads(like asyn DNS queries).
5 seconds sound reasonable specially for private tracker users where …
> Change default stop_tracker_timeout settings

- .travis.yml
- src/base/bittorrent/private/nativetorrentextension.cpp
- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrentcreatorthread.cpp
- src/base/bittorrent/torrenthandleimpl.cpp
I had a little bit of trouble making the debian packaging scripts work on the raw libtorrent folder for the PPA. It seems to work now!!!
Additionally this PR forces the RC_1_1 code path to really use RC_1_1 package and not the RC_1_2 package (from the qbittorrent-stable ppa for xenial).
Both RC_1_1/RC_1_2 are with deprecated functions disabled. I believe this is what was asked a while back.
> TravisCI: Use libtorrent with deprecated functions disabled for Linux builds

- src/base/logger.cpp
- src/base/logger.h
Log::Msg originally takes 32 bytes, now shrinks to 24 bytes.
Log::Peer originally takes 40 bytes, now shrinks to 32 bytes.
> Reduce padding in structure

- src/webui/www/private/views/preferences.html
Add missing setProperty and getProperty calls for the new UPnP lease
duration setting.
Fixes 6b4925d222c4078b7ab77c7edcd433294746727d.
Closes #12566.
> WebUI: Fix UPnP lease duration get/set

- src/base/bittorrent/session.cpp
Follow up to https://github.com/qbittorrent/qBittorrent/issues/12253#issuecomment-607206151
> Use configured net interface even when it is missing

- src/base/preferences.cpp
- src/base/preferences.h
- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.ui
- src/webui/api/appcontroller.cpp
- src/webui/webapplication.cpp
- src/webui/webapplication.h
- src/webui/www/private/views/preferences.html
Screenshots: [GUI](https://user-images.githubusercontent.com/9395168/79990281-7397eb00-84e3-11ea-8e48-f9539c333e26.png), [WebUI](https://user-images.githubusercontent.com/9395168/79990803-13557900-84e4-11ea-899d-f1d3d5724e2d.png)
> Add ability to send custom HTTP headers

- src/base/bittorrent/session.h
Qt 5.9.5 doesn't seem to recognize it, this patch fixes it.
Fix up: d8401c76f568e463022dd653124e8c99f33d0020.
Related: #12601.
> Register datatype properly

- .travis.yml
- CMakeLists.txt
- cmake/Modules/FunctionQbtCXXCompilerAndModeCheck.cmake
- cmake/Modules/MacroQbtCompilerSettings.cmake
- src/CMakeLists.txt
The CMake part of the fix to https://github.com/qbittorrent/qBittorrent/issues/12437.
Basically, the idea is to detect if the compiler version or C++ mode is lower than the minimum required one as early as possible, and fail the build with a descriptive message in that case.
The only tricky thing about this is that _full_ compiler support for different C++ modes does not necessarily "align at the version boundary". Thus, we must:
- Check if the compiler claims to support the minimum required C++ mode at all;
- Enforce a minimum compiler version based on what the C++ mode compatibility matrices of each compiler[1] have to say about their _full_ support for the minimum required C++ mode.
This is my first attempt at a "big" CMake PR, let me know if I'm not using best practices, or if this is …
> CMake: Enforce minimum C++ mode support

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/webui/api/appcontroller.cpp
- src/webui/www/private/views/preferences.html
This commit adds a new libtorrent setting to validate HTTPS tracker certificates. When enabled, libtorrent will validate the certificate of HTTPS trackers against the system's certificate store. This option is only enabled on libtorrent versions >= 1.2.6 and on non-Windows systems, as OpenSSL does not use the system's certificate store on Windows.
> Add HTTPS tracker certificate validation option

- src/gui/advancedsettings.cpp
- src/webui/www/private/views/preferences.html
Network interface changes are applied on the fly. A restart is not required.
> Remove "requires restart" from network interface settings

- src/gui/transferlistmodel.cpp
> Show tooltip for torrent name in transfer list

- src/webui/www/private/views/search.html
Previously, the filters would collapse into a mostly-hidden, scrollable div. Now, we simply hide the more granular filters when running on a tiny screen.
Closes #11386.
Before:
After:
> Hide additional Web UI search filters on small screens

- .travis.yml
- CMakeLists.txt
In the process of merging https://github.com/qbittorrent/qBittorrent/pull/12480, I accidentally clobbered part of a commit from @sledgehammer999 that fixed the travis build (https://github.com/qbittorrent/qBittorrent/commit/5afe892226e4c6c57cd2a9fce8200e7d0b72b2ce). Sorry about that.
> Use latest CMake on TravisCI

- src/gui/addnewtorrentdialog.ui
- src/gui/optionsdialog.ui
- src/gui/properties/propertieswidget.cpp
- src/gui/torrentcategorydialog.ui
fixes build errors like that:
```
[ 34%] Building CXX object src/gui/CMakeFiles/qbt_gui.dir/categoryfiltermodel.cpp.o
cd /Users/nick/tmp/qBittorrent/build/src/gui && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DBOOST_ALL_NO_LIB -DBOOST_NO_CXX11_RVALUE_REFERENCES -DQBT_VERSION=\"v4.3.0alpha1\" -DQBT_VERSION_2=\"4.3.0alpha1\" -DQBT_VERSION_BUGFIX=0 -DQBT_VERSION_BUILD=0 -DQBT_VERSION_MAJOR=4 -DQBT_VERSION_MINOR=3 -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_MACEXTRAS_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_STRICT_ITERATORS -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_XML_LIB -DSTACKTRACE -I/Users/nick/tmp/qBittorrent/build/src/gui/qbt_gui_autogen/include -I/Users/nick/tmp/qBittorrent/src …
```
> Clean up header inclusion

- src/webui/www/private/views/search.html
Before:
After:
Normal screen (unchanged):
> Shrink Web UI search bar on small screens

- src/webui/api/searchcontroller.cpp
- src/webui/api/searchcontroller.h
- src/webui/webapplication.h
- src/webui/www/private/views/search.html
The Web UI's default "All categories" option used its translated name, rather than its id, as its value. This caused the option not to work when using other languages. Additionally, the Web UI only ever displayed search categories by their id, so they were never translated. Translated category names are now shown instead.
Closes #10239.
Before:
After:
**TODO**
> Fix Web UI search categories only working in English

- src/gui/uithememanager.cpp
- src/gui/uithememanager.h
following #12143 but this time we do it from JSON file(`:uitheme/config.json`)
json file 
```json
{
"colors": {
"Palette.Window": "#353535",
"Palette.WindowText": "white",
"Palette.Base": "#191919",
"Palette.AlternateBase": "#353535",
"Palette.Text": "white",
"Palette.ToolTipBase": "white",
"Palette.ToolTipText": "white",
"Palette.BrightText": "red",
"Palette.Highlight": "#2a82da",
"Palette.HighlightedText": "black",
"Palette.Button": "#353535",
"Palette.ButtonText": "white",
"Palette.Link": "#2a82da",
"Palette.LinkVisited": "darkgrey",
"Palette.Light": "#353535",
"Palette.Midlight": "#191919",
"Palette.Mid": "#191919",
"Palette.Dark": "darkgrey",
"Palette.Shadow": "grey",
"Palette.WindowTextDisabled": "#484848",
"Palette.TextDisabled": "darkgrey",
"Palette.ToolTipTextDisabled": …
```
> Allow setting application palette from config.json

- src/gui/properties/propertieswidget.cpp
- src/gui/properties/propertieswidget.h
- src/gui/properties/propertieswidget.ui
Before: 
New:
Disproportionate spacing don't look good.
> Align Properties Tabbar in center

- src/webui/api/serialize/serialize_torrent.cpp
- src/webui/api/serialize/serialize_torrent.h
- src/webui/api/synccontroller.cpp
- src/webui/www/private/index.html
- src/webui/www/private/scripts/client.js
- src/webui/www/private/scripts/dynamicTable.js
- src/webui/www/private/scripts/mocha-init.js
- src/webui/www/private/views/filters.html
This PR introduces Trackers to the Web UI sidebar. A map of trackers<>torrents is calculated server-side and included in `/sync/maindata`.
All GUI functionality has been implemented with the exception of two items:
1. Error and Warning trackers (requires a refactor to decouple tracker alerts from GUI code).
2. Tracker favicons (breaks our Content Security Policy)
Closes #7601.
GUI for comparison:
**TODO**:
> Add Trackers section to Web UI sidebar

- src/base/http/requestparser.cpp
- src/base/http/responsebuilder.cpp
- src/base/http/responsebuilder.h
- src/base/http/types.h
- src/webui/webapplication.cpp
- src/webui/webapplication.h
* Prebuild HTTP headers as much as possible
This avoids some branching when building a HTTP response.
* Define and use a proper HTTP header structure
* Rename function
* Define and use Http::HeaderMap type
> Prebuild HTTP headers

- src/webui/www/private/addtrackers.html
Hitting the enter button inside the textarea would submit the form, rather than advancing to the next line.
> Fix Enter button behavior in web UI textarea

- src/webui/webapplication.cpp
Errors lacking a custom message (e.g. 404) don't specify a `Content-Type` header, causing browsers to download the response. With this PR, the error will now be displayed properly.
> Specify Content-Type in Web API error responses

- src/gui/fspathedit.cpp
Today I updated to msvc 16.6  and start getting this error 
```
..\src\gui\fspathedit.cpp(130): error C2039: 'logic_error': is not a member of 'std'                                    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\memory(24): note: see declaration of 'std'                                                                                                      ..\src\gui\fspathedit.cpp(130): error C3861: 'logic_error': identifier not found                                        ..\src\gui\fspathedit.cpp(149): error C2039: 'logic_error': is not a member of 'std'                                    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\memory(24): note: see declaration of …
```
> Fix compilation error with msvc 16.6

- src/gui/rss/feedlistwidget.cpp
- src/gui/uithememanager.cpp
- src/gui/uithememanager.h
* Make the icon cache a class variable
* Make class variable const
* Avoid overuse of QStringLiteral
This code path doesn't look like frequently used.
> Improvements to UIThemeManager

- conf.pri.windows
This comes from my recent experience with https://github.com/qbittorrent/qBittorrent/issues/12357.
- ~Given that Windows is what it is, seems useless to support anything other than static builds there (this is the main reason this is a draft PR, it is a big change in something I'm not totally comfortable with)~
- The names of the crypto libs have changed; I also changed the name of the boost lib to not hardcode a specific version.
- ~We don't officially support any platforms that don't have OpenSSL >= 1.1 for some time now (when support for RC_1_1 is removed the other nearby `TODO` can be addressed).~
> Improve Windows qmake build configuration files

- src/webui/www/private/rename_file.html
Now select the full file name instead of the part before the first dot.
Before:
After:
> WebUI: Fix wrong file renaming selection range

- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/common.h
- src/base/bittorrent/customstorage.cpp
- src/base/bittorrent/customstorage.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrenthandle.h
- src/base/bittorrent/torrenthandleimpl.cpp
- src/base/utils/fs.cpp
- src/gui/previewselectdialog.cpp
- src/gui/torrentcontentmodelfile.cpp
- src/gui/torrentcontentmodelfolder.cpp
- src/gui/torrentcontenttreeview.cpp
- src/webui/api/torrentscontroller.cpp
Users often put completed files (obtained from another sources) in the torrent folder and perform "force recheck", but qBittorrent keeps proceed with incomplete ones before. Now it prefers files without ".!qb" extension when torrent is checking.
It is implemented via the extension of default torrent storage to make sure that operations with files are performed when they are released by libtorrent. An additional advantage is that file renaming also occurs in the disk thread.
"Find complete files" when moving torrent storage is scheduled to be implemented after merging this PR.
These PRs should close some of "checking"-related Issues, but I'm not sure exactly which ones, nor am I sure they will close these Issues completely, so I didn't link them here.
P.S. It doesn't support libtorrent-1.1 …
> Find complete files when checking torrent

- src/base/bittorrent/peerinfo.cpp
- src/base/bittorrent/peerinfo.h
The country lookup happens quite often when "Resolve peer countries" option is enabled.
> Cache country lookup result in PeerInfo class

- dist/unix/systemd/qbittorrent-nox@.service.in
`qBittorrenti` -> `qBittorrent`
Pretty inconsequential, but I've been staring at it for years and I finally decided to do something about it.
> Fix typo in systemd service file

- src/webui/www/private/views/preferences.html
To sync with GUI and most importantly to avoid confusion from the one-too-many reports like this https://github.com/qbittorrent/qBittorrent/issues/12955#issuecomment-637505734 in the future.
> Preselect "Default save path" in WebUI watched folders

- src/app/application.cpp
- src/app/cmdoptions.cpp
- src/base/algorithm.h
- src/base/net/smtp.cpp
- src/gui/properties/peerlistwidget.cpp
- src/gui/properties/proptabbar.cpp
- src/gui/search/searchwidget.cpp
- src/gui/transferlistfilterswidget.cpp
- src/gui/transferlistwidget.cpp
* Don't use deprecated QTextStreamFunctions::flush()
* Don't use deprecated QSet::iterator::operator+(int)
* Don't use deprecated QAbstractSocket::error()
* Don't use QWheelEvent deprecated functions
* Don't use deprecated QButtonGroup::buttonClicked()
* Don't use deprecated QUrl::topLevelDomain()
* Don't use deprecated QProcess::startDetached() overload
> Don't use functions deprecated in Qt 5.15 

- src/base/bittorrent/nativesessionextension.cpp
- src/base/bittorrent/nativesessionextension.h
libtorrent-2.0 introduced a type-safe alternative to void* (lt::client_data_t)
for passing user-data into plugins. qBT doesn't use any user data in its
plugins, but the signatures have changed nevertheless, and qBT need to update to
be compatible with libtorrent-2.0.
> support changes to plugin API in libtorrent-2.0

- src/base/bittorrent/torrentcreatorthread.cpp
to instead include libtorrent/file_storage.hpp, as that's the only think necessary in torrentcreatorthread.cpp.
libtorrent/storage.hpp defines `storage_interface` and `default_storage`, useful when defining a custom storage. This file doesn't define a custom storage though, it just needs `file_storage`
> Correct libtorrent header include in torrentcreatorthread.cpp

- src/webui/www/private/confirmfeeddeletion.html
- src/webui/www/private/confirmruleclear.html
- src/webui/www/private/confirmruledeletion.html
- src/webui/www/private/css/Tabs.css
- src/webui/www/private/index.html
- src/webui/www/private/newfeed.html
- src/webui/www/private/newfolder.html
- src/webui/www/private/newrule.html
- src/webui/www/private/rename_feed.html
- src/webui/www/private/rename_rule.html
- src/webui/www/private/scripts/client.js
- src/webui/www/private/scripts/contextmenu.js
- src/webui/www/private/scripts/dynamicTable.js
- src/webui/www/private/views/preferences.html
- src/webui/www/private/views/preferencesToolbar.html
- src/webui/www/private/views/rss.html
- src/webui/www/private/views/rssDownloader.html
- src/webui/www/webui.qrc
I have implemented the RSS reader and auto downloader in the reference WebUI. Requires API defined in #12549 and closes #12355.
Screenshots:
&nbsp;
Regarding localization: all used strings are in the same context as their desktop ui version. Is there an easy way to port the translations over?
Also the `renameRule` API seems to be broken. Since I couldn't figure out where the mistake lies I created an issue.
> Implemented RSS reader and auto downloader in reference WebUI

- src/base/bittorrent/customstorage.cpp
- src/base/bittorrent/customstorage.h
Provide the same behavior as #12884 but in case of moving storage to the place where complete files exist.
> Find complete files when moving torrent storage

- src/base/bittorrent/session.cpp
- src/base/rss/rss_autodownloader.cpp
> Fix RSS article is not marked as "read" when torrent is downloaded

- src/src.pro
Refer to the [qt.io](https://doc.qt.io/qt-5/configure-linux-device.html).
When cross-compiling the qt5, the `-hostprefix` can be used to separate host tools like qmake, rcc, lrelease and so on from the binaries for the target devices. In this situation, the `QT_HOST_BINS` and `QT_INSTALL_BINS` have different values and they are the same when `-hostprefix` is not specificed.
Therefore, I think we should use `QT_HOST_BINS` instead of `QT_INSTALL_BINS` in the following lines.
https://github.com/qbittorrent/qBittorrent/blob/37d7323ac0c8f6b444b48230ca40b75975c7485a/src/src.pro#L71-L72
Have compiled the source successfully on Linux and Windows.
> Improve qmake configuration file for cross compilation

- .travis.yml
- CMakeLists.txt
- INSTALL
- configure
- configure.ac
- src/app/qtlocalpeer/qtlockedfile.cpp
- src/app/qtlocalpeer/qtlockedfile.h
- src/base/bittorrent/customstorage.cpp
- src/base/bittorrent/customstorage.h
- src/base/bittorrent/infohash.cpp
- src/base/bittorrent/infohash.h
- src/base/bittorrent/nativesessionextension.cpp
- src/base/bittorrent/nativesessionextension.h
- src/base/bittorrent/nativetorrentextension.cpp
- src/base/bittorrent/nativetorrentextension.h
- src/base/bittorrent/peerinfo.cpp
- src/base/bittorrent/portforwarderimpl.cpp
- src/base/bittorrent/portforwarderimpl.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrentcreatorthread.cpp
- src/base/bittorrent/torrenthandleimpl.cpp
- src/base/bittorrent/torrenthandleimpl.h
- src/base/bittorrent/torrentinfo.cpp
- src/base/bittorrent/torrentinfo.h
- src/base/bittorrent/trackerentry.cpp
- src/base/utils/misc.cpp
> Bump requirement to libtorrent 1.2

- src/webui/www/private/scripts/prop-peers.js
It is used in file `prop-peers.js` as the follwing line.
https://github.com/qbittorrent/qBittorrent/blob/ca8654d380d3703d89c4b98528c3985a23d96330/src/webui/www/private/scripts/prop-peers.js#L146
However, the api is defined in `transfercontroller.cpp`.
https://github.com/qbittorrent/qBittorrent/blob/ca8654d380d3703d89c4b98528c3985a23d96330/src/webui/api/transfercontroller.cpp#L120
> WebUI: fix the url for banPeers method

- src/gui/transferlistdelegate.cpp
Fixes https://github.com/jagannatharjun/qbt-theme/issues/22
One can't specify stylesheet for progress bar inside a View
> Use global style options for drawing progress in TransferList

- src/gui/log/loglistview.cpp
Previously we get textRect from QStyle but on some OS this returns invalid rect
fixes https://github.com/qbittorrent/qBittorrent/issues/12698
> Use delegate provided rect for textRect in LogItemDelegate

- CMakeLists.txt
- src/app/application.cpp
- src/base/bittorrent/peerinfo.cpp
- src/base/bittorrent/peerinfo.h
- src/config.h.cmakein
- src/webui/api/synccontroller.cpp
Follow-up to the findings in https://github.com/qbittorrent/qBittorrent/pull/12746. This PR will either fix the support for the feature or remove it entirely, depending on the decision.
@qbittorrent/demigods @qbittorrent/bug-handlers @qbittorrent/frequent-contributors  opinions?
@Chocobo1 votes for removing it (https://github.com/qbittorrent/qBittorrent/pull/12746#issuecomment-654197260):
> `COUNTRIES_RESOLUTION` exists in cmake and source code but not in autotools. I would prefer we remove this define/configure option from our codebase.
Devil's advocate would say "well, we could add support in autotools as well".
Personally I don't care either way about the compile-time defines, we already have a runtime setting to manage this, and I'm fine with just that.
> Remove DISABLE_COUNTRIES_RESOLUTION define

- cmake/Modules/MacroQbtCompilerSettings.cmake
- src/CMakeLists.txt
Side Effect 1: halves the compile-time when compiled with boost version greater than 1.60
Side Effect 2: reduces compiler warnings noise generated from Qt headers
> CMake improvements

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrenthandleimpl.cpp
- src/base/bittorrent/torrenthandleimpl.h
- src/gui/transferlistwidget.cpp
1. Carefully handle results of each move job.
2. Change "save path" property only after move is complete.
3. Also add more logging to help user side debugging.
> Improve "move torrent storage" handling

- src/gui/properties/proplistdelegate.cpp
- src/gui/properties/proplistdelegate.h
This PR replaces uses of QItemDelegate with QStyledItemDelegate for content view in Properties widget, QItemDelegate doesn't play well with stylesheets and Qt guys recommend QStyledItemDelegate, One side effect is large row height (I personally likes it and this is the real motivation behind this PR) compare to previous on windows but if anyone wants to stay with previous row height, they can use the stylesheet anyway.
> Use QStyledItemDelegate for content views

- src/base/bittorrent/session.cpp
- src/base/utils/string.cpp
In fact, we no longer prevent to store resume data for torrents in checking state in all cases, except for one, when it should be stored periodically. There we have outdated code that doesn't make any sense now.
Bonus commit eliminates crash on app exiting due to incorrect handling of `thread_local` objects by MinGW.
> Always allow to save resume data in checking state

- src/base/bittorrent/torrenthandleimpl.cpp
We need to explicitly update torrent status when "move storage" is enqueued otherwise it will updated only with some another state update that can take long time (or it is even never caused for paused torrents).
> Update torrent status on move enqueued

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
Since https://github.com/arvidn/libtorrent/pull/4808 got merged libtorrent now checks for file size mismatches for torrents added with Skip Hash. 
Now torrents get paused with a missing files error if files are missing when added with skip hash. 
So calling read_piece() is no longer necessary.
> Read piece for torrents added with skip hash only for older libtorrent

- src/base/bittorrent/addtorrentparams.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrenthandleimpl.cpp
- src/base/bittorrent/torrenthandleimpl.h
- src/gui/categoryfiltermodel.cpp
- src/gui/mainwindow.cpp
- src/gui/tagfiltermodel.cpp
- src/gui/torrentcreatordialog.cpp
- src/gui/transferlistfilterswidget.cpp
- src/gui/transferlistmodel.cpp
In short, a slightly deep redesign of everything related to torrent loading and "resume" data generation.
Here are some goals:
1. Deleted a lot of deprecated code.
2. Refactor a lot of code in order to further separate the paths of adding a new torrent from restoring an existing one (the shared code remained at the final stage, before adding the torrent to the libtorrent session).
3. Make torrent handle to store `add_torrent_params` it was added to libtorrent session with and update it when appropriate. It allows to correctly save resume data under some circumstances, e.g. in "missing files" state (although we tried to prevent this from being done earlier, the user could actually do it when, for example, changing some property of such a torrent).
> Improve torrent loading code

- src/gui/torrentcreatordialog.ui
As to prevent the dialog from going out-of-screen on a small monitor.
This PR is expected to supersede PR #13259.
Screenshot:
> Add a scroll area to torrent creator dialog

- src/webui/www/private/views/preferences.html
I was looking for bugs for issue #13267, but I didn't find any.
Those are just some coding style fixes while reviewing the related code.
Before:
After:
> Fix seeding time checkbox placement in WebUI

- src/gui/mainwindow.cpp
Hi!
I hope this was the correct way to implement it, it worked perfectly on Mac. I missed an easy way to open the statistics on the current qBittorrent so I hope you guys will merge this.
By the way, ``CTRL + I`` is consistent with VLC's more information & codec information shortcuts.
Thanks
> Add CTRL + I keyboard shortcut to open statistics (command + I on Mac)

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/webui/api/appcontroller.cpp
- src/webui/www/private/views/preferences.html
This PR exposes the LibTorrent Peer Turnover Settings in qBT Advanced Settings in order to allow users to adjust how frequently slow and uninteresting connections are closed to allow potentially better / faster connections to be made.
The default settings are to turnover peers when the number of connections is at least 90% of allowed global or per torrent connections, and to disconnect the least attractive 4% of these connections every 5 minutes.
See https://www.libtorrent.org/reference-Settings.html#peer_turnover
> Expose LibTorrent peer_turnover settings

- src/base/utils/string.h
- src/gui/properties/propertieswidget.cpp
- src/gui/properties/propertieswidget.h
Previously, if double click on the Size number in torrent content tab the path would be an incorrect value and as such open path functionality won't work, this commit fixes it.
> Fix open path won't work correctly

- src/gui/properties/propertieswidget.cpp
- src/gui/properties/propertieswidget.h
- src/gui/utils.cpp
Previously that action is the same as "Open" action which is wrong behavior, it should be opening the parent folder instead. The wrong behavior is observed on nautilus 3.36.3 and nemo 4.6.5.
> Fix "Open containing folder" opened the wrong path for folder item

- src/base/net/geoipmanager.cpp
Closes #13318.
---
The linked bug report provides an example with an Arabic system locale. The date was being formatted according to the system locale, so in this case, qBittorrent was attempting to download the database file from the following download URL, which includes the date in an Arabic script: `https://download.db-ip.com/free/dbip-country-lite-٢٠٢٠-٠٩.mmdb.gz`.
To fix it, force the date formatting to be done against the `C` (POSIX) locale.
> Fix GeoDB download in systems with non-C locales

- src/base/bittorrent/filterparserthread.cpp
- src/base/bittorrent/session.cpp
This PR improves compatibility with libt 2.0 but does *not* aim to fix all compile errors (there are many and non-trivial). IMO it would be better to slice the "supporting libt 2.0" work into smaller steps and this PR is one of them.
* Add helper function to convert to string from lt::socket_type_t type
* Migrate away from deprecated `address::from_string()`
* Migrate away from deprecated `address::to_string(error_code)`
The other overload require users to handle exceptions themselves.
> Improve compatibility with libt 2.0

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/webui/api/appcontroller.cpp
- src/webui/www/private/views/preferences.html
User may want to set higher value for faster client exit -> reference https://github.com/arvidn/libtorrent/pull/4620#issuecomment-626575180
User may want to set lower value to prevent timeouts/errors due to announcing too fast/file descriptor limits.
More info:
https://libtorrent.org/single-page-ref.html#max_concurrent_http_announces
>name | type | default
>-- | -- | --
>max_concurrent_http_announces | int | 50
>
>limits the number of concurrent HTTP tracker announces. Once the limit is hit, tracker requests are queued and issued when an outstanding announce completes.
> Expose libtorrent max_concurrent_http_announces in advanced settings

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/addnewtorrentdialog.cpp
- src/gui/addnewtorrentdialog.h
Don't re-use existing torrent handle created for preloading metadata. Just delete it and add torrent in a regular way to make logic clearer.
Additionally it fixes the issue when redundant notification about torrent moving is shown.
> Improve adding torrent using Magnet URI

- src/base/bittorrent/session.cpp
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/webui/www/private/views/preferences.html
* Disable deprecated libtorrent settings
* Initialize session with `session_params` class
The old way of initialization is deprecated in libtorrent 2.0.
* Move enums into anonymous namespace
* Move signal connections to appropriate place
> Disable deprecated settings in libtorrent 2.0

- src/base/bittorrent/session.cpp
In libtorrent > 2.0, the setting is turned off by default, now we just re-enable it to preserve the behavior as in earlier versions.
Upstream PR: https://github.com/arvidn/libtorrent/pull/5129
> Enable faster disk space allocation by default

- src/base/bittorrent/session.cpp
`char const* socket_type_name(socket_type_t);` is decided to be not exported and thus it is internal: https://github.com/arvidn/libtorrent/pull/4859/files#r452925563
> Avoid using libtorrent internal functions

- INSTALL
- src/base/utils/foreignapps.cpp
- src/gui/mainwindow.cpp
Previous versions are unsupported by Python => https://en.wikipedia.org/wiki/History_of_Python#Table_of_versions
And by us => https://github.com/qbittorrent/search-plugins
> Update minimum Python version to 3.5.0

- src/gui/mainwindow.cpp
Someone mentioned it will be possible to set a message in the tooltip's subtext in Qt6 (in which, some basic HTML is allowed (for icons)) but i can't find any info on it, https://doc-snapshots.qt.io/qt6-dev/qsystemtrayicon.html doesn't mention any overload for `QSystemTrayIcon::setToolTip()` unless they meant something else. If someone can verify i'll leave a TODO for Qt6 in the code.
If there is another way to set subtext in tooltip, i don't know it and i won't be looking for it so... merge this before the next release if no one else looks into this issue.
> Don't use HTML in Linux tray tooltip

- src/base/CMakeLists.txt
This should have been there from the start,
but for some reason, the lack of it didn't cause any issued
for many systems.
---
~WIP. For now just want to see the CI result.~ all good
> CMake: fix linking against OpenSSL

- cmake/Modules/MacroQbtCommonConfig.cmake
- src/CMakeLists.txt
* Don't impose unnecessary compile options on users
This is unexpected for users that take single job compilation as the default (which is always the case since forever). Users can change the default if they wish to use multicore for compilation.
* Remove compile requirement for boost::system
boost::system is not a dependency for our project.
* Set compression rate for rcc targets
This follows our current setting in src.pro.
> Improvements to cmake build system

- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrenthandleimpl.cpp
- src/base/bittorrent/torrenthandleimpl.h
Always store firstLastPiecePriority in resume data.
Don't recalculate firstLastPiecePriority value each time it is accessed.
Always store sequentialDownload in resume data as native libtorrent field.
> Improve sequentialDownload/firstLastPiecePriority handling

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/webui/api/appcontroller.cpp
- src/webui/www/private/views/preferences.html
Don't hardcode lt::settings_pack::no_connect_privileged_ports. We support the peer alert for it already, so connections blocked by this setting should be logged without any further changes.
> Allow users to configure no_connect_privileged_ports

- src/base/bittorrent/session.h
Link to [fully-qualified-moc-types](https://github.com/KDE/clazy/blob/master/docs/checks/README-fully-qualified-moc-types.md)
> Fix fully-qualified-moc-types clazy warning

- .github/workflows/ci.yaml
- Ubuntu 18.04/20.04, GUI ON/OFF
- Windows 2019
- macOS 10.15 GUI ON/OFF
---
~Depends on ~https://github.com/qbittorrent/qBittorrent/pull/12746~ https://github.com/qbittorrent/qBittorrent/pull/13327 (it's rebased on top of that one).~ `master` is now ready for this.
- The workflow runs on pushes to master or any events from PRs that target master.
- It takes 10 to 15 minutes to complete if cached.
The very first time around (or if the caches are dropped due to not being used for a week) there will be no caches. Without caches, it takes 1:30 to 3 hours.
- It's quite readable and maintainable: only ~230~ 240 lines for all OS/GUI combinations we currently have in CI, plus Ubuntu 20.04, which we currently don't have. It does not depend in any way on packages/archives from builds.shiki.hu. All …
> Add GitHub Actions CI workflow

- .github/workflows/ci.yaml
- CMakeLists.txt
This was default before CMake overhaul, and it doesn't
make sense to use static builds with daily developement.
Also static Qt builds are not readily available on Windows.
> By default use dynamic runtime with MSVC on CMake

- src/gui/properties/speedplotview.cpp
previously for duration other than 1 minute, graphs will always leave some space to the left side.
> Correctly fill whole width of graph

- cmake/Modules/MacroQbtCommonConfig.cmake
${qBittorrent_VERSION} will expand to a string that ends with build number but version string from qMake doesn't end with build number
> Fix CMake generated qBittorrent's version string 

- src/app/cmdoptions.cpp
- src/base/bittorrent/tracker.cpp
https://github.com/qbittorrent/qBittorrent/pull/13431 superseded https://github.com/qbittorrent/qBittorrent/pull/13425, so here are some other fixes - it no longer makes sense to follow Clazy's `fully-qualified-moc-types` recommendation.
https://github.com/KDE/clazy/blob/master/docs/checks/README-qstring-arg.md (carried over from the previous PR)
https://github.com/KDE/clazy/blob/master/docs/checks/README-qstring-insensitive-allocation.md (new)
> Clazy fixes

- src/base/bittorrent/torrentcreatorthread.cpp
- src/base/bittorrent/torrentcreatorthread.h
- src/gui/torrentcreatordialog.cpp
- src/gui/torrentcreatordialog.h
- src/gui/torrentcreatordialog.ui
This option is only available when qbt is built with libtorrent >= 2.0.
Some options are removed since libtorrent 2.0 deprecated them.
[Screenshot](https://user-images.githubusercontent.com/9395168/95658758-5b7a5d80-0b4f-11eb-858d-d0a57d05e584.png)
> Add support for creating v2 torrents

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/webui/api/appcontroller.cpp
- src/webui/www/private/views/preferences.html
This PR exposes libtorrent 2.0 configuration option `lt::settings_pack::hashing_threads` to a UI so that user can configure the number of hashing threads. This parameter is ignored by libtorrent prior to v2.
Here is the relevant part from [the official migration guide](https://www.libtorrent.org/upgrade_to_2.0-ref.html):
> aio_threads and hashing_threads
>
> In previous versions of libtorrent, the number of disk threads to use were configured by `settings_pack::aio_threads`. Every fourth thread was dedicated to run hash jobs, i.e. computing SHA-1 piece hashes to compare them against the expected hash.
>
> This setting has now been split up to allow controlling the number of dedicated hash threads independently from the number of generic disk I/O threads. `settings_pack::hashing_threads` …
> Add option for hashing_threads setting 

- CONTRIBUTING.md
- src/base/profile_p.cpp
Any reason to use on Linux the unusual path
```
~/.local/share/data/qBittorrent
```
instead of
```
~/.local/share/qBittorrent
```
?
> Don't create 'data' subdirectory on Linux

- src/gui/search/searchwidget.cpp
- src/gui/search/searchwidget.h
Adds a MiddleClickTabBar, which is a QTabBar which allows for the middle
click to close tabs. Also adds CloseableTabWidget, which is a QTabWidget
which uses the MiddleClickTabBar.
Closes #7905
Addresses #5628
Addresses #2581
> Enable the use of middle-click to close tabs

- src/webui/www/private/views/rss.html
The implementation before only stipped script tags which could result in RSS feeds like [this](https://pastebin.com/raw/yjhnWq7L) still executing code in the users browser. By placing the description in an sandboxed iframe that is no longer possible.
> Place WebUI RSS description in sandboxed iframe

- CMakeLists.txt
The version number is hardcoded in CMakeLists.txt now as well
> CMake: Bump version number

- src/webui/www/private/views/preferences.html
IIRC in the PR for "Disallow connection to peers on privileged ports" it was requested several times to change the name of the option and i guess this was forgotten.
Closes #13598
> Fix toggling advanced option in WebUI

- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/customstorage.cpp
- src/base/bittorrent/customstorage.h
- src/base/bittorrent/ltqhash.h
- src/base/bittorrent/torrenthandleimpl.cpp
`customstorage.h` has `QHash<lt::storage_index_t, StorageData> m_storageData;` and the compiler is complaining no suitable `qHash()` is found.
Only "Move qHash helper for libtorrent types to its own file" is related to improving libtorrent 2.0 support, other commits are just clean ups.
> Move qHash helper for libtorrent types to its own file

- src/webui/api/serialize/serialize_torrent.cpp
- src/webui/api/serialize/serialize_torrent.h
- src/webui/webapplication.h
> Expose contentPath in WebAPI torrents/info

- src/webui/api/synccontroller.cpp
- src/webui/www/private/views/preferences.html
The IPv6 addresses transfered to WebUI are not using the format `[ip]:port` and can't be parsed correctly, so that the IPv6 address can't be banned.
https://github.com/qbittorrent/qBittorrent/blob/66f0e6a8f27ca320cbb0febe88589548c04c40b8/src/webui/api/synccontroller.cpp#L553
The ban action doesn't depend on the ipfilter, and should not be disabled when ipfilter is not enabled.
Edit:
Add the screenshots of changes for WebUI 
Before:
After:
> Fix the issue that IPv6 address can't be banned

- .github/workflows/ci.yaml
Should fix all of the ```Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/``` warnings we've been getting on CI runs and prevent total breakage in the future.
EDIT:
See:
https://github.com/ilammy/msvc-dev-cmd/releases/tag/v1.4.1
https://github.com/lukka/run-vcpkg/releases/tag/v4.1
Other version bumps were just regular updates/maintenance releases.
No annotations :tada: https://github.com/qbittorrent/qBittorrent/actions/runs/327272055
> Update GitHub Actions CI actions versions

- src/base/bittorrent/nativetorrentextension.cpp
- src/base/bittorrent/nativetorrentextension.h
- src/base/bittorrent/torrenthandleimpl.cpp
Closes #13576.
Closes #13635.
Requires libtorrent >= 1.2.4 (but I didn't change build system projects, because we were still going to increase it to 1.2.10 or even 1.2.11 if it was released before the next release of qBittorrent).
> Don't resume "paused" torrents when put into "checking" state by libtorrent

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
mingw64 defines interface, so revert back to previous naming scheme
Fixes: 87864531ab747b10094b4e0efc32ea80c586b6b9
Closes #13649
> Fix mingw64 build error

- src/base/bittorrent/nativetorrentextension.cpp
- src/gui/torrentcontentmodelitem.h
@glassez 
Is `isPaused()` going to be used in the future? If yes, let me know and I'll ignore it.
> Suppress compiler warnings

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
- src/base/bittorrent/torrenthandleimpl.cpp
- src/base/bittorrent/torrenthandleimpl.h
- src/gui/transferlistmodel.cpp
- src/gui/transferlistwidget.cpp
- src/webui/api/serialize/serialize_torrent.cpp
- src/webui/api/torrentscontroller.cpp
I am continuing my series of changes to make the "backend abstraction layer" even more abstract, which should help resolve existing problems due to differences between libtorrent and qBittorrent interfaces.
In particular, libtorrent pauses/resumes torrents for various needs, but it is often inconvenient for us to directly translate the internal state to the user side and even take some actions depending on it (e.g. store resume data). From a user perspective, only the state that was set from here matters at all.
> Handle torrent "paused" state at application level

- src/gui/rss/automatedrssdownloader.ui
- src/webui/www/private/views/rssDownloader.html
Change date notation from
**2017.01.01 and 01.01.2017**
to
**2017.12.31 and 31.12.2017**
to prevent confusion between "MM" and "DD".
@glassez This pull request should be only one commit. I used squash in my own fork on GitHub, using separate branches. This seems to work in the online editor, but needs some preparation on my side. I closed my previous pull request because some stuff went wrong and reverting commits creates new commits... so.
> Fix confusion in date format description

- .github/workflows/ci.yaml
- .github/workflows/file_health.yaml
> Using the specific major action version allows you to receive critical fixes and security patches while still maintaining compatibility. It also assures that your workflow should still work.
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses
> Pin github actions scripts to major versions

- src/gui/torrentcontentfiltermodel.cpp
- src/gui/transferlistsortmodel.cpp
In torrent transfer list we should use underlying data for sorting, not displayed values.
Closes #13818.
> Fix wrong data used for comparison

- .travis.yml
The default version is so outdated that it needs to rebuild many dependencies. Now we bump it to the latest version so that it can use prebuilt packages.
> Update to use latest macOS image for TravisCI

- src/base/bittorrent/session.cpp
I discovered this by accident and due to the architectural changes from 4.2.5 to 4.3.0.
In my setup the value of `removingTorrentDataIter->pathToRemove` ended up being the root of my drive (eg `G:\`). Hence `smartRemoveEmptyFolderTree` started scanning the whole drive and qbt froze.
This affects magnets only.
For multifile torrents that are saved in the root of a drive without a toplevel folder the value of `removingTorrentDataIter->pathToRemove` is empty. For singlefile torrents the value is the entire path containing the single file too.
> Don't try to remove folders for a torrent without metadata

- src/webui/api/torrentscontroller.cpp
- src/webui/webapplication.h
Adds an optional (some may say `missing`) field to `/torrents/add` WebAPI endpoint.
Both no-tag and with-tags cases are tested manually. The change works as intended.
> WebAPI: allow to attach tags while adding torrents

- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/filesearcher.cpp
- src/base/bittorrent/filesearcher.h
- src/base/bittorrent/infohash.cpp
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrenthandleimpl.cpp
- src/base/bittorrent/torrenthandleimpl.h
- src/gui/addnewtorrentdialog.cpp
- src/gui/properties/propertieswidget.cpp
- src/gui/transferlistmodel.cpp
These are fixes, improvements and cleanups that I made along the way to solve the problem of processing the received metadata (still in progress).
They have an independent value, so I don't want them to wait for the main part to finish.
For testers:
It should correctly find existing files (both with and without .!qb extensions, and located in a temporary folder if there are no files in the main folder) when adding a torrent. In other words, it should behave like a master, except that the files are searched in a separate thread. If there are a large number of files in the torrent, it may cause a certain interval between adding the torrent and the moment when it appears in the list (instead of hanging the interface in the master).
Please also note if there are any regressions.
> Find existing files in separate thread

- src/base/bittorrent/session.cpp
Fixup 0c3fe54b0ba25c8f24fe50a41cf7ab797d53932f
---
I had not tested https://github.com/qbittorrent/qBittorrent/pull/13894 on Ubuntu 18.04 (it has Qt 5.9.5), only on other systems which all had Qt >= 5.10.
Torrents were silently failing to load, with this message being printed to terminal:
```
QMetaObject::invokeMethod: No such method FileSearcher::search(InfoHash,QStringList,QString,QString)
Candidates are:
search(BitTorrent::InfoHash,QStringList,QString,QString)
```
Luckily, as the message implies, the fix is trivial.
> Fix method invocation on Qt < 5.10

- .github/workflows/ci.yaml
- .travis.yml
- CMakeLists.txt
- INSTALL
- configure
- configure.ac
- m4/qbittorrent.m4
- src/CMakeLists.txt
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrenthandleimpl.cpp
- src/gui/advancedsettings.cpp
It doesn't make sense to allow anything lower (our floor at the moment is what the Ubuntu 18.04 repository has).
Also,
Closes https://github.com/qbittorrent/qBittorrent/issues/13510
> Bump minimum dependency versions

- src/base/bittorrent/nativetorrentextension.cpp
- src/base/bittorrent/nativetorrentextension.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrenthandleimpl.cpp
- src/base/bittorrent/torrenthandleimpl.h
This is a reincarnation of the last attempt to fix/improve received metadata handling (#13736).
Now torrent is reloaded internally once metadata is received to correctly apply all needed logic of preprocessing torrent content and finding probably existing files left from previous incomplete download.
Right now, detecting existing files should work the same regardless of how the torrent is added (using .torrent file or Magnet link).
Also, the implemented mechanisms should serve as a basis for future improvements in other aspects (for example, resuming "Missing files" torrent downloads without rechecking).
> Fix received metadata handling

- src/base/bittorrent/infohash.cpp
- src/base/bittorrent/infohash.h
- src/base/torrentfilter.cpp
- src/base/torrentfilter.h
- src/gui/mainwindow.cpp
- src/gui/transferlistfilterswidget.cpp
- src/gui/transferlistfilterswidget.h
- src/gui/transferlistsortmodel.cpp
- src/gui/transferlistsortmodel.h
- src/gui/transferlistwidget.cpp
- src/gui/transferlistwidget.h
- src/webui/api/torrentscontroller.cpp
This is a prerequisite clean up before further transition into new v2 info hash.
For testers:
It is not expected that this PR will break any existing use case. Please look for regressions in tracker filters widgets.
> Use the correct type when referring to info hash

- src/base/bittorrent/infohash.cpp
- src/base/bittorrent/infohash.h
- src/base/utils/version.h
- src/gui/transferlistsortmodel.cpp
Another idea would be manually define a custom comparison function for QVariant. However, having the function would be excessive due to its limited usage count, also note that we are already casting various QVariant to its underlying type in existing code.
Relevant discussion: https://github.com/qbittorrent/qBittorrent/pull/13937#issuecomment-741923331
> Migrate away from deprecated QVariant comparison operators

- configure
- configure.ac
Before this commit, autotools will inject `-g -O2` to debug build (`--enable-debug=yes`) and rendering the result binary useless. This
commit fixes it.
https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.70/html_node/C_002b_002b-Compiler.html
Closes #14032.
> Don't use default CFLAGS, CXXFLAGS from autotools

- src/base/bittorrent/cachestatus.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/statsdialog.cpp
- src/gui/statsdialog.h
- src/webui/api/synccontroller.cpp
* Initialize stat indices to -1
When the index is initialized it will be set to a number >= 0, so we use -1 to denote its uninitialized status.
* Don't use removed stat metric in libtorrent 2.0
For now, the metric is not entirely removed due to WebAPI still needs to access it.
* Use a helper function to look up stat index
> Don't use removed stat metric in libtorrent 2.0

- src/app/upgrade.cpp
- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrentcontentlayout.h
- src/base/bittorrent/torrenthandle.h
- src/base/bittorrent/torrenthandleimpl.cpp
- src/base/bittorrent/torrenthandleimpl.h
- src/base/bittorrent/torrentinfo.cpp
- src/base/bittorrent/torrentinfo.h
- src/base/rss/rss_autodownloader.cpp
- src/base/rss/rss_autodownloadrule.cpp
- src/base/rss/rss_autodownloadrule.h
- src/base/settingvalue.h
- src/base/utils/string.h
- src/gui/addnewtorrentdialog.cpp
- src/gui/addnewtorrentdialog.ui
- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.ui
- src/gui/rss/automatedrssdownloader.cpp
- src/gui/rss/automatedrssdownloader.ui
- src/webui/api/appcontroller.cpp
- src/webui/api/torrentscontroller.cpp
- src/webui/webapplication.h
- src/webui/www/private/download.html
- src/webui/www/private/scripts/download.js
- src/webui/www/private/upload.html
- src/webui/www/private/views/rssDownloader.html
Implement 3 torrent content layouts:
1. <del>Default</del> Original (follow original layout from torrent metadata)
2. Subfolder (create subfolder for torrent content regardless of original content layout)
3. NoSubfolder (don't create subfolder for torrent content regardless of original content layout)
Closes #12833.
> Improve content root folder handling

- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/abstractfilestorage.cpp
- src/base/bittorrent/abstractfilestorage.h
- src/base/bittorrent/torrenthandle.h
- src/base/bittorrent/torrenthandleimpl.cpp
- src/base/bittorrent/torrenthandleimpl.h
- src/base/bittorrent/torrentinfo.h
- src/base/utils/fs.cpp
- src/gui/properties/propertieswidget.cpp
- src/gui/torrentcontenttreeview.cpp
- src/webui/api/torrentscontroller.cpp
- src/webui/api/torrentscontroller.h
- src/webui/www/private/rename_file.html
- src/webui/www/private/scripts/file-tree.js
- src/webui/www/private/scripts/filesystem.js
- src/webui/www/private/scripts/prop-files.js
Closes #12328.
Supercedes #13081.
> Improve content file/folder names handling

- src/webui/www/private/scripts/download.js
Fixed a regression where the script tries to access elements that no longer
exist on the page, because they were replaced with others by a previous change.
Closes #14092.
Sorry, the structure of the Web application is alien to me (besides, I believe that qBittorrent web application is not designed in the best way), so it is difficult for me to clean up here. It would be easier if someone maintain it, but we still don't have a web developer.
Not sure if it would be better, continue trying to propagate with grief in half the main changes in WebUI, or just leave it without any care.
> Don't call non-existent elements (part 2)

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/mainwindow.cpp
- src/gui/mainwindow.h
It also drops notification about move storage failed. But it looks like it's more important so it might make sense to leave it out. If so, I'll delete the second commit from this PR.
Closes #13643.
> Drop notification about move storage finished

- .gitignore
- CMakeLists.txt
- cmake/Modules/MacroQbtCommonConfig.cmake
- src/app/CMakeLists.txt
- src/app/application.cpp
- src/app/main.cpp
- src/app/stacktracedialog.cpp
- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrentcreatorthread.cpp
- src/base/net/dnsupdater.cpp
- src/base/version.h.in
- src/gui/aboutdialog.cpp
- src/gui/mainwindow.cpp
- src/gui/programupdater.cpp
- src/qbittorrent.rc
- src/webui/api/appcontroller.cpp
- version.pri
The basic idea is we create a version header template at "src/base/version.h.in" and the build systems are expected to replace
strings that are enclosed with @ symbols and generate "src/base/version.h" for other source files to consume/include.
> Generate version header when configuring project

- src/gui/torrentcontentmodel.cpp
Only set editable flag on item's where editing is handled in the delegate.
Closes #13515.
> Correctly set items flags in TorrentContentModel 

- configure
- configure.ac
It increases compatibility with older qt versions.
This targets the `v4_3_x` branch.
> Use c++1z to enable c++17

- src/gui/torrentoptionsdialog.cpp
- src/gui/torrentoptionsdialog.h
These files were created and edited in their entirety in commit 8db4bde
As far as I can tell they were almost entirety rewritten from their original state.
The old copyright attribution is restored and the new author is added too.
> Correct copyright attribution

- src/base/bittorrent/torrentinfo.cpp
Try to detect whether generated content folder name contains extension
and drop it to avoid possible conflicts between file/folder names.
Closes #14193.
> Drop extension from generated content folder name

- src/gui/trackerentriesdialog.ui
it makes no sense to accept tab characters in that text field _and_ I'd like there to be a way to get out of that dialog purely using the keyboard.
> Allow tab to escape the text box in "Edit trackers" dialog

- src/gui/mainwindow.cpp
Closes #14217
Previous:
`"Already Using the Latest qBittorrent Version"`
ref: https://github.com/qbittorrent/qBittorrent/issues/14217#issue-785556411
This PR:
`"qBittorrent"`
> From Qt docs (https://doc.qt.io/qt-5/qmessagebox.html#details):
> 
> > The _Microsoft Windows User Interface Guidelines_ recommend using the **application name** as the **window's title**.
> Change title of "version update" dialog box

- src/gui/mainwindow.cpp
- src/gui/mainwindow.h
- src/gui/optionsdialog.cpp
- src/gui/properties/propertieswidget.cpp
* Disable translation of program name
* Don't let "program update" dialog steal focus
And also avoid creating an unnecessary event loop.
Closes #14250.
* Enlarge "speed limit" icon slightly
[screenshot](https://user-images.githubusercontent.com/9395168/105131305-a24efa80-5b23-11eb-8525-00ca02070e21.png)
> Don't let "program update" dialog steal focus

- src/webui/webapplication.h
#13995 was supposed to be included in the release along with other API changes, so both PRs had a version change to 2.7.0. However, it ended up in another release, and I forgot to upgrade the version again.
Unfortunately, it is unlikely to fix a problem like #14266, but at least it will fix it for users of intermediate/test builds.
@qbittorrent/bug-handlers, what do you think?
> Bump WebAPI version

- src/gui/torrentcontenttreeview.cpp
We hook our own actions on double click. Fixes #14269
> Disable expand on double click in TorrentContentTreeView

- AUTHORS
- src/gui/aboutdialog.ui
- src/gui/translators.html
- src/webui/www/private/views/about.html
#12609 addresses an issue where the Hungarian translator desires to be removed from list. The author also suggests linking Transifex team to each language, but upon research unless you join the language team you cannot get access to information regarding team members. 
Instead, I decided to add hyperlink to Transifex word on the introduction, which would redirect the user to the link to the qBittorrent Transifex dashboard (https://www.transifex.com/sledgehammer999/qbittorrent/) on both GUI and WebUI.
> Update translator tab on About

- src/gui/transferlistsortmodel.cpp
This makes the behavior of sorting by TR_SEED_DATE consistent.
> Reuse existing code for sorting

- .github/workflows/ci.yaml
- .github/workflows/file_health.yaml
After dropping "edited" keyword, it is the same as the default.
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
> Don't trigger Github Actions CI builds after editing a PR's opening post

- src/base/bittorrent/session.cpp
Currently if there are torrents with MissingFiles state, qBittorrent will prevent system from sleeping draining battery to zero even though nothing is actually downloading.
> Don't inhibit system sleep if all active torrents are errored

- src/gui/transferlistsortmodel.cpp
- src/gui/transferlistsortmodel.h
This drops all sub-sorting code paths and maintain the stable sorting property instead.
For example, user click on one column to sort it first and then click on a second column to sort it again, the values that are compared equal in the second column will preserve the order the previous sorting result.
> Use stable sorting in transfer list

- src/base/bittorrent/abstractfilestorage.cpp
Fixes regression introduced by #13995.
Closes #14341.
> Allow change-case-only file renaming on Windows

- src/base/bittorrent/torrent.cpp
- src/gui/transferlistmodel.cpp
* Show proper string when torrent availability is not available
* Clean up coding style
* Apply "Hide zero values" to "Time Active" column
* Apply "Hide infinity values" to "Down/Up Limit" columns
* Apply "Hide infinity values" to ETA column
> Show proper string when torrent availability is not available

- src/gui/rss/automatedrssdownloader.cpp
- src/gui/rss/automatedrssdownloader.h
- src/gui/rss/automatedrssdownloader.ui
- src/gui/torrentcategorydialog.cpp
#7629 suggests adding a button to add new category when creating a new automated RSS downloader rule. I think it's a pretty nice idea and straightforward to implement. When a new category is added, the rule's category is auto-selected to the created category. `TorrentCategoryDialog` class is reused to handle the logic.
I'm planning to make the same update on the WebUI in a following PR.
> Add category button on AutomatedRSSDownloader

- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.h
I found these while finding a way to disable save button if input field is empty for #14327. 
1. Rather than using a `for-loop` on the button box to find the apply button, we can directly find it using `button` method. 
2. Likewise, `applySettings` method can directly have signal on the apply button rather than on the button box, then using an `if` conditional to match the clicked button to be the apply button. I am not certain if there will be a side-effect on directly attaching the signal on the button, so please let me know.
3. It is clearer to define the type of the `m_applyButton` to be `QPushButton` than `QAbstractButton`. `QAbstractButton` is the abstact base class for numerous button types, including `QCheckBox`, `QPushButton`, `QRadioButton`, and `QToolButton`. I think there is …
> Refactor apply button logics on options dialog

- src/gui/properties/speedplotview.cpp
- src/gui/properties/speedplotview.h
- src/gui/properties/speedwidget.cpp
Previously SpeedPlotView assumed speed is updated per seconds but the the default value was 1500ms and this can be further changed by the user, this caused a lot of duplicate data in the calculation of the graph points. Now Averager averages based on the target duration, resolution and also takes into account when actual data has arrived.
Also improved resolution of 6-hour graph, previously it was same as 12
hour graph
Partially supersedes https://github.com/qbittorrent/qBittorrent/pull/13263
> Make SpeedPlotView averager time aware

- dist/unix/systemd/qbittorrent-nox@.service.in
My torrents reside on a USB HDD. qbittorrent sometimes starts before the HDD completes mounting, so qbittorrent errors out thinking the files are missing.
This change to the bundled qbittorrent systemd service file makes systemd wait until fstab filesystems are finished mounting before starting qbittorrent.
`local-fs.target` is a [special systemd target](https://www.freedesktop.org/software/systemd/man/systemd.special.html#local-fs.target) which is marked finished when fstab filesystems are mounted.
> Systemd: wait for mounting of local filesystems

- .github/FUNDING.yml
Closes  #14355.
See: [screenshot](https://user-images.githubusercontent.com/9395168/107869759-74fc2f00-6ecc-11eb-87da-a5005f650d1e.png)
The repository name in the screenshot is just an example, it will be the current repo name once merged.
And note that although the sponsor button will appear, we won't really be participating in Github Sponsors program due to reasons (e.g. org registration/taxes, Sponsors program not available in some countries).
> Enable sponsor button on Github

- src/app/main.cpp
- src/base/preferences.cpp
- src/base/preferences.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
Add an advanced setting for enabling or disabling icons in context menus. Defaults to enabled.
This makes it possible to better integrate qBittorrent in GTK based DEs on Linux.
Here's what it looks like with the adwaita-qt theme:
Left: Menu icons enabled, Right: Menu icons disabled.
Closes #3297.
> Add an option to disable icons in menus

- src/webui/www/private/confirmfeeddeletion.html
- src/webui/www/private/confirmruleclear.html
- src/webui/www/private/confirmruledeletion.html
- src/webui/www/private/newfeed.html
- src/webui/www/private/newfolder.html
- src/webui/www/private/rename_feed.html
- src/webui/www/private/rename_rule.html
It can be reproduced if we rename the RSS feed names to encoded string by the WebUI, such as `%D1%82%D0%B5%D1%81%D1%82` (`тест` in Russian). Then the renamed feeds can't been deleted/renamed again.
This is because the URL has been decoded once by the function `getdata()`. It will make something wrong if the original encoded strings are encoded once and decoded twice.
> WebUI: Properly decode strings

- .github/workflows/ci.yaml
- .travis.yml
- CMakeLists.txt
- INSTALL
- configure
- configure.ac
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/advancedsettings.cpp
- vcpkg/libtorrent/CONTROL
- vcpkg/libtorrent/no_use_iconv.patch
- vcpkg/libtorrent/portfile.cmake
- vcpkg/libtorrent/readme.md
libtorrent is updated:
https://github.com/arvidn/libtorrent/releases/tag/v1.2.12
https://github.com/arvidn/libtorrent/releases/tag/v2.0.2
> Raise minimum libtorrent version to 1.2.12 (2.0.2)

- src/gui/progressbardelegate.cpp
Now the background of progress bar is drawn correctly:
Before this PR:
Closes #12271.
Addresses #14464 partially.
> Correctly draw the background of progress bar

- .travis.yml
- src/gui/mainwindow.cpp
In homebrew `qt` package is referring to Qt6 instead of Qt5.
> Fix TravisCI macOS builds

- src/app/stacktrace_win.h
Pass application directory as PDB search path in SymInitialize.
Otherwise it searches in application working directory so when you run qBittorrent with working directory other than its installation one it can't find qbittorent.pdb file and produces broken stacktrace.
> Look for qbittorrent.pdb in installation directory

- src/base/bittorrent/magneturi.cpp
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrent.h
- src/base/bittorrent/torrentimpl.cpp
- src/base/bittorrent/torrentinfo.cpp
- src/base/bittorrent/torrentinfo.h
- src/base/bittorrent/trackerentry.cpp
- src/base/bittorrent/trackerentry.h
- src/gui/properties/trackerlistwidget.cpp
- src/gui/properties/trackersadditiondialog.cpp
- src/gui/trackerentriesdialog.cpp
- src/gui/trackerentriesdialog.h
- src/gui/transferlistfilterswidget.cpp
- src/gui/transferlistfilterswidget.h
- src/webui/api/synccontroller.cpp
- src/webui/api/torrentscontroller.cpp
Make TrackerEntry a regular structure that serves to provide data about the current state of interaction with some tracker. It's still used also for some other jobs where just tracker URL (and probably tier) is enough so it's better to change this logic in future.
Move all the data conversion (i.e. filling TorrentEntry structure) to TorrentImpl class, and make all conversion only once when creating an instance of TrackerEntry.
Provide data for each local endpoint separately. For now, keep the summary data inside the TrackerEntry structure, but intend to remove it from here so that the caller summarises it itself if it needs to (or just displays it separately for each endpoint).
> Improve tracker entries handling

- src/base/bittorrent/torrentimpl.cpp
This avoids a forced status update when creating torrent instance, but simply fills in individual fields from the add torrent params (the remaining fields are not so important until the first regular update). This should speed up the start of the session a bit.
> Initialize torrent status from add torrent params

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrentimpl.cpp
Eliminate cases of multiple resume data overwrites, where multiple properties of the same torrent are changed sequentially in a single event. 
Plus, I don't filter out stopped torrents explicitly when saving regularly, but rely on their `need_save_resume_data` property, so if we missed something, it will have a chance to be saved.
> Improve "save resume data" handling

- INSTALL
- src/gui/transferlistdelegate.cpp
- src/gui/transferlistmodel.cpp
- src/gui/transferlistmodel.h
Transfer list screenshot:
@qbittorrent/bug-handlers 
Any comment on this visual change?
> Show progress bar in disabled state for paused torrents

- src/webui/api/serialize/serialize_torrent.cpp
- src/webui/api/serialize/serialize_torrent.h
- src/webui/www/private/scripts/dynamicTable.js
- src/webui/www/private/scripts/misc.js
- src/webui/www/private/scripts/prop-general.js
- Add seeding time to the active time column in WebUI (like it is in GUI)
- Fix incorrect seeding time string in WebUI General tab
- Allow >100 days in WebUI function "friendlyDuration" (and make the statement above the function actually true)
Closes #14526
> Seeding time in WebUI

- src/app/qtlocalpeer/qtlocalpeer.cpp
- src/base/rss/rss_autodownloadrule.cpp
- src/base/rss/rss_parser.cpp
- src/base/utils/string.cpp
- src/base/utils/string.h
- src/gui/properties/propertieswidget.cpp
- src/gui/rss/automatedrssdownloader.cpp
- src/gui/search/searchjobwidget.cpp
- src/gui/torrentcontentfiltermodel.cpp
- src/gui/transferlistwidget.cpp
- src/webui/webapplication.cpp
Now wildcard filters follow closely the definition of wildcard for glob patterns. The backslash (\) character is not an escape char in this context. In order to match one of the special characters, place it in square brackets (for example, [?]). So it should be mentioned in release notes.
P.S. This makes current codebase more compatible with Qt 6.
> Use QRegularExpression instead of deprecated QRegExp

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrentimpl.cpp
- src/base/bittorrent/torrentimpl.h
Provide all the "resume data" in raw form, which will allow to save it in different ways in the future, for example, in SQLite database driven storage (WIP).
> Wrap "resume data" in LoadTorrentParams

- src/base/rss/rss_parser.cpp
In Qt6 calling `QHash::operator[]` can invalidate previously assigned references to its nodes.
> Don't cause QHash relayout while using reference to its node

- src/gui/trackerentriesdialog.ui
I'm terribly sorry. I must have been asleep while pushing commits for my last pull request.
The XML of the "Edit trackers" dialog should say `<property...` but it said `<attribute...`
This is to fix that.
> Fix tabChangesFocus attribute in "Edit trackers" dialog

- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/bencoderesumedatastorage.cpp
- src/base/bittorrent/bencoderesumedatastorage.h
- src/base/bittorrent/resumedatastorage.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrentimpl.cpp
- src/base/bittorrent/torrentimpl.h
Finish moving the "resume data" saving logic to "resume data storage":
1. Saving metadata
2. Managing IO thread
The logic itself keeps mostly unchanged.
Test cases are add/restore/remove torrent both from .torrent files and magnet links.
> Improve ResumeDataStorage

- src/base/bittorrent/torrentimpl.h
Otherwise it won't compile if libtorrent uses deprecated features since there are different namespaces declared.
> Correctly forward declare file_prio_alert

- .github/workflows/ci.yaml
Since we need to backport some changes and produce artifacts for testing.
> Enable Github Actions CI for other branches

- AUTHORS
- COPYING
- src/gui/gpl.html
- src/webui/www/private/views/about.html
Regarding this license clarification there are 3 commits of interest
(commits A, B, C). Before commit A the COPYING file contained only the
text of the GPLv2 license, while all source files had a license block
at the top saying that they are under the terms of "GPLv2 or later". With
commit A there was a temporary change to GPLv3. The COPYING file contained
only the text of the GPLv3 license, while all source files had a license
block at the top saying that they are under the terms of "GPLv3 or later".
Then with commit B the COPYING file and the license block of the source
files was reverted to their state before commit A. Afterwards, with
commit C a license summary(or clarification) block was put at the top of
the COPYING file. This block indicated that the license was GPLv2 without …
> Clarify that the license is GPLv2+

- src/gui/properties/speedplotview.cpp
This reverts commit 435bb3443507dd224b3579dbb4ba5657dc5cc8fa.
To achieve what the reverted commit wants, the timing
would need to be taken iteratively rather that cumulatively
fixes #14735
> Revert "Change clamping of update interval of SpeedPlotView::Averager"

- src/app/application.cpp
- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/torrentcreatorthread.cpp
- src/base/utils/compare.cpp
- src/base/utils/compare.h
- src/base/utils/string.cpp
- src/base/utils/string.h
- src/gui/addnewtorrentdialog.cpp
- src/gui/categoryfilterproxymodel.cpp
- src/gui/categoryfilterproxymodel.h
- src/gui/properties/peerlistsortmodel.h
- src/gui/rss/automatedrssdownloader.cpp
- src/gui/search/searchsortmodel.cpp
- src/gui/search/searchsortmodel.h
- src/gui/tagfilterproxymodel.cpp
- src/gui/tagfilterproxymodel.h
- src/gui/torrentcontentfiltermodel.cpp
- src/gui/torrentcontentfiltermodel.h
- src/gui/transferlistfilterswidget.cpp
- src/gui/transferlistsortmodel.cpp
- src/gui/transferlistsortmodel.h
- src/gui/transferlistwidget.cpp
Now the comparison function/class should be constructed before usage.
This change also make it easier to plug in into various containers which will require a compare function type (such as std::set).
> Simplify natural sort classes interface

- src/webui/api/torrentscontroller.cpp
- src/webui/webapplication.h
> Allow to specify file indexes in `torrents/files` API

- src/base/net/dnsupdater.cpp
The old register url for dyndns (`https://account.dyn.com/dns/dyndns/add.html`) is broken.
Replace with [a new link](https://account.dyn.com/dns/dyndns/add.html).
> Update dyndns register url

- dist/mac/Info.plist
- src/app/CMakeLists.txt
display 'q**B**ittorrent' (uppercase 'B') instead of 'q**b**ittorrent' (lowercase 'b') in application menu
before fix:
after fix:
> Don't use executable name as CFBundleName value

- src/base/bittorrent/torrent.h
- src/base/bittorrent/torrentimpl.cpp
- src/base/bittorrent/torrentimpl.h
- src/base/bittorrent/trackerentry.h
- src/gui/properties/trackerlistwidget.cpp
- src/webui/api/torrentscontroller.cpp
1. Don't overwrite tracker message.
2. Provide tracker's peers count via TrackerEntry (don't more expose additional accessor in Torrent interface).
> Improve "tracker entries" handling

- src/base/bittorrent/torrentimpl.cpp
If torrent failed to write, it stops downloading and goes to "upload mode" instead of errored state so it just keeps seeding.
Now qBittorrent indicates this state as "errored" and allows the user to manually bring the torrent out of this state.
> Correctly handle "not enough disk space" error (v4_3_x backport)

- dist/mac/Info.plist
- src/app/CMakeLists.txt
backport https://github.com/qbittorrent/qBittorrent/pull/14811 to v4_3_x
just cherry-picked 29e6b229ac7b5f717202cd9ed3e824c7ba7328bf
> Don't use executable name as CFBundleName value (v4_3_x backport)

- dist/mac/Info.plist
- src/app/CMakeLists.txt
Info.plist has ${MACOSX_DEPLOYMENT_TARGET} placeholder which is filled
by qmake, but not CMake. And as result, when building with CMake value
of LSMinimumSystemVersion field is '.0'. This happens because CMake has
possibility to substitute placeholders with values from corresponding
variables, and as so as there is no such variable, empty value is used.
So, to fix this, just set CMake variable MACOSX_DEPLOYMENT_TARGET to
CMAKE_OSX_DEPLOYMENT_TARGET value.
no fix, master as is:
with fix, this branch:
P.S> maybe it is worth to set `CMAKE_OSX_DEPLOYMENT_TARGET` explicitly in root CMakeLists.txt instead of passing it to command line each time (especially when 10.14 is **required**)? similar thing is done for qmake:
https://github.com/qbittorrent/qBittorrent/blob/c7c7924d37f225f1be345037cf757cf …
> Set correct minimum macOS version with CMake

- src/gui/progressbarpainter.cpp
fixes #14731
backports https://github.com/qbittorrent/qBittorrent/pull/14840
> Correctly draw progress background with stylesheet (backport v4_3_x)

- src/CMakeLists.txt
- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/bencoderesumedatastorage.cpp
- src/base/bittorrent/dbresumedatastorage.cpp
- src/base/bittorrent/dbresumedatastorage.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrent.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/src.pro
It is available as "experimental" advanced option.
Existing "resume data" is transferring in selected storage once you start qBittorrent with changed option.
libtorrent native "resume data" is stored in bencoded form in single database column to simplify first implementation. Actually we don't need to split it into separate columns until we really implement some improvements that need such data layout. But since until then we can't have an accurate idea of what kind of layout and data format of individual columns we will need, it is completely useless to do any kind of separation now.
> Allow to store "resume data" in SQLite database file

- src/base/bittorrent/trackerentry.h
This is to suppress the following compilation warnings:
```
base/bittorrent/magneturi.cpp: In constructor ‘BitTorrent::MagnetUri::MagnetUri(const QString&)’:
base/bittorrent/magneturi.cpp:87:60: warning: missing initializer for member ‘BitTorrent::TrackerEntry::message’ [-Wmissing-field-initializers]
87 |         m_trackers.append({QString::fromStdString(tracker)});
```
https://travis-ci.org/github/qbittorrent/qBittorrent/jobs/768355867#L5519
> Initialize struct members by default

- src/gui/addnewtorrentdialog.cpp
Currently, adjusting the priority on multiple files through the context menu when adding a new torrent results in a one item menu, the only purpose of which is to get to another menu.
It appears this is a byproduct of having additional options when only one file is selected.
The proposed change is to get straight into the priority options on right click when multiple files are selected, improving the usability.
The single selection behaviour remains unchanged.
uTorrent has a similar approach, which seems to be more convenient.
> Show priority menu at top level if there is no other

- src/icons/build-icons/package.json
This fixes CVE-2020-7729
Github link to the CVE: https://github.com/advisories/GHSA-m5pj-vjjf-4m3h
This was alerted by github's "dependabot" autoscan of the repo.
> Update grunt dependency

- src/base/bittorrent/dbresumedatastorage.cpp
- src/base/settingsstorage.cpp
- src/gui/properties/piecesbar.cpp
- src/gui/properties/piecesbar.h
* Move initial values to header
* Fix typo
* Throw the exact (same) exception
* Fix potential data race
This case could be considered benign however it could still be an undefined behavior to the compiler, so remove it.
Ref:
https://hacks.mozilla.org/2021/04/eliminating-data-races-in-firefox-a-technical-report/
> Fix potential data race

- src/app/qtlocalpeer/qtlocalpeer.cpp
- src/app/qtlocalpeer/qtlocalpeer.h
Test on Windows and Linux (Ubuntu 20.04 LTS).
> Remove the lockfile on exit

- cmake/Modules/MacroQbtCommonConfig.cmake
---
See this comment onward in the libtorrent issue tracker: https://github.com/arvidn/libtorrent/issues/5114#issuecomment-740586691.
Basically, this prevents deprecation warnings due to erroneous values of the `__cplusplus` macro on MSVC. See https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/ for more info. The only reason this is not default is because otherwise it would break legacy code relying on MSVC to always setting this to the same value.
I realize the commit title might not be the best, open to suggestions.
> CMake: fix MSVC __cplusplus

- src/gui/transferlistsortmodel.cpp
- src/gui/transferlistsortmodel.h
Fixes #15073
Sub-sorting now works like in most grids where sub-sorting is a thing (except there is still no indication in UI).
Sub-sorting column tracked from `sort()` method that is called exactly once per view sort unlike `lessThan()` so it is a bit cleaner now too.
This complements earlier work done in https://github.com/qbittorrent/qBittorrent/pull/14423
> Keep sub-sorting order

- src/gui/transferlistwidget.cpp
- src/gui/tristateaction.cpp
- src/gui/tristateaction.h
- src/gui/tristatewidget.cpp
- src/gui/tristatewidget.h
The issue was resolved by using QAction::toggled signal instead of QAction::triggered. The latter is documented to cause QMenus to close. Per [the manual](https://doc.qt.io/qt-5/qmenu.html):
> Widgets can be inserted into menus with the QWidgetAction class. Instances of this class are used to hold widgets, and are inserted into menus with the addAction() overload that takes a QAction. If the QWidgetAction fires the triggered() signal, the menu will close.
Verified working with qtbase 5.15.2.
> Don't close tags menu when toggling items. Closes #13492

- .github/workflows/ci.yaml
- CMakeLists.txt
- INSTALL
- configure
- configure.ac
- src/base/bittorrent/torrentimpl.h
- Also update vcpkg to latest commit: includes libtorrent 1.2.14,
Qt 5.15.2, and Qt 6.1.1
---
Split from https://github.com/qbittorrent/qBittorrent/pull/15090.
> Raise minimum libtorrent version to 1.2.14 (2.0.4)

- src/base/torrentfileswatcher.cpp
> Don't forget to start "watch timer"

- src/base/bittorrent/ltunderlyingtype.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrentcreatorthread.cpp
- src/base/bittorrent/torrentimpl.cpp
* Use `underlying_type` member directly
`LTUnderlyingType` served as a intermediate type for libtorrent 1.1 and 1.2 and is obsoleted now.
Also add helper to convert to underlying type.
* Reserve space for vector
> Use `underlying_type` member directly

- src/gui/macutilities.mm
- src/gui/properties/trackerlistwidget.cpp
- src/webui/www/private/scripts/dynamicTable.js
* Add tooltip for various columns
Those strings sometimes are quite long and having a tooltip would save the action of resizing the column width to see the full message.
The WebUI already has it done for all columns.
* Simplify initialization statement
* Don't use old style casts
Ref: https://github.com/qbittorrent/qBittorrent/runs/2996702005?check_suite_focus=true#step:8:298
> Add tooltip for various columns

- src/base/bittorrent/torrentimpl.cpp
- src/gui/properties/peerlistwidget.cpp
- src/gui/torrentcontentmodel.cpp
* Add tooltip for "client ID" column
Sometimes the client ID could be quite long and this patch helps showing it.
* Display tooltip for all columns in torrent content widget
It is primary useful for showing long file names.
* Suppress type narrowing warning on MSVC
Fix up 45e31a1.
> Add tooltip for more widgets

- src/gui/properties/propertieswidget.cpp
- src/gui/properties/propertieswidget.h
Addresses #5848.
- Implementation derived from [peer list widget](https://github.com/qbittorrent/qBittorrent/blob/9bfc74a1bcf1420ea0393ffbafe5057cae4f37e4/src/gui/properties/peerlistwidget.cpp#L178-L221)
- WebUI already has this functionality
- The cols >= 1 check is removed because "Name" column cannot be hidden
> Add context menu to toggle content tab columns

- src/base/torrentfileswatcher.cpp
- src/gui/watchedfoldersmodel.cpp
`QDir::canonicalPath()` performs unnecessary actions (for example, resolves symbolic links) that we don't really need. But at the same time, it returns an empty string if the path does not exist, which can lead to unexpected behavior.
Closes #15156.
> Properly create "clean path" for watched folder

- src/webui/www/private/scripts/dynamicTable.js
- src/webui/www/private/scripts/prop-files.js
This PR adds Web UI support for navigating tables via arrow keys. It works on all tables that use `DynamicTable` (torrents, peers, trackers, files, search results, etc). This brings the Web UI behavior closer to matching the GUI.
https://user-images.githubusercontent.com/8296030/125153229-295e5200-e107-11eb-90d9-25e17f5a2bcc.mov
> Support navigating Web UI tables with arrow keys

- src/webui/www/private/scripts/mocha-init.js
This allows the system to properly encode the '|', instead of passing the '|' on in the URL, which is not allowed and breaks proxies such as Authelia.
Then, for the purpose of generalization, I pushed this pattern through to all places where we join items with a '|'.
This comes with the caveat that when we have individual components which contain a '|' or any other character that is not allowed per the HTTP standard, we still like to encode the individual components, for example in the case of 3 strings, separated by a '|'. If we don't do this we run into the risk that upon decoding URI finds '|' in our original strings, which is something we don't want.
For example:
Sender:
````javascript
const arr = ["foo|1", "bar|2"];
const uri = new URI("test.html").setData(arr.join("|"));
````
Then …
> Use the URI's setData to set query data

- src/base/bittorrent/torrent.h
- src/base/bittorrent/torrentimpl.cpp
- src/gui/transferlistmodel.cpp
- src/webui/api/serialize/serialize_torrent.cpp
- src/webui/www/private/scripts/dynamicTable.js
ATM there is no distinction between `downloading metadata` forced or not.
This PR introduces the new state `ForcedDownloadingMetadata`, completing the forced states: `ForcedDownloading` and `ForcedUploading`.
TODO:
> Add "Forced metadata downloading" state

- src/base/bittorrent/bencoderesumedatastorage.cpp
- src/base/bittorrent/bencoderesumedatastorage.h
- src/base/bittorrent/dbresumedatastorage.cpp
We can no longer save valid torrent files in the general case, because for torrents of version 2, we need a full merkle tree to do it, but if a torrent is added from magnet link, full merkle tree may not be available even before the end of downloading all the data.
Actually, we don't need the full torrent file for the purposes of resuming the torrent, so we can allow libtorrent to produce only a minimal part of the metadata as part complete resume data, but we still want to store it in a separate file, so we extract the resulting metadata from the complete resume data before saving and merge it together before loading.
> Store minimal metadata for "restore torrent" purposes

- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrentimpl.cpp
Fixes #11450.
To repro the problem or test this PR you can:
1. Add a magnet link (don't wait for metadata, close the dialog and return to the transfer list)
2. Wait for metadata
3. Query `api/v2/torrents/files?hash=64a980abe6e448226bb930ba061592e44c3781a1` and check `priority` field
You can use this link:
`magnet:?xt=urn:btih:64a980abe6e448226bb930ba061592e44c3781a1&dn=ubuntu-21.04-desktop-amd64.iso&tr=https%3a%2f%2ftorrent.ubuntu.com%2fannounce&tr=https%3a%2f%2fipv6.torrent.ubuntu.com%2fannounce`
> Set default file priorities when not specified

- .github/workflows/ci.yaml
- update vcpkg to latest commit (includes Boost 1.76)
Closes #15244.
> GitHub Actions CI: update workflow

- src/app/upgrade.cpp
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/settingsstorage.cpp
- src/base/settingsstorage.h
- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.ui
- src/webui/api/appcontroller.cpp
- src/webui/www/private/views/preferences.html
* Use default property for widgets
* Revise checkbox label for "Use any available port" functionality
Also reorder the checkboxes a bit.
[screenshot](https://user-images.githubusercontent.com/9395168/126934588-88a99f1d-d1b2-41aa-bd0a-0ea1e9bf100d.png)
* Use spinbox special value to represent "Use any available port"
WebAPI functionality is preserved (deprecated) for now and should be removed in the future.
[screenshot](https://user-images.githubusercontent.com/9395168/127268378-fcfb4013-7a08-4fca-94bb-3ddb75130a23.png)
> Use spinbox special value to represent "Use any available port"

- src/webui/www/private/scripts/misc.js
`rel=noopener` results in [better performance](https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/) and [security for untrusted links](https://mathiasbynens.github.io/rel-noopener/). Implicit in very-up-to-date browsers, but people still use older browsers through embedded webviews in apps and devices. `rel=noreferrer` ever so slightly enhances user privacy.
> Disconnect comment links fom the WebUI

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/webui/api/appcontroller.cpp
- src/webui/www/private/views/preferences.html
I exposed the [ssrf_mitigation](http://libtorrent.org/reference-Settings.html#ssrf_mitigation) option of libtorrent both in the client and in the webUI.
> when enabled, tracker and web seed requests are subject to certain restrictions.
>An HTTP(s) tracker requests to localhost (loopback) must have the request path start with "/announce". This is the conventional bittorrent tracker request. Any other HTTP(S) tracker request to loopback will be rejected. This applies to trackers that redirect to loopback as well.
I checked on Windows and after deactivating this option I was able to connect to trackers using passkey i.e ``http://tracker.notworking.com:8080/PassKeyGoesHere/announce`` with an HTTP proxy running locally.
Probably closes #14260
> Expose SSRF mitigation

- conf.pri.windows
- configure
- configure.ac
- src/CMakeLists.txt
- src/base/bittorrent/customstorage.cpp
- src/base/bittorrent/customstorage.h
- src/base/bittorrent/infohash.cpp
- src/base/bittorrent/infohash.h
- src/base/bittorrent/magneturi.cpp
- src/base/bittorrent/nativesessionextension.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrentcreatorthread.cpp
- src/base/bittorrent/torrentcreatorthread.h
- src/base/bittorrent/torrentimpl.cpp
- src/base/bittorrent/torrentimpl.h
- src/base/bittorrent/torrentinfo.cpp
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/gui/downloadfromurldialog.cpp
- src/gui/statsdialog.cpp
- src/gui/torrentcreatordialog.cpp
- src/gui/torrentcreatordialog.h
* Add compile definition to indicate using of libtorrent 2.0
The compile definition is temporary which will be removed when qbt ditches libtorrent 1.x.
Part of code is adopted from https://github.com/qbittorrent/qBittorrent/pull/15242#issuecomment-889026909.
> Add compile definition to indicate using of libtorrent 2.0

- src/base/bittorrent/magneturi.cpp
Partially fixes #15287
I am also working on hiding the padding files but the solution is a bit involved. So I made this PR as standalone.
> Accept v2 infohashes for download

- .github/workflows/stale_bot.yaml
Stale bot will mark stale PR with a tag and close them after a specified interval of time.
Draft PRs are not subject to this marking.
> Introduce stale bot for PR

- .github/workflows/coverity-scan.yml
Now that TravisCI is gone we have to use it manually.
The good thing is that this now can be automated. Previously we had to manually run it by pushing into the `coverity_scan` branch.
Last run is from 2019-09-26. Yikes.
> Run Coverity once per month

- README.md
Unfortunately Freenode, after a takeover, decided to purge all their databases, thus
deleting all channel and user registrations, without a warning.
So if we're forced to re-register our stuff why not go where the cool kids are at?
> Change IRC channel to Libera.Chat

- .github/workflows/stale_bot.yaml
Previously only [28 PR are scanned per run](https://github.com/qbittorrent/qBittorrent/runs/3286243181?check_suite_focus=true#step:2:9922), this commit attempt to handle all open PR at once.
Another repo that has similar count of issues/PR utilize a larger number than this PR:
https://github.com/Automattic/wp-calypso/blob/trunk/.github/workflows/mark-issue-stale.yml#L34
However the proposed value (`200`) is already sufficient for handling all PR, see my previous "debug-only" run results: 
https://github.com/qbittorrent/qBittorrent/runs/3287536111?check_suite_focus=true#step:2:44016
> Stale bot: Handle more PR per run

- src/gui/fspathedit.cpp
- src/gui/optionsdialog.ui
- src/webui/www/private/views/preferences.html
* Use the same icon for selecting folders/files
As stated in Qt doc, the `QStyle::SP_DialogOpenButton` is only for a button within QDialogButtonBox which means it isn't suitable elsewhere.
* Use default upper limits for ddns entries
The default is 32767 which is larger than the previous artificial limit.
* Use default values for inconsequential fields
Or when the default value is actually what we want.
* Add tooltip to listening port spinbox
> Minor UI revise

- .github/workflows/ci.yaml
- .github/workflows/coverity-scan.yml
- .github/workflows/file_health.yaml
- .github/workflows/webui_ci.yaml
* Clean up Github workflows' name
* Add proper indention to steps section
Following the style from the examples in https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps
* Use latest Ubuntu images
Jobs in those workflows has little to do with specific OS version, so just use the latest.
* Split commands to multiple lines properly
* Avoid using legacy backticks
https://github.com/koalaman/shellcheck/wiki/SC2006
* Rename jobs 
* Use nodejs lts version for CI
The exact nodejs version isn't critical here, just make sure it isn't too outdated.
----
Screenshot:
(Ignore the Qt6 branch, it was from other PR)
> Clean up workflow files coding style

- .github/workflows/ci.yaml
* Support libtorrent v2.0.4 in CI
* Remove OS variable from build matrix
It is meaningless to build on multiple linux versions as we only depend on library versions, not OS versions.
Also remove redundant "shell default" section.
* Move global environment variables out
* Use ccache in CI
> Support libtorrent v2.0.4 in CI

- .github/workflows/ci_windows.yaml
This will save maintenance work on the vcpkg version.
Also a few other improvements:
* Add quotes to path
* Sort command flags
* Avoid switching shell, always use powershell (the default shell)
> GHA CI: Use preinstalled vcpkg

- src/base/bittorrent/torrentimpl.cpp
- src/base/bittorrent/torrentimpl.h
Until libtorrent provided an "old_name" field in `file_renamed_alert` we relied on a workaround with storing old file names to remove empty leftover folders.
> Use "old file path" provided by libtorrent

- src/qbittorrent.exe.manifest
We no longer support Windows Vista, so removed it's GUID from the manifest file.
> Remove Windows Vista support from manifest

- dist/unix/systemd/qbittorrent-nox@.service.in
The default was [90s](https://www.freedesktop.org/software/systemd/man/systemd-system.conf.html#DefaultTimeoutStartSec=), prolong to 30 mins. 
From the discussion in https://github.com/qbittorrent/qBittorrent/issues/15381#issuecomment-912080617, ~2k torrents took 5 mins to completely shutdown. Here we wait at most 30 mins which scales to about 12k torrents which should cover most use case (also note that 4.3.x series is mentioned to have even shorter shutdown time).
Setting it to `infinity` isn't a good idea since that would potentially stall the system if anything go wrong.
> Prolong wait time for shutdown

- src/gui/properties/peerlistwidget.cpp
- src/gui/properties/trackerlistwidget.cpp
- src/gui/search/searchjobwidget.cpp
- src/gui/torrentcontenttreeview.cpp
- src/gui/transferlistwidget.cpp
Minimizing columns no longer truncates text from the left, now elides
text from the right for better readability. Done by setting
textElideMode to Qt::TextElideRight for header (and columns, for
consistency).
Closes #14419.
Untruncated
Before
After
> Fix issue #14419, column header truncation

- src/webui/www/private/css/style.css
- src/webui/www/private/scripts/prop-general.js
- src/webui/www/private/views/properties.html
I use the WebUI mostly and I miss having the pieces progress bar show the status of each piece like in the GUI. I wanted the feature so I implemented it just on a local clone of this repo. Then I searched the current issues and found #15292 so I thought I'd submit a PR.
I initially used a bunch of `<div>`s for each piece but the quality of that was poor and it often looked like there were more pieces completed than in reality. So I changed it to use a `<canvas>` and it looks nicer and is more accurate.
I don't know much about the translations, so I'm not sure if there is anything else I need to do for that. I ran the `tstool.py` script, but it added several changes besides just my new addition. Not sure if all those changes should be submitted in this PR or not, just let me know and I can …
> Add pieces progress bar to General tab in the WebUI

- src/base/bittorrent/torrentinfo.cpp
- src/base/rss/rss_autodownloadrule.cpp
- src/gui/raisedmessagebox.h
* Prevent self-assignment in assignment operator
* Use Qt macro to disable various constructors
> Prevent self-assignment in assignment operator

- .github/workflows/coverity-scan.yml
- src/base/utils/gzip.cpp
- src/gui/properties/propertieswidget.cpp
* Initialize member fields
* Guard for null pointer
Although pointed out in https://github.com/qbittorrent/qBittorrent/pull/15303#discussion_r688377164, not all of them are actually trigger-able when nullptr is present. Therefore this commit only patches the report from coverity scan.
* Fix typo
Supersedes #15303.
> Fix code defects

- src/base/preferences.cpp
- src/base/profile.cpp
- src/base/profile.h
- src/base/profile_p.cpp
- src/base/profile_p.h
Add `Profile::rootPath` and `Profile::configurationName` properties.
Fix startup with different profiles.
Supercedes #15400.
> Improve Profile handling

- src/app/filelogger.cpp
- src/app/upgrade.cpp
- src/base/3rdparty/expected.hpp
- src/base/CMakeLists.txt
- src/base/asyncfilestorage.cpp
- src/base/base.pri
- src/base/bittorrent/bencoderesumedatastorage.cpp
- src/base/bittorrent/torrentcreatorthread.cpp
- src/base/bittorrent/torrentinfo.cpp
- src/base/net/downloadhandlerimpl.cpp
- src/base/net/geoipmanager.cpp
- src/base/rss/rss_autodownloader.cpp
- src/base/rss/rss_session.cpp
- src/base/torrentfileswatcher.cpp
- src/base/utils/io.cpp
- src/base/utils/io.h
- src/gui/rss/automatedrssdownloader.cpp
* Improve error detection when saving files
* Use QSaveFile wherever applicable
expected.hpp was fetched from: https://github.com/martinmoene/expected-lite/blob/b803e3c07b82551d6e5390c1431112a66e5a9bf1/include/nonstd/expected.hpp
* Flush manually when saving a file
This is to work around https://bugreports.qt.io/browse/QTBUG-75077
* Improve handling when writing to temporary files
Let QTemporaryFile remove incomplete written file when error occurs.
"XXXXXX" template is not strictly required according to Qt doc.
> Improve error detection when saving files

- src/app/application.cpp
- src/app/cmdoptions.cpp
- src/base/bittorrent/session.cpp
- src/base/net/dnsupdater.cpp
- src/gui/aboutdialog.ui
- src/gui/addnewtorrentdialog.ui
- src/gui/advancedsettings.cpp
- src/gui/mainwindow.cpp
- src/gui/mainwindow.ui
- src/gui/optionsdialog.ui
- src/gui/rss/automatedrssdownloader.ui
- src/webui/www/private/views/about.html
- src/webui/www/private/views/aboutToolbar.html
- src/webui/www/private/views/preferences.html
- src/webui/www/private/views/search.html
* Revise description wordings
I noticed some comments on transifex and some of them sounds reasonable to me. And here is the result.
* WebUI: update authors page
* Combine stream statements
> Revise description wordings

- src/webui/www/private/scripts/client.js
In benchmark, using `Math.imul()` is about ~20% faster than floating point multiplication.
> WebUI: revise hash function

- src/base/utils/fs.cpp
* Add remote filesystem magic numbers
* Reuse code path
`buf.f_type` should be compatible across platforms.
https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/statfs.2.html
> Add remote filesystem magic numbers

- src/gui/optionsdialog.ui
Uses the correct case at transferlistwidget.cpp line 283.Closes #15422.
This comes from PR [15492](https://github.com/qbittorrent/qBittorrent/pull/15492).
> This PR solves issue 15422: Double-click opens torrent when set to No Action.
> The main problem is in file transferlistwidget.cpp , in line 283. Here the switch sentence is getting the action as input, which in the end is the index from one of the ComboBoxes at the Preferences window.
> As for the Downloading torrents ComboBox there are less options than for the Completed torrents the action to perform is incorrect, and it is entering in the wrong part of the switch sentence.
> To solve this I just added an entry to the Downloading torrents ComboBox, so now both ComboBoxes have the same options and we have the expected behavior.
> Organizes ComboBox items in Behavior Preferences

- .github/workflows/ci_ubuntu.yaml
- .github/workflows/ci_windows.yaml
- .github/workflows/coverity-scan.yml
* GHA CI: build dependencies manually
Now it builds boost, libtorrent manually and we have control over its version.
Enable build matrix for libtorrent versions.
Reorganized the folder/file layout in built artifact.
* GHA CI: use larger cache for compiling
Previous default was 500MB and it couldn't fit all compile results in it, enlarge it to 2GB. Note that 2GB isn't the actual size stored on the server, it will be compressed again by zstd and will be a lot smaller.
> GHA CI: build dependencies manually

- src/gui/properties/propertieswidget.cpp
The list of files contained by a torrent (the "content" tab on the bottom of the main window) is not always sorted properly. If current sort column is "priority", "progress", "remaining" or "availability" and you select another torrent on the main download list, the sorting is improper. This PR changes the behavior in a way that the list is always sorted accordingly to currently selected sort column after selecting a torrent on the main download list and also after showing the "content" tab (it's not about sorting in real-time).
**Steps to reproduce**
1. Select the "content" tab on the bottom of the main window.
2. Click on the header of one of the mentioned columns i.e. "progress", the list of files should get resorted accordingly
3. Select another torrent on the main download list
4. …
> Fix torrent content sorting

- src/app/application.cpp
- src/app/applicationinstancemanager.cpp
- src/app/applicationinstancemanager.h
- src/app/qtlocalpeer/qtlocalpeer.cpp
- src/app/qtlocalpeer/qtlocalpeer.h
- src/app/qtlocalpeer/qtlockedfile.h
- src/base/profile_p.cpp
* Create lock file in config folder instead of temp folder 
Some linux distros seem to alter TMPDIR environment variable and therefore hamper qbt ability to find the lock files. So use config folder instead of TMPDIR folder to create/locate the lock files.
Note that this change will also make qbt become one instance per-user instead of one instance per-system.
Closes #15646.
* Use char array directly
This eliminates the possibility of reassigning the pointer to another address.
For testers: This is related to qbt multi-instances detection and it should work as before, that is, only one instance is allowed. Please look for regressions.
> Create lock file in config folder instead of temp folder

- .github/workflows/ci_macos.yaml
- .github/workflows/ci_ubuntu.yaml
- .github/workflows/ci_windows.yaml
Now qbittorrent binaries will be placed in its own folder and cmake related artifacts will be in another.
> GHA CI: Revise artifact folder layout

- src/gui/search/searchjobwidget.cpp
- src/gui/search/searchjobwidget.h
New feature (QT GUI).
In the "search" tab, when right-clicking a search result, a menu pops up. The menu contains "download" item - clicking it causes either immediate adding of the torrent to the download session or showing the download window where torrent content can be viewed and some download options can be selected. Whether the one or the other action is used is controlled by "Display torrent content and some options" setting.
This PR is about splitting the "download" item into two separate items - one for each of the two mentioned actions.
Rationale: In general I have "Display torrent content and some options" setting turned off so torrents are added immediately. However, sometimes I want to see what's in the torrent or adjust some download options before starting the download. I …
> Add more download options to torrent search result right-click menu

- README.md
- src/webui/www/private/views/about.html
* Add IRC link
https://en.wikipedia.org/wiki/Internet_Relay_Chat#URI_scheme
And also show the angle brackets in rendered markdown.
* WebUI: Remove IRC in about page
This follows the GUI change in 65a30ba.
* WebUI: Revise about page
Follow GUI more closely.
Screenshot:
> WebUI: Remove IRC in about page

- src/gui/torrentoptionsdialog.cpp
- src/gui/torrentoptionsdialog.h
- src/gui/torrentoptionsdialog.ui
- src/gui/transferlistwidget.cpp
- src/gui/transferlistwidget.h
I can't decide where's the best position for it. Pics of 2 places below (start of PR is the one on top). Let me know if you prefer it in some other position.
closes #15447, closes #14064, maybe #14572
> Move some options from transfer list's context menu into "Torrent options" dialog

- src/gui/torrentcontentmodel.cpp
Small fix.
In TorrentContentModel::setData there is this piece of code for handling Qt::CheckStateRole
https://github.com/qbittorrent/qBittorrent/blob/b45248bf99ef00ce314d210c1cb9ebe5fe247cc0/src/gui/torrentcontentmodel.cpp#L283-L303
This fragment is invalid:
```cpp
if (static_cast<int>(item->priority()) != value.toInt()) 
```
Current item priority is compared against new checkbox state. I believe the intention was to check if the priority changes before performing further actions. This PR fixes the issue - compare priority against new value that is about to be set rather then the checkbox state.
> Properly check if file priority changes

- .appveyor.yml
- Visual Studio 2022 is now 64-bit
- [Visual Studio 2022 reached GA November 8, 2021](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-now-available/)
- [Appveyor released a Visual Studio 2022 image on November 9, 2021](https://www.appveyor.com/updates/)
> Update AppVeyor CI image to Visual Studio 2022

- src/webui/www/private/css/Window.css
This reverts commit 864dca1b676f360509c6f5e0024f06a002e116f2.
Upstream change: https://github.com/stylelint/stylelint-config-standard/pull/212
Labeled "Hotfix" because some popular browser (safari) doesn't support percentage notation: https://developer.mozilla.org/en-US/docs/Web/CSS/opacity#browser_compatibility
> Revert "Use percentage notation for alpha-values in CSS"

- src/gui/properties/peerlistwidget.cpp
- src/webui/www/private/index.html
Menu items in disabled state can show tool tip to let users understand why the menu is unavailable.
Related issue: #15785.
This is just an experimental change, if this idea (disable menu items instead of hiding it) works well we can apply it to other menus gradually.
ps. I also want to defer this to post v4.4.0 release as there doesn't seem to have enough time for translation work.
> Disable "add peers" menu item instead of hiding it

- .github/workflows/ci_macos.yaml
- .github/workflows/ci_ubuntu.yaml
- .github/workflows/ci_windows.yaml
- .github/workflows/coverity-scan.yml
Update `libtorrent` version(s) to `2.0.5` & `1.2.15` in `GHA CI`
- https://github.com/arvidn/libtorrent/releases/tag/v2.0.5
- https://github.com/arvidn/libtorrent/releases/tag/v1.2.15
> GHA CI: Update libtorrent version(s)

- .github/workflows/ci_windows.yaml
- src/base/preferences.cpp
- src/base/preferences.h
- src/gui/mainwindow.cpp
- src/gui/mainwindow.h
- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.h
- src/gui/uithememanager.cpp
- src/gui/uithememanager.h
* Remove redundant UI cleanups
Just exiting the application will handle all of them automatically.
* GHA CI: don't let lupdate scan boost library
As it produces superflous warnings.
* Disable system tray icon menu when app is exiting
* Simplify tray icon related code
* Show GUI lock icon after system tray icon is initialized
> Simplify tray icon related code

- src/base/http/connection.cpp
- src/base/http/connection.h
- src/base/http/responsegenerator.cpp
* Restart idle timer on sending network response
* Reserve enough buffer space according to response content size
* Avoid needless string-bytes conversion
This saves a few microseconds.
> Improvements for WebAPI server

- src/base/http/connection.cpp
For writing, this ensures expire handler won't be executed in a small time window, that is after `m_socket->write()` and before `QIODevice::bytesWritten()` signal.
For reading, this let the socket to have the chance to process the received data instead of dropping it.
This is a supplement to ece92a886ab1c7f5a44906f43cdeea58d2872944.
> Don't expire connection when there are data in buffer

- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrentcontentlayout.cpp
- src/base/bittorrent/torrentcontentlayout.h
- src/base/bittorrent/torrentimpl.cpp
- src/base/bittorrent/torrentimpl.h
- src/base/bittorrent/torrentinfo.cpp
- src/base/bittorrent/torrentinfo.h
- src/base/utils/fs.cpp
- src/base/utils/fs.h
- src/gui/addnewtorrentdialog.cpp
- src/gui/addnewtorrentdialog.h
- src/gui/properties/peerlistwidget.cpp
- src/gui/properties/piecesbar.cpp
- src/gui/properties/propertieswidget.cpp
- src/gui/torrentcontentmodel.cpp
- src/gui/torrentcontentmodel.h
- src/webui/api/synccontroller.cpp
- src/webui/api/torrentscontroller.cpp
First commit provides core changes that make clear distinction between original torrent layout (including file names) and currently used local mapping of it (so TorrentInfo instance becomes immutable since then).
The second commit makes "Add new torrent dialog" to follow selected "Content layout" in files view.
> Improve torrent content handling

- .github/workflows/ci_ubuntu.yaml
As those won't work on testers system unless they install *all* and same version of the dependent libraries too.
Another way is making it to link statically but that will require rebuilds of *all* libraries which will increase CI run time unnecessarily, i.e. this way isn't practical for CI.
> GHA CI: Don't upload built artifacts for dynamic linking builds

- src/app/upgrade.cpp
A rather silly bug.
**People who have run the recent nightlies:** Delete from your config the `Meta/MigrationVersion` you the migration code will run again and correctly after this PR is merged.
Bug introduced with 39f054eef628b199c5c3d2d37fa62dd98a4a48f2
> Correct the order of the migrated settings' mappings

- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrent.h
- src/base/bittorrent/torrentimpl.cpp
- src/base/bittorrent/torrentimpl.h
- src/gui/properties/propertieswidget.cpp
- src/gui/transferlistmodel.cpp
- src/webui/api/serialize/serialize_torrent.cpp
- src/webui/api/torrentscontroller.cpp
Apply seeding time limit's action to finished (fully downloaded with excluded content)
instead of seeding torrents.
For your convenience:
```
// finished means all selected files/pieces were downloaded and available
// to other peers (this is always a subset of active time).
// seeding means all files/pieces were downloaded and available to
// peers
```
I wonder if any people consider this bug (IMO) as a feature.
> Fix bug in seeding time limit for partial torrents

- .gitattributes
- NEWS
- TODO
- configure.ac
The contents are outdated and the files are not in use.
`configure.ac` is adjusted to suppress automake errors.
https://www.gnu.org/software/automake/manual/html_node/Strictness.html#index-Strictness_002c-foreign
> Remove TODO and NEWS files

- src/app/application.cpp
This will resolve the recent "File health" error: https://github.com/qbittorrent/qBittorrent/runs/4733244476?check_suite_focus=true (after resync with Transifex)
> Move new line character out of translation string

- src/webui/api/synccontroller.cpp
- src/webui/api/torrentscontroller.cpp
- src/webui/webapplication.h
Regression from 1c0f8b4289b8d298041fe195cdc24f793dce4df5.
Closes #15969.
> WebAPI: fix wrong key used for categories

- dist/unix/org.qbittorrent.qBittorrent.desktop
qBittorrent is a single-window application.
By marking it as such desktop environments know to not offer to open
a new window for it.
This is a new standard key intruduced in
https://gitlab.freedesktop.org/xdg/xdg-specs/-/commit/3ea3bc26e24f252eb96f4bfdd525cf4f314330c4
> Mark as single window app in .desktop file

- src/webui/api/synccontroller.cpp
- src/webui/api/torrentscontroller.cpp
- src/webui/webapplication.h
Regression from 1c0f8b4289b8d298041fe195cdc24f793dce4df5.
Closes #15969.
> WebAPI: fix wrong key used for categories (backport)

- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrentimpl.cpp
- src/base/bittorrent/torrentinfo.cpp
- src/base/bittorrent/torrentinfo.h
We shouldn't use original file names for this to do.
Closes  #15962.
> Correctly track the root folder name change

- src/base/bittorrent/torrentinfo.cpp
> Keep "torrent info" alive while generating .torrent file

- src/gui/torrentoptionsdialog.cpp
In torrent options dialog while in Automatic Management Mode.
> Update the torrent's download path field when changing category

- src/base/rss/rss_parser.cpp
Previously RSS parser couldn't correctly handle XML parsing errors occurred at beginning of document.
This patch at least helps to understand what does happen in #16069.
> Correctly handle XML parsing errors

- .github/workflows/ci_windows.yaml
qbt cmake script enables that flag already, so it make sense to build dependencies with it too.
> GHA CI: build libtorrent with `/guard:cf` flag

- src/gui/transferlistwidget.cpp
- src/gui/transferlistwidget.h
By popular demand.
It's copy-paste re-adding what i removed in my PR with a few adaptations where needed (turn to manual mode explicitly when changing save path and `move() -> setSavePath()`.
Closes #15946 closes #15965 closes #16003
> Restore context menu actions

- src/base/bittorrent/torrentimpl.cpp
Closes #16058.
Note: this PR is for v4.4.x branch only. In v4.5 all similar problems should gone when #15915 is merged.
> Correctly concatenate paths

- conf.pri.windows
- configure
- configure.ac
- src/base/bittorrent/torrentimpl.cpp
* Revise error message
Remove the period mark at the end of error message since `errc.message()` already contains one.
* Remove outdated build configuration
* Add comment for new libtorrent build flag
Upstream change: [arvidn/libtorrent@66def89](https://github.com/arvidn/libtorrent/commit/66def8908909232b15f02a97c9671785bd019736)
Will back port "Revise error message" commit to v4.4.x.
> Revise error message

- src/base/bittorrent/nativetorrentextension.cpp
Closes #16049.
Closes #16033.
P.S. I have also met messages with the same crash as in #16033, but we now have a bunch of Issues in which crashes of different types are mixed, so it is difficult for me to identify them.
> Correctly handle received metadata

- src/gui/transferlistwidget.cpp
It conflicts with QMenu on Qt6 that causes the crash.
Closes #15779.
> Don't start separate event loop for QFileDialog

- src/gui/torrentcontentmodel.cpp
- src/gui/torrentcontentmodelfolder.cpp
- src/gui/torrentcontentmodelfolder.h
Use QHash to cache folder items to improve
TorrentContentModelFolder::childFolderWithName
> Improve Torrent content tree structure creation

- src/base/bittorrent/torrentimpl.cpp
- src/base/bittorrent/torrentimpl.h
Prevents repeated transformation of data from libtorrent format with several consecutive accesses.
> Cache pieces info

- src/base/bittorrent/peerinfo.cpp
- src/base/bittorrent/peerinfo.h
For ~800 pieces, this roughly cuts the run time (of this function) in half.
> Speed up piece relevance calculation

- src/gui/transferlistwidget.cpp
- src/gui/transferlistwidget.h
>Add tooltip to Automatic Torrent Management context menu action
It's "restore" actually (from #15452) but in the eyes of the users, this option never had a tooltip i.e. it never worked thanks to the stupid Qt default option `menu->setToolTipsVisible` being false. The same checkbox in Torrent options has the same tooltip so if you think it's too much, i'll drop that commit.
Closes #16046
> Add confirmation for enabling Auto TMM from context menu

- src/CMakeLists.txt
- src/app/CMakeLists.txt
- src/gui/CMakeLists.txt
fixes unnecessary recompilation when editing GUI files
cuts down recompilation times from the 20s to 4s for GUI lib (when only one file is changed, tested with "uithememanager.cpp")
> Manually specify UIC headers in CMake

- src/gui/fspathedit.cpp
- src/gui/fspathedit.h
Closes #16218.
Should be backported to v4.4.x.
> Open correct directory when clicked on Browse button

- src/base/bittorrent/torrentimpl.cpp
Fixes unnecessary renaming of files on windows
Improves startup time and also greatly decreases works outside the main thread at startup
> Don't rename file because of difference in path separator

- src/gui/mainwindow.cpp
Closes #16324.
Will backport to v4.4.x.
> Fix crash when shutting down and clicked on system tray icon

- src/gui/addnewtorrentdialog.cpp
- src/gui/addnewtorrentdialog.ui
1. Not sure if we should enable/disable the buttons at all.
2. Not sure if where i currently do them are the best places (or in `setupTreeview()` maybe?)
closes #16308, closes #15963
closes #16012
/off topic
After this i want to add a filter like in Content tab. It will be copy-paste, i have no interest in finding out how to somehow make them shared. If anyone has a problem with that, let me know so i don't open the PR.
While i'm in this file, anyone knows if #16012 has a simple solution or i should leave it alone?
> Add Select All/None buttons in new torrent dialog

- src/gui/mainwindow.cpp
> Fix crash when shutting down and clicked on system tray icon (backport)

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrentimpl.cpp
- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.ui
- src/webui/api/appcontroller.cpp
- src/webui/webapplication.h
If the option is enabled any relative save path will be resolved against an appropriate Category path instead of Global default one.
Closes #16209.
> Allow to use Category paths in "Manual" mode

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrentimpl.cpp
- src/base/bittorrent/torrentimpl.h
- src/gui/mainwindow.cpp
- src/gui/transferlistfilterswidget.cpp
- src/gui/transferlistfilterswidget.h
The idea is that we shouldn't pollute upper level components with all the atomic events in libtorrent. In some cases it's better to preprocess them and then report it as a compound events.
It should improve GUI performance (especially during startup with many torrents and tracker entries in them).
> Improve tracker status handling

- src/base/bittorrent/ltqbitarray.cpp
- src/base/path.cpp
- src/base/path.h
- src/webui/www/private/css/Window.css
* Use QVarLengthArray whenever applicable
* Use "table look-up" method for reversing byte
This method takes constant time and is less prone to (CPU) pipeline stalling due to less computation. Also it is slightly faster than the previous method.
* Make Path::operator== a free function
* Remove hack for outdated IE 6 browser
The `mask()` isn't valid in CSS.
> Use QVarLengthArray whenever applicable

- src/base/path.cpp
Otherwise `PathList` (aka` QList<Path>`) cannot be used in queued connections with Qt5.
> Correctly register PathList alias

- src/base/bittorrent/torrentimpl.cpp
- src/base/bittorrent/torrentimpl.h
Speedup access to file priorities by avoiding extra blocking call to libtorrent thread.
Improve the Torrent interface by hiding the asynchrony of file priority changes behind the scenes.
> Cache file priorities

- src/webui/www/private/scripts/client.js
This checks that `category_list[categoryHash].torrents` is truthy before dereferencing it. In some cases the API response will have a torrent in a category that doesn't exist resulting in the check to return `undefined` which is not `null`. This broadens the check so that it will create the category even if null.
> Fix UI crash when torrent is in non-existent category.

- src/base/global.h
- src/base/settingsstorage.cpp
Now we should start writing utf-16 QString literals in the form of: `u"string"_qs` everywhere where `QString` is expected.
Note that the QString is built at compile-time in Qt6 and in Qt5 it is built at run-time.
I haven't found a way to build it at compile-time in Q5.
Currently in Qt5 the newly added operator is faster than `QString(QLatin1String)` constructor.
> Add literal operator to efficiently construct QString in Qt5

- .pre-commit-config.yaml
And bump hooks version along the way.
> GHA CI: exclude checking for GUI i18n files

- src/base/bittorrent/portforwarderimpl.cpp
- src/base/bittorrent/session.cpp
This improves readability and may allow users to match log message with better accuracy.
Now log message is consisted of 2 parts:
The first part is a short sentence describing the event. It should avoid writing out the specifics of the event as it will be described in the next part of the message. The sentence should use correct tense of the event.
The second part consist of `Name: Value` pairs which will provide sufficient info for the event.
Note that none of the message parts is mandatory, one of them can be omitted when the resulting log message is clear enough.
Note: this PR mainly apply to `Session` class and other classes can be applied later (gradually).
> Unify log messages format

- .github/workflows/ci_file_health.yaml
- .github/workflows/ci_macos.yaml
- .github/workflows/ci_ubuntu.yaml
- .github/workflows/ci_webui.yaml
- .github/workflows/ci_windows.yaml
This will only cancel outdated workflow runs on PR branches and won't affect other normal repo branches.
> GHA CI: cancel outdated in-progress workflow runs

- src/gui/properties/proplistdelegate.cpp
Comment out the code which disables the QComboBox editor on the torrent properties widget for the file list items with "mixed" priority.
Fixes #1544
> Enable changing "mixed" priority from the dropdown

- src/gui/fspathedit.cpp
Enable shortcut folders for the Open and Save directory file dialogs on the Add New Torrent File dialog to allow browsing to shortcut folders on Windows OS.
Fixes #7900
> Enable browsing to shortcut folders

- src/gui/torrentcontentmodel.cpp
- src/webui/www/private/scripts/dynamicTable.js
This renames the "Size" column title on content tab to "Total Size" and changes the corresponding Enum's ID in the code to match the new title. 
Fixes #7348
> Rename content tab "Size" column to "Total Size"

- .github/workflows/ci_macos.yaml
libtorrent 2.0.5 has build issues with boost >= 1.78.
> GHA CI: install boost library manually

- src/gui/previewselectdialog.cpp
- src/gui/properties/peerlistwidget.cpp
- src/gui/properties/trackerlistwidget.cpp
- src/gui/search/pluginselectdialog.cpp
- src/gui/search/searchjobwidget.cpp
- src/gui/torrentcontenttreeview.cpp
- src/gui/transferlistwidget.cpp
`QHeaderView::setFirstSectionMovable()` was introduced in Qt 5.11. 
The first column in transfer list is movable without any of these but i included it anyway to be safe. I don't know if something is broken for me, maybe corrupt savestate of header in config file, i mention this because it happens sometimes when going from Qt6 to Qt5.
> Don't use hack to make the first column movable

- src/gui/properties/propertieswidget.cpp
- src/gui/properties/proplistdelegate.cpp
Currently you can't directly change the priority of a partially completed multi file torrent. You'll have to start downloading those files and then change their priority. Closes #10994, closes  #8673
> Allow setting priority for partially downloaded multi-file torrent

- src/gui/transferlistfilterswidget.cpp
This will allow users to perform action on all torrents with a single click instead of having to select all with ctrl+A or other cumbersome ways. Basically it copies the function found in tracker/category filters.
Closes #13398
> Add right click menu for status filters to allow bulk pause/resume/delete action

- .github/workflows/ci_file_health.yaml
- .github/workflows/ci_macos.yaml
- .github/workflows/ci_ubuntu.yaml
- .github/workflows/ci_webui.yaml
- .github/workflows/ci_windows.yaml
- .github/workflows/coverity-scan.yml
- .github/workflows/stale_bot.yaml
* GHA CI: Update `setup-python` action to `v3`
https://github.com/actions/setup-python/releases
* GHA CI: Update `checkout` action to `v3`
https://github.com/actions/checkout/releases
* GHA CI: Update `stale` action to `v5`
https://github.com/actions/stale/releases
* GHA CI: Update `upload-artifact` action to `v3`
https://github.com/actions/upload-artifact/releases
> GHA CI: Update multiple workflow `actions`

- src/gui/optionsdialog.ui
* It's now in keeping visually with `browse` button next to it.
> Remove unnecessary UI properties from "Ip Filter Refresh" button

- .github/workflows/ci_macos.yaml
- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrentimpl.cpp
- src/base/bittorrent/torrentimpl.h
The alert is too annoying and there is no control knob for tuning it, so disable it in v4_4_x branch.
Closes #16462.
Note: GHA CI commits are backported from PR #16539 to fix macOS CI failures.
> Disable performance alert

- src/base/http/requestparser.cpp
Change form data parser to allow blank lines when adding torrent URLs.
Fixes #11298
> Allow empty lines in multipart form data

- src/gui/aboutdialog.cpp
- src/gui/addnewtorrentdialog.cpp
- src/gui/autoexpandabledialog.cpp
- src/gui/banlistoptionsdialog.cpp
- src/gui/cookiesdialog.cpp
- src/gui/deletionconfirmationdialog.cpp
- src/gui/downloadfromurldialog.cpp
- src/gui/ipsubnetwhitelistoptionsdialog.cpp
- src/gui/mainwindow.cpp
- src/gui/optionsdialog.cpp
- src/gui/previewselectdialog.cpp
- src/gui/properties/propertieswidget.cpp
- src/gui/rss/automatedrssdownloader.cpp
- src/gui/search/pluginselectdialog.cpp
- src/gui/search/pluginsourcedialog.cpp
- src/gui/shutdownconfirmdialog.cpp
- src/gui/speedlimitdialog.cpp
- src/gui/statsdialog.cpp
- src/gui/torrentcreatordialog.cpp
- src/gui/torrentoptionsdialog.cpp
- src/gui/trackerentriesdialog.cpp
- src/gui/utils.cpp
- src/gui/utils.h
- src/gui/watchedfolderoptionsdialog.cpp
`widget` parameter is kept for now to avoid major disruption for other PR.
Also add comments for loading svg images.
> Remove obsoleted functions from Utils::Gui namespace

- src/base/bittorrent/infohash.cpp
- src/base/bittorrent/infohash.h
- src/base/bittorrent/ltqhash.h
- src/base/bittorrent/peeraddress.cpp
- src/base/bittorrent/peeraddress.h
- src/base/bittorrent/torrent.cpp
- src/base/bittorrent/torrent.h
- src/base/bittorrent/tracker.cpp
- src/base/bittorrent/tracker.h
- src/base/bittorrent/trackerentry.cpp
- src/base/bittorrent/trackerentry.h
- src/base/digest32.h
- src/base/net/downloadmanager.cpp
- src/base/net/downloadmanager.h
- src/base/path.cpp
- src/base/path.h
- src/gui/properties/peerlistwidget.cpp
* Update function signature for Qt6 qHash()
Since the `qhash()` signature has changed in Qt6.
* Avoid redundant hashing
The return type of `std::hash()` is larger (or equal) than what `qHash()` requires so we can omit hashing it again.
* Use hashing helpers provided by Qt6
> Avoid redundant hashing 

- src/gui/aboutdialog.cpp
Fix "C++" word breaking to new line on-the-fly as an alternative to changing it in all translations in Transifex.
Alternative to #16625.
Fixes #13805
> Fix C++ word breaking alternative

- src/gui/properties/peerlistwidget.cpp
- src/gui/properties/trackerlistwidget.cpp
- src/gui/properties/trackerlistwidget.h
- src/gui/torrentcontenttreeview.cpp
- src/gui/torrentcontenttreeview.h
- src/gui/transferlistwidget.cpp
Horizontal scrolling was added to the peer list and torrent list, but I see no reason why it should not also be applied to the tracker list and especially the torrent content list. Tested on Windows 10.
> Add horizontal scrolling for tracker list and torrent content

- src/gui/utils.cpp
Uses the same workaround as Qt does to call ShellExecute() when you use QDesktopServices::openUrl().
PR #16670.
Closes #16423.
> Prevent crash when open torrent destination folder

- CMakeLists.txt
The option is case sensitive.
Signed-off-by: Sam James <sam@gentoo.org>
> CMake: fix systemd directory help text

- src/app/application.cpp
Otherwise it is impossible to apply working set size larger than 4095 MiB.
> Avoid integer overflow when calculating working set size

- src/gui/properties/trackerlistwidget.cpp
- src/gui/properties/trackerlistwidget.h
- src/webui/www/private/scripts/dynamicTable.js
Change the confusing `Downloaded` column name in trackers tab.
Closes https://github.com/qbittorrent/qBittorrent/issues/14918
> Change Downloaded to Times Downloaded in trackers tab

- src/app/application.cpp
- src/app/qtlocalpeer/qtlockedfile_win.cpp
- src/app/stacktrace_win.h
- src/base/bittorrent/session.cpp
- src/base/utils/foreignapps.cpp
- src/base/utils/misc.cpp
- src/base/utils/misc.h
- src/gui/torrentcontentmodel.cpp
- src/gui/utils.cpp
* Use proper type to represent a path
* Don't use explicit memory management
> Use proper type to represent a path

- src/webui/www/private/scripts/client.js
Tags can be missing from config but remain in resume data. May happen due to corrupted/deleted config.
Closes https://github.com/qbittorrent/qBittorrent/issues/11906
> Fix WebUI crash due to missing tags from config

- src/base/bittorrent/session.cpp
Closes #16749.
(Damn, I (we) need to be more careful with backport of the changes, which is not trivially applicable.)
> Correctly handle changing of temp save path

- .github/workflows/ci_macos.yaml
- src/gui/properties/downloadedpiecesbar.cpp
- src/gui/properties/pieceavailabilitybar.cpp
* Add missing header
Fix up https://github.com/qbittorrent/qBittorrent/commit/75c93d72be7a31f29d6c14aa6f3eefa8ec9f9ea1.
* GHA CI: work around error when installing Qt
This is to (temporarily) work around CI errors at jurplel/install-qt-action.
Upstream issue: https://github.com/jurplel/install-qt-action/issues/130
> GHA CI: work around error when installing Qt 

- .github/workflows/ci_macos.yaml
> GHA CI: work around error when installing Qt (backport)

- src/webui/www/private/newcategory.html
- src/webui/www/private/newtag.html
- src/webui/www/private/rename.html
- src/webui/www/private/scripts/misc.js
- src/webui/www/private/scripts/mocha-init.js
- src/webui/www/private/setlocation.html
* WebUI: make various dialog resizable
And enlarge dialog default width.
* WebUI: show correct location path
The `path` might contains '&' (delimit character) so it must be encoded.
Closes https://github.com/qbittorrent/qBittorrent/issues/15976.
* WebUI: remove temporary element
Before:  [screenshot](https://user-images.githubusercontent.com/9395168/161377883-f14507f4-f964-4946-8acb-89c331659082.png)
After: [screenshot](https://user-images.githubusercontent.com/9395168/161377886-a83c5f2e-df7b-46e7-8ed2-e8803fe46b7b.png)
UPDATE, change verified: https://github.com/qbittorrent/qBittorrent/issues/15976#issuecomment-1085506109
> WebUI: show correct location path 

- src/app/stacktrace.h
- src/base/bittorrent/cachestatus.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/sessionstatus.h
- src/base/bittorrent/statistics.cpp
- src/base/bittorrent/statistics.h
- src/base/search/searchpluginmanager.h
- src/gui/optionsdialog.cpp
- src/gui/rss/articlelistwidget.cpp
- src/gui/rss/feedlistwidget.cpp
- src/gui/rss/rsswidget.cpp
- src/gui/statsdialog.cpp
- src/webui/api/synccontroller.cpp
* Omit redundant cast
* Use signed integer type for counters
* Migrate away from unsigned integer types
Signed integers should be preferred in these cases.
* Fix wrong conversion to QVariant
It was converted to bool-like type which is wrong.
>Migrate away from unsigned integer types 
It is actually more like unify integer types, since we reserve unsigned integers for bitwise operations (and few other very specific use cases like IP port numbers) and use signed integer for everything else.
> Migrate away from unsigned integer types

- src/app/cmdoptions.cpp
- src/base/indexrange.h
- src/base/rss/rss_autodownloadrule.cpp
- src/base/rss/rss_autodownloadrule.h
- src/gui/utils.cpp
- src/webui/api/torrentscontroller.cpp
* Move comparison operator out of class
* Simplify code
* Assign temporary data to a variable
This is mainly to avoid dangerous code pattern: getting an iterator on a temporary object. Previously `data()` returns a const reference so the code wasn't doing any harm.
I think those are worth cleaning up when I was experimenting with C++20.
> Move comparison operator out of class

- src/base/digest32.h
Previously `0000...` was erroneously displayed when v2 hash is absent, now it correctly shows the `N/A`.
> Fix wrong v2 hash string displayed in WebUI

- src/webui/api/apicontroller.cpp
- src/webui/api/apicontroller.h
- src/webui/api/authcontroller.cpp
- src/webui/api/authcontroller.h
- src/webui/api/isessionmanager.h
- src/webui/api/searchcontroller.cpp
- src/webui/api/searchcontroller.h
- src/webui/api/synccontroller.cpp
- src/webui/api/synccontroller.h
- src/webui/webapplication.cpp
- src/webui/webapplication.h
This will allow further to subscribe to BitTorrent session notifications in order to synchronize data more efficiently (only those torrents that have been updated since the last time).
It should also slightly improve performance by using direct data access instead of repetitive reading/rewriting of data in the abstract session storage.
> Have separate API controller instances per session

- src/webui/webapplication.cpp
Since https://github.com/qbittorrent/qBittorrent/commit/4471a6377ee7446cfbcf0314654a41de8bb4a9f3 when not having a session the API would return "Not Found" instead of "Forbidden" when trying to access a non-public endpoint.
This also broke other software like Radarr/Sonarr which expected a 403 and not a 404 to detect the web API version.
> WebAPI: return correct status

- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrentimpl.cpp
These are some improvements I made while working on #16840, and which can be applied separately.
Under some conditions (when libtorrent is doing heavy work), blocking calls can wait quite a long time, thereby suspending the main application thread. In some cases, we can avoid this, since we have enough data to make the job without call to libtorrent. Although in some cases it may require a little more work to be done in the main thread, but overall responsiveness still benefits greatly in the end, especially when the libtorrent working thread is heavily loaded.
> Avoid some blocking calls to libtorrent

- .github/workflows/ci_macos.yaml
- .github/workflows/ci_ubuntu.yaml
- .github/workflows/ci_windows.yaml
- .github/workflows/coverity-scan.yml
- .pre-commit-config.yaml
Update `libtorrent` version(s) to `2.0.6` & `1.2.16` in `GHA CI`
- https://github.com/arvidn/libtorrent/releases/tag/v2.0.6
- https://github.com/arvidn/libtorrent/releases/tag/v1.2.16
Update `Boost` version to `1.79.0`
- https://www.boost.org/users/history/version_1_79_0.html
Bump `pre-commit-hooks` version to `4.2.0`
- https://github.com/pre-commit/pre-commit-hooks/releases/tag/v4.2.0
Update `Qt6` version to `6.3.0`
- https://www.qt.io/blog/qt-6.3-released
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.3.0/release-note.md
Note: used `aqtinstall 2.1.0` with `jurplel
/
install-qt-action` for support of `Qt 6.2.1+`
(this requirement can be removed on official release of `jurplel
/
install-qt-action v3`)
> GHA CI: Update dependencies

- src/base/bittorrent/torrent.h
- src/base/bittorrent/torrentimpl.cpp
- src/base/bittorrent/torrentimpl.h
Related: https://github.com/qbittorrent/qBittorrent/pull/16886#discussion_r855882018
@Piccirello
Now you can use it from webapi:
```c++
const nonstd::expected<QByteArray, QString> result = someTorrentHandle.exportToBuffer();
if (result) // no error occurred, provides data
const QByteArray &data = result.value();
else  // has error, provides error string
const QString &errorMsg = result.error();
```
> Add support for exporting .torrent data to buffer

- src/app/main.cpp
* Use correct type for comparisons
`_write()` actually returns `int` type.
And fix wrong function parameters.
Closes https://github.com/qbittorrent/qBittorrent/issues/16938.
Closes https://github.com/qbittorrent/qBittorrent/issues/16944.
* Avoid splitting code over ifdef boundary
By removing unimportant debug message.
* Disable Linux-specific function when compiling for Windows
I should backport it to v4.4.x since it resolves severe compilation issue.
> Fix nogui compilation for Windows

- src/base/bittorrent/session.cpp
- src/gui/optionsdialog.ui
> Remove artificial max limits from "Torrent Queueing" related options

- src/gui/mainwindow.cpp
Sorry I don't know if this will work as I can't test it.
closes https://github.com/qbittorrent/qBittorrent/issues/14897
> Prevent the new update box from blocking input on other dialogues

- dist/docker/Dockerfile
- dist/docker/Readme.md
- dist/docker/entrypoint.sh
This PR separates these directories to prevent their contents from clobbering each other. For ex, on initial run, both directories create an `rss` directory. There are no guarantees future files won't conflict.
```sh
/ $ ls -l /config/qBittorrent/
total 20
-rw-r--r--    1 root     root             4 May  2 05:13 categories.json
srwx------    1 root     root             0 May  2 05:13 ipc-socket
-rw-r--r--    1 root     root             0 May  2 05:13 lockfile
-rw-r--r--    1 root     root           185 May  2 05:14 qBittorrent-data.conf
-rw-r--r--    1 root     root          1702 May  2 05:13 qBittorrent.conf
drwxr-xr-x    2 root     root          4096 May  2 05:13 rss
-rw-r--r--    1 root     root             4 May  2 05:13 watched_folders.json
/ $ ls -l /data/qBittorrent/
total 16 …
```
> Separate docker image `data` and `config` dirs

- src/webui/www/private/views/preferences.html
This mostly happens with a clean install.
> Fix empty selection in WebUI language combobox

- src/base/preferences.cpp
- src/webui/api/appcontroller.cpp
Previously it was wrapped in QVariant type.
> Store WebUI port setting in human readable number

- dist/docker/entrypoint.sh
If the user is using a pre-existing config, don't update the legal notice.
> Fix Docker legal notice when using existing config

- src/webui/api/apicontroller.cpp
- src/webui/api/apicontroller.h
- src/webui/api/torrentscontroller.cpp
- src/webui/api/torrentscontroller.h
- src/webui/webapplication.cpp
- src/webui/webapplication.h
- src/webui/www/private/index.html
- src/webui/www/private/scripts/mocha-init.js
- src/webui/www/private/views/transferlist.html
This PR adds the new "Export .torrent" (#16886) functionality to the WebAPI/WebUI. Props to @Chocobo1 for making this as easy as  possible. This has been tested in Firefox, Safari, and Chrome.
> Add support for exporting .torrent from WebUI

- dist/docker/Dockerfile
- dist/docker/Readme.md
- dist/docker/entrypoint.sh
* Improves code readability.
* Improve documentation.
* Fix "docker stop" doesn't terminate qbt gracefully which could lead to data corruption.
* Provide correct/working bittorrent listening port by default.
* Make use of qbt profile option instead of hacking environment variables.
* Simplify build steps.
~~Note that this PR already incorporate changes from #16974. I'll rebase it again after #16974 is merged.~~ Done.
> Improve Docker build

- CMakeLists.txt
- INSTALL
- configure
- configure.ac
This is a prerequisite for using boost stacktrace.
Note that this is not the first version that introduces boost stacktrace but the version that should be stable enough.
Boost 1.71 is available on both debian, ubuntu:
https://packages.debian.org/bullseye/libboost-dev
https://packages.ubuntu.com/focal/libboost-dev
> Bump boost requirement to 1.71

- dist/docker/Dockerfile
- dist/docker/Readme.md
- dist/docker/entrypoint.sh
* Avoid using valid path for illustrative purpose
Otherwise docker will really create this example path on host machine which is bad.
* Make the container filesystem read-only
It is not expected to modify the filesystem of the container. 
Mounted volumes (-v) are not affected.
* Run qbt-nox as non-root
This is mainly to avoid downloaded files being owned by root which requires another one or two commands to change the file ownership.
> Improve docker script

- src/base/bittorrent/torrentimpl.cpp
Fixes regression of bcfa4866fee8754147417cb20796eaeb2b2573ea.
Closes #16999.
> Mark all files as complete if torrent is in "seed mode"

- src/base/bittorrent/torrentimpl.cpp
When torrent is added without metadata libtorrent doesn't honor "seed mode" and doesn't save it in resume data so when metadata is available torrent will still check file hashes.
> Preserve "skip hash check" when there is no metadata

- src/gui/torrentcontentmodel.cpp
For the case of switching download/don't download via priorities.
closes #17037
> Update space label when changing priorities in new torrent dialog

- src/base/net/geoipdatabase.cpp
- src/base/net/geoipdatabase.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
Add const.
Move template implementation to .cpp file.
* Fix wrong GUI behavior in "Optional IP address to bind to" setting
Previously the address field got erroneously reset to "All addresses" when the network interface is down.
I suppose I should backport the GUI fix to v4_4_x branch.
> Fix wrong GUI behavior in "Optional IP address to bind to" setting

- src/gui/advancedsettings.cpp
Previously the address field got erroneously reset to "All addresses" when the network interface is down.
Original PR #17031.
> Fix wrong GUI behavior in "Optional IP address to bind to" setting (backport)

- src/base/bittorrent/torrentimpl.cpp
- src/base/bittorrent/torrentimpl.h
https://github.com/arvidn/libtorrent/pull/6867 is also required to close issues like #15747, #16240 and #16553.
> Handle all "fastresume rejected" cases consistently

- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/extensiondata.h
- src/base/bittorrent/magneturi.cpp
- src/base/bittorrent/nativesessionextension.cpp
- src/base/bittorrent/nativesessionextension.h
- src/base/bittorrent/nativetorrentextension.cpp
- src/base/bittorrent/nativetorrentextension.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrent.h
- src/base/bittorrent/torrentimpl.cpp
- src/base/bittorrent/torrentimpl.h
- src/base/bittorrent/torrentinfo.cpp
- src/base/bittorrent/torrentinfo.h
- src/base/bittorrent/trackerentry.cpp
- src/gui/mainwindow.cpp
- src/gui/properties/trackerlistwidget.cpp
- src/gui/transferlistfilterswidget.cpp
- src/gui/transferlistfilterswidget.h
- src/webui/api/torrentscontroller.cpp
This should significantly reduce the amount of blocking calls to libtorrent for retrieving announce entries (no such call at all in case of stopped torrents):
1. Tracker entries are cached at qBittorrent level so libtorrent is touched only when trackers info is updated.
2. Moreover cached tracker entries are initialized from resume data so libtorrent keeps untouched until trackers info is first time updated. This should have significant performance impact at startup time, especially within the context of #16840.
Tracker entries are also changed to be considered unique only based on the tracker URL, since allowing duplicates does not make sense and it isn't really supported by libtorrent. See https://github.com/arvidn/libtorrent/issues/6846 for reference.
This PR is most likely the last …
> Revamp tracker entries handling

- .appveyor.yml
- .github/workflows/ci_macos.yaml
- .github/workflows/ci_ubuntu.yaml
- .github/workflows/ci_windows.yaml
- src/app/CMakeLists.txt
It uses lupdate directly.
Qt's `qt_add_lupdate()` cmake function doesn't help much.
First of all it is Qt6 only.
Secondly, our project is split into multiple targets but we need all
strings into a single .ts file per language.
Thirdly, it looks like it will skip source files that are added conditionally into the build
via cmake condition checking (eg DBUS source files). We need to gather all strings present
in the source files regardless of the build configuration.
On another note, this is a step towards reducing dependency on qmake/autoconf.
> Use CMake to update translation files

- src/base/net/downloadhandlerimpl.cpp
May fix #16879.
The data from qnetworkrelpy seems to have been decompressed since qt 6.3.
> Don't decompress the reply data for Qt 6.3

- src/app/application.cpp
- src/app/application.h
- src/app/signalhandler.cpp
- src/base/bittorrent/session.cpp
- src/base/bittorrent/statistics.cpp
- src/base/rss/rss_item.cpp
- src/base/torrentfileguard.cpp
- src/base/torrentfileguard.h
- src/base/utils/misc.cpp
- src/gui/mainwindow.cpp
- src/gui/search/searchjobwidget.cpp
- src/gui/search/searchjobwidget.h
- src/gui/torrentcontentmodel.cpp
- src/gui/torrentcontentmodel.h
- src/gui/transferlistdelegate.cpp
- src/gui/transferlistdelegate.h
- src/gui/transferlistmodel.cpp
- src/gui/transferlistmodel.h
- src/gui/uithememanager.cpp
* Suppress type narrowing warnings
* Turn static variable into class member
* Revise code
* Move function into anonymous namespace
* Revise icon cache look up
Find in `m_iconCache` first because it is cheaper than calling `QIcon::fromTheme()`.
* Clean up usage of static keyword
They are either misused or redundant, so remove it.
> Clean up usage of `static` keyword

- src/gui/properties/trackerlistwidget.cpp
Global status takes precedence over specific torrent private status
> Fix DHT/PeX/LSD status when it is globally disabled

- src/base/preferences.cpp
- src/base/preferences.h
- src/gui/aboutdialog.cpp
- src/gui/addnewtorrentdialog.cpp
- src/gui/banlistoptionsdialog.cpp
- src/gui/cookiesdialog.cpp
- src/gui/downloadfromurldialog.cpp
- src/gui/ipsubnetwhitelistoptionsdialog.cpp
- src/gui/mainwindow.cpp
- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.h
- src/gui/previewselectdialog.cpp
- src/gui/rss/automatedrssdownloader.cpp
- src/gui/rss/automatedrssdownloader.h
- src/gui/search/pluginselectdialog.cpp
- src/gui/search/pluginsourcedialog.cpp
- src/gui/search/searchwidget.cpp
- src/gui/speedlimitdialog.cpp
- src/gui/statsdialog.cpp
- src/gui/torrentcreatordialog.cpp
- src/gui/torrentoptionsdialog.cpp
- src/gui/trackerentriesdialog.cpp
- src/gui/watchedfolderoptionsdialog.cpp
* Set dialog properties at the caller site
Redundant `setModal(true)` are removed since the dialog is already opened via `open()`.
* Don't resize dialog with invalid sizes
This fixes wrong dialog sizes on first startup.
> Fix wrong dialog sizes on first start up

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrentimpl.cpp
- src/gui/addnewtorrentdialog.cpp
- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.ui
- src/webui/api/appcontroller.cpp
- src/webui/webapplication.h
- src/webui/www/private/views/preferences.html
Blacklist filtered file names from being downloaded from torrent(s).
See Options > Downloads >Do not download.
Files matching any of the filters in this list will have their priority automatically set to "Do not download".
Closes #3369.
> Add file name filter/blacklist

- src/base/net/smtp.cpp
This PR adds support for custom ports in SMTP settings used for email notifications.
The port can be optionally specified by appending `:<port>` to the existing `SMTP Server` field in settings. If no port is specified, then the default port (`25` for insecure or `465` for SSL) is used.
Closes #12212.
> Add support for custom SMTP ports

- src/app/filelogger.cpp
- src/gui/properties/piecesbar.cpp
* Fix wrong file names displayed in tooltip
Also rename variable.
Closes https://github.com/qbittorrent/qBittorrent/issues/17179.
* Avoid string encoding conversion
Use UTF-16 string literals to match QTextStream internal buffer encoding.
I'll backport the fix to v4.4.x.
> Fix wrong file names displayed in tooltip

- src/gui/properties/piecesbar.cpp
> Fix wrong file names displayed in tooltip (backport)

- src/base/utils/compare.h
The QCollator will work on posix mode if not MacOS and also no ICU. From https://github.com/qt/qtbase/blob/8a665ba9a660a09e5e6ac7cce2272118e303c220/src/corelib/CMakeLists.txt#L799-L802 and https://github.com/qt/qtbase/blob/ffdd372c7bbda62e9d937f406319f38e3e982774/src/corelib/text/text.pri#L63-L74.
If the Qt is built without ICU, the qbittorrent-nox with numericMode enabled will generate a lot of warning messages in the CMD. From https://github.com/qt/qtbase/blob/8a665ba9a660a09e5e6ac7cce2272118e303c220/src/corelib/CMakeLists.txt#L799-L802.
Othes' report:
https://www.reddit.com/r/qBittorrent/comments/s9z2ys/no_detailed_text_info/
https://dietpi.com/forum/t/how-to-install-qbittorrent-4-3-9-vesrion/6092/4
> Don't use QCollator when it works on posix mode

- src/base/rss/feed_serializer.cpp
- src/base/rss/rss_article.cpp
- src/base/rss/rss_article.h
- src/base/rss/rss_autodownloader.cpp
- src/base/rss/rss_feed.cpp
- src/base/rss/rss_feed.h
- src/base/rss/rss_parser.cpp
- src/base/rss/rss_parser.h
1. Disunify the logic of adding new and saved articles to avoid some redundant work during startup.
2. Apply several code cleanups.
3. Fix regression of previous changes that prevents Qt5 based build from being working correctly.
As a further improvement, it would be nice to get rid of emitting `newArticle()` signals at startup altogether, and instead handle the event of the end of loading saved articles.
> Improve RSS subsystem initialization

- src/base/bittorrent/session.cpp
In Tools / Options / Advanced, set the outgoing ports to [min, max], but the actual outgoing ports used is [min, max+1].
libtorrent uses `outgoing_port` and `num_outgoing_ports` to set outgoing ports, the min and max outgoing ports are [outgoing_port, outgoing_port + num_outgoing_ports], see:
https://www.libtorrent.org/reference-Settings.html#outgoing_port
https://github.com/arvidn/libtorrent/blob/master/src/session_impl.cpp#L3138-L3153
qBittorrent set outgoing_port to min, num_outgoing_ports to max - min + 1, causes the actual max outgoing port is max+1.
> Fix max outgoing port setting incorrectly

- src/webui/www/private/css/style.css
The progress bar of the Web UI often looks blurry on edges of coloured bars, especially for torrents with large files. This is due to the fact that the default image scaling algorithm was optimized for photos and drawings, not pixelated images like a progress bar (with sharp edges).
This PR will fix the problem by specifying the [image scaling algorithm](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering#pixelated) for the canvas element of the progress bar. Please see the attached images for comparison (notice the edges of coloured bars):
Before (no `image-rendering` property specified):
After (`image-rendering: pixelated`):
> Improve Web UI progress bar rendering

- src/app/application.cpp
- src/app/application.h
- src/base/CMakeLists.txt
- src/base/applicationcomponent.cpp
- src/base/applicationcomponent.h
- src/base/base.pri
- src/gui/CMakeLists.txt
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/gui/gui.pri
- src/gui/guiapplicationcomponent.cpp
- src/gui/guiapplicationcomponent.h
- src/gui/interfaces/iguiapplication.h
- src/gui/mainwindow.cpp
- src/gui/mainwindow.h
- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.h
- src/webui/api/apicontroller.cpp
- src/webui/api/apicontroller.h
- src/webui/api/appcontroller.cpp
- src/webui/api/authcontroller.cpp
- src/webui/api/synccontroller.cpp
- src/webui/api/synccontroller.h
- src/webui/webapplication.cpp
- src/webui/webapplication.h
- src/webui/webui.cpp
- src/webui/webui.h
This PR starts to redesign application structure.
In the following steps this will: 
1. Allow the application components to access each other via application interface instead of using singletons. 
2. Allow to reduce some "noise" in the code that was due to access components using singletons. 
3. Allow to avoid some extra implementation details by hiding some service components behind helper methods.
> Implement base classes for application components

- src/base/bittorrent/session.cpp
This force reannounce isn't necessary since it can cause issues by doing unnecessary reannounce during startup and network address refresh.
The impact of this unnecessary call can be great if it happens on a regular basis and if someone has a lot of torrents.
If someone changes their port because it was a blacklisted one(by a pvt tracker), it's required only once, and such a thing can't warrant a force reannounce for all users just on receiveing this alert. This alert can be posted many times during session startup and due to interface/IP refresh.
If strictly necessary, they may enable the option of "Reannounce to all trackers when IP or port changed" from advanced settings.
> Remove unnecessary force reannounce on interface alerts

- src/app/application.cpp
- src/app/application.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/webui/www/private/views/preferences.html
You can already control the cache size in libtorrent 1.2.x so it doesn't make sense to implement this limit for all use cases. Also there are some downsides to using working set size to limit memory usage such as unresponsive GUI when limit gets hit.
> Make working set limit available only on libtorrent 2.0.x builds

- src/app/application.cpp
- src/app/application.h
The goal is to improve responsiveness of qbt when CPU resources are scarce.
Instead of lowering libtorrent threads priority, it is chosen to raise main event loop thread priority to avoid getting messy with libtorrent internals.
Also on Windows, threads doesn't inherit thread priority from the parent thread and it always use the default (normal) priority.
> Raise priority of the main "event loop" thread

- src/gui/macutilities.mm
- src/gui/transferlistwidget.cpp
actually 2 issues where fixed (see commit messages for details):
- the issue caused crash (the second commit)
- incorrect path was passed to openFiles()
`Torrent::contentPath()` already returns correct abolute path to the torrent content, it considers any possible situations
existing code tried to append some "prefix" and that lead to not existing "slightly duplicated" path like
```txt
"/Users/nickkorotysh/Downloads/Users/nickkorotysh/Downloads/ubuntu-22.04-desktop-amd64.iso"
```
so destination folder was not opened in any case (but no crash happens in such case)
crash was not actually fixed, its source somewhere deep in Qt, just some workaround added, see corresponding comment in the code.
[build](https://www.dropbox.com/s/ugjelspx01ewefk/qBittorrent-master-macOS-universal.dmg?dl=0) was …
> Fix "Open destination folder" on macOS

- src/app/application.cpp
- src/app/application.h
- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/bencoderesumedatastorage.cpp
- src/base/bittorrent/bencoderesumedatastorage.h
- src/base/bittorrent/dbresumedatastorage.cpp
- src/base/bittorrent/resumedatastorage.cpp
- src/base/bittorrent/resumedatastorage.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/rss/rss_autodownloader.cpp
- src/base/torrentfileswatcher.cpp
- src/base/torrentfileswatcher.h
- src/gui/categoryfiltermodel.cpp
- src/gui/categoryfiltermodel.h
- src/gui/mainwindow.cpp
- src/gui/search/searchjobwidget.cpp
- src/gui/tagfiltermodel.cpp
- src/gui/tagfiltermodel.h
- src/gui/transferlistfilterswidget.cpp
- src/gui/transferlistfilterswidget.h
- src/gui/transferlistmodel.cpp
- src/gui/transferlistmodel.h
Reduce the total startup time of the application and maintain sufficient responsiveness of the UI during startup due to the following:
1. Load resume data from disk asynchronously in separate thread,
2. Split handling of loaded resume data in chunks,
3. Reduce the number of emitting signals.
> Improve startup

- src/base/bittorrent/session.cpp
Tags can go missing from config/resume data. Try to recover them to avoid inconsistent behavior.
Inspiration taken from https://github.com/qbittorrent/qBittorrent/pull/16430 with due thanks to @glassez 
Closes https://github.com/qbittorrent/qBittorrent/issues/17289.
Closes https://github.com/qbittorrent/qBittorrent/issues/16710.
> Try to recover missing tags

- src/base/preferences.cpp
- src/base/preferences.h
- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.ui
- src/gui/uithememanager.cpp
- src/gui/uithememanager.h
As discussed in #15769, Linux support for System theme is getting removed.
Closes: #17150
> Remove option of using icons from system theme

- src/app/application.cpp
- src/app/application.h
- src/app/upgrade.cpp
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/interfaces/iapplication.h
- src/gui/advancedsettings.cpp
* Move "memory priority" settings to Application class
* Work around application stuttering on Windows
This is observed by unusual high page faults when the stuttering occurs.
With this workaround, the high page faults still occurs but the GUI remains responsive.
Will back port the second commit after this PR is merged.
> Work around application stuttering on Windows

- dist/docker/Readme.md
- src/gui/CMakeLists.txt
- src/gui/search/searchwidget.cpp
- src/gui/torrentoptionsdialog.cpp
- src/gui/transferlistwidget.cpp
- src/webui/api/synccontroller.cpp
- src/webui/api/torrentscontroller.cpp
Found via `codespell -q 3 -S *.ts,*.desktop,./src/base/3rdparty,./dist/windows/installer-translations -L ba,doas,ist,ro,ths`
> Fix various typos

- src/app/application.cpp
- src/app/application.h
- src/gui/CMakeLists.txt
- src/gui/advancedsettings.cpp
- src/gui/desktopintegration.cpp
- src/gui/desktopintegration.h
- src/gui/gui.pri
- src/gui/interfaces/iguiapplication.h
- src/gui/mainwindow.cpp
- src/gui/mainwindow.h
- src/gui/search/searchwidget.cpp
This PR is prerequisite for making possible to indicate only application loading progress until the BitTorrent session is fully restored.
It extracts desktop integration stuff (like tray icon, macOS dock and desktop notifications support) into separate class.
> Extract desktop integration stuff into separate class

- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.h
* Revise behavior of initializing checkboxes
The checkboxes initial value should not depend on parent state and should be restored anyway.
* Add tooltip message when system tray icon isn't available
Also don't hide the sub-options as they are already in disabled state.
* Don't needlessly hide Options dialog
The dialog should only close after all operations are done, not before.
> Revise behavior of initializing checkboxes

- unixconf.pri
The `/usr/share/pixmaps` location is considered a legacy location for
application icons; since the application icons are already installed in
the global XDG hicolor theme, then simply stop installing the 128px one
in the legacy pixmaps location.
> Stop installing app icon in pixmaps location

- src/base/rss/rss_autodownloader.cpp
Fix PVS-Studio issue "rss_autodownloader.cpp:111: warning: V668
There is no sense in testing the 'm_fileStorage' pointer against null,
as the memory was allocated using the 'new' operator.
The exception will be generated in the case of memory allocation error".
> Remove meaningless checking for nullptr

- src/base/bittorrent/torrentimpl.cpp
- src/base/bittorrent/torrentimpl.h
* Add workaround for payload upload/download rate
The graphs are showing 0 for both payload upload & download rate but torrent statistics aren't, so suppress it manually.
Closes https://github.com/qbittorrent/qBittorrent/issues/17294.
* Rename variable
> Add workaround for payload upload/download rate

- CMakeLists.txt
- INSTALL
- configure
- configure.ac
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/webui/api/appcontroller.cpp
- src/webui/www/private/views/preferences.html
* Bump libtorrent requirements to 2.0.6
* Split the OS cache settings into Disk IO read/write modes
> Split the OS cache settings into Disk IO read/write modes

- .github/workflows/ci_macos.yaml
- .github/workflows/ci_ubuntu.yaml
- .github/workflows/ci_windows.yaml
- .github/workflows/coverity-scan.yml
Update libtorrent to 2.0.7 & 1.2.17 in GHA CI
- https://github.com/arvidn/libtorrent/releases/tag/v2.0.7
- https://github.com/arvidn/libtorrent/releases/tag/v1.2.17
> Update libtorrent to 2.0.7 & 1.2.17 in GHA CI

- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.h
Instead of showing dialog, now it relies on icon to show the validation result.
> Don't show validation result dialog on every key input

- src/app/application.cpp
- src/gui/mainwindow.cpp
Fixes regression of #17313.
Also moves some logic to appropriate place.
> Prevent tray menu from being accessed after destruction

- src/gui/addnewtorrentdialog.ui
- src/gui/properties/propertieswidget.cpp
Done by adding an QScrollArea to the layout.
Closes #17387.
[Screenshot](https://user-images.githubusercontent.com/9395168/180130914-22d44423-7477-4174-bd01-f4bce85df209.png)
> Fix "Add torrent dialog" spill-over on smaller screens

- src/gui/fspathedit.cpp
- src/gui/fspathedit.h
- src/gui/fspathedit_p.cpp
- src/gui/fspathedit_p.h
* Improve performance of "filesystem line edit" widgets
Also prevent unnecessary querying on the filesystem by omitting calling setRootPath().
* Fix path validator
And revise tooltip message.
Closes https://github.com/qbittorrent/qBittorrent/issues/11152.
* Avoid redundant operation
The default is the same as the one specified here.
* Rename interface
* Simplify operations
* Use less intimidating icon for intermediate state
> Fix path validator

- src/base/path.cpp
- src/base/path.h
- src/base/utils/fs.cpp
- src/gui/addnewtorrentdialog.cpp
- src/webui/webapplication.cpp
* Simplify implementation
This also enable each platform to provide its own optimal implementation of it.
* Revise function for checking "same file"
* Improve free disk space reporting
For non-existent directories (which will be created on demand) `Utils::Fs::freeDiskSpaceOnPath` will return invalid value so instead query its parent path.
* Remove compile-time conditional
This checking should be universally applied and not limited to certain OS.
> Improve free disk space reporting

- src/base/bittorrent/torrent.h
- src/base/bittorrent/torrentimpl.cpp
- src/base/bittorrent/torrentimpl.h
sometimes tracker may respond with 0 for num_complete and num_incomplete and we should display that instead of deducing the peer count from peer list. We should only fallback to peer list if tracker does not respond with any information. In such cases num_incomplete and num_complete is set to -1 by libtorrent.
closes https://github.com/qbittorrent/qBittorrent/issues/10685
reference:
https://libtorrent.org/reference-Torrent_Status.html#num_incomplete
> Fix peer count issue when tracker responds with zero figure

- src/base/net/downloadhandlerimpl.cpp
- src/base/net/downloadmanager.cpp
Fix #17420
Relate to #17120
Let QT handle the reply data if compression/decompression is support.
Test with QT 6.3.1 and 5.15.5. ~~May need some tests if `-no-zlib` is set when QT is complied.~~
> Fix reply data can't be decompressed correctly

- src/base/bittorrent/session.cpp
- src/gui/addnewtorrentdialog.cpp
When duplicate torrent is added don't merge trackers by default.
It doesn't seem like a good idea to perform such an action behind the scenes since the user can have deleted some trackers previously and then add the duplicated torrent by mistake.
<del>The GUI has been left untouched for now, because</del> it would be better not just to remove it from GUI, but to add some advanced tracker merge dialog, as requested by some users (a task for a separate PR). Currently simple confirmation dialog is shown to the user.
> Don't merge trackers by default

- src/app/application.cpp
- src/app/cmdoptions.cpp
- src/base/utils/string.cpp
- src/base/utils/string.h
- test/CMakeLists.txt
- test/testutilsstring.cpp
* Translate app help text
* Fix empty string parameter was omitted
`QProcess::splitCommand()` will omit empty strings like `""` so provide
our own replacement.
Closes #13124.
> Fix empty string parameter was omitted

- dist/docker/Readme.md
Currently Docker Inc. recommends installing Docker Desktop instead of the CLI.
`docker-compose` has been deprecated, replaced by `docker compose`.
> Revise Docker document

- src/base/bittorrent/session.cpp
Fixes regression of #16840.
Closes #17435.
> Prevent multiple session refreshes from being enqueued

- src/base/rss/rss_parser.cpp
Maybe related to #17399.
Should be backported to v4.4.x branch.
> Clear RSS parsing error after use

- src/base/utils/version.h
- src/gui/utils.cpp
- test/CMakeLists.txt
- test/testutilsversion.cpp
* Improve command for running test
It enables `make check` command to build tests and run it altogether.
* Improve constructor 
Now we can write `Version<int, 3, 1>(1)` and provide only 1 parameter instead of all 3 parameters at once at the constructor. Note that for this instance of `Version` 3 numbers were specified but only 1 is truly mandatory.
The added code are required to specify conditions of the template instantiation for the compiler.
> Improve constructor of Version class

- src/base/bittorrent/nativesessionextension.cpp
- src/base/bittorrent/nativetorrentextension.cpp
libtorrent < 2.0.7 has a bug that `add_torrent_alert` is posted too early (before torrent is fully initialized and torrent extensions are created) so we have to fill initial torrent data in `add_torrent_alert` handler.
> Fill in initial data in `add_torrent_alert` handler

- src/app/application.cpp
- src/gui/mainwindow.cpp
Fix possible crash during first run on Windows.
Also fix bug of incorrectly replaced desktop integration menu (reported in https://github.com/qbittorrent/qBittorrent/pull/17389#issuecomment-1207136347).
> Avoid race conditions between dialogs on startup
