qbittorrent/qBittorrent

src/base/filesystemwatcher.cpp
src/base/filesystemwatcher.h
src/webui/api/appcontroller.cpp
src/webui/www/private/views/preferences.html

* Revise folder monitoring functions in WebUI
No visual changes are introduced.

Revise folder monitoring functions in WebUI

---

src/webui/www/private/scripts/client.js

WebUI: Fix magnet url from the browser

---

dist/windows/installer-translations/english.nsi
dist/windows/installer-translations/italian.nsi
dist/windows/installer.nsi

@glassez 
Please check and merge. Thanks.

Uninstall icon description multilanguage

---

src/base/rss/rss_parser.cpp
src/gui/programupdater.cpp

A small cleanup that makes the code a little more compatible with Qt6.

Enclose strings in QLatin1String

---

src/base/filesystemwatcher.cpp
src/base/filesystemwatcher.h
src/gui/trackerentriesdialog.ui
src/gui/translators.html
src/webui/api/appcontroller.cpp
src/webui/www/private/scripts/client.js
src/webui/www/private/views/preferences.html
src/webui/www/private/views/search.html

* PR #14624
* PR #14637
* PR #14645
* PR #14676
* PR #14703

Backport to v4_3_x

---

src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/gui/mainwindow.cpp
src/gui/mainwindow.h

Add "Notification timeout" option

---

src/base/net/dnsupdater.cpp
src/gui/mainwindow.cpp
src/webui/api/torrentscontroller.cpp
src/webui/webapplication.h

Included PRs:
#14792
#14794
#14795

Backport PRs to v4_3_x

---

src/base/bittorrent/peerinfo.cpp

* Capitalize "peer flags" descriptions
And use a helper function to build the descriptions.
* Reorder peer flags
Now we group related flags nearby.

Capitalize "peer flags" descriptions

---

src/gui/progressbarpainter.cpp

Correctly draw progress background with stylesheet

---

src/app/application.cpp
src/base/CMakeLists.txt
src/base/base.pri
src/base/bittorrent/addtorrentparams.h
src/base/bittorrent/bencoderesumedatastorage.cpp
src/base/bittorrent/torrent.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h
src/base/orderedset.h
src/base/tagset.cpp
src/base/tagset.h
src/gui/tagfiltermodel.cpp
src/gui/tagfiltermodel.h
src/gui/transferlistmodel.cpp
src/gui/transferlistsortmodel.cpp
src/gui/transferlistwidget.cpp
src/webui/api/serialize/serialize_torrent.cpp
src/webui/api/serialize/serialize_torrent.h
src/webui/api/torrentscontroller.cpp

Revise tag related implementations

---

dist/mac/Info.plist
src/app/CMakeLists.txt

backport #14813 to v4_3_x
just cherry-picked 28ef33b0a0e49b9869d77e61d09971062f09499c

Improve Info.plist generation with CMake (v4_3_x backport)

---

dist/windows/installer-translations/japanese.nsi

NSIS: Update Japanese translation

---

dist/windows/installer-translations/turkish.nsi

NSIS: Update Turkish translation

---

src/webui/www/private/views/preferences.html
src/webui/www/private/views/rss.html
src/webui/www/private/views/search.html

Make some strings in WebUI translatable

---

src/gui/properties/piecesbar.cpp

Creating new PR as suggested by Chocobo1. These typos where not fixed in #14928.

Fix typo "Highlited"

---

src/gui/search/searchwidget.cpp
src/gui/search/searchwidget.h

Closes #5628.
My very first PR on github

Add context menu for searchwidget to allow closing selected tab or all the tabs

---

.appveyor.yml

Update AppVeyor CI image to Visual Studio 2019.

Update AppVeyor CI image to Visual Studio 2019

---

cmake/Modules/MacroQbtCommonConfig.cmake

~The second commit is from the ongoing discussion happening here: https://github.com/qbittorrent/qBittorrent/discussions/14980#discussioncomment-764153.~ Extracted to a separate PR for further discussion: https://github.com/qbittorrent/qBittorrent/pull/15012
The first commit fixes an existing bug I found while implementing the changes from the second commit.

CMake: Fix compiler ID checks

---

src/gui/mainwindow.cpp

Fix #9510.
@qbittorrent/frequent-contributors 
I only briefly tested it, please try it out and see if there are any regressions.

Fix main window turns blank after restoring from tray

---

src/base/bittorrent/magneturi.cpp
src/base/bittorrent/session.cpp
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentinfo.cpp
src/base/logger.cpp
src/gui/log/logmodel.cpp
src/gui/tagfiltermodel.cpp

- warning C4267: 'initializing': conversion from 'size_t' to 'int',
possible loss of data

Suppress C4267 conversion warnings

---

src/app/qtlocalpeer/qtlocalpeer.cpp

Remove lockfile only when last app instance is destroyed

---

src/base/bittorrent/session.cpp

First, an attempt is made to add new tags to the Session.
Closes #15105.

Properly add torrent with new tags

---

src/base/bittorrent/bencoderesumedatastorage.cpp
src/base/bittorrent/dbresumedatastorage.cpp
src/base/bittorrent/session.cpp
src/base/bittorrent/torrentcreatorthread.cpp
src/base/bittorrent/torrentcreatorthread.h
src/base/bittorrent/torrentinfo.cpp
src/gui/addnewtorrentdialog.cpp

Related to #15109 (and #14272).

Handle exception when torrent file cannot be exported

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.ui

Related libtorrent issue: https://github.com/arvidn/libtorrent/issues/6283.

Use torrent info with hashes for creating .torrent file

---

src/webui/api/torrentscontroller.cpp

This new parameter is optional and works like 'category'.
The wiki needs to be updated.

WebAPI: Provide filtering torrents by tag

---

src/base/torrentfileswatcher.cpp
src/gui/watchedfoldersmodel.cpp

Backport changes to v4.3.x branch

---

src/base/torrentfilter.cpp
src/base/torrentfilter.h
src/gui/transferlistfilterswidget.cpp
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/views/filters.html

Add filter "Checking" to side panel

---

src/webui/www/private/scripts/dynamicTable.js

This PR allows for sorting Web UI tables when on a mobile device.

Support sorting Web UI tables via touch

---

src/webui/www/private/scripts/client.js

fix https://github.com/qbittorrent/qBittorrent/issues/13608
Desktop UI
Current - WebUI 
With this patch

WebUI: group trackers by hostname

---

src/base/torrentfileswatcher.cpp

Fixes regression of #14882.
Closes #15272.

Delay processing of watched folders

---

cmake/Modules/MacroQbtCommonConfig.cmake
src/CMakeLists.txt

Fix up 138c911ef45886fb9d4805e28a5dfe8afa8cf09a.
I thought the CI would have tested that, now I really tested it locally.

Fix cmake script

---

src/webui/api/serialize/serialize_torrent.cpp

Improve "last activity" calculation in WebAPI

---

src/gui/addnewtorrentdialog.ui

Remove unnecessary UI properties in "Add new torrent" dialog

---

src/webui/www/private/scripts/client.js

Fix WebUI crash when tracker URL is invalid

---

src/base/net/downloadhandlerimpl.cpp
src/base/net/downloadmanager.cpp
src/base/net/downloadmanager.h
src/base/rss/rss_feed.cpp
src/gui/rss/feedlistwidget.cpp

Fix invalid RSS feed icons 

---

src/gui/properties/propertieswidget.cpp

Fix broken behavior of "priority by shown file order"

---

src/base/torrentfileswatcher.cpp
src/gui/watchedfolderoptionsdialog.cpp
src/gui/watchedfolderoptionsdialog.ui

Add "Skip hash check" option for watched folders

---

src/base/preferences.cpp
src/base/preferences.h

* Suppress function unused warning
* Remove redundant const specifier

Clean up Preferences class

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/coverity-scan.yml

* Remove redundant dependencies
* Replace ccache action provider
* Let coverity-scan script build with libtorrent v2.0.4.

CI: Clean up scripts

---

configure
configure.ac

* Add detection for OpenBSD in configure script
Patch taken from downstream:
http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/net/qbittorrent/qbittorrent/patches/patch-configure_ac
* Add detection for Haiku in configure script
Patch taken from downstream:
https://github.com/haikuports/haikuports/blob/master/net-p2p/qbittorrent/patches/qbittorrent-4.3.1.patchset
* Use case statement for host OS detection

Add detection for various OS

---

src/base/CMakeLists.txt
src/base/base.pri
src/base/bittorrent/abstractfilestorage.h
src/base/bittorrent/lttypecast.h
src/base/bittorrent/session.cpp
src/base/bittorrent/torrent.h
src/base/bittorrent/torrentcreatorthread.cpp
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h
src/base/bittorrent/torrentinfo.cpp
src/base/bittorrent/torrentinfo.h
src/gui/addnewtorrentdialog.cpp
src/gui/previewselectdialog.cpp
src/gui/torrentcontentmodel.cpp
src/gui/torrentcontentmodelfolder.cpp
src/gui/transferlistwidget.cpp

Improve torrent content handling

---

src/gui/transferlistsortmodel.cpp
src/searchengine/nova3/socks.py

Found via `codespell -q 3 -S *.ts`

Fix various typos

---

cmake/Modules/MacroQbtCommonConfig.cmake
macxconf.pri
src/base/utils/fs.cpp

Don't use deprecated statfs64() on macOS

---

src/app/application.cpp
src/app/application.h
src/base/bittorrent/portforwarderimpl.cpp
src/base/bittorrent/portforwarderimpl.h
src/base/net/proxyconfigurationmanager.cpp
src/base/net/proxyconfigurationmanager.h
src/base/rss/rss_autodownloader.cpp
src/base/rss/rss_autodownloader.h
src/base/rss/rss_session.cpp
src/base/rss/rss_session.h
src/base/settingsstorage.h
src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.h
src/gui/mainwindow.cpp
src/gui/mainwindow.h
src/gui/watchedfolderoptionsdialog.cpp

Also add `QFlags<T>` support to `SettingsStorage`.

Migrate away from low-level `SettingsStorage` class

---

src/app/qtlocalpeer/qtlocalpeer.cpp
src/app/qtlocalpeer/qtlocalpeer.h
src/app/qtlocalpeer/qtlockedfile.cpp
src/app/qtlocalpeer/qtlockedfile.h
src/app/qtlocalpeer/qtlockedfile_unix.cpp
src/app/qtlocalpeer/qtlockedfile_win.cpp
src/base/bittorrent/torrentimpl.cpp
src/base/preferences.cpp
src/base/utils/misc.cpp
src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.h
src/gui/cookiesdialog.cpp
src/gui/cookiesdialog.h
src/gui/previewselectdialog.cpp

* Store Qt6 table header states under a different key
* Reformat code

Store Qt6 table header states under a different key

---

src/gui/properties/proplistdelegate.cpp

Apply download priority immediately in torrent content view

---

.appveyor.yml
.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/ci_windows.yaml
.github/workflows/coverity-scan.yml

* Appveyor CI: Setup build environment directly
* GHA CI: Simplify commands

GHA CI: Simplify commands

---

.appveyor.yml
.github/workflows/ci_windows.yaml

* Appveyor CI: Upload built artifacts
* GHA CI: Use prebuilt Qt library

GHA CI: Use prebuilt Qt library

---

src/base/http/requestparser.cpp

Closes #15754.
For testers: please test if the webUI is still working as usual, nothing should break.

Fix handling when Content-Length field is absent

---

src/base/bittorrent/infohash.h
src/base/bittorrent/ltqhash.h
src/base/bittorrent/torrentimpl.cpp
src/base/digest32.h
src/base/utils/misc.cpp
src/base/utils/version.h
src/gui/categoryfiltermodel.cpp
src/gui/fspathedit.h

Disclaimer: Before anyone is hyped on this, there are a lot of other warnings that I choose not to fix because false-positive or too intrusive.

Fix defects found by clazy

---

src/app/upgrade.cpp
src/base/bittorrent/bandwidthscheduler.cpp
src/base/net/dnsupdater.cpp
src/base/net/dnsupdater.h
src/base/preferences.cpp
src/base/preferences.h
src/gui/mainwindow.cpp
src/gui/optionsdialog.cpp
src/webui/api/appcontroller.cpp
src/webui/api/synccontroller.cpp

Affected settings will be migrated to new keys so nothing should break.

Store enum type in settings directly

---

src/app/application.cpp

Use correct URL scheme when https is enabled

---

src/gui/optionsdialog.cpp
src/gui/optionsdialog.h
src/gui/optionsdialog.ui
src/gui/transferlistwidget.cpp

Add "Show torrent options" double-click action

---

src/app/main.cpp
src/app/upgrade.cpp
src/app/upgrade.h
src/base/settingsstorage.cpp

* Migrate "setting key mappings" to upgrade code
* Set appropriate migration version number for new installations

Migrate "setting key mappings" to upgrade code

---

src/base/bittorrent/session.cpp
src/base/bittorrent/torrentimpl.cpp
src/base/rss/rss_feed.cpp
src/gui/addnewtorrentdialog.cpp
src/gui/properties/downloadedpiecesbar.cpp
src/gui/properties/pieceavailabilitybar.cpp
src/gui/rss/automatedrssdownloader.cpp
src/gui/rss/automatedrssdownloader.h
src/gui/search/searchwidget.cpp
src/gui/speedlimitdialog.cpp
src/gui/torrentoptionsdialog.cpp

* Replace QPair with std::pair
* Replace min, max, clamp functions with std counterparts

Replace Qt functions with std counterparts

---

src/gui/optionsdialog.cpp
src/gui/uithememanager.cpp
src/gui/uithememanager.h

fixes #12142 
v2:
Replaced the folder-based option with a selection of config.json
v1:
GUI changes **(not applicable anymore)**

Support folder based Themes

---

src/base/bittorrent/categoryoptions.cpp
src/gui/addnewtorrentdialog.cpp
src/gui/torrentcategorydialog.cpp

The compiler warnings were introduced in #15793.

Supress compiler warnings

---

dist/mac/Info.plist
dist/windows/options.nsi
src/base/bittorrent/torrentcontentlayout.cpp
src/gui/aboutdialog.cpp
src/qbittorrent.rc
src/webui/www/private/views/about.html

I considered force pushing these trivial changes, but I realized I wouldn't have time to finalize the release anyway(with uploaded builds).
And since I am going to sleep now, here it is for a courtesy review.
~Final v4.4.0 will be done later in the day of 2022-01-04.~
msvc2017 can't compile it without the added namespace.

Misc fixes before v4.4.0

---

src/base/torrentfileswatcher.cpp

Correctly handle Auto TMM in Torrent Files Watcher

---

src/base/bittorrent/torrentimpl.cpp

Don't try to move storage into its current location

---

src/app/upgrade.cpp

Q_ENUM_NS(ProxyType) was introduced in 4.4.0.
Before that wrapping QMetaEnum used the int value itself for loading/storing.
Closes #15994

Migrate proxy settings

---

src/gui/torrentoptionsdialog.cpp
src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h

- Update the torrent's download path field when changing category
- Restore all settings to the torrent list's context menu

Backport 4.4.x

---

src/gui/transferlistwidget.cpp

Regression from 0086bf895806346e701cfe56f18fd0b5bdde41ab

Fix wrong closing brace position

---

src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.h
src/gui/categoryfilterwidget.cpp
src/gui/categoryfilterwidget.h
src/gui/executionlogwidget.cpp
src/gui/executionlogwidget.h
src/gui/mainwindow.cpp
src/gui/mainwindow.h
src/gui/previewselectdialog.cpp
src/gui/previewselectdialog.h
src/gui/properties/peerlistwidget.cpp
src/gui/properties/peerlistwidget.h
src/gui/properties/propertieswidget.cpp
src/gui/properties/propertieswidget.h
src/gui/properties/trackerlistwidget.cpp
src/gui/properties/trackerlistwidget.h
src/gui/rss/rsswidget.cpp
src/gui/rss/rsswidget.h
src/gui/search/pluginselectdialog.cpp
src/gui/search/pluginselectdialog.h
src/gui/search/searchjobwidget.cpp
src/gui/search/searchjobwidget.h
src/gui/tagfilterwidget.cpp
src/gui/tagfilterwidget.h
src/gui/transferlistfilterswidget.cpp
src/gui/transferlistfilterswidget.h
src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h

* Clean up code related to show/hide columns
* Add "Resize columns" functionality 
* Make use of std algorithms
Since the result code is shorter.

Add "Auto resize columns" functionality

---

src/base/bittorrent/infohash.cpp
src/base/bittorrent/infohash.h
src/base/bittorrent/session.cpp
src/base/digest32.h

Store hybrid torrents using legacy filenames

---

src/base/bittorrent/infohash.cpp
src/base/bittorrent/infohash.h
src/base/bittorrent/session.cpp
src/base/digest32.h

This PR is satellite of #16237 for v4.5.x.

Store hybrid torrents using "torrent ID" as basename

---

src/base/bittorrent/session.cpp

When you move torrent to some location and then move it back while previous "move job" isn't started yet it will just cancelled. Currently torrent still shows "moving" in this case. This patch should fix it.
Also fixes iterator from being dereferenced after item is erased.

Change torrent moving state when it is cancelled

---

src/base/CMakeLists.txt
src/base/base.pri
src/base/bittorrent/ltqbitarray.cpp
src/base/bittorrent/ltqbitarray.h
src/base/bittorrent/peerinfo.cpp
src/base/bittorrent/torrentimpl.cpp

The old code took 3~5 times longer than the newer version.

Speed up bitfields conversion

---

src/gui/properties/propertieswidget.cpp

Fixes regression from f44341a8e26f078b8d1921824bf6d88a9c97f135.

Allow to open incomplete files from content view

---

src/base/bittorrent/torrentimpl.cpp

Improve tracker error handling

---

src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h

Optimize handleFileCompletedAlert

---

src/webui/www/private/css/Window.css

From PR #16408 to fix CI failures.

Remove hack for outdated IE 6 browser (backport)

---

src/base/bittorrent/ltqbitarray.cpp
src/base/path.cpp

* Improve Path constructor performance
* Fix wrong size
Fix up https://github.com/qbittorrent/qBittorrent/commit/cf96e6c64266bf11ba9cf3dc7d2eaf7628c6d7a9.

Improve Path constructor

---

src/base/bittorrent/session.cpp

Try to recover missing categories

---

.github/workflows/ci_webui.yaml

* Update "WebUI" `setup-node` action to `v3`
* https://github.com/actions/setup-node/releases

GHA CI: Update "WebUI" `setup-node` action to `v3`

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/webui/api/appcontroller.cpp
src/webui/webapplication.h
src/webui/www/private/views/preferences.html

Add tuning options related to performance warnings

---

src/gui/transferlistwidget.cpp

Fix scrolling to the lowermost visible torrent

---

src/base/bittorrent/session.cpp
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h
src/gui/optionsdialog.ui

Correctly handle changing of global save path

---

.github/workflows/ci_file_health.yaml
.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/ci_webui.yaml
.github/workflows/ci_windows.yaml

Fix up https://github.com/qbittorrent/qBittorrent/commit/2652c73a4fabd7bb85916e99c289dc58cad8f895.

GHA CI: Don't cancel CI builds on non-pull-request branches

---

src/app/filelogger.cpp
src/app/upgrade.cpp
src/base/bittorrent/bencoderesumedatastorage.cpp
src/base/bittorrent/session.cpp
src/base/bittorrent/torrentimpl.cpp
src/base/global.h
src/base/http/requestparser.cpp
src/base/http/types.h
src/base/net/geoipmanager.cpp
src/base/path.cpp
src/base/path.h
src/base/profile_p.cpp
src/base/search/searchdownloadhandler.cpp
src/base/search/searchhandler.cpp
src/base/search/searchpluginmanager.cpp
src/base/utils/fs.cpp
src/gui/aboutdialog.cpp
src/gui/addnewtorrentdialog.cpp
src/gui/mainwindow.cpp
src/gui/rss/htmlbrowser.cpp
src/gui/torrentcreatordialog.cpp
src/gui/uithememanager.cpp
src/webui/webapplication.cpp

The plan is to define QT_NO_CAST_FROM_ASCII eventually.
Note that this conversion would be performed in multiple PR.

Use QString literals

---

src/gui/transferlistwidget.cpp

and allow it even if torrent doesn't have complete metadata.
closes #12080
Edit: One problem I notice is that if you select multiple torrents and if some can't force reannounce, then the option will be unavailable. This may be problematic to some people who want to select everything regardless and have force reannounce available to them.
Edit 2: I think I solved that problem by showing force reannounce always if user selected multiple torrents(even if the action is impossible).
Edit 3: Now the option will show if one of the selected torrents can be force reannounced.

Disable force reannounce when it is not possible

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/base/bittorrent/torrentimpl.cpp
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/webui/api/appcontroller.cpp
src/webui/webapplication.h
src/webui/www/private/views/preferences.html

[screenshot](https://user-images.githubusercontent.com/9395168/156868931-5bb1d20b-5d4b-4074-9495-42650e14c24f.png)
Supersedes #16548.

Allow setting the number of maximum active checking torrents

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/base/bittorrent/torrent.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h
src/base/digest32.h
src/gui/transferlistfilterswidget.cpp
src/gui/transferlistfilterswidget.h

avoids quadratic paths in filters handling, PR should be helpful for users with the large number of torrents.

Optimize torrent filters in GUI

---

src/gui/transferlistfilterswidget.cpp
src/gui/transferlistfilterswidget.h

Fix up 30319e51e55ed7740b7bdc4b75563f441f9ccb71.

Avoid unnecessary lookups

---

src/base/bittorrent/session.cpp
src/base/bittorrent/torrentimpl.cpp

Closes several crash related Issues.

Prevent loading resume data with inconsistent ID

---

src/base/bittorrent/session.cpp

Fix up d26e582cc185889d82d00fabbf39d54d2f02e9ec.
Closes #16655.

Add back erroneously removed alert handler

---

src/gui/search/searchjobwidget.ui

And revise tooltip messages.
Note: it should have no visible changes except the tooltips.

Remove redundant properties

---

src/gui/properties/proptabbar.cpp

https://github.com/qbittorrent/qBittorrent/issues/11031#issuecomment-1066523943

Allow PropTabBar buttons to be focusable

---

src/gui/optionsdialog.cpp
src/gui/speedlimitdialog.cpp

Screenshots: [before](https://user-images.githubusercontent.com/9395168/158005036-8d3937e0-066e-41c8-b606-576a42a35853.png), [after](https://user-images.githubusercontent.com/9395168/158005034-a076af78-eb92-44d0-932b-32abc26977fc.png)
Supersedes PR #16533.

Enlarge "speed limits" icons

---

src/base/bittorrent/session.cpp
src/base/bittorrent/torrentimpl.cpp

Backport changes to v4.4.x branch

---

src/gui/utils.cpp

It uses the same workaround as Qt does to call `ShellExecute()` when you use `QDesktopServices::openUrl()`.
Closes #16423.

Prevent crash when open torrent destination folder

---

src/base/digest32.h

Delayed hash string generation should not cause detaching of shared data so Digest32 is revamped to prevent it.
Fixes regression from ad6e2b4b9439744b4939cf2b449e0c5fd2253e6c.

Prevent Digest32 shared data from being detached

---

src/base/preferences.cpp
src/base/preferences.h
src/gui/mainwindow.cpp
src/gui/mainwindow.h
src/gui/mainwindow.ui
src/webui/www/private/index.html
src/webui/www/private/scripts/client.js

No substantial changes have been made from the original PR #10933.
I'll open a review for issues left to discuss.

Add toggleable Filters Sidebar option to View Menu Bar

---

src/gui/properties/trackerlistwidget.cpp
src/gui/transferlistwidget.cpp
src/webui/api/synccontroller.cpp

Also fixes some compilation issues due to inappropriate QString usage.

Fix "Set location" to be really applied

---

src/app/application.cpp
src/app/qtlocalpeer/qtlockedfile_win.cpp
src/app/stacktrace_win.h
src/base/bittorrent/session.cpp
src/base/utils/foreignapps.cpp
src/base/utils/misc.cpp
src/base/utils/misc.h
src/gui/torrentcontentmodel.cpp
src/gui/utils.cpp

Don't use explicit memory management (backport)

---

src/webui/www/private/scripts/client.js

Fix WebUI crash due to missing tags from config (backport)

---

src/base/bittorrent/dbresumedatastorage.cpp

Also repairs currently corrupted database.

Don't forget to create 'download_path' field

---

src/gui/transferlistfilterswidget.cpp

Closes #16792.
Fixes regression of #16587.

Correctly populate trackers filter list

---

src/gui/mainwindow.cpp
src/gui/transferlistwidget.cpp

Use an appropriate method to show modal dialog

---

src/base/bittorrent/session.cpp

Correctly apply content layout when "Skip hash check" is enabled

---

src/app/application.cpp
src/base/search/searchhandler.cpp
src/gui/mainwindow.cpp

* Remove redundant function
This helper function is useless after using `Path` class.
* Use proper method for deferred calls

Remove redundant function

---

src/app/application.cpp
src/app/application.h
src/base/CMakeLists.txt
src/base/base.pri
src/base/interfaces/iapplication.h
src/gui/CMakeLists.txt
src/gui/advancedsettings.cpp
src/gui/gui.pri
src/gui/interfaces/iguiapplication.h
src/gui/optionsdialog.cpp

I aim to revive #16576 but there was an unwanted dependency on `QApplication` so this PR is a prerequisite.

Provide interface for Application class

---

src/app/application.cpp
src/app/application.h
src/base/interfaces/iapplication.h
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/webui/api/appcontroller.cpp
src/webui/webapplication.h
src/webui/www/private/views/preferences.html

Allow to set "working set limit" on non-Windows OS

---

src/base/bittorrent/session.cpp

Closes #16884 and similar issues.

Avoid dereferencing null pointers

---

src/base/bittorrent/infohash.cpp
src/base/bittorrent/infohash.h
src/base/bittorrent/torrent.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h
src/base/bittorrent/torrentinfo.cpp
src/base/bittorrent/torrentinfo.h
src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h

* Remove unused header
* Add "Export .torrent" action
[screenshot](https://user-images.githubusercontent.com/9395168/163668013-8cc1c34d-5c4a-49cc-98d4-109bf873145c.png)

Add "Export .torrent" action

---

dist/docker/Dockerfile
dist/docker/Readme.md
dist/docker/entrypoint.sh

Docker image for qBittorrent-nox, based on alpine linux
the old pull request #11138 for the dockerfile was old, had many issues and the person who submitted it lost the interest in maintaining it
subsequently a bot closed the pull request, this dockerfile implements the fixes requested in the previous pull request
closes #11128

Add Dockerfile

---

src/app/main.cpp
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/setlocation.html

Backport selected commits from:
#16784
#16941

Fix nogui compilation for Windows (Backport)

---

src/app/CMakeLists.txt
src/app/app.pri
src/app/main.cpp
src/app/signalhandler.cpp
src/app/signalhandler.h

And revise "signal safe print" function.

Move system signal related functions to its own file

---

src/gui/optionsdialog.ui

Increase limit of maximum number of articles per feed

---

dist/docker/.env
dist/docker/Dockerfile
dist/docker/Readme.md
dist/docker/docker-compose.yml

* Add support for search engine
Also mount /tmp as writable, this is required by qbt and not just for the search engine functionality.
* Add script for docker-compose

Add script for docker-compose

---

src/app/application.cpp
src/base/utils/foreignapps.cpp
src/gui/torrentcontentmodel.cpp

Those are some issues found when I was working with boost stacktrace and other exotic platforms.

Improve compatiability with various platforms

---

src/gui/transferlistwidget.cpp

Added keyboard navigation keys for context menu with &, added CTRL+M for force resume

Improve keyboard navigation

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/base/bittorrent/torrentimpl.cpp

Use uniform way to export .torrent files

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/base/bittorrent/torrent.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h
src/base/bittorrent/torrentinfo.cpp
src/base/bittorrent/torrentinfo.h

Add trackers in exported .torrent files

---

src/base/utils/string.cpp

See my comments starting from https://github.com/qbittorrent/qBittorrent/pull/9255#issuecomment-842737521

Consider brackets within wildcard as regular characters

---

src/gui/torrentcontentmodel.cpp

Consistently emit signal when file "ignored" state is changed

---

src/base/bittorrent/nativesessionextension.cpp

Pause torrent in all "fastresume rejected" cases

---

src/base/torrentfilter.cpp
src/gui/transferlistfilterswidget.cpp

Update torrent status filter counters consistently

---

src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.h
src/gui/addnewtorrentdialog.ui

Add "Filter files" field in new torrent dialog

---

src/base/bittorrent/session.cpp

Fixes the issue noticed when testing #16840 (and it seems to be related to the problems of extreme peaks on the Speed plot, which users report from time to time).

Fix rate calculation when interval is too low

---

src/app/cmdoptions.cpp
src/base/torrentfileswatcher.cpp
src/gui/properties/piecesbar.cpp
src/gui/search/searchwidget.cpp
src/gui/utils.cpp
src/gui/utils.h

Other classes already provide rich methods so avoid another layer of QTextStream which slow things down (slightly).

Remove usage of QTextStream

---

src/base/CMakeLists.txt
src/base/base.pri
src/base/rss/feed_serializer.cpp
src/base/rss/feed_serializer.h
src/base/rss/rss_feed.cpp
src/base/rss/rss_feed.h
src/base/rss/rss_session.cpp

Improves startup time and general responsiveness.

Do RSS serializing on worker thread

---

.github/workflows/ci_file_health.yaml
.pre-commit-config.yaml

* update `pre-commit` action to `v3.0.0`
https://github.com/pre-commit/action/releases
* Bump pre-commit-hooks to `v4.3.0` too
https://github.com/pre-commit/pre-commit-hooks.git

GHA CI: "file health" update `pre-commit` action to `v3.0.0`

---

src/base/3rdparty/expected.hpp

* Used  `commit: b78dd92cc92b0cfe4eedad823cfd411c13afeb66` (Release v0.6.0)
* Source https://github.com/martinmoene/expected-lite/releases

Sync `expected.hpp` with upstream

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/gui/addnewtorrentdialog.cpp
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/webui/api/appcontroller.cpp
src/webui/webapplication.h
src/webui/www/private/views/preferences.html

And removed the redundant (IMO) label "Filters:".

Add checkbox for "Excluded file names"

---

src/webui/www/private/scripts/download.js
src/webui/www/private/views/preferences.html
src/webui/www/private/views/rssDownloader.html
src/webui/www/public/scripts/login.js

`innerText` is too powerful for the job here, use a more restricted/secure way to manipulate text.
Related: #17211.

Use proper method for manipulating text

---

src/webui/api/transfercontroller.cpp
src/webui/api/transfercontroller.h
src/webui/webapplication.h

WebAPI: Add endpoint to set speed limit mode

---

src/app/application.cpp
src/app/filelogger.cpp
src/base/bittorrent/statistics.cpp
src/base/bittorrent/statistics.h
src/base/logger.cpp
src/gui/log/logmodel.cpp

* Fix garbage text appeared in log file
Fix up https://github.com/qbittorrent/qBittorrent/commit/fed969ed64f7812a5e0cc65e554c974e914b9074.
* Use coarse timestamp format
Since format in milliseconds doesn't add additional value and is slower than just seconds.
* Defer closing logger instance
So that logger can still be used in shutdown stage.
* Add shutdown logging
* Revise Statistics class

Add shutdown logging

---

src/base/bittorrent/session.cpp

Fix incorrect "max outgoing port" setting

---

src/base/path.cpp
src/gui/torrentcreatordialog.cpp

Fix up dd1bd8ad10fae86837e2c26132de92707622f08a.
Related #17279.

Fix filename not populated correctly

---

src/app/application.cpp
src/app/application.h
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h

PR https://github.com/qbittorrent/qBittorrent/pull/17275

Make working set limit available only on libtorrent 2.0.x builds

---

src/base/bittorrent/session.cpp
src/gui/macutilities.mm

Backported PR:
#17311
#17305
#17290

Backport fixes

---

src/app/application.cpp
src/base/http/connection.cpp
src/base/net/dnsupdater.cpp
src/base/net/geoipmanager.cpp
src/base/net/smtp.cpp
src/base/settingsstorage.cpp
src/gui/mainwindow.cpp
src/webui/webui.cpp

* Revise classes startup sequence
1. Initialize Logger class earlier so that it can record messages from other classes (for
debugging purpose).
2. Deprioritize WebUI port adjustment. It is not a high priority in here.
3. Slightly deprioritize file logger initialization.
* Use helper function for logging messages

Revise classes startup sequence

---

src/base/bittorrent/statistics.cpp
src/base/profile.cpp
src/base/profile.h
src/base/profile_p.cpp
src/base/profile_p.h
src/base/rss/rss_autodownloader.cpp
src/base/settingsstorage.cpp
src/base/settingsstorage.h

Remove redundant fragmentation of logic.

Refactor SettingsStorage implementation

---

src/webui/www/private/views/preferences.html

some have become obsolete due to minimum libtorrent version.

Clean up WebUI preferences

---

src/gui/advancedsettings.cpp
src/webui/api/appcontroller.cpp
src/webui/www/private/views/preferences.html

and rename it to be less ambiguous in GUI with tooltip.

Add refresh interval settings to WebUI

---

CMakeLists.txt
INSTALL
configure
configure.ac

Raise minimum libtorrent version to 2.0.7

Raise minimum libtorrent version to 2.0.7

---

src/gui/fspathedit.cpp
src/gui/optionsdialog.cpp
src/gui/optionsdialog.h
src/gui/torrentcontentmodel.cpp

* Avoid performance impact over network or removable drives
* Split code to smaller functions

Split code to smaller functions

---

src/base/net/downloadhandlerimpl.cpp
src/base/net/downloadmanager.cpp

Backport from:
~~#17204~~
#17438

Backport to v4_4_x

---

src/base/bittorrent/session.cpp
src/base/bittorrent/torrent.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h
src/gui/addnewtorrentdialog.cpp

When duplicate torrent is added set metadata to existing one

---

src/base/rss/rss_parser.cpp

Clear RSS parsing error after use

---

src/app/application.cpp
src/app/application.h
src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/gui/mainwindow.cpp
src/gui/mainwindow.h

Don't populate GUI until BitTorrent session is restored.

Show startup progress dialog

---

src/gui/downloadfromurldialog.cpp
src/gui/downloadfromurldialog.h

Add keyboard shortcut to Download URL dialog

---

src/base/bittorrent/session.cpp

closes https://github.com/qbittorrent/qBittorrent/issues/14733
closes https://github.com/qbittorrent/qBittorrent/issues/14113
closes https://github.com/qbittorrent/qBittorrent/issues/14395

Do not inhibit system sleep/auto shutdown for torrents stuck at downloading metadata

---

configure
m4/ax_boost_base.m4

Upstream: https://github.com/autoconf-archive/autoconf-archive/blob/master/m4/ax_boost_base.m4

Update `ax_boost_base.m4` to latest version

---

src/app/application.cpp

While app instance is loading and main window isn't available show progress dialog instead.
Fixes a bug mentioned in https://github.com/qbittorrent/qBittorrent/pull/17498#issuecomment-1207464709.

Show progress dialog on second instance run

---

src/webui/webapplication.cpp
src/webui/webapplication.h

Set HTTP method restriction on WebAPI actions

---

.github/workflows/ci_file_health.yaml
.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/ci_windows.yaml
.github/workflows/coverity-scan.yml

GHA CI: bump "Install Qt" action version

---

src/base/path.cpp
test/CMakeLists.txt
test/testpath.cpp

* Improve path validness test
* Improve absolute/relative path detection
* Add comments about "UNC path" support
* Fix wrong parent path
* Fix drive letter validness check
* Add unit testing for Path class

Add unit testing for Path class

---

src/gui/deletionconfirmationdialog.cpp
src/gui/deletionconfirmationdialog.ui
src/webui/www/private/confirmdeletion.html

Closes #14309.
Supersedes: #17523.

Rephrase `confirm deletion` dialog

---

src/base/bittorrent/session.cpp

Fix missing trackers from magnet link

---

src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/gui/properties/peerlistwidget.cpp
src/webui/api/synccontroller.cpp
src/webui/api/transfercontroller.cpp

Follow up 525692759de15391eec1760085b95f3042881c35.

Apply forward declaration

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/torrentinfo.cpp

Someone could use this PR for easily testing features of libtorrent master.

Make qBittorrent compatible with libtorrent master

---

src/base/bittorrent/bencoderesumedatastorage.cpp
src/base/bittorrent/dbresumedatastorage.cpp

libtorrent-2.0 until v2.0.5 didn't allow loading v2 .torrent files without piece layer so we cannot load torrent info of incomplete v2 torrents from separate files. As a workaround we had to join torrent info data with other resume data. Now we can switch back to separate loading to avoid unnecessary data allocation/copying.

Parse torrent info separately from resume data

---

src/app/application.cpp
src/app/application.h
src/base/preferences.cpp
src/base/preferences.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/webui/api/appcontroller.cpp
src/webui/www/private/views/preferences.html

Closes #11626.
Since previous attempt (PR #15449) was abandoned unfinished for some reason, I decided to recreate it from scratch.
**Screenshots**
GUI:
Web UI:

Add ability to run external program on torrent added

---

src/gui/properties/propertieswidget.cpp

Don't autofill background color on macOS

---

src/base/preferences.cpp
src/base/utils/net.cpp
src/base/utils/net.h
src/gui/ipsubnetwhitelistoptionsdialog.cpp
src/gui/optionsdialog.ui
src/webui/webapplication.cpp
src/webui/webapplication.h
src/webui/www/private/views/preferences.html

* Simplify functions
* Rename function
* Allow to use subnet notation in reverse proxy list
Closes #17475.
* Add tooltips

Allow to use subnet notation in reverse proxy list

---

src/webui/www/private/views/preferences.html

WebUI: alert when HTTPS settings are incomplete

---

dist/docker/Readme.md

Clarify that some paths should be full paths.
Related: #17729.

Improve docker documentation

---

src/gui/mainwindow.cpp
src/gui/mainwindow.h
src/gui/transferlistfilterswidget.h
src/webui/www/private/views/preferences.html

~~* Reduce dependency on implementation~~
* Fix 'Filter Sidebar' size restored incorrectly
And with a bit of code clean up.
Closes #17756.
* WebUI: allow string to be translated
Closes #17759.

Fix 'Filter Sidebar' size restored incorrectly

---

src/webui/www/private/scripts/prop-files.js

WebUI: don't disable file priority combobox

---

src/gui/torrentcontentfiltermodel.cpp
src/gui/torrentcontentmodel.cpp
src/gui/torrentcontentmodel.h

* Fix coding style
* Remove unused functions
* Fix torrent content checkboxes not updated properly 
Closes #17144, #17764.

Fix torrent content checkboxes not updated properly

---

src/gui/watchedfolderoptionsdialog.cpp

Correctly load state of use download folder

---

src/gui/transferlistfilterswidget.cpp

Fix wrong 'tracker error' count

---

dist/windows/installer-translations/dutch.nsi

Translate new strings and polish existing strings

NSIS: Update Dutch translation

---

dist/windows/installer-translations/portugueseBR.nsi

Added missing translation in: "inst_requires_win10".

NSIS: Update Portuguese BR translation

---

src/webui/api/appcontroller.cpp
src/webui/www/private/download.html
src/webui/www/private/scripts/download.js
src/webui/www/private/upload.html
src/webui/www/private/views/preferences.html

Allow to set torrent stop condition in WebUI

---

src/base/bittorrent/torrentimpl.cpp

Correctly set "stop condition" on force recheck invoked

---

src/base/bittorrent/portforwarderimpl.cpp
src/base/bittorrent/portforwarderimpl.h
src/base/bittorrent/sessionimpl.cpp

* Avoid redundant lookups in port forwarder
* Move code around

Avoid redundant lookups in port forwarder

---

src/webui/www/private/scripts/dynamicTable.js

WebUI: use proper comparison for numbers

---

CMakeLists.txt
INSTALL
configure
configure.ac
src/base/bittorrent/sessionimpl.h

* Require libtorrent versions `1.2.18/2.0.8`

Raise minimum libtorrent versions to `1.2.18/2.0.8`

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/tracker.cpp
src/base/preferences.cpp
src/base/preferences.h
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/webui/api/appcontroller.cpp
src/webui/webapplication.h
src/webui/www/private/views/preferences.html

Add port forwarding option for embedded tracker

---

src/app/application.cpp
src/base/bittorrent/sessionimpl.cpp
src/base/net/downloadmanager.cpp
src/gui/statusbar.cpp
src/gui/torrentcontenttreeview.cpp
src/gui/torrentcontenttreeview.h
src/gui/transferlistmodel.cpp

* Fix typos
* Reserve space before appending elements
* ~~Improve GUI performance when removing torrent~~
* ~~Remove wrong signal emitted~~
~~Those signals are wrong because the code calling them were not actually changing layout.~~
* ~~Reduce UI hang when updating the model~~
~~Addresses: https://github.com/qbittorrent/qBittorrent/pull/17806#discussion_r1008720226~~

Reserve space before appending elements

---

src/base/bittorrent/sessionimpl.cpp

Fixes regression since e19173c1f397857de791f14bd6c1c69a178acc47.

Save correct resume data when added new torrent

---

src/base/bittorrent/sessionimpl.cpp

Fixes regression since bb2caabd613a51a25f1057f0093036132e565e16.

Delete database file only after it is released

---

src/base/torrentfileswatcher.cpp

Destroy object within appropriate thread

---

src/gui/torrentcontentmodel.cpp
src/gui/torrentcontentmodel.h

This reverts commit 0f82c169362cd2e26c053725d3b8fae3889f1655.
Closes #18036.

Revert "Use another workaround to update files tree view"

---

src/base/rss/rss_feed.cpp

Prevent object from being used after destruction

---

src/webui/www/translations/webui_hr.ts

Remove trailing newline from translation file

---

src/webui/www/private/index.html

Fix Speed limit icon size

---

src/base/bittorrent/dbresumedatastorage.cpp
src/base/bittorrent/dbresumedatastorage.h

[Write-Ahead Logging](https://www.sqlite.org/wal.html)

Switch SQLite to use WAL journaling mode

---

src/gui/mainwindow.cpp
src/gui/mainwindow.h

Leftover from the system tray code refactoring.

Remove dead code

---

src/gui/color.h
src/gui/transferlistmodel.cpp

Revise text color for completed status

---

src/gui/uithememanager.cpp

Correctly load folder based UI theme

---

src/base/CMakeLists.txt
src/base/base.pri
src/base/bittorrent/bencoderesumedatastorage.cpp
src/base/bittorrent/dbresumedatastorage.cpp
src/base/bittorrent/dbresumedatastorage.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/rss/rss_autodownloader.cpp
src/base/rss/rss_autodownloader.h
src/base/rss/rss_session.cpp
src/base/rss/rss_session.h
src/base/torrentfileswatcher.cpp
src/base/torrentfileswatcher.h
src/base/utils/thread.cpp
src/base/utils/thread.h
src/webui/api/synccontroller.cpp
src/webui/api/synccontroller.h

Ensure thread is stopped before deleting QThread

---

src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h

Don't drop !qB extension when rename incomplete file

---

src/base/path.cpp

Correctly detect drive letter in path

---

src/gui/categoryfiltermodel.cpp

Correctly count the number of torrents in subcategories

---

src/gui/uithememanager.cpp

The first PR of "UI Theme handling improvements" series. It allows you to (partially) change the default UI theme settings by placing the appropriate configs/icons in `<qbt_config>/themes/default` folder. Subsequent changes I'm going to make:
1. Allow themes to provide alternative colors/icons for dark mode.
2. Allow to edit themes via UI
3. \* Change themes management by handling themes located under `<qbt_config>/themes` folder (so qBittorrent will list such themes in UI and allow you to select one).
4. \* Drop support of legacy `.qbtheme` themes <del>since they have compatibility problems etc</del>.

Allow to modify default UI theme

---

src/app/application.cpp
src/app/application.h

Add all torrents passed via the command line

---

src/gui/aboutdialog.cpp
src/gui/optionsdialog.cpp
src/gui/speedlimitdialog.cpp
src/gui/uithememanager.cpp
src/gui/uithememanager.h
src/gui/utils.cpp
src/gui/utils.h

Avoid leaking the paths of the theme resource files outside of the theme support implementation.

Provide scaled pixmaps by UIThemeManager

---

src/app/application.cpp
src/gui/desktopintegration.cpp
src/gui/desktopintegration.h
src/gui/mainwindow.cpp

Reload system tray icon to replace menu

---

src/app/application.cpp
src/app/main.cpp
src/app/upgrade.cpp
src/app/upgrade.h

Migrate setting about Simplified Chinese locale

---

src/base/bittorrent/addtorrentparams.h
src/base/bittorrent/loadtorrentparams.h
src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/torrentfileswatcher.cpp
src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.ui
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/gui/watchedfolderoptionsdialog.cpp
src/gui/watchedfolderoptionsdialog.ui
src/webui/api/appcontroller.cpp
src/webui/api/torrentscontroller.cpp

Closes #11599.
<hr>
**Preferences**
**Add torrent dialog**
**Watched folders options**

Allow to add new torrents to queue top

---

src/base/bittorrent/bencoderesumedatastorage.cpp
src/base/bittorrent/dbresumedatastorage.cpp
src/base/bittorrent/loadtorrentparams.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/torrent.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h
src/gui/mainwindow.cpp
src/gui/properties/propertieswidget.cpp
src/gui/transferlistwidget.cpp
src/webui/api/torrentscontroller.cpp

Rename isSeed to isFinished to correctly represent its meaning

---

src/base/bittorrent/torrentcontenthandler.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h
src/gui/addnewtorrentdialog.cpp
src/gui/torrentcontentmodel.cpp

This should further increase the responsiveness of the WebUI when "Content" tab is open.

Perform own tracking of files progress

---

src/base/rss/rss_session.cpp
src/gui/rss/feedlistwidget.cpp

Prevent RSS folder from being moved into itself

---

src/webui/webapplication.cpp

Reject requests that contain backslash in path

---

src/base/rss/rss_session.cpp
src/gui/rss/feedlistwidget.cpp
src/webui/api/torrentscontroller.cpp
src/webui/webapplication.cpp

PR #18613.
PR #18619.
PR #18626.

Backport changes to v4.5.x branch

---

src/base/net/downloadmanager.cpp
src/base/net/downloadmanager.h

Should probably fix the regression mentioned in https://github.com/qbittorrent/qBittorrent/pull/18528#issuecomment-1428425143.

Prevent possible problem of using incomplete type

---

src/base/bittorrent/sessionimpl.cpp

Prevent incorrect log message about torrent content deletion

---

src/base/bittorrent/torrentimpl.cpp

Improve finished torrent handling

---

src/gui/uithemedialog.cpp
src/gui/uithemedialog.h

~~I hope it's ok i snuck in the 2nd commit.~~

Save UI Theme Dialog size 

---

src/gui/lineedit.h
src/gui/mainwindow.cpp
src/gui/mainwindow.h

Combine all the column filter related widgets

---

src/gui/optionsdialog.cpp

If they are manually enabled/disabled that will override the groupbox's default behavior.

Initialize a few groupboxes' check state after their children

---

src/gui/properties/peerlistwidget.cpp

Don't forget to clear I2P peer items

---

src/base/net/downloadmanager.cpp

Fixes regression introduced by #18528.
Closes #18764.

Correctly handle redirections

---

src/base/orderedset.h
src/gui/CMakeLists.txt
src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.ui
src/gui/flowlayout.cpp
src/gui/flowlayout.h
src/gui/gui.pri
src/gui/torrenttagsdialog.cpp
src/gui/torrenttagsdialog.h
src/gui/torrenttagsdialog.ui
test/testorderedset.cpp

...and add ability to assign tags in "Add new torrent dialog". It will be added in other places further.

Implement torrent tags editing dialog

---

src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/utils/net.h
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/webui/api/appcontroller.cpp
src/webui/webapplication.h
src/webui/www/private/views/preferences.html

Expose 'socket send/receive buffer size' options

---

src/base/rss/rss_autodownloader.cpp
src/base/rss/rss_autodownloader.h
src/base/rss/rss_feed.cpp
src/base/rss/rss_feed.h
src/base/rss/rss_session.cpp
src/base/rss/rss_session.h
src/gui/rss/rsswidget.cpp
src/gui/rss/rsswidget.h
src/gui/rss/rsswidget.ui
src/webui/api/rsscontroller.cpp
src/webui/api/rsscontroller.h
src/webui/webapplication.h

Allow to edit RSS feed URL

---

src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/webui/www/private/views/preferences.html

* Use KiB unit for socket buffer sizes
https://github.com/qbittorrent/qBittorrent/pull/18806#issuecomment-1499894871
* Describe special values in label
https://github.com/qbittorrent/qBittorrent/pull/18806#discussion_r1158346210

Use KiB unit for socket buffer sizes 

---

src/base/bittorrent/dbresumedatastorage.cpp

Don't miss saving "download path" in SQLite storage

---

src/base/preferences.cpp

Ref.: https://github.com/qbittorrent/qBittorrent/issues/18731#issuecomment-1501197733.

Disable UPnP for web UI by default

---

src/webui/www/private/upload.html

Reverts file picker due to incompatibility with IOS:
Fixes https://github.com/qbittorrent/qBittorrent/issues/18683

WebUI: Use workaround for IOS file picker

---

src/base/logger.h
src/webui/www/private/scripts/misc.js
src/webui/www/private/scripts/mocha-init.js

ps. `Work around Chrome download limit` commit is eligible for backport.

Work around Chrome download limit

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h

Improve move storage handling

---

src/base/bittorrent/sessionimpl.cpp

Make sure ResumeSessionContext is destroyed before start processing

---

src/gui/lineedit.cpp
src/gui/lineedit.h

Avoid using style sheets to better support color mode switching.

Revamp LineEdit implementation

---

src/gui/transferlistfilterswidget.cpp

Avoid using style sheets to better support color mode switching.

Revamp TransferListFiltersWidget implementation

---

src/base/bittorrent/torrentimpl.cpp

Don't make assertion about 3rd party logic

---

src/base/CMakeLists.txt
src/base/base.pri
src/base/bittorrent/addtorrentparams.cpp
src/base/bittorrent/addtorrentparams.h
src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/rss/rss_autodownloader.cpp
src/base/rss/rss_autodownloadrule.cpp
src/base/rss/rss_autodownloadrule.h
src/base/torrentfileswatcher.cpp
src/gui/CMakeLists.txt
src/gui/addtorrentparamswidget.cpp
src/gui/addtorrentparamswidget.h
src/gui/addtorrentparamswidget.ui
src/gui/flowlayout.cpp
src/gui/flowlayout.h
src/gui/fspathedit.cpp
src/gui/fspathedit_p.cpp
src/gui/gui.pri
src/gui/rss/automatedrssdownloader.cpp
src/gui/rss/automatedrssdownloader.h
src/gui/rss/automatedrssdownloader.ui
src/gui/watchedfolderoptionsdialog.cpp
src/gui/watchedfolderoptionsdialog.h
src/gui/watchedfolderoptionsdialog.ui

**Watched folder options editor**
**RSS auto-download rule editor**

Unify/improve "add torrent parameters" template editing UI

---

src/gui/transferlistfilterswidget.cpp
src/gui/transferlistfilterswidget.h

Fix inconsistent background of filters widget

---

src/base/bittorrent/dbresumedatastorage.cpp

Avoid race condition when waking worker thread

---

src/app/application.cpp

Now it will try to raise the hard limit. The operation will fail if the process does not have sufficient privilege yet the error message should be of help to clear things up.
ps. This is not a direct response to #18282. However it is wished to confirm my theory that macos has a set a lower hard limit (`rlim_max`) that forbids the users in #18282 to raise the current limit (`rlim_cur`).

Improve "apply memory working set" routine

---

.github/workflows/ci_macos.yaml

Hopefully those bundles will be runnable on users machine.

GHA CI: upload macOS bundles

---

src/base/3rdparty/expected.hpp

Sync `nonstd/expected` with upstream

---

src/base/preferences.cpp
src/base/preferences.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/gui/transferlistwidget.cpp

Allow to disable confirmation of Pause/Resume All

---

src/gui/optionsdialog.cpp

Don't miss to enable Apply button

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/bittorrent/torrentimpl.cpp

Ref: https://github.com/qbittorrent/qBittorrent/pull/18801#issuecomment-1549923118.

Immediately update torrent status on moving files

---

src/app/upgrade.cpp
src/base/bittorrent/sessionimpl.cpp
src/base/net/downloadmanager.cpp
src/base/net/proxyconfigurationmanager.cpp
src/base/net/proxyconfigurationmanager.h
src/base/search/searchpluginmanager.cpp
src/gui/optionsdialog.cpp
src/webui/api/appcontroller.cpp
src/webui/www/private/views/preferences.html

Allow to globally disable the use of proxy

---

src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/preferences.cpp
src/base/preferences.h
src/gui/addnewtorrentdialog.cpp
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/webui/api/appcontroller.cpp

Add options to adjust behavior of merging trackers to existing torrent

---

src/gui/mainwindow.cpp

* Fixup from #18996
Ref.: https://github.com/qbittorrent/qBittorrent/pull/18996#issuecomment-1622336190

Display correct Minimum Python requirement

---

src/base/bittorrent/sessionimpl.cpp

Log when duplicate torrents are being added

---

src/base/bittorrent/dbresumedatastorage.cpp

Correctly add new column to existing database

---

src/base/bittorrent/sessionimpl.cpp
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui

For some reason it was missed in #19278.

Always honor the configured behavior for merging trackers

---

src/gui/transferlistfilters/trackersfilterwidget.cpp
src/gui/transferlistfilters/trackersfilterwidget.h

Fixes regression of #19062.
Closes #19307.

Use previous approach of deducing favicon URL

---

src/webui/www/private/views/rssDownloader.html

Fixes regression of #18824.
Closes #19323.

WebUI: use new format of RSS rules

---

src/gui/mainwindow.cpp
src/gui/mainwindow.h

Don't initialize Properties widget size until window is shown

---

src/gui/powermanagement/powermanagement_x11.cpp

Inhibit suspend instead of screen idle

---

src/gui/mainwindow.cpp
src/gui/mainwindow.h
src/webui/www/private/views/rssDownloader.html

Backport changes in v4.6.x branch

---

src/gui/powermanagement/powermanagement_x11.cpp
src/gui/powermanagement/powermanagement_x11.h

* Add support for systemd power management
* Use correct type
https://doc.qt.io/qt-6/qdbustypesystem.html
https://dbus.freedesktop.org/doc/dbus-specification.html#id-1.3.8
* Use default timeout
* Remove debugging messages
As requested in https://github.com/qbittorrent/qBittorrent/pull/19344#discussion_r1269156895

Add support for systemd power management

---

src/base/net/downloadmanager.cpp

I decided to redo it instead of backporting from existing commit.

Use efficient algorithm for removing entries (v4_6_x)

---

src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h

Map selected indexes to source before modify the data (v4.5)

---

src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h

Map selected indexes to source before modify the data (v4.6)

---

.github/workflows/ci_ubuntu.yaml
cmake/Modules/CommonConfig.cmake
src/gui/addnewtorrentdialog.cpp

* Guard against potential negative number
* Revise wording
* GHA CI: specify a category for CodeQL analysis

GHA CI: specify a category for CodeQL analysis

---

.github/workflows/ci_ubuntu.yaml
src/gui/powermanagement/powermanagement_x11.cpp
src/gui/transferlistwidget.cpp

Related PR:
#19316
#19396
#19403

Backport fixes to v4_6_x

---

src/gui/transferlistwidget.cpp

ps. I suppose it is eligible for v4_6_x.

Ensure file name is valid when exporting torrents

---

src/base/algorithm.h
src/base/orderedset.h
src/base/settingsstorage.h
src/base/utils/string.h
src/base/utils/version.h
test/testalgorithm.cpp

Related: https://clang.llvm.org/extra/clang-tidy/checks/modernize/use-constraints.html

Replace template conditionals with C++20 `requires` clause

---

.editorconfig

Additionally, changes the link to the EditorConfig website from http to https.

Specify charset and end_of_line in .editorconfig

---

CMakeLists.txt
src/base/bittorrent/trackerentry.h

* Remove unused include
* Switch to QHash

Remove unused include

---

src/base/bittorrent/sessionimpl.cpp
src/gui/addnewtorrentdialog.cpp

Replace Q_UNLIKELY with [[unlikely]] attribute

---

src/base/CMakeLists.txt
src/base/concepts/stringable.h
src/base/path.cpp
src/base/path.h
src/base/settingsstorage.h
src/base/utils/version.cpp
src/base/utils/version.h
test/CMakeLists.txt
test/testconceptsstringable.cpp
test/testutilsversion.cpp

Specify interface requirements as an C++ concept

---

src/gui/uithemesource.cpp
src/gui/uithemesource.h

Correctly load colors from custom themes

---

src/app/application.cpp
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/torrentimpl.cpp
src/base/net/geoipdatabase.cpp
src/base/rss/rss_autodownloader.cpp
src/base/rss/rss_feed.cpp
src/base/utils/misc.cpp
src/gui/addnewtorrentdialog.cpp
src/gui/cookiesmodel.cpp
src/gui/desktopintegration.cpp
src/gui/fspathedit_p.cpp
src/gui/mainwindow.cpp
src/gui/notifications/dbusnotifier.cpp
src/gui/search/searchwidget.cpp
src/gui/torrentcontentmodel.cpp
src/gui/torrentoptionsdialog.cpp
src/gui/transferlistfilters/categoryfilterwidget.cpp
src/gui/transferlistfilters/tagfilterwidget.cpp
src/gui/watchedfoldersmodel.cpp
test/testalgorithm.cpp

Also adds `const` to a few parameters.

Replace `Q_UNUSED` with `[[maybe_unused]]` attribute

---

src/app/application.cpp
src/app/main.cpp
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/torrentimpl.cpp
src/base/preferences.cpp

* PR #19460
* PR #19462
* PR #19463

Backport changes to v4.6.x branch

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h
src/base/bittorrent/trackerentry.h
src/gui/properties/trackerlistwidget.cpp
src/gui/properties/trackerlistwidget.h
src/gui/transferlistfilters/trackersfilterwidget.cpp
src/webui/api/torrentscontroller.cpp

Improve tracker entries handling

---

src/base/utils/io.cpp

Closes #19521.
ps. this should be backport to v4_6_x.

Perform type conversion properly

---

src/base/utils/io.cpp
src/gui/transferlistwidget.cpp

Backport changes to v4_6_x

---

src/base/rss/feed_serializer.cpp
src/gui/aboutdialog.cpp

Don't limit max RSS feed file size

---

src/base/bittorrent/torrentimpl.cpp

Don't show outdated tracker message

---

src/base/http/requestparser.cpp
src/base/torrentfileswatcher.cpp
src/gui/lineedit.cpp

* Fixes a couple of memory leaks (although not dangerous in practice, since we are talking about objects with a lifetime up to the end of the application)
* Fixes heap use after free
Closes #19632.

Fix memory leaks

---

src/base/http/requestparser.cpp
src/base/utils/bytearray.cpp
src/base/utils/bytearray.h
src/base/utils/password.cpp

Follow up #19417.
Addresses https://github.com/qbittorrent/qBittorrent/pull/19417#discussion_r1336732332.

Fix performance regression

---

src/base/bittorrent/dbresumedatastorage.cpp

Fixes one more minor memory leak.

Don't forget to delete worker thread object

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h

Specifically these alerts:
* i2p_alert
* session_error_alert

Add logging for some alerts

---

AUTHORS

I am sorry for this, but for privacy reason I need to change the name in contribution. Sorry for the trouble.

Change author name

---

dist/windows/installer.nsi
dist/windows/uninstaller.nsi
src/app/application.cpp
src/base/CMakeLists.txt
src/base/base.pri
src/base/preferences.cpp
src/base/preferences.h
src/base/utils/misc.cpp
src/base/utils/os.cpp
src/base/utils/os.h
src/gui/optionsdialog.cpp

Backport "Improve .torrent associate handling"

---

src/base/bittorrent/sessionimpl.cpp

Prevent crash due to race condition when adding magnet link

---

src/gui/properties/propertieswidget.cpp
src/gui/torrentcontentwidget.cpp
src/gui/torrentcontentwidget.h

Fix Enter key behavior when add new torrent

---

src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.h

Don't forget to delete TorrentContentAdaptor instance

---

src/gui/addnewtorrentdialog.cpp

Update size of selected files when selection is changed

---

src/base/bittorrent/torrentimpl.cpp

Correctly handle changing save path of torrent w/o metadata

---

src/webui/www/private/scripts/client.js

Fix incorrect subcategory sorting in WebUI

---

src/app/application.cpp
src/base/bittorrent/torrentimpl.cpp
src/base/net/downloadhandlerimpl.cpp
src/base/preferences.cpp
src/base/preferences.h
src/base/utils/misc.cpp
src/base/utils/misc.h
src/base/utils/os.cpp
src/base/utils/os.h
src/base/utils/random.cpp
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/gui/macosdockbadge/badgeview.mm
src/webui/api/appcontroller.cpp
src/webui/webapplication.h
src/webui/www/private/views/preferences.html

* Move some functions into Utils::OS namespace
Also remove `Utils::Misc::getUserIDString()` since there are no use of it.
* Expose Mark-of-the-Web setting in Options

Expose Mark-of-the-Web setting in Options

---

src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/views/filters.html

WebUI: Add "Moving" filter to side panel

---

src/webui/CMakeLists.txt
src/webui/api/synccontroller.cpp
src/webui/api/synccontroller.h
src/webui/freediskspacechecker.cpp
src/webui/freediskspacechecker.h
src/webui/webapplication.cpp
src/webui/webapplication.h

Use single free disk space checker instance for all the web sessions.
Closes #19732.

Improve free disk space checking for WebAPI

---

src/webui/www/private/views/rssDownloader.html

WebUI: Correctly set save path in RSS rules

---

src/app/application.cpp
src/app/application.h
src/app/main.cpp
src/base/utils/os.cpp

* Improve error message when daemonizing failed
* Simplify code

Improve error message when daemonizing failed

---

src/base/bittorrent/sessionimpl.cpp

Do not apply share limit if the previous one was applied

---

src/gui/guiaddtorrentmanager.cpp

Show Add new torrent dialog on main window screen

---

src/base/bittorrent/sessionimpl.cpp

Also contains fixup from #19970.

Simplify share ratio limits processing code

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/ci_windows.yaml

A subset from PR #19958.
Those commits affects how the CI cache is managed so I would like to backport them.

Backport CI improvements

---

src/base/bittorrent/addtorrentparams.cpp

Don't forget to store Stop condition

---

.pre-commit-config.yaml
src/webui/www/README.md

Rendered: https://github.com/qbittorrent/qBittorrent/blob/03dc4545b4cac6d9c1a3afe9407efcd9079d9d5a/src/webui/www/README.md

Update Readme for WebUI

---

src/gui/addnewtorrentdialog.cpp
src/gui/mainwindow.cpp
src/gui/mainwindow.h
src/gui/properties/propertieswidget.cpp
src/gui/properties/propertieswidget.h

In new torrent dialog and toggle between transfer list and content tab's search fields.

Enable Ctrl+F hotkey for more inputs

---

README.md

Remove old build instructions from README.md

---

src/base/bittorrent/sessionimpl.cpp
src/gui/torrentoptionsdialog.cpp

Apply inactive seeding time limit set on new torrents

---

src/gui/properties/propertieswidget.cpp

Show URL seeds for torrents that have no metadata

---

src/base/bittorrent/bencoderesumedatastorage.cpp
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h

Don't stuck loading on mismatching info-hashes in resume data

---

src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/dynamicTable.js

Improve responsiveness for operations related to Category/Tag.
Related: #20249.

Improve WebUI responsiveness

---

src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/misc.js
src/webui/www/private/views/search.html

Also change case sensitivity to the default of 'sort' mode.

Use natural sorting in WebUI

---

src/gui/CMakeLists.txt
src/gui/addtorrentparamswidget.cpp
src/gui/addtorrentparamswidget.ui
src/gui/torrentsharelimitswidget.cpp
src/gui/torrentsharelimitswidget.h
src/gui/torrentsharelimitswidget.ui

Add seeding limits to RSS and Watched folders options UI

---

src/base/bittorrent/sessionimpl.cpp

Don't use iterator after erase

---

src/base/bittorrent/bencoderesumedatastorage.cpp
src/base/bittorrent/torrentcreator.cpp
src/base/search/searchpluginmanager.cpp
src/base/torrentfileswatcher.cpp
src/base/utils/fs.cpp
src/base/utils/misc.cpp
src/base/utils/misc.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/webui/webapplication.cpp

* Avoid creating redundant file lists
* Sort languages combobox by language code

Sort languages combobox by language code

---

src/base/asyncfilestorage.cpp
src/base/asyncfilestorage.h

Open "lock" files for the same folder only once

---

src/webui/www/private/scripts/cache.js

Now cache initialization and `get()` is less costly and it shifts the weight to `set()`.

Revise cache internals

---

src/base/bittorrent/torrentimpl.cpp

Avoid blocking call to `libtorrent` when accessing underlying `torrent_info` object.

Improve received metadata handling

---

src/webui/www/package.json
src/webui/www/private/index.html
src/webui/www/private/scripts/misc.js
src/webui/www/private/views/about.html
src/webui/www/public/index.html
src/webui/www/public/scripts/login.js

* Warp script in anonymous scope (IIFE)
It was erroneously removed in 9b64d50.
* Remove unneeded polyfill
All browsers already have native support for it.
* Add description meta tag
* Avoid leaking user locale preference to the web
* Add viewport meta tag
This helps displaying WebUI on mobile devices. Note that WebUI aren't optimized for mobile yet.
* Write format result directly to file
And not print to stdout.

WebUI improvements

---

src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.h
src/gui/lineedit.cpp
src/gui/lineedit.h
src/gui/mainwindow.cpp
src/gui/mainwindow.h
src/gui/search/searchjobwidget.cpp
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/misc.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/views/log.html
src/webui/www/private/views/search.html

Add a small delay before processing the key input of search boxes

---

src/app/application.cpp

Ensure the 'profile' path of portable mode is pointing to a directory

---

src/app/upgrade.cpp
src/base/CMakeLists.txt
src/base/bittorrent/addtorrentparams.cpp
src/base/bittorrent/addtorrentparams.h
src/base/bittorrent/bencoderesumedatastorage.cpp
src/base/bittorrent/dbresumedatastorage.cpp
src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/bittorrent/sharelimitaction.h
src/base/bittorrent/torrent.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h
src/gui/addtorrentparamswidget.cpp
src/gui/optionsdialog.cpp
src/gui/torrentoptionsdialog.cpp
src/gui/torrentoptionsdialog.h
src/gui/torrentsharelimitswidget.cpp
src/gui/torrentsharelimitswidget.h
src/gui/torrentsharelimitswidget.ui
src/webui/api/appcontroller.cpp
src/webui/api/torrentscontroller.cpp

Allow torrents to override default share limit action

---

dist/windows/installer-translations/hungarian.nsh

NSIS: Update Hungarian translation

---

src/app/application.cpp

Prevent app from being closed when disabling system tray icon

---

.github/workflows/ci_macos.yaml

GHA CI: retry action on failure

---

src/webui/api/serialize/serialize_torrent.cpp

WebAPI: return correct value for queued uploading state

---

.github/workflows/ci_macos.yaml

Fix up 1d221c22e4da53d3f09969ec05fe8ba1c613a07e.
Will be backported to v4.6.x.

GHA CI: revise packaging failure detection

---

src/base/torrentfilter.h
src/gui/transferlistfilters/statusfilterwidget.cpp
src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h

Prevent invalid status filter index from being used

---

src/gui/guiaddtorrentmanager.cpp

Add extra offset for dialog frame

---

src/gui/downloadfromurldialog.cpp

Focus on Download button if torrent link retrieved from the clipboard

---

src/gui/mainwindow.cpp

Don't overwrite stored layout of main window with incorrect one

---

src/base/bittorrent/torrentimpl.cpp

Related issue description: https://github.com/qbittorrent/qBittorrent/issues/17962#issuecomment-2068585219

Don't forget to resume "missing files" torrent when rechecking

---

src/searchengine/nova3/nova2.py

make `nova2.py` faster when only some search plugins are used
example: [LightDestory/qBittorrent-Search-Plugins](https://github.com/LightDestory/qBittorrent-Search-Plugins)
```
$ time python src/nova2.py
./nova2.py [all|engine1[,engine2]*] <category> <keywords>
available engines: ilcorsaronero,kickasstorrents,rarbg,torrentdownload,yourbittorrent,rockbox,thepiratebay,btetree,glotorrents,ettv,pirateiro,academictorrents,nitro,snowfl,tntvillagedump
real    0m2.027s
$ time python src/nova2.py
./nova2.py [all|engine1[,engine2]*] <category> <keywords>
available engines: ilcorsaronero,kickasstorrents,rarbg,torrentdownload,yourbittorrent,rockbox,thepiratebay,btetree,glotorrents,ettv,pirateiro,academictorrents,nitro,snowfl,tntvillagedump
real    0m0.220s
```
downside: this will also add broken …

Lazy load search plugins

---

src/base/utils/number.cpp

Closes #20774.
This fixes compilation issues likely caused by musl.

Include missing header

---

src/gui/search/searchwidget.ui

Allow to rearrange search tabs

---

src/webui/www/private/scripts/mocha-init.js

Arbitrarily chosen number, works on my machine.
Closes #20536

Increase default height of 'Share ratio limit' dialog in WebUI

---

src/qbittorrent.exe.manifest

https://learn.microsoft.com/en-us/windows/win32/sbscs/application-manifests#assemblyidentity

Add required manifest field

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h

Apply share limits when torrent downloading is finished

---

src/gui/torrentcontentmodel.cpp

Don't use custom "file icon provider" on Windows

---

.github/workflows/ci_python.yaml
src/searchengine/nova3/helpers.py
src/searchengine/nova3/nova2.py
src/searchengine/nova3/novaprinter.py

A few code are revised because the type checker (mypy) doesn't allow changing types on a variable.

Add type annotations

---

src/gui/CMakeLists.txt
src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.h
src/gui/filterpatternformat.h
src/gui/filterpatternformatmenu.cpp
src/gui/filterpatternformatmenu.h
src/gui/properties/propertieswidget.cpp
src/gui/properties/propertieswidget.h
src/gui/torrentcontentwidget.cpp
src/gui/torrentcontentwidget.h

Allow to use regular expression to filter torrent content

---

src/gui/torrentcontentwidget.cpp

Apply bulk changes to correct content widget items

---

src/webui/webapplication.cpp

Ports #20711 into v5.0 branch as per https://github.com/qbittorrent/qBittorrent/pull/20711#issuecomment-2058311348.

Restore ability to use server-side translation by custom WebUI

---

src/webui/www/private/download.html
src/webui/www/private/index.html
src/webui/www/private/newcategory.html
src/webui/www/private/newfolder.html
src/webui/www/private/scripts/pathAutofill.js
src/webui/www/private/upload.html
src/webui/www/private/views/preferences.html
src/webui/www/webui.qrc

Followup for https://github.com/qbittorrent/qBittorrent/pull/20314
Implementation of path autocompletion in WEB UI
[Nagranie ekranu z 31.05.2024 15:28:15.webm](https://github.com/qbittorrent/qBittorrent/assets/45544416/24869ea0-c333-4596-9b8d-a14bbc773a71)

WebUI: Implement path autocompletion

---

src/gui/torrenttagsdialog.cpp
src/gui/transferlistwidget.cpp
src/gui/utils.cpp
src/gui/utils.h

Fix handling of tags containing '&' character

---

src/gui/torrenttagsdialog.cpp

Show scroll bar in Torrent Tags dialog

---

src/webui/www/private/addpeers.html
src/webui/www/private/confirmdeletion.html
src/webui/www/private/download.html
src/webui/www/private/newcategory.html
src/webui/www/private/rename_files.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/download.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/prop-general.js
src/webui/www/private/scripts/prop-peers.js
src/webui/www/private/scripts/prop-webseeds.js
src/webui/www/private/scripts/search.js
src/webui/www/private/setlocation.html
src/webui/www/private/shareratio.html
src/webui/www/private/views/installsearchplugin.html
src/webui/www/private/views/log.html
src/webui/www/private/views/preferences.html
src/webui/www/private/views/rss.html
src/webui/www/public/scripts/login.js

It is now clearer to see what property is being accessed. Previously mootools library would re-map attribute/property to another.
ps. Might have merge conflicts with #20951, #21000. Should this PR wait for them?

WebUI: access attribute/property natively

---

src/webui/www/private/scripts/cache.js
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/download.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/file-tree.js
src/webui/www/private/scripts/filesystem.js
src/webui/www/private/scripts/localpreferences.js
src/webui/www/private/scripts/misc.js
src/webui/www/private/scripts/pathAutofill.js
src/webui/www/private/scripts/piecesbar.js
src/webui/www/private/scripts/progressbar.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/prop-general.js
src/webui/www/private/scripts/prop-peers.js
src/webui/www/private/scripts/prop-trackers.js
src/webui/www/private/scripts/prop-webseeds.js
src/webui/www/private/scripts/rename-files.js
src/webui/www/private/scripts/search.js
src/webui/www/private/views/filters.html
src/webui/www/private/views/installsearchplugin.html
src/webui/www/private/views/log.html
src/webui/www/private/views/preferences.html
src/webui/www/private/views/rss.html
src/webui/www/private/views/rssDownloader.html
src/webui/www/private/views/searchplugins.html
src/webui/www/private/views/transferlist.html

ps. Will apply formatting after conflicting PRs are merged: #20951, #21000, #21007.

WebUI: avoid redundant re-initialization

---

src/webui/www/.htmlvalidate.json
src/webui/www/private/addpeers.html
src/webui/www/private/addtrackers.html
src/webui/www/private/confirmdeletion.html
src/webui/www/private/download.html
src/webui/www/private/downloadlimit.html
src/webui/www/private/edittracker.html
src/webui/www/private/index.html
src/webui/www/private/newcategory.html
src/webui/www/private/newfeed.html
src/webui/www/private/newfolder.html
src/webui/www/private/newrule.html
src/webui/www/private/newtag.html
src/webui/www/private/rename.html
src/webui/www/private/rename_feed.html
src/webui/www/private/rename_file.html
src/webui/www/private/rename_files.html
src/webui/www/private/rename_rule.html
src/webui/www/private/scripts/misc.js
src/webui/www/private/setlocation.html
src/webui/www/private/shareratio.html
src/webui/www/private/upload.html
src/webui/www/private/uploadlimit.html
src/webui/www/private/views/installsearchplugin.html
src/webui/www/private/views/log.html
src/webui/www/private/views/preferences.html
src/webui/www/private/views/propertiesToolbar.html
src/webui/www/private/views/rssDownloader.html
src/webui/www/private/views/search.html

* WebUI: associate label to input fields
* WebUI: simplify code

WebUI: Improve accessibility

---

src/webui/www/private/scripts/dynamicTable.js

Fix up 7131d1bd6b2d8d2b5908873e2b72b0c2ec58a5bc.
See: https://github.com/qbittorrent/qBittorrent/pull/21117#discussion_r1694753191

WebUI: fix accessing wrong variable

---

src/webui/api/torrentscontroller.cpp

Discussion: https://github.com/qbittorrent/qBittorrent/pull/21056#discussion_r1674632942

Don't reannounce when removing tracker via WebAPI

---

src/webui/www/private/css/style.css
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/mocha-init.js

This PR makes it possible to see common category of selected torrents in context menu. Everything should behave exactly like in GUI.
Closes #12701.

WebUI: Highlight torrent category in context menu

---

src/gui/transferlistfilters/statusfilterwidget.cpp

Hide zero status filters when torrents removed

---

src/webui/www/private/scripts/dynamicTable.js

Incomplete Save Path
Info Hash v1
Info Hash v2
Screenshot:

WebUI: Add missing columns in transfer list

---

src/webui/www/private/scripts/dynamicTable.js

… https://github.com/qbittorrent/qBittorrent/pull/20566#discussion_r1704548226

WebUI: Handle regex syntax error for torrent filtering

---

src/webui/www/private/css/style.css
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/progressbar.js
src/webui/www/private/views/log.html
src/webui/www/private/views/rss.html
src/webui/www/private/views/searchplugins.html

* WebUI: replace deprecated property
* WebUI: use native property to set styles
* WebUI: remove outdated CSS property
WebUI already has the standard counterparts.

WebUI: use native property to set styles

---

src/webui/www/private/scripts/dynamicTable.js

Fix up 2d9e3b333047d7d80368458cb0ce480205dc1410.
Related: https://github.com/qbittorrent/qBittorrent/pull/21147#issuecomment-2281528300

WebUI: fix wrong property for keyboard keys

---

src/base/bittorrent/peerinfo.cpp

Add a flag about the peers are using NAT hole punching

---

src/base/bittorrent/peerinfo.cpp
src/base/bittorrent/torrentimpl.cpp
src/gui/properties/downloadedpiecesbar.cpp
src/gui/properties/downloadedpiecesbar.h
src/gui/properties/pieceavailabilitybar.cpp
src/gui/properties/pieceavailabilitybar.h
src/gui/properties/piecesbar.cpp
src/gui/properties/piecesbar.h
src/gui/transferlistfilters/statusfilterwidget.cpp
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/dynamicTable.js

* #21052
* #21148
* #21150
* #21152
* #21158
* #21183 
* #21188

Backport changes to v5.0.x branch

---

src/base/3rdparty/expected.hpp

Sync "expected lite" with upstream

---

src/gui/optionsdialog.ui
src/webui/www/private/views/preferences.html

Add link to 'List of alternative WebUI' wiki page in Options

---

src/webui/www/private/views/rssDownloader.html

WebUI: Fix incorrectly backported code

---

src/webui/www/private/css/style.css
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/views/filters.html

A couple of tweaks to make them a little bit better:
1) Make highlightling functions more consistent (this also fixes miniscule bug when no filter item in tracker list is highlighted due to a type mismatch)
2) Use [event delegation](https://javascript.info/event-delegation) to handle filter toggling & item selection
3) Other minor improvements (everything should work like it was previously)

WebUI: Filter list improvements

---

src/webui/www/private/views/preferences.html

This PR adds 'Use Category paths in Manual Mode' option to WebUI.

WebUI: Provide 'Use Category paths in Manual Mode' option

---

src/webui/www/private/css/dynamicTable.css
src/webui/www/private/css/style.css

Fix up: https://github.com/qbittorrent/qBittorrent/pull/21162
Related: https://github.com/qbittorrent/qBittorrent/pull/21162#discussion_r1721799836

WebUI: Don't apply hover / selection styles to flag icons

---

src/webui/www/private/scripts/contextmenu.js

Related: https://github.com/qbittorrent/qBittorrent/pull/21163#discussion_r1739715585
Fix up 5afeecbf18397ca3805564bd499207ead2e3b4bb.

WebUI: do not follow anchor URL

---

src/webui/www/private/views/preferences.html

This PR adds 'Merge trackers to existing torrent' option to the WebUI.

WebUI: Provide 'Merge trackers to existing torrent' option

---

src/base/utils/random.cpp

* Use modern function for getting random numbers on Linux
Now we don't need a file handle anymore and there is no initialization involved in this new implementation.
* Use modern function for getting random numbers on Windows
The previous `RtlGenRandom()` just redirects to `ProcessPrng()` according to "The Windows 10 random number generation infrastructure" whitepaper from MS.
`ProcessPrng()` is also the de facto PRNG for Rust lang:
https://github.com/rust-random/getrandom/blob/aa13fa58821180248507b81c967d3c731a2ca1d5/src/windows.rs#L3C1-L22C81
And for golang:
https://go-review.googlesource.com/c/go/+/536235

Improve PRNG functions

---

src/webui/www/private/scripts/prop-trackers.js

WebUI: Fix removing tracker URL with '|' character

---

src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/search.js
src/webui/www/private/views/log.html
src/webui/www/private/views/rss.html
src/webui/www/private/views/rssDownloader.html
src/webui/www/private/views/searchplugins.html

I decided to switch all remaining tables in one go. RSS table required the biggest amount of changes so I would appreciate some testing there.

WebUI: Use Map instead of Mootools Hash in all dynamic tables

---

.github/ISSUE_TEMPLATE/bug_report.yml

* Fixed small formatting issue
* Reinstated all CI Builds for testing
* Removed obsolete/redundant (frequent/common issues list) & when asked section about logs/preferences
* Refactored tracker search to exclude feature requests so only issues are shown
* Made logs/preferences a requirement
* Updated preferred formatting example info.

Revise `bug_report` template

---

src/webui/www/private/editfeedurl.html
src/webui/www/private/views/rss.html
src/webui/www/webui.qrc

WebUI: Support updating RSS feed URL

---

dist/windows/installer-translations/luxembourgish.nsh

NSIS: update luxembourgish

---

.github/workflows/helper/pre-commit/.typos.toml
.pre-commit-config.yaml

* Bumped numerous revisions
* Removed obsolete exclusions (files/folders were removed previously)
* Implement fix/workaround for "false positives" (typos/codespell)

GHA CI: Update pre-commit-config workflow

---

src/webui/www/private/views/rss.html

I just found more unused variable...

WebUI: remove unused variable

---

src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/views/rss.html

Follow up to #21371 ([context](https://github.com/qbittorrent/qBittorrent/pull/21371#discussion_r1780908605)). I completely missed the concept of folders when implementing this previous PR.

WebUI: Handle folders when updating RSS feed url

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h

Correctly handle "torrent finished after move" event

---

src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/dynamicTable.js

Context menu classes are now created using vanilla JS syntax (minimal changes to reduce Mootools bits).

WebUI: Use modern class syntax in context menu classes

---

.github/workflows/ci_windows.yaml
src/gui/CMakeLists.txt
src/gui/colorscheme.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.h
src/gui/optionsdialog.ui
src/gui/uithememanager.cpp
src/gui/uithememanager.h

Allow to choose color scheme on Windows

---

src/webui/www/private/rename_files.html

WebUI: fix 'rename files' dialog cannot be opened more than once (v5_0_x)

---

src/gui/properties/piecesbar.cpp
src/gui/rss/rsswidget.cpp
src/gui/rss/rsswidget.h

* Fix pieces bars won't correctly detect color scheme change with Qt 6.8.
* Update RSS article content view on color scheme changed.
Closes #21327.

Improve color scheme change detection

---

src/gui/optionsdialog.cpp

A copy paste error was introduced in PR #20338.
@glassez 
Please backport this PR, thanks!

Fix button state for SSL certificate check

---

src/gui/previewselectdialog.cpp

This PR fixes sorting of file size in preview dialog, also adds back a missing header name (File Index) in right most column of the table.
The rootcause for the issue is that in previous implementation the file size is stored in a human readble format (for exmaple, 357249843 -> 340.7 MiB). Sorting of string happens instead of numerical values. Adding back the numerical representation and configure the table to sort w.r.t. it would resolve the issue.
https://github.com/qbittorrent/qBittorrent/blob/87644441ad88b251913402ece9fd4b6b78f59ff0/src/gui/previewselectdialog.cpp#L93
Before:
After the fix:
Closes #21510

Fix filesize sorting in preview dialog

---

src/base/net/downloadmanager.cpp
src/base/preferences.cpp
src/base/preferences.h
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/webui/api/appcontroller.cpp
src/webui/www/private/views/preferences.html

Original PR: #21364
The webui part uses the old way of setting/getting values.

Don't ignore SSL errors (v5_0_x)

---

src/gui/search/searchwidget.cpp
src/gui/search/searchwidget.h

Correctly delete the moved search tabs

---

src/webui/www/private/scripts/client.js

Only update the torrents table when torrents are added, edited, or removed.

WebUI: Eliminate unnecessary torrents table updates

---

src/gui/transferlistfilters/trackersfilterwidget.cpp

Remove trackers from previous category when moved to new one

---

src/base/addtorrentmanager.cpp
src/base/addtorrentmanager.h
src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.h
src/gui/guiaddtorrentmanager.cpp

Fix .torrent file could not be deleted when torrent is canceled

---

src/webui/www/private/css/Layout.css
src/webui/www/private/css/dynamicTable.css
src/webui/www/private/css/style.css
src/webui/www/private/rename_files.html
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/search.js
src/webui/www/private/views/log.html
src/webui/www/private/views/rss.html
src/webui/www/private/views/search.html

This PR relies on flexbox to ensure all WebUI tables are the correct height without overflowing. Table headers are now always visible and JS-based dynamic resizing is no longer needed.

WebUI: Improve table overflow handling

---

src/webui/www/private/addpeers.html
src/webui/www/private/addtrackers.html
src/webui/www/private/confirmdeletion.html
src/webui/www/private/confirmfeeddeletion.html
src/webui/www/private/confirmruleclear.html
src/webui/www/private/confirmruledeletion.html
src/webui/www/private/download.html
src/webui/www/private/downloadlimit.html
src/webui/www/private/edittracker.html
src/webui/www/private/index.html
src/webui/www/private/newcategory.html
src/webui/www/private/newfeed.html
src/webui/www/private/newfolder.html
src/webui/www/private/newrule.html
src/webui/www/private/newtag.html
src/webui/www/private/rename.html
src/webui/www/private/rename_feed.html
src/webui/www/private/rename_file.html
src/webui/www/private/rename_rule.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/color-scheme.js
src/webui/www/private/setlocation.html
src/webui/www/private/shareratio.html
src/webui/www/private/upload.html
src/webui/www/private/uploadlimit.html
src/webui/www/webui.qrc

A backport of #21750 as a follow up to #21748.
Important notes:
1. The original PR depends on changes from:
#21055
#21289
#21371
They are not in 5.0 branch, so I cut them out. That would need to addressed in the future.
3. A file removed in
#21185
is still present in 5.0, so I modified it too.

WebUI: fix color scheme for iframes (v5_0_x)

---

src/base/utils/os.cpp

Also use scope guards to handle resources.
Related #21788.

Avoid reapplying Mark-of-the-Web when it already exists

---

src/webui/www/private/addpeers.html
src/webui/www/private/addtrackers.html
src/webui/www/private/addwebseeds.html
src/webui/www/private/confirmfeeddeletion.html
src/webui/www/private/confirmtrackerdeletion.html
src/webui/www/private/download.html
src/webui/www/private/downloadlimit.html
src/webui/www/private/edittracker.html
src/webui/www/private/editwebseed.html
src/webui/www/private/newcategory.html
src/webui/www/private/newfeed.html
src/webui/www/private/newfolder.html
src/webui/www/private/newtag.html
src/webui/www/private/rename.html
src/webui/www/private/rename_feed.html
src/webui/www/private/rename_file.html
src/webui/www/private/rename_files.html
src/webui/www/private/scripts/client.js
src/webui/www/private/setlocation.html
src/webui/www/private/shareratio.html
src/webui/www/private/upload.html
src/webui/www/private/uploadlimit.html
src/webui/www/private/views/confirmdeletion.html
src/webui/www/private/views/preferences.html

Closing all windows is overly broad and never the intention.

WebUI: Always close one window

---

src/webui/www/private/download.html
src/webui/www/private/downloadlimit.html
src/webui/www/private/rename_files.html
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/scripts/progressbar.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/speedslider.js
src/webui/www/private/shareratio.html
src/webui/www/private/upload.html
src/webui/www/private/uploadlimit.html
src/webui/www/private/views/log.html
src/webui/www/private/views/preferences.html
src/webui/www/private/views/rssDownloader.html

Also replace `parseInt()` since `Number()` behavior is more intuitive.

WebUI: use native function to convert to numbers

---

src/gui/mainwindow.cpp

Instead of waiting it to complete, now it will react on installation process finish.
Also add more logging.

Improve Python installation process

---

src/webui/www/private/rename_files.html
src/webui/www/private/views/confirmAutoTMM.html
src/webui/www/private/views/confirmdeletion.html
src/webui/www/private/views/installsearchplugin.html
src/webui/www/private/views/preferences.html
src/webui/www/private/views/searchplugins.html

Fix up 1cd3c586c1be5b70db67e811fa149e9c65925129.
Fix up e1bd1038c0e1e540066034ba0ec1c81b5678627e.

WebUI: fix window can not close regression

---

dist/windows/installer-translations/italian.nsh

Translated a missing string for the italian translation

NSIS: Update Italian translation

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h

Avoid race condition when update tracker entries

---

.github/workflows/ci_file_health.yaml

GHA CI: Update `pandoc` to latest

---

src/webui/www/private/rename_files.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/prop-general.js
src/webui/www/private/scripts/prop-trackers.js
src/webui/www/private/scripts/prop-webseeds.js
src/webui/www/private/scripts/rename-files.js
src/webui/www/private/scripts/search.js
src/webui/www/private/views/cookies.html
src/webui/www/private/views/installsearchplugin.html
src/webui/www/private/views/preferences.html
src/webui/www/private/views/rss.html
src/webui/www/private/views/rssDownloader.html
src/webui/www/private/views/searchplugins.html

WebUI: migrate to fetch API

---

src/base/bittorrent/sessionimpl.cpp

Discussion:
https://github.com/qbittorrent/qBittorrent/pull/21296#issuecomment-2562341328
https://github.com/qbittorrent/qBittorrent/pull/21296#issuecomment-2561373010

Revise DHT bootstrap node list

---

src/base/search/searchpluginmanager.cpp
src/gui/search/searchjobwidget.cpp
src/gui/search/searchjobwidget.h
src/gui/search/searchwidget.cpp
src/gui/search/searchwidget.h

Allow to refresh existing search

---

src/base/bittorrent/torrentimpl.cpp

Return first tracker as fallback for "current tracker"

---

.github/workflows/ci_ubuntu.yaml

* Bump `FORTIFY_SOURCE` hardening flag to `3`

GHA CI: Bump `FORTIFY_SOURCE` hardening flag to `3`

---

src/webui/www/private/scripts/misc.js
src/webui/www/private/shareratio.html

This also fix share ratio dialog which had been broken in recent cleanup.

WebUI: inline redundant function

---

src/webui/api/rsscontroller.cpp

WebAPI: Don't trim string parameters

---

src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/misc.js
src/webui/www/private/scripts/progressbar.js
src/webui/www/private/views/preferences.html

Also fix a few variable names along the way.

WebUI: use recommended function for checking NaN values

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/tracker.cpp
src/base/rss/rss_feed.cpp
src/base/settingsstorage.cpp
src/gui/torrentcontentmodelfolder.cpp
src/gui/uithememanager.cpp
src/gui/uithemesource.cpp
src/webui/api/authcontroller.cpp
src/webui/api/searchcontroller.cpp
src/webui/api/synccontroller.cpp
src/webui/webapplication.cpp

This avoids an unnecessary check to the container internal atomic variable and prevents potential detachment.

Use const accessor

---

src/gui/CMakeLists.txt
src/gui/mainwindow.cpp
src/gui/powermanagement/inhibitor.cpp
src/gui/powermanagement/inhibitor.h
src/gui/powermanagement/inhibitordbus.cpp
src/gui/powermanagement/inhibitordbus.h
src/gui/powermanagement/inhibitormacos.cpp
src/gui/powermanagement/inhibitormacos.h
src/gui/powermanagement/inhibitorwindows.cpp
src/gui/powermanagement/inhibitorwindows.h
src/gui/powermanagement/powermanagement.h

Mainly it is about moving each platform code to its own file.

Refactor power management classes

---

src/webui/www/private/css/style.css
src/webui/www/private/rename_files.html
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/search.js
src/webui/www/private/views/filters.html
src/webui/www/private/views/log.html
src/webui/www/private/views/rss.html
src/webui/www/private/views/searchplugins.html
src/webui/www/private/views/transferlist.html

Small fixes/adjustments for changes made in v5.1.

WebUI v5.1 fixes

---

src/webui/www/private/scripts/dynamicTable.js

https://github.com/qbittorrent/qBittorrent/pull/21007 changed pretty much everything already but I spotted some leftovers and replaced them too.

WebUI: Access element attribute/property natively in log tables

---

.github/FUNDING.yml

The website don't use php now.

Update website URL

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/ci_windows.yaml
.github/workflows/coverity-scan.yaml

GHA CI: ensure compatibility with newer cmake versions

---

src/app/application.cpp

Improve command line parameters serialization

---

src/gui/uithemecommon.h

Don't miss to declare some of the color IDs

---

src/base/CMakeLists.txt
src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/freediskspacechecker.cpp
src/base/freediskspacechecker.h
src/base/preferences.cpp
src/base/preferences.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/gui/statusbar.cpp
src/gui/statusbar.h
src/webui/CMakeLists.txt
src/webui/webapplication.cpp
src/webui/webapplication.h

Show free disk space in status bar

---

src/app/application.cpp
src/app/cmdoptions.cpp
src/base/bittorrent/peeraddress.cpp
src/base/bittorrent/sessionimpl.cpp
src/base/http/connection.cpp
src/base/http/requestparser.cpp
src/base/net/smtp.cpp
src/base/path.cpp
src/base/rss/rss_autodownloadrule.cpp
src/base/rss/rss_item.cpp
src/base/rss/rss_session.cpp
src/base/search/searchpluginmanager.cpp
src/base/utils/compare.cpp
src/base/utils/string.h
src/gui/addnewtorrentdialog.cpp
src/gui/fspathedit.cpp
src/gui/optionsdialog.cpp
src/gui/rss/rsswidget.cpp
src/gui/search/searchsortmodel.cpp
src/gui/search/searchwidget.cpp
src/gui/transferlistfilters/categoryfiltermodel.cpp
src/gui/transferlistfilters/trackersfilterwidget.cpp
src/webui/webapplication.cpp

These code segments already have its boundary checked and can thus be faster.

Use slice method where applicable

---

src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/webui/api/appcontroller.cpp
src/webui/www/private/views/preferences.html

Also add a few missing units in WebUI.
Closes #22267.

Add control for 'hostname resolver cache expiry interval'

---

src/base/rss/rss_feed.cpp
src/base/rss/rss_feed.h
src/base/rss/rss_parser.cpp
src/base/rss/rss_session.cpp
src/base/rss/rss_session.h
src/gui/CMakeLists.txt
src/gui/rss/rssfeeddialog.cpp
src/gui/rss/rssfeeddialog.h
src/gui/rss/rssfeeddialog.ui
src/gui/rss/rsswidget.cpp
src/gui/rss/rsswidget.h
src/gui/rss/rsswidget.ui
src/webui/api/rsscontroller.cpp
src/webui/api/rsscontroller.h
src/webui/webapplication.h

RSS: Allow to set refresh interval per feed

---

src/base/rss/rss_session.cpp

RSS: Fix crash when moving a folder into its subfolder

---

src/webui/www/private/scripts/client.js

Related: https://github.com/qbittorrent/qBittorrent/pull/22103/files/73e9116d21015542caeb9a3cfd56bfb256ebed9d#r2014898781

WebUI: fix Tag counter counting wrong

---

WebAPI_Changelog.md
src/webui/webapplication.h

Related: https://github.com/qbittorrent/qBittorrent/pull/22460#issuecomment-2748821812

WebAPI: bump version

---

src/base/net/downloadmanager.cpp
src/base/search/searchdownloadhandler.cpp
src/base/search/searchhandler.cpp
src/base/search/searchpluginmanager.cpp
src/base/search/searchpluginmanager.h

* Refine environment variable scope
Previously the proxy environment variable will affect the qbt process globally. Now it is limited to where it required.
* Simplify proxy related code

Refine environment variable scope

---

src/webui/www/private/scripts/download.js

Thanks for the diagnosis in this [post](https://github.com/qbittorrent/qBittorrent/issues/22495#issue-2958553624).
Closes #21486.
Closes #22495.

WebUI: fix preferences not applied in magnet handler

---

src/base/addtorrentmanager.cpp
src/base/addtorrentmanager.h
src/base/bittorrent/infohash.cpp
src/base/bittorrent/infohash.h
src/base/bittorrent/sessionimpl.cpp
src/base/rss/rss_autodownloader.cpp
src/base/rss/rss_autodownloader.h
src/gui/guiaddtorrentmanager.cpp

Show info hash in log when added a duplicate torrent

---

src/searchengine/nova3/socks.py

Closes #16447 by upgrading `socks.py` from SocksiPy 1.01 to [PySocks 1.7.1](https://github.com/Anorov/PySocks/blob/c2fa43cbe1091e799e248e8e4433978916791a8b/socks.py), allowing python 3+ compatibility, [details](https://github.com/qbittorrent/qBittorrent/issues/16447#issuecomment-2776894026)
The content of the `socks.py` is entirely copied from the [PySocks repository](https://github.com/Anorov/PySocks/blob/c2fa43cbe1091e799e248e8e4433978916791a8b/socks.py), the only modification is the licence hearder at the top of the file.
https://github.com/user-attachments/assets/ad433f8b-face-4f68-986f-142256955aa2

Migrate `socks.py` from SocksiPy 1.01 to PySocks 1.7.1

---

src/gui/powermanagement/inhibitordbus.cpp

ref: https://github.com/qbittorrent/qBittorrent/pull/19333#discussion_r1793252710
cc @Chocobo1

Fix grammar

---

src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.h
src/gui/guiaddtorrentmanager.cpp
src/gui/guiaddtorrentmanager.h

Closes #19933.
Supercedes #22533.

Explicitly reject opened Add torrent dialogs when exiting app

---

src/gui/CMakeLists.txt
src/gui/mainwindow.cpp
src/gui/properties/peerlistwidget.cpp
src/gui/properties/propertieswidget.cpp
src/gui/rss/automatedrssdownloader.cpp
src/gui/rss/rsswidget.cpp
src/gui/trackerlist/trackerlistwidget.cpp
src/gui/transferlistwidget.cpp
src/gui/utils/keysequence.cpp
src/gui/utils/keysequence.h

Closes #20187.
Supersedes #22534.

Use the proper keyboard shortcut for deleting items on macOS

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/torrentimpl.cpp

Fix the torrent relocates files when switching to "manual" mode

---

src/base/bittorrent/bencoderesumedatastorage.cpp
src/base/bittorrent/dbresumedatastorage.cpp
src/base/bittorrent/dbresumedatastorage.h

Prevent crash due to corrupted resume data

---

src/base/bittorrent/bencoderesumedatastorage.cpp
src/base/bittorrent/dbresumedatastorage.cpp
src/base/bittorrent/dbresumedatastorage.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/torrentimpl.cpp
src/base/preferences.cpp
src/base/preferences.h
src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.h
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/gui/guiaddtorrentmanager.cpp
src/gui/guiaddtorrentmanager.h
src/searchengine/nova3/socks.py
src/webui/webapplication.cpp
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/download.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/prop-trackers.js

* #22299
* #22311
* #22480 
* #22487
* #22489
* #22492
* #22504
* #22507
* #22535
* #22537
* #22564
* #22569

Backport changes to v5.1.x branch

---

src/base/search/searchpluginmanager.cpp
src/searchengine/nova3/novaprinter.py
src/searchengine/nova3/socks.py

Also mark variable as private in novaprinter.py.

Add versioning to socks.py

---

src/searchengine/nova3/nova2dl.py

Print error message to stderr instead of stdout.

Improve error messages

---

src/webui/www/private/css/dynamicTable.css
src/webui/www/private/rename_files.html
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/prop-peers.js
src/webui/www/private/scripts/prop-trackers.js
src/webui/www/private/scripts/prop-webseeds.js
src/webui/www/private/views/log.html
src/webui/www/private/views/preferences.html
src/webui/www/private/views/transferlist.html

Adding virtual list support to dynamic tables to improve performance on large lists, I observed a 100x performance improvement on rendering on a torrent table with 5000 torrents:
| Before | After |
|--------|-------|
|![image](https://github.com/user-attachments/assets/c7d9bee1-34a7-4f03-bc50-e414bbc82e7b)|![image](https://github.com/user-attachments/assets/2a3e5b3f-7d09-41c2-989e-dd2a699a2330)|
This optimization is disabled by default and can be enabled in options:

WebUI: Optimize table performance with virtual list

---

src/webui/www/private/scripts/file-tree.js

Browsers have limited recursion depth about ~10000.

WebUI: migrate away from recursion calls

---

src/base/utils/string.cpp

Don't interpret wildcard pattern as filepath globbing

---

src/gui/optionsdialog.ui

Fix appearance of search history length spinbox

---

src/webui/www/eslint.config.mjs
src/webui/www/private/downloadlimit.html
src/webui/www/private/newtag.html
src/webui/www/private/scripts/cache.js
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/localpreferences.js
src/webui/www/private/scripts/pathAutofill.js
src/webui/www/private/scripts/rename-files.js
src/webui/www/private/scripts/search.js
src/webui/www/private/shareratio.html
src/webui/www/private/views/preferences.html
src/webui/www/private/views/rss.html

* WebUI: disallow unnecessary semicolons
* WebUI: ensure consistent shorthand syntax
* WebUI: disallow async functions which have no await expression
* WebUI: remove unused variable

WebUI: enforce coding style

---

src/webui/www/private/scripts/dynamicTable.js

Fixes https://github.com/qbittorrent/qBittorrent/pull/22502#issuecomment-2822201721 and https://github.com/qbittorrent/qBittorrent/pull/22502#issuecomment-2822253388

WebUI: fix virtual list defects

---

src/webui/www/private/scripts/dynamicTable.js

Dynamic table classes are now created using modern class syntax (minimal changes to remove Mootools bits).

WebUI: Use modern class syntax to create dynamic table classes

---

src/webui/www/private/scripts/file-tree.js

* WebUI: migrate 'file tree' class to JS native class
* WebUI: avoid double lookup

WebUI: migrate 'file tree' class to JS native class

---

src/gui/properties/peerlistwidget.cpp
src/gui/properties/propertieswidget.cpp
src/gui/torrentcontentmodel.cpp
src/gui/trackerlist/trackerlistmodel.cpp

Fix async result handlers

---

src/webui/www/private/css/style.css
src/webui/www/private/scripts/piecesbar.js

Mootools is no longer used to create PiecesBar class (+ I cleaned it up a bit and turned into custom element but everything should work as before).

WebUI: Convert 'Pieces Bar' class to a custom element

---

src/base/bittorrent/torrentcreator.cpp

Note that .lnk files (shortcuts) are always ignored on Windows.
Closes #22665.

Allow symbolic links in torrent creator on Windows

---

src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/localpreferences.js

And provide migration path for changing preferences.
Fixes #22639.

WebUI: add versioning to local preferences

---

src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/progressbar.js

Got rid of Mootools and manual calculation of width.

WebUI: Convert 'Progress Bar' class to a custom element

---

dist/windows/config.nsh

The GPL doesn't need to be agreed with and therefore remove 'I accept agreement' checkbox and adjust related UI elements.
screenshot:
Closes #22660.
ps. I avoided adding more text to avoid translation work.

NSIS: revise license page

---

src/gui/optionsdialog.cpp

Ref.: https://github.com/qbittorrent/qBittorrent/pull/22771#discussion_r2124413919.

Fix command line placeholders description

---

WebAPI_Changelog.md
src/webui/api/appcontroller.cpp
src/webui/webapplication.h

Send file / folder metadata instead of just the name of a filesystem entry.
Currently the endpoint only sends a list of string, containing the path of each entry, without specifying its type (file or folder).
The optional `withMetadata` flag has been added to provide metadata and to prevent breaking changes with older versions.
If `true`, JSON response will be an array of objects instead of an array of strings.
Build a server file browser inside WebUIs, feature is currently being developed for [VueTorrent](https://github.com/VueTorrent/VueTorrent).
It will include file metadata, filtering and sorting on the different fields.
Here's the corresponding TS interface for usage in WebUIs:
```typescript
interface BaseFsObject {
/** name of the file system entry, without parent path */
name: …
```

WebAPI: Add metadata in /app/getDirectoryContent response

---

src/webui/www/private/scripts/dynamicTable.js

Avoid recomputing the same result on every sort operation.
Also clean up the caller site.

WebUI: avoid redundant operations when sorting

---

src/base/search/searchpluginmanager.cpp

Don't ignore QFile::open() result

---

test/testpath.cpp

I was experimenting with something the other day and wrote some tests. It would be nice to add them IMO.

Provide testing cases for path concatenation

---

src/base/search/searchhandler.cpp
src/base/search/searchhandler.h
src/base/utils/bytearray.cpp
src/base/utils/bytearray.h
test/testutilsbytearray.cpp

Prevents unnecessary data copying while parsing search results.

Optimize parsing of search results

---

src/gui/properties/downloadedpiecesbar.cpp
src/gui/properties/piecesbar.cpp
src/gui/uithemecommon.h

Allow to customize PiecesBar colors

---

src/webui/www/private/index.html

Follow up to https://github.com/qbittorrent/qBittorrent/pull/22918.

WebUI: Fix footer left alignment

---

src/base/preferences.cpp
src/base/preferences.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/gui/transferlistdelegate.cpp
src/gui/transferlistdelegate.h
src/gui/transferlistmodel.cpp
src/gui/transferlistmodel.h
src/gui/transferlistwidget.cpp

Add option to disable torrent state colors

---

WebAPI_Changelog.md

Fix wrong PR linked in WebAPI changelog

---

src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/views/rss.html

WebUI: Fix broken CACHEID changes

---

.github/workflows/ci_macos.yaml

Failed CI instance: https://github.com/qbittorrent/qBittorrent/actions/runs/16437290836/job/46449723244
Follow up bb1c02125b30eeb537f8e840f2f29364258fc7d9.

GHA CI: fix broken retry when packaging for macOS

---

src/webui/www/private/newcategory.html

Closes #23042. This broke in #22938.

WebUI: Fix editing/creating category

---

src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/views/rssDownloader.html

Unify API usage across the code base.

WebUI: use static method for getting time

---

src/webui/www/private/rename_files.html
src/webui/www/private/scripts/monkeypatch.js
src/webui/www/private/scripts/rename-files.js
src/webui/www/private/views/preferences.html
src/webui/www/private/views/rss.html
src/webui/www/private/views/rssDownloader.html

WebUI: prefer prefix increment operator

---

src/webui/api/apicontroller.cpp

Small quality of life improvement.

WebAPI: send names of missing required params

---

src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h
src/webui/www/private/index.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/mocha-init.js

Allow to copy content paths of selected torrents

---

src/base/bittorrent/sessionimpl.cpp
src/gui/transferlistwidget.cpp

Don't fail because of existing files when exporting torrent files

---

src/base/http/requestparser.cpp
src/base/http/requestparser.h

Now the parsing is done with Views and the conversion to `QString` is only done in the last step.

Improve parsing HTTP request line

---

src/gui/utils.cpp

And log error messages from `stderr`.

Avoid spawning another temporary event loop
