qbittorrent/qBittorrent

src/base/3rdparty/expected.hpp

* Used commit: `95b9cb015fa17baa749c2b396b335906e1596a9e` (Release v0.6.2)
* Source: https://github.com/martinmoene/expected-lite/releases

Sync `nonstd/expected` with upstream

---

src/app/application.cpp

Now the behavior of double quotes aligns more as with issuing commands from shell/command line.
Related: https://github.com/qbittorrent/qBittorrent/pull/17453#issuecomment-1203372027
Tested on linux.

Revise quote behavior

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/ci_windows.yaml
.github/workflows/coverity-scan.yml

IMO it is stable enough that we shouldn't get into problems when github upgrades it.

GHA CI: switch to Ubuntu latest stable version

---

src/webui/www/private/css/style.css
src/webui/www/private/index.html
src/webui/www/private/scripts/piecesbar.js
src/webui/www/private/scripts/prop-general.js
src/webui/www/private/views/properties.html
src/webui/www/webui.qrc

This improves upon the first version of the pieces bar from #15418. I was able to adapt the GUI pieces bar code to work in the WebUI, and simplified it a bit. Original GUI code here https://github.com/qbittorrent/qBittorrent/blob/25b3f2d1a6b14f0fe098fb79a3d034607e52deae/src/gui/properties/downloadedpiecesbar.cpp#L54-L129
This fixes an issue in Firefox when there are more than ~30,000 pieces and also generally is more accurate. Previously a vertical line was drawn for each piece and relied on the browser to scale down the image to fit in the page. Instead now it does the scaling in code and only draws the exact needed number of pixels. This has another added benefit that when resizing the window the bar looks better now too.
Here are some examples of what the new bar looks like, it's …

WebUI: Improve pieces bar drawing algorithm

---

src/base/bittorrent/infohash.cpp
src/base/bittorrent/infohash.h
src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/base/bittorrent/torrentimpl.cpp
src/gui/addnewtorrentdialog.cpp
src/gui/torrentoptionsdialog.cpp
src/webui/api/synccontroller.cpp
src/webui/api/torrentscontroller.cpp

Handle conflict when the same hybrid torrent is added twice by v1 and v2 info hashes (magnet links) separately (in fact, we cannot know that these hashes refer to the same torrent until the metadata is received).
Allow to find hybrid torrent previously added using v1 info hash (magnet link).
Update info hashes and torrent ID of hybrid torrent previously added using v1-only or v2-only info hash once metadata received.
P.S. Because of this mess that hybrid torrents have made, some more conflicts are possible. I'll try to deal with them next time (I'm tired of it now).

Handle some torrent conflicts

---

src/gui/categoryfilterwidget.cpp
src/gui/deletionconfirmationdialog.ui
src/gui/mainwindow.ui
src/gui/tagfilterwidget.cpp
src/gui/transferlistfilterswidget.cpp
src/gui/transferlistwidget.cpp
src/webui/www/private/confirmdeletion.html
src/webui/www/private/index.html
src/webui/www/private/scripts/mocha-init.js

After d28b5f7834c0573ba6ab60892294e95e3e73c9c2, it is a bit inconsistent: the rephrased dialog preferred using 'remove' over 'delete' (as it refers to remove it from the torrent list) so IMO the menu/UI should follow it.

Use proper verb when referring to torrent removal

---

src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h

A little more caching to prevent blocking calls to libtorrent.
It seems that what remains after this PR cannot be cached, since it is updated in the process, so I will have to use other methods to avoid blocking on them.

Cache download/upload limit values

---

src/gui/transferlistwidget.cpp

Allow 'Export .torrent' tooltip to be translatable

---

src/gui/properties/trackerlistwidget.cpp

This is also applicable in `pluginselectdialog.cpp`:  https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/search/pluginselectdialog.cpp#L160, however the search system is in maintenance mode, so the same logic is not applied there.

Avoid string lookup when setting row color

---

src/app/application.cpp
src/webui/www/private/download.html
src/webui/www/private/upload.html
src/webui/www/private/views/preferences.html
src/webui/www/private/views/search.html

* Make strings translatable
* Suppress warning
Seems `lupdate` tool cannot correctly recognize the class/context of `tr()` here, so specify the
class/context manually.

Make strings translatable

---

src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/bittorrent/torrentimpl.cpp

This is a continuation of #17576.
Handles the case when you add hybrid torrent by v1-only magnet link and this torrent is already known by its full hybrid info hash (i.e. by both v1 and v2 info hashes).

Handle more torrent conflicts

---

src/gui/downloadfromurldialog.cpp

Also process URLs in the same order as from the text edit widget.
Closes #17693.

Don't reorder URLs when copied from the clipboard

---

src/webui/api/appcontroller.cpp

Qt6 has changed implementation for `QCoreApplication::quit` and therefore it is not suitable anymore.
Closes #17709.

WebAPI: fix wrong behavior for shutdown action

---

src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/trackerentry.cpp
src/base/bittorrent/trackerentry.h
src/gui/properties/trackerlistwidget.cpp
src/gui/properties/trackerlistwidget.h
src/gui/properties/trackersadditiondialog.cpp
src/gui/properties/trackersadditiondialog.h
src/gui/properties/trackersadditiondialog.ui
src/gui/trackerentriesdialog.cpp
src/webui/api/torrentscontroller.cpp
src/webui/www/private/addtrackers.html
src/webui/www/private/index.html
src/webui/www/private/scripts/prop-trackers.js
test/CMakeLists.txt
test/testbittorrenttrackerentry.cpp

* Rename action
* Revise 'Add trackers' dialog 
* Now it allow user to add tracker to different tier.
* The downloaded trackers are now displayed as is (without modifying).
* Now the dialog remember dialog size and last used URL.
Closes #17692.
[screenshot](https://user-images.githubusercontent.com/9395168/189814358-289550c6-e23b-4a2f-98d4-7909bcf76005.png)

Revise 'Add trackers' dialog

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/torrentimpl.cpp
src/base/preferences.cpp
src/base/preferences.h
src/gui/mainwindow.cpp
src/gui/mainwindow.h
src/gui/optionsdialog.cpp

* Reorder operations in 'torrent finished' handler
Avoid redundant data fetch.
Remove debug messages.
* Clean up 'recursive download' related code
Don't load .torrent files too early, otherwise qbt might emit a dubious error log message if the .torrent file is invalid.

Clean up 'recursive download' related code

---

src/gui/utils.cpp

Replaced QDesktopServices by native Windows function to open destination folder due to QDesktopServices issues on Windows
Closes #17482.
The specific kinda "black box" function is QDesktopServices::openUrl.
The issues are described in #17482 and even more detailed in https://github.com/qbittorrent/qBittorrent/discussions/17025

Fixes "Open destination folder" delay on Windows

---

src/gui/log/loglistview.cpp
src/gui/utils.cpp
src/gui/utils.h

* Revive dark theme detection
The code was removed in 199d770 and now revived.
I reckon this function would be useful in the future despite it isn't in use currently.
* Simplify code
Don't use replacement placeholder and use string append which is faster.
* Use proper color for highlighted text in log widget
The color is either from qbt theme pack or desktop environment.
Before:
After:

Use proper color for highlighted text in log widget 

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_windows.yaml

* Bumped Windows/macOS `Qt6` version to `6.4.0`
* Suppressed `gnu-zero-variadic-macro-arguments` warning on `macOS` (Qt6 only)

GHA CI: Bump Windows/macOS `Qt6` version to `6.4.0`

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/ci_windows.yaml
.github/workflows/coverity-scan.yml

* GHA CI: only install required Qt components
So it won't waste time download/install unused Qt components.
* GHA CI: bump Qt version to 6.4.0

GHA CI: only install required Qt components

---

src/base/bittorrent/torrentimpl.cpp

There's really nothing to move if the torrent still doesn't have metadata.
Additionally, such torrents in the queue can lead to unexpected behavior when reloading the torrent after metadata is received.

Don't pollute move queue by torrents w/o metadata

---

src/base/utils/string.cpp

I'm opening this PR to make sure the broken #16965 doesn't land into 4.5.0 release.
As spotted by @tristanleboss, and as I confirmed too, the implementation appeared to be broken. See https://github.com/qbittorrent/qBittorrent/pull/16965#issuecomment-1263084823 and following.
Until the implementation is fixed, or better, an UI letting optionally use the wildcards is implemented (see https://github.com/qbittorrent/qBittorrent/pull/9255#issuecomment-1263081969 and following), it should be reverted.

Revert "Consider brackets within wildcard as regular characters"

---

src/gui/transferlistfilterswidget.cpp
src/gui/transferlistfilterswidget.h

* Fix wrong 'tracker error' count
This happens when a torrent contains some tracker URLs that share the same domain.
Closes #17808.

Fix wrong 'tracker error' count

---

src/base/bittorrent/customstorage.cpp

The `lt::status_t::file_exist` is returned when `lt::move_flags_t::fail_if_exist` is used, which means the whole move operation failed. So hanlde this condition correctly (even if the `fail_if_exist` isn't used in the code base currently).

Support 'file exists' situation

---

.github/workflows/coverity-scan.yml
src/gui/fspathedit.cpp

* Set proper focus on widget
And also allow keyboard tabbing to the Browse button.
Fix up 6ab3551.
* GHA CI: add missing cmake flag for Qt6

Set proper focus on widget

---

src/base/bittorrent/addtorrentparams.h
src/base/bittorrent/bencoderesumedatastorage.cpp
src/base/bittorrent/dbresumedatastorage.cpp
src/base/bittorrent/dbresumedatastorage.h
src/base/bittorrent/loadtorrentparams.h
src/base/bittorrent/nativetorrentextension.cpp
src/base/bittorrent/nativetorrentextension.h
src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/bittorrent/torrent.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h
src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.ui
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/webui/api/torrentscontroller.cpp
src/webui/webapplication.h

Closes #17792.
Closes #929.
_(Actually it should close all issues about lack of ability to stop torrent after metadata downloaded or after files are initially checked.)_
Also makes explicit the temporary start of the torrent in the case when recheck of the stopped torrent is performed.
Preferences:
Add new torrent dialog:

Allow to set torrent stop condition

---

.github/workflows/coverity-scan.yml
src/gui/downloadfromurldialog.cpp
src/gui/transferlistmodel.cpp

* Show 'N/A' when there is no hash
This is to follow 'General' tab which show 'N/A' when there is no hash.
* Use Path internal representation for internal value in model
The internal value is used for sorting comparisons and not displayed to the user, so make a shortcut.
* Capitalize header title
This is the only one not properly capitalized.
* Don't use hardcoded URL scheme list
This is to avoid the list being outdated.
* GHA CI: add missing Qt module

Show N/A when there is no hash

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h

Prevent existing files overwriting when torrent is moved automatically (e.g. when moved from incomplete to final save path).

Use 'fail if exist' strategy on automatic move

---

src/webui/www/private/scripts/client.js
src/webui/www/private/upload.html

* WebUI: simplify attribute usage
The `multiple` attribute is a boolean value and its presence equals to `true`.
* WebUI: filter file selection to bittorrent files
Note that the user can still overwrite the selection filter and select other files.
* WebUI: handle drag and drop events
This allows user to drag and drop .torrent files and URL links onto the main window and will open the respective dialog.
Dropping folders are not supported due to technical reasons.
Closes #6038.

WebUI: handle drag and drop events 

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/bittorrent/torrentimpl.cpp

When shutting down, instead of waiting for all types of alert from libtorrent, now it only waits for specific alert types. This potentially help shorten the shutdown waiting time.

Revise "save resume data" handling on shutdown

---

src/gui/CMakeLists.txt
src/gui/color.h
src/gui/gui.pri
src/gui/log/logmodel.cpp
src/gui/transferlistmodel.cpp

This commit introduce color palettes from Primer and make use of it in various widgets.
Primer system is chosen due to well designed and is highly rated on Github (in terms of Github stars).
https://primer.style/primitives/colors
Screenshots:
[Transfer List light](https://user-images.githubusercontent.com/9395168/193185017-6841d796-fd21-4388-be0f-c527c6224f15.png)
[Transfer List dark](https://user-images.githubusercontent.com/9395168/193185024-fe2a7a9f-8aa5-4eb1-aa7c-eab7369c8fa6.png)
[Log light](https://user-images.githubusercontent.com/9395168/193185023-df4e3406-1ab5-4f46-92a4-0951f0b0a8f2.png)
[Log dark](https://user-images.githubusercontent.com/9395168/193185020-b69b21db-1ed1-4f56-a505-8efd21945beb.png)
I'm open to suggestions on the colors from Primer.. note that I didn't radically …

Introduce color palettes for both dark, light themes

---

src/base/net/geoipdatabase.cpp
src/base/net/geoipdatabase.h

Applied rule of three to GeoIPDatabase class. Combined variable declaration with initialization.

Make GeoIPDatabase interface safer

---

src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/webui/api/appcontroller.cpp
src/webui/webapplication.h
src/webui/www/private/views/preferences.html

Add a UI option for "Use proxy for hostname lookup" option and plumb it into libtorrent's settings_pack.proxy_hostnames option.  This is available for SOCKS5 and HTTP proxies, and defaults to true, which is the previous functionality.  Hostname lookups can be forced to be local by unchecking this option, which can aid compatibility with certain non-compliant proxy servers.
UI changes:
Closes #17902

Add a "Use proxy for hostname lookup" option

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/ci_windows.yaml
.github/workflows/coverity-scan.yml

* https://github.com/arvidn/libtorrent/releases/tag/v2.0.8
* https://github.com/arvidn/libtorrent/releases/tag/v1.2.18
NOTE:
Will create separate PR after this is merged raising minimum libtorrent requirements (if no objections).

GHA CI: Bump libtorrent version(s)

---

src/base/bittorrent/sessionimpl.cpp

Otherwise it can crash after converting resume data storage.

Correctly destroy startup resume data storage

---

src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentinfo.cpp

This happens when the `index` is a negative number.

Avoid out-of-bounds access

---

src/base/bittorrent/sessionimpl.cpp

There might be alerts already queued in buffer waiting to be handled at the time of pausing the session, so don't skip over them.
Discussed in https://github.com/qbittorrent/qBittorrent/pull/17885#issuecomment-1279917556

Handle all types of alerts on shutdown

---

src/base/bittorrent/portforwarderimpl.cpp
src/base/bittorrent/portforwarderimpl.h
src/base/net/portforwarder.h
src/webui/webui.cpp
src/webui/webui.h

This eases the usage of port forwarder as the caller code doesn't need to store previous used port and now can rely on port forwarder doing all the hard work.

Revise interface of port forwarder

---

src/base/bittorrent/bencoderesumedatastorage.cpp
src/base/bittorrent/dbresumedatastorage.cpp
src/base/bittorrent/loadtorrentparams.h
src/base/bittorrent/sessionimpl.cpp

This is now known from the session stage.

Don't use extra variable to distinguish restored torrents

---

src/gui/transferlistwidget.cpp
src/webui/www/private/scripts/mocha-init.js

Closes #17683
This adds a confirmation dialog to Pause All and Resume All. First I wanted to only add it in Tray, but honestly, clicking around in the menu, using hotkeys might trigger it just as easy.
This introduces new strings (please check) for the confirm/resume, so it adds 4 new translations.
It uses an existing confirmation dialog, taken from `recheckSelectedTorrents()`.
Feel free to reject it, I just "felt" the user's pain. Some people run 1000+ torrents and this might ease their pain.

Add confirmation to resume/pause all

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h

It was really bad to use blocking call within loop for each torrent.

Save torrents queue w/o blocking calls

---

src/base/bittorrent/portforwarderimpl.cpp
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h

We don't really need to get currently used settings pack in order to apply changes to session settings. It is enough to apply settings pack that contains only updated settings.

Avoid blocking call when changing libtorrent session settings

---

src/gui/torrentcontentmodel.cpp
src/gui/torrentcontentmodel.h

This is alternative approach to #17786. It uses the similar workaround as was used a long time with Qt5 and stoped working with Qt6 so it is adjusted in this PR.
Also this fixes content model resetting handling.

Use another workaround to update files tree view

---

src/base/torrentfileswatcher.cpp

Otherwise there are the following debug messages:
>QObject::killTimer: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread

Destroy object within appropriate thread

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h

Fixes regression since b68c4e21065fb6b1c84b53f8bfc0d0761cb08e74.
Closes #18030.
It seems that this tangle with saving resume data for a new torrent twice has finally unraveled. Previous attempts have resulted in one of the following:
1. Metadata is saved but resume data is incorrect
2. Correct resume data is saved but metadata is missing

Don't miss to store metadata of new torrent

---

src/gui/torrentcontentmodel.cpp
src/gui/torrentcontentmodel.h

This reverts commit 0f82c169362cd2e26c053725d3b8fae3889f1655.
There were some non-obvious defects, so it seems it would be better to return to a more reliable (although possibly more expensive) method of notifying the View about data changed.
Closes #18036.

Revert "Use another workaround to update files tree view"

---

src/base/torrentfileswatcher.cpp

Temporary solution for https://github.com/qbittorrent/qBittorrent/issues/18059
This reverts commit https://github.com/qbittorrent/qBittorrent/commit/4f2ac34440aca89bd6874bcc46e357d0bcf9afd9.

Temporarily fix blocker for v4_5_x

---

src/app/application.cpp

Otherwise it is destructed in QObject destructor, i.e. after GUI application is already destructed.
This can be related to some problems with system tray icon.
Closes #18093.

Destroy desktop integration at correct place

---

src/webui/api/torrentscontroller.cpp

WebAPI: return paths using platform-independent separator format

---

src/gui/color.h
src/gui/transferlistmodel.cpp

Now it uses the purple color which matches the completed status icon color.
[screenshot](https://user-images.githubusercontent.com/9395168/204402401-7c3700ff-102f-49a3-adfc-11d193df3488.png)
Related: #18078.

Revise text color for completed status

---

src/base/bittorrent/torrentimpl.cpp

Closes #18070.
The problem is that conversions between `std::string` and `QString` is not mutually equivalent (i.e. `QString::fromStdString(stdStr).toStdString() == stdStr` isn't always `true`).

Use identical conversions of tracker names

---

src/webui/www/private/rename_file.html
src/webui/www/private/scripts/prop-files.js

* WebUI: Make rename file dialog resizable
And enlarge dialog default width.
inline with https://github.com/qbittorrent/qBittorrent/pull/16784

WebUI: Make rename file dialog resizable

---

src/gui/rss/automatedrssdownloader.cpp
src/gui/rss/automatedrssdownloader.h
src/gui/rss/automatedrssdownloader.ui

This is quite the simple PR. It simply adds a new button to RSS Downloader so people are aware that they can rename. It's just usability, in my opinion.
At the moment, users can press F2 (only found this in source code) and double-click to rename a rule's title. But, there is no real hint about this. So I thought this button would be helpful, especially for the less techie people.
Feel free to reject it, if you don't agree.

Add "Rename rule" button to RSS Downloader

---

.github/workflows/ci_ubuntu.yaml
.github/workflows/helper/appimage/export_vars.sh
.github/workflows/helper/appimage/org.qbittorrent.qBittorrent.desktop

Upload an AppImage artifact on CI builds. This AppImage is a simplified version of the official one. It is meant to help with debugging PRs that fix issues.

CI: Build AppImage

---

src/base/bittorrent/peerinfo.cpp
src/base/bittorrent/peerinfo.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/bittorrent/torrent.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h
src/gui/properties/peerlistwidget.cpp
src/gui/properties/propertieswidget.cpp
src/gui/properties/trackerlistwidget.cpp

This (together with #18010) should prevent UI from being freezed when updates some data fetching from libtorrent when it does some hard work.
I tried to touch on all cases when it comes to regular auto-updates. There are still untouched cases when data is fetched on demand, for example, exporting a .torrent file or magnet link, etc. The Web API requires additional refactoring so that a similar approach can be applied there. This will follow further.

Fetch data asynchronously

---

src/base/bittorrent/sessionimpl.cpp

This can help when the DHT nodes are few.
Closes #18244.

Use "additional trackers" when metadata retrieving

---

src/webui/www/private/views/properties.html

This addresses an issue that the "Progress:" hint text is broken into several lines when using certain languages (e.g. `ja`, `zh-CN`, `zh-HK` and `zh-TW`).
* Current as in `en`
* Current as in `zh-CN`
* Expected as in `zh-CN`

WebUI: Prevent incorrect line breaking in properties panel

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_windows.yaml

* GHA CI: Bump Windows/macOS `Boost` version to `1.81.0`
* [Boost 1.81.0 Release Notes](https://www.boost.org/users/history/version_1_81_0.html)

GHA CI: Bump Windows/macOS `Boost` version to `1.81.0`

---

src/gui/torrentcategorydialog.cpp
src/gui/torrentcategorydialog.ui

Also pre-select (sub)category name for editing when dialog is opened for creating new (sub)category.
Closes #18265.

Apply correct tab order to Category options dialog

---

src/webui/api/torrentscontroller.cpp

Make properties endpoint less painful to use by adding more data returned (name and torrentID), related to #18188.
Does not close the ticket because maybe having a new endpoint would be even more convenient, as explained in the issue.
I could not run tests on my machine due to cmake shenanigans. I'll try on another machine soon.

WebAPI: Add "name" and "hash" fields to "torrents/properties" result

---

src/base/utils/misc.cpp
src/base/utils/misc.h
src/gui/optionsdialog.cpp
src/webui/webapplication.cpp
src/webui/www/private/views/preferences.html

This will avoid hardcoding the language list in JS. Also, different language naming conventions are used in in WEBUI and ts files, which will make GUI and WEBUI save different locale settings for some languages, such as `ar` and `ar_AE` for GUI and WEBUI respectively.

Unify the way to generate the language list in WebUI and GUI

---

src/webui/www/private/upload.html

On iOS (Chrome/Safari/Firefox) the existing file upload page uses a input file type with an `accept` attribute of `application/x-bittorrent, .torrent` does not allow the user to click any BitTorrent or `.torrent` files.  Swapping the order retains the existing functionality of selecting BitTorrent and .torrent files on other platforms but also allows iOS users to upload torrent files.

WebUI: change order of accepted types of file input

---

src/webui/www/private/scripts/client.js

Check if the active element is an input  or text area before triggering the hotkey and preventing the default action. Fixes #18325.

WebUI: Improve hotkeys

---

src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/gui/mainwindow.cpp

Such helpers do not make practical sense, since they can be trivially implemented on top of the base interface, but at the same time they can lead to undesirable consequences when some calling code requires slightly different behavior than another.
Fixes #18338.

Remove confusing helpers from Session interface

---

src/base/bittorrent/resumedatastorage.cpp
src/base/bittorrent/resumedatastorage.h
src/base/bittorrent/sessionimpl.cpp

Use more appropriate container (`QList`) for resume data queue buffer. `QVector` in Qt5 has poor performance of the first element taking operation, which is used to process the resume data queue. In Qt6, `QVector` is just an alias for `QList`, so there was no problem there.
Fixes #18341.

Fix startup performance on Qt5

---

src/app/application.cpp
src/app/application.h
src/app/upgrade.cpp
src/base/preferences.cpp
src/base/preferences.h
src/gui/CMakeLists.txt
src/gui/desktopintegration.cpp
src/gui/gui.pri
src/gui/mainwindow.cpp
src/gui/mainwindow.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.h
src/gui/optionsdialog.ui
src/gui/windowstate.h

Replace current "Start qBittorrent minimized" option with "Initial window state" that allows to start qBittorrent as "hidden in system tray" while retaining regular "minimize to panel" functionality.
Closes #487.

Improve startup window state handling

---

src/webui/www/private/views/search.html

Added autocomplete="off"  for the search input box. 
Don't want torrent search history to pop up next time you try to search for torrents.. right? 
There are people who would search for 18+ content and what they searched would load up next time they are about to search.

WebUI: disable "auto complete" for torrent search input

---

src/base/preferences.cpp
src/base/preferences.h
src/webui/webapplication.cpp
src/webui/webapplication.h

WebAPI: Allow to specify session cookie name

---

src/gui/windowstate.h

Fixes build with '-pedantic' flag.
GCC 10 on Debian 11 seems to be more stricter than GCC 12 regarding '-pedantic -pedantic-errors' compiler flags, so extra ';' (because another one is hidden in macro) leads to build error.
```
[  473s] ../src/gui/windowstate.h:45:27: error: extra ‘;’ [-Wpedantic]
[  473s]    45 |     Q_ENUM_NS(WindowState);
[  473s]       |                           ^
```
Strange, GCC 12 with the same options set doesn't produce even warning.
fixup 32e437120823120e233ea589c3901cfc9b528f82
detected on ci building nightly packages for Debian, all builds for Debian 11 failed regardless of target architecture.
full command line:
```
[  473s] FAILED: src/gui/CMakeFiles/qbt_gui.dir/advancedsettings.cpp.o 
[  473s] /usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_ASIO_ENABLE_CANCELIO …
```

Drop extra semicolon

---

dist/windows/installer.nsi
src/app/main.cpp

This was discovered by investigating https://github.com/qbittorrent/qBittorrent/issues/18339#issuecomment-1384204242

Fix PDB loading for valid stacktraces

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h

Adjusting limits was made based on the belief that "forced" torrents (internally used for prefetching metadata) are still under limits, but ignore only the queue. This is not really the case. "Forced" torrents ignore the limits like "maximum active torrents/downloads", so adjusting limits is not required, and what's more, it really causes the problem of unexpectedly activated previously queued torrents when adding some magnet using "Add new torrent" dialog.
Fixes #18490.

Don't increase limits when prefetching metadata for added magnets

---

src/app/application.cpp
src/app/application.h
src/app/cmdoptions.cpp
src/app/cmdoptions.h
src/app/main.cpp

Encapsulate parameters dispatching in Application class.
Avoid serializing parameters when it is not necessary.

Improve command line parameters dispatching

---

src/base/bittorrent/torrentimpl.cpp

I believe it's better to revert this changes until complex  solution is available. IIRC, "fail if exists" strategy can make the life hard for much many users (after all, files with the same name but different content are unlikely to occur more often than really matching files).
Closes #18297.
Closes #18495.

Revert changes of conflict resolution strategy on automatic move

---

src/base/http/server.cpp

This is an alternative to PR #18486
See my comment for some explanation https://github.com/qbittorrent/qBittorrent/pull/18486#issuecomment-1409475175
And my code comments for the rest.
Very useful site for the Ciphersuite list/explanation: https://ciphersuite.info (be sure to select `OpenSSL` in order to get the correct name strings)
Closes https://github.com/qbittorrent/qBittorrent/issues/18483
Closes https://github.com/qbittorrent/qBittorrent/issues/18122

Harden the SSL/TLS web server

---

src/gui/log/logmodel.cpp
src/gui/rss/articlelistwidget.cpp
src/gui/transferlistmodel.cpp
src/gui/uithememanager.cpp
src/gui/uithememanager.h
src/gui/utils.cpp
src/webui/webapplication.cpp

Allows to use another icons in dark mode. You can put them to `<config>/themes/default/icons/dark` folder (restart is required). Once some icon set was ready and approved we'll build it into executable alongside with default one.
Also allows to override default colors for dark mode via `<config>/themes/default/config.json` (using "colors.dark" dictionary).

Allow to use another icons in dark mode

---

src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/webui/api/synccontroller.cpp
src/webui/api/synccontroller.h

Don't serialize and compare all the data on each `sync/maindata` request but track changes between two subsequent requests and serialize/compare only knownlingly changed data. This should significantly improve the server side performance when synchronizing a large number of torrents (unless I am mistaken in my estimates).

WebAPI: Improve "sync/maindata" performance

---

src/webui/api/appcontroller.cpp
src/webui/webapplication.h
src/webui/www/private/views/preferences.html
src/webui/www/private/views/preferencesToolbar.html

Closes #17421.
- Add `Behavior` tab and filelog settings.
- Move language and  `Log performance warnings` settings to `Behavior` tab. This is consistent with the GUI.
Screenshot:

WebUI: Add filelog settings

---

src/app/main.cpp
src/base/bittorrent/sessionimpl.cpp
src/base/torrentfileswatcher.cpp
src/webui/api/appcontroller.cpp

The implementation of QTimer::singleShot() uses Qt::PreciseTimer if interval is less than 2 seconds. This isn't mentioned in the docs.
Qt::PreciseTimer increases the system's timer resolution which negatively affects power consumption.
Closes #18350.
Supercedes #18475.

Prevent precise timers from being used when unnecessary

---

src/webui/www/private/scripts/client.js

MooTools More has CVE-2021-20088 and qbt is affected by it by using the unsafe function call `String.parseQueryString()`, so migrate away from it.

Migrate away from unsafe function

---

src/base/bittorrent/extensiondata.h
src/base/bittorrent/nativesessionextension.cpp
src/base/bittorrent/nativetorrentextension.cpp
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h

In particular, this should further improve the performance of the sync API by reducing the number of blocking calls that are made each time the torrent data is serialized.

Access some more data in a non-blocking manner

---

src/gui/properties/peerlistwidget.cpp

Followed the compilation and build guide:
https://github.com/qbittorrent/qBittorrent/wiki/Compilation:-Windows-(MSVC-2019,-64-bit,-static-linkage)
Tested and working on Windows 10 Pro Version 22H2 (OS Build 19045.2486).

Add shortcut for "Ban peer permanently" function

---

src/base/bittorrent/torrentimpl.cpp

We have to force update the cached state, otherwise someone will be able to get an incorrect one during the interval until the cached state is updated in a regular way.
Closes #18559.

Update the cached state once recheck is started

---

.github/workflows/ci_file_health.yaml
.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/ci_webui.yaml
.github/workflows/ci_windows.yaml
.github/workflows/coverity-scan.yml
.github/workflows/stale_bot.yaml

* GHA CI: speed up package installation on macOS
Setup time is shortened by cutting down unnecessary operations.
https://docs.brew.sh/Manpage#environment
* GHA CI: use least permission level
`actions: write` is required by Chocobo1/setup-ccache-action.
`pull-requests: write` is required by actions/stale.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
* GHA CI: revert "[CI Ubuntu] Strip installed components"
For tester convenience, the binaries should ship with debug symbols.
This reverts commit b8aa9e5.
* GHA CI: don't overwrite system default compile flags
System might have some default compile flags which are crucial for security hardening so we should append our flags instead of overwriting them.
* GHA CI: compress debug symbols
The …

GHA CI improvements

---

src/base/bittorrent/sessionimpl.cpp

As the name implies, this PR adds filtered port numbers in logs.
I am not sure about implementation here, so it needs a review.

Show filtered port numbers in logs

---

src/webui/www/private/css/style.css
src/webui/www/private/index.html
src/webui/www/private/rename_files.html
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/file-tree.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/scripts/preferences.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/rename-files.js
src/webui/www/private/views/transferlist.html
src/webui/www/webui.qrc

Closes #16239.
(Partially addresses #6961.)
The purpose of the PR is to enable users to bulk rename files on the WebUI. 
_Image Description: Renaming 200 config files using a named variable and the file enumeration variable_
**Search Field**: The text criteria to search for as either a plain text string or a regular expression.
**Use Regular Expressions**: When checked, the search field will be interpreted as an ECMAScript regular expression. If not then the search field will be interpreted as a plain text string.
**Match all occurrences**: When checked, all matches of text in the search field will be replaced with the replacement text. Otherwise, only the first instance will be replaced.
**Case Sensitive**: When checked, the text specified in the search field will be treated as case …

WebUI: add multi-file renaming

---

src/webui/api/torrentscontroller.cpp

WebAPI: Allow to set read-only directory as torrent location

---

src/base/bittorrent/dbresumedatastorage.cpp

This should prevent SQLite temporary files from being created for transient index when selecting torrents ordered by queue position.

Index torrents table by queue position

---

src/base/bittorrent/dbresumedatastorage.cpp

Otherwise, when downgrading to qBittorrent version that used the previous database format, the database version is mistakenly overwritten by the old one, so that a conflict occurs when upgrading again.

Correctly check for database needs to be updated

---

src/base/bittorrent/dbresumedatastorage.cpp

SQLite based resume data storage is redesigned to give async worker more control over the queue of incoming change requests, so that it can now execute multiple adjacent queries within a single transaction, which is supposed to improve disk I/O performance.

Apply adjacent changes within single transaction

---

src/gui/mainwindow.cpp
src/gui/mainwindow.h
src/gui/transferlistmodel.h
src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h

Responding to #16335
**Add a combobox to select to filter by name or save path** 
Easily expandable to include other filters as the combobox item just need to have a `TransferListModel::Column`  data
ps : this is my first pull request, sorry for mistakes

Allow to filter torrent list by save path

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/ci_webui.yaml
.github/workflows/helper/codeql/cpp.yaml
.github/workflows/helper/codeql/js.yaml
src/webui/www/private/rename_files.html
src/webui/www/private/scripts/piecesbar.js
src/webui/www/private/scripts/prop-files.js

* GHA CI: add CodeQL scanning
This enable codebase scanning for C++ and JavaScript languages.
https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql
https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/customizing-code-scanning
* GHA CI: drop needless syntax
https://docs.github.com/en/actions/learn-github-actions/expressions#about-expressions
>When you use expressions in an if conditional, you may omit the
>expression syntax (${{ }}) because GitHub automatically evaluates the if conditional as an expression.
* Fix code defects

GHA CI: add CodeQL scanning

---

src/base/bittorrent/sessionimpl.cpp
src/base/digest32.h

Since standard library could have platform dependent specialized hashing functions.
Also the main idea is to let `qHash` handle whatever integer type `std::hash` returns and mix it with `seed` accordingly.
ps. this should be backported once merged.

Delegate string hashing to standard library

---

src/base/algorithm.h
src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/gui/properties/peerlistwidget.cpp
src/gui/properties/peerlistwidget.h

Closes #16257.
Supersedes #18462.

Add I2P support

---

src/gui/desktopintegration.cpp
src/gui/desktopintegration.h
src/gui/uithememanager.cpp
src/gui/uithememanager.h

Currently qBittorrent uses system tray icon from the Linux system theme regardless of whether the corresponding option is enabled. It looks inconsistent/incorrect to me and I believe this should be fixed.

Use tray icon from system theme only if option is set

---

src/webui/api/appcontroller.cpp
src/webui/api/synccontroller.cpp
src/webui/www/private/index.html
src/webui/www/private/newcategory.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/views/filters.html
src/webui/www/private/views/preferences.html

- Show subcategories in a tree view in WebUI
- Add `Add subcategory...` context option to WebUI
- Add `use_subcategories` property to maindata in WebAPI
- Add `Use subcategories` preference to WebUI & WebAPI
Closes #12819

WebUI: Implement subcategories

---

src/webui/webapplication.cpp

TL;DR: Make CORS works by only little change.
Google Chrome changed cross-site cookie policy on 2020 https://developers.google.com/search/blog/2020/01/get-ready-for-new-samesitenone-secure When no `SameSite` set, default value changes from `None` to `Lax`, which will prevent CORS access. This PR set `SameSite` to `None` when CSRFProtection is Disabled by user.
ref #16993 #9884
Tip: to make cors really works, https and `Secure` flag shoule be enabled,  `access-control` headers should be set.

Set "SameSite=None" if CSRF Protection is disabled

---

src/gui/mainwindow.cpp

While a torrent is considered "finished" upon download completion, a session's handleTorrentFinished() event is only queued after any relevant move event is completed. So if a user chooses a post-download action such as system shutdown, torrents will finish, move, and then shutdown occurs.
However, inhibit system sleep behaviour is managed by an independent timer than checks the native status of torrents. This leads to a particular scenario where the user may expect sleep to be inhibited until downloads complete, followed by the system hibernating/shutting down/etc. But since sleep inhibition lapses as soon as torrents are downloaded, a move operation of sufficient duration may allow the system to suspend, meaning the expected post-download action is not executed.
I'm not sure this …

Inhibit system sleep while torrents are moving

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_windows.yaml
.github/workflows/coverity-scan.yml

Updated some Windows/macOS dependencies
* Qt 6.5.0
* Boost 1.82.0
Note:
I left Qt 6.2.0 on `linux`, didn't try to remove `qtdeclarative` dependency on `macOS`
Updated `Coverityscan` with Qt 6.5.0

GHA CI: Update some dependencies

---

src/base/bittorrent/customstorage.cpp

libtorrent has made the following change to its master branch: "make status_t a proper flag type, to clean up oversized_file indication from disk subsystem"

Replace status_t with disk_status

---

src/base/bittorrent/sessionimpl.cpp
src/gui/addnewtorrentdialog.cpp
src/gui/addtorrentparamswidget.cpp

In #18824 I lost my way, trying to unify the work of interfaces of different levels.
This patch should make the behavior of the low-level interface more logical when resolving effective values of omitted parameters considering explicitly specified ones.
E.g. when user specifies "download path" it's more obvious that he/she wants to use it even if "use download path" is omitted.
These changes do not affect the parameters editing UI, since there is supposed to be a somewhat different way of perception (which was actually the problem), i.e. if the user explicitly sets "Use download path" as "Default" there, then he/she really wants to use the default value instead of specifying any path.
Closes #18951.

Consider explicitly specified parameters when resolving optional ones

---

src/base/search/searchdownloadhandler.cpp
src/base/search/searchhandler.cpp
src/base/search/searchpluginmanager.cpp
src/base/utils/foreignapps.h
src/searchengine/nova3/nova2.py
src/searchengine/nova3/nova2dl.py

This (more or less) avoids user's environment variables tampering the search process.
I'm not sure it will solve all 'plugins unworkable' issues but at least it should shrink the problem surface.

Use python isolate mode

---

INSTALL
src/base/utils/foreignapps.cpp
src/gui/mainwindow.cpp
src/gui/programupdater.cpp

How was the `3.7.0` decided? I took a look at https://repology.org/project/python/versions and look at the relic `debian 10` and used that.
For the Windows installer: I looked at https://devguide.python.org/versions/#python-release-cycle and took the latest branch/version that is in the `security` phase.
ps. The deciding process should probably be formalized and recorded in INSTALL file...

Bump python version minimum requirement

---

.github/workflows/ci_ubuntu.yaml

Since appimage is bundling the libraries it make sense to embed libtorrent statically into qbt binary.
Another side effect is now qbt binary includes debug symbols from libtorrent too (which I consider a good thing for debugging). Previously appimage seems to (unnecessarily) strip the libtorrent debug symbols.
ps. this only affects linux appimages.

GHA CI: build libtorrent as a static library

---

src/webui/www/private/scripts/download.js

Fixes the displayed default category save path. The default save path does not contain a trailing slash so there was a missing slash in between the default save path and the category name.
Before|After
-------|-----

WebUI: Fix category save path

---

src/gui/mainwindow.cpp

Fixes regression of #18726.
Incorrect:
Correct:

Fix incorrect height of Filter line edit

---

.appveyor.yml

The package is also updated to:
OpenSSL: 1.1.1t
Boost: 1.82.0
Libtorrent: 2.0.9+git73089332ab
and the config needs some updating to accommodate the new structure.

AppVeyor update config

---

src/webui/www/private/index.html
src/webui/www/private/scripts/client.js

Sets the title on the connection status and speed limits icons so that the tooltip matches.
Before|After
------|-----
Fixes #18958

WebUI: Set Connection status and Speed limits tooltips

---

src/base/rss/rss_autodownloader.cpp
src/base/rss/rss_autodownloader.h
src/base/rss/rss_autodownloadrule.cpp
src/base/rss/rss_autodownloadrule.h
src/gui/mainwindow.cpp
src/gui/rss/automatedrssdownloader.cpp
src/gui/rss/automatedrssdownloader.ui
src/webui/api/rsscontroller.cpp

When an article matches to several rules, it is processed by the first of them. Previously, rules were applied in an arbitrary order, but it may be useful to be able to affect their order.

Allow to assign priority to RSS download rule

---

src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h

Closes #18980.
Screenshot of new options:

Make I2P session options configurable

---

src/base/http/types.h
src/webui/webapplication.cpp

This separates browsing context for different origin sites and prevents leaking data from it.
This header is only present when using built-in WebUI. Alternative WebUI is not affected.
https://web.dev/why-coop-coep/#coop

WebUI: set Cross Origin Opener Policy to `same-origin`

---

src/gui/mainwindow.cpp

Not sure whether this is the best way to fix it. `Alt + 1` wouldn't change to transfer list tab.

Fix transfer list tab hotkey

---

src/gui/mainwindow.cpp
src/gui/search/searchwidget.cpp

Closes #19180
Followed the compilation and build guide:
https://github.com/qbittorrent/qBittorrent/wiki/Compilation:-Windows-(MSVC-2019,-64-bit,-static-linkage)
Tested and working on Windows 10 Pro Version 22H2 (OS Build 19045.3086).

Add alternative shortcut CTRL+E for CTRL+F

---

src/base/bittorrent/peerinfo.cpp
src/base/bittorrent/sessionimpl.cpp
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/gui/optionsdialog.cpp

libtorrent 1.2 does not contain a lot of I2P related fixes made recently, and I2P is almost completely unusable there (according to the feedbacks of the users involved).
Also fixes build when libtorrent is compiled with I2P support disabled.
Closes #19152.

Drop I2P support with libtorrent 1.2

---

src/gui/torrentcreatordialog.cpp

If the last level of the added path is a symlink, the user probably expects it to appear in the torrent under the symlink name, not under the resolved one.

Disable symlink resolving in Torrent creator

---

src/gui/fspathedit.cpp
src/gui/fspathedit.h
src/gui/fspathedit_p.cpp
src/gui/fspathedit_p.h
src/gui/torrentcreatordialog.cpp
src/gui/torrentcreatordialog.ui

* Visually validate input path in torrent creator dialog

Visually validate input path in torrent creator dialog

---

src/gui/torrentcontentwidget.cpp

When scrolling large torrent files (torrent with 100k files in one level) in the TorrentContentWidget, the application freezes.
This PR fixes this problem by specifying that the all TorrentContentWidget's items have the same height

Improve performance when scrolling large torrents

---

src/base/iconprovider.h
src/base/logger.h
src/base/net/downloadmanager.h
src/base/net/geoipmanager.h
src/base/preferences.cpp
src/base/preferences.h
src/base/rss/rss_session.h
src/base/search/searchpluginmanager.h
src/base/settingsstorage.cpp
src/webui/webui.cpp

* ~~Move default functions to header~~
* Don't update settings when it hasn't changed
So when a setting is the same as the default, it won't write an entry to config file on disk.
* Don't emit superfluous signal
`Preferences::apply()` might emit superfluous changed signal even when the settings hasn't changed (e.g. not dirty), this commit fixes it.
* Don't unnecessarily restart Web server
When related settings hasn't changed.
* Mark singleton class as final

Don't update settings when it hasn't changed

---

src/webui/api/appcontroller.cpp
src/webui/www/private/views/preferences.html

If the current network interface is down (eg: wg0) the endpoint used to construct the dropdown with available values for network interfaces will not return it.
For this reason the value "Any intercace" will be pre-selected, and by calling the Save (without the user change the network interfaces) it undesirable update the current network interface to "Any intercace".
This fix is to add the current interface to the dropdown when needed, this way the current network interface will be always present and selected.
--
This issue have been previous mentioned on the GUI app #17031 and #17058, but still present on WebUI.
I belive the fix for GUI was read the interface value from settings/Session and merge it when needed: [advancedsettings.cpp](https://github.com/qbittorrent/qBittorrent/pull/17031/f …

WebUI: Preserve the network interfaces when down

---

src/base/bittorrent/bencoderesumedatastorage.cpp
src/base/bittorrent/common.h
src/base/bittorrent/dbresumedatastorage.cpp
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/torrentinfo.cpp
src/base/preferences.cpp
src/base/preferences.h
src/gui/addnewtorrentdialog.cpp
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/webui/api/appcontroller.cpp
src/webui/webapplication.h
src/webui/www/private/views/preferences.html

* Expose 'max torrent file size' setting
* Expose 'bdecode limits' settings
This includes:
* Bdecode depth limit
* Bdecode token limit

Expose 'bdecode limits' settings

---

src/base/http/connection.cpp
src/base/http/requestparser.cpp
src/base/http/requestparser.h
src/base/http/responsegenerator.cpp

* Fix response for HTTP HEAD method
Closes #19288.
* Response proper error status for invalid request methods
* Avoid stuffing the log via junk requests

Fix response for HTTP HEAD method

---

.github/workflows/ci_macos.yaml

Related issue: https://github.com/Wandalen/wretry.action/issues/106
A workaround was suggested in https://github.com/Wandalen/wretry.action/issues/106#issuecomment-1631860467

GHA CI: fix environment variable not being used

---

src/gui/mainwindow.cpp

On versions before Windows 10 the user is running the Qt5 build.
The next qBittorrent release will change to Qt6 as the default build.
It is counterintuitive to tell the user about available updates when they are running an incompatible Windows version.

Disable update checks on versions before Windows 10

---

src/gui/powermanagement/powermanagement.h
src/gui/powermanagement/powermanagement_x11.cpp
src/gui/powermanagement/powermanagement_x11.h

* Change default power management to Gnome Session Manager
As seen on https://www.freedesktop.org/wiki/Specifications/power-management-spec/, the `org.freedesktop.PowerManagement` is obsolete.
* Clean up coding style
* Detect D-Bus interface
* Revise message

Change default power management to Gnome Session Manager

---

src/gui/mainwindow.cpp
src/gui/mainwindow.h
src/gui/powermanagement/powermanagement.cpp
src/gui/powermanagement/powermanagement.h
src/gui/powermanagement/powermanagement_x11.cpp

* Set power state to idle when deconstructing class
* Avoid excessive power management updates
* Fix indentation
* Fix incorrect state
Fix up f3f9cfe44ed49d5bf3de0e318fa9c8ec48645ca4.

Avoid excessive power management updates

---

src/base/algorithm.h
src/base/bittorrent/sessionimpl.cpp
src/base/http/server.cpp
src/base/orderedset.h
src/webui/api/synccontroller.cpp
test/testalgorithm.cpp

`Algorithm::removeIf()` is still valuable as `QHash::removeIf()` predicate require an iterator or a `std::pair`, which both require more code to unpack the parameter and therefore makes it unwieldy.

Use library provided `erase_if()`

---

src/lang/TRANSLATION_INSTRUCTIONS

The old one redirects to https://explore.transifex.com instead of the project.

Update Transifex link in TRANSLATION_INSTRUCTIONS

---

src/base/utils/misc.cpp
src/gui/properties/speedplotview.cpp

* Remove unused conditional
* Use qreal type whenever feasible
The idea is follow Qt and use `qreal` instead of `double` for generic code.

Remove unused conditional

---

src/base/bittorrent/torrentdescriptor.cpp

Fixes regression of #19301.
Ref.: https://github.com/qbittorrent/qBittorrent/pull/19301#discussion_r1280154593.

Don't use variable after it is moved

---

src/webui/www/private/scripts/prop-files.js
src/webui/www/private/views/log.html
src/webui/www/private/views/preferences.html

This pull request resolves an issue with Safari not properly selecting an `<option>`.  Unlike other browsers Safari does select an `<option>` when the `selected` attribute is set using `setAttribute()`. Using `setProperty()` solves this issue.
I have tested it by patching qBittorrent version 4.5.2. That means I have not tested the log view as it is not present in that version.
Tested with Safari version 16.4 on macOS. I have also verified that it is still working in Firefox 113.0.2.
Closes #17866.

WebUI: Use setProperty() for selecting an option

---

src/gui/properties/propertieswidget.ui

The property widget already has scroll bars and thus we don't need this span.
Closes #15000.

Remove column span

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
CMakeLists.txt
INSTALL

* GHA CI: install boost from upstream
* Bump boost requirement to 1.76
`std::hash` specialisations for `boost::asio` structures is required.
* GHA CI: remove redundant conditionals

Bump boost requirement to 1.76

---

src/base/rss/rss_session.cpp
src/base/rss/rss_session.h

Related to issue #19439
What it does:
1. Changed `loadFolder()`'s return type to `bool` to be able to return `updated` from inside recursive calls.
2. Made `loadFolder()` change `updated` based on changes in feeds **AND** subfolders. previously only based on changes in feeds.
3. `loadFolder()` returns `updated` instead of calling `store()` then after returning to `load()` it checks the returned value to find out whether to call `store()` or not.
4. Changed `loadLegacy()` to not call `store()` but call it after returning to `load()`. (for consistancy)
Points to note outside the bugfix:
1. `rss_session::loadLegacy()` and `rss_session::loadFolder()` no longer call `store()`
2. `rss_session::loadFolder()` now returns `bool` instead of `void`

Fix overwriting feeds.json with an incomplete load of it

---

src/app/application.cpp
src/app/main.cpp
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/torrentimpl.cpp

The idea is that in the case of a known unrecoverable error (in which we deliberately throw an unhandled exception to abort the program), not to show the stack trace, but some more useful message instead (if possible). This can help in fixing confusing issues like #19436, where it is difficult to figure out how to reproduce it.

Display error message when unrecoverable error occured

---

src/base/3rdparty/.clang-tidy

Disable clang-tidy for 3rd-party code

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_windows.yaml
.pre-commit-config.yaml

* GHA CI: Bump Windows/macOS Boost version to 1.83.0
(Left Linux at 1.76.0 as per https://github.com/qbittorrent/qBittorrent/pull/19428)
* GHA CI: Bump `typos` action revision to 1.16.4
(Bumped this along the way)

GHA CI: Bump Windows/macOS Boost version to 1.83.0

---

CODING_GUIDELINES.md
src/app/application.cpp
src/app/qtlocalpeer/qtlocalpeer.cpp
src/base/bittorrent/sessionimpl.cpp
src/base/utils/fs.cpp
src/base/utils/misc.cpp
src/base/utils/misc.h
src/base/utils/random.cpp
src/gui/mainwindow.cpp
src/gui/programupdater.cpp
src/gui/torrentcontentmodel.cpp
src/gui/utils.cpp

This was partially done in PR #4505, and this PR converts the rest of the headers.
Also removes a duplicate header include in `mainwindow.cpp`.

Convert Windows header names to lowercase

---

src/base/CMakeLists.txt
src/base/bittorrent/torrentcreator.cpp
src/base/bittorrent/torrentcreator.h
src/gui/torrentcreatordialog.cpp
src/gui/torrentcreatordialog.h

The change is in preparation for adding the possibility to create torrent files via the API.
Rework TorrentCreatorThread to be a more lightweight QRunnable class. The parameters are now defined on construction time and are fixed throughout the lifecycle of the TorrentCreator. The lifecycle of the object is not bound to the one of QDialog anymore; it is now handled by the QThreadPool. This will enable easier queueing of multiple torrent creation jobs without risk of spawning many threads.

Use QThreadPool for torrent creation

---

src/gui/transferlistwidget.cpp

Fix the problem caused by attempting to open the destination folder when torrent has no metadata.
Closes #18738.

Open "Save path" if torrent has no metadata

---

src/app/application.cpp
src/app/application.h
src/base/bittorrent/torrentcreator.cpp
src/base/bittorrent/torrentcreator.h

QAtomicInteger underlying is using std::atomic structures, so using std::atomic directly should not be a problem for us.

Use atomic primitives from standard library

---

src/gui/addnewtorrentdialog.cpp
src/gui/guiaddtorrentmanager.cpp

Closes #12849.
Closes #12852.
Closes #19072.

Don't set parent of "Add new torrent dialog" on macOS

---

src/gui/aboutdialog.cpp
src/gui/aboutdialog.h
src/gui/aboutdialog.ui

* Add button to copy library versions to clipboard
Closes #18702.
* Make the title label selectable
And therefore its text is copyable.

Add button to copy library versions to clipboard

---

src/webui/www/private/views/rssDownloader.html

Added a field with tags for RSS downloader rules.

"Add Tags" field for RSS rules in WebUI

---

src/base/http/requestparser.cpp
src/base/utils/net.cpp
src/base/utils/net.h

The codebase already prefers `std::pair` to `QPair` (~11 occurrences v.s. ~2).

Use `std::pair` instead of `QPair`

---

src/base/unicodestrings.h
src/base/utils/misc.cpp
src/gui/properties/speedplotview.cpp
src/gui/torrentcontentmodelitem.cpp

* Use Qt built-in non-breaking space variable
* Remove thin space
Generally qbt doesn't put a space before percentage symbol.
This change makes the UI elements consistent.

Use Qt built-in non-breaking space variable

---

.github/dependabot.yml
.github/workflows/ci_file_health.yaml
.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/ci_webui.yaml
.github/workflows/ci_windows.yaml
.github/workflows/coverity-scan.yaml
.pre-commit-config.yaml

* GHA CI: simplify vcpkg commands
* GHA CI: introduce dependabot updates 
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
* GHA CI: bump versions

GHA CI: introduce dependabot updates

---

src/gui/transferlistmodel.cpp
src/gui/transferlistmodel.h
src/gui/transferlistwidget.cpp
src/webui/api/serialize/serialize_torrent.cpp
src/webui/api/serialize/serialize_torrent.h
src/webui/webapplication.h
src/webui/www/private/scripts/dynamicTable.js

This PR adds new `Reannounce In` column into main transfer list. Same thing as in torrent info `General` tab.
The column is hidden by default.

Implement `Reannounce In` column

---

src/gui/addnewtorrentdialog.cpp

Improves "Metadata received" stop condition handling by "Add new torrent" dialog.
The problem is when "Metadata received" stop condition is set the metadata can still be received 0.1 sec before clicking the "OK" button so torrent is actually added with metadata and therefore it cannot respect "Metadata received" stop condition.
The solution is to uncheck "Start torrent" checkbox once metadata is received.
Closes #19583.

Prevent torrent from being started unexpectedly

---

src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/webui/api/appcontroller.cpp
src/webui/webapplication.h
src/webui/www/private/views/preferences.html

This allows user to select DHT bootstrap nodes. Or even use their own bootstrap nodes.

Expose 'DHT bootstrap nodes' setting

---

src/webui/www/private/scripts/dynamicTable.js

Closes #18737.
tested locally, working as expected

WebUI: fix missing error icon

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml

Those have minimal impact on run-time:
https://www.gnu.org/software/libc/manual/html_node/Source-Fortification.html
https://bugs.launchpad.net/kicad/+bug/1838448/comments/40

GHA CI: enable run-time checks in C++ library

---

src/gui/rss/rsswidget.cpp

When 'Unread' is selected in rss feed list, user may be confused about which site the current rss article from. So it would be better to show the rss feed title simultaneously.
RSS feed title will be displayed on top of the rss html browser when 'Unread' is selected in rss feeds list.
screenshot:

Show RSS feed title in HTML browser

---

.github/workflows/ci_macos.yaml
CMakeLists.txt
INSTALL

Addresses:
* [CVE-2022-0778](https://github.com/advisories/GHSA-x3mh-jvjw-3xwx)
* [OpenSSL 1.1.1 End of Life](https://www.openssl.org/blog/blog/2023/09/11/eol-111/)

Bump OpenSSL requirement to 3.0.2

---

src/base/preferences.cpp
src/base/preferences.h
src/base/utils/foreignapps.cpp
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/gui/mainwindow.cpp
src/gui/mainwindow.h
src/webui/api/appcontroller.cpp
src/webui/webapplication.h
src/webui/www/private/views/preferences.html

Allow users to specify Python executable path

---

src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/gui/mainwindow.cpp
src/gui/transferlistfilters/trackersfilterwidget.cpp
src/gui/transferlistfilters/trackersfilterwidget.h
src/gui/transferlistfilterswidget.cpp
src/gui/transferlistfilterswidget.h

Previously, it could leave the error/warning counters not updated if you deleted the corresponding trackers via "Edit Trackers..." dialog.

Improve handling the case when torrent enters/leaves trackerless state

---

src/gui/statusbar.cpp
src/gui/statusbar.h

`QStyle::standardPixmap()` is deprecated.

Migrate away from deprecated function

---

src/base/bittorrent/dbresumedatastorage.cpp

Prevents qBittorrent from being failed to start after torrents database metadata is corrupted by one of the first releases of v4.5.x series.
Closes #19622.

Double check whether database needs to be updated

---

src/gui/guiaddtorrentmanager.cpp

Allows you to bring the main window to the front when one or more "Add new torrent" dialogs are open.
Also allows you to minimize/maximize the "Add new torrent" dialog.
Closes #17919.

Improve GUI behavior when adding multiple torrents

---

src/base/bittorrent/torrentimpl.cpp
src/base/net/downloadhandlerimpl.cpp
src/base/utils/misc.cpp
src/base/utils/misc.h

In short, now Windows can identify newly downloaded files (from bittorrent) and possibly prevent novice users from executing dangerous file extensions.
https://redcanary.com/threat-detection-report/techniques/mark-of-the-web-bypass/
https://mikehadlow.blogspot.com/2011/07/detecting-and-changing-files-internet.html
https://textslashplain.com/2016/04/04/downloads-and-the-mark-of-the-web/
Closes #19648.

Add support for Mark-of-the-Web

---

.pre-commit-config.yaml
dist/windows/config.nsi

Updated:
* pre-commit-hooks -> 4.5.0
* codespell -> 2.2.6
* typos -> 1.16.18
Note:
fixed a typo from previous "test run"  of codespell 2.2.6 (L151) `dist\windows\config.nsi` - `unistaller` -> `uninstaller`

GHA CI: Update numerous pre-commit revisions and fixed typo

---

src/app/application.cpp
src/base/http/server.cpp
src/base/http/server.h
src/webui/webui.cpp
src/webui/webui.h

- Check if WebUI is enabled and print an appropriate message otherwise.
- Print an actual runtime server scheme, address and port.

Fix WebUI greeting for `qbittorrent-nox`

---

.pre-commit-config.yaml

The `repo` value will be used by `git clone` command and therefore the URL should end with `.git` for repos on Github.
https://pre-commit.com/#repos-repo

GHA CI: use proper git URL

---

.github/workflows/ci_windows.yaml
src/app/cmdoptions.cpp

Otherwise, there is a conflict of run-time libraries used (since Qt DLLs are still use dynamic MSVCRT) that leads to strange errors.
Closes #19701.

CI: Use dynamic MSVC run-time library

---

dist/windows/installer.nsh
dist/windows/uninstaller.nsh
src/app/application.cpp
src/base/preferences.cpp
src/base/preferences.h
src/base/utils/os.cpp
src/base/utils/os.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.h
src/gui/optionsdialog.ui

Allow to set qBittorrent as default program

---

src/webui/www/private/scripts/dynamicTable.js

The overlay scrollbars [introduced](https://www.mozilla.org/en-US/firefox/100.0/releasenotes/#note-789043) in Firefox 100 take up no space, breaking the existing overflow detection. This may result in a second, defunct vertical scrollbar inside the Transfer List Panel with a travel of only 1px.
Add an extra check for scrollHeight != clientHeight which is able to detect an overflow independent of scrollbar style ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight)).
Before:
After:

WebUI: Fix duplicate scrollbar on Transfer List

---

.github/workflows/ci_windows.yaml
cmake/Modules/CommonConfig.cmake
src/base/utils/misc.cpp
src/gui/mainwindow.cpp
src/gui/programupdater.cpp
src/qbittorrent.exe.manifest

* Migrate away from deprecated functions
* Drop unsupported keys
* Bump Windows macro versions
* GHA CI: don't override cmake default CXXFLAGS

Code clean ups

---

src/base/CMakeLists.txt
src/base/bittorrent/torrentimpl.cpp
src/base/net/downloadhandlerimpl.cpp
src/base/utils/misc.cpp
src/base/utils/misc.h

* Use proper fallback value for Mark-of-the-Web URL
References:
https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/components/services/quarantine/quarantine_win.cc#211
https://hg.mozilla.org/mozilla-central/file/bd568ad893882d37f094d43cba3f62c78982cd05/toolkit/components/downloads/DownloadIntegration.sys.mjs#l537
* Add support for quarantine on macOS
['Quarantine'](https://iboysoft.com/news/com-apple-quarantine.html) is macOS terminology for [mark-of-the-web](https://textslashplain.com/2016/04/04/downloads-and-the-mark-of-the-web/).
ps. I have tested it and verify that it works.
pps. I plan to provide ui options to enable/disable it in a later PR.

Add support for quarantine on macOS

---

src/app/application.cpp
src/app/application.h
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h

This has no effect on macOS.
https://stackoverflow.com/questions/3274385/how-to-limit-memory-of-a-os-x-program-ulimit-v-neither-m-are-working
Closes #18656.

Remove "Physical memory (RAM) usage limit" option on macOS

---

src/gui/desktopintegration.cpp

Workaround for https://bugreports.qt.io/browse/QTBUG-53550
Closes #19758

Fix invisible tray icon with Qt5 in Linux

---

src/icons/icons.qrc

Window icon isn't showing if "Use icons from system theme" setting is disabled.
This is how it looks in Lubuntu 22.04 / 23.10 for qBittorrent from sources/repo/AppImage:
~~The proposed patch uses "qbittorrent-tray" icon because there is no "qbittorrent" icon in the UI Theme.~~
Perhaps a better solution is possible.

Add missing Window icon

---

src/webui/www/private/upload.html

Mobile Safari on iOS does report `ios` platform, but iPadOS reports `mac` instead. It is common sense to check for touch points when this happens to differentiate Mac and iPad.
Closes #19057.

Fix .torrent file upload on iPadOS

---

src/webui/api/torrentscontroller.cpp
src/webui/api/torrentscontroller.h
src/webui/webapplication.h

Allow to request torrents count via WebAPI

---

src/gui/transferlistmodel.cpp
src/gui/transferlistmodel.h
src/webui/www/private/scripts/dynamicTable.js

Before this PR, "checking/moving" shared the same icon in `transferlist`.
____

Use appropriate icon for "moving" torrents in transfer list

---

src/base/bittorrent/common.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h

Revives the "Unwanted folder" feature that keep all the unchecked files in ".unwanted" subfolders.
Closes #13531.

Keep unwanted files in separate folder

---

cmake/Modules/CommonConfig.cmake
src/app/CMakeLists.txt

* Use highest compression algorithm & level 
https://doc.qt.io/qt-6/resources.html#compression
* Exclude identical strings
This gives slightly smaller final binary.
https://doc.qt.io/qt-6/linguist-lrelease.html#lrelease-options
>If the translated text is the same as the source text, exclude the message.

Improve settings for Qt resource compiler

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/ci_windows.yaml

Here is some benchmark for various archive formats:
```
gz
0m11.384s
0m11.495s
0m11.193s
zip
0m14.159s
0m14.416s
0m13.917s
7z
0m17.569s
0m17.295s
0m18.496s
bz2
0m31.519s
0m28.885s
0m29.510s
```
Looking by compressed size, bz2 is the best. However its decompressing speed is the slowest. bz2 and gz file size only differs by ~20MB and this difference is neglectable given the network speed on Github. So switch to gz format to speed up CI build time.

GHA CI: speed up boost installation

---

src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h
src/webui/api/serialize/serialize_torrent.cpp
src/webui/api/serialize/serialize_torrent.h
src/webui/webapplication.h
src/webui/www/private/index.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/mocha-init.js

- Didn't know which icon to use so i used the same as the one for "Copy" menu item.
- Not sure what to do about WeAPI version.
- In WebUI i suppose it would be desirable to clear the clipboard before the copy in case there is something else there and no selected torrent has a comment but i couldn't figure out how to do that.
Closes #18890.

Add copy comment functionality to the torrent list's context menu

---

src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.h
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h

Add option to enable previous Add new torrent dialog behavior

---

src/webui/www/private/rename_files.html

Removed an extra `)` for `QBT_TR`

WebUI: Remove extra ')' in QBT_TR macro

---

src/app/application.cpp
src/app/application.h
src/app/cmdoptions.cpp
src/app/cmdoptions.h
src/base/interfaces/iapplication.h
src/base/preferences.cpp
src/base/preferences.h
src/base/utils/password.cpp
src/base/utils/password.h
src/gui/ipsubnetwhitelistoptionsdialog.cpp
src/gui/mainwindow.cpp
src/gui/optionsdialog.cpp
src/gui/optionsdialog.h
src/gui/optionsdialog.ui
src/webui/api/appcontroller.cpp
src/webui/api/authcontroller.cpp
src/webui/api/authcontroller.h
src/webui/webapplication.cpp
src/webui/webapplication.h
src/webui/webui.cpp
src/webui/webui.h

This is how it is supposed to behave:
1. WebUI is still disabled by default for regular build and enabled for no-GUI one.
2. There are no default credentials for now (default username "admin" is still supported). no-GUI build uses temporary auto generated password until user sets custom one. Existing regular installations that had enabled WebUI with default credentials will fail to start WebUI until user sets custom password.
Note that credentials explicitly set to "admin:adminadmin" are considered as valid.

Drop WebUI default credentials

---

src/base/torrentfileswatcher.cpp
src/base/torrentfileswatcher.h

Fixes regression of #19650.
>QObject::~QObject: Timers cannot be stopped from another thread
Supercedes #19741.

Improve Torrent files watcher internals

---

cmake/Modules/CommonConfig.cmake

This suppresses compiler warnings in GHA CI:
>ld: warning: direct access in function 'std::__1::__function::__func<libtorrent::storage_interface* (*)(libtorrent::storage_params const&, libtorrent::file_pool&), std::__1::allocator<libtorrent::storage_interface* (*)(libtorrent::storage_params const&, libtorrent::file_pool&)>, libtorrent::storage_interface* (libtorrent::storage_params const&, libtorrent::file_pool&)>::target(std::type_info const&) const' from file '/usr/local/lib/libtorrent-rasterbar.a(create_torrent.cpp.o)' to global weak symbol 'typeinfo name for libtorrent::storage_interface* (*)(libtorrent::storage_params const&, libtorrent::file_pool&)' from file 'src/base/libqbt_base.a(mocs_compilation.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely …

Set symbol visibility to hidden

---

cmake/Modules/CommonConfig.cmake

This negatively affect stacktrace functionality.
This reverts commit 50680a3d9b2242b83e38094cefb6377dbfb4fd52.
Sorry about the noise.

Revert "Set symbol visibility to hidden"

---

src/base/net/downloadmanager.cpp

Otherwise, network requests may be in a pending state indefinitely if for some reason they cannot be executed (i.e. data cannot be transferred).

Add timeouts to network requests

---

src/base/CMakeLists.txt
src/base/bittorrent/categoryoptions.cpp
src/base/bittorrent/downloadpathoption.cpp
src/base/bittorrent/downloadpathoption.h
src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/gui/torrentcategorydialog.cpp

Now (finally) subcategories are supposed to follow the options of parent categories when constructing implicitly defined save paths, etc.
Previously category `Music/Rock` used `<DefaultSavePath>/Music/Rock` (e.g. `D:\Torrents\Music\Rock`) path unless another one was explicitly set in its options.
Now it will use `<ParentSavePath>/Rock`, i.e. if `Music` has redefined save path, e.g. `D:\Music`, then `Music/Rock` will use `D:\Music\Rock`.
Closes #19941.

Follow the parent category options

---

src/gui/mainwindow.cpp

The parent widget of lockMenu is going to be used to derive the transient parent window. Currently the parent widget of lockMenu is the main window, therefore the main window is also going to be the transient parent for lockMenu's window handle.
In other words, the "View" menu and "Lock qBittorrent" menu are going to be considered as siblings by the window manager even though the latter is nested inside the former.
On platforms like wayland, such popup hierarchies are illegal, popups must be properly nested. qtwayland works around it, but it also prints warning messages.
This change makes lockMenu a child of the view menu so they are properly nested from the window manager point of view.
Closes https://github.com/qbittorrent/qBittorrent/issues/19955.

Fix parent widget of "Lock qBittorrent" submenu

---

src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/prop-webseeds.js
src/webui/www/private/views/log.html
src/webui/www/private/views/preferences.html
src/webui/www/private/views/rss.html

Closes #19034.
The memory leak can be reproduced easily by opening two web pages of qbittorrent so that the WebUI pages are updated with `full_update = true`. If you have a large number of torrents, such as 100 torrents, you can observe a rapid increase in memory usage.
This is caused by the incorrect usage of `dispose` and `empty` methods in the js codes and none of them garbage collect the elements. If event listeners are added to the DOM elements, those DOM elements will not be garbage collected at all event if they are not referenced or out of the scope, which will cause memory leaks. If some elements are expected to be removed, the correct way is to use [`destroy`](https://github.com/mootools/mootools-core/blob/master/Docs/Element/Element.md#element-method-destroy-elementdestroy) …

Fix JS memory leak

---

src/app/main.cpp

The messages printed out via stdout is usually important and short so there is no reason to buffer them.
Closes #19984.

Disable stdout buffering for qbt-nox

---

src/gui/transferlistfilters/categoryfiltermodel.cpp
src/gui/transferlistfilters/categoryfiltermodel.h
src/gui/transferlistfilters/tagfiltermodel.cpp
src/gui/transferlistfilters/tagfiltermodel.h

Don't forget to update filter items

---

src/app/cmdoptions.cpp
src/base/utils/fs.cpp
src/base/utils/fs.h

Currently, if you try something like: `qbittorrent --profile=foo`, the program simply crashes because it requires an absolute path (`BitTorrent::BencodeResumeDataStorage::BencodeResumeDataStorage()` has this check: `Q_ASSERT(path.isAbsolute());`.
This PR makes the command line argument parser convert the given profile path to an absolute one.

Support relative profile paths

---

.github/workflows/ci_windows.yaml

lukka/run-vcpkg v11.3 has deliberately changed to avoid writing outside of `GITHUB_WORKSPACE` directory and this conflict with our usage. So ditch it and invoke vcpkg directly.
https://github.com/lukka/run-vcpkg/releases/tag/v11.3

GHA CI: ditch unusable build step

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/ci_windows.yaml
.github/workflows/coverity-scan.yaml

Boost main download site jfrog is unavailable at the time of writing.
Related: https://github.com/boostorg/boost/issues/842
BTW, happy new year everyone!

GHA CI: add fallback URL for boost library

---

src/app/main.cpp

Sometimes users had not properly configured their system locale and thus qbt will specify a default locale just in case.
Closes #16127.
Closes #19609.
Closes #19834.
ps. This PR is eligible to be backported to v4.6.x.

Specify a locale if none is set

---

src/base/CMakeLists.txt
src/base/utils/compare.h

According to https://doc.qt.io/qt-6/qcollator.html#posix-fallback-implementation
The 'POSIX fallback implementation' is only used when ICU is not available. So the correct way is to detect ICU directly and not depend on the OS. The exceptions are macOS and Windows since they support the required functionalities natively.
Closes #20205.
ps. I can reproduce the issue and confirm the fix.
pps. this is eligible to be backported to v4.6.x

Revise conditional for when to use QCollator

---

src/base/bittorrent/sessionimpl.cpp

Show correctly decoded filename in log

---

src/base/utils/compare.cpp
src/base/utils/compare.h
test/testutilscompare.cpp

1. Use proper case folding function instead of `toLower()`.
2. Use locale aware comparison instead of comparing unicode code points.
Now `a` comes before `A` which is the same as the result from QCollator. A nice side effect
is now it properly compares locale specific characters (for example `C`, `Č`).
3. Improve testing. Now the test is runnable and stable on all platforms.
ps. IMO not eligible for backporting.

Improve natural sort algorithm

---

src/base/CMakeLists.txt
src/base/utils/datetime.cpp
src/base/utils/datetime.h
src/webui/api/serialize/serialize_torrent.cpp
src/webui/api/torrentscontroller.cpp
src/webui/www/private/scripts/prop-general.js
test/CMakeLists.txt
test/testutilsdatetime.cpp

* Fix wrong time stamp values in WebAPI
The wrong values are observed when encountered an invalid QDateTime data.
* Leave the fields empty when value is invalid
This follows GUI behavior.
* Use initialization form for variable
* Provide safe helper for converting to 'seconds since epoch'
ps. I intend to use 'rebase and merge' strategy.

Fix wrong time stamp values in WebAPI

---

src/base/bittorrent/sessionimpl.cpp
src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.ui
src/gui/optionsdialog.cpp

Torrent  that is being added with metadata is considered to be added as stopped if "metadata received" stop condition is set for it.
Closes #20122.

Change "metadata received" stop condition behavior

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h

The code is restructured to more closely track the number of outstanding resume data requests. Otherwise, it could, under certain conditions, lead to unnecessary waiting at shutdown and adding an error message to the log.

Revamp handling of getting resume data from libtorrent

---

src/webui/www/private/views/preferences.html

Fix a typo caused by merged PR #19801 
The typo causes the Web UI options window to break.
[Link to code-review](https://github.com/qbittorrent/qBittorrent/pull/19801#pullrequestreview-1834730250)

Fix typo in preferences.html

---

src/webui/api/apicontroller.cpp
src/webui/api/apicontroller.h
src/webui/api/torrentscontroller.cpp
src/webui/webapplication.cpp

Some WebAPI endpoints produce a result that is essentially data in some format (e.g. `torrents/export` actually produces `.torrent` file data). Now they can specify the MIME type of this data and the suggested filename.

Allow WebAPI to specify filename and mime type for result data

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/ci_windows.yaml
.github/workflows/coverity-scan.yaml

* Bump macOS/windows Boost version to 1.84.0 (Linux was left at min_supported=1.76.0)
* Revised Boost install method across all CI

GHA CI: Bump boost dependency and revise install method

---

src/webui/www/.eslintrc.json
src/webui/www/private/confirmdeletion.html
src/webui/www/private/download.html
src/webui/www/private/downloadlimit.html
src/webui/www/private/index.html
src/webui/www/private/scripts/cache.js
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/download.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/scripts/prop-general.js
src/webui/www/private/upload.html
src/webui/www/private/uploadlimit.html
src/webui/www/private/views/about.html
src/webui/www/private/views/preferences.html
src/webui/www/private/views/rss.html
src/webui/www/private/views/rssDownloader.html
src/webui/www/public/index.html
src/webui/www/webui.qrc

* Cache program preferences
So that qbt can just use the data from memory which is vastly faster than waiting for a response over the net.
* Migrate to Cache for commonly used data
Previously it was abusing the `localStorage` and now it is storing data in memory (per session).
* Simplify code
* Add support for dark theme
* Combine script tags
* Defer loading of js code on landing pages
So that DOM tree can be processed earlier.
* Stop sync requests after qbt has been shutdown
This is the last batch for now.

WebUI Improvements

---

cmake/Modules/CommonConfig.cmake

From https://learn.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=msvc-170:
>Specify standards conformance mode to the compiler. Use this option to help you identify and fix conformance issues in your code, to make it both more correct and more portable.

Specify standards conformance mode to MSVC

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/ci_windows.yaml
.github/workflows/coverity-scan.yaml

* Libtorrent 2.0.10 released
https://github.com/arvidn/libtorrent/releases/tag/v2.0.10

GHA CI: Bump libtorrent 2 version to 2.0.10

---

src/base/CMakeLists.txt
src/base/bittorrent/addtorrentparams.cpp
src/base/bittorrent/addtorrentparams.h
src/base/bittorrent/bencoderesumedatastorage.cpp
src/base/bittorrent/dbresumedatastorage.cpp
src/base/bittorrent/loadtorrentparams.h
src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/bittorrent/sslparameters.cpp
src/base/bittorrent/sslparameters.h
src/base/bittorrent/torrent.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h
src/base/http/server.cpp
src/base/utils/net.cpp
src/base/utils/sslkey.cpp
src/base/utils/sslkey.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.h
src/gui/optionsdialog.ui
src/webui/api/appcontroller.cpp
src/webui/api/torrentscontroller.cpp
src/webui/api/torrentscontroller.h
src/webui/webapplication.h
src/webui/www/private/views/preferences.html

This is a revise of PR #19542.
The 'SSL torrent' feature is not standardized. I.e. there are no BEP (BitTorrent Enhancement Proposals) associated with it, so we do not greatly encourage its usage as it will only work with libtorrent clients and derivatives. It will not work with other torrent clients that do not support the libtorrent specific implementation.
This PR aims to provide minimal support for those who need SSL torrents. Furthermore, it is intended that there will be no UI support (nor indication) of adding/creating SSL torrents.
* Prerequisites:
I omit the instructions of creating those files as the intended audience (experts & advanced users) should have no problem with it. All files are as follow:
1. Root (torrent publisher) certificate
2. Root private key
3. A .torrent file …

Add support for SSL torrents

---

src/app/application.cpp
src/app/application.h
src/base/interfaces/iapplication.h
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/gui/mainwindow.cpp
src/gui/mainwindow.h
src/webui/api/appcontroller.cpp
src/webui/webapplication.h
src/webui/www/private/css/style.css
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/views/preferences.html

This is to allow users to differentiate qbt instances when there are multiple running.
Closes #17905.
Screenshot:
The custom suffix is set to `myInstance`

Allow to set custom suffix to window title

---

src/webui/www/public/scripts/login.js

Fixes reload bug in login.js for webgui on librewolf by adding
`location.assign(location);` before `location.reload(true);`.
left the latter for when `location.assign(location);` fails.
Closes #20441.

Improve WebUI login behavior

---

.github/workflows/ci_windows.yaml

OpenSSL isn't compatible with `/guard:cf` flag so we omit it for now. Related: https://github.com/openssl/openssl/issues/22554
Closes #20479.

GHA CI: disable security hardening flag

---

.gitignore

Continuation of PR #20492, which was closed because I accidentally deleted the branch.
I have been using vscode for development for the past months. It saves its configuration (per project) in a `.vscode` subfolder in the root of the project. Currently my settings hold the necessary configuration environment for cmake to find my custom built packages.
It doesn't make much sense to share those.
I put it in the ignore list so I can finally have a clean `git status`.

Update gitignore for vscode

---

src/gui/addtorrentparamswidget.cpp
src/gui/torrentoptionsdialog.cpp
src/gui/torrentoptionsdialog.h
src/gui/torrentoptionsdialog.ui
src/gui/torrentsharelimitswidget.cpp
src/gui/torrentsharelimitswidget.h

Now it handles share limits in a consistent manner with the underlying model.

Correctly handle share limits in torrent options dialog

---

src/gui/log/logfiltermodel.cpp
src/gui/transferlistsortmodel.cpp

We can use this function since the columns doesn't change.

Switch to lightweight function for filtering data

---

src/gui/desktopintegration.cpp

Closes #20367.
Adapted from #19814, removed Qt version check.

Fix invisible tray icon on Plasma 6 in Linux

---

src/gui/fspathedit_p.cpp
src/gui/fspathedit_p.h

This should save some resources and prevent unnecessary access to the file system.

Initialize completer for file system path widget on demand

---

src/gui/log/logmodel.cpp
src/gui/log/logmodel.h
src/gui/rss/articlelistwidget.cpp
src/gui/rss/articlelistwidget.h
src/gui/transferlistmodel.cpp
src/gui/transferlistmodel.h
src/gui/uithemecommon.h
src/gui/uithemedialog.cpp
src/gui/uithememanager.cpp
src/gui/uithememanager.h
src/gui/uithemesource.cpp

Some icons were also affected (those that are located in the same scope of the code with the custom colors).

Refresh custom colors once color scheme is changed

---

src/webui/www/private/scripts/client.js

This fixes a bug where the filters sidebar would always be displayed when switching back to the Transfers tab. Closes #19257.

WebUI: Conditionally show filters sidebar

---

src/app/application.cpp
src/gui/desktopintegration.cpp
src/gui/desktopintegration.h
src/gui/mainwindow.cpp
src/gui/mainwindow.h

Update system tray icon menu without re-create it.
Closes #20516.

Revamp system tray icon menu handling

---

dist/unix/CMakeLists.txt
dist/unix/org.qbittorrent.qBittorrent.metainfo.xml

Releasing v4.6.4 on Flathub was failing due to invalid AppStream metadata and this PR will fix it.
https://github.com/flathub/org.qbittorrent.qBittorrent/pull/148
This PR should be backported to v4.6.

Improve AppStream metadata

---

.pre-commit-config.yaml
src/webui/www/private/css/style.css
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/views/search.html

This PR adds support for running multiple concurrent searches in the Web UI. This is already supported in the GUI as well as by the Web API. Behavior mimics the GUI as closely as possible.
All filters and sorting are preserved per-tab, allowing you to apply unique filters and sorts to each of your searches. Row selection is also preserved across tab navigation.
Closes #12840.
I meant to add this capability shortly after adding search support in the Web UI (#9758), but it was delayed 5.5 years 😄

WebUI: Add support for running concurrent searches

---

src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/mocha-init.js

This PR fixes various accounting issues with the trackers list. Removing a torrent would not update the trackers list, nor would removing a tracker from a torrent. And removing a tracker with a shared host but unique url (e.g. example.com/1 and example.com/2) would erroneously remove the tracker's host from the list, despite trackers with that host still remaining.
Closes #20054, closes #20053.

WebUI: Improve accuracy of trackers list

---

src/base/CMakeLists.txt
src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/bittorrent/torrent.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h
src/base/bittorrent/torrentinfo.cpp
src/base/bittorrent/trackerentry.h
src/base/bittorrent/trackerentrystatus.cpp
src/base/bittorrent/trackerentrystatus.h
src/gui/mainwindow.cpp
src/gui/trackerlist/trackerlistmodel.cpp
src/gui/trackerlist/trackerlistmodel.h
src/gui/trackerlist/trackerlistwidget.cpp
src/gui/transferlistfilters/trackersfilterwidget.cpp
src/gui/transferlistfilters/trackersfilterwidget.h
src/gui/transferlistfilterswidget.cpp
src/gui/transferlistfilterswidget.h
src/gui/transferlistwidget.cpp
src/webui/api/serialize/serialize_torrent.cpp
src/webui/api/synccontroller.cpp
src/webui/api/torrentscontroller.cpp

The main motivation is that, in a future PR I would like to create a simple struct to pass/parse information from the GUI (without all the additional unused fields as it is now currently):
```c++
struct TrackerEntry
{
QString url {};
int tier = 0;
};  
```
The current `TrackerEntry` has a lot of fields and IMO it is more like providing some info instead of a simple 'entry'.

Revise Tracker related classes

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml

Also set a lower cache limit for macOS to prevent cache thrashing. Previously the default was 5G.
Will backport to v4.6.x.

GHA CI: only store cache for master branch

---

src/webui/www/private/scripts/dynamicTable.js

This prevents hitting a TypeError when the category stored in localstorage does not exist. The behavior for a nonexistent category now mirrors that of a nonexistent tag or filter - no option is selected and no torrents are shown.
Closes #20623.

WebUI: Fix error when category doesn't exist

---

src/base/bittorrent/torrent.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h
src/gui/properties/propertieswidget.cpp
src/gui/properties/propertieswidget.ui
src/gui/transferlistmodel.cpp
src/gui/transferlistmodel.h
src/gui/transferlistsortmodel.cpp
src/gui/transferlistwidget.cpp
src/webui/api/serialize/serialize_torrent.cpp
src/webui/api/serialize/serialize_torrent.h
src/webui/api/torrentscontroller.cpp
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/prop-general.js
src/webui/www/private/views/properties.html

Hello,
Thank you for this amazing torrent client! 🙇🏻‍♂️
I believe it would be nice to have a metric that shows how popular a torrent is.
It's especially helpful for clean up purposes if you want to delete the least popular torrents.
So I'd like to suggest an implementation of the `Popularity` metric.
_A new metric is inspired by the [Interest Rate](https://en.wikipedia.org/wiki/Interest_rate) from the finance world.
An implementation is adapted to the use-case and has nothing to do with money._
`Popularity` is an average number that represents how many times a torrent is seeded back on a monthly basis calculated as `all_time_upload / all_time_download / (activeTime() / MONTHS_SECONDS)`, translated to `realRatio() / activeMonths` for simplicity. The resulting values are reasonably small …

Add the Popularity metric

---

src/webui/www/public/scripts/login.js

Example for choosing French: http://127.0.0.1:8080/?lang=fr
There were a few reports that the user has messed up their browser's language and this PR gives an escape hatch in case the user is unable to configure the browser's language for various reasons.

WebUI: Allow to specify login page language via query parameter

---

src/gui/fspathedit_p.cpp
src/gui/fspathedit_p.h

Prevent inappropriate default completer from being used by path edit.
Closes #20663.

Fix Enter key behavior in Add new torrent dialog

---

src/webui/www/package.json

For unknown reasons, ESLint v9 doesn't work correctly. Migration to ESLint v9 will be done later when it is stable enough.
Will backport to v4.6.x.

GHA CI: lock to ESLint v8

---

src/webui/www/private/css/style.css
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/dynamicTable.js

This PR improves touch interaction with table rows that have a context menu. Previously, those rows couldn't be selected or scrolled on mobile. Additionally, this PR modifies the context menu to appear when the user removes their finger/touch, rather than the current behavior of appearing mid-touch. This allows us to only display the context menu if the user's finger remains on the same element, which should significantly reduce erroneous context menu triggering.
Closes #19819, closes #19820, closes #19823.

WebUI: Improve table scrolling and selection on mobile

---

src/webui/www/private/views/search.html

This PR restores searches previously performed in the same browser (via local storage).
~~I explored moving this logic server-side and adding a new API to allow for listing current searches. However, my extreme rustiness with C++, combined with `m_searchHandlers` being an instance variable, led me to abandon this approach. If someone can assist with converting `m_searchHandlers` into a `std::shared_ptr`, I'd be open to making the necessary changes.~~
Edit: discussed below

WebUI: Restore search tabs on load

---

dist/unix/org.qbittorrent.qBittorrent.metainfo.xml

Those URL are pointing to our git repo: https://github.com/qbittorrent/qBittorrent-website/tree/723c0df824392d888b4c2590ceca89ed347a5bd3/src/img/screenshots/linux
Will backport to v4.6.x.

Update screenshot URL in appstream metadata

---

src/webui/www/private/scripts/prop-trackers.js

WebUI: fix wrong peer number

---

CMakeLists.txt
INSTALL

* Libtorrent 2.0.10 released
https://github.com/arvidn/libtorrent/releases/tag/v2.0.10

Raise minimum libtorrent 2 version to 2.0.10

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_windows.yaml
.github/workflows/coverity-scan.yaml

Bumped Boost to 1.85.0 on Windows/macOS & coverity-scan, Linux remains at 1.76.0
[Boost 1.85.0 Release Notes](https://www.boost.org/users/history/version_1_85_0.html)

GHA CI: Bump Boost version to 1.85.0

---

src/base/CMakeLists.txt
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/utils/number.cpp
src/base/utils/number.h
src/gui/optionsdialog.ui
src/gui/trackersadditiondialog.cpp
src/webui/www/private/views/preferences.html
test/CMakeLists.txt
test/testutilsnumber.cpp

* On torrent add, tiers of additional trackers will be adjusted after the highest tier of the existing trackers.
* "Add trackers" button will adjust tiers of all newly added trackers after existing trackers.
Closes #20102.

Adjust tracker tier when adding additional trackers

---

src/webui/www/.eslintrc.json
src/webui/www/private/downloadlimit.html
src/webui/www/private/newtag.html
src/webui/www/private/rename_files.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/download.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/scripts/piecesbar.js
src/webui/www/private/scripts/progressbar.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/prop-peers.js
src/webui/www/private/scripts/prop-trackers.js
src/webui/www/private/scripts/prop-webseeds.js
src/webui/www/private/scripts/rename-files.js
src/webui/www/private/scripts/speedslider.js
src/webui/www/private/shareratio.html
src/webui/www/private/uploadlimit.html
src/webui/www/private/views/preferences.html
src/webui/www/private/views/search.html

* WebUI: clean up code
Use proper function for finding match.
Use strict comparison operators.
* WebUI: enforce strict comparison operators
* WebUI: migrate away from MooTools deprecated functions
https://mootools.net/core/docs/1.6.0/Core/Core#Deprecated-Functions
I intend to use 'create a merge commit' for merging.

WebUI: clean up code

---

src/base/search/searchhandler.cpp
src/base/search/searchhandler.h
src/gui/search/searchjobwidget.cpp
src/gui/search/searchsortmodel.h
src/searchengine/nova3/novaprinter.py
src/webui/api/searchcontroller.cpp
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/views/search.html

This PR adds a date column to the built-in search engine to show when a torrent was published/uploaded on the torrent site.
When a plugin wants to show a date, it can now add a `date` entry to its result dict. The value format is a unix timestamp (an integer representing seconds since epoch).
This commit adds the date column to both the Qt UI and the WebUI and updates the nova3 prettyPrinter.
Plugins with no date support will keep working.
If this PR is accepted, I will send a PR to the plugins repo to update as many plugins as I can! Here's the updated thepiratebay for testing the PR: https://github.com/ducalex/qbittorrent-search-plugins/blob/ducalex/add-date-field-tpb/nova3/engines/piratebay.py
Related open issues: #1463
Still to do are translations (a single additional string "Date"), …

Add date column to the built-in search engine

---

src/webui/api/serialize/serialize_torrent.cpp
src/webui/api/serialize/serialize_torrent.h

Currently, the "isPrivate" flag is only present on the "properties"-API:
/api/v2/torrents/properties
With this PR, I'd like to add it to the "info" -API:
/api/v2/torrents/info
Advantage:  This way it can be retrieved for all torrents in one go (rather than having to query the properties-API for each hash 1 by 1)
Disclaimer: I tried to the best of my abilities to read the code and amend it (which I believe is a super simple change).
I was not able (due to my lack of skill) to build qBit with my change and test it. 
Thank you very much for your review.

WebAPI: Provide "isPrivate" flag via "torrents/info" endpoint

---

src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h
src/base/preferences.cpp
src/base/preferences.h
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/gui/mainwindow.cpp
src/gui/mainwindow.h
src/gui/mainwindow.ui
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h

* Replaces current unsafe `Start all` and `Stop all` actions with `Pause session` and `Resume session` (paused session preserves started/stopped states of torrents when resumed).
* Adds an option to start session in paused state.
Closes #18993.

Add ability to pause/resume entire session

---

src/webui/www/.eslintrc.json
src/webui/www/package.json

https://eslint.style/guide/migration

WebUI: migrate ESLint rules

---

src/base/bittorrent/peerinfo.cpp

Clients can send arbitrary UTF-8 strings as their client identificators. qBittorrent displays that strings as is, which could lead to unexpected results and affect GUI layout in case of junk or intentionally malicious strings.
This PR introduces basic sanitization for client strings.
* Source string is [simplified](https://doc.qt.io/qt-6/qstring.html#simplified).
* Rest non-printable characters are removed.
Fixes #20010

Sanitize peer client names

---

src/base/search/searchdownloadhandler.cpp
src/base/search/searchdownloadhandler.h
src/base/search/searchhandler.cpp
src/base/search/searchhandler.h
src/base/search/searchpluginmanager.cpp
src/base/search/searchpluginmanager.h
src/gui/search/searchjobwidget.cpp
src/gui/search/searchsortmodel.h
src/searchengine/nova3/nova2dl.py
src/webui/api/searchcontroller.cpp
src/webui/api/searchcontroller.h

* Use search engine name instead of site URL (like nova2 does).
* Load only requested search engine.
* WebAPI: Add a way to download .torrent file using search plugin. This can help with solving https://github.com/qbittorrent/qBittorrent/issues/18334.

WebAPI: Add a way to download .torrent file using search plugin

---

src/gui/mainwindow.cpp

Don't hide member variables when storing current speeds

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h

Process libtorrent alerts in the order they are received.

Revamp alerts handling

---

src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.h
src/gui/addnewtorrentdialog.ui
src/gui/guiaddtorrentmanager.cpp

Code restructuring that separates the basic logic from the logic that depends on the parameters and properties of the torrent being added.

Improve structure of AddNewTorrentDialog code

---

src/webui/webapplication.cpp

* Use simpler conversion
The cookie value can only contain ASCII characters.
* Use Qt built-in methods

Simplify HTTP cookie code

---

.gitignore
src/searchengine/nova3/helpers.py

Some sites use headers to determine if it's a bot performing the search or it's an actual user, by adding it to the `retrieve_url` function, plugin developers can now pass any custom headers

Add optional headers to search request

---

src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/bittorrent/torrentimpl.cpp
src/gui/addnewtorrentdialog.cpp

Apply filename filter to subfolder names as well

---

src/gui/trackerlist/trackerlistmodel.cpp

* Capitalize header text
* Revise Protocol column
Add "BT" (BitTorrent) to avoid confusion about which protocol it is referring to.
Also its value doesn't need to be translated since it is used as-is in the spec (BEP52).
screenshot:

Revise Protocol column

---

src/base/bittorrent/bencoderesumedatastorage.cpp
src/base/http/connection.cpp
src/base/http/connection.h
src/base/http/server.cpp
src/gui/transferlistfilterswidget.cpp

1. Previously unhandled connections will stay in pending state. It won't be closed until timeout happened. This may lead to wasting system resources. Now the (over-limit) connection is actively rejected.
2. When out-of-memory occurs here, reject the new connection instead of throwing exception and crash.
3. Also clean up some unused bits.

Improve connection handling

---

src/searchengine/nova3/novaprinter.py

The canonical type for `size_string` is `str`. However numeric types are also accepted in order to accommodate poorly written plugins.

Allow numeric types

---

src/base/bittorrent/sessionimpl.cpp

Previously `m_shutdownTimeout * 1000` was calculated in `int` and now it is `qint64`.

Use proper casting

---

src/webui/www/private/scripts/search.js

This switches the WebUI's default search plugin from "All plugins" to "Only enabled". "All plugins" is a nonsensical default since it completely ignores whether plugins are enabled. This now matches the behavior of the GUI.
Closes #20558

WebUI: Use enabled search plugins by default

---

.github/workflows/ci_ubuntu.yaml

It does not affect the produced artifacts. The only difference is the tool itself won't depend on some specific OS image or library version.

GHA CI: use static versions of AppImage builder

---

src/base/bittorrent/customstorage.cpp
src/base/bittorrent/torrentimpl.cpp

Unlike libtorrent-2.0 disk IO is customizable on per-torrent basis in libtorrent-1.2, so it should be handled when reloading underlying torrent as well.

Use custom storage when reloading torrent

---

src/webui/www/private/scripts/client.js

`selected_tab` is already used for tracking the selected torrent properties tab. The affected feature hasn't yet been shipped in a release.

WebUI: Fix preference name conflict

---

src/base/CMakeLists.txt
src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/bittorrent/torrent.h
src/base/bittorrent/torrentcontentremoveoption.h
src/base/bittorrent/torrentcontentremover.cpp
src/base/bittorrent/torrentcontentremover.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h
src/base/preferences.cpp
src/base/preferences.h
src/base/utils/fs.cpp
src/base/utils/fs.h
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/gui/deletionconfirmationdialog.cpp
src/gui/deletionconfirmationdialog.ui
src/gui/transferlistwidget.cpp
src/webui/api/appcontroller.cpp
src/webui/api/torrentscontroller.cpp
src/webui/www/private/confirmdeletion.html
src/webui/www/private/views/preferences.html

Allow to move content files to trash instead of deleting them

---

src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/views/preferences.html

This PR implements double-click behavior controls for the WebUI, similar to the desktop GUI.
Closes #20436.
But as I discussed in https://github.com/qbittorrent/qBittorrent/issues/20436#issuecomment-2192285880, despite the same names, this is not the same settings. Because existing options of the GUI are not applicable for the WebUI, they are implemented as independent standalone settings.
Also the settings implemented as selectors, despite having only 2 options. They actually could be implemented as check boxes instead, but:
1. I think it is better to be kinda consistent with the GUI.
2. Allows for more options to be easily added in the future.
<details>
<summary>Screenshot</summary>
</details>

Implement double-click behavior controls for the WebUI

---

src/gui/properties/propertieswidget.cpp
src/gui/properties/propertieswidget.ui
src/gui/transferlistmodel.cpp
src/gui/transferlistmodel.h
src/gui/transferlistsortmodel.cpp
src/gui/transferlistwidget.cpp
src/webui/api/serialize/serialize_torrent.cpp
src/webui/api/serialize/serialize_torrent.h
src/webui/api/torrentscontroller.cpp
src/webui/webapplication.h
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/prop-general.js
src/webui/www/private/views/properties.html

Adds private flag to GUI that is available in /info and /properties response
+ WebUI & GUI: +"Private" column in torrent list (hidden by default)
+ WebUI & GUI: +"Private" flag in properties of selected torrent ("Information" section)

Add ability to display torrent "privateness" in UI

---

src/webui/www/private/views/rssDownloader.html

WebUI: Correctly apply changed "save path" of RSS rules

---

src/webui/api/serialize/serialize_torrent.cpp
src/webui/api/serialize/serialize_torrent.h

Adds `root_path` to the `torrent/info` API endpoint for each transfer.
Closes #21057.

WebAPI: Add root_path to torrent/info result

---

src/base/bittorrent/torrentdescriptor.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentinfo.cpp
src/base/bittorrent/torrentinfo.h
src/gui/addnewtorrentdialog.cpp

Just following the previously planned course of restructuring the object model.
In fact, it follows the changes supposed to be made to `libtorrent`, but it is slow in such things (for various reasons). However, nothing prevents us from getting ahead of `libtorrent` in such matters in order to avoid the spread of legacy approaches in our code.

Represent by TorrentInfo only info-section related metadata

---

src/base/search/searchpluginmanager.cpp
src/searchengine/nova3/helpers.py
src/searchengine/nova3/nova2.py
src/searchengine/nova3/novaprinter.py

Notable changes:
1. Prevent excessive engine module imports.
2. Replace trivial usage of `join()`.
3. Keep the output text sorted whenever possible.
4. Close handles properly.
5. Print error to stderr, not stdout.
6. Report search job exit code.
7. Print exception message to stderr if exception was thrown when running a search job.
8. Utilize XML library to build XML data And use 2 spaces as indentation.

Clean up search engine

---

src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/piecesbar.js
src/webui/www/private/scripts/progressbar.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/prop-general.js
src/webui/www/private/scripts/prop-peers.js
src/webui/www/private/scripts/prop-trackers.js
src/webui/www/private/scripts/prop-webseeds.js
src/webui/www/private/scripts/search.js
src/webui/www/private/views/rss.html

* WebUI: avoid queuing up requests
`setInterval()` will always fire a new timeout regardless previous `updateRssFeedList()` has completed or not. This patch will now wait for previous request to complete before another timeout.
* WebUI: avoid excessive checking
* WebUI: listen to resize events properly 
The workaround is not needed now.
Also added a debouncer to avoid too many transient resizing events.
* WebUI: clear timer variable properly
In JS the timer handle pool is reused and therefore require careful handling of it.

WebUI: timer related clean ups

---

src/webui/www/private/scripts/dynamicTable.js

Remove the torrent row regardless of it being visible.
I've also removed the return value because:
- it doesn't appear to be used by any caller;
- other functions (e.g. `updateRowData`) do not return any value;
- it's not clear whether `true` refers to the torrent being removed from the list of all torrents or just the visible ones.
Closes #21070.

WebUI: remove deleted torrents even if they are currently filtered out

---

src/webui/www/private/css/dynamicTable.css
src/webui/www/private/rename_files.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/prop-peers.js
src/webui/www/private/scripts/prop-trackers.js
src/webui/www/private/scripts/search.js
src/webui/www/private/views/log.html
src/webui/www/private/views/preferences.html
src/webui/www/private/views/rss.html
src/webui/www/private/views/searchplugins.html

This PR introduces ability to control alt row coloring in tables.
It is no longer necessary to handle files table in any special way - [n-th child selector with modern \[of \<selector\>\] syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child#the_of_selector_syntax) covers all cases. Currently web seed table is not handled at all but everything will sort itself out after #21055 is merged.
Included tiny fix to achieve better visibility of unread rss articles. It was hard to make out their titles with alt coloring off and dark theme on.
---
I read that using MooTools is discouraged so I decided to use vanilla JS as much as possible (even for element lookups) - is this ok now and going forward?

WebUI: Add ability to toggle alternating row colors in tables

---

src/gui/optionsdialog.ui
src/gui/speedlimitdialog.ui
src/gui/torrentoptionsdialog.ui

I created the same functionality here many years ago, it received some positive feedback but was ultimately closed: https://github.com/qbittorrent/qBittorrent/pull/4943
Since then, I went ahead and created this feature within Qt itself, see documentation here: https://doc.qt.io/qt-6/qspinbox.html#setStepType
Now that this functionality exists in a more straightforward way, maybe it can be useful for us here?

Enable adaptive step size for upload and download limits

---

src/base/bittorrent/torrentimpl.cpp

Fix Incomplete Save Path cannot be changed for torrents without metadata

---

src/webui/www/private/scripts/client.js
src/webui/www/private/views/preferences.html

This PR implements 'Auto hide zero status filters' option in WebUI.
---
In GUI, filters are not cleaned up after deleting all torrents:
Just add a couple of torrents in paused state then delete them all to reproduce.
When you reopen the client only 'All' remains, so it looks like a bug (checked both 4.6.5 and master).
In WebUI, 'All' is the only filter shown in all cases.

WebUI: Implement 'Auto hide zero status filters'

---

src/webui/www/private/scripts/client.js

Like other similar data structures, trackerList also need to be cleared in the event of a full sync update.

WebUI: Clear trackerList on full update

---

src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/prop-general.js
src/webui/www/private/scripts/prop-webseeds.js
src/webui/www/private/scripts/search.js

`innerHTML` &  `outerHTML` setter will more or less evaluate the value which could be used to inject malicious code. So replace them with safer alternatives.

WebUI: migrate away from inline HTML code

---

src/webui/www/private/css/style.css
src/webui/www/private/index.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/dynamicTable.js

This PR adds ability to filter torrent list by save path. Everything should work exactly like in GUI.
Closes #19393.

WebUI: Allow to filter torrent list by save path

---

src/webui/webapplication.cpp

qbt only need to escape double quotes for the sake of HTML attributes. As for single quotes it can leave them as-is since WebUI enforce using double quotes for strings.
Related discussion #21130.

Revise quote escaping for translated strings in WebUI

---

src/webui/www/private/scripts/client.js

This PR ensures that generic filter items are created in all circumstances.
---
There is at least a couple of ways to reproduce it, here's one:
1) Delete all torrents and custom categories / tags (if any present) from the desktop client
2) Turn on "Use subcategories" option
3) Open fresh WebUI:
4) Here's how tracker filter list looks after adding one trackerless torrent:

WebUI: Always create generic filter items

---

src/searchengine/nova3/helpers.py

This allows passing post_data to retrieve_url in order to create a post request.
This is required for me to fix eztv search plugin.

Search helpers: Add POST support to `retrieve_url`

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_windows.yaml
.github/workflows/coverity-scan.yaml

* Bump (macOS/windows/coverity-scan) Boost version to 1.86.0 (Linux was left at min_supported=1.76.0)

GHA CI: Bump Boost dependency

---

src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/misc.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/scripts/search.js
src/webui/www/private/views/rss.html
src/webui/www/private/views/searchplugins.html

* WebUI: prevent passing wrong parameter
The `event` object will be passed as the first parameter to the event handler. So wrap the event handler with a closure to prevent `event` leaking to other functions.
* WebUI: remove redundant events
The base class already handle them.
Also optimize the base implementation a bit.
* WebUI: implement debounce behavior for resize events
* WebUI: use passive event hanlders
These kind of event handlers can be asynchronously dispatched, freeing up the main thread for lag-free operation.

WebUI: improve event handlers

---

src/gui/search/searchjobwidget.cpp
src/gui/search/searchjobwidget.h

* Improve color of visited search result items
* Refresh search results colors once color scheme is changed
Closes #21187.

Refresh search results colors once color scheme is changed

---

src/webui/www/private/css/style.css
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/prop-general.js
src/webui/www/private/scripts/prop-peers.js
src/webui/www/private/scripts/prop-trackers.js
src/webui/www/private/scripts/prop-webseeds.js
src/webui/www/private/views/properties.html
src/webui/www/private/views/propertiesToolbar.html

This PR improves properties panel.
---
It is now possible to expand & collapse it by clicking directly on tabs, just like in GUI.
In addition, collapse state is saved and applied on page load.
Fixed one minor bug and now files search input is properly hidden even when panel is collapsed, before it was like this:

WebUI: Improve properties panel

---

src/base/utils/net.cpp
src/base/utils/net.h
src/webui/webapplication.cpp

It is not needed since `QHostAddress::isLoopback()` can do the job.

Remove 'loopback address detection' helper function

---

src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/misc.js
src/webui/www/private/views/preferences.html

It is now possible to display only hostname in the Tracker column. 
Closes #11357.

WebUI: Allow to display only hostname in the Tracker column

---

src/gui/properties/piecesbar.cpp
src/gui/properties/piecesbar.h

Much better contrast with download piece and selected pieces. Previously same color was used for both
New Behaviour
https://github.com/qbittorrent/qBittorrent/assets/34717789/b3d80dbb-47aa-4e03-b1e6-22f31b2e7982
https://github.com/qbittorrent/qBittorrent/assets/34717789/58f08ea1-eb86-4487-9f5d-d21363547d7f

Fix highlighted piece color

---

src/webui/www/private/css/dynamicTable.css
src/webui/www/private/scripts/dynamicTable.js

WebUI: Show country/region name next to its flag when 'Resolve peer countries' is enabled

---

src/base/bittorrent/sessionimpl.cpp
src/base/net/smtp.h

Fixes the problem described in https://github.com/qbittorrent/qBittorrent/issues/20342#issuecomment-2313118433.

Apply "merge trackers" logic regardless of way the torrent is added

---

src/base/http/types.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/webui/webapplication.cpp
src/webui/webapplication.h
src/webui/www/private/views/preferences.html

The localhost is 'potentially trustworthy' and RFC 6265 allows setting secure flag in this case.
Also check `X-Forwarded-Proto` header value to support reverse proxy usage.
Note: for reverse proxy users, now the `X-Forwarded-Proto` header is expected to be sent to qbt
otherwise the `secure` flag might be set erroneously.
https://datatracker.ietf.org/doc/html/rfc6265#section-4.1.2.5
https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy

Revise cookie 'secure flag' enable condition

---

src/qbittorrent.exe.manifest

SegmentHeap provides a faster malloc implementation that only available with Dynamic UCRT in Windows 10, version 2004 (build 19041) and later

Opt into Windows SegmentHeap

---

src/webui/www/private/css/style.css
src/webui/www/private/newcategory.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/views/filters.html

This PR improves subcategories.
---
Now they should fully match GUI behavior, please let me know if I missed something.
Still plenty of room to improve them further (e.g styling/CSS) but for now I wanted to keep the changes to the minimum.
Also included small tweaks to category context menu actions

WebUI: Improve subcategories

---

src/gui/optionsdialog.ui
src/webui/www/private/views/preferences.html

The link is helpful for users whom needs to setup reverse proxy.

Add URL link for reverse proxy setup examples

---

src/webui/api/appcontroller.cpp
src/webui/www/private/css/Window.css
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/views/preferences.html

- Added 'Confirm when deleting torrents' option to the WebUI
- Confirm deletion dialog now uses MUI.Modal
Closes #18345.
---
Everything should work like in GUI, so:
Confirm OFF:
1) When deleting selected torrents:
DEL / context menu: torrents deleted, files untouched
Shift + DEL: both deleted
2) When deleting by Category/Tag/Tracker:
Torrents deleted, files untouched
Confirm ON:
Should work like before, no changes there.

WebUI: Improve torrent deletion

---

src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/webui/api/appcontroller.cpp
src/webui/www/private/views/preferences.html

This change extends the Advanced section of the Preferences menu with a new field, allowing changing the time statistics save interval. A null value will prevent recurrent saving.
This aims to provide the feature requested in issue #21285 
Tested updating the value from the web UI and reading it from the local client and the other way around. Did **not test** the actual file update time, as I did not touch the mechanism below the `saveStatistics` function.
I did not extend the lang/translation files as I wasn't sure I was supposed to. This is my first contribution to qBittorent, so I'm not familiar with the WoW
closes #21285

Enable customizing the save statistics time interval

---

src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/mocha-init.js

Mootools is not maintained and [Hash itself was deprecated](https://mootools.net/core/docs/1.5.2/Types/Object#Deprecated-Functions
) over 10 years ago so I wanted to experiment a bit and switched torrents table to use vanilla Map instead. What do you think? Could be done one table at a time.. Or maybe it should be done differently (approach)?
Pretty much all tables could be pretty easily switched to Map with just some minor changes. Only RSS Feed & Article tables would require more work IIRC.

WebUI: Use Map instead of Mootools Hash in Torrents table

---

src/webui/www/private/css/style.css
src/webui/www/private/index.html
src/webui/www/private/scripts/contextmenu.js

This PR provides better feedback for hash context menu actions and now it is clearly shown if there is anything to copy.

WebUI: Improve hash copy actions in context menu

---

src/webui/www/private/scripts/client.js

GUI completely hides DHT information when DHT is disabled - now WebUI does the same thing.
I think this could close https://github.com/qbittorrent/qBittorrent/issues/18417

WebUI: Display DHT information in the Status bar only when DHT is enabled

---

src/webui/api/appcontroller.cpp
src/webui/www/private/css/style.css
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/views/confirmRecheck.html
src/webui/www/private/views/confirmdeletion.html
src/webui/www/private/views/preferences.html
src/webui/www/webui.qrc

This PR adds setting & confirmation dialog for torrent recheck.
Closes https://github.com/qbittorrent/qBittorrent/issues/19557

WebUI: Add 'Confirm torrent recheck' option

---

src/gui/properties/propertieswidget.cpp
src/webui/www/private/addwebseeds.html
src/webui/www/private/editwebseed.html
src/webui/www/private/index.html
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/prop-webseeds.js
src/webui/www/private/views/properties.html
src/webui/www/webui.qrc

WebUI: Support managing web seeds

---

src/base/utils/misc.cpp
src/base/utils/misc.h
src/gui/mainwindow.cpp
src/gui/mainwindow.h
src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h

Now drop action is only allowed on transfer list, previously it was on main window.
Having drop action on the whole main window is not preferred because it could allow drop action on other unrelated widgets, such as execution log or RSS widget which is unexpected behavior.

Allow drop action only on transfer list

---

src/webui/webui.cpp
src/webui/webui.h

There is no reason for `WebUI` class to retain this information.

Reduce sensitive data instances

---

src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/search.js

This PR adds 'Engine' column to Search table.
I also fixed inconsistent naming and renamed 'Search engine' column to 'Engine URL'.

WebUI: Add 'Engine' column to Search table

---

src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/dynamicTable.js

Torrent hashes in tracker list are now kept in sets instead of arrays.

WebUI: Improve lookup performance when filtering by tracker

---

src/app/qtlocalpeer/qtlockedfile.h
src/gui/macutilities.mm
test/testbittorrenttrackerentry.cpp

Migrated last remnants of `QVector` to `Qlist`, reference https://github.com/qbittorrent/qBittorrent/pull/21016#issuecomment-2212403741 onward.

Replace QVector with QList

---

src/base/net/smtp.cpp
src/base/rss/rss_parser.cpp
src/gui/advancedsettings.cpp
src/gui/rss/automatedrssdownloader.cpp

Migrate away from deprecated functions in Qt 6.9

---

src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/gui/advancedsettings.cpp
src/webui/www/private/views/preferences.html

I think everyone is aware of infamous LT20 memory-mapped files problems at this point. In case someone not up to the topic: arvidn/libtorrent#6667.
Despite it being on its way to a pread-disk-io implementation (arvidn/libtorrent#7013), I am sick of waiting and fighting with mmap problems.
Here is a simple way to fix it completely by cutting the problem roots:
LT20 currently falls back to pread io for small files (<640K). But that's actually a tunable [`mmap_file_size_cutoff`](https://www.libtorrent.org/reference-Settings.html#mmap_file_size_cutoff), never used by qBittorrent. So the fix is very straightforward, we simply increase that value.
This patch implements a new disk IO type, which forces all files to use the pread/pwrite fallback.
Well, technically files <32 TiB in size, as this …

Add "Simple pread/pwrite" disk IO type

---

src/webui/www/private/css/Window.css
src/webui/www/private/index.html
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/views/confirmAutoTMM.html
src/webui/www/webui.qrc

Just like in GUI, confirmation dialog shows up if it's possible to enable Auto TMM for any selected torrent. Right now it's not possible to properly test all cases in the WebUI because context menu completely hides TMM option when some torrents have it enabled and some not (no tri-state) - but that's something to add in another PR.

WebUI: add confirm dialog for Auto TMM

---

src/base/bittorrent/sessionimpl.cpp

router.utorrent.com has been dead for a long time. router.bittorrent.com died about a month or two ago. dht.aelitis.com doesn't work either. It is no longer possible to get DHT nodes from them.
Added router.silotis.us. Only ipv6!

Remove non-working DHT bootstrap nodes

---

src/base/utils/os.cpp

Trying to apply it to a nonexistent file is unacceptable, as it may unexpectedly create such a file.
Closes #21081.
Closes #21239.
Closes #21434.
Closes #21440.

Don't try to apply Mark-of-the-Web to nonexistent files

---

src/base/bittorrent/bencoderesumedatastorage.cpp
src/base/bittorrent/bencoderesumedatastorage.h
src/base/bittorrent/dbresumedatastorage.cpp
src/base/bittorrent/dbresumedatastorage.h
src/base/bittorrent/resumedatastorage.cpp
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/bittorrent/torrentcreationmanager.cpp
src/base/rss/rss_autodownloader.cpp
src/base/rss/rss_autodownloader.h
src/base/rss/rss_session.cpp
src/base/torrentfileswatcher.cpp
src/base/torrentfileswatcher.h
src/gui/properties/propertieswidget.cpp
src/gui/torrentcontentwidget.cpp
src/gui/torrentcreatordialog.cpp
src/gui/uithemedialog.cpp
src/gui/utils.cpp
src/webui/webapplication.cpp

This help identifying threads when debugging.
The name is using 'variable name + class/function name' due to the thread name field is limited to 16 chars on linux. Note that on Windows, the limit is 32767 chars.

Add name to threads

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/ci_windows.yaml

This turn on assertions from qbt codebase so that testers can verify the assertions really hold.

CI: turn on assertion checks

---

src/gui/torrentcreatordialog.cpp

Disabling will reduce the number of users experiencing this issue.
- https://github.com/qbittorrent/qBittorrent/issues/21011

Disable the ability to create torrents with a piece size of 256MiB

---

src/gui/optionsdialog.ui
src/gui/torrentcreatordialog.ui
src/gui/torrentoptionsdialog.ui
src/gui/torrentsharelimitswidget.ui

- `Torrent options`
- `Torrent creator`
- `Preferences`
In "torrent creator" the `tabChangesFocus` property is not set for the `textEdit` fields so tab is trapped in there AFAIK. Is there any reason not to set it?
~~The options dialog is a mess and i don't know how to fix it. e.g. in `Behavior` the second tabstop in the list of the .ui file is the language and yet it takes 15 tabs to get there.~~
Figured it out.
Closes #21387.

Fix the tab order in dialogs

---

src/webui/www/private/scripts/client.js

This removes duplicate stylesheet imports that caused the transfer list to be completely collapsed in Chrome-based browsers.
Closes https://github.com/qbittorrent/qBittorrent/issues/21426.

WebUI: Don't load Tabs & dynamicTable stylesheets in Properties panel

---

src/webui/www/private/scripts/search.js
src/webui/www/private/views/search.html

This PR adds context menu to Search tabs (same options as in GUI):

WebUI: Add context menu to search tabs

---

src/webui/www/private/css/style.css

Previously, text color of selected filter items was not applied correctly in all situations, making them difficult to read. This improves existing styles so that text is always correctly distinguished from the background.
This fixes issue from second post in https://github.com/qbittorrent/qBittorrent/issues/21426

WebUI: Use proper text color to highlight items in all filter lists

---

src/searchengine/nova3/helpers.py
src/searchengine/nova3/nova2.py
src/searchengine/nova3/novaprinter.py

Fixes "plugin not supported" errors with python 3.8.
ps. Tested with python 3.7.9 & 3.8.10 on windows. Also tested master branch with python 3.9.13 & 3.12.4, no problem.

Import correct libraries

---

src/searchengine/nova3/nova2.py
src/searchengine/nova3/novaprinter.py

The master branch should have version larger than stable branch.
https://github.com/qbittorrent/qBittorrent/pull/21539/files#r1790078486
Master branch `helpers.py` already has version `1.49` so no need to bump it.

Bump search engine components version

---

.github/workflows/ci_windows.yaml
src/app/main.cpp
src/base/preferences.cpp
src/base/preferences.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.h
src/gui/optionsdialog.ui
src/gui/uithememanager.cpp

Allow to choose Qt style

---

src/webui/www/private/css/style.css
src/webui/www/private/index.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/views/confirmdeletion.html
src/webui/www/private/views/filters.html
src/webui/www/private/views/transferlist.html

This PR adds following improvements: 
* Remove unused tracker entries while processing sync data
* Take into account filter selection & terms when performing 'Start/stop/delete' context actions in filter lists
Now, only filtered torrents will be affected by them, just like in the GUI.
* Provide better feedback when performing 'Start/stop/delete' context actions in filter lists
Small improvement over GUI - now these actions will be disabled if it's not possible to use them.
* Add context menu to status filter list
* Fix error when toggling filter title
Fixup for small bug introduced in https://github.com/qbittorrent/qBittorrent/pull/21269

WebUI: Improve filter lists

---

src/webui/www/private/scripts/client.js

It is enough to set them up just once during initial load. Number of elements with copyToClipboard class is fixed - they are context menu items.

WebUI: Setup copy events only once

---

src/gui/utils.cpp

currently, on linux desktop, when we have Thunar installed as the default file manager, qbittorrent does not support open file manager and select the downloaded file when we double click that item.
thus, I added the Thunar support.

Add support for Thunar file manager

---

src/gui/torrentcontentmodel.cpp
src/gui/torrentcontentmodel.h
src/gui/torrentcontentwidget.cpp

Now qbt supports dragging items from torrent content widget to another app.
Closes #5860.

Add drag support to torrent content widget

---

src/base/bittorrent/bencoderesumedatastorage.cpp
src/base/net/geoipmanager.cpp

The function already has a parameter named `result`.
Also remove a duplicate variable since it already has a pref pointer at the start of the function.

Avoid shadowing function parameter

---

src/base/bittorrent/resumedatastorage.cpp
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/webui/api/torrentscontroller.cpp

Also, by switching to template we can avoid the cost of converting to some specific type and perfectly forward the parameter to the final function.

Avoid heavy weight function object

---

src/gui/optionsdialog.cpp

Also keep the list sorted.
Fix up 2d185dc1c7932e775ecf5f2b0a7b7639ed8228f7.
Before:
After:

Don't change combobox index after selection

---

src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/dynamicTable.js

This PR adds custom compare function to Status column (same sort order as in the GUI but I could use some double check here).
I suppose this could close https://github.com/qbittorrent/qBittorrent/issues/15499

WebUI: Improve sort order in Status column

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/torrentimpl.cpp

Correctly apply filename filter when !qB extension is enabled

---

src/webui/www/private/rename_files.html

Added an IIFE around the whole script to suppress variable redeclaration errors.
Closes #21614.
ps. PR #21621 is for v5_0_x since it wasn't able to cleanly cherry-pick this PR to v5_0_x.

WebUI: fix 'rename files' dialog cannot be opened more than once

---

src/webui/webapplication.cpp

Closes #20873. Maybe also #20675.
More explanation in: https://github.com/qbittorrent/qBittorrent/issues/20873#issuecomment-2408992631

Free resources allocated by web session once it is destructed

---

src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/gui/uithememanager.cpp

Relevant prior PR #21553
Fusion is still the default.
Here is how it looks on a default profile:

Allow to select Qt's default style

---

COPYING.GPLv2

The license text and terms do not change, but the document has been updated, to reflect the FSF's current contact points, and to change the example name, under the "How to apply..." part, to "Moe Ghoul".
This reflects the FSF's own change, in the www.gnu.org CVS repo, at https://web.cvs.savannah.gnu.org/viewvc/www/www/licenses/old-licenses/gpl-2.0.txt?annotate=1.5
Fixes #7749.

Update GPLv2 license to reflect latest version

---

src/webui/www/private/scripts/dynamicTable.js

Fixup for #21007 and #21147. Table navigation with arrows (#15186) has been broken by that changes.
See https://github.com/qbittorrent/qBittorrent/pull/21007#discussion_r1807326166 and https://github.com/qbittorrent/qBittorrent/pull/21147#discussion_r1807361385 for details.
This PR restores the functionaly.

WebUI: restore arrow keys table navigation

---

src/webui/www/private/scripts/client.js

This fixes a bug where the file filter is only shown when the Content tab is switched to. The filter is not being shown if the Content tab is already selected on page load (due to being previously selected).

WebUI: Show file filter when Content tab selected on load

---

src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/prop-trackers.js

Static trackers come before anything else so in this PR I made sure they are not moved when sorting Trackers table columns.

WebUI: Don't sort rows with static trackers in Trackers table

---

src/gui/mainwindow.cpp

* Updated python installer URL to retrieve version `3.13.0` (Windows)

Update python installer version for Windows

---

src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/prop-general.js
src/webui/www/private/scripts/prop-peers.js
src/webui/www/private/scripts/prop-trackers.js
src/webui/www/private/scripts/prop-webseeds.js

Currently the properties panels don't immediately clear when unselecting the torrent (e.g. by switching filters)/

WebUI: Clear properties panel when torrent no longer selected

---

src/webui/www/private/scripts/dynamicTable.js

Auto resize can be triggered by:
1. Double clicking the column's resize handle (its rightmost edge)
2. The table header's context menu
Closes #21627.

WebUI: Support auto resizing table columns

---

src/webui/www/private/scripts/client.js

The required JS may not yet be loaded, resulting in an error when calling `window.qBittorrent.Rss.init()`.

WebUI: Fix displaying RSS panel on load

---

src/base/http/server.cpp
src/base/http/server.h

Simplify code by utilizing QSslConfiguration object.
Also don't mess with global default value via `QSslConfiguration::setDefaultConfiguration`. It should not be done at such local class.

Simplify SSL parameters setup

---

src/webui/www/private/css/style.css
src/webui/www/private/index.html
src/webui/www/private/scripts/client.js
src/webui/www/private/views/preferences.html

Closes #21600
Sometimes I am bored and want to try new things. This time I wanted to code the WebUI.
If user hasn't explicitly set validly his preference -> Use system/browser preference and react to changes to it
If user has explicitly and validly set his preference -> Use the user's settings and don't react to system/browser preference change
Obligatory pic:

WebUI: Add color scheme switcher

---

src/gui/optionsdialog.cpp

Handle Qt style names in a case insensitive way

---

src/webui/www/private/css/style.css
src/webui/www/private/index.html

Add a tooltip to indicate the button's function. 
And change the cursor to a pointer since label is used as a button.

WebUI: Add tooltip to regex filter button

---

src/base/bittorrent/bandwidthscheduler.cpp
src/base/bittorrent/sessionimpl.cpp
src/base/http/connection.cpp
src/base/net/dnsupdater.cpp
src/base/torrentfilter.cpp
src/gui/advancedsettings.cpp
src/gui/torrentcontentmodelitem.cpp
src/gui/transferlistmodel.cpp
src/webui/api/synccontroller.cpp
src/webui/webapplication.cpp

Those are the `default` cases which are not expected to hit (nor reachable) normally.
When the code is compiled with release mode and it reaches `Q_UNREACHABLE()`, it becomes undefined behavior. So it rely on the developers to catch the errors in debug mode. The upside of this is that the `switch` statement will be more optimized than not using it. This also means the statements after `Q_UNREACHABLE()` isn't important. It allow anything to preserve the intention of the code.
This marco is preferred over C++23 `std::unreachable` because it will automatically insert a `Q_ASSERT(false)` with it.

Use proper macro for unreachable switch cases

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/bittorrent/torrentimpl.cpp

Obtain current date time of Qt and libtorrent clocks only once for processing entire current libtorrent alerts bunch.

Optimize conversion of time points from libtorrent to Qt clocks

---

src/base/bittorrent/torrentimpl.cpp

There may be quite a few endpoint names (one for each available network card), and they usually remain unchanged throughout the session, while previously producing such names was performed every time they were accessed. Now they are retrieved from the cache.

Optimize converting TCP endpoints to strings

---

src/gui/uithememanager.cpp

`QStyleHints::colorScheme()` returns chosen color scheme even if current style doesn't support it and uses different palette.
Ref.: https://github.com/qbittorrent/qBittorrent/issues/21421#issuecomment-2453437663.

Check real palette darkness to detect "dark theme"

---

src/webui/www/public/css/login.css
src/webui/www/public/scripts/login.js

Fetch API is the modern replacement for XMLHttpRequest.
Also show more detailed error messages. Closes #21739.
Screenshot:

WebUI: use Fetch API to login

---

src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/preferences.cpp
src/base/preferences.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/gui/statusbar.cpp
src/gui/statusbar.h
src/webui/api/appcontroller.cpp
src/webui/api/synccontroller.cpp
src/webui/api/transfercontroller.cpp
src/webui/www/private/index.html
src/webui/www/private/scripts/client.js
src/webui/www/private/views/preferences.html

This change displays the last detected IPv4 and/or IPv6 address(es) in the GUI and WebUI's status bar. This does not yet handle systems with multiple addresses of the same type (e.g. multiple IPv6 addresses).
This is a continuation of #20118, which has been closed. I've reused most of the code (with minor changes) but removed the ability to directly open the Execution Log by clicking on the address label.
GUI (resolution 1280x800):
WebUI:

Display External IP Address in status bar

---

src/webui/www/private/addpeers.html
src/webui/www/private/addtrackers.html
src/webui/www/private/addwebseeds.html
src/webui/www/private/confirmfeeddeletion.html
src/webui/www/private/confirmruleclear.html
src/webui/www/private/confirmruledeletion.html
src/webui/www/private/confirmtrackerdeletion.html
src/webui/www/private/download.html
src/webui/www/private/downloadlimit.html
src/webui/www/private/editfeedurl.html
src/webui/www/private/edittracker.html
src/webui/www/private/editwebseed.html
src/webui/www/private/index.html
src/webui/www/private/newcategory.html
src/webui/www/private/newfeed.html
src/webui/www/private/newfolder.html
src/webui/www/private/newrule.html
src/webui/www/private/newtag.html
src/webui/www/private/rename.html
src/webui/www/private/rename_feed.html
src/webui/www/private/rename_file.html
src/webui/www/private/rename_rule.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/color-scheme.js
src/webui/www/private/setlocation.html
src/webui/www/private/shareratio.html
src/webui/www/private/upload.html
src/webui/www/private/uploadlimit.html
src/webui/www/webui.qrc

Fixup for #21613.
Applies the color scheme for `iframe` dialogs.
I extracted the logic into a separate file to avoid copy-paste hell.

WebUI: fix color scheme for iframes

---

src/webui/api/torrentscontroller.cpp
src/webui/www/private/css/style.css
src/webui/www/private/scripts/prop-general.js
src/webui/www/private/views/properties.html

This PR adds torrent progress percentage next to pieces bar in General tab, as in the GUI:

WebUI: Display torrent progress percentage in General tab

---

src/webui/www/private/scripts/localpreferences.js
src/webui/www/private/scripts/mocha-init.js

LocalPreferences class is now created using modern class syntax (minimal changes to remove Mootools bits). In addition, I removed redundant suffix from class name.

WebUI: Use modern class syntax to create LocalPreferences class

---

src/webui/www/private/css/palette.css
src/webui/www/private/index.html
src/webui/www/private/scripts/client.js
src/webui/www/private/views/preferences.html

Original PR: #21613
The css is different in this branch.
I took the liberty of changing the `*` selector to the `root` selector. I hope this is fine.

WebUI: Add color scheme switcher (v5_0_x)

---

src/base/net/downloadmanager.cpp
src/base/preferences.cpp
src/base/preferences.h
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/webui/api/appcontroller.cpp
src/webui/www/private/views/preferences.html

Backport of #21364
Closes #21781
The PPA autobuilds the `v4_6_x` branch for the older Ubuntu versions. So this will be available automatically after the PR is merged.
Because it involves a security fix I think we should backport it to v4_6_x.

Don't ignore SSL errors (v4_6_x)

---

src/base/bittorrent/torrentimpl.cpp

The resume data obtained from libtorrent contains an empty "progress" when it was requested at a time when the initial resume data has not yet been checked (e.g. when user closed qBittorrent shortly after launch). We should preserve the initial "progress" in such cases.
Ref.: #21775.

Preserve initial torrent progress while checking resume data

---

src/webui/www/private/scripts/color-scheme.js

Fixup for #21780. Account for changed preferences class name in the color scheme logic.

WebUI: fix preferences class name

---

src/webui/www/private/css/style.css

Thin scrollbars are now used if they are supported by user's browser. The main goal was to make them less intrusive in Chrome-likes on some platforms.
a) Before:
b) After:

WebUI: Use thin scrollbars

---

src/webui/www/private/scripts/client.js

The cached info doesn't need to wait until the DOM is loaded. They can be fetched far earlier.

WebUI: fetch cached info early

---

src/base/bittorrent/torrentimpl.cpp

`TorrentImpl::isDownloading()` was excessively broad which included unexpected events for the case here. So check the underlying state directly.
The current PR should be able to handle #21788 use case.
Closes #21788.

Don't apply Mark-of-the-Web on existing files

---

src/base/addtorrentmanager.cpp
src/base/addtorrentmanager.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/bittorrent/torrentimpl.cpp
src/base/utils/os.cpp
src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.h
src/gui/guiaddtorrentmanager.cpp
src/gui/optionsdialog.cpp
src/gui/search/searchwidget.cpp
src/gui/search/searchwidget.h
src/gui/transferlistfilters/trackersfilterwidget.cpp
src/gui/uithememanager.cpp

* #21687
* #21717
* #21720
* #21735
* #21738
* #21764
* #21768
* #21770
* #21771
* #21784
* #21786
* #21806
* #21836

Backport changes in v5.0.x branch

---

src/gui/mainwindow.cpp
src/gui/search/searchwidget.cpp
src/gui/search/searchwidget.h

Don't depend on upper level widget (Main Window) state.

Remove wrong dependency on Main Window

---

src/webui/www/private/css/dynamicTable.css
src/webui/www/private/css/style.css
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/search.js
src/webui/www/private/views/log.html
src/webui/www/private/views/rss.html
src/webui/www/private/views/searchplugins.html
src/webui/www/private/views/transferlist.html

Event delegation is now used to handle basic table events. 
2 minor fixes were added to match GUI behavior:
- Clicking on the table body deselects everything
- Table rows are now scrolled into view when using up/down arrows

WebUI: Use event delegation to handle common table events

---

src/app/cmdoptions.cpp
src/app/qtlocalpeer/qtlocalpeer.cpp
src/base/bittorrent/dbresumedatastorage.cpp
src/base/http/requestparser.cpp
src/base/http/types.h
src/base/net/geoipdatabase.cpp
src/base/utils/fs.cpp
src/base/utils/string.cpp
src/base/utils/string.h

Also change helper function parameter to `std::string_view` as it is more generic and can handle more types (including view types).

Avoid redundant string length function calls

---

src/webui/www/private/scripts/dynamicTable.js

The value has unit suffix (`px`) and require using `parseInt()` for conversion.
Related: https://github.com/qbittorrent/qBittorrent/pull/21831#discussion_r1844954795.
Fix up f73f31619ddebafcc82dfd65b9be7eeb347d467a.

WebUI: fix failed conversion to number

---

src/base/bittorrent/torrentimpl.cpp

Discard obsolete "state update" events after torrent is reloaded

---

src/webui/www/private/scripts/client.js

Only update the Status filter list when torrents are removed, added or their state changed.

WebUI: Eliminate unnecessary Status filter list updates

---

src/gui/mainwindow.cpp

Change `https://www.qbittorrent.org/news.php` to `https://www.qbittorrent.org/news` to avoid redirect.

Update link to news

---

src/webui/webapplication.cpp
src/webui/www/private/scripts/misc.js
src/webui/www/private/scripts/mocha-init.js

Previously we would still download the file but it would contain the error response, resulting in an invalid file.
To test: export a .torrent file for a torrent that hasn't yet downloaded metadata

WebUI: Display error when download fails

---

src/webui/api/torrentscontroller.cpp

Adds the parameter `addForced` to the `/api/v2/torrents/add` API call. Defaults to false if not provided.

WebAPI: Add `forced` parameter to `torrents/add`

---

src/webui/www/private/scripts/misc.js
src/webui/www/private/scripts/pathAutofill.js
src/webui/www/public/scripts/login.js

The `Content-type` header isn't required since `URLSearchParams` is present.
The `method` property is preferred to be always specified for clarity.
The `cache: "no-store"` is preferred for most GET requests to avoid caching.

WebUI: clean up fetch API usage

---

src/base/rss/rss_autodownloadrule.cpp

If you already have episode `2x4` in the previously matched list for an RSS auto-download rule, then a REPACK or PROPER is matched, the original is added to the list again, e.g.:
```
2x4
2x4-REPACK
2x4
```
This change should append an episode to an auto download rule's previously matched list only if it hasn't been previously matched.

Don't add duplicate episodes to list of previously matched

---

src/webui/www/private/css/style.css

This PR ensures that the same base background color is used across different browsers (more consistent styling).
Context https://github.com/qbittorrent/qBittorrent/pull/21498#issuecomment-2399929576
Used default Chrome colors https://github.com/qbittorrent/qBittorrent/issues/21894#issuecomment-2494253459
Before/after (Firefox):
PR https://github.com/qbittorrent/qBittorrent/pull/21498 can go forward after this is merged.

WebUI: Set base background color

---

src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h

Schedule request of announce entries of torrent and skip subsequent requests until existing one is done. Otherwise, they can flock in the queue until `libtorrent` is free to execute them, which leads to multiple overwriting of tracker entry statuses with identical (or even obsolete) data.

Avoid redundant requests of announce entries from libtorrent

---

src/base/rss/rss_parser.cpp
src/base/rss/rss_parser.h

Yet another `QDateTime` related performance improvement.

Use cached current time when parse RSS feed

---

src/base/bittorrent/torrentcreator.cpp

Now on Windows, it won't follow/include .lnk files when creating torrents.
Note that libtorrent will throw errors if we force adding .lnk files.
Closes #13286.

Don't follow symlink when creating torrents

---

src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/prop-general.js
src/webui/www/private/scripts/prop-peers.js
src/webui/www/private/scripts/prop-trackers.js
src/webui/www/private/scripts/prop-webseeds.js
src/webui/www/private/scripts/search.js
src/webui/www/private/views/aboutToolbar.html
src/webui/www/private/views/cookies.html
src/webui/www/private/views/log.html
src/webui/www/private/views/preferencesToolbar.html
src/webui/www/private/views/rss.html
src/webui/www/private/views/rssDownloader.html

All addClass(), removeClass() and hasClass() instances were changed to use classList equivalent:
https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

WebUI: Replace Mootools class list manipulation methods

---

src/webui/www/private/index.html

This PR adds missing icon to 'Queue' context menu item:

WebUI: Add missing icon to 'Queue' context menu item

---

src/base/bittorrent/torrentimpl.cpp

Include the `xl` (eXact Length) parameter in the magnet URI string inside the function `TorrentImpl::createMagnetURI()`.
Closes #20752.

Add eXact Length parameter when creating magnet URI

---

dist/windows/installer-translations/italian.nsh
src/base/bittorrent/dbresumedatastorage.cpp
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/bittorrent/torrent.h
src/base/bittorrent/torrentcreator.cpp
src/base/bittorrent/torrentdescriptor.cpp
src/base/bittorrent/torrentdescriptor.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h
src/base/rss/rss_autodownloadrule.cpp
src/base/rss/rss_parser.cpp
src/base/rss/rss_parser.h
src/gui/rss/htmlbrowser.cpp
src/webui/api/serialize/serialize_torrent.cpp
src/webui/api/torrentcreatorcontroller.cpp
src/webui/www/private/scripts/prop-trackers.js
src/webui/www/public/scripts/login.js

* #21873
* #21874
* #21879
* #21904
* #21917
* #21944
* #21949
* #21959
* #21346
* #21832
* #21920

Backport changes to v5.0.x branch

---

src/webui/webapplication.cpp

It might block WebUI from logging in under specific network configurations.
Fix up 130c0d848751ca0ebf236ddc09310b7d3a32a80e.
ps. Only affects master branch.

Remove wrong conditional in Origin trustworthy check

---

src/webui/www/private/rename_files.html
src/webui/www/private/scripts/download.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/piecesbar.js
src/webui/www/private/scripts/progressbar.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/search.js

All elements are now created using createElement() method:
https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement

WebUI: Use vanilla JS to create elements

---

.github/workflows/ci_python.yaml
.github/workflows/helper/pre-commit/check_grid_items_order.py
.github/workflows/helper/pre-commit/check_translation_tag.py
.pre-commit-config.yaml
src/gui/aboutdialog.ui
src/gui/addnewtorrentdialog.ui
src/gui/banlistoptionsdialog.ui
src/gui/ipsubnetwhitelistoptionsdialog.ui
src/gui/optionsdialog.ui
src/gui/properties/peersadditiondialog.ui
src/gui/properties/propertieswidget.ui
src/gui/rss/automatedrssdownloader.ui
src/gui/statsdialog.ui
src/gui/torrentcategorydialog.ui
src/gui/torrentcreatordialog.ui
src/gui/torrentoptionsdialog.ui
src/gui/torrentsharelimitswidget.ui
src/gui/trackersadditiondialog.ui

* GHA CI: add checks for grid items order
Now all items under `QGridLayout` are required to be sorted. This allow
us to omit tabstop order. The tabstop order will follow the layout order.
The script can be invoked to fix wrong grid items order in .ui files:
```console  
python check_grid_items_order.py file.ui
```
* Sort grid items properly
Supersedes #21856.
* Make links accessible by keyboard
* Make tab key switch focus
These fields do not expect tab characters.

Sort grid items properly

---

src/gui/rss/rsswidget.cpp
src/gui/rss/rsswidget.h
src/gui/rss/rsswidget.ui

Related: https://github.com/qbittorrent/qBittorrent/pull/21996#issuecomment-2543127251

Fix tab order in RSS widget

---

src/gui/rss/rsswidget.cpp
src/gui/rss/rsswidget.h

In RSS widget, a relative url will cause an infinite loop loading for resource, which won't break until unselect the article explicitly, thus caused the memory leak described in #20117 .
The code provides a conversion over the first 3 forms of relative path as described in [MDN web docs](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL#absolute_urls_vs._relative_urls) using regex, and only function on `<a href>` and `<img src>` html tags. With the code, RSS widget now should follow the correct absolute urls.
However, the #20117 could not be fully closed with the code, as now log shows the RSS widget still send around 5 reqs/sec in the condition which was causing a rapid flow of qDebug log which indicates it stuck on a infinite loop sending …

Resolve relative URLs within RSS article description

---

.pre-commit-config.yaml

* Bumped `pre-commit-hooks` -> v5.0.0
* Bumped `typos` -> v1.28.4

GHA CI: Bump some pre-commit hook revs

---

src/webui/www/private/scripts/dynamicTable.js

All getParent() instances (Mootools) were changed to use closest() method:
https://developer.mozilla.org/en-US/docs/Web/API/Element/closest

WebUI: Use closest() to get parent element

---

src/searchengine/nova3/helpers.py

* Use built-in method for decoding HTML entities
* Provide SSL context field
The allows the caller to provide proper SSL parameters and avoid dirty monkey patching to suppress SSL errors.

Improve Search engine

---

src/webui/api/torrentscontroller.cpp

The backport commit c3c7f28bad0a3e874e6883d98e422c6716f8e77a was insufficient.
Closes #22039.

Fix cannot remove trackers via WebAPI

---

src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/search.js

All getElement instances (Mootools) were changed to querySelector.

WebUI: Replace getElement with querySelector

---

src/webui/www/private/views/rssDownloader.html

This PR removes broken event listener attached to RSS Rules table. Alternatively, it could be fixed (by changing toElement property to target) but doing so would make the context menu behavior inconsistent between WebUI/GUI.
Please let me know what is preffered.

WebUI: Remove redundant event listener

---

src/base/bittorrent/sessionimpl.cpp

By capturing the specific data instead of torrent handle the lambda can become non-mutable.

Simplify captured variable type

---

src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/misc.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/views/filters.html

Now the containers support using string as key so the intermediate hashing/mapping to number isn't needed now.

WebUI: Remove unnecessary hashing

---

src/searchengine/nova3/helpers.py

Some plugin needed the raw data for further processing.
Related: #22074.

Add parameter to control whether to unescape HTML entities

---

src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/webui/api/appcontroller.cpp
src/webui/www/private/views/preferences.html

This feature is adapted from [qBittorrent-Enhanced-Edition](https://github.com/c0re100/qBittorrent-Enhanced-Edition) to allow for automatically adding trackers retrieved from a URL. @ngosang's [trackerlist repo](https://github.com/ngosang/trackerslist/) is a good example, however I've opted not to include a default URL.
Partially addresses #14535.

Support fetching tracker list from URL

---

src/gui/optionsdialog.cpp

Handle Qt style options uniformly

---

src/webui/www/package.json

The plugin was causing problems in new versions so pin it with an older version and look into it later.

WebUI: temporarily pin dependency version

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/ci_windows.yaml
.github/workflows/coverity-scan.yaml

* Updated `primary` "boost_url" to `archives.boost.io`
____
**The agreement between Boost & JFrog came to an end in December 2024.**
____
**Reference:**
* https://github.com/boostorg/boost/issues/924

GHA CI: Update Boost URL

---

src/gui/search/searchjobwidget.cpp
src/gui/search/searchwidget.cpp
src/gui/search/searchwidget.h

The search pattern text reflects that of the current search tab, unless it is manually edited.
The edited search pattern can be reset by double-clicking on one of the tabs.
The alternative option @bartonnen [suggested](https://github.com/qbittorrent/qBittorrent/issues/17184#issuecomment-2573591004) is to simply follow the current tab regardless of whether the pattern has been edited or not. This behavior seems undesirable to me.

Allow to reuse existing search term

---

.github/workflows/ci_webui.yaml

Before this change, it wasn't clear which exact version were installed.

GHA CI: show installed version

---

src/webui/api/torrentscontroller.cpp

This PR adds an optional parameter `includeTrackers` to the Torrent info endpoint `/torrents/info` to include the trackers list of each torrent in the response under the key `trackers`.
Me and a lot of other users runs anything between 1-40k torrents in a single instance and we rely on various tools to do things like tag by different tracker states.
To get the trackers we have to first get the list of torrents and then loop through that to get the trackers per torrent. With 10k torrents that's 10000+1 requests towards qBitorrent. It does handle it fairly well but it feels a bit wrong to spam it like that.
With this change we'll be able to get all that info in a single call (or few calls with pagination). It will most likely reduce the overall load quite a bit.
This is my first time …

WebAPI: optionally include trackers list in torrent info response

---

src/base/utils/os.cpp
src/gui/powermanagement/powermanagement.cpp

Only Mark-of-the-Web and Power Management are affected.

Avoid memory leak on macOS

---

src/gui/torrentcontentmodel.cpp

Set folder as partially checked when it has at least one partially checked child and none unchecked.
Closes #22189.

Fix torrent content checkbox state under certain conditions

---

.pre-commit-config.yaml
src/app/application.cpp

* Bumped `codespell` -> `2.4.0`
* Bumped `typos` -> `1.29.4`
(Applied typo fix from dry-run)

GHA CI: Bump numerous hook revs

---

src/base/preferences.cpp
src/base/preferences.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.h
src/gui/optionsdialog.ui
src/gui/search/searchjobwidget.cpp
src/gui/search/searchjobwidget.h
src/gui/search/searchwidget.cpp
src/gui/search/searchwidget.h

Store opened search tabs between app restarts

---

src/gui/properties/peerlistwidget.cpp

Hide zero and infinity values in peer list only when that setting is set to `Always`

---

src/webui/www/private/css/dynamicTable.css
src/webui/www/private/scripts/dynamicTable.js

See https://github.com/qbittorrent/qBittorrent/pull/22118#issuecomment-2600211009 for updated information.

WebUI: Allow to move state icon to name column in torrents table

---

src/base/rss/feed_serializer.cpp
src/gui/search/searchwidget.cpp

It saves a bit of space on disk and deters novice users from tampering them.

Use compact format for JSON files

---

src/base/preferences.cpp
src/base/preferences.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/gui/search/searchwidget.cpp
src/gui/search/searchwidget.h

Store search history

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/ci_windows.yaml
.github/workflows/coverity-scan.yaml

* Bump libtorrent -> `1.2.20`
https://github.com/arvidn/libtorrent/releases/tag/v1.2.20
* Bump libtorrent2 -> `2.0.11`
https://github.com/arvidn/libtorrent/releases/tag/v2.0.11

GHA CI: Bump libtorrent versions

---

src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/search.js
src/webui/www/private/views/preferences.html
src/webui/www/private/views/rss.html

This PR further reduces Mootools usage.

WebUI: Replace getElements & getChildren

---

src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/webui/api/appcontroller.cpp
src/webui/www/private/views/preferences.html

The `announce_port` setting permits to overwrite the port passed along to trackers as the `&port=` parameter. If left as the default, the listening port is used. This setting is only meant for very special cases where a seed's listening port differs from the effectively exposed port (e.g., through external NAT-PMP). See https://github.com/arvidn/libtorrent/pull/7771 for an example use-case.
This PR adds the relevant setting alongside the existing `announce_ip` setting.
The setting subsequently modifies the announced port (`&port=1234`):
```
127.0.0.1 - - [27/Oct/2024 09:44:16] "GET /announce?info_hash=%a7%801%f7%3b%a1k%3a%8e%b6%84%dd%cfyw%f1%f3%b8m!&peer_id=-qB5100-YwWihiQ4KGdM&port=1234&uploaded=0&downloaded=0&left=0&corrupt=0&key=CEDD0BC7&event=started&numwant=200&compact=1&no_peer_id=1& …
```

Add announce_port support

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/ci_windows.yaml
.github/workflows/coverity-scan.yaml

Also bump boost::asio to 1.77 (linux) since previous version has a bug that prevents compiling in C++20 mode.

GHA CI: explicitly set C++20 mode for libtorrent

---

src/webui/www/private/scripts/contextmenu.js

This PR fixes a memory leak in context menus. Previously, for some reason, each menu retained references to its target elements without utilizing them further. Since the targets property was accessible/reachable from the root (window object), these references persisted even after the elements were removed from the DOM, preventing them from being garbage collected.
It's easily reproducible - just add a decent amount of torrents, switch between categories multiple times, then capture heap/detached elements snapshot in the Memory tab (Chrome dev tools). The number of detached elements will continue to increase after each category switch and they won't be cleaned up.
[more context](https://github.com/qbittorrent/qBittorrent/pull/22220/files#r1941137796)

WebUI: Fix memory leak in context menus

---

.github/workflows/ci_ubuntu.yaml

Upstream now defaults to static runtime and the previous URL is invalid now.
Upstream commits:
* https://github.com/linuxdeploy/linuxdeploy/commit/c28054bab6623e72e0e27ffec88c41df5ce46667
* https://github.com/linuxdeploy/linuxdeploy-plugin-qt/commit/ce5291e25979d7d6417551d787f308b88c1b8d76
Also fuse2 is not needed now as stated on:
https://github.com/AppImage/type2-runtime?tab=readme-ov-file#type2-runtime-

GHA CI: fix AppImage building

---

.github/workflows/ci_webui.yaml
src/webui/www/package.json
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/misc.js
src/webui/www/private/scripts/progressbar.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/speedslider.js
src/webui/www/test/private/misc.test.js

The `round()` returning floating point number is not a good idea. This is due to floating point representation is imprecise and sometimes it cannot faithfully represent a number, for example `0.09 + 0.01 !== 0.1 `. Therefore, it should be avoided and/or utilize other function to achieve the goal.
Also, improve `window.qBittorrent.Misc.toFixedPointString()` and add test cases.

WebUI: replace rounding function from MooTools

---

src/webui/api/torrentscontroller.cpp

WebAPI: Do not wrap result if offset is invalid

---

src/gui/CMakeLists.txt
src/gui/macosshiftclickhandler.cpp
src/gui/macosshiftclickhandler.h
src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h

Adds a macOS-specific event filter to handle shift-click range selection in the transfer list. This addresses a long-standing issue where shift-click selection was not working correctly in the transfer list on macOS.
The implementation:
- Creates a dedicated MacOSShiftClickHandler class to manage shift-click behavior
- Tracks the last clicked index using a persistent model index
- Properly handles both shift-click and command+shift-click selection modes
- Only activates on macOS via conditional compilation
This is a workaround for QTBUG-115838, which affects QTreeView shift-click selection behavior on macOS. The issue prevents users from selecting a range of torrents using shift-click, making bulk operations more difficult.
Closes #16818.
_Please note that in these videos, I'm holding the …

Fix shift-click selection on macOS

---

src/webui/www/private/scripts/dynamicTable.js

This PR fixes a bug where the sort icon did not update correctly after reordering columns.
Steps to reproduce:
1. Sort a column
2. Move it to a different position
3. The sort icon remains in its original location

WebUI: Update sort icon after changing column order

---

src/webui/www/private/scripts/prop-trackers.js

We can only edit one URL through the dialog, so there's no point in showing this context option when more than one tracker is selected in trackers table.

WebUI: Show 'Edit tracker URL...' only when one tracker is selected

---

src/webui/www/private/scripts/prop-trackers.js

In Trackers table, moving the 'URL' column from its default (2) position caused the 'Tracker editing' dialog to display incorrect data.
Steps to reproduce:
1. Move 'URL' column in Trackers table to any position from default
2. Choose tracker URL and click 'Edit tracker URL':

WebUI: Fix bug where the 'Tracker editing' dialog displays incorrect data

---

src/webui/www/private/scripts/dynamicTable.js

This PR fixes a bug where row highlight effect would be lost after reordering columns.

WebUI: Maintain row highlight after rearranging table columns

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_ubuntu.yaml
.github/workflows/ci_windows.yaml

* GHA CI: tweak cache size
It seems ~500MB is enough to cache all the build artifacts but we still make it a bit larger to avoid thrashing.
* GHA CI: shorten Windows CI build time
Now vcpkg caches b2 tool. Boost doesn't need the exact b2 version to generate the cmake files.

Improve CI scripts

---

.pre-commit-config.yaml
src/base/http/requestparser.cpp
src/base/search/searchpluginmanager.cpp
src/base/utils/bytearray.cpp
src/base/utils/bytearray.h
src/base/utils/foreignapps.cpp
src/base/utils/password.cpp
src/gui/search/searchwidget.cpp
test/testutilsbytearray.cpp

1. Utilize string matcher
2. Remove split behavior parameter Previously `KeepEmptyParts` behavior doesn't match Qt's implementation and since our codebase doesn't really make use of it, we can just remove the parameter.
3. Add tests.

Improve "split to byte array views" function

---

src/app/application.cpp
src/base/search/searchdownloadhandler.cpp
src/base/search/searchhandler.cpp
src/base/search/searchpluginmanager.cpp
src/base/utils/foreignapps.cpp
src/gui/utils.cpp

It is unexpected for the child process to inherit parent file descriptors.
Requires Qt >= 6.6 and only affects Linux.
Closes #10312.

Don't leak parent file descriptors to child processes

---

src/webui/www/private/views/preferences.html

`Hash` is deprecated by mootools.
Also simplify related code.

WebUI: replace deprecated data type

---

src/app/application.cpp
src/base/CMakeLists.txt
src/base/addtorrentmanager.cpp
src/base/addtorrentmanager.h
src/base/bittorrent/addtorrenterror.h
src/base/bittorrent/session.h
src/base/bittorrent/sessionimpl.cpp
src/base/rss/rss_autodownloader.cpp
src/base/rss/rss_autodownloader.h

Allows the observer to determine that the torrent was not added due to a duplicate torrent.
This is not supposed to have any effect on its own, but it is required for some other improvements.

Improve add torrent error handling

---

src/base/rss/rss_autodownloader.cpp

Partialy solves the problem described in #18436.

RSS: Mark matched article as "read" if refers to duplicate torrent

---

src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/webui/www/private/views/preferences.html

Most affected options are not really incompatible with SOCKS4 but it is due to Qt missing implementation. Therefore 'unavailable' is more suitable.
screenshot:

Revise wordings related to SOCKS4 proxy

---

src/webui/webapplication.cpp

Since client-side translation wasn't implemented I believe we should restore ability to use server-side translation by custom WebUI in all the current branches.
Original PR #20968.

Restore ability to use server-side translation by custom WebUI

---

src/webui/www/private/scripts/client.js

Fixup for https://github.com/qbittorrent/qBittorrent/pull/21145
To reproduce:
1) Select status filter with 0 torrents
2) Enable 'Auto hide zero status filters' and save settings. Hidden filter is still selected:

WebUI: Set status filter to 'All' if selected filter is no longer visible

---

.github/workflows/ci_macos.yaml
.github/workflows/ci_windows.yaml

* Bumped Windows/macOS Qt version to `6.9.0`
[Qt 6.9.0 Released](https://www.qt.io/blog/qt-6.9-released) / [Release Notes](https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.9.0/release-note.md)
Qt 6.8.3+ has a fix for macOS related issue, ref.: #22303 / [QTBUG-134316](https://bugreports.qt.io/browse/QTBUG-134316).

GHA CI: Use Qt 6.9.0 on Windows and macOS

---

src/webui/www/private/views/rss.html

Introduced Author, 'Open link' headers.
Note that the Author and 'Open link' are not mandatory fields in RSS/Atom feeds. So these headers will only be displayed when the feed includes them.
screenshot:

WebUI: add headers to RSS entry viewer

---

src/webui/www/private/views/rss.html

Use `allow-same-origin` sandbox directive to allow fetching the parent CSS.

WebUI: fix dark mode in RSS entry viewer

---

src/webui/www/private/scripts/client.js

Don't save the wrong size when the tab is collapsed.
Reported in: https://github.com/qbittorrent/qBittorrent/pull/21215/files#r1966052959

WebUI: avoid saving invalid size

---

src/base/search/searchpluginmanager.cpp
src/searchengine/nova3/helpers.py

Pass 'Perform hostname lookup via proxy' setting along the way.
Also add underline to variables and functions that are private to the python module.
ps. based on user reports, the search engine SOCKS lib seems to be broken. I'll look into it after this PR.

Add SOCKS4/SOCKS4a proxy support to search engine

---

src/searchengine/nova3/helpers.py
src/searchengine/nova3/nova2.py
src/searchengine/nova3/nova2dl.py

Previously it require each plugin to import helpers.py to setup SOCKS proxy.
Now it is enforced by default for all plugins when qbt invokes them.
Also added a function for plugins to ignore/restore the socket to default state.

Enforce SOCKS proxy setting in search engine plugins

---

src/gui/mainwindow.ui
src/webui/www/private/index.html

Swap "Add torrent file" with "Add torrent link" button to be consistent with order in File menu.
Closes #22420.
Before
After

Swap add file/link buttons on toolbar

---

src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h

Deferring the opening of the preview slightly gives the preview select dialog time to close and for focus to shift back to the main window.
Closes #22607.

Fix preview not opening on Wayland

---

src/base/bittorrent/filesearcher.cpp
src/base/bittorrent/filesearcher.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/bittorrent/torrent.h
src/base/bittorrent/torrentcontenthandler.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h
src/gui/addnewtorrentdialog.cpp
src/gui/properties/peerlistwidget.cpp
src/gui/properties/propertieswidget.cpp
src/gui/torrentcontentmodel.cpp
src/gui/trackerlist/trackerlistmodel.cpp
src/webui/api/synccontroller.cpp
src/webui/api/torrentscontroller.cpp

Makes asynchronous logic to look more straightforward.
Allows caller to choose blocking or non-blocking way of obtaining asynchronous results via the same interface.

Provide asynchronous results via QFuture

---

src/gui/rss/rsswidget.cpp

The long format is too verbose and hard to read.
Before (long format):
After (short format):

Use short format for displaying RSS entry date

---

src/gui/optionsdialog.ui
src/webui/www/private/views/preferences.html

Revise labels for 'duplicate torrent' actions

---

src/webui/www/private/scripts/dynamicTable.js

Convenience feature in the "Rename Files" menu in the Web UI. 
If you click one file's checkbox, and then click another with Shift held, all the checkboxes between those two will be selected/unselected based on the state of the first checkbox.
It's based on what the Windows file explorer does when holding Ctrl and Shift
Closes #22455

WebUI: Select multiple files to rename with Shift

---

src/webui/www/private/views/properties.html

Making General-tab text `unselectable` is not an improvement.
It begs to add a new `Copy -> Save path` feature, because using `Set location` to copy save path (*which requires a request*) is not faster than simply copying it from the `General` tab by double-left clicking and pressing `CTRL+C`.
I don't see a reason why its necessary to software-restrict people from copying details from the `General`-tab - there are several reasons why you would - incl. the above mentioned usecase for quickly copying save-path, but other than that its counterproductive to limit people from copying the details displayed.

WebUI: Remove `unselectable` from General tab

---

.github/workflows/ci_file_health.yaml

zizmor 1.7.0 has changed the ID.
https://docs.zizmor.sh/release-notes/#v170

GHA CI: update zizmor rules ID

---

src/app/application.cpp
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/webui/www/private/views/preferences.html

Memory working set limit is not effective on Linux at all. See [`getrlimit(2)`](https://man7.org/linux/man-pages/man2/getrlimit.2.html) → `RLIMIT_RSS`.
Introduced in #16874, disabled for macOS in #19805. This PR hides the option for Linux too.
Worth to mention that #19805 did not deliver the change for WebUI. So there is also a small fixup, I covered both cases.
Also removed pointless "This option is less effective on Linux" remark.

Remove "Physical memory (RAM) usage limit" option on Linux

---

src/app/cmdoptions.cpp

Fixes #22662.
For windows environment the `--help` output will show :
```
set QBT_NO_SPLASH=1
C:\Program Files\qBittorrent\qbittorrent.exe
```
instead of 
```
QBT_NO_SPLASH=1 C:\Program Files\qBittorrent\qbittorrent.exe
```
Changes:
- Adds a OS based if condition to `makeUsage` function to switch between the lines

Update help message for Windows systems

---

.pre-commit-config.yaml

* Bumped `codespell` -> `2.4.1`
* Bumped `typos` -> `1.32.0`

GHA CI: Bump spellcheck related hooks revs

---

src/webui/www/private/rename_files.html

Before the release of 5.1.0 I believe these two fields both used monospace fonts and also had an increased font size, maybe 14px (I couldn't find in blame where/how this regressed). Ideally, I'd like to bring this back, as it makes elaborate regexes easier to grok. This PR currently just tells the browser to use its monospace font, but I could also add a similar in-line style for font size. I just don't know if this is the best way to solve this problem; if there's a better place for this sort of styling to happen let me know
Before (v5.1.0):
After (inspect element edited):
Thanks for all your continued work maintaining the best torrent client!

WebUI: Make multi-rename search & replace fields use a monospace font

---

src/base/utils/random.cpp
src/base/utils/randomlayer_linux.cpp
src/base/utils/randomlayer_other.cpp
src/base/utils/randomlayer_win.cpp

`getrandom()` is available since Linux 3.17 (2014/10/05) yet there are older devices that don't meet this requirement.
Closes #22691.

Add fallback for random number generator

---

src/webui/www/private/scripts/client.js

Only IPv6 addresses may have a 'zone index' and therefore it should be replaced last for the result to be correct.

WebUI: fix wrong replacement sequence

---

src/webui/www/public/index.html

This PR improves the user experience on mobile devices by ensuring the username field in the login form does not automatically capitalize the first letter when the keyboard opens.
- Added `autocapitalize="none"` to the username input field (`login.html`).
Mobile browsers tend to automatically capitalize the first letter of text inputs, which can lead to login failures if the username is case-sensitive. By explicitly disabling autocapitalization, the WebUI ensures a more predictable and user-friendly experience on mobile devices.
---
**Tested on:**
- iOS (Safari)

WebUI: Prevent mobile keyboards from capitalizing username input

---

src/webui/www/private/index.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/monkeypatch.js
src/webui/www/private/scripts/search.js
src/webui/www/private/views/cookies.html
src/webui/www/private/views/preferences.html
src/webui/www/private/views/rss.html
src/webui/www/webui.qrc

See #22734, there is a memory leak in the MooTools `.destroy()`, this replaces all uses of that with the browser native `.remove()`.
This also overrides the MooTools `Document.id` function, which is used by `$(id)`. The original function always allocates an ID to elements it selects, the override doesn't, and is also a little more efficient.

WebUI: Fix memory leak

---

src/base/bittorrent/torrentimpl.cpp
src/webui/api/serialize/serialize_torrent.cpp
src/webui/api/serialize/serialize_torrent.h

We have already added some properties to serialized form of torrent used in `torrents/info` and `sync/maindata`. There are only a few properties left that are only accessible through `torrents/properties`, and users want them to be still accessible through `torrents/info`. I see no reason not to do this.
This will also allow we to completely deprecate `torrents/properties`, and use in WebUI only the data from the synchronized snapshot.

WebAPI: Add more properties to 'torrents/info' result

---

src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/trackerentrystatus.h
src/gui/trackerlist/trackerlistmodel.cpp
src/gui/transferlistfilters/trackersfilterwidget.cpp
src/webui/api/torrentscontroller.cpp
src/webui/webapplication.h
src/webui/www/private/scripts/prop-trackers.js

So far, "Updating" has been one of the tracker (announce) entry states, but it is inherently different from all the other values that indicate the **result** of the last announce. Although it makes sense to combine them into a single system in some use cases (like it is done in Trackers list), at a core level they still should be provided as different properties.
Ref.: https://github.com/qbittorrent/qBittorrent/pull/22166#issuecomment-2912282003.

Interpret tracker "updating" status as a separate property

---

.github/workflows/ci_python.yaml
.github/workflows/helper/pre-commit/check_grid_items_order.py
.github/workflows/helper/pre-commit/check_translation_tag.py
src/searchengine/nova3/helpers.py

This main point is to normalize the sorting of imports in Python scripts.
Currently the default setting from isort is used: https://pycqa.github.io/isort/docs/configuration/custom_sections_and_ordering.html

GHA CI: enforce sorted import in Python scripts

---

src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h

Avoid a blocking call to `lt::torrent_handle::torrent_file_with_hashes()`.

Use modern API to export torrent

---

src/app/filelogger.cpp

qBittorrent is able to write to the log file, so it's ok if the permission change fails. The downside will be that the file remains readable to the world.

Make modifying log file perms best effort

---

src/webui/www/private/scripts/search.js
src/webui/www/private/views/search.html

WebUI equivalent of #22122. Refreshing maintains all existing filters.

WebUI: Add ability to refresh search

---

src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui

The Language option now has its own layout since it is independent to other options (Style and Color scheme).
This avoids text in Language combobox to be left out and replaced by `...` due to Style Hint text being too long.
Screenshot:

Revise Interface section layout in Options dialog

---

src/webui/www/private/index.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/scripts/statistics.js
src/webui/www/webui.qrc

This change ensures that the WebUI caches relevant server stats for immediate display once the statistics window is opened. Previously, all stats would remain blank until maindata was fetched. This could take a while if e.g. the user was on the search tab.
Closes #22764

WebUI: Cache server stats for statistics window

---

src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/views/filters.html
src/webui/www/private/views/preferences.html

When double clicking on a filter, all other filters will be reset. For example, double clicking on a status filter will reset the categories, tags, and trackers filters to "All". This behavior can be disabled in WebUI options.
Closes #22449

WebUI: Reset filter selection when double clicking filter

---

src/webui/www/private/scripts/dynamicTable.js

This change drastically improves the performance of changing a table's sorted column. This performance is achieved through improved data structures, namely removing operations that repeatedly spliced an array. We also no longer iterate over a potentially large array.
On a torrent with ~50,000 files, re-rendering after a sort improves from ~20 seconds to 2 seconds.

WebUI: Improve performance of re-sorting table rows

---

src/webui/www/private/addpeers.html
src/webui/www/private/addtrackers.html
src/webui/www/private/addwebseeds.html
src/webui/www/private/confirmfeeddeletion.html
src/webui/www/private/confirmruleclear.html
src/webui/www/private/confirmruledeletion.html
src/webui/www/private/confirmtrackerdeletion.html
src/webui/www/private/download.html
src/webui/www/private/editfeedurl.html
src/webui/www/private/edittracker.html
src/webui/www/private/editwebseed.html
src/webui/www/private/newcategory.html
src/webui/www/private/newfeed.html
src/webui/www/private/newfolder.html
src/webui/www/private/newrule.html
src/webui/www/private/newtag.html
src/webui/www/private/rename.html
src/webui/www/private/rename_feed.html
src/webui/www/private/rename_file.html
src/webui/www/private/rename_files.html
src/webui/www/private/rename_rule.html
src/webui/www/private/setlocation.html
src/webui/www/private/shareratio.html
src/webui/www/private/speedlimit.html
src/webui/www/private/upload.html

So that the HTML layout can be rendered earlier.
A few inline scripts are moved into `<head>` for consistency.
Also, those scripts needs to wait for `DOMContentLoaded` event.

WebUI: use `defer` when loading scripts

---

WebAPI_Changelog.md
src/base/bittorrent/torrentdescriptor.cpp
src/base/bittorrent/torrentdescriptor.h
src/webui/api/torrentscontroller.cpp
src/webui/api/torrentscontroller.h
src/webui/webapplication.h

This PR implements two new APIs for fetching a torrent's metadata. The APIs accept a magnet URI, torrent hash, .torrent URL, or uploaded .torrent file, and return the torrent's associated metadata. This PR also modifies the `/torrents/add` API to support downloading a torrent whose metadata has been previously fetched. The ultimate goal is for the WebUI to provide an Add Torrent experience equivalent to that of the GUI, where content can be reprioritized/unchecked before the torrent is added.
To request metadata for a torrent, specify the torrent in the `source` query parameter of a GET request to `/api/v2/torrents/fetchMetadata`. Torrents are supported  in the following formats:
- magnet URI (e.g. `magnet:?xt=urn:btih:a8eeefc8a0dc402b24686ddfd775a409fe4b00e0&dn=example`)
- hash (e.g. …

Add WebAPI for fetching torrent metadata

---

src/webui/www/private/scripts/dynamicTable.js

By default, nodes should be expanded until explicitly collapsed. This restores the default behavior which changed in b4a16f64641873bd067ab5f6c6d54c0b4c12fdcf.
Relevant: https://github.com/qbittorrent/qBittorrent/pull/21645#discussion_r2150695297

WebUI: Restore node default collapse state

---

src/webui/www/private/scripts/dynamicTable.js

The previous logic assumed that `trs` was properly sorted, which is no longer the case.
Follow up to #22827.

WebUI: Delete correct rows after re-sort

---

src/gui/search/searchwidget.cpp

Such that action subject is truly unambiguous to the user.
Screenshots:

Revise label wordings

---

src/base/bittorrent/resumedatastorage.cpp
src/base/bittorrent/resumedatastorage.h
src/base/bittorrent/sessionimpl.cpp
src/base/bittorrent/sessionimpl.h
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/torrentimpl.h

"Resume data" can contain rather big amount of data esapecially in case of v2/hybrid torrents (due to merkle tree hashes) so it's better to avoid copying it whenever possible.

Avoid copying resume data when loading torrents

---

src/webui/api/appcontroller.cpp

Hacked qbt instances may contain malicious script placed in Run External Program and the script will attempt to hide itself by adding a lot whitespaces at the start of the command string. Users may mistake the field of being empty but is actually not. So trim the leading whitespaces to easily expose the malicious script.
**Note that GUI already trim the fields and only WebAPI doesn't trim them. This patch will unify the behavior.**
Related: https://github.com/qbittorrent/docker-qbittorrent-nox/issues/71#issuecomment-2993567440

WebAPI: Trim leading whitespaces on Run External Program fields

---

src/webui/www/private/index.html

The window footer can now be scrolled.
Closes #21541

WebUI: Make footer scrollable on mobile

---

src/gui/mainwindow.cpp
src/gui/programupdater.cpp
src/gui/programupdater.h

This brings a fallback version check to the update mechanism, which should be as stable as it can be.
It will allow migrating to another primary mechanism without having to have updated the older primary mechanism too.
In case that the primary and fallback mechanism become out of sync, the fallback mechanism wins. In this case when the user chooses to download the new update, qbt will launch our download page in their browser.
It seems that login to fosshub is not possible at this moment. So I opt to introduce this mechanism as soon as possible in order to minimize the number of users that aren't going to get informed about new version going forward.
At some later point, I'll change the primary mechanism too.

Add fallback to update mechanism

---

src/webui/www/private/css/style.css
src/webui/www/private/scripts/client.js

The toolbar should be hidden when not on the "Transfers" tab. The hiding of this toolbar can result in resizing the panels, especially on mobile, so we should recompute panel heights.

WebUI: Fix hiding of filters toolbar

---

src/webui/www/private/views/search.html

This change better handles resizing of elements on the search page to ensure no controls are hidden at typical mobile screen sizes.
Improvements seen below:
- "Search" button is now accessible
- Content no longer overflows w/ "Search plugins..." button pushed offscreen
- Tabs overflow horizontally and are scrollable, rather than pushing down the search results table
After: (including the changes from #22914 and #22915)
Before:

WebUI: Improve search page experience on mobile

---

src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/prop-peers.js
src/webui/www/private/scripts/prop-trackers.js
src/webui/www/private/scripts/prop-webseeds.js
src/webui/www/private/views/rss.html
src/webui/www/private/views/rssDownloader.html
src/webui/www/private/views/searchplugins.html

This change makes the WebUI easier to use on small screens (e.g. mobile). In cases where the window's default size is larger than the user's screen, the window will be resized appropriate (see example below). Every window has been tested for compatibility. The only windows that don't support this are the multi file rename window and the RSS Downloader window.
Height and width auto resized to fit on screen w/ small margin:
Closes #19813

WebUI: Limit window sizes to viewport size

---

WebAPI_Changelog.md
src/base/bittorrent/categoryoptions.cpp
src/webui/webapplication.h

When a category's download path option is set to "Default", its `downloadPath` is serialized into JSON as `undefined`. This results in the `downloadPath` field being omitted from `torrents/categories` and `torrents/maindata` payloads (as is expected with an `undefined` value).
The use of `undefined` here causes an issue in the WebUI. Specifically, when the category previously contained a value for this field (i.e. download path option set to either "Yes" or "No"), the `processMap` logic in `SyncController` does not detect the removal this field. This results in the category's new `downloadPath` not being properly sent to the client. By switching from `undefined` to `null`, we ensure that the `downloadPath` value is always included in the category's payload. This allows `processMap` to …

Modify `CategoryOptions` serialization to JSON

---

src/gui/transferlistwidget.cpp
src/webui/api/torrentscontroller.cpp

This matches the behavior exhibited by `TrackerListWidget` when reannouncing to a torrent's complete tracker list.
I noticed this discrepancy when investing adding individual tracker reannounce support to the WebUI/WebAPI.

Reannounce DHT when reannouncing all trackers

---

src/webui/www/private/confirmfeeddeletion.html
src/webui/www/private/confirmruleclear.html
src/webui/www/private/confirmruledeletion.html
src/webui/www/private/confirmtrackerdeletion.html
src/webui/www/private/download.html
src/webui/www/private/scripts/client.js
src/webui/www/private/upload.html

Closes [#13891](https://github.com/qbittorrent/qBittorrent/issues/13891)
Tested on the following WebUI Modals:
1. Delete
2. Rename files
3. Settings
4. About
5. Statistics
6. Add torrent
Pressing Escape without an active modal/dialog should not do anything, in my tests it did not, but i might have missed some strange cases. If any such is reported, im gonna can care of it.

WebUI: Allow closing dialogs with Escape key

---

src/gui/mainwindow.cpp
src/gui/programupdater.cpp
src/gui/programupdater.h

The alternative URL is hosted on GitHub and users are able to access it:
https://github.com/qbittorrent/qBittorrent/issues/23000#issuecomment-3092538814
https://github.com/qbittorrent/qBittorrent/issues/23009#issuecomment-3093201180
Also, disguise the user agent as a normal browser to avoid standing out from the crowd and avoid whatever issues from CDN. This only applies to non-fosshub URLs.
Closes #23000.
Closes #23009.

Add alternative URL for program update checking

---

src/app/main.cpp

Now when user specified 'help' or 'version' flag, the program will process them first and ignore all other flags (even invalid flags).
This improves program usability since user will be able to consult the help description without ensuring existing flags are all valid (or removing all flags). And user can revise the flags after reading the help description.

Revise command-line show message condition

---

src/webui/www/eslint.config.mjs
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/speedlimit.html
src/webui/www/private/views/preferences.html

The following message appears when using the outdated value:
>[@stylistic/eslint-plugin]: You are using deprecated value(boolean) for "allowTemplateLiterals"
>in "quotes", please use "always"/"never" instead.
Also prefer using double quotes over backticks for strings.

WebUI: migrate away from outdated config in ESLint

---

src/gui/CMakeLists.txt
src/gui/desktopintegration.cpp
src/gui/macutilities.h
src/gui/macutilities.mm

Currently `NSUserNotifications API` is used on MacOS to display notifications. However this is marked as deprecated and should be replaced with `UserNotifications.frameworks API`. With the new API it is required to ask for permission before notifications can be send. The program will ask for permission to send notifications on the start.
Asking for permission to send notifications:
Notification for added torrent:
Notification for finished torrent:
Related: https://github.com/qbittorrent/qBittorrent/issues/15630

Migrate away from deprecated API on MacOS

---

src/webui/www/private/views/preferences.html

Cryptographically strong random number generators are generally preferred over others.

WebUI: use secure random number generator for generating random port

---

src/base/search/searchpluginmanager.cpp

This saves a few URL redirections. And avoids potential issues related to Cloudflare protections/blockages on qbt domain.
Closes #22990.

Use source URL for search plugins

---

.github/workflows/ci_macos.yaml

Currently the hardened runtime is enabled for code signing in the github workflow for macOS. However in this thread https://github.com/qbittorrent/qBittorrent/discussions/23041#discussioncomment-13969415 a user had a problem to open the nightly builds from github. Relevant part of the error:
```
Reason: tried: '/private/var/folders/y0/jmsflc717tn_tj2x9d1g3d9w0000gn/T/AppTranslocation/8B53E367-2E0C-42C1-A4D5-6787109EE46E/d/qbittorrent.app/Contents/Frameworks/QtWidgets.framework/Versions/A/QtWidgets' (code signature in '/private/var/folders/y0/jmsflc717tn_tj2x9d1g3d9w0000gn/T/AppTranslocation/8B53E367-2E0C-42C1-A4D5-6787109EE46E/d/qbittorrent.app/Contents/Frameworks/QtWidgets.framework/Versions/A/QtWidgets' not valid for use in process: mapping process and mapped file (non-platform) have …
```

GHA CI: Disable the hardened runtime in the codesigning workflow for macOS

---

WebAPI_Changelog.md
src/webui/api/torrentscontroller.cpp
src/webui/www/private/edittracker.html
src/webui/www/private/scripts/prop-trackers.js

This PR adds the ability to direct modify a tracker's tier from the WebUI. This process is notably different than the GUI, which provides arrows for increasing/decreasing a tracker's tier.
Closes #12233

WebUI: Support editing tracker tier

---

src/webui/www/eslint.config.mjs
src/webui/www/package.json

NPM has a bug that cannot fetch the plugin via git protocol: https://github.com/npm/cli/issues/2610, so fetch a tarball instead.

WebUI: enforce using prefix increment/decrement operators via ESLint

---

src/base/http/requestparser.cpp
src/base/http/requestparser.h
src/base/utils/bytearray.cpp
src/base/utils/bytearray.h
test/testutilsbytearray.cpp

Parse HTTP headers using raw byte arrays instead of strings. This allows us to apply different encodings for different parts.
This change is backward compatible and should not affect any existing operation, so WebAPI version bump is not required.

Improve parsing of HTTP headers 

---

WebAPI_Changelog.md
src/webui/api/torrentscontroller.cpp
src/webui/www/private/scripts/client.js

This allows us to bypass any issues related to non-ascii file names.
Supersedes #23080.

WebAPI: Omit file names in `parseMetadata` response

---

src/webui/www/private/scripts/cache.js
src/webui/www/private/views/confirmdeletion.html
src/webui/www/private/views/preferences.html

We should use modern promise chaining over legacy callbacks wherever possible. This will also make some future async work I'm doing a bit easier.

WebUI: replace callback with promise chaining

---

src/gui/CMakeLists.txt
src/gui/macosstatusitem/itemview.h
src/gui/macosstatusitem/itemview.mm
src/gui/macosstatusitem/statusitem.h
src/gui/macosstatusitem/statusitem.mm
src/gui/mainwindow.cpp
src/gui/mainwindow.h

**Summary**
Implements a native macOS status bar item that displays the qBittorrent icon and provides a minimal menu showing live download and upload rates. This allows quick network activity checks without switching to the app window or relying on the Dock.
**Details**
- Adds `MacUtils::StatusItem` with `ItemView` to initialize a `NSStatusItem` in the system status bar.
- Uses existing `qbittorrent_mac.icns` as the icon.
- Menu updates download and upload rates in real-time using friendly unit formatting.
**Why**
This addresses [feature request #22545 ] to provide a lightweight, always-visible network activity indicator. Many macOS apps with long-running background activity (e.g., Tailwind) prefer a status bar item over a Dock menu

Add status bar menu with DL/UL display on macOS

---

src/webui/api/torrentscontroller.cpp

This TODO has been in the code for 8 years since it was added in #6475 (commit b271fa9f001f96cb0d934918ccbd181d86c8a326). It appears to have been related to the `skipChecking` variable, though what it actually means has been lost over time. Note that both the `savePath` and the `downloadPath` are recursively created if they don't yet exist.

WebAPI: Remove outdated TODO

---

src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/prop-peers.js

The WebUI part of the changes for #23061. Now qBittorrent will display I2P peers in WebUI peers tab.
Fixes the second part of #19794 ("i2p peer list does not show in GUI").

WebUI: add I2P peers to peer list

---

src/base/bittorrent/torrentdescriptor.cpp
src/base/bittorrent/torrentimpl.cpp
src/base/rss/rss_session.cpp

This adds c++23 support. In my testing it works for nox and desktop.
It seems to be an error with Debian Trixie (stable) and Alpine edge. I think this is gcc version related, maybe v14+ 
In Ubuntu Noble you can set c++23 and it won't have an error.
My builds worked here
https://github.com/userdocs/qbittorrent-crossbuild/actions/runs/17349079380/job/49252858311

Fix compilation in C++23 mode

---

src/webui/www/private/addtorrent.html
src/webui/www/private/scripts/dynamicTable.js

Firefox seems to have an issue where svgs loaded via `background-url` are not animated. Loading the svg directly as an `img` fixes this.
Related: #23074

WebUI: Fix add torrent spinner in Firefox

---

src/webui/www/private/scripts/client.js

The FileList type has no `entries()` method. Use the generic function from `Array` instead.
Addresses https://github.com/qbittorrent/qBittorrent/pull/23182#discussion_r2319408410
Closes #23224.

WebUI: fix invalid method

---

src/webui/www/private/views/aboutToolbar.html
src/webui/www/private/views/preferencesToolbar.html

These were missed in 6ac0c5a8b82918120b7db9ec7ef6834ec9ea240d. Also refactor the code a bit.

WebUI: prefer `for` loop over `Array.forEach` method

---

src/app/cmdoptions.cpp

use `class` instead of `struct` for consistency
all objects that extends `Option` in `src/app/cmdoptions.cpp` uses the `class` keyword except `StringOption`
no change in behavior.
makes the `public` in the mean something now in the `StringOption` class

Use class instead of struct

---

src/webui/www/private/views/rss.html

`same-origin`:
> Sends the full URL (stripped of parameters) for same-origin requests. Cross-origin requests will contain no referrer header.
This would be helpful for 3rd party WebUI that were forked from the official one. The official WebUI is not affected by this change since the request is currently blocked by CSP.

WebUI: don't send HTTP Referer header to other servers

---

src/base/preferences.cpp
src/base/preferences.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/gui/properties/propertieswidget.cpp
src/gui/torrentcontentwidget.cpp
src/gui/torrentcontentwidget.h

Multi-selection for default LMB action, as before 5.1 update
Adds option to select grab as the default behavior,
for users who don't have the Alt key available.
Holding the Alt key toggles between grab/multi-selection.
Closes https://github.com/qbittorrent/qBittorrent/issues/22686

Restore default drag behavior in Torrent Content widget

---

src/gui/mainwindow.ui
src/webui/www/private/index.html

**Summary**: 
This PR adds a "Torrent Creator" button to the toolbar in qBittorrent, placing it next to existing buttons for improved accessibility.
**Problem**: 
The torrent creator functionality exists but is currently only accessible via the Tools dropdown menu "Torrent Creator" or shortcut (CTRL+N), making it less convenient for quick access without menu navigation. Due to it being a frequently used action, there have been requests to add it to the quick access toolbar, such as here: https://github.com/qbittorrent/qBittorrent/issues/21489.
**Solution**: 
- Added the torrent creator button to the main toolbar, positioned next to the existing buttons.
- The button triggers the existing torrent creator dialog.
- Updated the toolbar layout to ensure consistent spacing and alignment. …

Add Torrent Creator toolbar button

---

src/gui/rss/articlelistwidget.cpp
src/gui/rss/articlelistwidget.h
src/gui/rss/rsswidget.cpp
src/gui/rss/rsswidget.h
src/webui/www/private/views/rss.html

Adds a search bar for RSS items. It supports plain text search (no regex), applies only to the selected tab, updates results as you type, and shows all items when the field is empty.
GUI
webui
resolves #15538, resolves #22570, resolves #14719, resolves #18444, resolves #18183

Allow to filter RSS by simple string

---

src/base/bittorrent/sessionimpl.cpp

In C++20 `std::views::transform()` followed by `std::views::filter()` has a nasty effect of invoking transformation function twice.
Note that there will be a `std::views::cache_latest()` in C++26 to address this issue.
Ref:
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2760r1.html#cache_last
https://stackoverflow.com/questions/64199664/why-c-ranges-transform-filter-calls-transform-twice-for-values-that-match

Avoid duplicate lookup

---

src/webui/www/private/views/createtorrent.html

|before|after|
|----|----|
|<img width="374" height="252" alt="image" src="https://github.com/user-attachments/assets/ae428222-09df-4f23-ae0b-6c023787cbfb" />|<img width="371" height="235" alt="image" src="https://github.com/user-attachments/assets/432d2c94-88f3-4c1f-8fd6-e19ca87fa605" />|

WebUI: Fix path input label layout in torrent creator
