src/main.cpp
src/properties/propertieswidget.cpp
src/properties/propertieswidget.ui
src/webui/www/public/properties_content.html

s/Pieces size/Piece size/
s/uknown/unknown/
Closes #2367.

Fix few spelling mistakes

---

src/webui/btjson.cpp
src/webui/www/public/scripts/client.js
src/webui/www/public/scripts/contextmenu.js
src/webui/www/public/scripts/dynamicTable.js
src/webui/www/public/scripts/misc.js
src/webui/www/public/transferlist.html

Improvements:
- added functions, which may be used to reorder and hiding columns in torrents table
- new columns can be easily added to torrents table

WebUI: Change torrent model

---

.gitignore
build-aux/compile
build-aux/config.guess
build-aux/config.sub
build-aux/install-sh
build-aux/missing
configure

Add a few things to *.gitignore*, update to latest build-aux scripts, re-bootstrap the *configure* file.

Update build-aux, configure, and .gitignore

---

src/gui/transferlistfilterswidget.cpp

Removes white bar in the labels list. Closes #1151.

---

src/gui/searchengine/nova/engines/piratebay.py
src/gui/searchengine/nova/engines/versions.txt
src/gui/searchengine/nova3/engines/piratebay.py
src/gui/searchengine/nova3/engines/versions.txt

It was rewritten from a scratch.
Py2 and Py3 are identical

[searchengine] Fix piratebay. Closes #2270

---

src/gui/transferlistfilterswidget.cpp
src/gui/transferlistfilterswidget.h

Change "remove empty labels" to "remove unused labels".

---

src/gui/searchengine/nova/engines/kickasstorrents.py
src/gui/searchengine/nova/engines/versions.txt
src/gui/searchengine/nova3/engines/kickasstorrents.py
src/gui/searchengine/nova3/engines/versions.txt

The old domain kickass.so has been seized and seems never will work again.

Updated URL in kickasstorrents search engine

---

src/gui/searchengine/engineselectdlg.cpp

Because of changes in the directory tree. Some info #2541.

Change Update URL for search engines

---

src/core/qtlibtorrent/alertdispatcher.cpp
src/core/qtlibtorrent/alertdispatcher.h
src/core/qtlibtorrent/bandwidthscheduler.h
src/core/qtlibtorrent/filterparserthread.cpp
src/core/qtlibtorrent/filterparserthread.h
src/core/qtlibtorrent/qbtsession.cpp
src/core/qtlibtorrent/qbtsession.h
src/core/qtlibtorrent/qtorrenthandle.cpp
src/core/qtlibtorrent/shutdownconfirm.cpp
src/core/qtlibtorrent/shutdownconfirm.h
src/core/qtlibtorrent/torrentmodel.cpp
src/core/qtlibtorrent/torrentmodel.h
src/core/qtlibtorrent/torrentspeedmonitor.cpp
src/core/qtlibtorrent/torrentspeedmonitor.h
src/core/qtlibtorrent/torrentstatistics.cpp
src/core/qtlibtorrent/torrentstatistics.h
src/core/qtlibtorrent/trackerinfos.h

This is not fully coding style fix according to #2192 but only indentation size changes.
I provide this PR to prevent possible further PR conflicts in cases where some of them contain indentation changes, while others do not.
All other #2192 related changes in these files I'll do during the work on #2433.

Fix indentation size in qtlibtorrent/* files.

---

src/core/http/connection.cpp

The previous code caused a crash in case "gzip" was at the end of the
string with no quality factor (;q=*) specified.

WebUI: Use regular expression to check if gzip is accepted

---

src/core/misc.cpp
src/core/misc.h
src/core/preferences.cpp
src/core/preferences.h
src/core/qtlibtorrent/qbtsession.cpp
src/core/qtlibtorrent/qbtsession.h
src/core/qtlibtorrent/torrentmodel.cpp
src/core/qtlibtorrent/torrentmodel.h
src/gui/mainwindow.cpp
src/gui/properties/propertieswidget.cpp
src/gui/properties/propertieswidget.h
src/gui/properties/trackerlist.cpp
src/gui/properties/trackerlist.h
src/gui/transferlistfilterswidget.cpp
src/gui/transferlistfilterswidget.h
src/gui/transferlistsortmodel.cpp
src/gui/transferlistsortmodel.h
src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h
src/webui/webapplication.cpp

The past few days I am trying to implement a tracker list as per #170. However, I come to some difficult obstacles.
@glassez @pmzqla any idea on the following?
1. **How do I update the list when trackers are added via the webui?**
I am thinking of connecting the webapplication and the mainwindow on the Application class level (signal->slot). Then the mainwindow will forward the signal to the tracker list in the sidepane and in the properties panel.
2. **How the hell do I setup the filter of the transferlist based on trackers?**
I imagine that our custom filter model needs access to the TrackerFiltersList and its QHash that holds the info_hashes per tracker.
An alternative solution would, the TrackerFiltersList will not hold the info-hashes just an int per tracker for counting purposes and …

Tracker list discussion

---

src/searchengine/nova/engines/torrentz.py
src/searchengine/nova/engines/versions.txt
src/searchengine/nova3/engines/torrentz.py
src/searchengine/nova3/engines/versions.txt

demonii is working well but the others are sometimes unresponsive. I added 4 more.

[search engine] Update Torrentz trackers list

---

src/webui/abstractwebapplication.cpp

WebUI: create a new session for each user

---

src/gui/about.ui
src/gui/mainwindow.ui

QtCreator complains it doesn't find icons.qrc.

Fix wrong path in .ui files

---

src/webui/www/private/login.html
src/webui/www/public/scripts/mocha-init.js

Fix #3038. If someone wants to test needs an apache server running with mod_proxy enabled and this configuration:
```
ProxyPass "/qbittorrent/" "http://localhost:8080/"
ProxyPassReverse "/qbittorrent/" "http://localhost:8080/"
```
Access URL: http://127.0.0.1/qbittorrent/

Web UI: Fix login and logout relative URLs. Closes #3038

---

src/searchengine/nova/engines/piratebay.py
src/searchengine/nova/engines/versions.txt
src/searchengine/nova3/engines/piratebay.py
src/searchengine/nova3/engines/versions.txt

The old code doesn't show the complete name if it contains special characters like '&'.
Try to search **"Ratchet & Clank"** (with the double quotes) in the old code and in the new one.

[search engine] Fix thepiratebay engine. Closes #3012

---

src/webui/www/public/scripts/prop-general.js

Web UI: Fix Max connections and Time active in transfer panel. Closes #2993

---

src/webui/prefjson.cpp
src/webui/www/public/preferences_content.html

Web UI: New config - Global maximum number of upload slots. Closes #2997

---

src/searchengine/searchengine.cpp
src/searchengine/searchengine.h
src/searchengine/searchtab.cpp

Fix #764 and also speed up the code. The program used to freeze.

Change width of columns in search tab. Closes #764

---

src/gui/options_imp.cpp

checkStartMinimized moved outside the if condition and some order.

Fix Start Minimized checkbox in Options

---

src/gui/mainwindow.cpp

It should be enough to just delete object as search will be aborted in destructor but i'm bit unsure about closure sequence

Aborting search engine process during closure. Close #2671

---

src/searchengine/nova/helpers.py
src/searchengine/nova3/helpers.py

Set 2 second timeout and handle any possible connection error
Return empty string to engine search in case of connection exception
As per @pmzqla suggestion i'm making separated commit for exception free url_retrieve
@sledgehammer999
It would be good to have it in 3.2.0 :)

[search engine] Exception free url_retrieve

---

src/searchengine/engineselect.ui
src/searchengine/engineselectdlg.cpp

Now it looks like this:
There are many users who open issues saying that the search engines do not work but we can't help because they don't know the installed version (if the plugins are updated or not).

[Search engine] Show the version of search engines

---

src/searchengine/nova/engines/legittorrents.py
src/searchengine/nova/engines/versions.txt
src/searchengine/nova3/engines/legittorrents.py
src/searchengine/nova3/engines/versions.txt

Even if it works just fine. I want to remove deprecated sgmllib's usage from python3.
@ngosang Please review me :)

[search engine] Update Legit Torrent to remove sgmllib

---

src/core/bittorrent/torrenthandle.cpp
src/core/bittorrent/torrenthandle.h

This should fix the problem described here: [#2892 (comment)](https://github.com/qbittorrent/qBittorrent/pull/2892#issuecomment-98361957).
Thanks to @ngosang.

Fix BitTorrent::TorrentHandle class.

---

src/searchengine/engineselect.ui
src/searchengine/engineselectdlg.cpp

This PR is a copy of #2844 but for v3_2_x branch.

[Search engine] Show the version of search engines (v3_2_x)

---

src/core/dnsupdater.cpp
src/core/downloadthread.cpp
src/searchengine/nova/helpers.py
src/searchengine/nova3/helpers.py

This PR is a copy of #3010 but for v3_2_x branch.

Changes in User-Agent (v3_2_x)

---

src/core/fs_utils.cpp
src/core/fs_utils.h
src/searchengine/searchengine.cpp

3_2_x mapping: [search engine] Remove python3 cache during updateNova()

---

src/core/http/requestparser.cpp
src/core/misc.cpp
src/core/qtlibtorrent/qbtsession.cpp
src/gui/rss/rssfeed.cpp

This PR is a copy of #3004 but for v3_2_x branch.

Cppcheck: scope reduction & unused variables (v3_2_x)

---

src/gui/previewselect.cpp

Same as #2958 but for master branch.

Fix potential negative loop bound

---

src/app/main.cpp
src/core/qtlibtorrent/qbtsession.cpp
src/gui/mainwindow.cpp
src/gui/mainwindow.ui
src/gui/options_imp.cpp
src/gui/properties/propertieswidget.cpp
src/gui/properties/trackerlist.cpp
src/gui/rss/cookiesdlg.cpp
src/gui/rss/rss_imp.cpp
src/gui/transferlistfilterswidget.cpp
src/webui/webui.cpp
src/webui/www/private/index.html
src/webui/www/public/download.html
src/webui/www/public/scripts/mocha-init.js

This PR is a copy of #2805 but for v3_2_x branch.

Changes in typography (v3_2_x)

---

src/gui/addnewtorrentdialog.cpp
src/webui/webapplication.cpp

This changes were proposed by @PiotrNawrot in these PRs: #2967, #2970.

Code clean up

---

src/core/preferences.cpp
src/core/preferences.h
src/core/qtlibtorrent/qbtsession.cpp
src/gui/options.ui
src/gui/options_imp.cpp

The default setting for this option is false.

Add checkbox option for IpFilterTrackers, closes #3154.

---

src/gui/mainwindow.cpp
src/gui/mainwindow.h
src/gui/mainwindow.ui

From discussion in PR #2805.
Also added/modified some item's accelerator.
* File
* Edit (untouched):
* View
* Tools
* Help

Revamp menu items

---

src/gui/mainwindow.cpp
src/gui/mainwindow.h
src/gui/mainwindow.ui

Same as #2847 but for v3_2_x branch.

Revamp menu items 

---

src/core/preferences.cpp
src/core/preferences.h
src/core/qtlibtorrent/qbtsession.cpp
src/gui/options.ui
src/gui/options_imp.cpp

Same as #3167 but for v3_2_x branch.

Add checkbox option for IpFilterTrackers.

---

src/core/preferences.cpp
src/gui/options_imp.cpp

Otherwise it doesn't build on FreeBSD.

Added missing include <cstdlib>

---

src/core/bittorrent/torrenthandle.cpp

Same as #3099 but for master branch.

 Improve ratio calculation formula

---

src/gui/mainwindow.cpp

Fix crash when cancel open file dialog.

---

src/core/misc.cpp
src/core/qtlibtorrent/alertdispatcher.cpp

Same as #2719 but for v3_2_x branch.

Fix potential out-of-bound access in misc::friendlyUnit()

---

src/core/misc.cpp
src/core/misc.h
src/gui/properties/propertieswidget.cpp
src/gui/properties/propertieswidget.ui

Same as #3078 but for v3_2_x branch.

Revamp general tab info

---

src/core/bittorrent/private/sessionprivate.h
src/core/bittorrent/session.cpp
src/core/bittorrent/session.h
src/core/bittorrent/torrenthandle.cpp
src/core/bittorrent/torrenthandle.h
src/gui/mainwindow.cpp
src/gui/properties/propertieswidget.h
src/gui/torrentmodel.cpp
src/gui/torrentmodel.h
src/gui/transferlistdelegate.cpp
src/gui/transferlistfilterswidget.cpp
src/gui/transferlistfilterswidget.h
src/gui/transferlistsortmodel.cpp
src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h

Use BitTorrent::TorrentHandle as TorrentModel item directly.

Improve TorrentModel class (Issue #2433).

---

src/gui/rss/rss_imp.cpp

Fix add torrent dialog is not shown (#2892 regression).

---

src/searchengine/nova/helpers.py
src/searchengine/nova/nova2.py
src/searchengine/nova/nova2dl.py
src/searchengine/nova/novaprinter.py
src/searchengine/nova3/helpers.py
src/searchengine/nova3/nova2.py
src/searchengine/nova3/nova2dl.py
src/searchengine/nova3/novaprinter.py

Fix this https://github.com/qbittorrent/qBittorrent/pull/2550#issuecomment-111191019 bug.

[search engine] Fix novaprinter.py version number

---

src/searchengine/nova/engines/kickasstorrents.py
src/searchengine/nova/engines/versions.txt
src/searchengine/nova3/engines/kickasstorrents.py
src/searchengine/nova3/engines/versions.txt

* Indentation changed.
* Fix  redirecting to the description page without https https://github.com/qbittorrent/qBittorrent/pull/3311#issuecomment-116029186

[search engine] Update KickassTorrents

---

src/searchengine/nova/engines/btdigg.py
src/searchengine/nova/engines/versions.txt
src/searchengine/nova3/engines/btdigg.py
src/searchengine/nova3/engines/versions.txt

Now returns more accurate results. See https://github.com/qbittorrent/qBittorrent/pull/3308#issuecomment-116014346

[search engine] Update BTDigg

---

src/searchengine/nova/engines/torrentz.py
src/searchengine/nova/engines/versions.txt
src/searchengine/nova3/engines/torrentz.py
src/searchengine/nova3/engines/versions.txt

* Replace offline tracker with a new one
* Fix a little bug

[search engine] Update Torrentz

---

src/core/utils/misc.cpp
src/gui/properties/propertieswidget.cpp
src/gui/properties/propertieswidget.ui

As discussed in PR #3078.
Screenshot:

Reorder layout in information box

---

src/searchengine/nova/engines/extratorrent.py
src/searchengine/nova/engines/versions.txt
src/searchengine/nova3/engines/extratorrent.py
src/searchengine/nova3/engines/versions.txt

Now returns more accurate results.

[search engine] Update ExtraTorrent

---

src/webui/prefjson.cpp
src/webui/webapplication.cpp
src/webui/www/public/preferences_content.html

Added these options:
* Copy .torrent files for finished downloads to: (Downloads tab)
* Use different port on each startup (Connection tab)
* Disable connections not supported by proxies (Connection tab)
* Apply to trackers (Connection tab)
* Share Ratio Limiting (BitTorrent tab)

[Web UI] Add new options

---

src/gui/mainwindow.cpp

Capitalize menu item

---

.travis.yml

Changes/Improvements:
* Switch to libtorrent git repository (faster repo fetch)
* Reduce clone depth to 1
* Rename variable
* Cleanup comments
Fixed:
* Fix missing configure argument when compiling for coverity scan
Note that there is no significant nor minor improvement on travis building speed :(
The only saving is system resource.

Travis script update

---

src/webui/btjson.cpp
src/webui/btjson.h
src/webui/webapplication.cpp
src/webui/webapplication.h
src/webui/webui.qrc
src/webui/www/public/css/style.css
src/webui/www/public/properties.html
src/webui/www/public/properties_content.html
src/webui/www/public/scripts/client.js
src/webui/www/public/scripts/prop-files.js
src/webui/www/public/scripts/prop-general.js
src/webui/www/public/scripts/prop-trackers.js
src/webui/www/public/scripts/prop-webseeds.js

At this moment is just to see the info, you can't edit or add new web seeds.
@pmzqla If this is merged you have to update the api.
```
var url = 'query/propertiesWebSeeds/' + current_hash;
/**
* Returns the web seeds for a torrent in JSON format.
*
* The return value is a JSON-formatted list of dictionaries.
* The dictionary keys are:
*   - "url": Web seed URL
*/
```

[Web UI] Add Web Seeds (HTTP Sources) tab

---

src/app/qtsingleapplication/qtlocalpeer.cpp

Fixes building with Qt 5.5.0-beta.

Add missing QDataStream include

---

src/gui/transferlistsortmodel.cpp

Same as #2966.
Related issue: #2965.

Fix sorting torrents by ETA

---

src/core/bittorrent/torrenthandle.cpp
src/core/bittorrent/torrenthandle.h
src/gui/torrentmodel.cpp
src/gui/transferlistdelegate.cpp

It requires to make changes in the WebUI to handle all torrent states after this PR will be merged.

Fix missing torrent states. Closes #3302.

---

src/webui/www/public/scripts/dynamicTable.js

Fix missing torrent states added in #3329.
Fix sidebar filters (adding forceUP & forceDL)

[Web UI] Fix missing torrent states.

---

src/searchengine/nova/engines/torrentz.py
src/searchengine/nova/engines/versions.txt
src/searchengine/nova3/engines/torrentz.py
src/searchengine/nova3/engines/versions.txt

Related https://github.com/qbittorrent/qBittorrent/pull/3306#issuecomment-118610372

[search engine] Fix Python 2 implementation of Torrentz

---

src/gui/transferlistwidget.cpp

This is how the problem was fixed in master branch.

Fix torrent renaming. Closes #3398

---

src/webui/webapplication.cpp

Code from https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/mainwindow.cpp#L1238

[Web UI] Torrent download from hash. Closes #1173

---

src/core/bittorrent/torrenthandle.cpp

Talk here https://github.com/qbittorrent/qBittorrent/pull/3348#issuecomment-118437871

Add Force Seeding state to Completed filter

---

src/webui/prefjson.cpp
src/webui/webapplication.cpp
src/webui/www/public/preferences_content.html

**API changes:** Added **web_ui_upnp** preference (no need to change API version, just update documentation) https://github.com/qbittorrent/qBittorrent/pull/3040#issuecomment-107954174

[Web UI] New option Web UI port UPNP. Closes #3358

---

src/searchengine/searchengine.cpp
src/searchengine/searchengine.h
src/searchengine/searchtab.cpp
src/searchengine/searchtab.h

#2859 leads to idea that it would be good to align Search status with current tab.
Draft commit for that

Search status tab

---

src/gui/properties/trackerlist.cpp

Some changes around `forceDHTAnnounce()`
Please tell me if anything is not reasonable.

DHT announce

---

src/webui/webapplication.cpp
src/webui/www/public/properties_content.html

[Web UI] Fix empty trackers addition

---

src/webui/www/public/scripts/dynamicTable.js

See https://github.com/qbittorrent/qBittorrent/pull/3410#issuecomment-121087500

[Web UI] Fix sort by queue number

---

src/webui/www/public/scripts/client.js
src/webui/www/public/scripts/dynamicTable.js

**10 torrents**
Before:
1) This comparison https://github.com/qbittorrent/qBittorrent/blob/master/src/webui/www/public/scripts/dynamicTable.js#L465 is done 247 times * 10 torrents = 2470 times / second.
2) Updates all rows and columns in the transfer list.
3) Time of execution (average) of this call https://github.com/qbittorrent/qBittorrent/blob/master/src/webui/www/public/scripts/client.js#L177 **30 ms.** (it's called each second so it's not negligible)
After:
1) 11 times * 10 torrents = 110 times / second.
2) Only updates changed values. Fixed in this line https://github.com/qbittorrent/qBittorrent/pull/3467/files#diff-1d55956245e67ad3c0b3eb4c48509ecdR465
3) **5 ms.**
**100 torrents**
Before:
1) 247 times * 100 torrents = 24700 times / second.
2) Updates all rows and columns in the …

[Web UI] Massive increase in performance.

---

src/core/bittorrent/session.cpp
src/core/bittorrent/session.h
src/gui/statusbar.cpp

Also fix Bandwidth Scheduler doesn't disable when user change speed limit mode via WebUI.

Fix Bandwidth Scheduler. Closes #3376.

---

src/app/application.cpp
src/gui/options.ui
src/gui/options_imp.cpp

Old:
New: 
For anyone is interested, please help testing.
I'll squash commits and add the "close #nums" after review.

Add more "Run External Program" parameters 

---

.gitignore
winconf-mingw.pri
winconf-msvc.pri
winconf.pri

These are the changes I made when compiling on windows.
I think it would be nice if these could be merged upstream.

Compilation on windows

---

.travis.yml

Same as #3512 but for v3_2_x branch.

Migrate TravisCI to container-based infrastructure

---

src/core/net/private/geoipdatabase.cpp

Related to [#3488 (Comment)](https://github.com/qbittorrent/qBittorrent/pull/3488#issuecomment-126178868).

Fix strict-aliasing warning.

---

src/gui/mainwindow.cpp

@sledgehammer999 , please cherry pick into V3_2_x branch too.

Add back "qBittorrent" in program updater title, closes #3549.

---

INSTALL

Fix minimum libtorrent-rasterbar version

---

src/core/misc.cpp
src/core/misc.h
src/gui/properties/propertieswidget.cpp
src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h

Also, add the support for Nautilus (Gnome 3), Caja and Nemo.
Backport of #2544.

Select the file of single file torrents when opening destination folder

---

src/core/net/downloadhandler.cpp

DownloadManager: fix downloads after a redirection

---

src/core/utils/fs.cpp

This should be the correct default path for windows vista (and above), but not for windows xp (which MS doesn't support anymore...)

Fix wrong default download directory in Windows. Closes #2625.

---

src/core/preferences.cpp
src/core/preferences.h
src/core/qtlibtorrent/qbtsession.cpp
src/gui/advancedsettings.h
src/gui/options.ui
src/gui/options_imp.cpp

Same as #3481, but for v3_2_x branch.

Move option "Ignore transfer limits on local network" to Speed page

---

src/core/fs_utils.cpp

Same as #2633 but for v3_2_x branch.

Fix wrong default download directory in Windows

---

src/core/bittorrent/session.cpp
src/core/net/downloadmanager.cpp
src/core/preferences.cpp
src/core/preferences.h
src/gui/options.ui
src/gui/options_imp.cpp

Add an option to allow the use of proxies only for torrents

---

src/core/bittorrent/session.cpp
src/core/bittorrent/session.h

Hopefully it closes #475 and #3072
It was functionally tested with "physical" interfaces on a virtual machine and also with vpn software, on Ubuntu 14.

Interface bind fixes

---

src/gui/rss/rss_imp.cpp

Closes #997, #2152, #2461, #3718, #3747, #3766, #3806, #3814, #3829 and #3846.

Fix RSS crash when deleting RSS feeds. Closes #3846

---

src/core/misc.cpp
src/core/misc.h
src/gui/rss/automatedrssdownloader.cpp

Same as #3165 but for v3_2_x branch.

Sort labels in RSS Downloader dialog

---

dist/windows/installer-translations/german.nsi

The letter "p" was missing in "Dateiverknüpfung" in line 47 & 49

[german.nsi] Added letter "p"

---

src/core/utils/misc.cpp

@sledgehammer999 Could be backported to v3.2.4.

Fix Konqueror detection in Plasma (KDE5)

---

src/gui/properties/pieceavailabilitybar.cpp
src/gui/properties/pieceavailabilitybar.h

I suspect the allocation sometimes fail, causing the crash in #3877.

Fix potential crash when memory allocation failed. Closes #3877.

---

src/core/bittorrent/private/torrenthandleprivate.h
src/core/bittorrent/session.cpp
src/core/bittorrent/torrenthandle.cpp
src/core/bittorrent/torrenthandle.h

Reimplement old 'Append label to save path' behavior.

Fix 'Append label to save path'. Closes #3495.

---

src/webui/www/private/index.html
src/webui/www/public/addtrackers.html
src/webui/www/public/confirmdeletion.html
src/webui/www/public/scripts/mocha-init.js
src/webui/www/public/transferlist.html

[Web UI] Code cleanup and little change in contextual menu

---

src/core/bittorrent/session.cpp
src/core/bittorrent/session.h
src/core/preferences.cpp
src/core/preferences.h
src/gui/options.ui
src/gui/options_imp.cpp

This option does not apply to private torrents.

Automatically add trackers to new downloads. Closes #262

---

src/webui/btjson.cpp
src/webui/prefjson.cpp
src/webui/webapplication.cpp
src/webui/webapplication.h
src/webui/webui.qrc
src/webui/www/private/index.html
src/webui/www/public/filters.html
src/webui/www/public/newlabel.html
src/webui/www/public/scripts/client.js
src/webui/www/public/scripts/dynamicTable.js
src/webui/www/public/scripts/mocha-init.js

**Labels can't be removed but this PR is ready to merge.**
The first 2 commits are from #2558. I rebased and slightly modified the commits but whole credit to Felipe Barriga Richard.
The 3rd commit is entirely mine and fixes many problems.
**Remaining things:**
* ~~Sort labels in sidebar and contextual menu.~~
* It's not possible to delete labels from WebUI.
* ~~When you add or delete a label in the GUI the WebUI is not updated.~~
* ~~When you delete a torrent in the GUI the WebUI is not updated.~~
* ~~Improve New label dialog.~~
* ~~Change API to allow set one label in several torrents in one request and send only the label not the object.~~
* ~~Improve sidebar update performance.~~
**Screenshots:**

[Web UI] Labels implementation

---

src/searchengine/nova/engines/demonoid.py
src/searchengine/nova/engines/extratorrent.py
src/searchengine/nova/engines/kickasstorrents.py
src/searchengine/nova/engines/mininova.py
src/searchengine/nova/engines/piratebay.py
src/searchengine/nova/engines/torrentz.py
src/searchengine/nova3/engines/demonoid.py
src/searchengine/nova3/engines/extratorrent.py
src/searchengine/nova3/engines/kickasstorrents.py
src/searchengine/nova3/engines/mininova.py
src/searchengine/nova3/engines/piratebay.py
src/searchengine/nova3/engines/torrentz.py

I'm receiving annoying messages in this email account.
@sledgehammer999 I didn't change the plugins version because it isn't necessary to update. You don't have to include this commit in the log.

Change personal email

---

src/gui/properties/speedplotview.cpp

Fix confirmation: https://github.com/qbittorrent/qBittorrent/issues/4134#issuecomment-157643161

Fix Speed graph legend is illegible on dark background. Closes #4134.

---

src/webui/www/public/css/dynamicTable.css
src/webui/www/public/css/style.css

The selected color was little bit too close to the progress bar color.

WebUI: Change selected color

---

CODING_GUIDELINES.md

Added missing (but actually used) rules.
Also added some rules which are required due to c++11 support.

Improve CODING_GUIDELINES.md.

---

src/core/preferences.cpp
src/core/preferences.h
src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.ui

"Set as default label" option

---

src/gui/lineedit/src/lineedit.cpp
src/gui/lineedit/src/lineedit.h
src/searchengine/searchengine.cpp

Qt5 supports native ClearButton in QLineEdit.
Also 
Old:
New (Native):

Use QLineEdit built-in ClearButton

---

src/gui/advancedsettings.h
src/gui/properties/propertieswidget.cpp

* "0: Disabled" is ambiguous, using "0: Unlimited" is better.
* Was showing "(-1 max)", correct should be "(∞ max)"

Misc fixes

---

qm_gen.pri

Fix lrelease version due to the default Qt5 build

---

src/gui/torrentcontentmodel.cpp
src/webui/www/public/properties_content.html

Rename `Priority` to `Download Priority`. As mentioned in: https://github.com/qbittorrent/qBittorrent/issues/4520#issuecomment-169882945.
Before: ![old](https://cloud.githubusercontent.com/assets/9395168/12199941/d3106af4-b656-11e5-8223-571c457bd263.png)
After: ![new](https://cloud.githubusercontent.com/assets/9395168/12199942/d34e1c8c-b656-11e5-9def-526befaf3b2a.png)

Rename column header

---

src/webui/www/public/preferences_content.html

Updated parameters for external program at the end of torrent download in WebUi. Now they are equal to #3457

Update webui run program parameters

---

src/base/bittorrent/session.cpp

STRONGLY RECOMMENDED for v3.3.2!

[IMPORTANT] Fix loading corrupted .fastresume file

---

src/searchengine/nova/engines/piratebay.py
src/searchengine/nova/engines/versions.txt
src/searchengine/nova3/engines/piratebay.py
src/searchengine/nova3/engines/versions.txt

.ms domain is suspended.
https://torrentfreak.com/registry-suspends-pirate-bays-new-ms-domain-name-160114/

[search engine] Update PirateBay plugin.

---

src/gui/properties/peerlistwidget.cpp

I just copy pasted from trackerlist (tested ofc). No idea if it can be
done differently.
First pull request, hope i didn't mess something.

Unlock the first column in peerlist too

---

src/gui/options_imp.cpp
src/gui/options_imp.h
src/webui/extra_translations.h
src/webui/www/public/preferences_content.html

Default username: admin (unchanged)
Min user length: 3 characters
Default password: adminadmin (unchanged)
Min password length: 6 characters

Check WebUI username and password length. Closes #4191

---

src/webui/www/public/css/style.css
src/webui/www/public/filters.html

[Web UI] Minor changes in CSS styles

---

src/base/preferences.cpp
src/base/preferences.h
src/gui/options.ui
src/gui/options_imp.cpp
src/gui/torrentmodel.cpp
src/gui/transferlistdelegate.cpp
src/gui/transferlistdelegate.h

~~Don't merge yet!!~~
Before:
After:
Feedback are welcome!

Hide zero & infinity values

---

dist/windows/qt.conf
src/app/application.cpp
src/gui/about.qrc
src/gui/about.ui
src/gui/about_imp.h
src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.h
src/gui/addnewtorrentdialog.ui
src/gui/advancedsettings.cpp
src/gui/options.ui
src/gui/options_imp.cpp
src/gui/statusbar.cpp
src/gui/statusbar.h

Fix bugs in #2963.
Old | New
------------- | -------------
[add_torrent_old_1](https://cloud.githubusercontent.com/assets/9395168/11587237/fc0daa08-9ab2-11e5-965e-1096196bffd4.png) | [add_torrent_new_1](https://cloud.githubusercontent.com/assets/9395168/11587144/5f9222da-9ab2-11e5-9c21-06e57711a842.png)
Old | New
------------- | -------------
[adv_opt_old_1](https://cloud.githubusercontent.com/assets/9395168/11587236/fc0b4786-9ab2-11e5-8f71-774aec904688.png) | [adv_opt_new_1](https://cloud.githubusercontent.com/assets/9395168/11587145/5f9812a8-9ab2-11e5-9aef-ebc17ddca16c.png)
Old | New
------------- | -------------
[opt_old_1](https://cloud.githubusercontent.com/assets/9395168/11587278/343d1652-9ab3-11e5-8570-9f02cad1928e.png) | [opt_new_1](https://cloud.githubusercontent.com/assets/939516 …

Fix incorrectly displayed UI elements on Windows 

---

src/base/net/smtp.cpp
src/base/net/smtp.h

Fix malformed date header in email.

---

src/searchengine/nova/engines/demonoid.py
src/searchengine/nova/engines/extratorrent.py
src/searchengine/nova/engines/mininova.py
src/searchengine/nova/engines/piratebay.py
src/searchengine/nova/engines/versions.txt
src/searchengine/nova3/engines/demonoid.py
src/searchengine/nova3/engines/extratorrent.py
src/searchengine/nova3/engines/mininova.py
src/searchengine/nova3/engines/piratebay.py
src/searchengine/nova3/engines/versions.txt

1. Switch to retrieve_url instead of low-level HTTPConnection module usage
@ngosang Please review
I originally used it as effective means to utilize connection for multiple requests, but i think it is not worth it at all.
Besides it will simplify code

[search engine] Align search engine url getting mechanism. Closes #4778

---

src/gui/addnewtorrentdialog.ui

Put comment_lbl in QScrollArea.

---

src/base/CMakeLists.txt

Obvious fix for the new source files.

fix cmake build

---

src/gui/properties/proplistdelegate.cpp
src/gui/properties/proplistdelegate.h
src/gui/torrentcontentmodel.cpp
src/gui/torrentcontentmodelfile.cpp
src/gui/torrentcontentmodelfolder.cpp
src/gui/torrentcontentmodelitem.cpp
src/gui/torrentcontentmodelitem.h

I like to be able to see how much data is remaining for each piece of a torrent.

add a remaining column to the torrent content model

---

src/gui/options.ui

Fix tab icons messed up.

---

src/gui/statusbar.cpp
src/gui/statusbar.h
src/webui/www/private/index.html
src/webui/www/public/css/Layout.css
src/webui/www/public/scripts/client.js

Status bar befor:
Status bar after:

Change appearance of speed labels in status bar

---

.travis.yml
src/base/utils/misc.cpp

* Hmmm, linux build time wasn't that bad as I imagined, probably due to powerful Google Compute Engine  (GCE)...
* The exotic `- |` syntax is to treat the follow string (`if` block) as a whole (preserves newline chars), so I can put comments in the `if` block

TravisCI: switch to Trusty image

---

src/webui/www/public/preferences_content.html

Missing string from this PR #4849.

[WebUI] Add missing string

---

src/base/utils/misc.cpp

Fix "Open Containing Folder" for caja

---

src/searchengine.qrc

Sorry, I forgot this in #5012.

[Search engine] Added TorLock search engine. Fix #5012

---

src/gui/executionlog.ui
src/gui/rss/rss.ui
src/gui/rss/rsssettingsdlg.ui

Split out from #4995.
Removed border around Execution Log:
[old](https://cloud.githubusercontent.com/assets/9395168/13978483/625a93d4-f10c-11e5-80c9-bdca43e3569d.png)
[new](https://cloud.githubusercontent.com/assets/9395168/13978480/6254fffa-f10c-11e5-8c1c-26c65089eeeb.png)
Minor tweak rss settings:
[old](https://cloud.githubusercontent.com/assets/9395168/13978482/62588076-f10c-11e5-90e5-aa9056ce5889.png)
[new](https://cloud.githubusercontent.com/assets/9395168/13978481/625838f0-f10c-11e5-8f02-e5a345ed950f.png)

Minor UI tweaks 

---

dist/windows/qt.conf

Declare ourselves as a Non DPI–aware app.
Tested with Qt 5.6.

More DPI changes

---

src/gui/options.ui

Fix uic warnings. Closes #5056

---

src/gui/transferlistdelegate.cpp
src/gui/transferlistdelegate.h

Fix for: https://github.com/qbittorrent/qBittorrent/pull/4253#issuecomment-205037938 & https://github.com/qbittorrent/qBittorrent/pull/4253#issuecomment-205225857
Also works for git master, so it's safe to merge IMO.
I only tested in linux, please test in Windows.

Improve TransferListDelegate::sizeHint

---

src/gui/options_imp.cpp

Old: ![old](https://cloud.githubusercontent.com/assets/9395168/14471353/c557ddba-0120-11e6-8422-d0dea2dbc739.png)
New: ![new](https://cloud.githubusercontent.com/assets/9395168/14471331/ac8f9fde-0120-11e6-992d-dffa8de26f27.png)

Fix long text clipping. Closes #5091.

---

src/gui/properties/speedplotview.cpp
src/gui/properties/speedplotview.h
src/gui/properties/speedwidget.cpp

Two changes:
* Replace QQueue by boost::circular_buffer
* Reduce number of points to draw (join points with equal Х coordinate)
Need testing.

SpeedPlotView: speedup

---

src/base/searchengine.cpp
src/base/searchengine.h
src/gui/search/pluginselectdlg.ui
src/gui/search/pluginsourcedlg.ui
src/gui/search/searchwidget.cpp
src/gui/search/searchwidget.h
src/gui/search/searchwidget.ui

Match combobox height to button height:
[search](https://cloud.githubusercontent.com/assets/9395168/13978564/11a6478e-f10d-11e5-8922-a76b9e50fe14.png)
Sort & rename categories & plugins entries:
[categories](https://cloud.githubusercontent.com/assets/9395168/13978485/625ae96a-f10c-11e5-9a8b-f3c6ec61cc37.png)
[plugins](https://cloud.githubusercontent.com/assets/9395168/13978484/625ad3b2-f10c-11e5-8606-acdc054b92a1.png)

Search UI tweaks

---

src/webui/webapplication.cpp
src/webui/webapplication.h
src/webui/www/private/index.html
src/webui/www/public/css/style.css
src/webui/www/public/filters.html
src/webui/www/public/newcategory.html
src/webui/www/public/scripts/client.js
src/webui/www/public/scripts/contextmenu.js
src/webui/www/public/scripts/dynamicTable.js
src/webui/www/public/scripts/mocha-init.js
src/webui/www/public/transferlist.html

WebUI: Implement labels filter context menu

---

src/gui/statsdialog.cpp
src/gui/statsdialog.ui

Minor change in Stats dialog

---

src/gui/rss/rss.ui

Fix Update all button height in RSS tab

---

CMakeLists.txt
cmake/Modules/FindLibtorrentRasterbar.cmake
src/CMakeLists.txt
src/base/CMakeLists.txt

Cmake: clean cmake files

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/gui/mainwindow.cpp
src/gui/mainwindow.h

@glassez I think I found the simplest name for the new signal requiring the simplest source modifications.
If no good objections I would like to push it to master.

Don't show added torrent notification during startup.

---

src/base/settingsstorage.cpp

1. Extract "transaction" support for QSettings into separate class
TransactionalSettings.
2. Define macrto with explicit name for the case when this "transaction"
support is needed.
3. A bit optimize QHash <-> QSettings copying: replace assign with
insert() and remove repetitive key lookups.
4. In save() check dirty status before getting the lock too.
The changes from items 1 and 2 make text more structured and the logic of the SettingsStorage class gets separated from the implementation-level task of guarding the serialized settings. The changes in 3 and 4 do not make the app much faster, but neither make any harm to the code readability.

refactor SettingsStorage class

---

src/base/scanfoldersmodel.cpp
src/gui/options.ui
src/gui/options_imp.cpp
src/gui/properties/peerlistwidget.cpp
src/gui/scanfoldersdelegate.cpp

* "Auto download torrents" in Options:
* The default download location changed from "monitored folders" to "default save location"
* Improved wordings
* screenshots: [old](https://cloud.githubusercontent.com/assets/9395168/15266982/72b6891e-19e7-11e6-9ee2-4dffde210625.png), [new](https://cloud.githubusercontent.com/assets/9395168/15266983/72f26a42-19e7-11e6-9b6b-978e990287a0.png)
* Right click menu in peers list:
* screenshots:[old](https://cloud.githubusercontent.com/assets/9395168/15266984/72f859d4-19e7-11e6-92b4-e6589a89e968.png), [new](https://cloud.githubusercontent.com/assets/9395168/15266985/72f9907e-19e7-11e6-9f0b-9a9a3121880e.png)

Improve wordings

---

src/base/scanfoldersmodel.cpp
src/base/scanfoldersmodel.h
src/gui/options_imp.cpp
src/gui/scanfoldersdelegate.cpp

A fixup PR for #5251. 
* Improve error messages for "Auto download torrents"
* Add lookup function to get PathType display names
* Cleanup headers & Code formatting

Improve wordings 2

---

src/webui/prefjson.cpp
src/webui/www/public/preferences_content.html

Implements #262 in the WebUI. No need to update API minor version.

[WebUI] Expose Add trackers feature

---

src/gui/search/searchtab.cpp
src/gui/search/searchtab.h

As usual with a dark color theme, the default color here does not look good.

Use QPalette::LinkVisited color for downloaded items in search results

---

src/searchengine/nova/engines/piratebay.py
src/searchengine/nova/engines/versions.txt
src/searchengine/nova3/engines/piratebay.py
src/searchengine/nova3/engines/versions.txt

https://torrentfreak.com/pirate-bays-domain-shuffle-come-full-circle-160520/

[Search engine] Update PirateBay

---

src/searchengine/nova/engines/btdigg.py
src/searchengine/nova/engines/demonoid.py
src/searchengine/nova/engines/torrentreactor.py
src/searchengine/nova/engines/versions.txt
src/searchengine/nova3/engines/btdigg.py
src/searchengine/nova3/engines/demonoid.py
src/searchengine/nova3/engines/torrentreactor.py
src/searchengine/nova3/engines/versions.txt

[search engine] Remove filters from Torrentreactor, BTDigg and Demonoid

---

src/webui/btjson.cpp

Show type name in btjson.cpp@processMap assert

---

src/gui/mainwindow.cpp
src/gui/properties/peerlistwidget.cpp
src/gui/properties/propertieswidget.cpp
src/gui/properties/trackerlist.cpp
src/gui/rss/automatedrssdownloader.cpp
src/gui/rss/rss_imp.cpp

Mappings: http://doc.qt.io/qt-4.8/qkeysequence.html#standard-shortcuts

Use "Standard Shortcuts" defined by Qt whenever possible.

---

.travis.yml

I wish the homebrew guys didn't break it so often and the travis guys updated their images more frequently.
(here to test the build before merging in master)

Fix travis again.

---

src/searchengine/nova/engines/extratorrent.py
src/searchengine/nova/engines/versions.txt
src/searchengine/nova3/engines/extratorrent.py
src/searchengine/nova3/engines/versions.txt

Fixed https://github.com/qbittorrent/qBittorrent/issues/5736
Tested for both python2 and python3.

fixed extratorrent search not working v.3.3.7 #5736

---

src/gui/mainwindow.cpp

I can't reproduce the crash, but the code is wrong.

Fix tray icon crash

---

src/searchengine/nova/engines/extratorrent.py
src/searchengine/nova/engines/versions.txt
src/searchengine/nova3/engines/extratorrent.py
src/searchengine/nova3/engines/versions.txt

Fix extratorrent searchengine. Closes #5773

---

src/webui/qjson/json_parser.cc
src/webui/qjson/json_scanner.cc
src/webui/qjson/parser.cpp
src/webui/qjson/parser_p.h
src/webui/qjson/serializer.cpp

Upstream URL: https://github.com/flavio/qjson
This only matter when building with Qt4.

QJson: update to latest git version

---

src/base/bittorrent/private/filterparserthread.cpp
src/base/bittorrent/private/filterparserthread.h
src/gui/properties/propertieswidget.cpp
src/gui/rss/feedlistwidget.cpp
src/gui/transferlistsortmodel.cpp

I check qBittorrent by new release of PVS-Studio for Linux, some fixes and improvements below

Fixes and improvements after check by PVS-Studio

---

src/gui/properties/peerlistwidget.cpp
src/gui/properties/peerlistwidget.h
src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h

Only for TransferListWidget, PeerListWidget

Horizontal scroll

---

src/base/CMakeLists.txt

Fix CMake compilation error.

---

src/base/preferences.cpp
src/base/preferences.h
src/gui/rss/rss.ui
src/gui/rss/rss_imp.cpp

screenshot: ![pic](https://cloud.githubusercontent.com/assets/9395168/20177753/50601ef4-a789-11e6-9cb1-2925989981aa.png)

Change RSS view layout to horizontal

---

src/base/net/geoipmanager.cpp
src/base/net/smtp.cpp
src/gui/optionsdlg.cpp
src/gui/previewlistdelegate.h
src/gui/properties/peerlistdelegate.h
src/gui/properties/proplistdelegate.cpp
src/gui/search/searchlistdelegate.cpp
src/gui/transferlistdelegate.cpp

This take care of most warnings on macOS (TravisCI).

Fix warnings on macOS

---

src/gui/mainwindow.cpp
src/gui/mainwindow.ui

Make resume/pause menu items clickable. Closes #6040

---

src/base/bittorrent/session.cpp

The bug seems to be fixed in version 5.7.1.

Set upper version limit for QTBUG-52633

---

src/gui/mainwindow.cpp
src/webui/www/public/css/dynamicTable.css

* Fix download & upload icon too large in systray on linux. Closes #6233.
* Fix statusIcon too large. Closes #6228.

Fix icon issues

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/base/bittorrent/torrenthandle.cpp
src/base/bittorrent/torrenthandle.h

Two fixes for resume files, which are likely to be needed in any case.

Resume fixes

---

src/base/utils/misc.cpp

The warning can be seen at: https://travis-ci.org/qbittorrent/qBittorrent/jobs/186764572#L881
I reordered & simplified the #ifdef blocks & expression, didn't touch the internals.

Fix compile warning: unused parameter ‘action’

---

src/gui/optionsdlg.ui

Give more meaningful names to tab pages

Clarify options tab page objects names

---

src/app/application.cpp
src/base/http/requestparser.cpp
src/base/net/downloadhandler.cpp
src/base/utils/fs.cpp
src/base/utils/fs.h
src/gui/search/pluginselectdlg.cpp
src/gui/search/searchwidget.cpp
src/webui/abstractwebapplication.cpp

Put temp files in .qBittorrent directory

---

.travis.yml

Put `allow_failures` in the correct place.

Allow some Mac jobs to fail

---

src/gui/bandwidth_limit.ui
src/gui/speedlimitdlg.cpp
src/gui/transferlistwidget.cpp

* Code rewrite, no behavior change
* Speedlimitdlg: raise slider default value to 10000

Speedlimitdlg: raise slider default value to 10000

---

src/base/utils/misc.cpp
src/base/utils/misc.h
src/gui/rss/rsssettingsdlg.cpp
src/gui/rss/rsssettingsdlg.ui
src/webui/www/private/index.html
src/webui/www/public/css/Layout.css

* Fix rss icon too large in rss settings dialog
* Remove trailing spaces
* Fix download & upload icon too large on statusbar in webui

Fix new icons too large

---

src/gui/categoryfiltermodel.cpp
src/gui/categoryfiltermodel.h
src/gui/categoryfilterwidget.cpp
src/gui/categoryfilterwidget.h
src/gui/gui.pri
src/gui/transferlistfilterswidget.cpp
src/gui/transferlistfilterswidget.h
src/src.pro

Show categories in tree mode when subcategories are enabled.

Implement category filter widget. Closes #5444.

---

src/gui/properties/trackerlist.cpp
src/gui/properties/trackerlist.h

Before:
After (only with libtorrent >= 1.0.0):

Display more information in tracker tab

---

src/webui/abstractwebapplication.cpp
src/webui/btjson.cpp
src/webui/www/private/index.html
src/webui/www/public/css/dynamicTable.css
src/webui/www/public/css/style.css
src/webui/www/public/properties_content.html
src/webui/www/public/scripts/contextmenu.js
src/webui/www/public/scripts/dynamicTable.js
src/webui/www/public/scripts/progressbar.js
src/webui/www/public/transferlist.html

WebUI: Implement adjustable dynamic table columns

---

src/webui/www/public/upload.html

No need to increase API version

[Web UI] Fix category in torrent upload. Closes #6260

---

src/gui/addnewtorrentdialog.cpp
src/gui/mainwindow.cpp
src/gui/mainwindow.h
src/gui/properties/propertieswidget.cpp
src/gui/properties/proptabbar.cpp
src/gui/properties/trackerlist.cpp
src/gui/rss/automatedrssdownloader.cpp
src/gui/rss/rss_imp.cpp
src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h

Also closes abandoned PR #3971.
Connecting "Return" to a hotkey didn't work so i changed `torrentDoubleClicked()` a little (copied from `renameSelectedTorrent()`) and now it works.
I'm open to suggestions for the hotkeys themselves of course. IMO they should all be accessible with the left hand.
Oh and while we're on the subject `Alt+1` doesn't work (switch to transferlist) if anyone knows how to fix it please let me know or open a PR, thanks.

Add hotkeys for some things. Closes #2090

---

src/gui/mainwindow.h

Duplicate declaration in _**src/gui/mainwindow.h**_
`class about;`
removed.

Update mainwindow.h (remove duplicate declaration)

---

.travis.yml
src/app/main.cpp
src/base/CMakeLists.txt
src/base/base.pri
src/base/bittorrent/session.cpp
src/base/preferences.cpp
src/base/utils/random.cpp
src/base/utils/random.h
src/gui/optionsdlg.cpp
src/webui/abstractwebapplication.cpp

* Replace rand() by a true uniform distribution generator
~~Bump/fix usable port range from [1024, 64512] to [1024, 65535]~~
~~Anyone know why `64512` is used instead of `65535`?~~
* Turn off port forwarding of WebUI by default for GUI users
Access permission for WAN users should not be on by default.

Replace rand()

---

src/gui/properties/trackerlist.cpp

~~and center align their url strings.~~
pics:
Left alignment:
Center alignment:

Trackerlist: Seperate seeds from peers for DHT, PeX, LSD

---

src/searchengine/nova/engines/extratorrent.py
src/searchengine/nova/engines/versions.txt
src/searchengine/nova3/engines/extratorrent.py
src/searchengine/nova3/engines/versions.txt

https://torrentfreak.com/extratorrents-main-domain-name-shut-down-by-registrar-170302/

[Search engine] Update Extratorrent plugin

---

.travis.yml
src/base/utils/random.cpp

The thread_local fix is for https://github.com/qbittorrent/qBittorrent/pull/6366#issuecomment-284095650
Also Drop back to xcode7.3 on TravisCI.

Workaround thread_local on osx

---

src/base/base.pri
src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/base/utils/net.cpp
src/base/utils/net.h
src/gui/banlistoptions.cpp
src/gui/banlistoptions.h
src/gui/banlistoptions.ui
src/gui/gui.pri
src/gui/optionsdlg.cpp
src/gui/optionsdlg.h
src/gui/optionsdlg.ui
src/webui/prefjson.cpp
src/webui/www/public/preferences_content.html

Implemented locally banned IP list managment + minor objects and functions renames.
Close issue #1837 .

locally banned IP list managment (Closes #1837 )

---

src/gui/categoryfiltermodel.cpp

see https://github.com/qbittorrent/qBittorrent/issues/6523 for details
i hope i did this right

Remove extra space between category names and torrent counts

---

dist/windows/installer.nsi
dist/windows/uninstaller.nsi

* NSIS: trim whitespaces
* NSIS: set exit code to 0 on install/uninstall success
Closes #6129.

NSIS: set exit code to 0 on install/uninstall success

---

dist/windows/installer-translations/french.nsi

Follow-up to #6079 and 4a0244ae88ce1de92dba3c7ad799ac87651ec8e9.

Update French translation for the installer

---

dist/windows/installer-translations/german.nsi

Translation of 64-bit text done.

Update of german.nsi

---

src/base/http/server.cpp
src/base/http/server.h
src/webui/webui.cpp
src/webui/webui.h

* Refactor: group port forwarding code together
Unify log message
* Rename class variables
* Refactor: move the validation of certificates & key functions under Server class
* Refactor: move methods under the same #if section. 
Call disableHttps() in constructor
Done some minor refactor when tracing webUI code...

Webui: refactor

---

src/gui/addnewtorrentdialog.cpp
src/gui/properties/peerlistdelegate.h
src/gui/properties/peerlistwidget.cpp
src/gui/properties/peerlistwidget.h
src/gui/properties/proplistdelegate.cpp
src/gui/properties/proplistdelegate.h
src/gui/search/searchlistdelegate.cpp
src/gui/search/searchlistdelegate.h

* Fix downloaded/uploaded columns were not highlighted properly when selected.
Refactor
* Always draw background
* Setup parent pointer
* Cleanup & refactor

GUI polish

---

src/webui/www/public/properties_content.html

Not sure this is the preferred fix.

WebUI: Fix checkbox hidden

---

.travis.yml
configure
configure.ac
src/base/CMakeLists.txt
src/base/http/connection.cpp
src/base/http/connection.h
src/base/http/responsegenerator.cpp
src/base/http/responsegenerator.h
src/base/http/server.cpp
src/base/http/server.h
src/base/http/types.h
src/base/net/downloadhandler.cpp
src/base/net/geoipmanager.cpp
src/base/utils/gzip.cpp
src/base/utils/gzip.h

~~**[DON'T MERGE YET]: trying to fix TravisCI builds.**~~ Fixed now.
I found out that our http server don't follows the standard close enough (claiming http 1.1 yet only supports 1.0), thus some fixes & improvements.
I plan to enable http persistence connection after http parser supports http pipelining (which should be done in later PR).
This is just the first phase of refactoring, as you can see many methods should have better place to be, I plan to do some more refactor around the classes and review http parser in later PRs.
This PR should not break/change current usage.

Webui server fixes

---

src/base/utils/gzip.cpp

Anyway, use std::vector to allocate memory on the heap (in compress() too).
@qbittorrent/demigods 
please pull in as you see fit.

Fix stack overflow in Utils::Gzip::decompress

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h

This reverts commit 5cbc7b16c04331599f382fa71bdc73f4aed476c7.
https://github.com/qbittorrent/qBittorrent/commit/5cbc7b16c04331599f382fa71bdc73f4aed476c7#commitcomment-21965846
@sledgehammer999 was wrong, creating the commit, so I just revert it back.

Revert "Guard the flag used for deferred session configure."

---

src/webui/www/public/scripts/misc.js

WebUI: Increase the number of digits after the decimal point

---

src/webui/abstractwebapplication.cpp

Continuation of #6776 due to branch issues

Use less permissive Content Security Policy

---

src/gui/properties/propertieswidget.cpp
src/gui/properties/propertieswidget.h
src/gui/properties/trackerlist.cpp
src/gui/properties/trackerlist.h
src/gui/transferlistwidget.cpp

And some coding style here and there.
And set alignment of columns with numbers to the right.
I wanted to fix coding style in whole trackerlist.cpp but the PR would get too big.
If sledgehammer doesn't have a problem with reviewing an extra commit i'll gladly do it.

Trackerlist: Add toggle columns menu

---

src/webui/www/private/index.html
src/webui/www/public/scripts/client.js

Also added the ending semi-colon.

[Quick Fix] Set icon height in html instead of js

---

src/base/bittorrent/torrenthandle.cpp
src/base/utils/version.h

* Initialize variable 
* Add explicit error handling when filesCount() returns negative value

[QuickFix] Fix coverity issues

---

src/base/preferences.cpp
src/base/preferences.h
src/gui/mainwindow.cpp
src/gui/mainwindow.h
src/gui/mainwindow.ui
src/gui/statusbar.cpp
src/gui/statusbar.h

Improve original #4029. 
Now StatusBar is not created when it is not needed (or it is deleted when it is no longer needed).

Add show/hide statusbar option (Supersede #4029)

---

cmake/Modules/MacroQbtCompilerSettings.cmake
src/app/stacktrace.h
src/base/bittorrent/infohash.cpp
src/base/bittorrent/private/filterparserthread.cpp
src/base/bittorrent/torrenthandle.cpp
src/base/filesystemwatcher.cpp
src/base/net/private/geoipdatabase.cpp
src/base/preferences.cpp
src/base/utils/random.cpp
src/gui/mainwindow.cpp
src/gui/messageboxraised.cpp
src/gui/optionsdlg.cpp
src/gui/powermanagement/powermanagement_x11.cpp
src/gui/previewlistdelegate.h
src/gui/properties/pieceavailabilitybar.cpp
src/gui/statsdialog.cpp
src/gui/torrentcontentmodel.cpp
src/gui/transferlistdelegate.cpp
src/gui/transferlistwidget.cpp
src/webui/btjson.cpp

Just a routine replacement of C-style casts with C++ casts where needed.

Replace C-style casts with C++ ones

---

src/base/rss/private/rss_parser.cpp
src/base/rss/rss_article.cpp
src/base/rss/rss_article.h
src/base/rss/rss_autodownloader.cpp
src/base/rss/rss_feed.cpp

This PR has also some prerequisites for #5413.

Improve RSS Article handling

---

src/gui/cookiesdialog.cpp
src/gui/cookiesdialog.ui
src/gui/cookiesmodel.cpp

* Allow to select & delete multiple entries in "Manage Cookies" dialog
* Enable alternatingRowColors for "Manage Cookie" dialog
Set EditTriggers to AllEditTriggers for easier editing

Manage Cookies dialog improvements

---

dist/windows/installer-translations/arabic.nsi

Fills the untranslated parts of the installer

Installer Arabic language update

---

src/base/rss/rss_article.cpp

Fix regression of RSS code redesign.

Fix RSS with normal links do not work. Closes #7003

---

src/webui/www/public/scripts/client.js
src/webui/www/public/scripts/contextmenu.js
src/webui/www/public/scripts/download.js
src/webui/www/public/scripts/dynamicTable.js
src/webui/www/public/scripts/misc.js
src/webui/www/public/scripts/mocha-init.js
src/webui/www/public/scripts/parametrics.js
src/webui/www/public/scripts/prop-files.js
src/webui/www/public/scripts/prop-general.js
src/webui/www/public/scripts/prop-trackers.js
src/webui/www/public/scripts/prop-webseeds.js

Changes include:
Add missing semicolons (and remove inappropriate semicolons)
Use [] to initialize arrays
Use triple equals for comparisons, as appropriate (checking null, undefined, boolean, etc)
Add 0 after decimal point for clarity (`1024.` vs `1024.0`)
Don't re-declare existing variables

Fix various javascript errors and follow best practices

---

src/gui/autoexpandabledialog.cpp
src/gui/autoexpandabledialog.h
src/gui/previewselect.cpp
src/gui/previewselect.h
src/gui/properties/peerlistsortmodel.h
src/gui/properties/trackerlist.cpp
src/gui/properties/trackerlist.h
src/gui/shutdownconfirmdlg.cpp
src/gui/shutdownconfirmdlg.h
src/gui/torrentcontentfiltermodel.cpp
src/gui/torrentcontentfiltermodel.h
src/gui/torrentcontenttreeview.cpp
src/gui/torrentcontenttreeview.h

Mostly indentation spacing and variable renaming.

Coding style for several files

---

src/webui/www/public/scripts/client.js
src/webui/www/public/scripts/dynamicTable.js

`category` could be 'undefined'.
Fixup of a7f4ea8b185b4866134ea396d1bec9ffaf6d16c5.

[WebUI] Fix value comparison

---

src/icons/qbt-theme/README.md

This PR adds a `README.md` to `qbt-theme`, describing the primary source for the new icons by @bertyhell.  Hopefully I got it right this time…  
@evsh, @bertyhell, @Chocobo1:  This PR replaces [<https://github.com/qbittorrent/qBittorrent/pull/7076>].

Create README for "qbt-theme"

---

src/webui/abstractwebapplication.cpp

Fixup of 0532d546d7f3f971cbe9b7f6cf5202995e18d0d6

[WebUI] Load the domain list at least once on startup

---

.travis.yml
cmake/Modules/DeployQt5.cmake
cmake/Modules/QbtTargetSources.cmake
cmake/Modules/bundle.cmake
dist/mac/bundle.cmake
src/CMakeLists.txt
src/app/CMakeLists.txt
src/src.pro

Install platform and svg plugins into bundle. Update dependencies in
Travis.
This also adds dependency on Qt5Svg to the make system. Somehow I forgot to do that in he PR that switched to SVG tray icons.

Install required plugins into bundle

---

src/gui/mainwindow.cpp
src/gui/mainwindow.h

* Trim whitespaces 
* Fix "QObject::connect: No such slot" errors
Fixup of d25467d
ping, in case you're making a release.

Fix "No such slot" errors

---

src/webui/btjson.cpp
src/webui/www/public/css/dynamicTable.css
src/webui/www/public/scripts/client.js
src/webui/www/public/scripts/dynamicTable.js

This provides a text description of the current status vs. the current state image.

Add Status column to webui (addresses #6815)

---

src/gui/torrentcontentmodel.cpp

TL;DR Merging #6156 did not implement anything useful for file type icons on macOS.
More details are available at https://github.com/qbittorrent/qBittorrent/pull/6156#issuecomment-316338699. Please consider merging this into 3.4.0.

Fixed file type icons not displaying on macOS

---

src/gui/transferlistwidget.cpp
src/webui/extra_translations.h
src/webui/www/private/index.html
src/webui/www/public/setlocation.html

Some follow up fixups from merged PRs:
* 145641a
* 07a85a1

WebUI fixups

---

src/gui/categoryfilterwidget.cpp
src/gui/tagfilterwidget.cpp
src/gui/transferlistfilterswidget.cpp

Also remove extra parentheses.

Add space between widgets in left side panel. Closes #7224.

---

src/webui/btjson.cpp
src/webui/webapplication.cpp
src/webui/webapplication.h
src/webui/www/private/index.html
src/webui/www/public/scripts/contextmenu.js
src/webui/www/public/scripts/mocha-init.js
src/webui/www/public/transferlist.html

I rebased #7063 and created this one since the author didn't response.
@qbittorrent/demigods 
Please approve and I'll merge it.

Auto torrent management from webui context menu

---

src/base/bittorrent/session.cpp

Closes #7235.
Bug introduced in #7099.
There may be an underlying bug or limitation of libtorrent here too. I don't know what their code expects as "interface name" on Windows. Their docs don't specify. They only talk about linux.
I tried giving the interface guid or the user-configurable-name but it still didn't work.
If someone knows how to dig through the libtorrent source, he may found the real reason.

Fix connection problems when a specific interface/ip is configured.

---

src/webui/btjson.cpp

Wrap class & functions in anonymous namespace
Rename vars
Cleanup class interfaces
Pass by reference whenever possible

Minor cleanup 

---

src/gui/properties/speedwidget.cpp

* Setup parent ownership to avoid memory leak - found by `-fsanitize=address`
* Use Qt5 connect syntax

Fix leak & use Qt5 connect syntax

---

src/base/bittorrent/session.cpp

Actually suggest_mode is of type int.

Fix suggest_mode setting (#3235 bug)

---

CODING_GUIDELINES.md

Add ranged-based for loop example
Add class inheritance example
Add Prefer pre-increment, pre-decrement operators section
Fix space after comment keyword
Fix header include order
preview: https://github.com/Chocobo1/qBittorrent/blob/coding_style/CODING_GUIDELINES.md

Update coding guidelines (proposal)

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/gui/advancedsettings.cpp
src/gui/optionsdlg.cpp
src/gui/optionsdlg.ui
src/webui/prefjson.cpp
src/webui/www/public/preferences_content.html

Add uTP only mode option

---

src/webui/webapplication.cpp

* WebAPI: fix root_folder default behavior
Bug was introduced in 6b33db3
* Refactor
* WebAPI: fix addPaused wrong default behavior

WebAPI: fix root_folder default behavior

---

src/base/bittorrent/torrenthandle.cpp
src/gui/transferlistdelegate.cpp

`time_since_upload` & `time_since_download` can be -1, so filter them out

Fix last activity calculation

---

src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h

A little refactoring: 
renamed class member names (added m_ prefix), 
rename  main_window -> m_mainWindow 
and  nameFilterModel -> m_sortFilterModel.

members names clarification

---

src/gui/mainwindow.cpp
src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h

added keyboard shortcut to delete torrent. closes #7508 
used standard key sequence for 'Delete' command

added keyboard shortcut to delete torrent. closes #7508

---

src/webui/btjson.cpp

Also do the following cleanups:
* Use string constant QB_EXT
* Remove redundant variable
* Add const

[WebAPI] Add file-to-piece-index mappings in /query/propertiesFiles command

---

src/webui/webui.cpp

An app restart won't be necessary from now on.

Reinitialize webUI server when "IP address" setting changed

---

src/app/application.cpp
src/app/application.h
src/base/preferences.cpp
src/base/preferences.h
src/gui/optionsdlg.cpp
src/gui/optionsdlg.ui
src/webui/www/public/preferences_content.html

screenshot: ![screenshot](https://user-images.githubusercontent.com/9395168/32001585-c15d30f0-b9cc-11e7-84f4-9dc723e64bfd.png)

Allow SMTP sender to be set. Closes #7575.

---

src/base/rss/rss_feed.cpp

Fix RSS log messages was untranslatable.
Add more logging.

Improve RSS events logging

---

src/webui/abstractwebapplication.cpp
src/webui/abstractwebapplication.h

Also refactor to use class methods
The message was not sufficient to help users to diagnosis the problem.

[WebAPI] Improve error messages

---

src/app/application.cpp
src/app/application.h
src/webui/webui.cpp
src/webui/webui.h

From conversations in #7636.
@glassez @Chocobo1 @evsh this may not be ideal, but is this ok to merge as temp solution for v4.0.0?

WebUI: Correctly exit depending if mainloop is running.

---

src/base/rss/rss_feed.cpp

rss_feed.cpp: #include <QDebug> Fixes #7805

---

src/gui/properties/downloadedpiecesbar.cpp
src/gui/properties/downloadedpiecesbar.h
src/gui/properties/peerlistdelegate.h
src/gui/properties/peerlistwidget.cpp
src/gui/properties/peersadditiondlg.cpp
src/gui/properties/peersadditiondlg.h
src/gui/properties/pieceavailabilitybar.cpp
src/gui/properties/pieceavailabilitybar.h
src/gui/properties/piecesbar.h
src/gui/properties/propertieswidget.cpp
src/gui/properties/propertieswidget.h
src/gui/properties/propertieswidget.ui
src/gui/properties/proplistdelegate.cpp
src/gui/properties/proplistdelegate.h
src/gui/properties/proptabbar.cpp
src/gui/properties/proptabbar.h
src/gui/properties/speedplotview.cpp
src/gui/properties/speedplotview.h
src/gui/properties/speedwidget.cpp
src/gui/properties/speedwidget.h
src/gui/properties/trackerlist.cpp
src/gui/properties/trackersadditiondlg.cpp
src/gui/properties/trackersadditiondlg.h

I took a peak at all the non .ui files in /gui/properties/
A few questions:
1. Should members of a private struct be prepended with m_?
2. Is there any reason for [this method](https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/properties/propertieswidget.cpp#L871) to return anything? AFAIK it's only used in the method below.
3. Should i change enum element names to CamelCase (those who are in UPPER case)?
I changed some var names in propertieswidget.ui and i'm not sure if you want them so i put them in separate commits for now.
Apologies for the relatively large PR and don't hesitate to say if you prefer something differently :)

Coding style for many files

---

src/webui/www/public/scripts/client.js
src/webui/www/public/scripts/mocha-init.js

For me, logout action sometimes doesn't work reliable on IE11, the commit "Use POST for logout command" fixes it.

[WebUI] Fix logout behavior

---

src/gui/mainwindow.cpp

* Fix issue: https://github.com/qbittorrent/qBittorrent/issues/7785#issuecomment-347092418
* Minor refactor

Allow to drag-n-drop URLs into mainwindow to initiate download

---

src/base/bittorrent/torrentcreatorthread.cpp
src/base/bittorrent/torrentcreatorthread.h
src/gui/torrentcreatordlg.cpp
src/gui/torrentcreatordlg.h
src/gui/torrentcreatordlg.ui

Add source field in Torrent creator

---

src/webui/btjson.cpp
src/webui/www/public/properties_content.html
src/webui/www/public/scripts/misc.js
src/webui/www/public/scripts/progressbar.js
src/webui/www/public/scripts/prop-files.js

WebUI (pre-formatting changes):
New WebUI:
GUI:

Add "Remaining" and "Availability" columns to webui Content tab

---

src/base/bittorrent/torrenthandle.cpp
src/gui/search/searchlistdelegate.cpp

Fix translation context.

---

src/webui/www/public/scripts/dynamicTable.js

Fixes the bug introduced in #8286

Remove default case, fix #8302

---

src/app/application.cpp

It's an artifact introduced by commit b3c73b7868.

Don't set application name twice

---

src/webui/www/private/scripts/mocha-init.js

This PR saves the user's window size to local storage after a resize event. It then uses those values whenever creating that window (much like the GUI).
This PR should not interfere with #7610.

 WebUI Save user's resized windows

---

src/webui/api/appcontroller.cpp
src/webui/www/private/preferences_content.html

Add "Use proxy only for torrents" option to webui

---

CODING_GUIDELINES.md

You can read more about commit messages [here](https://chris.beams.io/posts/git-commit/).

Add Coding Style rules for commit messages

---

src/webui/api/synccontroller.cpp
src/webui/www/private/css/style.css
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/statistics.html

This should also fix #8422.
Before:
After:

Improve WebUI stats dialog (addendum to #8349)

---

src/webui/www/private/scripts/mocha-init.js

Fix broken WebUI

---

src/webui/www/private/uploadlimit.html

Use correct API method URL in WebUI

---

src/app/application.cpp
src/app/application.h
src/gui/optionsdlg.cpp
src/webui/www/private/preferences_content.html

Closes #8586.
Also sort headers.

Add Tags parameter to "Run External Program"

---

src/webui/www/private/scripts/lib/mocha.js

This reverts commit 470e993c2d700e250889852aa495c9f2cc2b11d6.
As discussed in https://github.com/qbittorrent/qBittorrent/pull/8672#issuecomment-378665038
Ping @Piccirello

Partially revert "Remove unused JavaScript library"

---

src/base/utils/random.cpp
src/base/utils/random.h

The general consensus is to use random facility provided by OS instead of using other software random generators.

Use RNG provided by OS

---

src/base/bittorrent/torrentcreatorthread.cpp
src/base/bittorrent/torrentinfo.cpp

Fix compilation against libtorrent 1.0.x

---

src/gui/properties/peersadditiondlg.cpp
src/gui/properties/peersadditiondlg.ui

Fix untranslated string

---

src/gui/mainwindow.cpp

Fixes commit a468c84b304bdcea985989ca987bda391e3ccaad

Add RSS/Log widgets to the QTabWidget on macOS

---

src/base/bittorrent/torrentinfo.h
src/gui/properties/peersadditiondlg.h

Since these issues aren't critical (and to not break the existing translations), this PR can be deferred to after v4.1.0 release.

Fix tr() related issues

---

src/app/filelogger.cpp

I somehow missed this obvious logic error.

Fix deletion of old logs

---

src/gui/advancedsettings.cpp
src/webui/extra_translations.h
src/webui/www/private/index.html
src/webui/www/private/preferences_content.html

Make strings translatable

---

src/app/application.cpp

This follows utorrent behavior: they don't append backslash character at the end of path variables.

Improve "Run External Program" behavior

---

src/gui/addnewtorrentdialog.cpp

This PR fixes the previous PR (#8922).
I initially missed that only new save paths are added to the beginning of the history, and the old ones remain in place. Now the last used save path is always at the beginning of the history.

Add last used save path to the front of history. Fixes #8922

---

src/base/utils/misc.cpp

Closes #8977 
The new includes were introduced in PR #8936

Fix compilation without D-Bus support

---

src/base/indexrange.h
src/base/tristatebool.cpp
src/base/tristatebool.h
src/base/utils/version.h

This allows compiler to make inferences at compile-time.

Add constexpr to various classes

---

src/webui/webapplication.cpp
src/webui/webapplication.h
src/webui/www/private/preferences_content.html

Restricts form submissions to the current origin + forces/upgrades all connections to https when https is enabled.

More restrictive Content Security Policy

---

src/gui/mainwindow.cpp

Not trying to do anything fancy.
New dialog:

Add changelog URL link in updater

---

src/webui/www/private/scripts/dynamicTable.js

This key will now be recognized for WebUI Table multi-selection, as Ctrl is.

Add WebUI support for Mac ⌘ (Command) key

---

src/webui/api/torrentscontroller.cpp
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/setlocation.html

When using qbittorrent-nox it is not always possible to manually create
the target path for torrent moving. This commit allows
automatic path creation.

Create non-existing path in setLocationAction()

---

src/base/search/searchpluginmanager.cpp
src/base/search/searchpluginmanager.h
src/base/utils/foreignapps.cpp

Now python cache artifacts are removed at plugin install & uninstall.

Omit removing python cache artifacts on qbt start

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h

Modify aio_threads for performance tuning
Related to arvidn/libtorrent#3005
@Chocobo1 Hi. Could you review my code which allow to modify "aio_threads" field?
Thanks a lot

Add aio_threads option to AdvanceSetting Page

---

src/base/bittorrent/session.cpp
src/base/bittorrent/torrenthandle.cpp
src/base/bittorrent/torrenthandle.h
src/base/torrentfilter.cpp
src/base/torrentfilter.h

Please refer to the commit messages.
"Avoid potentially setting the wrong peice priorities" is suggested by arvidn in https://github.com/qbittorrent/qBittorrent/issues/3113#issuecomment-408657870

Avoid potentially setting the wrong piece priorities

---

src/base/preferences.cpp
src/base/preferences.h
src/gui/mainwindow.cpp

 Notify users on 1st time close/minimize to tray 

---

src/gui/mainwindow.cpp
src/gui/search/searchjobwidget.cpp
src/gui/search/searchjobwidget.h
src/gui/search/searchwidget.cpp
src/gui/search/searchwidget.h

Add a name filter for search results 

---

src/base/net/downloadhandler.cpp
src/base/net/downloadhandler.h
src/lang/lang.pri

* Generate i18n .ts files in the correct directory
* Fix lupdate errors

Fix lupdate errors

---

src/gui/transferlistsortmodel.cpp

I'm not sure this fix will be effective, please help testing it.

Fix values sorted wrong in "Last Activity" column

---

src/webui/www/private/css/style.css
src/webui/www/private/filters.html
src/webui/www/private/preferences_content.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/mocha-init.js

* Adjust WebUI Options form alignment
* WebUI sidebar filter toggle
These are very minor changes, mostly visual alignment.
Before:
After:
Before:
After:
Before:
After:

Minor WebUI visual changes

---

src/gui/addnewtorrentdialog.cpp
src/gui/autoexpandabledialog.cpp
src/gui/autoexpandabledialog.h
src/gui/properties/propertieswidget.cpp

Based on PR #7891. 
Closes #2647, closes #7889.

Preselect name without extension when renaming files

---

src/base/bittorrent/torrenthandle.cpp

Save state change from queued to paused

---

src/searchengine/nova/helpers.py
src/searchengine/nova/nova2.py
src/searchengine/nova/nova2dl.py
src/searchengine/nova/novaprinter.py
src/searchengine/nova3/helpers.py
src/searchengine/nova3/nova2.py
src/searchengine/nova3/nova2dl.py
src/searchengine/nova3/novaprinter.py

The following command is used:
`pycodestyle --ignore=E265,E722 --max-line-length=100 <py files>`

Reformat python code to be compliant with PEP8

---

src/base/utils/misc.cpp

Replace magic number with system define.

Replace magic number with system define.

---

src/base/search/searchpluginmanager.cpp
src/base/unicodestrings.h
src/gui/categoryfilterwidget.h
src/gui/transferlistmodel.h

Defects found by: https://lgtm.com/projects/g/qbittorrent/qBittorrent/alerts/?mode=list&lang=cpp
Only fixed the ones that looked severe enough.
---
Maybe we should integrate lgtm.com to check our PRs, the checking quality looks decent.
https://lgtm.com/help/lgtm/managing-pr-integration
@ngosang @Piccirello 
It also found some defects for python/javascript, maybe you would be interested:
https://lgtm.com/projects/g/qbittorrent/qBittorrent/alerts/?mode=list&lang=python
https://lgtm.com/projects/g/qbittorrent/qBittorrent/alerts/?mode=list&lang=javascript

Fix minor defects

---

src/webui/www/private/preferences_content.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/download.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/lib/mocha.js
src/webui/www/private/scripts/misc.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/prop-general.js
src/webui/www/private/scripts/prop-trackers.js
src/webui/www/private/scripts/prop-webseeds.js

Fix minor JavaScript defects

---

src/base/utils/misc.cpp

Support TS extension during torrent preview

Recognize TS files as previewable

---

src/webui/webapplication.h

Bumping per discussion in #9586. In the future this will be done directly in the PR.
Changes documented in #9717.
Closes #9717

Bump WebAPI version

---

src/base/utils/misc.cpp
src/base/utils/misc.h
src/gui/properties/speedplotview.cpp
src/gui/search/searchjobwidget.cpp

Make Y axis scale to fix on predetermined nice looking positions, which have nice looking round quarter labels.

Improve scaling of speed graphs

---

src/base/search/searchpluginmanager.cpp
src/searchengine/nova/helpers.py
src/searchengine/nova/nova2.py
src/searchengine/nova/nova2dl.py
src/searchengine/nova/novaprinter.py
src/searchengine/nova3/helpers.py
src/searchengine/nova3/nova2.py
src/searchengine/nova3/nova2dl.py

~~Currently the plugin update function is broken, I'll apply fix to the search plugin repo too.~~ Update: fixed now.

Fix defects in search engine

---

src/gui/properties/speedplotview.cpp

Fix for zero yMultiplier on high speeds bug. Closes #9807

Fix speed graph "high speeds" bug. Closes #9807

---

src/base/bittorrent/session.cpp
src/gui/optionsdialog.cpp
src/gui/optionsdialog.h
src/gui/optionsdialog.ui
src/gui/properties/peerlistwidget.cpp
src/gui/speedlimitdialog.cpp
src/gui/speedlimitdialog.h
src/gui/speedlimitdialog.ui
src/gui/statusbar.cpp
src/webui/api/appcontroller.cpp
src/webui/www/private/preferences_content.html

As discussed in https://github.com/qbittorrent/qBittorrent/pull/9740
Screenshots: [gui](https://user-images.githubusercontent.com/9395168/47975966-2b1c2000-e0eb-11e8-9d65-c708841136b6.png), [webui](https://user-images.githubusercontent.com/9395168/47975996-5868ce00-e0eb-11e8-8161-53b83ab618bd.png)

 Remove speed limit checkbox in Options dialog

---

src/base/rss/private/rss_parser.cpp
src/base/rss/rss_article.cpp
src/base/rss/rss_feed.cpp
src/base/rss/rss_feed.h

Don't process "out-of-limit" articles.
Closes #9833.

Improve RSS Feed updating. Closes #9833

---

src/base/preferences.cpp
src/base/preferences.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/webui/api/appcontroller.cpp
src/webui/webapplication.cpp
src/webui/webapplication.h
src/webui/www/private/preferences_content.html

* Add option for WebUI Host header validation
Closes #9743.
* Put WebUI security related options into a groupbox
screenshots: [GUI](https://user-images.githubusercontent.com/9395168/48660731-b3ae9f00-eaa1-11e8-8e5a-a7c4c86144c2.png), [WebUI](https://user-images.githubusercontent.com/9395168/48660730-b3ae9f00-eaa1-11e8-9f44-0a965ced940a.png)

Add option for WebUI Host header validation

---

src/app/application.cpp
src/base/search/searchpluginmanager.cpp
src/base/search/searchpluginmanager.h

Only instantiate SearchPluginManager as needed

---

src/base/bittorrent/torrenthandle.cpp
src/gui/torrentcontentmodelfolder.cpp
src/gui/torrentcontentmodelitem.cpp

I'm not sure this will actually fix #9863, the related code looks wrong to me anyway.

Code cleanup

---

src/base/bittorrent/tracker.cpp
src/base/bittorrent/tracker.h

* Use QHostAddress for storing IP
* Use ip parameter from tracker request if provided
Closes #9949.

 Use ip parameter from tracker request if provided 

---

src/gui/optionsdialog.cpp

Save option to start minimized in Mac

---

src/app/stacktracedialog.h
src/base/utils/misc.cpp
src/base/utils/misc.h
src/gui/aboutdialog.h
src/gui/aboutdialog.ui

Add OpenSSL version to GUI & stackdump

---

src/webui/www/private/css/style.css
src/webui/www/private/index.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/dynamicTable.js

Add torrent name filtering to WebUI

---

src/base/rss/rss_autodownloadrule.cpp

Fix for #9898. This patch will let the RSS system keep track of REPACK/PROPER downloads for a filter and refuse to download them again. Specifically it will allow 1 each of REPACK, PROPER and REPACK-PROPER.

Keep track of REPACK/PROPER downloads

---

src/gui/translators.html

Mention more translators

---

src/gui/previewselectdialog.cpp
src/gui/previewselectdialog.h
src/gui/transferlistwidget.cpp

I took PR #9756 and made changes based on the comments from that PR.

Prevent flickering preview dialog

---

src/webui/www/private/preferences_content.html
src/webui/www/public/login.html

This helps the password manager to identify each field and provide adequate actions.

Add autocomplete attribute to WebUI

---

src/base/bittorrent/torrentcreatorthread.cpp
src/base/bittorrent/torrenthandle.cpp
src/base/bittorrent/torrenthandle.h
src/base/net/reverseresolution.cpp

* Use the proper Qt type
* Replace boost::function with std::function
* Remove unused headers

Replace boost::function with std::function

---

src/webui/www/private/css/style.css
src/webui/www/private/index.html
src/webui/www/private/properties_content.html
src/webui/www/private/rename.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/prop-peers.js
src/webui/www/private/scripts/prop-trackers.js
src/webui/www/webui.qrc

This makes Trackers table columns resizable/hide-able and allows multiple rows to be selected for bulk operations (remove/copy).
Closes #8663

Allow WebUI Trackers and Content tables to be manipulated

---

src/gui/translators.html

Mention Swedish translator

---

src/app/application.cpp
src/app/application.h
src/app/stacktracedialog.h
src/base/bittorrent/session.cpp
src/base/global.h
src/gui/aboutdialog.h
src/gui/advancedsettings.cpp

I can't remember nor understand why we need it, so I'll try remove it, let me know if it is really useful.

Remove exception handling

---

src/webui/www/private/css/dynamicTable.css
src/webui/www/private/scripts/download.js

The order was reversed compared to the GUI. Also added a second commit to fix a bug on the download/upload page.

Fix direction of Web UI sorted column icon

---

src/base/bittorrent/private/statistics.cpp
src/base/bittorrent/private/statistics.h
src/base/logger.cpp
src/base/logger.h
src/gui/rss/htmlbrowser.cpp
src/gui/rss/htmlbrowser.h
src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/misc.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/scripts/progressbar.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/prop-general.js
src/webui/www/private/scripts/prop-trackers.js
src/webui/www/private/scripts/prop-webseeds.js

Please correct me if I'm wrong, I choose the current year because we only started to add a license header to the files now. Also I presume the author should be the one who created the file.

Add license header

---

src/base/net/downloadhandler.cpp
src/base/net/downloadhandler.h
src/base/net/downloadmanager.cpp
src/base/net/downloadmanager.h

* Log DownloadManager SSL errors
* ~~Avoid nested handleRedirection() calls~~
* Limit DownloadHandler max redirection to 20

Fix crash due to network redirections

---

src/app/stacktracedialog.h
src/gui/aboutdialog.h
src/gui/deletionconfirmationdialog.h
src/gui/previewselectdialog.cpp
src/gui/previewselectdialog.h
src/gui/previewselectdialog.ui
src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h

This makes the whole codebase consistent in terms of ui object management.

Convert to use private pointer for ui object

---

src/app/main.cpp
src/base/profile.cpp
src/base/profile.h
src/base/rss/rss_feed.cpp
src/gui/addnewtorrentdialog.h
src/gui/fspathedit.cpp
src/gui/fspathedit.h

These 2 types are very similar and we should prefer the one from C++ standard library.

Replace QScopedPointer with std::unqiue_ptr

---

.travis.yml

This should reduce build time for affected jobs

Use custom packages for travis and RC_1_2

---

INSTALL

There are no optional dependencies except python, so the INSTALL file is outdated, this PR updates it.

Update INSTALL file

---

src/app/application.cpp

It works locally for me. Let's see if it works for appveyor.

Remove wrong ifdef

---

src/gui/search/searchjobwidget.cpp
src/gui/search/searchjobwidget.h

Make num enter key work the same as return in searchjobwidget

---

src/webui/www/README.md

This PR only aims to reflect our consensus on the *current* compatibility to browsers, please refrain from discussing future plans.
I'm not sure what to put in to the lower bound for chrome, so I choose something that is not too recent and also not too old.

Document current WebUI browser compatibility

---

src/base/http/requestparser.cpp

Fixes #10451.
Will backport to 4.1.x branch once approved.

Correctly handle '+' sign in x-www-form-urlencoded data

---

src/base/http/requestparser.cpp
src/webui/api/synccontroller.cpp
src/webui/api/synccontroller.h

Backport recent PRs to v4_1_x

---

src/base/bittorrent/session.cpp
src/base/bittorrent/torrentinfo.cpp
src/base/global.h
src/gui/addnewtorrentdialog.cpp

Backport #10464 to v4_1_x

---

src/base/http/server.cpp
src/base/http/server.h
src/base/utils/version.h

Backport to v4_1_x

---

src/webui/www/private/scripts/dynamicTable.js

This is useful for seeing the value of a narrow field. 
A title hasn't been added to the Progress Bar. It seemed like a lot of effort.

Set title attribute for all WebUI table cells

---

src/webui/webapplication.cpp
src/webui/webapplication.h
src/webui/www/private/about.html
src/webui/www/private/addtrackers.html
src/webui/www/private/confirmdeletion.html
src/webui/www/private/download.html
src/webui/www/private/downloadlimit.html
src/webui/www/private/edittracker.html
src/webui/www/private/index.html
src/webui/www/private/newcategory.html
src/webui/www/private/preferences.html
src/webui/www/private/rename.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/setlocation.html
src/webui/www/private/shareratio.html
src/webui/www/private/upload.html
src/webui/www/private/uploadlimit.html
src/webui/www/public/css/login.css
src/webui/www/public/index.html

* Align WebUI login button to the right
screenshot:
* Use force refresh on WebUI logout
* Use a random number for WebUI cache busting

Misc improvements in WebUI

---

src/webui/www/private/download.html
src/webui/www/private/scripts/download.js
src/webui/www/private/upload.html

Closes #10392.
Will backport to 4.1.x branch.

Fix "Create subfolder" option is not working in WebUI

---

src/gui/mainwindow.cpp

Closes #9240 and possibly #9121, as @zeule suggested here: https://github.com/qbittorrent/qBittorrent/issues/9240#issuecomment-408025722.

Don't turn screen blank when closed to system tray

---

src/gui/transferlistfilterswidget.cpp

[previous](https://user-images.githubusercontent.com/34717789/58174081-a9709600-7cba-11e9-9313-0684c8c7bb73.png)

Replace CheckBox with Arrow in transferlistfilterswidget

---

src/base/bittorrent/trackerentry.cpp

The error is caused by silly copy-paste error.
Fixup 09ff735007e7aa650c7045d2546d95366b8147a4.

Fix wrong logic

---

src/gui/lineedit/src/lineedit.cpp
src/gui/optionsdialog.ui

* Fix search icon placement when using RTL languages
Screenshots:
[before](https://user-images.githubusercontent.com/9395168/58257521-a69da000-7da3-11e9-934f-44dc7d0f1ee5.png), [after](https://user-images.githubusercontent.com/9395168/58257522-a7363680-7da3-11e9-9a48-2861dfb10170.png)
* Avoid combo boxes extending to the right in Options dialog
* Tweak visuals in Options dialog 
Screenshots:
Page 1: [before](https://user-images.githubusercontent.com/9395168/58258023-8e7a5080-7da4-11e9-947d-f4fab3bb5018.png), [after](https://user-images.githubusercontent.com/9395168/58258027-8f12e700-7da4-11e9-89fe-7b4eb3c305c3.png)
Page 3: [before](https://user-images.githubusercontent.com/9395168/58258024-8f12e700-7da4-11e9-8be4-9b06e42b1c75.png), …

Various visual tweaks

---

src/base/net/downloadmanager.cpp

This issue occurred because of latest changes in redirection handling.
Should be backported to v4.1.x.
Probably closes #10215 and similar issues.

Fix sequential downloading when redirected

---

src/base/bittorrent/session.cpp
src/base/bittorrent/torrenthandle.cpp
src/base/bittorrent/torrenthandle.h
src/gui/addnewtorrentdialog.cpp
src/gui/mainwindow.cpp
src/gui/rss/rsswidget.cpp

* Avoid using deprecated stats_alert
* Use less operations when building strings

Avoid using deprecated stats_alert

---

src/app/stacktracedialog.h
src/base/utils/misc.cpp
src/base/utils/misc.h
src/gui/aboutdialog.h
src/gui/aboutdialog.ui
src/webui/api/appcontroller.cpp
src/webui/www/private/about.html

Add zlib version to libraries tab in about dialog and to stacktrace dialog.
Closes #10240

Add zlib version to GUI & stackdump

---

src/base/preferences.cpp
src/base/preferences.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/webui/api/appcontroller.cpp
src/webui/webapplication.cpp
src/webui/webapplication.h
src/webui/www/private/preferences_content.html

* Add WebAPI session timeout settings 
Raise default timeout to 1 hour.
Supersedes PR #10624.
Screenshots:
* GUI
* WebUI

Add WebAPI session timeout settings

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/base/net/proxyconfigurationmanager.cpp
src/base/net/proxyconfigurationmanager.h
src/base/utils/misc.cpp
src/base/utils/misc.h
src/gui/properties/peerlistwidget.cpp
src/gui/properties/propertieswidget.cpp
src/gui/tagfiltermodel.cpp
src/gui/transferlistdelegate.cpp
src/gui/transferlistwidget.cpp
src/webui/api/torrentscontroller.cpp

* Improve handleFileErrorAlert error message
Will backport to v4_1_x
* Remove workaround in TorrentHandle::setCategory
* Add comparison operators for ProxyConfiguration
* Remove redundant variable
* Set wheel event to accepted only if we handle it
Will backport to v4_1_x
* Fix crash when removing phantom tags
Closes #10569.
Will backport to v4_1_x
* Fix wrong "Time Active" value displayed 
* Support year unit in userFriendlyDuration()
* Use appropriate type
A couple of small fixes when reviewing code.
Let me know if some commit are suppose to have its own PR.

Misc. fixes

---

src/gui/optionsdialog.cpp
src/gui/search/searchjobwidget.cpp
src/gui/search/searchjobwidget.h
src/gui/torrentcategorydialog.cpp
src/gui/transferlistwidget.cpp

* Avoid creating unnecessary event loops 
This is part 2.
* Fix wrong while() statement

Avoid creating unnecessary event loops

---

src/base/bittorrent/session.cpp
src/base/utils/random.cpp
src/base/utils/random.h
src/gui/advancedsettings.cpp
src/webui/api/searchcontroller.cpp

* Remove upper limit of "Disk cache" setting
* Remove limits of "Disk cache expiry interval" setting
* Use numeric_limits instead of constants from C

Remove upper limit of disk cache setting

---

src/app/main.cpp

This raises qbt's open file descriptor limit to the available maximum (within user privileges) and thus users don't need to adjust it manually anymore.

Adjust open file descriptor limit on startup

---

src/base/bittorrent/trackerentry.cpp
src/gui/CMakeLists.txt
src/gui/gui.pri
src/gui/trackerentriesdialog.cpp
src/gui/trackerentriesdialog.h
src/gui/trackerentriesdialog.ui
src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h

* Add editTrackersDialog
Menu:
Dialog:
* Replace QList by QVector

Add dialog to mass edit torrent's tracker

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/base/bittorrent/torrenthandle.cpp
src/base/bittorrent/torrenthandle.h

I had to backport it manually (for the most part), so I'm not sure it turned out to be completely correct. I have no opportunity to test it.

Fix torrent checking issues (backport to v4.1.x)

---

src/app/application.cpp

Closes #10925.
will backport to v4.1.x.

Prevent command injection via "Run external program" function

---

src/gui/transferlistdelegate.cpp
src/gui/transferlistmodel.cpp
src/gui/transferlistmodel.h
src/webui/api/serialize/serialize_torrent.cpp
src/webui/api/serialize/serialize_torrent.h
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/misc.js

* Add availability column
* ~~Remove redundant comparisons 
QSortFilterProxyModel::lessThan() can handle those types by default.~~
* Add helper function to convert to fixed-point string

Add availability column

---

src/webui/www/private/download.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/mocha-init.js

List of supported parameters retrieved from [here](https://en.wikipedia.org/wiki/Magnet_URI_scheme)
Closes #10939

Fix WebUI removing parameters from magnet links

---

src/base/bittorrent/torrenthandle.cpp

Fix incomplete file extension not applied for new torrents

---

src/webui/www/private/scripts/client.js
src/webui/www/private/search.html

Web UI implementation of #10852

 Add context menu to Web UI search table

---

src/webui/api/torrentscontroller.cpp
src/webui/api/torrentscontroller.h
src/webui/api/transfercontroller.cpp
src/webui/api/transfercontroller.h
src/webui/www/private/addpeers.html
src/webui/www/private/index.html
src/webui/www/private/scripts/prop-peers.js
src/webui/www/webui.qrc

Add ability to add and ban a peer from the Web UI

---

src/gui/optionsdialog.ui
src/webui/www/private/preferences_content.html

Fix translation issues (backport to v4_1_x)

---

src/gui/rss/automatedrssdownloader.cpp
src/gui/rss/automatedrssdownloader.h
src/gui/rss/automatedrssdownloader.ui

To replace "..." icon with the actual icon.
Closes #8897

Use FileSystemPathEdit in automated rss downloader

---

src/base/bittorrent/session.cpp
src/base/bittorrent/tracker.cpp
src/base/bittorrent/tracker.h
src/base/exceptions.h
src/base/http/httperror.cpp
src/base/http/httperror.h
src/base/http/responsebuilder.cpp
src/base/http/types.h
src/base/tristatebool.h
src/gui/advancedsettings.cpp
src/webui/api/appcontroller.cpp

Closes #9958. This PR covers almost all of it.
Parts that is incomplete (and I don't think worth implementing fully):
* `min interval`
* Partial support for IPv6 announcement.

Improve embedded tracker

---

src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui

Screenshot: ![screenshot](https://user-images.githubusercontent.com/9395168/63896130-c1775480-ca23-11e9-9db7-f54548db3e71.png)

Move "Check for program updates" checkbox out of Advanced settings

---

src/base/bittorrent/peerinfo.cpp

Already tested on linux & windows.

Construct QHostAddress more efficiently

---

.github/ISSUE_TEMPLATE.md

Fix ambiguity in GitHub Issue template

---

src/base/bittorrent/session.cpp

Fix up d657c872433aea21a2762880599e9dbee40db9a0.

Add check for null pointer

---

src/base/utils/fs.cpp
src/gui/torrentcontenttreeview.cpp

Fix filename validation on non-Windows OS

---

src/base/filesystemwatcher.cpp
src/base/scanfoldersmodel.cpp

Treat .magnet file extension as case insensitive in filesystem watcher

---

src/gui/addnewtorrentdialog.cpp
src/gui/properties/propertieswidget.cpp

Revise HTML escaping in GUI (Backport)

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/gui/transferlistwidget.cpp
src/webui/api/torrentscontroller.cpp
src/webui/www/private/views/preferences.html

Continuation from #8671
closes #8074, closes #8151

Add "Remove torrent and its files" option to share ratio limiting

---

src/gui/CMakeLists.txt
src/gui/deletionconfirmationdialog.cpp
src/gui/deletionconfirmationdialog.h
src/gui/gui.pri
src/gui/transferlistwidget.cpp

* Move DeletionConfirmationDialog class to its own .cpp file
* Use signal/slot to return dialog results

Revise DeletionConfirmationDialog class

---

src/base/bittorrent/private/filterparserthread.cpp
src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/base/bittorrent/torrenthandle.cpp

* Clean up "network interfaces configuration" code
* Migrate to lt::error_code

Clean up "network interfaces configuration" code

---

src/base/utils/fs.cpp

Fix integer narrowing on x86 (backport)

---

src/base/bittorrent/session.cpp
src/base/bittorrent/torrenthandle.cpp

Reserved size is based on discussion in https://github.com/qbittorrent/qBittorrent/pull/11307#discussion_r340230628

Reserve memory for file data buffers

---

src/gui/banlistoptionsdialog.cpp
src/gui/banlistoptionsdialog.ui

Due to the author of PR #11351 insisted on his own version and I'm tired of meaningless debates, this PR exists as an replacement.

Allow to select multiple entries in "banned IP" dialog

---

src/base/bittorrent/session.cpp

Fix up 5d46c9b2d6e476d8dd1eee770bf65a8366e80fe7.

Avoid session reconfiguration when limit has not changed

---

src/webui/webapplication.h

Bump Web API version

---

src/gui/transferlistwidget.cpp

edit-delete is the red `X` sign icon and list-remove is the red trash can icon.

Fix inconsistent icon for deleting torrent

---

cmake/Modules/MacroQbtCompilerSettings.cmake

Fixes https://github.com/qbittorrent/qBittorrent/issues/11606.

Remove -march=native optimisation 

---

src/webui/api/torrentscontroller.cpp
src/webui/api/torrentscontroller.h
src/webui/www/private/index.html
src/webui/www/private/newcategory.html
src/webui/www/private/rename_file.html
src/webui/www/private/scripts/prop-files.js
src/webui/www/webui.qrc

Renaming folders is not yet supported
Closes #8892.

Add ability to rename torrent files from the WebUI

---

src/base/bittorrent/torrenthandle.cpp
src/base/bittorrent/torrenthandle.h
src/gui/transferlistmodel.cpp
src/gui/transferlistmodel.h
src/gui/transferlistwidget.cpp
src/gui/transferlistwidget.h

Allow transfer list text color changes through QSS

---

src/gui/properties/peerlistwidget.cpp
src/webui/www/private/scripts/dynamicTable.js

Some displayed flags may belong to regions.

Rename Country column to "Country / Region"

---

src/webui/www/private/views/preferences.html

Fixup 8200ef6bd5aaeb142b112d11d758155c856e8350

WebUI: remove unused/deprecated "Listen on IPv6 address" option

---

src/webui/www/private/scripts/client.js
src/webui/www/private/statistics.html

Just because these 2 fixes are quite important for the WebUI and are an easy backport.

WebUI: backport #11635 and #11756 to v4_1_x

---

src/gui/previewselectdialog.cpp

Allow double-click in preview dialog

---

src/base/bittorrent/session.cpp
src/base/private/profile_p.cpp
src/base/profile.cpp
src/base/profile.h

Trying to fix portable mode bug described in #11706, #11178, #7765.
After manual testing in Windows and Ubuntu it looks like everything is working fine in portable and normal mode. But I could miss some test scenarios so it would be great if someone else also did some tests.

Fix portable mode

---

src/webui/www/private/scripts/mocha-init.js

Closing document explicitly is recommended by MDN:
https://developer.mozilla.org/en-US/docs/Web/API/Document/write

Close document properly after writing

---

src/base/rss/rss_feed.cpp

Don't access download handler after it's finished

---

dist/windows/installer-translations/czech.nsi

translating to czech and trying to make existing translation more accurate

NSIS: Improve Czech translation

---

dist/windows/installer-translations/german.nsi

German translation of "inst_requires_win7" added.

NSIS: Update German translation

---

src/gui/mainwindow.cpp

Change placeholder text in torrent list's filter
Closes #11891

Change placeholder text in torrent list's filter

---

src/base/bittorrent/session.cpp
src/base/bittorrent/torrenthandle.cpp
src/base/bittorrent/torrenthandle.h
src/base/bittorrent/torrentinfo.cpp
src/base/bittorrent/torrentinfo.h
src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.h
src/gui/addnewtorrentdialog.ui

Allow to save downloaded metadata as torrent file

---

src/gui/optionsdialog.ui

* Fix wrong field for translation comment
* Improve torrent management tooltip to cover both modes
* Add new tooltips for potentially confusing settings
Decent progress towards #6346, closes #9994, closes #11528

Improve the options tooltips

---

src/base/bittorrent/peerinfo.cpp

Fix for https://github.com/qbittorrent/qBittorrent/pull/12108#discussion_r388174852

Use proper type for piece index

---

src/gui/properties/propertieswidget.cpp
src/gui/properties/trackerlistwidget.cpp
src/gui/rss/rsswidget.cpp
src/gui/torrentcontenttreeview.cpp
src/gui/transferlistwidget.cpp

* Fix crash when renaming torrent contents
Closes #10328.
* Initialize boolean variables

Fix crash when renaming torrent contents

---

README.md
src/base/net/geoipmanager.cpp
src/base/net/private/geoipdatabase.cpp
src/base/net/private/geoipdatabase.h
src/gui/aboutdialog.h
src/gui/aboutdialog.ui
src/gui/advancedsettings.cpp

Yes, i realize there probably won't be another 4.1.x release.
As requested in https://github.com/qbittorrent/qBittorrent/issues/11792#issuecomment-590519205

Backport #12014: Use IP geolocation database by DB-IP instead of MaxMind

---

src/base/bittorrent/session.cpp

fixup e4ff206e3c7eddc5652c8f7fb5315ff9938d419e
closes #12185 (tested)

Append new move storage job to queue

---

src/gui/statsdialog.cpp
src/webui/api/synccontroller.cpp

Also fix small typo in function name.
Partially resolves https://github.com/qbittorrent/qBittorrent/issues/12092.
See https://github.com/qbittorrent/qBittorrent/issues/12092#issuecomment-599283630.

Fix total connected peers count calculation

---

dist/unix/org.qbittorrent.qBittorrent.appdata.xml

It would be nice, if this version string too could be updated for new releases.

Update Linux appdata release version 

---

src/base/scanfoldersmodel.cpp

closes #12202, closes #11236, closes #11966, closes #10268

Disable Auto TMM when not using default savepath from monitored folder

---

src/base/http/requestparser.cpp
src/webui/api/torrentscontroller.cpp

WebAPI: fix matching uncategorized torrents

---

src/gui/properties/piecesbar.cpp

Just missing include... Fixes build with Qt 5.15

Add missing QPainterPath header include

---

src/app/application.cpp
src/app/cmdoptions.cpp
src/app/main.cpp
src/app/stacktrace_win.h
src/base/bittorrent/session.cpp
src/base/http/responsegenerator.cpp
src/base/net/geoipmanager.cpp
src/base/net/proxyconfigurationmanager.cpp
src/base/rss/rss_autodownloader.cpp
src/base/rss/rss_autodownloadrule.cpp
src/base/rss/rss_feed.cpp
src/base/rss/rss_session.cpp
src/base/search/searchpluginmanager.cpp
src/gui/aboutdialog.cpp
src/gui/advancedsettings.cpp
src/gui/categoryfiltermodel.cpp
src/gui/lineedit.cpp
src/gui/mainwindow.cpp
src/gui/optionsdialog.cpp
src/gui/rss/automatedrssdownloader.cpp
src/gui/rss/feedlistwidget.cpp
src/gui/statsdialog.cpp
src/gui/tagfiltermodel.cpp
src/gui/torrentcreatordialog.cpp
src/gui/transferlistfilterswidget.cpp
src/webui/api/apierror.h
src/webui/api/searchcontroller.cpp

* Allow to translate error messages 
* Construct QString more efficiently

Construct QString more efficiently

---

src/base/bittorrent/session.cpp

See #12245 and #12282
PS: I am not able to actually test it.

Fix broken UNC paths in fastresumes on Windows

---

src/base/bittorrent/private/resumedatasavingmanager.cpp

This commit also allows the strings to be translated.

Improve logging for errors

---

src/gui/transferlistmodel.cpp

Fix date format for "Last seen complete"

---

src/app/application.h
src/app/qtlocalpeer/qtlockedfile.h
src/base/bittorrent/private/filterparserthread.h
src/base/bittorrent/private/nativesessionextension.h
src/base/bittorrent/private/nativetorrentextension.h
src/base/bittorrent/private/portforwarderimpl.h
src/base/bittorrent/torrentcreatorthread.h
src/base/bittorrent/tracker.h
src/base/http/server.h
src/base/net/downloadmanager.cpp
src/base/net/private/downloadhandlerimpl.h
src/base/private/profile_p.h
src/base/rss/private/rss_parser.cpp
src/base/scanfoldersmodel.h
src/webui/webapplication.h

This allow compilers to generate more efficient code.
I excluded classes in gui folder and I plan to address it in subsequent PR.

Add final specifier to classes

---

src/base/bittorrent/session.cpp

Separated from #12162.
See discussion: https://github.com/qbittorrent/qBittorrent/pull/12162#discussion_r408317536

Change default upload slot choking limits

---

src/gui/optionsdialog.ui

Reduce ambiguity for selecting icons

---

src/base/bittorrent/session.cpp

Fix crash when torrent is deleted on limit reached

---

src/webui/api/appcontroller.cpp
src/webui/api/rsscontroller.cpp
src/webui/api/rsscontroller.h

In order to implement the RSS functionality in the WebUI (#12355) new API functionality is required.

Expand RSS related WebAPI

---

src/gui/optionsdialog.cpp

Fix typo in optionsdialog.cpp

---

.travis.yml

Is there any reason to staying to xenial?
(Canonical has stopped providing xenial for the PPAs and it is EOL)
This will initially probably fail until the qbittorrent-team/qbt-libtorrent-travisci has build the libtorrent package for bionic.

Switch TravisCI to bionic

---

src/base/bittorrent/torrenthandleimpl.cpp
src/gui/torrentcontentmodel.cpp
src/gui/torrentcontentmodelfile.cpp

* Handle empty piece range properly
Related: #12677.

Handle empty piece range properly

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/base/bittorrent/torrenthandleimpl.cpp
src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.ui
src/gui/optionsdialog.cpp
src/gui/optionsdialog.ui
src/gui/rss/automatedrssdownloader.ui
src/webui/api/appcontroller.cpp
src/webui/www/private/download.html
src/webui/www/private/upload.html
src/webui/www/private/views/preferences.html

Rename "Create subfolder" option to "Keep subfolder"

---

src/gui/log/loglistview.cpp
src/gui/log/logmodel.cpp
src/gui/log/logmodel.h

Fixes https://github.com/qbittorrent/qBittorrent/issues/5199

Allow changing log colors from config.json

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/base/bittorrent/torrenthandle.h
src/base/bittorrent/torrenthandleimpl.cpp
src/base/bittorrent/torrenthandleimpl.h

Wait for storage to be moved when removing torrent

---

src/base/bittorrent/session.cpp

Fix invalid assertion

---

src/gui/uithememanager.cpp
src/gui/uithememanager.h

fixes https://github.com/qbittorrent/qBittorrent/issues/12810

Cache flag icons

---

src/base/bittorrent/torrenthandle.h
src/base/bittorrent/torrenthandleimpl.cpp
src/base/bittorrent/torrenthandleimpl.h
src/gui/properties/peerlistwidget.cpp

Closes https://github.com/qbittorrent/qBittorrent/issues/12853

Address some issues regarding private torrents

---

src/gui/log/loglistview.cpp

Fixes https://github.com/qbittorrent/qBittorrent/issues/12758

Fix large strings not visible in log widget

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/base/bittorrent/torrenthandleimpl.cpp
src/gui/properties/pieceavailabilitybar.cpp
src/gui/properties/pieceavailabilitybar.h
src/gui/properties/piecesbar.cpp
src/gui/properties/piecesbar.h
src/gui/torrentcontentmodel.cpp

Drop ".unwanted folder" feature

---

src/webui/www/private/download.html
src/webui/www/private/newcategory.html
src/webui/www/private/newfeed.html
src/webui/www/private/newfolder.html
src/webui/www/private/newrule.html
src/webui/www/private/newtag.html
src/webui/www/private/rename.html
src/webui/www/private/rename_feed.html
src/webui/www/private/rename_file.html
src/webui/www/private/rename_rule.html
src/webui/www/private/setlocation.html
src/webui/www/private/upload.html
src/webui/www/private/views/rssDownloader.html

I have addressed the issues that have been raised regarding the WebUI RSS implementation.
- RSS Feed links and names where limited to 100 Characters
- Inputs in RSS downloader would go outside off their parent object
- Added buttons for creating and deleting RSS downloader rules
<br />
I don't know if this should be merged now or wait until more issues arise and are solved.

Fix issues regarding WebUI RSS implementation

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h

fixes https://github.com/qbittorrent/qBittorrent/issues/12560
special thanks to @arvidn (see discussion https://github.com/arvidn/libtorrent/issues/4890)

Fix impossible speed in graph

---

src/gui/properties/peerlistwidget.cpp
src/gui/search/searchjobwidget.cpp

Otherwise the table/value can be edited by double clicking (or pressing F2) on it.

Disable edit action

---

src/gui/rss/rsswidget.cpp

Primarily useful for custom themes.

Use palette colors in RSS feeds

---

src/gui/rss/articlelistwidget.cpp

Fix incorrect foreground for read articles with custom theme

---

src/webui/www/private/confirmfeeddeletion.html
src/webui/www/private/confirmruledeletion.html
src/webui/www/private/newfeed.html
src/webui/www/private/newfolder.html
src/webui/www/private/newrule.html
src/webui/www/private/rename_feed.html
src/webui/www/private/rename_rule.html

Change api requests in RSS WebUI to relative paths

---

src/base/http/types.h
src/gui/gpl.html
src/gui/thanks.html
src/gui/translators.html
src/webui/api/torrentscontroller.cpp
src/webui/www/private/download.html
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/upload.html
src/webui/www/public/scripts/login.js

* Improve handling of empty iframe src
"about:blank" is suggested in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
* Specify UTF-8 charset when forming data from plain text
This suppresses a browser warning about unspecified character encoding of an HTTP response.
* Use proper uppercase "UTF-8" in charset field

Minor WebUI improvements

---

src/base/bittorrent/session.cpp
src/gui/log/logmodel.cpp

Fix peer blocked message

---

src/gui/properties/peerlistwidget.cpp

The selected rows aren't queried until after a user confirms they
would like to ban the selected peers. If a peer disconnects before
the confirmation is pressed, the function, they will not be included
to the selection. This commit makes sure the selected rows are cached
first before a selection is made to prevent the loss of any peers.
Closes #13385.

Prevent peers from being lost when banning

---

cmake/Modules/MacroQbtCommonConfig.cmake
src/app/CMakeLists.txt

* Add compile flags from conf.pri.windows file to cmake
* Use silent flag when invoking lrelease via cmake

CMake improvements

---

src/app/CMakeLists.txt

Fix CMake project

---

src/gui/advancedsettings.cpp
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/views/preferences.html

* Fix image not loading under proxy
Closes #13483.
* Fix wrong capitalization

Fix image not loading under proxy 

---

src/gui/properties/peerlistwidget.cpp
src/gui/transferlistmodel.cpp

Fixup 13aab6e04d6accc6768d49246967b167187a6df2
Closes #13491

Fix regression of not hiding zero values in the peer list

---

.travis.yml

- Our CMake configuration has matured over time, disallow build failures
- Remove outdated branches block

Disallow CMake build failures on Travis

---

src/base/http/connection.cpp

Fix typo in connection.cpp

---

src/webui/api/appcontroller.cpp

Avoid settings being reset via WebAPI

---

src/gui/optionsdialog.ui
src/webui/www/private/views/preferences.html

Closes https://github.com/qbittorrent/qBittorrent/issues/13628.

Clarify protocol choice label

---

src/gui/properties/propertieswidget.cpp

Fix crash when clicked outside the table of torrent content view

---

src/base/bittorrent/peerinfo.cpp
src/base/bittorrent/torrentinfo.cpp
src/base/bittorrent/trackerentry.cpp

After this PR, all that left is related to `InfoHash` class.

Improve compatibility with libtorrent 2.0

---

src/gui/CMakeLists.txt
src/gui/gui.pri
src/gui/progressbardelegate.cpp
src/gui/progressbardelegate.h
src/gui/properties/proplistdelegate.cpp
src/gui/properties/proplistdelegate.h
src/gui/torrentcontentfiltermodel.cpp
src/gui/torrentcontentmodel.cpp
src/gui/torrentcontentmodel.h
src/gui/torrentcontentmodelfolder.cpp
src/gui/torrentcontentmodelfolder.h
src/gui/torrentcontentmodelitem.cpp
src/gui/torrentcontentmodelitem.h
src/gui/transferlistdelegate.cpp
src/gui/transferlistdelegate.h

~~Add a new option `progressbar-style` in config.json, `native` draw with stylesheet style else fallback to platform default~~
see below

Allow progress bar styling from custom themes

---

src/gui/mainwindow.cpp
src/gui/mainwindow.h

Allow adding torrents using "Paste" key sequence

---

src/base/bittorrent/torrenthandle.h
src/base/bittorrent/torrenthandleimpl.cpp
src/gui/transferlistmodel.cpp
src/webui/api/serialize/serialize_torrent.cpp
src/webui/www/private/scripts/dynamicTable.js

Don't use deprecated torrent state "allocating"

---

src/webui/www/private/confirmdeletion.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/mocha-init.js

Add ability to use 'shift+delete' to delete torrents in WebUI

---

.github/workflows/file_health.sh
.github/workflows/file_health.yaml

Also adjust newlines to improve output
---
@sledgehammer999
Follow-up to https://github.com/qbittorrent/qBittorrent/pull/13659. These `*.ts` files issues must be fixed and tested for, as they are behind at least one known bug: https://github.com/qbittorrent/qBittorrent/issues/12369.

Detect .ts file issues with file health workflow

---

src/gui/properties/speedplotview.cpp
src/gui/torrentcontentmodelitem.cpp
src/gui/transferlistmodel.cpp

Closes #13869.
Fix up 02f19bfbee1a1529a8dae5106f98c909d82c1932.

Fix availability value

---

.travis.yml

Also bumping to ubuntu focal as libtorrent requires boost >= 1.66.

Add libtorrent 2.0 to TravisCI script

---

src/webui/www/private/newcategory.html
src/webui/www/private/newrule.html
src/webui/www/private/newtag.html
src/webui/www/private/rename.html
src/webui/www/private/rename_file.html
src/webui/www/private/rename_rule.html

Remove unnecessary restriction on input length

---

src/base/bittorrent/session.cpp
src/base/bittorrent/torrenthandleimpl.cpp

Fix bug of torrents don't save "stopped" state

---

CODING_GUIDELINES.md

---
Follow-up to: https://github.com/qbittorrent/qBittorrent/pull/13948

Update coding guidelines policy for include guards

---

src/webui/api/torrentscontroller.cpp

Fortunately, serializing to JSON limits the data types to a very small subset and thus we are able to implement the comparison without much hassle.
Fix up cba8d83b2195a2c323e5fc430b8f68a0aff33a6f.

Migrate away from deprecated QVariant comparison operators (part 2)

---

src/base/bittorrent/session.cpp

Fix bug of "move storage job" can be performed multiple times

---

src/webui/api/torrentscontroller.cpp

Fix up 78638a15be33d2f8e336117e23ca496841221d42.
Closes #14041.

Fix wrong JSON type returned

---

src/base/unicodestrings.h
src/gui/optionsdialog.cpp
src/lang/lang.qrc
src/lang/qbittorrent_az@latin.ts
src/lang/qbittorrent_et.ts
src/webui/www/private/views/preferences.html
src/webui/www/translations/webui_az@latin.ts
src/webui/www/translations/webui_et.ts
src/webui/www/translations/webui_translations.qrc

Add new languages

---

src/base/bittorrent/session.cpp
src/base/settingvalue.h
src/base/torrentfileguard.cpp
src/base/torrentfileguard.h
src/gui/addnewtorrentdialog.h
src/gui/previewselectdialog.cpp
src/gui/previewselectdialog.h
src/gui/search/searchjobwidget.cpp
src/gui/search/searchjobwidget.h
src/gui/torrentcreatordialog.cpp
src/gui/torrentcreatordialog.h
src/gui/trackerentriesdialog.h

This new layer would be handy for saving GUI widget states as they don't need the value cached and they store/load rarely.

Add a thin layer around SettingsStorage class

---

src/app/application.cpp
src/app/upgrade.cpp
src/base/bittorrent/portforwarderimpl.cpp
src/base/net/proxyconfigurationmanager.cpp
src/base/rss/rss_autodownloader.cpp
src/base/rss/rss_session.cpp
src/base/settingsstorage.cpp
src/base/settingsstorage.h
src/base/settingvalue.h
src/gui/addnewtorrentdialog.cpp
src/gui/cookiesdialog.cpp
src/gui/mainwindow.cpp

Previously it only handle the case of failed lookup, now it discard invalid values when deserializing the database from disk.
Also checks whether the data is convertible to the intended type.

Improve load data behavior of SettingsStorage class

---

src/base/preferences.cpp
src/base/preferences.h
src/gui/aboutdialog.cpp
src/gui/aboutdialog.h
src/gui/banlistoptionsdialog.cpp
src/gui/banlistoptionsdialog.h
src/gui/downloadfromurldialog.cpp
src/gui/downloadfromurldialog.h
src/gui/ipsubnetwhitelistoptionsdialog.cpp
src/gui/ipsubnetwhitelistoptionsdialog.h
src/gui/optionsdialog.cpp
src/gui/optionsdialog.h
src/gui/previewselectdialog.cpp
src/gui/search/pluginselectdialog.cpp
src/gui/search/pluginselectdialog.h
src/gui/search/pluginsourcedialog.cpp
src/gui/search/pluginsourcedialog.h
src/gui/speedlimitdialog.cpp
src/gui/speedlimitdialog.h
src/gui/statsdialog.cpp
src/gui/statsdialog.h
src/gui/torrentcreatordialog.cpp
src/gui/torrentoptionsdialog.cpp
src/gui/torrentoptionsdialog.h
src/gui/trackerentriesdialog.cpp

This applies to "About Dialog", "Ban List Options Dialog", "Download From URL Dialog", "IP Subnet Whitelist Options Dialog", "Search Plugin Select Dialog", "Search Plugin Source Dialog", "Statistics Dialog", "Speed Limit Dialog" and "Torrent Options Dialog".

Remember dialog sizes

---

src/base/profile_p.cpp

Implement this [comment](https://github.com/qbittorrent/qBittorrent/issues/13519#issuecomment-710946352) to attempt to fix #13519 and close #14177 (dup).

On Linux use legacy 'data' directory only as a fallback

---

src/webui/www/private/scripts/prop-files.js

WebUI: Correctly represent torrent content structure

---

src/gui/addnewtorrentdialog.cpp
src/gui/addnewtorrentdialog.ui
src/gui/categoryfilterwidget.cpp
src/gui/executionlogwidget.cpp
src/gui/mainwindow.cpp
src/gui/properties/peerlistwidget.cpp
src/gui/properties/propertieswidget.cpp
src/gui/properties/propertieswidget.ui
src/gui/properties/trackerlistwidget.cpp
src/gui/rss/automatedrssdownloader.cpp
src/gui/search/searchjobwidget.cpp
src/gui/tagfilterwidget.cpp
src/gui/transferlistfilterswidget.cpp
src/gui/transferlistwidget.cpp

* Move menu actions out of .ui files
* Add ability to prioritize selected items
Closes #2834.
* Remove redundant variable declarations

Add ability to prioritize selected items by shown file order

---

src/base/bittorrent/torrentimpl.cpp

Fixes the issue described in https://github.com/qbittorrent/qBittorrent/issues/3896#issuecomment-771194748.

Improve handling of "missing files" torrents

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/base/bittorrent/torrentimpl.cpp
src/gui/transferlistmodel.cpp
src/webui/api/serialize/serialize_torrent.cpp

This addresses https://github.com/qbittorrent/qBittorrent/pull/14335#issuecomment-774667836
The WebAPI is not affected as a workaround is added.

Revise getter function for torrrent queue position

---

src/base/utils/misc.cpp
src/base/utils/misc.h

* Fix potential out-of-bounds access
* Use std::optional to return results

Fix potential out-of-bounds access

---

src/gui/transferlistsortmodel.cpp
src/gui/transferlistsortmodel.h

Support sub-sorting in Transferlist

---

src/app/application.cpp
src/base/CMakeLists.txt
src/base/base.pri
src/base/bittorrent/infohash.cpp
src/base/bittorrent/infohash.h
src/base/bittorrent/magneturi.cpp
src/base/bittorrent/session.cpp
src/base/bittorrent/torrentimpl.cpp
src/base/bittorrent/tracker.cpp
src/base/digest32.h
src/gui/addnewtorrentdialog.cpp
src/gui/properties/propertieswidget.cpp
src/gui/transferlistsortmodel.h
src/gui/transferlistwidget.cpp
src/webui/api/serialize/serialize_torrent.cpp
src/webui/api/synccontroller.cpp
src/webui/api/torrentscontroller.cpp

This should help with improving libtorrent-2 support (not only).

Improve "info hash" handling

---

src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/gui/advancedsettings.cpp
src/gui/advancedsettings.h
src/webui/api/appcontroller.cpp
src/webui/www/private/rename_file.html
src/webui/www/private/views/preferences.html

* Add missing semicolon
* Expose ToS setting from libtorrent
Closes #14420.

Expose ToS setting from libtorrent

---

src/app/application.cpp

This would avoid the unwanted effect of replacing parameter coming from another parameter.

Replace parameters in one step

---

src/base/net/smtp.cpp
src/base/net/smtp.h

Make current codebase more compatible with Qt 6.

Don't use deprecated QTextCodec

---

src/gui/mainwindow.cpp
src/gui/torrentcontentmodelitem.cpp
src/gui/utils.cpp

Makes current codebase more compatible with Qt 6.

Clean up the code

---

src/webui/www/private/confirmfeeddeletion.html
src/webui/www/private/confirmruleclear.html
src/webui/www/private/confirmruledeletion.html
src/webui/www/private/edittracker.html
src/webui/www/private/rename.html
src/webui/www/private/rename_file.html
src/webui/www/private/scripts/mocha-init.js
src/webui/www/private/setlocation.html
src/webui/www/private/views/rss.html
src/webui/www/private/views/rssDownloader.html

WebUI: Avoid decoding strings repeatedly

---

src/base/bittorrent/session.cpp

Fixes https://github.com/qbittorrent/qBittorrent/issues/12892#issuecomment-792292336

Fix bad IPv6 address format for outgoingInterfaces

---

src/webui/www/private/scripts/contextmenu.js
src/webui/www/private/scripts/download.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/file-tree.js
src/webui/www/private/scripts/filesystem.js
src/webui/www/private/scripts/preferences.js
src/webui/www/private/scripts/progressbar.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/prop-general.js
src/webui/www/private/scripts/prop-peers.js
src/webui/www/private/scripts/prop-trackers.js
src/webui/www/private/scripts/prop-webseeds.js
src/webui/www/private/views/filters.html
src/webui/www/private/views/installsearchplugin.html
src/webui/www/private/views/preferences.html
src/webui/www/private/views/rss.html
src/webui/www/private/views/rssDownloader.html
src/webui/www/private/views/search.html
src/webui/www/private/views/searchplugins.html
src/webui/www/private/views/transferlist.html

* Remove wrong parentheses
Fix up 87ad8a1.
* Make global functions immutable

Remove wrong parentheses in WebUI

---

src/gui/transferlistsortmodel.cpp

Sort invalid QDateTime values after valid values

---

.github/workflows/webui_ci.yaml
src/webui/www/.eslintrc.json
src/webui/www/.jsbeautifyrc
src/webui/www/package.json
src/webui/www/private/addpeers.html
src/webui/www/private/addtrackers.html
src/webui/www/private/confirmdeletion.html
src/webui/www/private/download.html
src/webui/www/private/edittracker.html
src/webui/www/private/index.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/misc.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/speedslider.js
src/webui/www/private/views/about.html
src/webui/www/private/views/preferences.html
src/webui/www/private/views/propertiesToolbar.html
src/webui/www/private/views/rss.html
src/webui/www/private/views/rssDownloader.html
src/webui/www/private/views/search.html
src/webui/www/private/views/searchplugins.html
src/webui/www/public/index.html

The new CI in github actions will lint code and check code formatting for js, html files.

Add WebUI checking to CI

---

.github/workflows/webui_ci.yaml
src/gui/transferlistsortmodel.cpp
src/webui/www/.eslintrc.json
src/webui/www/.jsbeautifyrc
src/webui/www/package.json
src/webui/www/private/addpeers.html
src/webui/www/private/addtrackers.html
src/webui/www/private/confirmdeletion.html
src/webui/www/private/download.html
src/webui/www/private/edittracker.html
src/webui/www/private/index.html
src/webui/www/private/scripts/client.js
src/webui/www/private/scripts/dynamicTable.js
src/webui/www/private/scripts/misc.js
src/webui/www/private/scripts/prop-files.js
src/webui/www/private/scripts/speedslider.js
src/webui/www/private/views/about.html
src/webui/www/private/views/preferences.html
src/webui/www/private/views/propertiesToolbar.html
src/webui/www/private/views/rss.html
src/webui/www/private/views/rssDownloader.html
src/webui/www/private/views/search.html
src/webui/www/private/views/searchplugins.html
src/webui/www/public/index.html

Backport to v4_3_x (#14619, #14590)

---

CMakeLists.txt
configure
configure.ac
m4/qbittorrent.m4
src/app/CMakeLists.txt
src/app/qtlocalpeer/qtlocalpeer.cpp
src/base/rss/rss_autodownloadrule.cpp
src/base/rss/rss_parser.cpp
src/base/utils/string.cpp
src/base/utils/string.h
src/gui/properties/propertieswidget.cpp
src/gui/rss/automatedrssdownloader.cpp
src/gui/search/searchjobwidget.cpp
src/gui/torrentcontentfiltermodel.cpp
src/gui/transferlistwidget.cpp
src/webui/webapplication.cpp

Targets 4.3.x branch.
Partially reverts 4037143 and fully 3b74817
Closes #14611
@Kolcha can you confirm that it builds and works?

Lower Qt requirement to 5.11

---

src/gui/downloadfromurldialog.cpp

Move cursor to the next line of end of text

---

src/app/filelogger.cpp
src/app/main.cpp
src/base/bittorrent/session.cpp
src/base/bittorrent/session.h
src/base/net/reverseresolution.cpp
src/base/net/reverseresolution.h
src/base/settingsstorage.cpp
src/gui/addnewtorrentdialog.cpp
src/gui/properties/piecesbar.cpp
src/gui/properties/piecesbar.h
src/gui/properties/propertieswidget.cpp
src/gui/torrentcontentmodel.cpp

I will add here those changes that can be integrated into the current codebase without a major headache. Most of them will be added conditionally. But some (for example, the first commit) should be added unconditionally, so if you think I should add some explanations in the code in the form of comments, then ask for it.

Make current codebase more compatible with Qt6

---

src/gui/translators.html

Remove my name from translation credits

Remove contributor as requested

---

src/webui/www/private/views/search.html

Remove unnecessary URL encoding
