- src/preferences/preferences.cpp
Simplify logic of related functions.
Make sure that all open handles are closed.
Explicitly use Unicode versions of Windows API functions.
Prevent max subkey length overwrite.
Use Windows API style of variable names.
Fix heap corruption during Registry access.
> Improve Windows Registry searching for Python.

- src/webui/abstractrequesthandler.h
- src/webui/btjson.cpp
- src/webui/btjson.h
- src/webui/requesthandler.cpp
- src/webui/requesthandler.h
- src/webui/webapplication.h
- src/webui/www/public/downloadlimit.html
- src/webui/www/public/scripts/client.js
- src/webui/www/public/scripts/mocha-init.js
- src/webui/www/public/uploadlimit.html
```sync/maindata``` request is used to synchronize torrents data, labels, server state (transfer speed, transfer speed limit, connection state, etc.) with web client. Response of ```sync/maindata``` request will contain only the changed data from the previous request if ID of previous request ( ```rid``` ) was passed to the request.
> Web API: Implement sync/maindata request

- src/webui/www/public/preferences_content.html
Passing objects to push() seems to be broken on Firefox, making the
preferences impossibile to use when there are watched folders.
Fix this by passing strings instead of elements.
> WebUI: Fix watched folders on Gecko

- src/properties/peerlistwidget.cpp
It's useless to copy only the IP address, the port is also need to connect. With this PR it's copied the IP and the port in the same format than uTorrent.
> Copy selected peers (IP:Port)

- macxconf.pri
- src/about_imp.h
- src/dnsupdater.cpp
- src/mac/qt.conf
- src/qtlibtorrent/qbtsession.cpp
- src/torrentcreator/torrentcreatorthread.cpp
Qt5 on OS X apparently does not add ```-stdlib=libc++``` to *CXXFLAGS* or *LFLAGS*, so they must be added by us for compilation to succeed. Fix packaging by removing erroneous ```Prefix``` entry from the Mac *qt.conf*, change translation install location.
Fixes #2133
> Fix OS X compilation and packaging

- src/application.cpp
Fix compilation on OS X >10.8 by including headers for QFont.
Without this, I get the following error during compilation on OS X 10.10 with both Qt4 and Qt5:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -g -O2 -stdlib=libc++ -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE -DWITH_GEOIP_EMBEDDED -DTORRENT_LINKING_SHARED -DBOOST_ASIO_DYN_LINK -DBOOST_ASIO_ENABLE_CANCELIO -DBOOST_EXCEPTION_DISABLE -DBOOST_ASIO_HASH_MAP_BUCKETS=1021 -DTORRENT_USE_OPENSSL -DWITH_GEOIP_EMBEDDED -DQT_NO_DEBUG_OUTPUT -DVERSION_MAJOR=3 -DVERSION_MINOR=2 -DVERSION_BUGFIX=0 -DVERSION_BUILD=0 -DVERSION=\"v3.2.0alpha\" -DQT_NO_CAST_TO_ASCII …
```
> Include QFont headers for OS X

- src/core/preferences.cpp
The first time you create a new torrent, in the TrackerList textbox appears your home dir.
> Fix: default settings in "Create Torrent" dialog

- src/gui/previewlistdelegate.h
- src/gui/properties/proplistdelegate.h
- src/gui/transferlistdelegate.cpp
I have removed the decimal when it is 100%. Doesn't have sense to have 100.0 when can't be greater than 100. Also because 100% occupies a similar size to xx,x% (100.0% is bigger).
> Small change in progress bar percentage

- src/gui/searchengine/nova/engines/mininova.py
- src/gui/searchengine/nova/engines/versions.txt
- src/gui/searchengine/nova3/engines/mininova.py
- src/gui/searchengine/nova3/engines/versions.txt
This error only happens with some search terms.
Test:
```
[ngosang@ngo qBittorrent]$ python nova2.py mininova all x264
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python3.4/threading.py", line 921, in _bootstrap_inner
self.run()
File "src/searchengine/nova3/nova2.py", line 110, in run
self.engine.search(self.what, self.cat)
File "/home/ngosang/qBittorrent/src/searchengine/nova3/engines/mininova.py", line 108, in search
parser.feed(res_tab)
File "/home/ngosang/qBittorrent/src/searchengine/nova3/sgmllib3.py", line 98, in feed
self.goahead(0)
File "/home/ngosang/qBittorrent/src/searchengine/nova3/sgmllib3.py", line 132, in goahead
k = self.parse_starttag(i)
File "/home/ngosang/qBittorrent/src/searchengine/nova3/sgmllib3.py", line 290, in parse_starttag …
```
> Fix: error in mininova search engine

- src/gui/transferlistfilterswidget.cpp
- src/gui/transferlistfilterswidget.h
Adds "Remove empty labels" in the context menu and puts "Add label.." in first place.
Related with #2256 and #2491.
> New feature: Remove empty labels

- src/gui/transferlistwidget.cpp
- src/gui/transferlistwidget.h
Implementation of feature request #2452 
Adds a new option in the right-click menu of the torrent list to copy the name(s) of selected torrent(s) to the clipboard. This is similar to the existing option to copy the magnet links to the clipboard.
This patch was originally authored by Chris Hirst (ciaobaby, @chrishirst ). I changed the item name from "Copy caption" to "Copy name" (the torrent list column header says "Name"), and I added the missing line in the header file.
Note: Translations are not updated for the English menu item "Copy name".
> Add "Copy name" option in right-click menu of torrent list

- src/webui/www/public/scripts/client.js
Because of the recent changes the browser title is updated only when the server state changes, so the browser title is not always immediately updated (basically when there's no transfer going on).
> WebUI: Update browser title even with no transfer going on

- src/webui/btjson.cpp
If the offset is negative, it must be added to the current list size.
> WebUI: Fix negative offsets when requesting torrent list

- src/webui/www/public/preferences_content.html
The 'checked' attribute does not require any value, so for unckecked
checkboxes nothing should be added.
Fix f16b7614a147.
> WebUI: Fix checkboxes of the watched folder list in the preferences

- src/gui/rss/automatedrssdownloader.cpp
- src/gui/rss/automatedrssdownloader.h
- src/gui/rss/rss_imp.cpp
With on_finished shows a warning in the console when RSS Downloader is opened.
The RSS feeds are updated when the function RssFolder::addStream is called.
> Removes several warnings related with RSS

- src/core/qtlibtorrent/qbtsession.cpp
> Let the OS decide the default interface regardless of IPv4/IPv6. Closes #2156.

- configure
- m4/qbittorrent.m4
To compare strings, = should be used instead of ==.
Closes #2627.
> Use correct operator to compare strings in configure script

- src/gui/mainwindow.cpp
shutdownCleanUp() had been removed with 458b216b74e1 ("MainWindow cleanups.")
> Remove dead connection from MainWindow

- src/gui/rss/rssdownloadrule.cpp
These members were uninitialized before.
> Initialize class members

- src/core/qtlibtorrent/qtorrenthandle.cpp
Trying to get the number of files of a torrent with no metadata causes
a crash. Prevent this by first checking if the metadata is available.
If the number of files can't be determined, -1 will be returned.
Closes #2522.
> Use out of range value when the number of files can't be determined

- src/webui/btjson.cpp
Currently QJsonDocument::fromVariant() does not support QVariantHash,
so use QVariantMap instead.
Closes #2849.
> WebUI: Use QVariantMap instead of QVariantHash

- src/core/qtlibtorrent/torrentmodel.cpp
Fixes #2360. It also displays the hash when the torrent has no name.
More details in the comments of the code.
> Changes torrent name when metadata is retrieved. Closes #2360.

- src/webui/btjson.cpp
Currently QJsonDocument::fromVariant() does not support QVariantHash,
so convert the torrent list to QVariantMap.
Closes #2849.
> WebUI: Convert torrent list from QVariantHash to QVariantMap

- src/gui/mainwindow.cpp
In some cases QApplication::aboutToQuit() signal not emitted on
Windows. This happened when qBittorrent is started with both "Show
minimized" and "Minimize to system tray" enabled.
Also fix MainWindow::writeSettings() called twice on application exit.
> Fix aboutToQuit signal is not emitted on Windows.

- .gitignore
- src/app/application.cpp
- src/core/preferences.cpp
- src/webui/abstractwebapplication.cpp
Three littles modifications:
* Add "qbittorrent-nox" to the gitignore like is brother "qbittorrent"
* Fix a bug that prevent webUI startup information to print in the console with qbittorrent-nox
* Fix login.html JavaScript bug. There is a quote in the French translation that is not escape. So all the JavaScript doesn't compile. I just replace quotes by double quotes for QBT_TR strings
> login.html escape quotes + add qbittorrent-nox to gitignore + bug with startup info with qbittorrent-nox

- src/src.pro
The result is 1.9% smaller binary size, i.e. 1MB smaller binary on my linux machine.
> Increase resource files compression level

- unixconf.pri
This allow installing icons, appdata and desktop files into a
directory outside the prefix. This comes in handy on a multiarch
layout, where arch specific stuff goes into /usr/${host}/{bin,lib}
but arch independent files still into /usr/share.
> Use DATADIR for installation of icons and appdata

- src/app/application.cpp
I've had this fixed locally for months and just realized that I never submitted it. Anyways, compilation of `src/app/application.cpp` on 3.2.0 has failed on OS X ever since 0c50a8b.
```
app/application.cpp:223:13: error: use of undeclared identifier 'running_'
if (running_)
^
app/application.cpp:226:13: error: use of undeclared identifier
'paramsQueue_'; did you mean 'm_paramsQueue'?
paramsQueue_.append(path);
^~~~~~~~~~~~
m_paramsQueue
app/application.h:88:17: note: 'm_paramsQueue' declared here
QStringList m_paramsQueue;
^
2 errors generated.
Makefile:36238: recipe for target 'application.o' failed
```
It seems that `running_` and `paramsQueue_` were used mistakenly, as they don't appear anywhere else. So I have switched those identifiers to `m_running` and `m_paramsQueue`, which are …
> Fix variable names

- configure
- configure.ac
- src/gui/geoip/geoip.pri
Somebody shuffled this stuff around but forgot to update the supporting references. I was confused for a while until I figured it out. Would've been much more obvious to me if these references had been updated as well.
> Removing the confusion caused by moving GeoIP code/.dat

- src/gui/torrentcreator/torrentcreatordlg.cpp
> Disable Auto piece size checkbox when creating a new torrent

- src/gui/options.ui
- src/gui/options_imp.cpp
- src/gui/options_imp.h
The UI did not allow users to set unbounded up/down limits for alt global rate limits, but did allow it for regular global rate limits. The rest of the code treats everything appropriately, it was purely a UI limitation. It seemed silly to me that I would have unbounded down for regular limits and then have to set 99999 KB/s on my alt download limit to alter just my upload rate.
> Treating Alt Global Rate Limits Like Regular Global Rate Limits

- src/gui/mainwindow.cpp
- src/gui/options_imp.cpp
On windows (not sure about OSX), theme color can be changed too. So why not let users have more choices?
> Enable to choose dark/light tray icons on all platforms.

- src/gui/properties/propertieswidget.cpp
- src/gui/properties/propertieswidget.h
Allow to open only one file at a time and ignore keypresses when multiple items are selected.
> Allow to Open files from the properties pane by pressing "Enter"

- src/gui/transferlistfilterswidget.cpp
The current label text is hard to read (which is using `SmallCaps`).
I suggest changing it to `AllUppercase`.
Comparison:
Old:
New:
> Use AllUppercase for label text

- src/gui/rss/automatedrssdownloader.cpp
Save the rules as soon as they are edited so that the matching
articles tree is immediately updated.
Closes #2829.
> Update matching RSS articles while editing rules

- src/core/net/dnsupdater.cpp
- src/core/net/downloadmanager.cpp
- src/searchengine/nova/helpers.py
- src/searchengine/nova3/helpers.py
This commit is to keep consistency.
qBittorrent User-Agent: qBittorrent/v3.3.0
Firefox User-Agent (to avoid bans): Mozilla/5.0 (X11; Linux i686; rv:38.0) Gecko/20100101 Firefox/38.0
This is the last Firefox version and an incomplete User-Agent can be suspicious.
> Changes in User-Agents

- src/core/utils/fs.cpp
- src/core/utils/fs.h
- src/searchengine/searchengine.cpp
It came to me that for some reason qBittorent removes only python2 cache while python3 cache is stored into separated directory ```__pycache__```
So here is small commit to change that.
Found in google some idea for simple recursive dir removal hope it is fine :)
> [search engine] Remove python3 cache during updateNova()

- src/core/bittorrent/torrenthandle.cpp
Return null QDateTime object when converting from 0 time_t value.
According to libtorrent doc:
```c++
// the posix-time when this torrent was finished. If the torrent is not
// yet finished, this is 0.
time_t completed_time;
```
> Fix time_t 0 special meaning.

- dist/unix/qBittorrent.appdata.xml
Usage of the <updatecontact/> breaks validation. The correct tag is <update_contact/> as per info on this page:
http://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-update_contact
> Update qBittorrent.appdata.xml (invalid tag)

- src/app/main.cpp
- src/core/bittorrent/session.cpp
- src/gui/mainwindow.cpp
- src/gui/mainwindow.ui
- src/gui/options_imp.cpp
- src/gui/properties/propertieswidget.cpp
- src/gui/properties/trackerlist.cpp
- src/gui/rss/cookiesdlg.cpp
- src/gui/rss/rss_imp.cpp
- src/gui/transferlistfilterswidget.cpp
- src/webui/webui.cpp
- src/webui/www/private/index.html
- src/webui/www/public/download.html
- src/webui/www/public/scripts/mocha-init.js
Most of them are minor changes. I want to discuss about other changes:
* "Add &link to torrent..." in menu "File" => "Add torrent &link..."
* "Options" in menu "Tools" => "Preferences" (maybe move to "Edit" menu)
* "Transfers" / "Transfers list" => "Downloads" / "Downloads list" (in some places it is called in one way and others another)
I don't know why but the first two messages in the log window are not translated:
* 30/03/15 16:10 - qBittorrent v3.2.0beta started => The traslated string exists but it's not used.
* 30/03/15 16:10 - Peer ID: -qB3200- => It's in src/core/qtlibtorrent/qbtsession.cpp:134 but I don't know how to mark it for translation.
I think there is an Issue related to rename priority buttons but can't find.
> Changes in typography

- .travis.yml
- README.md
First, create a new (official) project on [Coverity Scan](https://scan.coverity.com/), better do it in advance, it took me a few days to get approved.
Second, create a new git branch "coverity_scan" which correspond to the variable `coverity_branch` in travis.yml. Every update on this branch will run a new scan.
Update these variables in travis.yml:
`global.secure`: replace with the new hash generated by Coverity
`addons.coverity_scan.project.name`
`addons.coverity_scan.notification_email`
Last, in Readme.md
point Coverity badge to show the correct project status
> Hookup to Coverity Scan, Closes #2601

- src/webui/webapplication.cpp
Problem:
After selecting "exit qbittorrent" in webui, the browser doesn't change to the "qBittorrent has been shutdown." page.
I hooked up wireshark, and confirmed that qB didn't response `200 OK` after receiving shutdown command.
The immediate  `singleShot(0,,)` doesn't give qB enough time to send out response.
Only observable on windows builds; linux builds behave correctly...and browser version/os doesn't matter.
> WebUI: add delay in shutdown command in order to send out response msg

- src/core/bittorrent/torrenthandle.cpp
- src/core/bittorrent/torrenthandle.h
There was some problem. New torrents added in the "No ratio limit" mode. Now all correctly - using "Use global ratio limit" for new torrents.
> Fix ratio limit for new torrents. Closes #3210.

- src/core/utils/misc.cpp
The old code could allow `i = 6`, while `units[]` only has a size of 5. And also simplify the code a bit.
> Fix potential out-of-bound access in misc::friendlyUnit()

- src/app/app.pri
- src/app/main.cpp
- src/app/upgrade.h
- src/core/bittorrent/session.cpp
- src/core/utils/fs.cpp
I've implemented simple upgrade feature.
I brought it to a separate file so that it's easier to remove it. 
In this case, I did not change anything in BitTorrent::Session. Update code only copies the old files to the new location (with slight modifications where necessary). Session runs as always.
I was not too wise with the text (I'm not good at this), so if there are any suggestions, I'll fix it.
> Upgrade to v3.3

- src/core/bittorrent/torrenthandle.cpp
- src/core/bittorrent/torrenthandle.h
- src/gui/properties/propertieswidget.cpp
- src/gui/properties/propertieswidget.ui
Added a bunch of info fields:
BTW, I was trying to shrink the default height of the `Comment:` text box, but I can't find anything to control it...
---
LATEST VERSION (will update when code changed):
> Revamp general tab info, closes #982

- src/gui/downloadfromurldlg.ui
"Download from urls" dialog can be opened by a keyboard shortcut. But, after the text box opens, the tab key doesn't work to change focus to the "Download" button and nor does the return key, so we need to use the mouse.
Understandably, the return key is needed to make the links one per line, but I did not find a reason for the use of tab in the textbox, so we can use tab to change the focus. 
This allows tab key to change focus. A new torrent from magnet link can be now added completely with the keyboard without needing to even touch the mouse.
> Download-from-URL textbox change focus on tab key

- src/gui/downloadfromurldlg.h
As title. I personally think downloadFromURL dialog should be kept open instead of closing it.
> Don't close downloadFromURL dialog when showing empty url warning.

- src/webui/www/private/index.html
- src/webui/www/public/about.html
- src/webui/www/public/css/Layout.css
- src/webui/www/public/css/style.css
- src/webui/www/public/preferences.html
- src/webui/www/public/preferences_content.html
- src/webui/www/public/scripts/client.js
- src/webui/www/public/scripts/dynamicTable.js
- src/webui/www/public/scripts/mocha-init.js
**UPDATED!!!**
**[Web UI] Changes in menus to keep the client's style**
* Capitalize menu titles #3214
* Added priority buttons in Edit menu (this is necessary if the Top Toolbar is hidden)
* Exit confirmation dialog #3073
* Simplify Help menu #3214
* Queue number (#) is now the first column (if it's enabled) #2808
* Rework About window to show links to the Website, Bug tracker and Forum. #3214
* Add magnet now is the first icon in the Top Toolbar
* Fix icons in transfers list for states forcedDL, metaDL and forcedUP.
**[Web UI] Option to hide Top Toolbar**
* Added View => Top Toolbar feature to show/hide the Top Toolbar.
**[Web UI] Reorder the tabs/groups in Options window**
* Now the tabs are Downloads, Connection, Speed (**new**), BitTorrent and WebUI (Proxy and Ip filter **removed**) …
> [Web UI] Changes in menus, new features and reordered Options.

- src/gui/about_imp.h
Before this may appear as
C+
+
or
C
++
> Fix ugly 'C++' wrapping in About dialog.

- src/searchengine/nova/engines/torrentreactor.py
- src/searchengine/nova/engines/versions.txt
- src/searchengine/nova3/engines/torrentreactor.py
- src/searchengine/nova3/engines/versions.txt
Now returns more accurate results. This PR filter the TorrentReactor results to discard unrelated results. Related #3256
Changed the domain and the search URL to avoid 3 redirections in each query.
> [search engine] Update TorrentReactor

- src/core/unicodestrings.h
- src/core/utils/misc.cpp
- src/gui/about.qrc
- src/gui/about.ui
- src/gui/about_imp.h
- src/gui/addnewtorrentdialog.cpp
- src/gui/gpl.html
- src/gui/options_imp.cpp
- src/gui/properties/propertieswidget.cpp
- src/gui/speedlimitdlg.cpp
- src/gui/thanks.html
- src/gui/transferlistdelegate.cpp
- src/gui/translators.html
Still one warning remains, but there isn't any unicode character at there:
```
gui\options_imp.cpp(621) : warning C4819: The file contains a character that cannot be represented in the current code page (950). Save the file in Unicode format to prevent data loss
```
I have no idea how to fix it...
> Fix MSVC2013 complains on Unicode characters

- src/gui/torrentcreator/createtorrent.ui
- src/gui/torrentcreator/torrentcreatordlg.cpp
> Add 16 KiB, 8 MiB and 16 MiB piece sizes in Torrent Creator

- src/gui/torrentcontentmodelfolder.cpp
**With the old code:**
The old code was completely wrong because it's calculating the average value of progress without weighting the size.  In the screenshot the real total progress it's around 33.7 % but as you can see the result is 83.4 % The code reach this number doing:
100 + 33.7 + 100 + 100 = 333.7
333.7 / 4 = 83.4 %
**With the new code:**
33.7 * size2 gives you the downloaded size of these file.
total_size = size1 + size2 + size3 + size4
(100 * size1 + 33.7 * size2 + 100 * size3 + 100 * size4) / total_size = 33.7 %
> Fix progress calculation in Content tab. Closes #2639 Closes #2752

- src/core/preferences.cpp
- src/core/preferences.h
- src/gui/advancedsettings.h
- src/gui/transferlistwidget.cpp
Adds this line in Advanced options
to disable this dialog:
> MrKB: Is there a way to make qBittorrent stop asking me if I'm sure I want to perform a recheck? It's annoying: http://i.imgur.com/ng1tlSS.png
> Sc0rpius: I don't see why you need to recheck, since if you know your bittorrent protocol, you should know that every piece is checked after download
> Sc0rpius: recheck is only useful if: a.- you deleted a file externally from qBittorrent by mistake, b.- a fatal error happened (like full disk)
> MrKB: Because sometimes I need to verify that something I did didn't change the files I'm seeding.
> Sc0rpius: you shouldn't work in the files directly, you should seed copies that you're not gonna use
> MrKB: For example: fb2k not messing with ID3 tags of albums I'm still seeding.
> MrKB: …
> Implement an option to disable confirmation of torrent recheck

- src/searchengine/nova/engines/extratorrent.py
- src/searchengine/nova/engines/versions.txt
- src/searchengine/nova3/engines/extratorrent.py
- src/searchengine/nova3/engines/versions.txt
> [search engine] Remove the word 'torrent' in ExtraTorrent results

- src/webui/abstractwebapplication.cpp
Environment:
Firefox 39.0 & qbtorrent running in ArchLinux.
When I use Firefox 39.0 to connect to `127.0.0.1:8080` (webUI), log from qbtorrent says the source IP is from `::ffff:127.0.0.1`.
This could be a QT issue, but we can also fix it locally.
See: https://en.wikipedia.org/wiki/IPv6_transition_mechanism#Stateless_IP.2FICMP_Translation
> Fix translated localhost address (::ffff:127.0.0.1) is not recognized

- src/core/utils/misc.cpp
- src/gui/mainwindow.cpp
* Simplifies the code
* If python2 & python3 executables are not detected in UNIX tries to find python.
* Always obtain the python version from the command output instead of assume `python2 => version = 2` (https://github.com/qbittorrent/qBittorrent/blob/f6bbd9377f99cf50c282da6e62791dca92797044/src/core/utils/misc.cpp#L262)
* Show a message in the log when python is not detected.
* Fix a translation problem, two different string for the same message:https://github.com/qbittorrent/qBittorrent/blob/f6bbd9377f99cf50c282da6e62791dca92797044/src/gui/mainwindow.cpp#L1387 and
https://github.com/qbittorrent/qBittorrent/blob/f6bbd9377f99cf50c282da6e62791dca92797044/src/gui/mainwindow.cpp#L1410
> Improve Python detection

- src/gui/properties/propertieswidget.cpp
- src/gui/transferlistdelegate.cpp
- src/webui/btjson.cpp
- src/webui/www/public/css/style.css
- src/webui/www/public/properties_content.html
- src/webui/www/public/scripts/misc.js
- src/webui/www/public/scripts/prop-general.js
Added changes from #3078 and #3270.
It's necessary to update the API documentation. https://github.com/qbittorrent/qBittorrent/pull/3040#issuecomment-107954174 New parameters added (no deletions)
```
/**
* Returns the properties for a torrent in JSON format.
*
* The return value is a JSON-formatted dictionary.
* The dictionary keys are:
*   - "time_elapsed": Torrent elapsed time
*   - "seeding_time": Torrent elapsed time while complete
*   - "eta": Torrent ETA
*   - "nb_connections": Torrent connection count
*   - "nb_connections_limit": Torrent connection count limit
*   - "total_downloaded": Total data uploaded for torrent
*   - "total_downloaded_session": Total data downloaded this session
*   - "total_uploaded": Total data uploaded for torrent
*   - "total_uploaded_session": Total …
```
> [Web UI] Add information in General tab

- .travis.yml
- INSTALL
- configure
- configure.ac
- src/core/bittorrent/infohash.h
- src/core/bittorrent/magneturi.cpp
- src/core/bittorrent/peerinfo.cpp
- src/core/bittorrent/session.cpp
- src/core/bittorrent/torrentcreatorthread.cpp
- src/core/bittorrent/torrenthandle.cpp
- src/core/bittorrent/torrenthandle.h
- src/core/logger.cpp
- src/core/logger.h
- src/core/net/portforwarder.cpp
- src/core/net/portforwarder.h
- src/core/preferences.cpp
- src/core/preferences.h
- src/gui/executionlog.cpp
- src/gui/options_imp.cpp
- src/gui/properties/trackerlist.cpp
- src/gui/properties/trackerlist.h
- src/webui/prefjson.cpp
@sledgehammer999 If you still decide to drop support for outdated libtorrent-0.16.x, you will simply merge this PR.
> Drop libtorrent 0.16.x support.

- src/gui/properties/propertieswidget.cpp
- src/gui/torrentmodel.cpp
IMHO, this is more correct.
Example:
```
Single-file torrent
Before: /home/asdf/Desktop/torrent_test/ubuntu-14.04.2-desktop-amd64.iso
After:  /home/asdf/Desktop/torrent_test/
Multi-file torrent
Before: /home/asdf/Desktop/torrent_test
After:  /home/asdf/Desktop/torrent_test/Wallpapers_HQ    <--this is the root folder of the downloaded data
```
> Use `rootPath()` in save path field

- src/core/bittorrent/torrenthandle.cpp
- src/core/bittorrent/torrenthandle.h
To fix issue #2107.
I was thinking it could be fixed by counting rename events at [torrenthandle.cpp#L1298 ](https://github.com/qbittorrent/qBittorrent/blob/de84bb98245365425eb8e6d8ff471e92456908f2/src/core/bittorrent/torrenthandle.cpp#L1298) and [torrenthandle.cpp#L1535](https://github.com/qbittorrent/qBittorrent/blob/de84bb98245365425eb8e6d8ff471e92456908f2/src/core/bittorrent/torrenthandle.cpp#L1535).
Unfortunately I cannot reproduce that issue, even before my commit, so I have no clue if that problem really existed or not (or it's fixed in my commit).
However I can see my code is working.
> Fix "Run External Program Launches too Early" issue

- src/app/application.cpp
- src/core/bittorrent/session.cpp
- src/gui/rss/rssparser.cpp
* `MAX_TRACKER_ERRORS` and `longMonth` are unused vars.
* `pref = Preferences::instance()` unused var in nox build.
**Finally not included:**
* `QMetaType::Float` I tested it and seems that everything is working but please review it carefully. I found the fix here https://stackoverflow.com/questions/31290606/qmetatypefloat-not-in-qvarianttype
> Fix 3 compiler warnings

- src/core/utils/misc.cpp
The comment in the code explains why this is needed.
@glassez can you take a look a tell if I am ok with the WINAPI usage? I am not too confident on my C skills.
@pmzqla @ngosang @Chocobo1 @glassez @Gelmir 
This isn't finished. While it fixes the problem stated in the commit, it is broken in another way.
If the file resides in folders that have letters explorer.exe still shows the default path. If the path has only folders with digit names it works. Example:
```
G:\myfolder\file.mkv  --> doesn't work
G:\12\file.mkv  --> works
```
Printing the `cmd` variable and using its contents via the terminal it works!!!
I cannot understand what the problem is here.
Any ideas?
> Fix a bug with highlighting selected file on Windows. Closes #3185.

- src/app/application.cpp
- src/gui/properties/propertieswidget.cpp
- src/gui/torrentmodel.cpp
- src/webui/btjson.cpp
Before:
`C:/a/b/`
After: 
`C:\a\b\`
~~It's probably a copy-paste error in `savePath()` & `actualSavePath()`, not sure about it.~~
> Use native path separators

- src/gui/mainwindow.cpp
- src/gui/mainwindow.ui
- src/webui/www/private/index.html
The most used button is Top priority so must be the first.
**Previous order was:**
Lowest Decrease Increase Maximum (priority)
**Now:**
Maximum Increase Decrease Lowest (priority)
Other clients:
* http://i49.tinypic.com/2rzxduv.png
* http://imagenes.es.sftcdn.net/es/scrn/43000/43961/utorrent-21-700x386.png
* https://wiki.vuze.com/mediawiki/images/b/b9/Vuze43TorrentDetailsSources.png
> Change Queue buttons order in the Toolbar (GUI & Web UI)

- src/core/bittorrent/session.cpp
- src/core/preferences.cpp
- src/core/preferences.h
- src/gui/advancedsettings.h
- src/gui/options.ui
- src/gui/options_imp.cpp
As discussed in https://github.com/qbittorrent/qBittorrent/issues/3177#issuecomment-111364989.
Old: 
New:
Maybe change `Apply rate limit to local peers` to `Apply rate limit to peers on local network`? Any ideas?
UPDATE: I changed to `Apply rate limit to peers on LAN`.
> Move option "Ignore transfer limits on local network" to Speed page

- src/gui/advancedsettings.h
- src/gui/options.ui
- src/gui/options_imp.cpp
Due to users complaining about the OK/cancel default in torrent delete confirmation dialog, I think it's a good idea to expose this option:
This PR is based on #3481 (because it contains a cleanup), so please merge that before this, then I will rebase if needed.
> Move option "Confirm torrent deletion" to Behavior page

- src/gui/properties/speedwidget.cpp
- src/gui/properties/speedwidget.h
In windows, using QToolButton in this case seems a little bit weird, e.g. the height is smaller, the down arrow is near to bottom. It doesn't give a consistent UI feel, maybe switching it to QComboBox is better.
Below screenshot is using QT5.
Old:
New:
> Change "Select Graphs" from QToolButton to QComboBox

- src/gui/transferlistfilterswidget.cpp
- src/gui/transferlistfilterswidget.h
This was done only when favicon.ico couldn't be decoded, but not when
favicon.ico could not be downloaded at all.
> Try to download favicon.png when the download of favicon.ico fails

- src/gui/rss/rss.ui
- src/gui/rss/rss_imp.cpp
- src/gui/rss/rssarticle.cpp
- src/gui/rss/rssfeed.cpp
- src/gui/rss/rssparser.cpp
* **Handle magnet links as torrents instead of news URLs.**
Closes #3560. Some RSSs have magnet links in the URL instead of an attached torrent.
* **Trim elements text in RSS articles**
If some RSS has this format, the Articles list looks horrible because each element occupies 2 lines and the link doesn't work. Found in #3560 also.
```xml
<item>
<title>
Toco-mocho</title>
<link>
magnet:?xt=urn:btih:7YUK6RY4IPP2LTO..........</link>
....
```
* **Fix contextual menu in RSS torrents list**
Display the menu only if there are items selected and news URL is not always available (if url = magnet link)
* **Improve error handling when a RSS feed doesn't contain torrents**
There are RSS feeds without torrents or magnets which caused problems in the double click download and in the automatic download …
> [RSS] Several changes in RSSs. Closes #3560

- .travis.yml
Some issues:
* Error occurred "QtDBus not found" when compiling. Workaround by adding `--disable-qt-dbus` when doing configure.
* Some warnings issued when doing `macdeployqt`
@Noctem can you help out?
Now we can produce artifacts for osx builds, I wonder if we have a server to upload it. Of course this should only apply to master branch builds.
> TravisCI: build on osx

- src/gui/options.ui
- src/gui/options_imp.cpp
- src/gui/options_imp.h
The GUI layout cleanups are done mostly to the Speed page and it's parents widgets, other pages are not touched.
It's hard to commit each small step since one small change leads to another change and so on...
I plan to cleanup each page... this is the first step.
I applied "Follow project coding style" by running my script. I already skimmed through, a pair of fresh eyes would help catching some leftovers.
Before:
After:
[new_ver1](https://cloud.githubusercontent.com/assets/9395168/9698540/ac09dc04-53ed-11e5-95b1-91a2ba8df14e.png)
@ngosang 
You might want to try it out.
> Cleanup in options_imp

- src/core/net/downloadmanager.cpp
Recent changes in Torcache prevent adding (or drag-and-dropping) a torrent link into qBittorrent. Modifying DownloadManager to always spoof the HTTP Referer header to the file itself being downloaded solves this.
> Allow adding torrent link from Torcache

- src/core/downloadthread.cpp
Allow adding torrent link from Torcache.
Recent changes in Torcache prevent adding (or drag-and-dropping) a torrent link into qBittorrent. Modifying DownloadManager to always spoof the HTTP Referer header to the file itself being downloaded solves this.
> Backporting #3765 to v3_2_x branch

- src/webui/btjson.cpp
I'm working with the Sonarr devs to add a qBittorrent plugin (pull request at https://github.com/Sonarr/Sonarr/pull/779). There are two obstacles at the moment.
One is the inability to set a label on torrents added by Sonarr, which is resolved by the "[Web UI] Labels implementation pull" request, https://github.com/qbittorrent/qBittorrent/pull/3444. So +1 to that!
The second is that Sonarr needs to cache a download path for each torrent it sees. Because this isn't currently included in the api for /query/torrents, we need to make an extra request to /query/propertiesGeneral for every torrent in the list. Including the "save_path" field in the maps returned with /query/torrents and /sync/maindata allows us to avoid these extra requests.
> RFC: [Web UI] add save_path to /query/torrents and /sync/maindata

- src/gui/rss/rss_imp.cpp
When you **add a new RSS feed** you get this message in the console:
```
virtual bool RssFeed::refresh() Feed "https://xxxxxxxxxxxxxx" is already being refreshed, ignoring request
```
This is caused because `stream->refresh();` is called two times. It's called inside `RssFeedPtr stream = rss_parent->addStream(m_rssManager.data(), newUrl);` few lines above the removed line.
> [RSS] Removes refresh message when adding a new feed

- src/core/utils/string.cpp
- src/core/utils/string.h
- src/gui/rss/automatedrssdownloader.cpp
- src/gui/rss/automatedrssdownloader.ui
**~~WIP, don't merge yet!!~~**
-----
And also clean up the layout, capitalize strings...
I added a modified version of `naturalSort()` which IMO works better in some cases.
If possible the new version should be able to replace the old one.
BTW `naturalSort()` should be renamed to `naturalCmp()`, because it doesn't really sort, it just compare  inputs.
[old_ver1](https://cloud.githubusercontent.com/assets/9395168/8058682/a8648490-0eed-11e5-93b2-5d72cc984fd8.png)
[old_ver2](https://cloud.githubusercontent.com/assets/9395168/9930570/39d3d3be-5d67-11e5-9008-8f6199f39c9a.png)
Latest version:
Original naturalSort():
[old1](https://cloud.githubusercontent.com/assets/9395168/8058684/a9fd6556-0eed-11e5-8e31-fd4cb6629588.png)
> Sort labels in RSS Downloader dialog

- src/core/bittorrent/torrenthandle.cpp
This patch must fix #3649-related issues.
> Use default save path if save path is not set.

- src/webui/prefjson.cpp
I not tested it with Qt4, but I'm sure it works.
> Cast MaxRatioAction to int when store as JSON. Closes #3939.

- src/gui/properties/downloadedpiecesbar.cpp
- src/gui/properties/downloadedpiecesbar.h
- src/gui/properties/pieceavailabilitybar.cpp
- src/gui/properties/pieceavailabilitybar.h
- src/gui/properties/propertieswidget.cpp
- src/gui/properties/propertieswidget.ui
- src/gui/properties/proptabbar.cpp
Tooltip for progress bar:
Tooltip for availability bar:
-----
UPDATE:
`Use theme color for background in PropertiesWidget` & `Replace horizontal line with border` changes this:
Before:
After:
> Availability bar, progress bar, button group improvements

- src/core/utils/misc.cpp
- src/core/utils/misc.h
- src/gui/mainwindow.cpp
- src/gui/transferlistfilterswidget.cpp
Removed borders around transfer list & filter list.
The spacing between different set of filters is a bit larger, IMO, it was too tight before.
If any change is not preferable, it can be reverted.
Old:
New:
-----
UPDATE:
After commit `Move "Lock qBittorrent" button to the right of "Options..." buttion`:
-----
> Minor style change in transfer list & filters

- src/core/bittorrent/torrenthandle.cpp
- src/core/bittorrent/torrenthandle.h
This fixes #3895.
Functions totalPayloadUpload() and totalPayloadDownload() must be qlonglong since total_payload_upload and total_payload_download are defined as boost::int64_t size in libtorrent.
> Changed payload functions from int to qlonglong in TorrentHandle class

- src/core/bittorrent/session.cpp
- src/core/bittorrent/session.h
- src/core/utils/fs.cpp
- src/core/utils/fs.h
IMO, it makes no sense to delete torrent contents **parent** folder, no matter it is created by user or qbt.
Just deleting the folder containing the contents is enough.
#3144,  #3619 is probably related.
Should I remove `Utils::Fs::smartRemoveEmptyFolderTree()`? It's not being called anymore after this PR.
> Don't remove torrent contents parent folder, even it is empty.

- src/core/bittorrent/session.cpp
- src/core/bittorrent/session.h
- src/core/bittorrent/torrenthandle.cpp
<del>This fixes issue that may happen if you used one of the early pre-release builds of version 3.3 before.</del>
This patch is required for v3.3.
> Fix 'Append label to save path'. Closes #4031.

- src/core/preferences.cpp
- src/gui/advancedsettings.h
In #4028, the user have 16GB of system ram and running 32bit qBT. The cache size was set to 1800MB and the system throws "bad allocation" exception.
Maybe the allowed maximum should be reduced.
And a little bit refactor from the information here: http://nadeausoftware.com/articles/2012/02/c_c_tip_how_detect_processor_type_using_compiler_predefined_macros#x86andx8664
> Reduce max value of "Disk cache size"

- src/searchengine/engineselectdlg.cpp
The old code when the plugin is invalid shows the message "A more recent version of '%1' search engine plugin is already installed.", "%1 is the name of the search engine"...
> [searchengine] Fix invalid plugin message and detect new plugin URL from clipboard

- src/core/bittorrent/session.cpp
- src/core/bittorrent/session.h
- src/gui/torrentmodel.cpp
- src/gui/torrentmodel.h
- src/gui/transferlistfilterswidget.cpp
- src/gui/transferlistfilterswidget.h
Handle data changed event for all torrents at once.
Additional changes:
Calculate TorrentStatusReport only once per update.
> Some TransferListWidget speedup.

- src/core/bittorrent/session.cpp
- src/core/bittorrent/session.h
- src/core/bittorrent/torrenthandle.cpp
- src/core/bittorrent/torrenthandle.h
Hopefully this will be the last **torrent save path** fix.
> Fix default save path for magnet. Closes #4105.

- src/searchengine/nova/engines/torrentz.py
- src/searchengine/nova/engines/versions.txt
- src/searchengine/nova3/engines/torrentz.py
- src/searchengine/nova3/engines/versions.txt
Removed demonii. Reason => https://torrentfreak.com/demonii-torrent-tracker-shuts-down-for-good-151116/
> [searchengine] Update Torrentz trackers

- src/webui/www/public/css/dynamicTable.css
- src/webui/www/public/css/style.css
It reverts changes in #4111. Now selected filters in sidebar have white text.
> [WebUI] Change colors in selected filters and torrents.

- src/webui/extra_translations.h
- src/webui/webapplication.cpp
- src/webui/webapplication.h
- src/webui/www/public/download.html
- src/webui/www/public/scripts/download.js
- src/webui/www/public/scripts/mocha-init.js
- src/webui/www/public/upload.html
This patch allows people to configure save path, cookies and labels when adding torrents using the WebUI, either downloading from an URL or uploading it from the local filesystem.
This is a feature that is pretty popular in other bittorrents clients so I think qBittorrent being as great as it is should have them.
This consist in expanding the AddTorrentParams to allow passing cookies from the WebUI to the main program.
Also the webpages upload.html and download.html were changed a little bit to allow browsers to autocomplete.  The way they were designed doesn't allow browsers to autocomplete fields.  Nobody is going to paste cookies all the time in the WebUI they would want their browser to remember them.  This fix includes that as well.
> [WebUI] Add save path, cookies and labels when adding torrents

- src/gui/mainwindow.cpp
- src/gui/mainwindow.ui
- src/gui/properties/propertieswidget.cpp
- src/gui/properties/propertieswidget.ui
Border in various pages are removed, now it should align perfectly (with upper windows), see pic below.
~~I also changed the use of (our own) LineEdit to QLineEdit in Content page.~~
Old:
New:
[new_1](https://cloud.githubusercontent.com/assets/9395168/10969027/a5be2c7c-8400-11e5-9353-815a7d225f46.png)
After reduce mainwindow border width: ![new2](https://cloud.githubusercontent.com/assets/9395168/11452838/cda2ea3e-962f-11e5-8df6-b9eef43cb00a.png)
> Properties widget cleanup

- src/gui/properties/propertieswidget.cpp
- src/gui/torrentcontentfiltermodel.cpp
- src/gui/transferlistwidget.cpp
Supersedes #4164.
Uses the [WildcardUnix](http://doc.qt.io/qt-4.8/qregexp.html#PatternSyntax-enum) mode.
> Support wildcards for filtering torrent list and torrent content

- src/gui/rss/rssfeed.cpp
@sledgehammer999 this is yet another v3.3 hotfix so merge it before 3.3.1 release.
> Fix RSS isn't automarking articles as read. Closes #4260.

- .travis.yml
* Don't build with Qt4 on OSX, it's slow. Qt4 builds is covered by linux builds.
* Turn off warning on OSX builds: unused-local-typedefs.
* Reordered option list, sort by `lt_branch` then `qt` then `gui`
> [Travis CI] Don't build with Qt4 on OSX

- src/base/http/requestparser.cpp
- src/base/http/types.h
This is a fix for #4428
Basically the problem is that when several torrents are uploaded via the WebUI, a QMap is filled with this data.  The QMap m_request.files uses disposition["name"] as a key and all the files have the same HTML name attribute value ("fileselect[]").   It was changed to disposition["filename"] which has way more sense.  If you look at the code you'll see that even validates disposition["filename"] but somehow used disposition["name"] for the key:
```
if (disposition.contains("filename")) {
UploadedFile ufile;
ufile.filename = disposition["filename"];
ufile.type = disposition["content-type"];
ufile.data = data.mid(header_end + EOH.length());
m_request.files[disposition["name"]] = ufile;
}
```
That last line was changed to:
```
m_request.files[disposition["filename"]] …
```
> Multiple Torrents Uploads Fix.  Closes #4428

- src/base/bittorrent/peerinfo.cpp
- src/base/bittorrent/peerinfo.h
- src/base/bittorrent/torrentinfo.cpp
- src/base/bittorrent/torrentinfo.h
- src/gui/properties/peerlistdelegate.h
- src/gui/properties/peerlistwidget.cpp
- src/gui/properties/peerlistwidget.h
Add a new column to peers list that shows list of files which are
donwloaded right now from a peer. The column is empty if we do not
download anything from the given peer.
> Add column with list of currently downloading files

- src/searchengine/nova/engines/piratebay.py
- src/searchengine/nova/engines/versions.txt
- src/searchengine/nova3/engines/piratebay.py
- src/searchengine/nova3/engines/versions.txt
According to this => https://torrentfreak.com/registrar-shuts-down-pirate-bay-domain-names-151228/ old domains are not coming back.
According to this => https://torrentfreak.com/the-pirate-bay-switches-on-new-ms-domain-160107/ the only alive domain is https://thepiratebay.ms
> [search engine] Update PirateBay plugin. Closes #4470

- src/app/application.cpp
- src/base/bittorrent/torrenthandle.cpp
- src/base/preferences.cpp
- src/base/utils/misc.cpp
- src/gui/powermanagement/powermanagement.cpp
There is header file windows.h, not Windows.h.
MinGW on Linux build machine is filename case-sensitive.
> convert includes like <Windows.h> to lowercase

- src/base/preferences.cpp
- src/base/preferences.h
- src/gui/options_imp.cpp
This commit adds combo box that allows user to choose default magnet links handler application in Mac OS X. It is implemented in mac way. I mean that mac applications usually have such combo boxes with list of apps that can handle some URLs or documents (windows apps usually have checkbox that says make me default).
I suggest to move qBittorrent.app to /Applications deleting it from build folder to test this feature. This is needed to exclude duplicates for the same bundle ID because LSSetDefaultHandlerForURLScheme() accepts bundle ID of the app, and Launch Services "likes" when application is installed in /Applications
> Set qBittorrent as default torrent app in Mac OS

- src/base/bittorrent/session.cpp
- src/src.pro
Since we use it in the WebUI now. See #4574.
> Allow GeoIP in NoGUI builds

- src/base/bittorrent/session.cpp
This commit fixes the following scenario:
1. Set network address (1.2.3.4) in qBittorrent advanced settings and apply.
2. Network address is passed through into libtorrent session, and appended to announce strings (&ip=1.2.3.4)
3. Clear the network address in qBittorrent advanced settings and apply.
4. New setting is **not** passed through to libtorrent session, and so libtorrent continues to erroneously append the now-invalid setting (&ip=1.2.3.4).
5. For trackers which respect this field, this results in peers having an incorrect IP and thus no incoming connections.
libtorrent allows and handles this setting when it is empty string. See:
https://github.com/arvidn/libtorrent/blob/master/src/http_tracker_connection.cpp#L181-185
> Always update native session's announce_ip setting

- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/gui/gui.pri
- src/gui/options.ui
- src/gui/options_imp.cpp
IMO, it's better to divide the settings into `qBittorrent` group and `libtorrent` group, so that "power users" can know what kind of settings they are tweaking.
Before:
After:
> Group settings in advanced settings table

- src/app/main.cpp
- src/app/stacktrace_win.h
- src/app/stacktrace_win_dlg.h
It's not possible to make signal handler perfectly safe, but at least non-safe function calls is much less than before; still, that shouldn't matter, since our signal handler is for program termination :p.
In the end, it's just some cleanup.
Was trying to print more useful infos (when crashed) on windows, like exception description, but later realized that is only possible in a `try()... catch()` block.
Tested on windows & linux.
> Simplify signal handler

- src/base/bittorrent/torrenthandle.cpp
- src/gui/transferlistwidget.cpp
- src/webui/www/private/index.html
Closes #189,  #2331 and #1813. Maybe #3743.
I did a lot of tests (more than 50 different movies) and the index length is proportional to the file length. It depends on many things as the codec, framerate... but I get a fix for that.
* The AVI format has the biggest index at the end of the file.
* In most AVI files the index length is 0.25% of the total file size.
* In the worst AVI file I have found the index length is almost 1% of the total file size.
This fix always downloads the last 1% of the file.
Example: Movie 1.3 GB (5612 pieces x 256 KB)
* In the current implementation you will download 1 piece (1 x 256 KB = 256 KB)
* With this PR you will download 52 pieces (52 * 256 KB = 13 MB)
The index length will be between 2MB and 13MB but we can't know. With this fix maybe we are …
> Download more pieces in "Download first and last pieces first" feature

- src/base/bittorrent/cachestatus.cpp
- src/base/bittorrent/cachestatus.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrentcreatorthread.cpp
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
- src/base/bittorrent/torrentinfo.cpp
- src/base/bittorrent/torrentinfo.h
- src/base/bittorrent/trackerentry.h
- winconf-msvc.pri
This is a minimal set of changes that adds support for libtorrent v1.1. 
Its advantages are not used.
@sledgehammer999, The first two commits are improvements for current code and they are important in themselves. Next, I want to implement support for some innovations (in particular, a new way to get alerts you suggested) and get rid of the use of deprecated functions. This PR can (and, IMO, should) be merged without waiting for the rest.
> Add libtorrent v1.1 basic support

- src/app/upgrade.h
This is the same fix as I did to prevent loading corrupted fastresume files.
> Fix upgrade corrupted fastresume file

- src/base/bittorrent/magneturi.cpp
- src/base/bittorrent/magneturi.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
- src/base/utils/misc.cpp
- src/base/utils/misc.h
- src/gui/addnewtorrentdialog.cpp
- src/gui/addnewtorrentdialog.h
- src/webui/webapplication.cpp
Fix saving torrent to **current directory** (when empty save path passed to libtorrent).
Fix loading corrupted .fastresume file. Related to #4454.
Manage torrent save path in TorrentHandle constructor. This is the last point where we can do it, so we can be sure that we remembered to do it. (Don't worry about the fact that we now do not set the save path in the add_torrent_params before calling the async_add_torrent() function: because we run the torrent in a paused state, the actual file operations will not begin to run until the call to the TorrentHandle constructor since we call TorrentHandle::resume after it.)
> Manage save path in one place

- src/app/upgrade.h
- src/base/base.pri
- src/base/bittorrent/private/resumedatasavingmanager.cpp
- src/base/bittorrent/private/resumedatasavingmanager.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrenthandle.cpp
WARNING!
This patch swith .fastresume file naming to pre-v3.3 form: \<torrent-hash\>.fastresume.
qBittorrent silently converts all v3.3.0-v3.3.1 fastresume files to new names.
Don't worry about this! If you downgrade qBittorrent will be able to load these files (as old format fastresumes).
> Improve .fastresume saving and torrents starting up. Closes #4315.

- src/app/main.cpp
- src/base/preferences.cpp
BTW when testing this, I found the splash-screen is hidden under mainwindow, due to 0d32b9a to fix #1391. Now the splash-screen is never visible to me (unless minimize the mainwindow) rendering this option useless (on linux).
Some thoughts here:
1. Make splash-screen default off, I don't think splash-screen is a trend anymore...
2. The issue in #1391, I guess is caused by sharing the same thread with libtorrent. Merely removing the `Qt::WindowStaysOnTopHint` flag won't help much, the mainwindow could still hang, so it still need a proper fix. (Not sure this is still the case in current git master)
I would prefer doing the 1st change so that making the proper fix could be a low prio task (or even postponed forever :p).
> Fix potential race condition in showSplashScreen()

- src/gui/addnewtorrentdialog.ui
I accidentally added a vertical spacer when doing #4251.
This is a quick fix, hope you can merge in soon.
Before:
After this PR:
BTW, I am looking at #4204. There is still anomaly when downloading via magnets. I think I will postpone fixing it until there are no overlapping PRs.
> Remove additional vertical spacer.

- configure
- configure.ac
- winconf-mingw.pri
- winconf.pri
Source: https://github.com/mxe/mxe/blob/master/plugins/apps/qbittorrent-1-fixes.patch
(Change of winconf.pri was improved, commit "convert includes like <Windows.h> to lowercase" is not needed.)
> compatibility with MXE

- src/base/http/requestparser.cpp
qBittorrent currently fails API calls with an extraneous content-length: 0 header.  This allows for the extra header without returning a 400 error.
> Do not try to parse request message when content-length is 0

- src/app/stacktrace_win.h
- src/app/stacktrace_win_dlg.h
- src/base/utils/misc.cpp
- src/base/utils/misc.h
- src/gui/about_imp.h
* Shorten crash report on windows: Comment out "List of linked Modules" section.
* Also created some helper functions to get version strings.
* `Utils::Misc::osName()` output on Win8.1: `Windows 8.1 6.3.9600 x86_64`
* output on archLinux: `Arch Linux 4.4.1-2-ARCH x86_64`
> Shorten crash report on windows

- src/gui/properties/propertieswidget.cpp
Qt's tr() ate 'true' parameter, which was supposed to be for
friendlyUnit(). 
As the result, the label was reading like "1 MiB/s (1 MiB avg.)"  and '/s' was lost for the average value
> Fix typos in speed label text

- dist/unix/CMakeLists.txt
SYSTEMD_SERVICES_INSTALL_DIR includes systemd installation prefix already
> cmake: fix systemd unit install path

- src/base/http/server.cpp
- src/base/http/server.h
- src/webui/webui.cpp
This fixes issue #4896 when built with Qt5 and retains the original behavior with Qt4.
> Support SSL certificate bundles. Closes #4896.

- dist/unix/CMakeLists.txt
Fix copy-n-paste error: for non-GUI build we have to install
qbittorrent-nox.1, but not qbittorrent.1.
> cmake: fix man installation

- src/gui/addnewtorrentdialog.cpp
- src/gui/addnewtorrentdialog.h
- src/gui/addnewtorrentdialog.ui
Lazy to describe, see screenshot below.
Before:
After:
> Fix additional space in comment label

- src/base/settingsstorage.cpp
Was reading `settingsstorage` and found some minor style defects and fixed it by the way.
The (original) code is cleanly written :+1:
> Minor refactor

- src/gui/properties/peerlistwidget.cpp
- src/gui/properties/peerlistwidget.h
Copy-paste-adjusted from transferlistwidget. The only problem i've seen with this is "Resolve peer countries". If disabled in options and then the column is re-enabled via the menu it'll just be blank and i was thinking whether it's functionality can/should be attached to this menu. I tried to do it and i partially succeeded=failed. I guess it's not good to copy paste especially if it's to be done again and again for trackerlist and contents. I tried to make some kind of template and i failed (again) so i put this here in hopes that it can inspire someone to do it better.
> Add toggle columns menu for peerlist. Closes #3301

- src/base/bittorrent/peerinfo.cpp
- src/base/bittorrent/peerinfo.h
- src/base/bittorrent/torrentinfo.cpp
- src/base/bittorrent/torrentinfo.h
- src/gui/properties/peerlistdelegate.h
- src/gui/properties/peerlistwidget.cpp
- src/gui/properties/peerlistwidget.h
This reverts reversion and fixes torrent_info::map_block() call, providing the correct piece size to it. Hopefully  now it will not lead to crashes like in issue #4597
> Show downloading files in peers list. Attempt #2

- README.md
- src/base/net/dnsupdater.cpp
- src/base/net/geoipmanager.cpp
- src/gui/gpl.html
- src/gui/options.ui
- src/gui/programupdater.cpp
- src/gui/properties/trackersadditiondlg.cpp
- src/searchengine/nova/engines/extratorrent.py
- src/searchengine/nova/engines/torrentreactor.py
- src/searchengine/nova/engines/versions.txt
- src/searchengine/nova3/engines/extratorrent.py
- src/searchengine/nova3/engines/torrentreactor.py
- src/searchengine/nova3/engines/versions.txt
- src/webui/www/public/preferences_content.html
The main goal of this was to move some search engines over to HTTPS to avoid censorship on (some) ISPs. However, this may warrant discussion of moving all the URLs over to https://unblocked.red/ which would prevent all types of censorship and provide HTTPS protection for the engines that don't support it.
I took the opportunity to fix a few other URLs on top of that.
I also tried to verify if the update checker was done over HTTPS and I assume it to be this URL: http://www.fosshub.com/software/feedqBittorent in which case I'd strongly recommend moving this over to GitHub and having qBt download the raw XML file from GitHub over HTTPS. As it stands anyone can MitM the XML file feeding custom versions pointing to any malicious URL. A less malicious user could use this to gather statistics …
> Move some URLs overs to HTTPS

- README.md
- appveyor.yml
Mine attempt of adding appveyor support.
In `QBT_LIB_URL` boost dir, I've striped some unused dirs to make file smaller.
Compile process here: https://ci.appveyor.com/project/Chocobo1/qbittorrent/build/appveyor-2
You can copy the files at `QBT_VER_URL` & `QBT_LIB_URL` to your server and give me the new URLs.
If you want to use secret variables, see: http://www.appveyor.com/docs/build-configuration#secure-variables
> Add appveyor support

- uncrustify.cfg
The changes make uncrustify to 
1) add a space in the beginning of a comment ('// comment');
2) do not split '<<' and '>>' when used in template declarations;
3) add empty line before class access specifiers.
> update uncrustify config

- CODING_GUIDELINES.md
C++11 brings some features that allow you to write the same thing in different ways. Mixing these methods reduces code readability, so we need to regulate it.
> Add new Coding Style rules for some c++11 features

- src/searchengine/nova/engines/btdigg.py
- src/searchengine/nova/engines/torrentz.py
- src/searchengine/nova/engines/versions.txt
- src/searchengine/nova/helpers.py
- src/searchengine/nova3/engines/btdigg.py
- src/searchengine/nova3/engines/versions.txt
**[Search engine] Fix Python 2 encoding problems**
Extratorrent, mininova and piratebay search engines stopped working after merging #4781
**[Search engine] Change URL getting mechanism in BTDigg**
BTDigg wasn't using `retrieve_url` method.
I tested all plugins in Python2 & Python3.
> [Search engine] Python2 encoding and URL getting mechanism in BTDigg

- src/gui/transferlistfilterswidget.cpp
It tries to fix #4990, #4905, #4864, #4855, #4818, #4726,  #4648. I know that `item(1)` should always exist but it's the only thing in that function that can be causing the crash...
Related 3067f82aea1a3c0ff0df5236db05d20334887722
> Potential fix for crash. Closes #4990, #4905, #4864, #4855, #4818, #4726,  #4648

- src/gui/search/searchtab.cpp
- src/gui/search/searchtab.h
- src/gui/search/searchwidget.cpp
Both download handlers (in the tab and widget classes) convert model
index into an URL, set row color, and call download function.
Make the download button handler (in the SearchWidget class) call the
slot of the SearchTab class.
> Remove duplicated code from search tab and widget

- src/gui/addnewtorrentdialog.ui
Place all widgets in "Torrent information" into the same grid layout instead of different layouts.
Hope I covered everything this time.
Before resizing:
[before](https://cloud.githubusercontent.com/assets/9395168/14151537/efdc042a-f6e0-11e5-9c81-2846d9e1faf9.png)
after resizing (not fixed):
[current](https://cloud.githubusercontent.com/assets/9395168/14151542/f275d80a-f6e0-11e5-89bb-bce63996b469.png)
after resizing (fixed):
[previous attempt](https://cloud.githubusercontent.com/assets/9395168/14151606/583b3284-f6e1-11e5-8e91-d08565b983be.png)
[latest fix](https://cloud.githubusercontent.com/assets/9395168/14242934/1a6126e2-fa85-11e5-9780-802ebd50fdcb.png)
Tab order tweak (fixed):
[tab_order](https://cloud.githubusercontent.com/assets/9395168/14151541/f235f988-f6e0-11e5-9ded-54c60169a7fd.pn …
> Fix resizing bug in "add torrent dialog"

- src/app/application.cpp
- src/app/application.h
- src/base/utils/misc.cpp
- src/base/utils/misc.h
* Fix Coverity Scan 143909
* Enable access to shutdown functions when configured with `--disable-gui` option
-
Don't merge yet, qbt tray icon hangs on quit when `Confirmation on auto-exit when downloads finish` is enabled.
gdb backtrace:
```
#0  0x00007ffff723b3e8 in pthread_cond_timedwait@@GLIBC_2.3.2 ()
from /usr/lib/libpthread.so.0
#1  0x00007ffff53e2bc6 in QWaitCondition::wait(QMutex*, unsigned long) ()
from /usr/lib/libQt5Core.so.5
#2  0x000000000051d4aa in BitTorrent::Session::getPendingAlerts (this=0xe07d50, out=...,
time=30000) at base/bittorrent/session.cpp:2239
#3  0x0000000000521ed2 in BitTorrent::Session::saveResumeData (this=this@entry=0xe07d50)
at base/bittorrent/session.cpp:1575
#4  0x000000000052b4dc in BitTorrent::Session::~Session (this=0xe07d50,
__in_chrg=<optimized …
```
> Fix Shutdown confirmation

- uncrustify.cfg
Uncrustify inserts line break between an access specifier and "slots".
However, it keeps these words combinations if "Q_SLOTS" is used.
Its built-in parser classifies "Q_SLOTS" as WORD token, thus let's add
"slots" to that class.
> uncrustify: add "slots" to WORDs keywords.

- src/gui/advancedsettings.cpp
The only concern is we are saving only the interface name and could be several with the same name.
> Fix duplicate network interfaces. Closes #5131

- src/base/bittorrent/infohash.cpp
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrenthandle.cpp
Save torrent in `temp_path/<truncated_torrent_hash>` directory.
Closes #5154.
This is also the required prerequisite to #4081.
> Use unique temp directories. Closes #5154.

- cmake/Modules/FindLibtorrentRasterbar.cmake
- cmake/Modules/FindQtSingleApplication.cmake
- src/base/CMakeLists.txt
base "module" needs -DQT_DBUS_LIB set to compile proper power management code. The appropriate library dependency was mistakenly forgotten.
Also mark libtorrent and qtsingleapplication include dirs as system.
> cmake: fix powermanagement compilation

- uncrustify.cfg
Stick the '*' and '&' symbols to the variable name if there is one.
Also fix empty function bodies collapse option: replace it with the
eat_blanks_before_close_brace setting.
> uncrustify: honour pointer and reference symbols alignment rules

- src/base/bittorrent/session.cpp
- src/gui/options_imp.cpp
The session setting got lost during refactor.
> Fix "IP Filtering - Apply to trackers" wasn't being applied

- src/gui/about.ui
Adjust about tab font-size to match other tabs of about dialog.
Before:
After:
> Set about tab font-size to default

- .travis.yml
- bootstrap.sh
- src/src.pro
See: https://blog.travis-ci.com/2016-05-03-caches-are-coming-to-everyone
* Suppress warning on OSX builds: only Qt4 builds are affected: https://travis-ci.org/qbittorrent/qBittorrent/jobs/127618787#L331
* Use POSIX shell since the script doesn't require bash-specific functions.
* Enable CI cache: linux builds are working as expected. ~~For OSX builds, Qt4 builds are working, *Qt5 builds doesn't seem to fully utilize ccache*, not sure why.~~  Update: OSX builds are also working now.
* Use qmake built-in test function `files` to locate translation files
> Enable CI cache

- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/session.cpp
- src/base/torrentfileguard.cpp
- src/base/torrentfileguard.h
- src/gui/addnewtorrentdialog.cpp
- src/gui/addnewtorrentdialog.h
- src/gui/addnewtorrentdialog.ui
- src/gui/options.ui
- src/gui/options_imp.cpp
Re-implementation of #2700 
Some browsers do not download files, intended for an immediate opening, into a temporary directory, and the regular downloads directory accumulates those unneeded files.
The option allows qBittorrent to clean after itself and delete those files whether they were successfully added or not (user selects the policy).
The identifiers names (the option name, the preferences class members names, and the helper class name) are more than debatable and I will be thankful for better ones.
Options tab screenshot:
The warning label appears when any of the two options gets checked.
> Add option to automatically remove .torrent files upon adding

- src/base/torrentfileguard.cpp
- src/base/torrentfileguard.h
- src/gui/addnewtorrentdialog.cpp
- src/gui/options_imp.cpp
Sorry, committed the incorrectly cased identifier.
> Fix a typo in TorrentFileGuard and a crash when adding torrent via magnet link

- src/webui/btjson.cpp
- src/webui/www/public/scripts/dynamicTable.js
If you take a look at #5145 #1092 and #738 you can see that this has been requested a few times.
As far as I understand the reasoning behind this is that once you have a list of say hundreds of torrents there is no way to sort your torrents to see which ones are the 'latest ones'. To do this you either need an 'Added on' column or a 'Completed on'.
This PR adds that 'Added on Column'. I suggest closing down all old issues that deals with 'Added on' or 'Completed on'. 
I would like to stress that this might not be the most elegant way. We should in my opinion add many more columns (as many as the desktop client has) and then have a way to add/remove columns from the webui via a context menu (right clicking).
But for the time being, this gets the job done.
> Added 'Added on' column in Webui. Closes #5145,#1092,#738

- src/gui/properties/peerlistwidget.cpp
- src/gui/properties/peerlistwidget.h
- ~~Removed `m_resolveCountries` as we can use `Preferences::instance()->resolvePeerCountries()` directly, i guess there was a reason for using `m_resolveCountries` so i'm waiting to be corrected.~~
- Check if a column is visible before resizing it to be able to keep the column's saved width even when we restart qbit with that column disabled. If there are no objections with this one we should do the same in `transferlistwidget` as it suffers the same problem.
- Now it doesn't resize Country column to contents on every restart (fixes part of #5236)
- Now country column is automatically shown when you enable Resolve peer countries" after a qbit restart with it disabled (had to manually show the country column from the column menu).
> Minor refactor in PeerListWidget

- src/app/stacktrace_win.h
- src/src.pro
> Stack trace for windows now contains source filenames and line numbers

- src/base/preferences.cpp
closes issue #5235 (https://github.com/qbittorrent/qBittorrent/issues/5235).
As this is not a proper pull request, please feel free to make the change yourself (if you want to keep the number of contributors to real contributors)
> default RSSRefreshInterval to 30 mins

- src/base/bittorrent/session.cpp
- src/base/preferences.cpp
- src/base/preferences.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
Added a new advanced settings option to make qbittorrent bind to a specific ip if you have a network device with multiple ip's. This will override the network interface setting when used.
This allows you to use src ip based rule routing in linux to route torrent traffic to a specific exit point .
> Bind directly to an IP instead of using a network Interface

- src/gui/options.ui
Fix minor issues caused by #5213.
```
uic gui/options.ui
gui/options.ui: Warning: The name 'horizontalLayout_11' (QHBoxLayout) is already in use, defaulting to 'horizontalLayout_111'.
gui/options.ui: Warning: The name 'verticalLayout_17' (QVBoxLayout) is already in use, defaulting to 'verticalLayout_171'.
```
> Minor fix: typo and two warnings

- src/gui/search/searchtab.cpp
- src/gui/search/searchwidget.cpp
1) "Only enabled" search engines should be the selected option (as it was before #4995)
2) I think there are not many TiB size torrents. If you want to set the upper limit in GiB you only have to change the number.
> Minor changes in Search UI

- src/app/application.cpp
- src/gui/mainwindow.cpp
From #4871.
All starts at: https://github.com/qbittorrent/qBittorrent/blob/master/src/app/application.cpp#L482
`~options_imp()` is calling `ScanFoldersModel::configure()` which access `Preference` class.
But at the time, `Preference` has already become invalid so the crash pop up.
~~Dirty workaround, better ideas welcome.~~
------
BTW, in the first commit, is it a good idea to make `static QAtomicInt alreadyDone;` independent of `DISABLE_GUI` & `Q_OS_WIN`, so it can apply to all platforms?
> Fix crash when qbt exits with options dialog opened

- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
- src/base/bittorrent/torrentinfo.cpp
- src/base/bittorrent/torrentinfo.h
- src/base/indexrange.h
- src/gui/properties/CMakeLists.txt
- src/gui/properties/downloadedpiecesbar.cpp
- src/gui/properties/downloadedpiecesbar.h
- src/gui/properties/pieceavailabilitybar.cpp
- src/gui/properties/pieceavailabilitybar.h
- src/gui/properties/piecesbar.cpp
- src/gui/properties/piecesbar.h
- src/gui/properties/properties.pri
- src/gui/properties/propertieswidget.cpp
- src/gui/properties/propertieswidget.h
A little improvements for the progress bars in the "General" tab of the torrent properties are proposed.
1. Show files (and their sizes) for a piece under cursor in tooltip.
2. If the cursor points to a single file which extends over several pieces, highlight those pieces.
This works as follows: the following phrase is added to the tooltip "Hold Shift key for detailed information":
Here is an illustration:
And if this modifier (Shift) is pressed when tooltip is requested, detailed information about a pieces of a file under cursor is shown:
The detailed tooltip shows a table with sizes and names of the files in the piece under cursor. 
In both images one can see highlighted (actually darkened) part of the torrent, occupied by the file under cursor.
This PR extends (and based on) PR #4867. …
> Improve tooltips for torrent progress bar

- src/gui/properties/piecesbar.cpp
A hotfix for the detailed tooltips glitch, which appears if you request the detailed tooltip at the image border.
If tooltip text contains an empty HTML body, Qt still shows it as an
empty rectangle. Thus, output HTML tags only if we are within the
image region, and return true empty string if we are at the borders.
@Chocobo1, thank you for the test case!
> Fix empty tooltips showed at the progress bar borders

- src/app/application.cpp
- src/app/application.h
Users can write (platform dependent) shell scripts now.
A dead simple script like the following isn't possible before
```shell
echo "%F" >> /tmp/txt
```
Update: some info:
[std::thread::detach](http://en.cppreference.com/w/cpp/thread/thread/detach)
[What happens to a detached thread when main() exits?](http://stackoverflow.com/questions/19744250/what-happens-to-a-detached-thread-when-main-exits)
> Replace QProgress::startDetached with std::detatch.

- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrenthandle.cpp
Do not create the save folder as long as the torrent will not start downloading.
> Do not create save folder in advance. Closes #5422

- src/gui/optionsdlg.ui
The icons for selecting different pages in Options dialog were missing when using RTL languages.
It's fixed now:
Please verify in Windows.
> Fix icons are missing when using RTL languages in Options dialog

- src/gui/properties/speedplotview.cpp
I've briefly looked into the code, and i think [this causes the bug](https://github.com/onto/qBittorrent/blob/cdab0bb140b76083dbc77dea3caaeba445d08a37/src/gui/properties/speedplotview.cpp#L84).
It should be `m_counter6Hour = (m_counter6Hour + 1) % 18;` instead of the `% 6` (and not 36, since [it has a double-sized buffer](https://github.com/onto/qBittorrent/blob/cdab0bb140b76083dbc77dea3caaeba445d08a37/src/gui/properties/speedplotview.h#L98) compared to the 30 min plot)
> Fix 6-hour speedplot point push rate #5545

- src/gui/deletionconfirmationdlg.h
- src/gui/mainwindow.cpp
- src/gui/transferlistwidget.cpp
- src/gui/transferlistwidget.h
Added new shortcut (shift+delete) to open delete torrent dialog with checkbox to remove files checked.
Old behaviour with just delete key or toolbar button unchanged.
> Add torrent and files deletion with Shift+Delete hotkey

- src/app/application.cpp
- src/base/utils/misc.cpp
- src/base/utils/misc.h
- src/gui/mainwindow.cpp
Searching through various directories for a system program is not a good practice.
> Call system msiexec.exe directly

- src/base/net/private/geoipdatabase.cpp
Updated MaxMind database limit from 10MB to 64MB. I hope it will be enough for few years.
Fix for issue #5609
> Update geoipdatabase.cpp to allow larger GeoLite2-Country database (issue #5609)

- src/base/net/smtp.cpp
- src/base/net/smtp.h
- src/gui/optionsdlg.cpp
This pull request includes two relatively minor fixes:
1. Fixes a bug with the smtp client where in certain cases sending an email when a torrent completes would silently fail. Cases where it could happen includes but is not limited to: trying to connect to an SMTP server without encryption when it requires SSL, the connecting timing out, or the connection being refused.
2. Hides the "This server requires a secure connection (SSL)" checkbox in the settings when qBittorrent is built without SSL support, as all emails will be unencrypted anyway. This is consistent with the SSL aspects of the Web UI settings being hidden when the build does not include SSL.
> Fixes bug where sending email could silently fail

- src/base/net/private/geoipdatabase.cpp
```bash
base/net/private/geoipdatabase.cpp:130:21: aviso: comparación entre expresiones enteras signed y unsigned [-Wsign-compare]
if (data.size() > MAX_FILE_SIZE) {
~~~~~~~~~~~~^~~~~~~~~~~~~~~
```
> Fix warning in geoipdatabase.cpp

- src/base/net/portforwarder.cpp
- src/base/net/portforwarder.h
- src/webui/webui.h
Can now use WEBUI port bigger than 32766. Don't know if this causes any other problems.
Also changed the remaining `qint16` to `quint16` in `portforwarder` (other than `addPort()` `deletePort()`) as it makes no sense to use `signed type` for ports.
Although i tested it and didn't get any new problems, i get all sorts of UPnP errors (`unknown UPnP error (-1)`, `500 Internal Server Error`, `400 Bad Request`) when i try to change port or disable UPnP from the options, with or without these changes so testing for side effects is limited. 
/Offtopic
The problem i mention in #5673 about being able to change port only once per qbit session remains. To circumvent it you can change port, apply, disable UPnP and re-enable it and it'll open the port.
>  Fix WEBUI port overflow

- src/gui/mainwindow.cpp
Deleted offending code
```
MainWindow::~MainWindow()
{
-#ifdef Q_OS_MAC
-    // Workaround to avoid bug http://bugreports.qt.nokia.com/browse/QTBUG-7305
-    setUnifiedTitleAndToolBarOnMac(false);
-#endif
delete m_ui;
}
```
which was a workaround to avoid bug https://bugreports.qt.io/browse/QTBUG-7305
The bug was fixed at Qt 4.6.2 https://github.com/Blizzard/qt4/blob/master/dist/changes-4.6.2
> Fix Mac OS X Build (Closes #5763)

- src/gui/addnewtorrentdialog.cpp
This commit fixes the default save path bug (v3.3.7) which can be reproduced by changing the default save path in new torrent dialog and checking "do not show again" checkbox followed by "OK" button. Now if a new torrent file is opened it is saved automatically to previous default directory rather than to the new save path.
> fix default save path bug

- src/gui/transferlistfilterswidget.cpp
At https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/transferlistfilterswidget.cpp#L538, `item(row);` might return 0.
> Fix crash in TrackerFiltersList::removeItem()

- src/gui/transferlistsortmodel.cpp
If you want to sort torrents by name, you expect they are sorted case insensitively.
Or current implementation is intentional?
> Sort torrent names case insensitively

- configure
- configure.ac
I am tired of typing ./configure --disable-qt-dbus
> Add --disable-qt-dbus to configure if $host_os is macOS

- src/app/main.cpp
- src/gui/mainwindow.cpp
Since Apple made difficult for users to set PATH and /usr/bin/python
is almost unusable, I simply add /usr/local/bin before default PATH
to pick up Homebrew Python.
> Set /usr/local/bin before default PATH on macOS. Closes #5639 #5571

- src/gui/downloadfromurldlg.h
I am actually not very much sure why this fixes the problem.
But my guess is as soon as close() is called url_list_cleaned is destroyed by setAttribute(Qt::WA_DeleteOnClose)
resulting MainWindow::downloadFromURLList() gets invalid memory area.
I tested on Ubuntu 16.04 and Windows 10 to make sure this change does not break.
> Fix downloadFromURL bug. Closes #5844

- src/gui/properties/speedwidget.cpp
Fix QMenu left orphaned when speedwidget is destructed.
> memleak fix

- src/base/utils/fs.cpp
- src/base/utils/fs.h
* Simplify function call
`GetDiskFreeSpaceExW` is supported on win XP, so there is no need for the `GetProcAddress` loading method.
* Fix memory leak
`path` variable was not freed after use.
* refactor
* Remove unused variable
> Fix memory leak

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
Minimized number of warnings about deprecated auto_ptr from some dozens to just 1 warning. The last warning caused by libtorrent API call, can't fix it.
> minimizing the number of warnings about deprecated auto_ptr

- src/base/bittorrent/session.cpp
The QTBUG-52633 results in flood of network interface changed events, libtorrent IP
rebind calls and flood in the qBt log. The work around is the check not only for
interface name, but for IP address on that interface before triggering the libtorrent rebind.
I don't know yet the project policy on maintaining workarounds.
> Add a workaround for QTBUG-52633, qBt issue #5073

- cmake/Modules/winconf.cmake
This allows user to override their default value via -D cmake switch
> cmake: make prefix variables cached

- src/base/torrentfileguard.cpp
- src/base/torrentfileguard.h
moc from Qt4 ignores `Q_ENUMS` when it is behind `#if QT_VERSION `check.
Therefore moc entries for enum in `TorrentFileGuard` were not generated
and the setting was not saving/loading. This closes #6103, #5451
> Workaround problem with moc from Qt4 and #if. Closes #6103, #5451

- src/base/bittorrent/session.cpp
If removing of added torrents is enabled and dialog for adding torrents
is disabled, file guard was assuming that torrent is added successfully.
And that can be not the case if a user trying to add a broken torrent
file (or not a torrent file at all). Then this file gets deleted always.
Fix this by checking result of addTorrent_impl().
> Do not remove added files unconditionally. Closes #6248

- src/webui/www/public/preferences_content.html
proxy_type = none must be 0.
This leads to an unnecessary Session::configure() call.
Possibly related to https://github.com/qbittorrent/qBittorrent/issues/6127
> Webui proxy_type bug fix

- src/gui/transferlistfilterswidget.cpp
The culprit is some zh_HK translators dropped the nessesary white space.
```
<source>%1 (%2)</source>
<translation>%1（%2）</translation>
```
Note in the translation, the character right after `%1` is `（`.
(0xFF08 = FULLWIDTH LEFT PARENTHESIS) 
But I think these translations are actually not necessary.
> Avoid unnecessary translation. Closes #6158

- src/gui/rss/automatedrssdownloader.ui
This pull request addresses issue #6164.
Fixes the tabbing order in the RSS download rules dialog so it goes "Must Contain" -> "Must Not Contain" -> "Episode Filter".
> Fix tab order in RSS downloader. Closes #6164.

- src/app/stacktrace.h
There are many bug reports with useless stacktraces from UNIX users, created on systems without installed debug symbols. We can count function names in the stacktrace, and if there are no or too few of them, suggest user to install debug symbols and warn that the stacktrace as it is is useless.
> Warn if no function names are present in the stacktrace

- src/base/bittorrent/session.cpp
Used existing function to fix "Don't Repeat Yourself" principle violation.
> Little DRY violation fixed

- src/base/bittorrent/torrenthandle.cpp
- src/webui/btjson.cpp
Closing PR #5300 in favor of this one.
* Fix webUI used the wrong value. Closes #5048.
* Use the numbers from tracker scrape response. Closes #6117.
also see: https://github.com/qbittorrent/qBittorrent/issues/6117#issuecomment-269104117
> Use the numbers from tracker scrape response

- dist/mac/Info.plist
- src/app/CMakeLists.txt
Fixed the error when you do `macdeployqt` after `./configure --disable-gui` or `cmake -DGUI=OFF`
I doubt there are needs for qbittorrent-nox for macOS though.
> Build qbittorrent-nox for macOS

- src/base/bittorrent/torrenthandle.cpp
- src/gui/transferlistwidget.cpp
This behavior could be troublesome in some situations, e.g., I download a torrent to some temp folder, now later I have a permanent folder for it, so I use "Set location" to relocate it but it deletes my temp folder.
> After files relocate, don't remove the old folder even if it is empty

- src/app/application.cpp
- src/base/preferences.cpp
The default locale (`QLocale()`) was always system locale, not the one user selected in options dialog.
> Set default locale

- src/base/rss/rssdownloadrule.cpp
- src/base/rss/rssfeed.cpp
- src/base/rss/rssfeed.h
- src/gui/rss/automatedrssdownloader.cpp
- src/gui/rss/automatedrssdownloader.h
- src/gui/rss/rss_imp.cpp
- src/gui/rss/rss_imp.h
- src/gui/torrentmodel.cpp
Result of running `uncrustify` with the qBittorrent `uncrustify.cfg` on all the files used in my pull requests. All other pull requests that use any of these files have been rebased on top of this commit.
> Follow project coding style. Issue #2192.

- src/base/preferences.cpp
- src/base/preferences.h
- src/gui/properties/peerlistdelegate.h
- src/gui/properties/peerlistwidget.cpp
- src/gui/search/searchlistdelegate.cpp
- src/gui/search/searchtab.cpp
- src/gui/search/searchtab.h
- src/gui/search/searchwidget.cpp
- src/gui/search/searchwidget.h
- src/gui/transferlistwidget.cpp
- Aligned text to the right in columns that handle numbers in PeerList and SearchTab. I wanted to do it for Content and Trackers too but i don't know how, actually i could do it in data() and headerData() for Content but i don't know how to unstretch the last column because IMO it's unacceptable to have even 1 column that aligns to the right in combination with a stretched last column.
- Make columns in Search tabs toggleable.
- Keep columns width in TransferList even if they are hidden on qBittorrent startup (unless something goes wrong) like we did in PeerList in another PR.
- Allow to hide zero values for the "uploaded" and "downloaded" columns in PeerList via "Hide zero and infinity values" (or maybe do it like the [cases below](https://github.com/qbittorrent/qBittorrent/blob/master/sr …
> Changes and additions in search, peerlist, transferlist

- src/gui/mainwindow.cpp
- src/gui/rss/rss_imp.cpp
Apparently, we can not use symbolic icons transparently.
Uncovered in #6274
> Replace icon name "open-menu" with "preferences-system"

- src/base/unicodestrings.h
- src/base/utils/misc.cpp
- src/base/utils/misc.h
KiB and MiB remain unaffected
GiB get 2, TiB and above get 3.
Thoughts on these numbers?
Maybe i should implement it like i originally intended directly in `friendlyUnit`?
```
else if (unit <= SizeUnit::MebiByte)
return Utils::String::fromDouble(friendlyVal, 1) + " " + unitString(unit);
else if (unit == SizeUnit::GibiByte)
return Utils::String::fromDouble(friendlyVal, 2) + " " + unitString(unit);
else
return Utils::String::fromDouble(friendlyVal, 3) + " " + unitString(unit);
```
Or maybe move everything in the new method
```
diff --git a/src/base/utils/misc.cpp b/src/base/utils/misc.cpp
index 18f06d2..943a814 100644
--- a/src/base/utils/misc.cpp
+++ b/src/base/utils/misc.cpp
@@ -355,15 +355,30 @@ QString Utils::Misc::friendlyUnit(qint64 bytesValue, bool isSpeed)
if …
```
> Increase number of digits after the decimal point. Closes #5053

- src/gui/mainwindow.cpp
- src/gui/mainwindow.h
This pull request addresses issue #5797.
Changes `Ctrl+F` to focus the torrent filter text field and select all contents, as per the comments in #5797.
> Ctrl+F search filter. Closes #5797.

- src/base/bittorrent/torrenthandle.cpp
I'm not sure if this error should be more verbose then debug.
here cases where we could get a missmatch beteen known files and file progress resonse, there are 2 empty return cases:
https://github.com/arvidn/libtorrent/blob/master/src/torrent.cpp#L10205-L10228
> fix index overflow for torrents with invalid meta data or empty progress

- src/app/main.cpp
- src/app/upgrade.h
- src/base/rss/rssfeed.cpp
This is one of a series of pull requests designed to improve the responsiveness of the UI. This pull request addresses #6167.
When editing RSS downloader rules, each edit results in persisting the rules to disk. Since the `old_items` are in the same file, this also means persisting the `old_items` to disk each time a rule is edited. I have ~100 rules which use <1MB on disk, but the `old_items` use ~70MB, so persisting them each edit affected responsiveness.
This change moves the RSS `old_items` from `qBittorrent-rss.conf` to a new `qBittorrent-rss-items.conf`. Existing entries are migrated on first run.
> Move old RSS items to separate config file. Closes #6167.

- src/base/rss/rssdownloadrule.cpp
- src/base/rss/rssdownloadrulelist.cpp
- src/gui/rss/automatedrssdownloader.cpp
- src/gui/rss/automatedrssdownloader.h
This pull request addresses issue #5539.
Adds a blank entry to the top of the category list for RSS rules. This means that a rule that already has a category assigned can be reset to no category.
> RSS: allow resetting rule to no category. Closes #5539.

- src/base/rss/rssdownloadrule.cpp
- src/base/rss/rssdownloadrulelist.cpp
- src/gui/rss/automatedrssdownloader.cpp
- src/gui/rss/automatedrssdownloader.h
This pull request addresses issue #6163.
Correctly saves the enabled/disabled state of a rule when it is changed while the rule is not selected.
Note that this pull request has been rebased on top of #6212 and uncrustified.
> Save rule on enable/disable even if not selected. Closes #6163.

- src/base/rss/rssdownloadrule.cpp
- src/base/rss/rssdownloadrulelist.cpp
- src/gui/rss/automatedrssdownloader.cpp
- src/gui/rss/automatedrssdownloader.h
This pull request addresses issue #6171.
Adds support for | in the "Must Contain" field for RSS rules. Also makes the difference between using whitespace and `*` explicit in the tooltip (tokens separated by whitespace can be in any order in the article title).
> Allow | in RSS must contain. Closes #6171.

- src/base/rss/rssdownloadrule.cpp
- src/base/rss/rssdownloadrulelist.cpp
- src/gui/rss/automatedrssdownloader.cpp
- src/gui/rss/automatedrssdownloader.h
- src/gui/rss/automatedrssdownloader.ui
This pull request addresses issue #6165.
This pull request changes the RSS episode filter validation to be consistent with the must and must not contain fields - red text + warning icon if invalid.
The existing behaviour has some undesirable characteristics - in particular, not allowing intermediate states e.g. if you have a valid filter "1x2-" and you want to change it to "1x3-", it is not currently possible to delete the "2" and then type "3". It is instead necessary to have "1x23-" before deleting the "2".
> RSS use red text to indicate invalid filter. Closes #6165.

- src/base/rss/rssdownloadrule.cpp
- src/base/rss/rssdownloadrulelist.cpp
- src/gui/rss/automatedrssdownloader.cpp
- src/gui/rss/automatedrssdownloader.h
This pull request addresses issue #6170 (and the issues mentioned in there - #800 and #3876).
Adds support for the following:
- Zeroes in the episode portion of the filter, including episode #0 for specials e.g. `1x00;`.
- Open-ended filters now match future seasons e.g. `1x01-;` will match all episodes from season 2 and later. This is issue #3876 which had been closed.
- Matches episodes specified like `1x01` in the article title (this is an extension of issue #800).
It looks like this also fixes #2749 (although I'm not convinced there was an actual problem there, but the use case works with this pull request).
> RSS episode filter improvements. Closes #800, #2749, #3876, #6170.

- src/base/rss/rssdownloadrule.cpp
PR #6181 introduced code which required Qt 5.4 or later - `QStringRef::split()`. This PR reverts to using `QString.split()`.
There is currently discussion about making Qt 5.5.1 the minimum supported version, and if that happens this PR should probably be backed out. However, currently this error will mask other errors on builders using Qt <5.4.
> Fix compilation error on Qt<5.4. Closes #6170.

- src/base/bittorrent/private/filterparserthread.h
A little correction to distinguish inner used  methods from outer API methods.
> reduce methods accessibility from public to private

- src/base/rss/rssfeed.cpp
- src/base/rss/rssfeed.h
- src/base/rss/rssmanager.cpp
- src/base/rss/rssmanager.h
This is one of a series of pull requests designed to improve the responsiveness of the UI. This pull request addresses #873, #1089, #1235, #5423 (which are all essentially the same issue reported multiple times).
The issues mentioned talk about using QThread, and my initial intention was to move the processing of the RSS articles fully to the thread currently being used for RSS parsing, but I wasn't able to work out how to get it to work. I have taken a different approach in this pull request - process a single article, then fire a timer to process the next article with a 1ms delay. This allows UI and input events to be processed almost immediately instead of the entire UI freezing until the feed is processed.
Note: Qt seems to do something special with a 0ms delay - I'm guessing adding …
> Improve UI responsiveness during RSS downloading. Closes #873, #1089, #1235, #5423

- src/gui/transferlistsortmodel.cpp
- src/gui/transferlistsortmodel.h
A small fix belonging to #2531.
During the sorting empty QDateTime values are shuffled around due to
unstable sort in QSortFilterProxyModel (see #2526 and #2158), causing
the transfer list items to constantly change order.
Fixed by using an already existing correct comparison (with a torrent
hash fallback).
> Fixed sort order for datetime columns with empty values (closes #2988)

- CMakeLists.txt
- cmake/Modules/FunctionReadVersion.cmake
The title says it. 
An assumption was made that VER_STATUS is any of 0-9 and a-z or empty (see the regex in `cmake/Modules/FunctionReadVersion.cmake`.  I do not know whether the assumption is correct.
> cmake: read version numbers from the version.pri file. Closes #6350.

- src/gui/rss/automatedrssdownloader.cpp
- src/gui/rss/automatedrssdownloader.h
- src/gui/rss/automatedrssdownloader.ui
- src/gui/rss/rss_imp.cpp
A collection of bugfixes for the RSS rules downloader UI and RSS tab feed list.
1. Issue #3782: Save feed aliases when renaming.
2. Issue #6281: Sort the feed list (but see PR #6345 for further enhancement).
3. Show "Disabled" in Subsequent Matches spinner when 0 days.
4. Clear all fields when no rule selected.
5. Clear all fields when creating a new rule.
6. When multiple rules are selected, use tri-state partially-selected checkbox for feeds that are used by some but not all of the selected rules.
7. Fix the episode validator so an empty string is considered valid.
8. Fix a case where a rule could be saved with the criteria from a different rule:
1. Select a rule.
2. Ctrl-click a second rule - now have 2 rules selected)
3. Ctrl-click the second rule - now have 1 rule selected, but …
> RSS rules and feed UI bugfixes. Closes #3782, #6281.

- src/base/rss/rssdownloadrule.cpp
- src/base/rss/rssdownloadrule.h
- src/gui/rss/automatedrssdownloader.cpp
Fixes an error introduced in PR #6181 that resulted in regex always matching (unless prevented by must not match or episode).
The rules are as follows:
1. An empty must contain field matches all articles.
2. An empty must not contain field does not exclude any articles.
3. An empty `|` clause e.g. `expr|` in the  must contain field matches all articles (this was already the behaviour of regex, so make wildcard work the same).
4. An empty `|` clause e.g. `expr|` in the must not contain field excludes all articles (this was already the behaviour of regex, so make wildcard work the same).
Updated the tooltips to make the behaviour with an empty `|` clause explicit.
> Fix regex RSS matching. Closes #6337.

- src/base/http/server.cpp
Due to a bug in Qt 5.8 (QTBUG-58706) QTcpServer tries to use HTTP proxy
when it is set as default app proxy (for instance via "http_prxy"
environment variable) and this breaks the server. So we disable any proxy
in it.
> Disable proxy in WebUI HTTP server. Closes #6349.

- src/base/http/server.cpp
- src/base/utils/string.cpp
* 2 commits for Qt4 should also merged into 3.3.x branch.
The Qt::escape() is defined in QTextDocument header which is available only when gui=true. So I just borrowed the code from upstream.
> Fix issues when compiling with Qt4 

- src/gui/optionsdlg.cpp
- src/gui/optionsdlg.h
- src/webui/webui.cpp
* This allows qbt to load/use ECDSA certificate in webUI
Limit max read size
Improve messages in dialogs
Refactor
**Merge this after Qt4 is dropped (PR #6266)**
> Allow QSsl::Ec as private key format

- src/base/bittorrent/torrenthandle.cpp
<del>Now we need to write the libtorrent::torrent_handle method calls in the correct form, which should improve code maintainability and allow to use advanced code navigation features of QtCreator (and of other IDEs).</del>
Remove SAFE_* macros from TorrentHandle class.
Using these macros don't seem necessary.
> Remove exception suppressing from torrenthandle.cpp

- src/webui/btjson.cpp
- src/webui/webui.qrc
- src/webui/www/private/index.html
- src/webui/www/public/scripts/client.js
- src/webui/www/public/scripts/mocha-init.js
- src/webui/www/public/statistics.html
(Fixed from previous bad PR, thanks for the feedback @sledgehammer999 @thalieht)
Implemented a simple statistics display window for the web UI. It is not perfect, as contents don't load immeadiately if the overall torrent activity is low, but works well enough to be usable.
I think this limitation has to do with the frequency that processServerState() gets called, and the fact that I made it so that the window only gets updated when said function is called.
@buinsky
> Implement statistics window in web UI

- src/CMakeLists.txt
- src/app/upgrade.h
- src/base/bittorrent/magneturi.cpp
- src/base/bittorrent/peerinfo.cpp
- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrentcreatorthread.cpp
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrentinfo.cpp
- src/base/bittorrent/tracker.cpp
- src/base/bittorrent/trackerentry.cpp
- src/base/logger.cpp
- src/base/preferences.cpp
- src/base/utils/string.cpp
- src/base/utils/string.h
- src/gui/categoryfilterwidget.cpp
- src/gui/deletionconfirmationdlg.h
- src/gui/properties/peerlistwidget.cpp
- src/gui/properties/propertieswidget.cpp
* Remove remaining QBT_USES_QT5 defines.
Fixup of e64bb1d.
* Replace Utils::String::toStdString() by QString::toStdString()
* Replace Utils::String::toHtmlEscaped() by QString::.toHtmlEscaped()
UPDATE:
* Replace Utils::String::fromStdString() by QString::fromStdString()
> Remove remainings of Qt4

- src/base/rss/rssdownloadrule.cpp
- src/base/rss/rssdownloadrule.h
- src/base/utils/string.cpp
- src/base/utils/string.h
- src/gui/rss/automatedrssdownloader.cpp
- src/gui/rss/automatedrssdownloader.h
Change `rssdownloadrule` and `automatedrssdownloader` to use `QRegularExpression` instead of `QRegExp`.
_Note: `QRegularExpression` is only available since Qt 5.0 so this PR cannot be merged while Qt 4.8 is supported. Since `QRegularExpression` is not a strict superset of the functionality in `QRegExp` I do not want to use one engine for Qt 4.8 and a different one for Qt 5.0+._
When using regex for rules, add a tooltip to the invalid icon specifying the first error. Not done for wildcards as we can't get this info in a way that corresponds to the wildcard string.
The second commit in the PR adds caching of the rule regexes - this results in a significant performance improvement over creating the regexes every time.
To convert wildcards to regex, use an internal function in `QRegExp` which …
> Use Perl-compatible regexes for RSS rules. Closes #6367.

- src/base/torrentfileguard.cpp
- src/base/torrentfileguard.h
The problem was created during Qt 4 drop, when FileGuard was promoted
from a member to a base class. The function was blindly changed.
> Fix TorrentFileGuard::setAutoRemove() recursion problem. Closes #6488.

- dist/windows/options.nsi
dpi-aware installer
ManifestDPIAware is supported from nsis 3.0
> NSIS ManifestDPIAware

- .travis.yml
- dist/mac/bundle.cmake
- src/app/CMakeLists.txt
1. Remove Qt4 leftover from CMake build files.
1. Fix cmake build and bundle creation on OSX
1. Add CMake builds to Travis (with fails allowed).
> cmake: fix build and add build configurations for Travis

- src/app/CMakeLists.txt
- src/app/app.pri
- src/app/application.cpp
- src/app/application.h
- src/app/main.cpp
- src/app/options.cpp
- src/app/options.h
- src/app/upgrade.h
- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/private/statistics.cpp
- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrenthandle.cpp
- src/base/net/geoipmanager.cpp
- src/base/private/profile_p.cpp
- src/base/private/profile_p.h
- src/base/profile.cpp
- src/base/profile.h
- src/base/rss/rssdownloadrulelist.cpp
- src/base/rss/rssfeed.cpp
- src/base/searchengine.cpp
- src/base/settingsstorage.cpp
- src/base/utils/fs.cpp
- src/base/utils/fs.h
- src/base/utils/misc.cpp
- src/gui/rss/htmlbrowser.cpp
It may be useful to have different configurations either for portable versions or for debugging purposes. To implement this we add two options, avaliable via command line switches
1. An option to change configuration name (`--configuration`). The name supplied via this option is appended to `QCoreApplication::applicationName()` to form `qBittorrent_<conf_name>` name for the configuration files.
2. An option to provide a path do directory where all the settings are stored (kind of profile directory). There is a shortcut `--portable` which means "use directory `profile` near the executable location".
In order to implement that we have to perform initialisation of the profile directories before the `SettingStorage` and `Preferences` singletones are initialised. Thus, options parsing shall be …
> Implement configurations and portable mode. Closes #465

- src/app/application.cpp
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
Commit dd0537d changed torrents startup code adding alerts processing
into it. Therefore alerts were processing before UI code subscribed to
signals and therefore part of  alerts was not reflected in UI.
Thus here we do not start torrents in Session constructor but do this
from Application::exec() after UI was constructed and is ready to process
signals.
> Start up torrents after UI was created. Fixes #6454.

- src/base/http/requestparser.cpp
- src/webui/abstractwebapplication.cpp
- src/webui/webapplication.cpp
- src/webui/www/public/download.html
- src/webui/www/public/scripts/mocha-init.js
- src/webui/www/public/upload.html
API design
Adding two post fields to `command/download` and `/command/upload`.
- `skip_checking`: Skip hash checking if `skip_checking` is presented and of string value `true`.
- `paused`: Add task as paused state, if `paused` is presented and of string value `true`.
```http
POST /command/download HTTP/1.1
User-Agent: Fiddler
Host: 127.0.0.1
Cookie: SID=your_sid
Content-Type: multipart/form-data; boundary=---------------------------6688794727912
Content-Length: length
-----------------------------6688794727912
Content-Disposition: form-data; name="urls"
https://torcache.net/torrent/3B1A1469C180F447B77021074DBBCCAEF62611E7.torrent
https://torcache.net/torrent/3B1A1469C180F447B77021074DBBCCAEF62611E8.torrent
-----------------------------6688794727912
Content-Disposition: form-data; …
```
> [WebUI-API] Add "skip_checking" and "paused" to "/command/download" and "/command/upload"

- .travis.yml
- src/gui/CMakeLists.txt
- src/gui/mainwindow.cpp
- src/gui/properties/CMakeLists.txt
- src/gui/properties/peerlistwidget.cpp
- src/gui/properties/peersadditiondlg.cpp
- src/gui/properties/peersadditiondlg.h
- src/gui/properties/propertieswidget.cpp
- src/gui/properties/propertieswidget.h
- src/gui/properties/proplistdelegate.cpp
- src/gui/properties/trackerlist.cpp
- src/gui/properties/trackersadditiondlg.cpp
- src/gui/properties/trackersadditiondlg.h
- src/gui/rss/rss_imp.cpp
- src/gui/rss/rss_imp.h
- src/gui/search/pluginselectdlg.cpp
- src/gui/search/pluginselectdlg.h
- src/gui/search/pluginsourcedlg.cpp
- src/gui/search/pluginsourcedlg.h
- src/gui/search/searchwidget.cpp
- src/gui/search/searchwidget.h
- src/gui/speedlimitdlg.cpp
- src/gui/speedlimitdlg.h
- src/gui/statusbar.cpp
With version 3.8 CMake became stricter with include directories and instead of messing up with them, here we remove generated includes (actually, only uic products) from header files in `src/gui/` subdirs to make it compile, introducing `m_ui` pointers.
Additionally, Homebrew updated its Qt formula and now Qt installs into a different prefix, which has to be reflected in our workaround (the second commit).
> CMake 3.8 compatibility and refactoring

- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/searchengine.cpp
- src/base/searchengine.h
- src/base/utils/version.h
- src/gui/search/pluginselectdlg.cpp
In connection with discussion in #5183 replace `qreal` with a class.
> Use explicit class for search plugin versions

- src/base/private/profile_p.cpp
- src/base/private/profile_p.h
- src/base/profile.cpp
- src/base/profile.h
Do not append '/config/' to data location on Windows to maintain backward compatibility.
Thanks @glassez  for spotting this and sorry for the inconvenience.
Additionally, Windows sub-path was ignoring configuration name.
PR updated: now it should work, but I did test on Linux only so far. And there is a little ugliness in the case of UNIX and non-MacOS: instead of using `~/.local/share/qBittorrent` directory,  qBt creates `~/.local/share/qBittorrent/data/` and writes files there. I don't understand why does it do so. To me, it would be a good idea to migrate these files out of the 'data' subdir. But for now  `Private::DefaultProfile::dataLocation()` contains an `#ifdef`.
And I went ahead and renamed `Profile::configurationName()` and `Private::Profile::configurationName()` into …
> Migrate from platform-specific code in Private::DefaultProfile to QStandardPaths

- src/gui/addnewtorrentdialog.cpp
This annoying bug appeared, apparently as a result of many rebasing for 2 years...
> Fix "Create subfolder" in AddNewTorrentDialog

- winconf-msvc.pri
Embedding manifest fails for me after upgrading to VS2017, this fixes it.
Qt: 5.7.1
Qt doc: https://doc.qt.io/qt-5/windows-deployment.html#manifest-files
Compile log:
```bat
qrc_lang.cpp
linking release\qbittorrent.exe
LINK : warning LNK4075: ignoring '/MANIFESTFILE' due to '/MANIFEST:EMBED' specif
ication
Creating library release\qbittorrent.lib and object release\qbittorrent.exp
mt.exe /nologo /manifest release\qbittorrent.exe.embed.manifest /outputr
esource:release\qbittorrent.exe;1
release\qbittorrent.exe.embed.manifest : general error c1010070: Failed to load
and parse the manifest. ???????????
```
> Disable Qt embedding manifest automatically

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
- src/gui/addnewtorrentdialog.cpp
This allows qBittorrent to use the default settings for this option if the user does not specify it explicitly.
Also fixes AddTorrentData since it shouldn't use TriStateBool params.
> Allow strip root folder using default settings

- .travis.yml
The coverity build job actually builds when `build_system=cmake`, this PR allows only `build_system=qmake` to build.
https://travis-ci.org/qbittorrent/qBittorrent/builds/225280424
> TravisCI: only allow coverity build job when `build_system=qmake`

- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/addtorrentparams.h
- src/base/bittorrent/session.h
Prevent inclusion of big "session.h" into other header when we want to create some class field of type AddTorrentParams.
> Move AddTorrentParams to its own header

- CMakeLists.txt
- cmake/Modules/MacroGlibcDetect.cmake
- cmake/Modules/MacroQbtCompilerSettings.cmake
- cmake/Modules/winconf.cmake
- src/CMakeLists.txt
- src/app/stacktrace.h
- src/base/net/private/geoipdatabase.h
- src/webui/abstractwebapplication.cpp
- src/webui/abstractwebapplication.h
- src/webui/webapplication.cpp
- src/webui/webapplication.h
The set is far from perfect, but guards against common errors with GCC.
> cmake: set warning and error compiler options

- src/app/application.cpp
- src/app/main.cpp
Qt doc: https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt
OS support summary:
* macOS: with `Info.plist` setup correctly, everything should be in place.
* linux: depends on environment variable `QT_AUTO_SCREEN_SCALE_FACTOR`.
This PR sets `QT_AUTO_SCREEN_SCALE_FACTOR=1` by default.
* windows: still depends on `qt.conf`.
Tried `QT_AUTO_SCREEN_SCALE_FACTOR` & `SetProcessDPIAware()` combinations, no use.
~~**[WIP] Don't merge yet**~~
PR is ready
> Opt-in DPI scaling 

- src/app/application.cpp
- src/app/main.cpp
- src/app/options.cpp
- src/app/options.h
- src/base/bittorrent/addtorrentparams.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
- src/gui/addnewtorrentdialog.cpp
- src/gui/addnewtorrentdialog.h
- src/gui/addnewtorrentdialog.ui
- src/gui/rss/rsswidget.cpp
This pull request adds the following command line arguments to qBittorrent that apply when specifying new torrents via the command line:
-p | --path <path>: Torrent save path
--add-started | --add-paused: Add torrents as started or paused
--skip-hash-check: Skip hash check
--category <category name>: Assign torrents to category
--sequential: Download torrents in sequential order
Using one or more of these arguments will make qBittorrent skip the "Add new torrent" dialog and simply add the torrent with the specified options, falling back on the application-wide settings for the options not specified. This fulfills many users' requests for a better method of adding torrents via scripts or some other method of automation, including the ability to specify options for those new torrents, and …
> Command line arguments for specifying options when adding torrents

- src/gui/addnewtorrentdialog.cpp
Found a macOS specific bug in `AddNewTorrentDialog` while working on my other PR. The gist of it is that since `AddNewTorrentDialog` is a sheet in macOS, it should not be repositioned. This is especially true if the main qBittorrent window is on a secondary monitor, because it causes the sheet to leap off screen in a manner that makes it invisible and totally inaccessible.
> Fix for macOS-specific bug in AddNewTorrentDialog

- src/gui/search/pluginselectdlg.cpp
- src/gui/search/pluginselectdlg.h
Fixup of 14e168039cae8e7b241c206754fe6d6f8a7f919e.
Error msg in console when you click "Search Plugins ..." button:
```
QObject::connect: No such signal SearchEngine::checkForUpdatesFinished(QHash<QString, qreal>)
QObject::connect:  (receiver name: 'PluginSelectDlg')
```
> Fix signaling to checkForUpdatesFinished() failed

- .gitignore
To exclude the offending file `_build_dir/src/moc_predefs.h`.
> .gitignore: ignore moc_*.h

- src/app/main.cpp
write() is declared with __attribute__ ((__warn_unused_result__)) and as
such we shall check its return value. Took opportunity and adjusted
error reporting a bit: if writing to stderr fails, try to write to
stdout.
Would appreciate a quick review, since Gentoo builds are broken now.
> Fix release CMake build

- src/app/main.cpp
We stored reference to parameters object in main(), but that object gets
deleted when we reset Application object upon entering daemon mode.
Change reference to copy to fix that.
> Fix crash when entering daemon mode. Closes #6759.

- src/base/rss/rss_folder.cpp
- src/base/rss/rss_folder.h
When we looking at RSS Folder Articles it should be updated whenever a child RSS Item has been added/removed.
> Forward add/remove child RSS Item event as set of add/remove Articles events

- src/base/bittorrent/session.cpp
When searching for incomplete files for a new torrent (as introduced in
commit e0d9ae3), we should use the actual top-level directory name
(which may have been modified in the dialog) instead of the default
torrent name.
Fixes #6265.
> Use actual top-level dirname to look for incomplete files in new torrent

- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
- src/base/unicodestrings.h
- src/gui/addnewtorrentdialog.cpp
- src/gui/properties/propertieswidget.cpp
- src/gui/properties/proplistdelegate.cpp
- src/gui/properties/proplistdelegate.h
- src/gui/torrentcontentmodel.cpp
- src/gui/torrentcontentmodel.h
- src/gui/torrentcontentmodelfile.cpp
- src/gui/torrentcontentmodelfile.h
- src/gui/torrentcontentmodelfolder.cpp
- src/gui/torrentcontentmodelfolder.h
- src/gui/torrentcontentmodelitem.cpp
- src/gui/torrentcontentmodelitem.h
Following the path of PR #2885 and #4936 this PR proposes a new column for the "Contents" tab of the torrent properties. This column show current availability of the files in the pool.
One of the probable use cases for this feature is  way to make a quick estimation whether a given file of folder can be downloaded using given torrent, or it is better to look for another collection.
This is WIP code, but I want to share it early, because there are a couple of design decision which need to be done, but I feel a lack of a good criterion. Here they are.
1. Availability for files is computed in a different way comparing to the progress bar: if a piece is available from many different peers, it is counted only once. This seems to be logical, since we most likely need this information to decide …
> Add availability column to torrent contents

- src/gui/mainwindow.cpp
- src/gui/mainwindow.h
Simply ignore DoubleClick event, as it always come after Trigger event.
> Fix double click on system tray icon causing program to open and minimize immediately

- src/gui/CMakeLists.txt
- src/gui/addnewtorrentdialog.cpp
- src/gui/addnewtorrentdialog.h
- src/gui/addnewtorrentdialog.ui
- src/gui/fspathedit.cpp
- src/gui/fspathedit.h
- src/gui/fspathedit_p.cpp
- src/gui/fspathedit_p.h
- src/gui/gui.pri
- src/gui/optionsdlg.cpp
- src/gui/optionsdlg.h
- src/gui/optionsdlg.ui
The combinations of `QLineEdit` or `QComboBox` with a browse button for file system paths editing most likely results in selecting files or dirs via the button and a file dialog. However,  typing with auto completion might provide a better alternative. This PR implements it in the standard for Qt way, using `QCompleter` and `QFileSystemModel`.
The PR adds `FileSystemPathLineEdit` and `FileSystemPathComboEdit` classes (share most of the implementation) that provides widgets for editing file names with `QLineEdit` or `QComboBox` (in editable mode). The widgets also contain the "Browse" button, which launches a file dialog. Properties of the dialog (title, file filter, etc.) are specified as `FileSystemPathEdit` class properties. 
The class also uses `Utils::Fs::fromNativePath()` and …
> Add a widget for editing file names

- src/base/settingvalue.h
* Add another constructor to save a call to proxyFunc when its not needed
note that this call is a virtual function call
* Pass in proxyFunc by const reference
* move get methods together ~~, and return m_value directly~~
> Tweak CachedSettingValue

- src/base/utils/fs.cpp
- src/base/utils/fs.h
Uses [QStorageInfo](https://doc.qt.io/qt-5/qstorageinfo.html) Instead of using native APIs/#if for each platform.
> cross-platform free space on disk (Closes #6780)

- src/webui/webapplication.cpp
This allows the API caller to see if the torrent was successfully added. Currently, the API returns a blank string regardless of the outcome.
> Include response status in upload torrent API

- src/gui/optionsdlg.cpp
- src/gui/optionsdlg.h
Because simple solutions are not for us, and because qBt debug stream is highly crowded (BTW, let's switch over to categorised debug output?), this PR routinely replaces signal/slots connections in options dialog with the new syntax.
> Use new signal/slot syntax in options dialog

- src/gui/CMakeLists.txt
- src/gui/addnewtorrentdialog.cpp
- src/gui/categoryfiltermodel.cpp
- src/gui/categoryfiltermodel.h
- src/gui/categoryfilterproxymodel.cpp
- src/gui/categoryfilterproxymodel.h
- src/gui/categoryfilterwidget.cpp
- src/gui/gui.pri
- src/gui/transferlistsortmodel.cpp
I would definitely appreciate a review of the last commit, because I am _way_ out of my league here.  Is there really no easier way to get a simple case-insensitive sort?
> Fix instances where categories where still sorted case-sensitively. Closes #6708.

- src/base/bittorrent/addtorrentparams.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
- src/gui/optionsdlg.cpp
- src/gui/optionsdlg.h
- src/gui/optionsdlg.ui
- src/gui/torrentcreatordlg.cpp
- src/gui/transferlistwidget.cpp
- src/gui/updownratiodlg.cpp
- src/gui/updownratiodlg.h
- src/gui/updownratiodlg.ui
- src/webui/extra_translations.h
- src/webui/prefjson.cpp
- src/webui/www/public/preferences_content.html
This feature appears from time to time in the Issues section as a [Wishlist].  I use it heavily.
This allows to specify seeding a torrent for up to X minutes.  You can also mix it with the max share ratio option and the torrent will stop seeding if any of both rules applies first.
This PR has several changes:
1.- The method processBigRatios() was renamed to processShareLimits().  That's because the name was misleading in the first place since most people set "1" or "2" as a share ratio limit and those are not big numbers, and also because this method now also process seeding time limits.
2.- Sadly I couldn't change the name of max_ratio_act for the action to apply to the torrent when it's completed in the WebUI because that would break backward compatibility.
3.- The ETA method now …
> Share torrents until seeding time reaches an specific amount of minutes

- src/gui/categoryfilterproxymodel.h
```
[ 56%] Building CXX object src/gui/CMakeFiles/qbt_gui.dir/categoryfilterproxymodel.cpp.o
In file included from /opt/qt55/include/QtCore/QSortFilterProxyModel:1:0,
from /home/travis/build/evsh/qBittorrent/src/gui/categoryfilterproxymodel.h:32,
from /home/travis/build/evsh/qBittorrent/src/gui/categoryfilterproxymodel.cpp:29:
/opt/qt55/include/QtCore/qsortfilterproxymodel.h:122:17: error: ‘virtual QModelIndex QSortFilterProxyModel::index(int, int, const QModelIndex&) const’ was hidden [-Werror=overloaded-virtual]
QModelIndex index(int row, int column, const QModelIndex &parent = QModelIndex()) const Q_DECL_OVERRIDE;
^
In file included from /home/travis/build/evsh/qBittorrent/src/gui/categoryfilterproxymodel.cpp:29:0:
/home/travis/build/evsh/qBittorrent/src/gui/categoryfilterproxymodel.h:4 …
```
> Fix build error.

- src/gui/optionsdlg.ui
* Reverts back options dialog size
https://github.com/qbittorrent/qBittorrent/pull/5375#discussion_r117052936
* Also removes unused tabstops
* Remove unused row in "Share Ratio Limiting" group box
* Remove unless horizontal layout widget
Should be no visual change, just underlying cleanups.
> [Quick Fix] Cleanup options dialog

- cmake/Modules/FindSystemd.cmake
Apparently, recent version of CMake made PkgConfig stuff scooped and we
need to call find_package(PkgConfig) in FindSystemd.cmake too, the call
in FindLibtorrentRasterbar.cmake, that is always used first, is not
enough now.
> [QuickFix] cmake: fix FindSystemd.cmake

- src/gui/rss/articlelistwidget.cpp
One of the commits from PR #6698. This commit does not really belong to that PR. It replaces hardcoded colours in RSS list widget with colours from app palette.
> Do not use hardcoded colors in RSS feed view

- src/webui/www/public/download.html
- src/webui/www/public/scripts/mocha-init.js
- src/webui/www/public/upload.html
These are cosmetic fixes for the pull request #6475 that was merged like 3 months ago but I think it doesn't look good.
Here's how it looks right now:
Here's what I'm proposing:
No unnecessary scrollbar and no centering of the checkmark, it's so far way is hard to see what it is for.
Same for download, here's how it looks right now:
And here's what I'm proposing:
> Cosmetic fixes for WebUI upload and download windows

- src/webui/www/public/scripts/client.js
First I should apologize that I haven't reviewed all WebUI changes until now so I'm fixing bugs that are several months old.
This fixes a little bug introduced with PR #5547 with commit 7aadf644e0a0abd47b3f5fc749c2ea96b4ed45e3.  By the way, this was a great addition to the WebUI and I love these new features.
The PR renames torrentsTable.table to torrentsTable.tableBody but the developer didn't rename it everywhere; specifically, he forgot about the file client.js.
What is happening is that when you select a filter through the WebUI: All, Completed, Paused, whatever, you have to wait until the next REST call to see the changes in your browser window, because of this line:
```
if (typeof torrentsTable.table != 'undefined')
updateMainData();
```
Since PR #5547 torrentsTable.table is always …
> Fix slow filtering in WebUI

- src/base/utils/fs.cpp
- src/gui/addnewtorrentdialog.cpp
- src/gui/addnewtorrentdialog.h
- src/gui/previewselect.cpp
- src/gui/properties/propertieswidget.cpp
- src/gui/torrentcontentmodelfile.cpp
- src/gui/torrentcontentmodelfolder.cpp
*  Fix renaming files is not case sensitive on Windows platform
*  Code formatting 
*  Improve error message reported to user
Should not contain "file" or "folder", because it's not clear which type is selected
> Fix renaming files is not case sensitive on Windows platform

- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/torrentcreatorthread.cpp
- src/base/bittorrent/torrentcreatorthread.h
- src/base/global.h
- src/base/preferences.cpp
- src/base/preferences.h
- src/base/utils/fs.cpp
- src/gui/mainwindow.cpp
- src/gui/mainwindow.h
- src/gui/torrentcreatordlg.cpp
- src/gui/torrentcreatordlg.h
- src/gui/torrentcreatordlg.ui
- All settings/text field in Torrent creator & dialog size are now remembered.
- Support drag and drop in Torrent creator.
- Support drag and drop to open Torrent creator in mainwindow.
- Revised popup messages.
- Switch to modeless dialog.
scrnshot: [old](https://cloud.githubusercontent.com/assets/9395168/14884053/ea122c40-0d74-11e6-9790-7915a2d24973.png), [new](https://cloud.githubusercontent.com/assets/9395168/14935452/b0c953fa-0f04-11e6-9482-84c6a788827b.png)
> Revamp Torrent creator

- src/app/cmdoptions.cpp
- src/base/utils/string.h
- src/webui/abstractwebapplication.cpp
- src/webui/abstractwebapplication.h
Previously cookie name such as `<any string>SID` will be mistakenly
accepted as `SID` session ID, this commit fixes it.
> [WebUI] Make cookie parsing robust

- src/base/bittorrent/torrentinfo.cpp
- src/base/bittorrent/torrentinfo.h
- src/webui/btjson.cpp
- src/webui/btjson.h
- src/webui/webapplication.cpp
- src/webui/webapplication.h
Now getting pieces information for a specific torrent is possible via:
* returns a list of states (integers) of pieces in order. defined:
"0=not downloaded", "1=downloading", "2=downloaded".
`GET /query/getPieceStates/<torrent_hash>`
* returns a list of hashes (hex strings) of pieces in order:
`GET /query/getPieceHashes/<torrent_hash>`
-------
UPDATE1: updated API names
> [WebAPI] Get piece information/state 

- src/gui/properties/piecesbar.cpp
When torrent size is smaller than the image width, bytes per pixel was
set to zero and code was crashing. Set it to -1 instead, as we do when
image is empty. This will disable highliting, but our algorithm does not
work in this case anyway.
> Fix crash in download piece bar

- src/gui/rss/feedlistwidget.cpp
How to reproduce:
click on RSS feed (not Unread feed) then click on any article then right click this feed then delete.
This PR has a solution if you want to keep unread count doesn't change till changing articles, we can change this behavior to make article read on click (I can work on it).
Crash report:
qBittorrent has crashed
Please file a bug report at http://bugs.qbittorrent.org and provide the following information:
qBittorrent version: v3.4.0alpha (64-bit)
Libtorrent version: 1.0.11.0
Qt version: 5.9.0
Boost version: 1.64.0
OS version: Windows 10 (10.0) 10.0.15063 x86_64
```
#100 Qt5Guid.dll          0x00007ff88f55be5a QDragManager::self()
#101 Qt5Guid.dll          0x00007ff88f55e9d3 QDragManager::self()
#102 Qt5Guid.dll          0x00007ff88f519a15 QDragManager::self()
#103 …
```
> Fix crash when delete RSS feed

- src/gui/mainwindow.cpp
... and statusbar was disabled before.
Since QMainWindow creates default statusbar we should remove it when application starts with disabled statusbar option.
> Fix empty statusbar showed after app restarted

- src/gui/mainwindow.cpp
Placing modeless dialog A on top of modeless dialog B, then open dialog B again,
the expected behavior is B on top of A.
Before this PR, A is still on top of B.
> Fix focusing on the previously opened dialog didn't work

- src/CMakeLists.txt
In qmake we define QStringLiteral=QLatin1String, so define it in cmake
builds too.
> cmake: fix compilation with Qt 4

- .travis.yml
- src/app/qtsingleapplication/CMakeLists.txt
This fixes CMake compilation with bundled QtSingleApplication, which is broken now due to the removed already -Wno-error=old-style-cast flag.
> Disable warnings in the bundled QtSingleAppplication and fix CMake builds in Travis

- src/gui/transferlistfilterswidget.cpp
I don't know if that is useful but I was downloading a torrent from ubuntu.com and qBT didn't recognize its favicon that's why I thought about using Google to grab the favicon without worrying about details.
google will be used only in case of failure of getting {root}/favicon.ico or {root}/favicon.png
Time benchmarking: varies from 3 to 8 ms to fetch via Google.
the only drawback is that it returns a generic icon if there is no favicon.
> Fetch Favicons via google

- src/base/bittorrent/torrentcreatorthread.cpp
- src/base/bittorrent/torrentcreatorthread.h
- src/gui/torrentcreatordlg.cpp
- src/gui/torrentcreatordlg.h
- src/gui/torrentcreatordlg.ui
See: ~~[screenshot](https://cloud.githubusercontent.com/assets/9395168/26484280/c38960ea-4223-11e7-82f3-0a18d5c8973f.png)~~, [screenshot2](https://cloud.githubusercontent.com/assets/9395168/26518946/9fea7dbc-42ec-11e7-9377-729e3e6444f4.png)
~~The calculation `libt::create_torrent().num_pieces()` is quite fast.~~ But not fast enough to do so for every input event.
> [TorrentCreator] Show total number of pieces. Closes #6774.

- src/base/http/server.cpp
If there is going to be v3.3.15. Please include this in.
> Fix keep alive duration was wrongly in milliseconds instead of seconds

- src/gui/rss/articlelistwidget.cpp
ArticleListWidget::handleArticleList() can be called inside
ArticleListWidget::handleArticleAboutToBeRemoved() and list widget
item can be removed at this point. Now we checking for it existence.
Closes #6896.
> Fix crash in ArticleListWidget. Closes #6896

- src/gui/fspathedit.cpp
- src/gui/fspathedit_p.cpp
- src/gui/fspathedit_p.h
Not a code I can be proud of. Any suggestions are very welcome.
This PR adds a QValidator implementation for filesystem paths and uses validation result in the file line edit to show a warning action with explanation tooltip when validation was not successful.
The following situations are handled:
1. File or directory does not exist.
2. Expected a file (directory), but path points to a directory (file).
3. User has no read permission for the object, pointed by path.
4. User has no write permission for the object, pointed by path.
Tests are selected basing on the widget mode (file or directory open or save).
> Add visual feedback for wrong paths in FileSystemPathEdit

- src/base/http/types.h
This save us another transition when some day we implements HTTP/2 (which all headers are in lowercase).
> Convert all http header name constants to lowercase

- src/base/bittorrent/addtorrentparams.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
- src/base/preferences.cpp
- src/base/preferences.h
- src/base/torrentfilter.cpp
- src/base/torrentfilter.h
- src/gui/CMakeLists.txt
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/gui/gui.pri
- src/gui/tagfiltermodel.cpp
- src/gui/tagfiltermodel.h
- src/gui/tagfilterproxymodel.cpp
- src/gui/tagfilterproxymodel.h
- src/gui/tagfilterwidget.cpp
- src/gui/tagfilterwidget.h
- src/gui/torrentmodel.cpp
- src/gui/torrentmodel.h
- src/gui/transferlistfilterswidget.cpp
- src/gui/transferlistfilterswidget.h
- src/gui/transferlistsortmodel.cpp
- src/gui/transferlistwidget.cpp
- src/gui/transferlistwidget.h
This change adds a Tags system to the GUI. Tags are a set of user defined text strings that serve as arbitrary metadata for the purpose of organizing and filtering torrents. 
Tags are conceptually similar to the existing Categories system, with the following differences:
- A torrent can have any number of Tags, whereas only one Category is allowed.
- Tags are unstructured; Categories have a tree structure.
- Tags are not linked into other torrent management systems, like save path assignment. Hence they can be added & removed without any complex side effects.
The motivation for this system was to allow more flexible torrent organization in the GUI - for example, being able to assign multiple filterable labels to a single torrent. This is difficult to do with the existing Categories …
> Add a Tags system to the GUI to expand torrent organization / filtering options. Closes #13.

- winconf-msvc.pri
The report in #7021 imply that there are recursive calls in `boost::asio::ssl` and I concluded that all stack space had exhausted, eventually qbt crash.
* Raise total stack size on Windows to 8 MB. Closes #7021.
MSVC default was 1 MB.
8 MB is also the default of arch linux (x64), so I follow that.
https://docs.microsoft.com/en-us/cpp/build/reference/stack-stack-allocations
* Separate "Release mode" linker options
> Raise total stack size on Windows

- src/gui/fspathedit_p.cpp
- src/gui/fspathedit_p.h
This fixes the bug when completion popup is shown when AddNewTorrent dialog is activated and  default save path is set to file system or drive root.
> Do not show completion when text is not being edited

- src/webui/webapplication.cpp
Also skips the check if the user's session is already active.
Closes #6860 
Replaces #6862
> Skip webui username/password check for active sessions

- src/base/settingvalue.h
- src/base/torrentfileguard.cpp
- src/base/torrentfileguard.h
- src/gui/search/searchtab.cpp
- src/gui/search/searchtab.h
Enums are stored as strings, that improves configuration file
readability and maintainability. String values are obtained via
QMetaEnum, and since with Qt 5.5 QMetaEnum::fromType() includes a
static_assert, this has to be a safe method.
So, this change provides a simple way to store enumerations in the config file.
> Implement enum support in CachedSettingValue

- src/base/bittorrent/session.cpp
This sets interface for outgoing traffic to the same as for ingoing
(listetning) with libtorrent 1.1.x.
> Set interface for outgoing traffic.

- src/CMakeLists.txt
- src/app/main.cpp
- src/base/preferences.cpp
- src/base/preferences.h
- src/gui/CMakeLists.txt
- src/gui/addnewtorrentdialog.cpp
- src/gui/categoryfilterwidget.cpp
- src/gui/categoryfilterwidget.h
- src/gui/executionlog.cpp
- src/gui/hidabletabwidget.h
- src/gui/mainwindow.cpp
- src/gui/mainwindow.h
- src/gui/optionsdlg.cpp
- src/gui/optionsdlg.h
- src/gui/properties/proptabbar.cpp
- src/gui/rss/rsswidget.cpp
- src/gui/search/searchwidget.cpp
- src/gui/statusbar.cpp
- src/gui/tagfilterwidget.cpp
- src/src.pro
Hello,
This pull-request consolidates and fixes most of the existing changes (e.g. #4757 and #2096) and brings us other improvements. Whereas this is not a complete fix to all design issues in qBittorrent in regards to macOS, this is certainly a good start.
Please let me know what you consider important to change (if anything), and let's get this merged :)
The changelist includes:
<details>
<summary>Screenshots</summary>
</details>
Regarding separator → spacer replacement: I am thinking of removing them entirely, since they do not really add much clarity, but to my eyes it looks fine either way. If you think it is better to remove them, let me know.
Regarding Dock restoration: it is a very annoying bug (or shall I say feature) in Qt, no event is delivered to the dispatcher when you click …
> Various macOS UI improvements

- src/gui/mainwindow.cpp
There is just another macOS UI issue I did not spot in my initial patch.
On macOS `About <name>`, `Check For Updates…`, `Preferences…`, and `Quit <name>` should reside in the main menu column. Like it is [now](https://user-images.githubusercontent.com/4348897/28383842-2b7ceca4-6ccb-11e7-89a6-69e060e0f513.png).
Qt attempts to reorder the items automatically, but mostly fails. `Check For Updates` is definitely not around, and other languages are just messed up. A solution is to provide a MenuRole.
Also asking for this to go to 3.4.0, since it is very minor and in fact should have been part of #6952 if I noticed.
> Fix main menu item location on macOS

- src/base/searchengine.cpp
- src/base/searchengine.h
- src/gui/mainwindow.cpp
- src/gui/search/pluginselectdlg.cpp
- src/gui/search/pluginselectdlg.h
- src/gui/search/searchwidget.cpp
Crash reproduce steps:
1. open search plugins dialog, the one that install/update plugins, leave it open.
2. minimize qbt to tray.
3. right click on tray icon and quit qbt.
> Fix crash when exiting qbt with search plugin update dialog open

- src/base/bittorrent/torrenthandle.cpp
The same as #7175 but it is for v3.3.x branch.
> [v3.3.x] Fix temporary subfolder isn't deleted

- src/gui/transferlistwidget.cpp
- src/gui/transferlistwidget.h
This change replaces the standard QAction context menu items used for displaying / toggling the tags assigned to selected torrents in the transfer list. The custom menu items offer two improvements:
- They are capable of displaying tristate checkboxes. The 'partially checked' state is used to indicate the case where a given tag is assigned to some, but not all, of the selected torrents.
- You can now toggle multiple tags without needing to reopen the menu. This makes it much faster to perform multiple tag edits on a group of torrents.
I also got rid of the "Remove..." tag dialog option. With the faster system for toggling tags, it is no longer needed.
> Improve tag selection context menu. Closes #7060

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrentinfo.cpp
- src/base/bittorrent/torrentinfo.h
This PR get rid from creation of subfolders inside temporary folder. The single exception is multifile torrents with stripped root folder. They have subfolders with its original root name.
> Don't create subfolder inside temp folder. Closes #5503

- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
Since a lot of users prefer to move the files of the torrent manually and then use the "Set location", they lose the existing data and get broken torrent (there are many issues about it on this bugtracker). This PR should fix the problem.
P.S. Auto Torrent Management feature isn't affected  by this PR. It always overwrite existing files.
> Don't replace existing files when manually relocating torrent

- src/base/bittorrent/torrenthandle.cpp
**Don't** remove shared temp folder when torrent finished and moved to
its "complete" folder. Only torrents with stripped root folder
have subfolder in temp folder so they should remove it.
> Don't remove shared temp folder

- src/app/application.cpp
- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrentcreatorthread.cpp
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrentinfo.cpp
- src/base/bittorrent/tracker.cpp
- src/base/filesystemwatcher.cpp
- src/base/net/downloadhandler.cpp
- src/base/net/downloadmanager.cpp
- src/base/net/proxyconfigurationmanager.cpp
- src/base/preferences.cpp
- src/base/profile.cpp
- src/base/scanfoldersmodel.cpp
- src/base/searchengine.cpp
- src/gui/addnewtorrentdialog.cpp
- src/gui/mainwindow.cpp
- src/gui/optionsdlg.cpp
- src/gui/powermanagement/powermanagement_x11.cpp
- src/gui/programupdater.cpp
- src/gui/properties/peerlistwidget.cpp
- src/gui/properties/propertieswidget.cpp
- src/gui/search/pluginselectdlg.cpp
- src/gui/search/searchwidget.cpp
- src/gui/torrentcontentmodel.cpp
- src/gui/transferlistwidget.cpp
- src/webui/abstractwebapplication.cpp
- src/webui/prefjson.cpp
- src/webui/webapplication.cpp
Qt documentation says:
>qDebug(), qInfo(), qWarning(), qCritical(), qFatal() expect %s arguments
to be UTF-8 encoded, while qPrintable() converts to local 8-bit encoding.
Therefore qUtf8Printable() should be used for logging strings instead of
qPrintable().
> Use qUtf8Printable() for logging strings

- src/gui/fspathedit_p.cpp
- src/gui/search/searchtab.cpp
- src/gui/search/searchtab.h
* Initialize variables
* Remove unused variable
Also
* @sledgehammer999 can you filter out the path `/opt/qt55` in coverity dashboard?
* @glassez, 
at https://github.com/qbittorrent/qBittorrent/blob/master/src/base/asyncfilestorage.cpp#L41, the exception is handled nowhere, is this behavior intended?
or RSS function should just fail silently without crashing the program?
> Fix issues found by coverity scan

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
RC_1_1 does the same calculation when it fills the deprecated `cache_status::average_job_time` field.
> Fix calculation of 'Average time in queue' stat under libtorrent 1.1.x

- src/gui/optionsdlg.ui
This fixes RSS tab looking differently from all the other preference tabs at least on macOS.  
Screenshots for reference: [example tab 1](https://user-images.githubusercontent.com/4348897/29269044-399bc648-80f8-11e7-8710-77c9e4028715.png), [example tab 2](https://user-images.githubusercontent.com/4348897/29269045-39e22c50-80f8-11e7-8eb9-0c06a74a99bf.png),  [ugly RSS](https://user-images.githubusercontent.com/4348897/29269136-a5db04e0-80f8-11e7-8f8f-464b55e007f0.png), [fixed RSS](https://user-images.githubusercontent.com/4348897/29269046-39e57f7c-80f8-11e7-84ad-50ed4a5f9b2e.png).
It could have been done the other way, for example, by adding an extra scrollarea widget around the RSS tab, but this would be inadequate design-wise, since the inner widgets should not pretend to look similarly …
> Unify preference window borders across the tabs

- src/gui/mainwindow.cpp
I fixed the bugs with cross icon in #6952, yet managed to break hide icon (the middle one) unfortunately, which resulted in one being unable to restore the window after hiding it via the yellow icon. This change ensures that both icons work just fine.
Please merge into 3.4.0. From what I can tell there are no conflicts with #7253.
> Fix macOS window restoration after using hide icon

- src/gui/macutilities.h
- src/gui/macutilities.mm
- src/gui/mainwindow.cpp
This got accidentally broken as a result of #6952. Now uses a native API, which is available since [10.8](https://developer.apple.com/documentation/foundation/nsusernotification), and thus should be fine.
> Fix notification display on macOS

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/advancedsettings.cpp
See details in this bug report I filed: https://github.com/arvidn/libtorrent/issues/2251
From that thread `use_disk_cache_pool` seems to not be well tested and they're in favor of removing it.
The change in the meaning of the value of `cache_size` shouldn't change older client behavior compiled against RC_1_0, since it seems that branch contains a bug making the cache behave the same for `-1` and `0` values. And by my limited testing to bigger values too.
The 2nd commit is self-explanatory. Why store them as uints when libtorrent will take them as ints?
> Options to better memory control by libtorrent. Closes #7029.

- src/webui/abstractwebapplication.cpp
X-Forwarded-Host is a foreign proxy setting, it isn't the same as qbt's local setting and thus it makes no sense to verify it.
@sledgehammer999 if v3_3_x has another release, please include this in.
IMO this issue isn't serious enough to do a new release just for it.
Also probably best to include this in 3.4 beta 2 (if there is going to be one).
> WebAPI: fix validating wrong header field. Closes #7311.

- src/base/searchengine.cpp
- src/base/utils/version.h
Printing of Version with all components set to zero was segfaulting due
to underflow in array index. Also add log message for such plugins.
> Fix ignoring of incorrect version strings in search plugins. Closes #7101

- src/gui/advancedsettings.cpp
This will allow selecting VPN tunnel interfaces under Windows
Fixes #7291
> Disable skipping of loopback interfaces

- src/base/bittorrent/session.cpp
Perhaps this PR also fixes many other similar issues.
> Skip user input events when adding torrent. Closes #7327

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
I found some interesting options when reading libtorrent's document:
- [guided_read_cache](http://www.libtorrent.org/reference-Settings.html#guided_read_cache): [default off]
Also see: [tuning#disk-cache](http://www.libtorrent.org/tuning.html#disk-cache)
> The idea being that slow peers don't use up a disproportional amount of space in the cache
This looks promising. 
-  [prefer_tcp](http://www.libtorrent.org/reference-Settings.html#bandwidth_mixed_algo_t): [default off]
Also see: [tuning#utp-tcp-mixed-mode](http://www.libtorrent.org/tuning.html#utp-tcp-mixed-mode)
Since there are issues with `peer_proportional` in the past, then just use `prefer_tcp` in all cases.
I can't see why this should be depending on `rate_limit_utp`.
- [use_parole_mode](http://www.libtorrent.org/reference-Settings …
> libtorrent session options

- src/gui/categoryfilterwidget.cpp
CategoryFilterWidget must contain subcategories when they are expanding. It was broken after one of last changes.
> Fix CategoryFilterWidget::sizeHint()

- src/gui/properties/propertieswidget.cpp
The check that I removed was introduced in the 1st form in 4b2d8a7941bd75a54345bf748258de9c47acd8ed and in the 2nd form in d413bc65eff957aec03fb7fa4e12e6e8f5ca6e91
The check was to not expand when the torrent was stripped. But the 2nd form ended up in not expanding the torrents which are singlefile but the file is inside a folder already.
But there's no harm in always trying to expand the file list. It doesn't crash or output any warning. So I reverted to the old way to not do any checks.
> Fix file list expansion on singlefile torrent with folder.

- src/base/bittorrent/session.cpp
The torrent is removed from session after `deleteTorrent()`
yet we still invoke `torrent->name()`, thus result in crash.
I imagine using shared_ptr for torrent handle pointer could be a lot better.
> Fix dereferencing freed pointer

- src/base/tristatebool.h
It seems a single byte is sufficient.
Comments welcome!
> Use smaller data type for TriStateBool

- src/gui/downloadfromurldlg.h
- src/gui/downloadfromurldlg.ui
- src/gui/login.ui
- src/gui/preview.ui
- src/gui/previewselect.cpp
- src/gui/previewselect.h
- src/gui/trackerlogin.cpp
- src/gui/trackerlogin.h
This PR will make button order follow the platform default.
For example: windows: OK, Cancel; linux: Cancel, OK.
> Replace dialog ok-cancel buttons with QDialogButtonBox

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
Is it ok that I put the struct in the private section?
`torrent_deleted_alert` and `torrent_delete_failed_alert` are always preceded by `torrent_removed_alert`
> Better reporting of success/failure of torrent and file deletion.

- src/gui/fspathedit.cpp
Introduced in 30081e0.
I discovered this from the most obvious offending place:
Before:
After:
Other places where it is used are tighter now too.
> Don't use margins in FileSystemPathEdit widgets.

- src/gui/optionsdlg.cpp
Option dialog's state will be saved on cancel action too.
> Options dialog save windows state in destructor

- src/gui/optionsdlg.cpp
- src/gui/optionsdlg.h
The reason for this was, that options dialog overflow at bottom, so Ok and Cancel buttons was out of screen.
> Center Options dialog when showed

- src/gui/addnewtorrentdialog.cpp
It is confusing if the dialog doesn't show the existing torrent name.
> Show torrent name in "add new torrent" dialog on merging trackers

- src/gui/transferlistdelegate.cpp
The "Time active" field was broken, displaying nothing when in downloading state.
> Fix "Time active" field in transfer list

- src/gui/search/pluginselectdlg.cpp
- src/gui/search/pluginselectdlg.ui
enabled sorting for installed plugins list. closes #7526
> allow search plugins sorting. closes #7526

- src/gui/downloadfromurldlg.h
This makes it easier to put each magnet link on its own line.
And there is this "One link per line" message...
* Before:
* After:
BTW, my preference: `QTextOption::NoWrap` > `QTextOption::WrapAnywhere` > `QTextOption::WordWrap` (current git master).
> Set QTextOption::NoWrap property in "Download from URLs" dialog

- src/gui/fspathedit.cpp
This shows up on Windows: Choose a new save path from the browse button in "Add New Torrent" dialog and the path is shown with `/` instead of `\`.
@evsh I am not sure if I should have done this in the base class or in the 2 derived classes.
> Show new paths in native form.

- src/gui/mainwindow.cpp
- src/gui/transferlistwidget.cpp
- src/gui/transferlistwidget.h
As discussed in https://github.com/qbittorrent/qBittorrent/pull/7550#issuecomment-335027918 .
We want to show the accelerator key in the menu but without hitting the ambiguous overload error.
Also, if this PR is accepted, I shall close #7550.
> Fix delete key has no effect due to "Ambiguous shortcut overload"

- src/webui/webui.cpp
I'm trying to debug why qbittorrent-nox fails to listen() to the webui port on my FreeBSD 11.1 jail. This missing error string is the first necessary step.
Also this whole block is inside of `if(pref->isWebUiEnabled())`? Wouldn't it make more sense to throw an exception and die instead of starting up and silently failing to start the webui?
> Report TCPServer errorString() if webui fails to listen to port

- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
- src/base/preferences.cpp
- src/base/torrentfilter.h
- src/gui/guiiconprovider.cpp
- src/gui/mainwindow.cpp
- src/gui/optionsdlg.cpp
- src/gui/optionsdlg.h
- src/gui/transferlistdelegate.cpp
- src/gui/transferlistdelegate.h
- src/webui/btjson.cpp
As per discussion in #6698 I'm splitting that PR onto smaller ones. Here is the first part. No functional changes here, just code formatting and refactoring,
> Themes commit-by-commit part 1

- src/CMakeLists.txt
- src/gui/properties/CMakeLists.txt
- src/gui/properties/speedwidget.cpp
- src/gui/properties/speedwidget.h
- src/src.pro
Remove excess QtConcurrent usage in SpeedWidget. Existing usage of QtConcurrent has no meaning because of: 
1. The only task processed inside separate thread is just to copy 10 simple values from one place to another and sleep 1000 msecs. 
2. There is no heavy GUI blocking operations. 
3. It blocks 1 thread in QtConcurrent forever for infinite loop with Sleep(), hogging resources in QtConcurrent thread pull.
4. It adds burden of inter-thread synchronization and context switching. 
5. Maintenance cost for programmers.
> Excess QtConcurrent usage removal

- src/webui/abstractwebapplication.cpp
Due to #7577, some error message is needed to ease the diagnosis pain.
ps. I'll be moving `isCrossSiteRequest` out of this class later, thus I need to pass `env` as a parameter.
> [WebUI]: Print error messages upon receiving invalid header fields

- src/base/preferences.cpp
- src/base/preferences.h
- src/gui/optionsdlg.cpp
- src/gui/optionsdlg.h
- src/gui/optionsdlg.ui
- src/webui/prefjson.cpp
- src/webui/webui.cpp
- src/webui/www/public/preferences_content.html
As I mentioned in a previous PR, I had an issue with qbittorrent-nox failing to `listen()` on my FreeBSD jail. The reason it was failing is because the webui is hard coded to use `QHostAddress::Any` which tries to bind to IPv4 and IPv6. This caused the failure because my jail has IPv6 disable.
This patch adds a "WebUI\Address" config option. It uses the string parsing built into `QHostAddress`. One caveat is that there is no equivalent string for `QHostAddress::Any`, so I've opted to use the string "*" to mean Any and this is the default.
Since there is parsing now being done in `Preferences`, I've had to add a `PreferencesParsingError` exception class.
> Add WebUi\Address config option

- src/base/bittorrent/session.cpp
Related to bda5be8e4ce3dd998805427af862e134bdc7daa1, but this time is from webUI.
> Disable processing socket events in findIncompleteFiles()

- src/base/bittorrent/session.cpp
libtorrent 1.1 enables upnp by default.
> Disable upnp & nat-pmp on startup if disabled in options. Closes #7338.

- src/app/main.cpp
- src/app/stacktrace.h
- src/app/stacktrace_win_dlg.h
I noticed that signal information is often missing in reported stackdumps...
Examples:
* linux:
```
*************************************************************
Please file a bug report at http://bug.qbittorrent.org and provide the following information:
qBittorrent version: v3.4.0beta2
Caught signal: SIGABRT
Stack trace:
/usr/lib/libc.so.6 : gsignal()+0x110  [0x7f8647f958a0]
/usr/lib/libc.so.6 : abort()+0x1c9  [0x7f8647f96f09]
src/qbittorrent : TorrentCreatorDlg::TorrentCreatorDlg(QWidget*, QString const&)+0x48c  [0x55b786aa66bc]
src/qbittorrent : MainWindow::createTorrentTriggered(QString const&)+0x85  [0x55b786a31805]
```
* windows:
```
qBittorrent version: v3.4.0beta2 (64-bit)
Libtorrent version: 1.1.5.0
Qt version: 5.7.1
Boost version: 1.65.1
OS version: Windows 7 SP 1 6.1.7601 …
```
> Include & print caught signal in stackdump

- src/gui/addnewtorrentdialog.cpp
- src/gui/addnewtorrentdialog.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/gui/fspathedit.cpp
- src/gui/fspathedit.h
Unlike the author of #4084, I decided to put the option into the advanced settings, because I consider the Downloads page overflooded already. Let me know if you want to change this, please.
> Add option to tune download history list length. Closes #4043.

- configure
- configure.ac
- m4/ax_boost_base.m4
- m4/ax_boost_system.m4
If the `AX_BOOST_BASE` & `AX_BOOST_SYSTEM` fail, configure process will stop immediately, so no need for another `AS_IF` variable check and besides, the tested variables could be valid empty.
> Update m4 macros

- src/base/preferences.cpp
- src/base/preferences.h
- src/base/utils/net.cpp
- src/gui/CMakeLists.txt
- src/gui/banlistoptions.cpp
- src/gui/gui.pri
- src/gui/ipsubnetwhitelistoptionsdialog.cpp
- src/gui/ipsubnetwhitelistoptionsdialog.h
- src/gui/ipsubnetwhitelistoptionsdialog.ui
- src/gui/optionsdlg.cpp
- src/gui/optionsdlg.h
- src/gui/optionsdlg.ui
- src/webui/abstractwebapplication.cpp
- src/webui/prefjson.cpp
- src/webui/www/public/preferences_content.html
Requested in #924.
Provides a more permanent solution than this [wiki page](https://github.com/qbittorrent/qBittorrent/wiki/Disable-authentification-of-webGUI) while also allowing the web API auth to be disabled
This feature is useful when qBitttorrent is used behind a reverse proxy with its own authentication scheme, or when it's running on a local network.
> Add ip subnet whitelist for bypassing webui auth

- src/base/bittorrent/torrentcreatorthread.cpp
- src/gui/torrentcreatordlg.cpp
The wait time wasn't long enough causing the thread to terminate prematurely.
Also, to avoid crashing qbt entirely when creating a torrent for a very big file, I decided to wait indefinitely here.
> Fix crash when aborting a torrent creation process

- src/app/application.cpp
"app/application.cpp:108:7: error: class 'Application' does not have
any field named 'm_webui'"
> Fix build with --disable-webui

- src/base/bittorrent/session.cpp
MixedModeAlgorithm::Proportional will throttle TCP connections when utp is in use and users is expecting maximum speed no matter what, so now disable the throttling.
> Change MixedModeAlgorithm default to TCP. Closes #7779.

- configure
- m4/ax_boost_base.m4
Fix building on i686 fails with wrong multilib library path #7845
> Fix i386 build (configure). Closes #7845

- src/base/bittorrent/private/filterparserthread.cpp
When a lot of errors happen the resulting log lines introduce
a huge slowdown of the GUI, due to writing each log line to disk.
Closes #7755.
> Stop logging IP filter parsing errors after a while.

- src/base/utils/string.cpp
- src/base/utils/string.h
- src/gui/addnewtorrentdialog.cpp
- src/gui/categoryfilterproxymodel.cpp
- src/gui/properties/peerlistsortmodel.h
- src/gui/rss/automatedrssdownloader.cpp
- src/gui/search/searchsortmodel.cpp
- src/gui/tagfilterproxymodel.cpp
- src/gui/torrentcontentfiltermodel.cpp
- src/gui/transferlistfilterswidget.cpp
- src/gui/transferlistsortmodel.cpp
- src/gui/transferlistwidget.cpp
When selected to sort on different columns, now qbittorrent will remember previous indexes order and provide a stable sort result.
The most related issue I've found is #6304.
> [GUI] Implement stable sort

- src/base/http/types.h
- src/webui/abstractwebapplication.cpp
- src/webui/www/private/login.html
Tested on Chrome 62, Firefox 57, IE11.
> Fix missing qbt logo on login page in webUI. Closes #7953.

- src/gui/categoryfilterproxymodel.cpp
- src/gui/properties/peerlistsortmodel.h
- src/gui/search/searchsortmodel.cpp
- src/gui/tagfilterproxymodel.cpp
- src/gui/transferlistsortmodel.cpp
mapFromSource() didn't work as expected, when used in lessThan(), it sometimes returns an invalid QModelIndex.
A crash is observed when filtering source model via filterAcceptsRow() in #7952, the crash is due to endless recursive of filterAcceptsRow() & lessThan() calling each other and mapFromSource() is the culprit of it.
This also removes the stable sort functionality.
Sorry for the inconvenience.
Currently the filter function in search tab is unusable. Maybe a new minor release is required.
> Fix crash in #7952

- src/webui/abstractwebapplication.cpp
For some reason `QUrl::fromUserInput()` incorrectly treat URLs like `[::1]:8080` as local files (at least on Windows).
> Fix WebUI is not reachable via IPv6

- src/gui/macutilities.h
- src/gui/macutilities.mm
- src/gui/mainwindow.cpp
- src/gui/properties/propertieswidget.cpp
- src/gui/torrentcontentmodel.cpp
- src/gui/transferlistwidget.cpp
On macOS one expects standard behaviour for all "Reveal in Finder"-like commands, thus including "Open destination folder" qBittorrent has. The idea is to open as many Finder windows as necessary selecting all the necessary files (and folders) in each.
There are several places on the internet discussing this issue (e.g. [1](https://stackoverflow.com/questions/42133029/can-qt-on-mac-open-finder-and-selecthighlight-some-files-in-the-opened-finder), [2](https://stackoverflow.com/questions/9137692/qdesktopservicesopenurl-with-selecting-specified-file-in-explorer)), and it is fairly easy to implement the desired behaviour by invoking the native API.
Please consider merging this into a relatively nearest release, since macOS 4.x is not ready yet, and it will be nice to have this feature land …
> Fix torrent file selection in Finder on mac

- src/gui/mainwindow.cpp
- src/gui/mainwindow.h
- src/gui/mainwindow.ui
On macOS one expects CMD+W to close the window but not hide it into the Dock.
There is a relevant [Qt bug](https://bugreports.qt.io/browse/QTBUG-42242), which explains that one needs to provide a `Close Window` entry for this functionality to work.
Please consider merging this into a relatively nearest release, since macOS 4.x is not ready yet, and it will be nice to have this feature land from the beginning.
> Fix CMD+W not closing the main window

- src/gui/fspathedit.cpp
Changing the icon used for opening a dialog & locating a file.
Before:
After:
> Use standard folder icon for open file behavior on Windows

- src/gui/categoryfilterproxymodel.cpp
- src/gui/properties/peerlistsortmodel.h
- src/gui/search/searchsortmodel.cpp
- src/gui/tagfilterproxymodel.cpp
- src/gui/transferlistsortmodel.cpp
Mentioned in https://github.com/qbittorrent/qBittorrent/issues/8080#issuecomment-353078550
`sortRole()` is used because of https://github.com/qbittorrent/qBittorrent/blob/b8277614ecf719e5ec1f710aa1ef68407f587577/src/gui/properties/peerlistwidget.cpp#L452
> Fix sorting of country flags column in Peers tab.

- src/base/utils/string.cpp
Fix natural sorting when the common part of 2 strings ends partially in a number which continues in the uncommon part.
Closes #8080 #6732.
> Fix natural sorting

- src/base/bittorrent/session.cpp
Closes #7745.
**Testing methodology**
I run the testing build in a VM and the host OS run the official 4.0.2 x64 build. The VM acted as the leecher. I created a new torrent from local files, so I won't get polluted by external peers.
For μTP, I forced the leecher to connect only through μTP.
The only problem I cannot fix is this: The μTP limiting/unlimiting takes effect only for new connections.
I'll open a bug report on libtorrent to see if this intended.
For me at least, the peer classes documentation is a bit confusing or light on details.
So in addition to looking the various code comments on the relevant headers about classes and functions used, you can also look at my small discussion with arvid on the mailing list: https://sourceforge.net/p/libtorrent/mailman/message/36134756/
> Fix application of speed limits on LAN and μTP connections.

- src/base/bittorrent/peerinfo.cpp
...by separating them with newline and adding the identifier character to the description.
> Make peer information flags in peerlist more readable

- src/searchengine/nova/nova2.py
- src/searchengine/nova3/nova2.py
closes #8053 
this removes the clutter from plugins that do not support the selected category
> search only when category is supported by plugin

- src/webui/btjson.cpp
- src/webui/www/public/scripts/dynamicTable.js
Adds the two remaining columns that are present in the GUI but missing from the WebUI:
* Add Tags columns
* Add Time Active column
* Reposition Total Size column to match GUI
> Webui add torrent columns to match gui

- README.md
- configure
- configure.ac
- dist/unix/qbittorrent.appdata.xml
- dist/windows/installer.nsi
- src/gui/about_imp.h
- src/gui/mainwindow.cpp
- src/webui/www/private/index.html
- src/webui/www/public/about.html
www.qbittorrent.org has implemented HSTS (strict-transport-security) for the www subdomain. This PR changes all links to use https for www.qbittorrent.org.
> Use https for www.qbittorrent.org

- src/base/rss/rss_autodownloader.cpp
Don't process new/updated RSS auto downloading rules when AutoDownloader is disabled.
> Don't process new/updated RSS rules when disabled

- src/app/application.cpp
Now I fail to execute my test program and reverting is the simple way.
Also I've gathered reports that the revert works better for users:
https://github.com/qbittorrent/qBittorrent/issues/5439#issuecomment-344438235
https://github.com/qbittorrent/qBittorrent/issues/6352#issuecomment-285689938
> Revert "Run external program" function

- src/gui/torrentmodel.cpp
- src/gui/transferlistsortmodel.cpp
This issue is reproducible under Ubuntu Xenial, that's why we haven't already caught this.
I am not sure if it is caused by the Qt version (5.5.1) or the gcc version(5.3.1).
I somehow believe that the Xenial environment is more strict and more "correct". Let me explain briefly the situation:
1. The `enum class BitTorrent::TorrentState` is declared as `Q_DECLARE_METATYPE(BitTorrent::TorrentState)` too. This allows to use it inside a `QVariant`
2. In `TorrentModel::data()` for the `TR_STATUS` column we first converted the `TorrentState` to `int` and then we returned the **int** as a `QVariant`
3.  In `TransferListDelegate::paint()` for the `TR_STATUS` column we tell the QVariant to convert the underlying `int` type to an `enum class` named `BitTorrent::TorrentState`. This fails and returns …
> Fix constant status of '[F] Downloading'. Closes #7628.

- src/gui/torrentcreatordlg.cpp
- src/gui/torrentcreatordlg.ui
According to https://github.com/arvidn/libtorrent/pull/2669#issuecomment-355553751
It seems there are rare occasions that 32 MiB piece size is needed.
> Torrent creator: raise maximum piece size to 32 MiB

- src/gui/transferlistwidget.cpp
- src/gui/transferlistwidget.h
Currently as of this writing, you can force a reannounce event for a torrent if you go into the respective torrent's trackerlist and use the context menu there. However, this can be tedious if the user is going through multiple torrents and forcing a reannounce on each one. This pull request remedies that.
Now, there is a new "Force reannounce" option under the context menu for the transferlist. Users can now select a multitude of torrents and select this new option, and it will reannounce to every tracker within each torrent that the user has selected.
There are already a few torrent clients that support such an option, such as Deluge or Transmission. This PR also closes #6448. Feel free to let me know your thoughts!
> transferlist: added a force reannounce option

- src/gui/search/searchwidget.cpp
This PR only adds separators to the Search tab's comboboxes if there are additional items to separate.
> Only add Search combobox separators as needed

- src/webui/www/public/scripts/dynamicTable.js
This matches the torrent statuses in the webui to the statuses [in the gui](https://github.com/qbittorrent/qBittorrent/blob/e48b97466c15dfec06a32843ff59648949c0e3c8/src/gui/transferlistdelegate.cpp#L226).
> Match webui statuses to gui, closes #7516

- CODING_GUIDELINES.md
Coding style changes suggestion.
The my reasons:
1. Less code for the same thing,
2. Use special thing, not the workaround.
> Require '#pragma once' in new code

- src/base/rss/rss_session.cpp
@sledgehammer999, to not to put unrelated logic in **SettingsStorage** class, I just try to remove all possible legacy/corrupted RSS settings every time.
> Remove legacy and corrupted RSS settings. Closes #8278

- src/base/preferences.cpp
- src/base/preferences.h
- src/gui/ipsubnetwhitelistoptionsdialog.cpp
- src/gui/ipsubnetwhitelistoptionsdialog.ui
- src/webui/prefjson.cpp
This PR increases the size of the textbox in the ip subnet whitelist gui. It also moves subnet validation directly to `Preferences::setWebUiAuthSubnetWhitelist()` to improve core library robustness (while simplify the calling code).
> Refactor ip subnet whitelist

- src/webui/www/public/css/style.css
- src/webui/www/public/scripts/client.js
- src/webui/www/public/statistics.html
This PR right-aligns stat values while also adding missing units for _Write/Read cache overload_ and _Average time in queue_.
Old WebUI:
New WebUI:
GUI:
> WebUI Statistics parity with GUI

- src/base/searchengine.cpp
- src/gui/properties/trackerlist.cpp
qDeleteAll() is being used on an unnecessary temporary container created
by QHash::values().
Using qDeleteAll(mycontainer) instead.
> Don't use qDeleteAll() on temporaries

- src/gui/optionsdlg.cpp
- src/gui/optionsdlg.h
Found this typo while poking around
> Fixed typo in function name isSplashScreenDisabled()

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
The setting is defaulted to ON. Closes #8295.
> Add "Coalesce reads & writes" checkbox in advanced options

- src/base/bittorrent/session.cpp
- src/gui/statsdialog.cpp
- src/gui/statsdialog.ui
* Redefine CacheStatus.readRatio field.
Now it is defined as:
CacheStatus.readRatio = (blocks read from cache) / (blocks read from disk + blocks read from cache)
The 2 variables in denominator are counted separately and the formula before this change doesn't really make sense
* Add percentage sign to "Read cache hits" stats
* Also remove redundant header include
* Clarify some terms in stats dialog
Reorder list
* Screenshot
Before:
After:
> Improve stats dialog

- src/base/rss/rss_autodownloader.cpp
- src/base/rss/rss_autodownloader.h
- src/base/rss/rss_autodownloadrule.cpp
- src/base/rss/rss_autodownloadrule.h
- src/gui/optionsdlg.cpp
- src/gui/optionsdlg.ui
- src/gui/rss/automatedrssdownloader.cpp
- src/gui/rss/automatedrssdownloader.h
- src/gui/rss/automatedrssdownloader.ui
Hi
This PR is a first attempt at a smart episode filter. It checks the filter name against the article name in the RSS feed, then attempts to pull the episode number out of the name and checks that against a list of previously downloaded files.
There's currently no way to clear the downloaded episode number other than deleting the filter and re-adding it.
This PR should resolve issue #4928
Regards
elFarto
> Implement Smart Filter

- src/base/scanfoldersmodel.cpp
- src/gui/torrentcontenttreeview.cpp
- src/src.pro
- src/webui/api/appcontroller.cpp
It prevents detachments:
To illustrate:
QMap<QString, QString> map;
/* code compiles and works fine but find() returns the non-const
QMap::iterator that detaches!
*/
QMap<QString, QString>::const_iterator it = map.find("girish");
but also some subtle bugs:
QHash<int, int> wrong;
if (wrong.find(1) == wrong.cend()) {
qDebug() << "Not found";
} else {
/* find() detached the container before cend() was called, so it
prints "Found"
*/
qDebug() << "Found";
}
QHash<int, int> right;
if (right.constFind(1) == right.cend()) {
qDebug() << "Not found"; // This is correct now !
} else {
qDebug() << "Found";
}
Enforced by QT_STRICT_ITERATORS definition.
> Don't implicitly cast iterator to const_iterator

- src/webui/www/private/index.html
- src/webui/www/private/scripts/client.js
This feature matches the functionality of the GUI. I've also added a divider between _Speed in Title Bar_ and _Statistics_ to more closely match the GUI.
Old WebUI:
New WebUI:
GUI:
> Add option to show/hide webui status bar

- src/app/main.cpp
Instead of qgetenv("QT_AUTO_SCREEN_SCALE_FACTOR").isEmpty().
It's faster (don't allocate memory) and don't throw exceptions.
> Use qEnvironmentVariableIsEmpty

- src/gui/hidabletabwidget.h
Looks like I forgot to include a header in the past, and it bugs us now.
> Fix compilation with Qt 5.11 on macOS

- src/base/global.h
- src/base/rss/rss_autodownloader.cpp
- src/base/rss/rss_folder.cpp
- src/base/utils/fs.cpp
- src/gui/ipsubnetwhitelistoptionsdialog.cpp
- src/gui/properties/speedplotview.cpp
- src/webui/api/appcontroller.cpp
Explicit or implicit calls to begin() and end() cause a non-const
container to detach from shared data, ie. to perform a deep-copy to gain
a unique copy of the data.
That can be a expensive although unneeded operation.
> Prevent possible c++11 range-loop container detach

- src/base/bittorrent/session.cpp
It also prevents unnecessary parsing, no need to (possibly) pause|delete twice.
I managed to reproduce the crash (sometimes) by having a torrent exceed my chosen ratio _and_ seeding time and then i chose the `Remove them` option to delete the torrent. The log showed the "torrent removed" messages for both ratio and seeding time (the times it didn't crash).
My observation is that the larger the torrent, the higher the chance to crash. Actually i don't think i managed to get a torrent to crash that is a few MB size (files), it just constantly replaced the first 8 chars of the torrent name with gibberish in the log msg of removal for seeding time... in linux. Couldn't reproduce this "8-char" in the official 4.0.4 Win.  
Fixes #7692 Fixes #7935 Fixes #8206 Fixes #8329 Fixes #8376 Fixes #8473
> Fix possible crash when using both share limits

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/optionsdlg.cpp
- src/gui/optionsdlg.ui
[inactive_down_rate
inactive_up_rate](https://www.libtorrent.org/reference-Settings.html#inactive_down_rate)
[auto_manage_startup](https://www.libtorrent.org/reference-Settings.html#auto_manage_startup)
The docs for `auto_manage_startup` don't mention it but AFAIK [it's only used with dont_count_slow_torrents](https://github.com/arvidn/libtorrent/blob/d2e874fca8af9cf9a09f3a9a9080e1e5a66eb974/src/torrent.cpp#L9114)
What i'm worried about is that the labels may not be descriptive enough.
> Expose the libtorrent fields for "dont_count_slow_torrents" to GUI. Closes #5713

- src/gui/optionsdlg.cpp
- src/gui/optionsdlg.h
- src/gui/optionsdlg.ui
- src/webui/www/private/preferences_content.html
Per the [wiki-](https://github.com/qbittorrent/qBittorrent/wiki/Anonymous-Mode) when Anonymous Mode is enabled, UPnP, DHT, and LSD are all disabled. This PR reflects that rule within the GUI + WebUI by disabling their respective options.
> Disable options when Force Proxy is enabled

- src/webui/www/private/scripts/client.js
- src/webui/www/private/scripts/dynamicTable.js
This PR saves Torrent Table's selected row ids prior to a full_update, and then re-selects them once the update completes. The purpose is two-fold:
1. Provide a better user experience by saving the user's selection when a full update occurs
2. Provide a temporary fix for the excessive full updates issue
> Reselect webui torrents after full_update. Temporary fix for #8209.

- src/app/application.cpp
- src/base/rss/rss_autodownloadrule.cpp
Avoid temporary allocations.
QString::xxxRef() returns a QStringRef. QStringRef avoids the memory
allocation and reference counting overhead of a standard QString by simply
referencing a part of the original string.
> Don't create temporary substrings

- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/search/searchdownloadhandler.cpp
- src/base/search/searchdownloadhandler.h
- src/base/search/searchhandler.cpp
- src/base/search/searchhandler.h
- src/base/search/searchpluginmanager.cpp
- src/base/search/searchpluginmanager.h
- src/gui/search/pluginselectdlg.cpp
- src/gui/search/pluginselectdlg.h
- src/gui/search/searchtab.cpp
- src/gui/search/searchtab.h
- src/gui/search/searchwidget.cpp
- src/gui/search/searchwidget.h
Legacy SearchEngine class really has three roles:
1. Manage search plugins,
2. Handle the search job, and
3. Handle the download of the torrent file using the search plugin.
Now it is splitted into 3 classes: SearchManager, SearchHandler and SearchDownloadHandler.
Search GUI is also improved.
Make SearchManager singleton to be accessible from different UI.
NOTE: in GUI application SearchManager instance is still created legacy way. This behavior will be changed later when I complete some other research on the application core.
> Improve Search handling

- cmake/Modules/MacroQbtCompilerSettings.cmake
The pair Clang/qmake builds.
CMake compiler settings are more strict and it causes clang build to fail.
> Make it build when using Clang under CMake

- src/base/bittorrent/torrentinfo.cpp
- src/base/bittorrent/torrentinfo.h
* `torrent_info` constructor has default limits that can't be changed via
parameters, so we handle the loading process manually and explicitly
specifiy the limits to `bdecode()`.
* The token_limit is changed to 10000000.
> Fix loading very large torrents. Closes #8449

- src/gui/optionsdlg.cpp
- src/gui/optionsdlg.ui
FileSystemPathEdit::selectedPath() returns path in unix format, so we must convert it to native format.
> Revert back to QLineEdit for "Run external program". Closes #7800.

- src/base/http/connection.cpp
- src/base/http/connection.h
- src/base/http/requestparser.cpp
- src/base/http/requestparser.h
- src/base/http/types.h
Major points:
* Enable Http persistence connection: This enables reusing existing TCP
connection instead of opening a new connection for every request
* Add more checks and also more strict checks for invalid conditions
Minor points:
* Add http version field
* Raise max request size to 20MB
* Add author in license
* Use Qt5 new connect syntax
> Rewrite RequestParser

- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/tracker.cpp
- src/base/bittorrent/tracker.h
- src/base/http/requestparser.cpp
- src/base/http/types.h
- src/base/utils/bytearray.cpp
- src/base/utils/bytearray.h
- src/webui/webapplication.cpp
- src/webui/webapplication.h
The exact structure of the query string is not standardised (it's not part of HTTP). So it should be parsed at (web-)application level. Different web applications can expect different data format there.
This patch should fix Embedded Tracker.
> Parse URL query string at application level

- src/base/bittorrent/tracker.cpp
- src/base/bittorrent/tracker.h
Tracker shouldn't add peer with "port=0" to the list but it still should send non-error response to it.
> Properly reply to announce request

- src/base/utils/version.h
There are two instances of this:
```
In file included from base/search/searchpluginmanager.h:36:0,
from base/search/searchhandler.cpp:37:
./base/utils/version.h: In instantiation of ‘constexpr Utils::Version<T, N, Mandatory>::Version() [with T = short unsigned int; long unsigned int N = 2ul; long unsigned int Mandatory = 2ul]’:
/opt/qt55/include/QtCore/qmetatype.h:756:28:   required from ‘static void* QtMetaTypePrivate::QMetaTypeFunctionHelper<T, Accepted>::Construct(void*, const void*) [with T = Utils::Version<short unsigned int, 2ul>; bool Accepted = true]’
/opt/qt55/include/QtCore/qmetatype.h:1680:76:   required from ‘int qRegisterNormalizedMetaType(const QByteArray&, T*, typename QtPrivate::MetaTypeDefinedHelper<T, (QMetaTypeId2<T>::Defined && (! …
```
> Fix missing initializer warning during build

- src/base/search/searchpluginmanager.cpp
- src/base/search/searchpluginmanager.h
- src/gui/search/searchwidget.cpp
Uses the selected plugin to determine the supported search categories.
Before:
After:
> Calculate search categories based on selected plugin

- src/gui/optionsdlg.ui
Let me know if you think the layout name change doesn't deserve a whole commit.
> Move suffix-labels inside the corresponding spinboxes

- src/gui/torrentcontenttreeview.cpp
New QT implementation of QHeaderView is rewritten in 5.10.1 and behaves differently on the property StretchLastSection (true by default).
Setting that property to false while creating the new (unused) QHeaderView for "Content" window solve the issue #8439.
> Fix for "Content" panel messed up

- src/gui/optionsdlg.ui
Notice the position of "(More information)":
Before: ![before](https://user-images.githubusercontent.com/9395168/37356057-140688f4-2720-11e8-9000-00a042ee1d32.png)
After: ![after](https://user-images.githubusercontent.com/9395168/37356055-13dde99e-2720-11e8-831b-e56e7c1a92e5.png)
> Properly align text label

- src/base/rss/private/rss_parser.cpp
- src/base/rss/private/rss_parser.h
- src/base/rss/rss_feed.cpp
For some reason, the RSS feed may contain malformed XML data and it may not be successfully parsed by the XML parser. We are still trying to load as many articles as possible until we encounter corrupted data. So we can have some articles even in case of parsing error.
Closes #8527.
Closes #8569.
> Process loaded RSS articles in case of parsing error

- src/app/upgrade.h
- src/base/CMakeLists.txt
- src/base/algorithm.h
- src/base/base.pri
- src/base/bittorrent/session.cpp
- src/base/filesystemwatcher.cpp
- src/base/net/portforwarder.cpp
- src/base/search/searchpluginmanager.cpp
- src/gui/categoryfiltermodel.cpp
- src/gui/categoryfilterwidget.cpp
- src/gui/search/pluginselectdlg.cpp
- src/gui/transferlistfilterswidget.cpp
- src/webui/api/appcontroller.cpp
- src/webui/api/synccontroller.cpp
Stops temporary containers being created needlessly due to API misuse.
For example, it’s common for developers to assume QHash::values() and
QHash::keys() are free and abuse them, failing to realize their
implementation internally actually iterates the whole container, allocates
memory, and fills a new QList.
Found using clazy.
> Don't create temporary containers just to iterate over them

- src/base/filesystemwatcher.cpp
- src/base/filesystemwatcher.h
- src/base/utils/fs.cpp
- src/base/utils/fs.h
The main point of this PR:
Add delay before processing FS changes
This prevents renaming errors in monitored folder, for example: ABC.torrent.part -> ABC.torrent
> Improve FS watcher

- src/app/application.cpp
- src/app/cmdoptions.cpp
- src/app/main.cpp
- src/app/upgrade.h
- src/base/bittorrent/session.cpp
- src/gui/search/searchwidget.cpp
* Using iostream usually adds a lot of other operators (<<, endl), whereas
*printf takes only 1 function call.
* Also use qUtf8Printable whenever possible.
> Use lightweight printf instead of iostream

- qbittorrent.pro
Make uncrustify.cfg available to integrated into QT Creator IDE beautifier plugin.
> Make uncrustify.cfg available to QtCreator IDE

- src/app/application.cpp
- src/base/bittorrent/session.cpp
- src/base/utils/misc.cpp
- src/base/utils/misc.h
- winconf.pri
The dlls should be loaded from windows\system32 explicitly, otherwise it poses a security risk.
> Add helper for loading Windows system functions

- src/base/net/proxyconfigurationmanager.cpp
We need to be careful when using the multi-arg version of
QString::arg() and passing as 2nd, 3rd etc parameter an int.
It doesn't do the same as passing multiple QStrings.
> Fix wrong QString::arg() usage that leads to crash

- src/gui/properties/propertieswidget.cpp
Check whether the file is already downloaded before appending QB_EXT to filename.
Closes #8039.
> Fix renaming completed files

- src/base/bittorrent/torrentcreatorthread.cpp
- src/base/bittorrent/torrentcreatorthread.h
- src/gui/torrentcreatordlg.cpp
- src/gui/torrentcreatordlg.h
- src/gui/torrentcreatordlg.ui
Adds an optional "Preserve file order" checkbox when creating torrents (like in utorrent and others). Mainly used in private trackers.
Tested on windows, would be nice if someone could check if it works on linux / osx as intended - Chocobo1 said similar code hadn't worked in the past for some reason (full details unknown) in https://github.com/qbittorrent/qBittorrent/issues/5652.
> Add "Preserve file order" option to torrent creator. Closes #5652

- CONTRIBUTING.md
@sledgehammer999 @Chocobo1 @glassez @Piccirello 
Related issue: https://github.com/qbittorrent/qBittorrent/issues/8330
Rewrote the contributing guidelines based on the previous ones, Atom's and uBlock Origin's.
The file is now clearly split into 3 sections, corresponding to the 3 main ways one can contribute to the repo.
Right now this very much open to discussion. As you might guess, especially from reading the changes, I also want to change the GitHub issue template to better match what is asked of the users in the guidelines. I will update the PR with that soon (later this week, if possible).
Overall, the new guidelines are more strict and demanding, but give clearer directions, mainly on what data to provide when opening issues, as well as what a valid issue actually is. I believe …
> New CONTRIBUTING.md, based on the old one, Atom's and uBlock Origin's

- src/app/application.h
```
../../qBittorrent/src/app/application.h:113:10: warning: 'event' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
bool event(QEvent *);
^
../../Qt-5.10.1/lib/QtWidgets.framework/Headers/qapplication.h:204:10: note: overridden virtual function is here
bool event(QEvent *) Q_DECL_OVERRIDE;
^
1 warning generated.
```
> Add missing "override" 

- src/base/bittorrent/session.cpp
For some reason `iphlpapi.h` uses some definitions from `wincrypt.h` but doesn't include it.
> Fix compilation with MinGW

- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
- src/gui/torrentmodel.cpp
- src/gui/transferlistdelegate.cpp
- src/webui/api/serialize/serialize_torrent.cpp
- src/webui/api/synccontroller.cpp
- src/webui/api/torrentscontroller.cpp
- src/webui/www/private/scripts/dynamicTable.js
See individual commit messages for explanation.
~~**Attention**
The 1st commit was made on a false assumption. It turns out that libtorrent currently doesn't report the move progress, so I opened https://github.com/arvidn/libtorrent/issues/2923.
Please review as if the feature exists. I won't merge current PR before libtorrent adds the feature.
If the feature is denied I'll modify this PR too.~
> Move and recheck progress

- src/gui/addnewtorrentdialog.cpp
- src/gui/addnewtorrentdialog.ui
Replace in "Add new torrent" dialog confusing "Set as default save path" option
with "Remember last used save path" option that affects only selected value in
"Save path" combo box.
> Add option to remember last used save path. Closes #7323

- src/base/net/private/geoipdatabase.cpp
My original intention was removing double underscore in variable names.
> Detect endianness at compile time

- src/webui/api/appcontroller.cpp
Also rename RSS properties to follow other names.
Since old names was undocumented it shouldn't cause version change.
New names is documented now (on Wiki page).
> Properly set RSS settings via API. Closes #8925

- src/base/rss/rss_autodownloader.cpp
- src/base/rss/rss_autodownloadrule.cpp
- src/base/rss/rss_autodownloadrule.h
- src/gui/rss/automatedrssdownloader.cpp
- src/gui/rss/automatedrssdownloader.ui
Current matching code has a bug. When Episode filter matches the article it prevents Smart filter from execution.
Now the matching code correctly process all sub-filters.
> Improve code of  RSS auto-downloading rule. Closes #8933

- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrentinfo.cpp
- src/base/bittorrent/torrentinfo.h
Traditionally the torrent name is the name of its content (i.e. the file name for single-file torrents or root folder name for multi-file torrents).
qBittorrent allows you to rename torrent and its content independently. However, when a user renames the contents of a torrent when it is added, it usually expects the torrent name to follow the name of its contents.
> Rename torrent if content was initially renamed. Closes #8910

- src/base/rss/rss_article.cpp
- src/base/rss/rss_autodownloadrule.cpp
- src/base/rss/rss_feed.cpp
Some sites omit publication date in its RSS feed articles
that prevents "Ignore Subsequent Matches" to work properly.
> Use RSS feed update time as a fallback. Closes #8959

- conf.pri.windows
It is advised to update the stack trace statement since #8701, otherwise people may forget to change it, which results in no pdb file generated for Windows distribution package.
> Update conf.pri.windows from #8701

- src/app/stacktrace_win.h
- src/gui/torrentcontentmodel.cpp
The warning was:
```
gui/torrentcontentmodel.cpp:135:33: warning: missing initializer for member '_SHFILEINFOW::iIcon' [-Wmissing-field-initializers]
gui/torrentcontentmodel.cpp:135:33: warning: missing initializer for member '_SHFILEINFOW::dwAttributes' [-Wmissing-field-initializers]
gui/torrentcontentmodel.cpp:135:33: warning: missing initializer for member '_SHFILEINFOW::szDisplayName' [-Wmissing-field-initializers]
gui/torrentcontentmodel.cpp:135:33: warning: missing initializer for member '_SHFILEINFOW::szTypeName' [-Wmissing-field-initializers]
```
> Initialize variables properly

- src/webui/webapplication.h
As far I see, PR #8782 makes API changes. 
Am I correct that older clients can ignore the new parameter and continue to work?
If so, this PR is correct. Otherwise, I'll
```c++
constexpr Utils::Version<int, 3, 2> API_VERSION {2, 1, 0};
constexpr int COMPAT_API_VERSION = 19;
constexpr int COMPAT_API_VERSION_MIN = 19;
```
> Bump Web API version

- src/base/rss/rss_feed.cpp
- src/base/rss/rss_feed.h
- src/base/rss/rss_session.cpp
- src/base/rss/rss_session.h
RSS feed URLs can be too long and exceed max path limit.
Add RSS feed UIDs and use UIDs as base for file names instead of URLs.
> Don't use RSS feed URLs as base for file names. Closes #8399

- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/gui/optionsdlg.cpp
- src/gui/optionsdlg.h
The mouse wheel events for QComboBox & QSpinBox widgets in Options dialog are filtered out.
> Disable certain mouse wheel events in Options dialog

- src/gui/powermanagement/powermanagement.cpp
`IOPMAssertionCreate` is marked deprecated starting from Snow Leopard (10.6).
`IOPMAssertionCreateWithName` is available starting from Snow Leopard (10.6).
Since the minimum macOS we support is Mavericks (10.9), we should be able to do the replace.
Closes #8993.
> Replace deprecated function on macOS

- src/webui/www/private/scripts/mocha-init.js
- src/webui/www/private/setlocation.html
The feature is useful when the user needs to move their torrent to a
sub or parent folder. If more than one torrent is chosen, the path
of the first selected torrent is used. The window was made wider to
allow more convenient editing of long paths.
> Show current save path in 'Set location' window

- conf.pri.windows
- configure
- configure.ac
- src/src.pro
Now the flag will be present when building with boost version <= 1.59.
Closes #8990.
> Revise usage of BOOST_NO_CXX11_RVALUE_REFERENCES

- src/base/search/searchpluginmanager.cpp
It always bugs me that when I press auto-format in my IDE it destroys the version numbering for my search plugins.
See PEP 8 Style Guide
https://www.python.org/dev/peps/pep-0008/#inline-comments
> PEP 8 compliant version comments in search plugins

- conf.pri.windows
- winconf.pri
The performance impact should be negligible according to the documentation on msdn.
Documentation:
* https://msdn.microsoft.com/en-us/library/windows/desktop/mt637065(v=vs.85).aspx 
* https://docs.microsoft.com/en-us/cpp/build/reference/guard-enable-control-flow-guard
BTW if we want full coverage, then the libraries we use must be compiled with this flag present, but that is out of scope of this PR.
> Turn on Control Flow Guard for MSVC builds

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrentinfo.cpp
- src/base/net/dnsupdater.cpp
- src/base/net/downloadhandler.cpp
- src/base/net/downloadhandler.h
- src/base/net/downloadmanager.cpp
- src/base/net/downloadmanager.h
- src/base/net/geoipmanager.cpp
- src/base/rss/rss_feed.cpp
- src/base/search/searchpluginmanager.cpp
- src/gui/addnewtorrentdialog.cpp
- src/gui/mainwindow.cpp
- src/gui/programupdater.cpp
- src/gui/properties/trackersadditiondialog.cpp
- src/gui/properties/trackersadditiondialog.h
- src/gui/search/pluginselectdialog.cpp
- src/gui/transferlistfilterswidget.cpp
QNetworkAccessManager executes network requests in parallel.
From **QNetworkAccessManager** doc:
>Currently, for the HTTP protocol on desktop platforms, 6 requests are executed in parallel for one host/port combination.
This may lead to blocking on some sites. In particular, when a user has multiple RSS feeds from a single site, their update often fails.
This feature allows you to register specific sites (hostname and port pair) as "sequential services" and prevent parallel requests to them.
> Implement "Sequential downloading" feature. Closes #6835

- src/gui/transferlistfilterswidget.cpp
Some trackers use UDP protocol but we can't download its favicon
using UDP. Just try to download it using HTTP.
> Download favicon using appropriate protocol

- src/webui/webapplication.cpp
- src/webui/webapplication.h
The newly cached values are used for every request, so it make sense to avoid the overhead fetching from Preference class.
Also group the cached values in a struct.
> Cache more preference values in WebApplication

- src/base/bittorrent/session.cpp
This avoids "deferencing null pointer" warning from static analyzers.
> Simplify code

- src/gui/addnewtorrentdialog.cpp
- src/gui/addnewtorrentdialog.ui
The new checkboxes are: "Download in sequential order", "Download first and last pieces first".
screenshot:
history: [pic1](https://user-images.githubusercontent.com/9395168/42895320-16c0748a-8aec-11e8-8156-b54d8c9b11cd.png)
> Add options in AddNewTorrentDialog

- CODING_GUIDELINES.md
I often want to read something from the guidelines but the document is too big to just scroll and find the correct place.
Now with the TOC it is easier to navigate it.
EDIT: Also remove trailing dot from some headings
> Add a TOC in the coding guidelines

- src/webui/api/torrentscontroller.cpp
- src/webui/api/torrentscontroller.h
- src/webui/www/private/index.html
- src/webui/www/private/scripts/mocha-init.js
- src/webui/www/private/transferlist.html
This brings to the WebUI a feature added in #8199.
> Add WebUI Force Reannounce option

- src/base/preferences.cpp
People might not know that this option is active and never look at the options and so mistakenly believe that the program never closes (me included). A chunk of the reports about qBt process that never ends may be because of this.
Closes #6060
> Set "close to tray" to false as default

- qbittorrent.pro
- src/base/bittorrent/session.cpp
- src/base/iconprovider.cpp
- src/base/iconprovider.h
- src/gui/guiiconprovider.cpp
- src/gui/guiiconprovider.h
- src/src.pro
About "Avoid regenerating .qm files unnecessarily", I'm not intending to find a better solution, just reverting back to the old way.
> Put temporary files in qbt own temp folder and cleanups

- src/gui/programupdater.cpp
IMO it is natural to have native (64-bit) applications running on a (64-bit) machine, firefox also had done the 32-bit to 64-bit migration: https://www.ghacks.net/2017/07/22/firefox-56-automatic-32-bit-to-64-bit-upgrade/
> Make ProgramUpdater upgrade to 64-bit qbt when running on 64-bit Windows

- src/base/bittorrent/session.cpp
Paused torrent should not have any resume data changes.
Since resume data is already saved for such torrent (or at least is currently saving) we can to save no resume data anymore until it is resumed back.
This should prevent unnecessary load on the disk, as well as significantly reduce the application shutdown time for those users who have a lot of torrents, most of which are paused (do not forget that the final saving causes a forced update of the torrent state, which is quite expensive).
> Never save resume data for already paused torrents

- src/base/bittorrent/session.cpp
Issue report: https://github.com/qbittorrent/qBittorrent/commit/9612a75faa32ef852cc5485db7b788ec73138500#commitcomment-30026061
> Fix I/O error after fetching magnet metadata

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/preferences.cpp
- src/base/preferences.h
- src/gui/mainwindow.cpp
- src/gui/mainwindow.h
- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.h
- src/gui/optionsdialog.ui
"Active torrents" is a somewhat unintuitive concept to base preventing sleep on, as torrents can become active or inactive on the network at any time. This brings some predictability to the inhibit sleep option, and will inhibit sleep as long as there are unpaused downloads or uploads, regardless of network activity.
> Inhibit sleep for running downloads or uploads regardless of network activity

- unixconf.pri
In commit 5d94db9c7940aee9af769ce314c1dd1be9ddc18c the desktop file was moved from src/ to dist/ but the relative path from src/src.pro was switched to an absolute path from the repository root. This broke detection of the file from within qmake.
Fix by using the same $DIST_PATH used elsewhere for consistency, which uses ../dist/.
> Fix regression that broke installing desktop file

- src/qbittorrent_mingw.rc
Warning introduced by commit 6203f23f06b
The warnings of mingw (gcc 8.1.0) were:
```
qbittorrent_mingw.rc:1: unrecognized escape sequence
qbittorrent_mingw.rc:2: unrecognized escape sequence
```
> Fix mingw warning about unrecognized escape sequence

- src/base/preferences.cpp
QVariant doesn't have constructor for plain char, by default it converts a plain char into an integer, hence the WebUI issue.
Closes #9333.
> Fix WebUI unreachable issue

- src/gui/transferlistwidget.cpp
The fact that you can now set these options from the new torrent dialog got me thinking if this is possible and it turns out that it is, tested.
P.S. I know the commit msg is longer than 50 chars but i can't shrink it even more.
> Allow setting seq & first/last from context menu without metadata

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
We forgot about queue priorities when saving fastresume, especially for paused torrents.
Closes #9368
> Save fastresumes when changing torrent priorities

- INSTALL
- src/base/search/searchpluginmanager.cpp
- src/gui/cookiesdialog.ui
- src/gui/deletionconfirmationdialog.ui
- src/gui/optionsdialog.ui
* Avoid copy-construct QString in for loop
* Reset button text to default 
This is to avoid Qt auto-generating code like this:
`buttonAdd->setText(QStringLiteral(""));`
Which makes no sense and triggers clazy warning (Wclazy-empty-qstringliteral).
* Update INSTALL file
> Minor fixes

- src/gui/optionsdialog.cpp
- src/webui/www/private/preferences_content.html
This behavior was changed in libtorrent in https://github.com/arvidn/libtorrent/pull/3251.
Closes #9292
> Don't disable DHT when using force proxy

- src/app/main.cpp
It seems `QT_AUTO_SCREEN_SCALE_FACTOR` doesn't work as expected.
Closes #6935.
> Fix GUI scaling issue on Linux

- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrenthandle.cpp
This is the 1st commit from PR #9007. That PR is a bit huge and I locally get random crashes, so I am not pushing it.
This PR is a stopgap measure, until a full solution is found. It would be great if this gets approved to be included in the upcoming 4.1.3 (I plan till the weekend to make a release)
Commit message follows:
During startup we can get above 1000 alerts at each pop even with only
30 torrents in the queue. This is because libtorrent will post
piece_finished_alert and file_completed_alert for each torrent. These
alerts push out of the way the ones we care about.
The alert queue will be grown to max only if needed. So we don't use
more memory. It will greatly depend on how many torrents a user has in
their session.
When getting fastresume_rejected_alert we need to act as fast as …
> Decrease probability of missing important alerts

- src/gui/mainwindow.cpp
I made the mistake in fd5d1583de810f6fec780552b29f4e244d943b27
@zeule reminded me yesterday(?)
Better key names are welcome. This PR makes it `GUI/DownloadTrackerFavicon`
I opted to not have upgrade code for this option from its previous key.
> Save option about tracker favicons under correct key

- src/base/bittorrent/torrentinfo.cpp
- src/base/bittorrent/torrentinfo.h
- src/base/net/downloadmanager.cpp
- src/base/net/private/geoipdatabase.cpp
- src/gui/addnewtorrentdialog.cpp
- src/gui/categoryfiltermodel.cpp
- src/gui/cookiesmodel.cpp
- src/gui/guiiconprovider.h
- src/gui/mainwindow.cpp
- src/gui/properties/peerlistdelegate.h
- src/gui/properties/peerlistwidget.cpp
- src/gui/properties/peerlistwidget.h
- src/gui/properties/trackerlistwidget.cpp
- src/gui/scanfoldersdelegate.cpp
- src/gui/search/pluginselectdialog.cpp
- src/gui/search/searchjobwidget.cpp
- src/gui/tagfiltermodel.cpp
- src/gui/tagfiltermodel.h
- src/gui/torrentcontentfiltermodel.h
- src/gui/torrentcontentmodel.cpp
- src/gui/torrentcontentmodel.h
- src/gui/torrentcontentmodelfolder.cpp
- src/gui/torrentcontentmodelfolder.h
- src/gui/torrentcreatordialog.h
- src/gui/transferlistdelegate.cpp
- src/gui/transferlistfilterswidget.h
- src/gui/transferlistmodel.cpp
- src/gui/transferlistwidget.cpp
- src/gui/transferlistwidget.h
>scrape_incomplete scrape_complete scrape_downloaded
if this tracker has returned scrape data, these fields are filled in with valid numbers. Otherwise they are set to -1.
Closes #9460.
>  Show "N/A" if there is no scrape response

- src/base/bittorrent/torrenthandle.cpp
- src/webui/api/synccontroller.cpp
- src/webui/api/torrentscontroller.cpp
- src/webui/api/torrentscontroller.h
- src/webui/extra_translations.h
- src/webui/www/private/filters.html
- src/webui/www/private/index.html
- src/webui/www/private/newcategory.html
- src/webui/www/private/scripts/client.js
- src/webui/www/private/scripts/contextmenu.js
- src/webui/www/private/scripts/misc.js
- src/webui/www/private/scripts/mocha-init.js
Before:
After:
GUI for comparison:
Closes #9223, closes #5716.
> Add save path and category editing to WebUI

- CMakeLists.txt
This reverts commit 239352ad88a6533bbeb317b2f8ce57f34fdcb637.
> Revert "Print warning about cmake support status"

- src/base/bittorrent/session.cpp
Closes #9547 
It helps with not dealing with a ton of unwanted `piece_finished_alert`.
> Use a more detailed alert mask where possible

- src/gui/lineedit/src/lineedit.cpp
- src/gui/lineedit/src/lineedit.h
This PR clears LineEdit on ESC keypress, LineEdit is used on three places, as Filter box for torrents, on Content tab for filtering files in a torrent and in search engine.
> Clear LineEdit on ESC

- src/gui/properties/speedplotview.cpp
- src/gui/properties/speedplotview.h
~~Re-wright~~ Rewrite averaging code and reduce horizontal graphs resolution for 30 minutes and 6 hours graphs to decrease CPU usage. On 6 hours graph achieved near 5-6 times decrease of processor ticks utilization.
> Rewrite averaging code and reduce horizontal graphs resolution

- src/base/filesystemwatcher.cpp
- src/base/filesystemwatcher.h
- src/base/utils/fs.cpp
- src/base/utils/fs.h
This allows network mounts to be monitored correctly by polling timer.
> Add isNetworkFileSystem() detection on Windows

- src/webui/www/private/scripts/contextmenu.js
When multiple torrents are selected with different Auto TMM values, the Auto TMM context menu option is hidden. This option is never unhidden, requiring a refresh of the page.
> Fix WebUI Auto TMM context menu bug

- .travis.yml
Instead of hard coding a macOS version to use, now we follow TravisCI default version, currently: xcode9.4.
> Fix TravisCI cmake build on macOS

- src/app/application.cpp
- src/base/search/searchpluginmanager.cpp
- src/gui/search/searchwidget.cpp
- src/webui/CMakeLists.txt
- src/webui/api/searchcontroller.cpp
- src/webui/api/searchcontroller.h
- src/webui/webapplication.cpp
- src/webui/webui.pri
> WebUI search API. Closes #2495

- src/webui/CMakeLists.txt
- src/webui/api/freediskspacechecker.cpp
- src/webui/api/freediskspacechecker.h
- src/webui/api/synccontroller.cpp
- src/webui/api/synccontroller.h
- src/webui/webui.pri
- src/webui/www/private/index.html
- src/webui/www/private/scripts/client.js
- src/webui/www/private/scripts/misc.js
> Puts free space on disk (Default save path) in WebUI's status 
This is a continuation of #6829 and addresses the need to poll for free disk space on a separate thread. Comments/suggestions on the QThread implementation are welcome.
Closes #9680
> Free disk space in WebUI status bar

- src/base/preferences.cpp
When WebApplication configures, it compare m_currentLocale  with application locale and (re-)load an appropriate translator if locale was changed. m_currentLocale is set to "" initially so it should be different from all locale and translator should be loaded at the first time. `Preferences::getLocale()` returns system locale if locale setting isn't set. But it doesn't handle the (invalid) case when locale is set to empty string.
This patch make "empty" locale considered as not set (so system locale is returned instead).
> Consider empty locale  setting as not set. Closes #9735

- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
Add/restore all torrents in "paused" state and then resume those that need to be really "resumed" (added/restored in "resumed" state).
Keep torrents with missing files paused.
Force recheck torrent with missing files when it's resumed by the user.
> Improve handling of torrent startup/recheck

- src/base/bittorrent/session.cpp
We don't know whether the download will be successful, so default to success. Closes #9811.
> Handle downloading .torrent file as success

- src/CMakeLists.txt
Libtorrent does the same and we have to follow since
its ABI depends on the C++ standard version.
Partially closes #9485.
> cmake: use C++14 when available

- src/gui/mainwindow.cpp
`m_searchFilterAction` is owned by Qt, so we shouldn't delete it manually.
Closes #9819.
> Don't double delete a pointer

- src/gui/search/searchjobwidget.cpp
Because it causes qBt's width to exceed the screen's width for laptop users. See #9826.
> Allow qBt to resize the search filter in search job

- src/gui/properties/propertieswidget.cpp
- src/webui/api/torrentscontroller.cpp
Previously here was using a cheap method to avoid divisor becoming < 0, but from the crash stacktrace it seems this is not enough, now the value is properly clamped to have 1 as the minimum.
Closes #9857.
> Clamp values properly

- .travis.yml
- configure
- configure.ac
- src/src.pro
Closely related to PR #9509.
Newer compilers have C+14 mode as default and package maintainers tends to not specifying a C++ version when building a package, this causes compatibility issues when (for example) qbt is compiled in C++11 and dependency lib is in C++14.
This commit will detect the default C++ mode and try append "-std=c++11" flag only
when the compiler doesn't support C++ >= 11 mode by default.
> Implement proper C++11 mode detection

- src/webui/www/private/css/dynamicTable.css
- src/webui/www/private/scripts/dynamicTable.js
This PR adds the up/down arrow to a column header when sorting by that column. This matches the existing GUI behavior.
WebUI:
GUI:
> Show icon in WebUI sorted column

- src/webui/webapplication.cpp
This attribute prevents the cookie from being submitted on any cross-site request, strongly limiting CSRF.
Closes #9877.
> Add SameSite attribute to WebUI session cookie

- src/webui/www/private/download.html
- src/webui/www/private/upload.html
Disabled form values aren't submitted, causing the add_paused value not to be sent when Start Torrent is checked. qBittorrent then falls back to the global Start Torrent preference.
Closes #9855.
> Fix WebUI bug on override of Start Torrent option

- src/webui/www/private/css/style.css
- src/webui/www/private/scripts/client.js
Also allows the WebUI sidebar to be collapsed (dragged to a width of 1).
Before:
After:
> Show ellipsis when WebUI sidebar is too narrow

- src/base/bittorrent/private/resumedatasavingmanager.cpp
- src/base/bittorrent/private/resumedatasavingmanager.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/rss/rss_feed.cpp
See #9556 for explanation.
1. It saves/restores queue when "queuing" is enabled (unlike existing code). Is it acceptable change?
2. <del>When user disables "queuing" it just stops saving queue file. Should it remove/clear queue file?</del>
> Save torrents queue in separate file

- configure
- configure.ac
- m4/qbittorrent.m4
This is a rethinking of how to handle C++ modes. What it does with this PR:
1. If the **enabled** C++ mode is >= C++11, either by compiler default or because another package's compiler flags enabled it, we continue as-is without explicitly modifying compiler flags concerning the C++ mode.
2. If the **enabled** C++ mode is < C++11, then we modify the compiler flags to see if C++11 is supported. If yes, we force it, print a warning message to the user and continue. If not, then we error out.
Minor other fixes:
1. Removed various AC_LANG_PUSH() macros because at the begining AC_LANG(C++) is already set.
2. Refactored a bit so our compiler flag modifications come after the user's preset one in case of number `2` above. Example case: User runs `CPPFLAGS="-std=c++98" ./configure` with a …
> Autotools: Better C++ mode detection and handling

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
Adds a spinbox in advanced options to change the libtorrent setting
`checking_mem_usage`.
Potential usefulness: refer to discussion at https://github.com/qbittorrent/qBittorrent/issues/9061
>  Add checking_mem_usage option to AdvancedSettings

- .travis.yml
- CMakeLists.txt
- configure
- configure.ac
- src/CMakeLists.txt
- src/app/application.cpp
- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/preferences.cpp
- src/base/preferences.h
- src/base/utils/password.cpp
- src/base/utils/password.h
- src/base/utils/string.cpp
- src/gui/mainwindow.cpp
- src/gui/mainwindow.h
- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.ui
- src/webui/api/appcontroller.cpp
- src/webui/api/authcontroller.cpp
- src/webui/www/private/preferences_content.html
Some notes:
* openssl >= 1.0 is now a required dependency.
* This PR makes stored password hash very much harder to crack compared to previously used method.
This basically means even if bad actor acquired your password hash, he won't be able to easily compute your real password (assuming the real password is good enough for brute force attack).
* UI changes: [GUI](https://user-images.githubusercontent.com/9395168/49236436-135c6100-f437-11e8-913e-f5c8f9ab384c.png), [WebUI](https://user-images.githubusercontent.com/9395168/49236438-135c6100-f437-11e8-967f-95b72df29e59.png)
* PBKDF2 is chosen because qbt already uses openssl which saves us from adding another library, and also it is the only method openssl implemented AFAIK.
* PBKDF2 parameters are chosen to be in line with 1password …
> Do password hashing properly

- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.h
- src/gui/optionsdialog.ui
- src/webui/api/appcontroller.cpp
- src/webui/api/torrentscontroller.cpp
- src/webui/www/private/css/style.css
- src/webui/www/private/download.html
- src/webui/www/private/preferences_content.html
- src/webui/www/private/scripts/download.js
- src/webui/www/private/shareratio.html
- src/webui/www/private/upload.html
This adds all the remaining GUI preferences to the WebUI- including a complete Auto TMM implementation- with a few exceptions.
**Added:**
* Downloads tab
* "When adding a torrent" section
* Default Torrent Management Mode
* "When ... changed" options
* Email "From" field
* Connection tab
* Random port generator
* "Password saved unencrypted" info notice
* Speed tab
* Apply rate limit to peers on LAN
* Global/Alternate limit icons
* BitTorrent tab
* Slow torrent thresholds
* Web UI tab
* Use alternative Web UI
**Not added:**
* Behavior tab (doesn't apply to the WebUI, except maybe the Log file options)
* Downloads tab
* Torrent download dialog options
* "Use Subcategories" option (on my to-do list, but not high up)
* "Also when addition is cancelled" option- doesn't seem to apply to the …
> Add missing Preferences to WebUI

- src/webui/www/private/properties_content.html
Fixes a JavaScript error caused by the element lookup returning null
> Fix JavaScript error

- src/webui/www/private/css/style.css
- src/webui/www/private/download.html
- src/webui/www/private/index.html
- src/webui/www/private/installsearchplugin.html
- src/webui/www/private/scripts/client.js
- src/webui/www/private/scripts/contextmenu.js
- src/webui/www/private/scripts/dynamicTable.js
- src/webui/www/private/scripts/mocha-init.js
- src/webui/www/private/search.html
- src/webui/www/private/searchplugins.html
- src/webui/www/webui.qrc
This PR is a WebUI implementation of the search API from #8584.
It currently supports a single search job, but supporting multiple concurrent searches here and in the GUI is on my eventual todo list. My current ugly hack for concurrent searches is to open a new browser tab for each search.
Closes #859, closes #8107, closes #9154
> Add Search feature to WebUI

- src/webui/www/private/scripts/dynamicTable.js
Before:
After:
GUI:
("Before" and "GUI" images stolen from @thalieht)
> Match WebUI Peers table column order to GUI

- src/base/CMakeLists.txt
- src/base/base.pri
- src/base/bittorrent/filepriority.cpp
- src/base/bittorrent/filepriority.h
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
- src/gui/addnewtorrentdialog.cpp
- src/gui/ipsubnetwhitelistoptionsdialog.cpp
- src/gui/ipsubnetwhitelistoptionsdialog.h
- src/gui/properties/propertieswidget.cpp
- src/gui/properties/proplistdelegate.cpp
- src/gui/torrentcontentmodel.cpp
- src/gui/torrentcontentmodelfile.cpp
- src/gui/torrentcontentmodelfolder.cpp
- src/gui/torrentcontentmodelfolder.h
- src/gui/torrentcontentmodelitem.cpp
- src/gui/torrentcontentmodelitem.h
- src/webui/api/torrentscontroller.cpp
- src/webui/www/private/properties_content.html
- src/webui/www/private/scripts/prop-files.js
This API was never changed during the API revamp some months back
Closes #6259
>  Set priority for multiple files in one WebAPI request

- src/base/bittorrent/trackerentry.h
- src/gui/properties/trackerlistwidget.cpp
- src/gui/properties/trackerlistwidget.h
- src/webui/api/torrentscontroller.cpp
- src/webui/api/torrentscontroller.h
- src/webui/webapplication.h
- src/webui/www/private/css/style.css
- src/webui/www/private/edittracker.html
- src/webui/www/private/index.html
- src/webui/www/private/properties_content.html
- src/webui/www/private/scripts/prop-trackers.js
- src/webui/www/webui.qrc
Note: This does not break anything in the existing `/torrents/trackers` API; it only adds additional info
Before:
After:
GUI, for comparison:
**Context menu:**
webui: 
gui: 
**Category editing**
webui:
gui:
Closes #7934, closes #6797, closes #3024
> Add additional tracker info to WebUI

- .travis.yml
Also limit ccache cache size to 512 MB. Previously the size was 5 GB for macOS and it took 1~3
mins just for uploading the cache, limiting the size should shorten total build time.
> Upgrade TravisCI to xenial

- src/webui/webapplication.cpp
- src/webui/webapplication.h
- src/webui/www/translations/webui_en.ts
Since it is possible alternative WebUI could be coded in languages other than English, WebUI must be able to load user-provided webui_en.qm.
> Unify translation files loading action

- src/webui/www/private/addtrackers.html
- src/webui/www/private/confirmdeletion.html
- src/webui/www/private/download.html
- src/webui/www/private/downloadlimit.html
- src/webui/www/private/filters.html
- src/webui/www/private/installsearchplugin.html
- src/webui/www/private/newcategory.html
- src/webui/www/private/preferences.html
- src/webui/www/private/preferences_content.html
- src/webui/www/private/properties_content.html
- src/webui/www/private/rename.html
- src/webui/www/private/scripts/client.js
- src/webui/www/private/scripts/contextmenu.js
- src/webui/www/private/scripts/download.js
- src/webui/www/private/scripts/dynamicTable.js
- src/webui/www/private/scripts/misc.js
- src/webui/www/private/scripts/mocha-init.js
- src/webui/www/private/scripts/progressbar.js
- src/webui/www/private/scripts/prop-files.js
- src/webui/www/private/scripts/prop-general.js
- src/webui/www/private/scripts/prop-trackers.js
- src/webui/www/private/scripts/prop-webseeds.js
- src/webui/www/private/search.html
- src/webui/www/private/searchplugins.html
- src/webui/www/private/setlocation.html
- src/webui/www/private/shareratio.html
- src/webui/www/private/transferlist.html
- src/webui/www/private/upload.html
- src/webui/www/private/uploadlimit.html
- src/webui/www/public/login.html
@Piccirello 
I plan to merge this after these PRs: #9758, #9752, #9541, #9375, you probably don't want to hold on them any longer.
> Use Javascript strict mode

- src/app/cmdoptions.cpp
- src/app/cmdoptions.h
- src/base/bittorrent/infohash.cpp
- src/base/bittorrent/infohash.h
- src/base/bittorrent/private/statistics.h
- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrenthandle.h
- src/base/bittorrent/trackerentry.cpp
- src/base/bittorrent/trackerentry.h
- src/base/net/private/geoipdatabase.h
- src/base/private/profile_p.h
- src/base/rss/rss_feed.cpp
- src/base/settingsstorage.cpp
- src/base/torrentfileguard.h
- src/gui/properties/proplistdelegate.h
- src/gui/properties/speedwidget.h
- src/gui/properties/trackerlistwidget.h
- src/gui/properties/trackersadditiondialog.cpp
- src/gui/torrentcontentmodelfolder.h
- src/gui/torrentcontentmodelitem.h
Marking it as explicit makes the object construction step more... explicit, do we really want this? I'm open to ideas.
> Mark constructors as explicit

- src/base/bittorrent/magneturi.cpp
- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/net/downloadmanager.cpp
- src/base/net/downloadmanager.h
- src/base/search/searchpluginmanager.cpp
- src/base/utils/misc.cpp
- src/base/utils/misc.h
- src/gui/addnewtorrentdialog.cpp
- src/gui/addnewtorrentdialog.h
- src/gui/mainwindow.cpp
- src/gui/rss/rsswidget.cpp
- src/gui/search/pluginselectdialog.cpp
* The format is marked obsolete on 2009.12.28 and has been replaced by magnet links.
http://wiki.bitcomet.com/inside_bitcomet#bc_link_format_obsoleted_as_of_v117
https://www.bitcomet.com/en/changelog
* Cleanup code
> Drop support for "BC Link" format

- src/gui/previewlistdelegate.h
- src/gui/properties/proplistdelegate.cpp
- src/gui/transferlistdelegate.cpp
Qt has a bug QTBUG-72558, which leads to incorrect progress bar
position, when drawing it in delegate.
Also, since OS X 10.10 Yosemite macOS default style was changed,
and progress bars became very tiny and without text (percentage).
These two cases make qBittorrent look pretty awful, but drawing
progress bar in Fusion style solves both issues.
fixes the issue with progress bar discussed in #9096 , see https://github.com/qbittorrent/qBittorrent/issues/9096#issuecomment-445469128 , https://github.com/qbittorrent/qBittorrent/issues/9096#issuecomment-447240247 , https://github.com/qbittorrent/qBittorrent/issues/9096#issuecomment-449083322 , https://github.com/qbittorrent/qBittorrent/issues/9096#issuecomment-449127155 for screenshots.
> Draw progress bar in Fusion style on macOS systems

- dist/mac/Info.plist
Added few required/recommended and removed obsolete/deprecated keys according to [Apple developers documentation](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html).
- [more info about CF* keys](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-SW1)
- [more info about **NSAppTransportSecurity** key](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW33)
I'm not an experienced macOS developer, I'm just enthusiast, which mostly writes software in Qt. so I changed Info.plist based on …
> Cleanup Info.plist

- src/gui/advancedsettings.cpp
The maximum value is currently [99MiB](http://doc.qt.io/qt-5/qspinbox.html#maximum-prop). Allowing setting it larger helps to easier do benchmark. For 32-bit builds, a slight increase from 99MiB to 128MiB should not contribute to any problem.
> Allow setting larger checking memory usage in GUI

- src/gui/transferlistfilterswidget.cpp
It is a bad idea for user privacy to automatically contact a 3rd party
about tracker domains. Especially when the user isn't informed about
this and the 3rd party is Google.
Reverts 1b9882b3a31fa51b43554935e36fc6708c260857
> Don't query Google for tracker favicons

- src/base/bittorrent/tracker.cpp
- src/base/http/requestparser.cpp
- src/webui/webapplication.cpp
Allow special characters in query string parameters.
NOTE: this PR should be backported to 4.1 branch.
> Separate URL components before percent-decoding. Closes #9116

- src/base/bittorrent/tracker.cpp
- src/base/http/requestparser.cpp
- src/webui/webapplication.cpp
Allow special characters in query string parameters.
> Separate URL components before percent-decoding

- src/webui/api/appcontroller.cpp
- src/webui/api/appcontroller.h
- src/webui/www/private/about.html
- src/webui/www/private/aboutToolbar.html
- src/webui/www/private/properties_content.html
- src/webui/www/private/scripts/client.js
- src/webui/www/private/scripts/mocha-init.js
- src/webui/www/webui.qrc
> Match WebUI About page to GUI

- src/gui/mainwindow.cpp
- src/gui/properties/propertieswidget.cpp
- src/gui/properties/propertieswidget.h
Drop redundant dependencies.
Refresh after BitTorrent session refreshing  (instead of using timer).
> Improve Properties widget

- src/app/CMakeLists.txt
- src/app/app.pri
- src/app/main.cpp
- src/app/upgrade.cpp
- src/app/upgrade.h
- src/base/http/server.cpp
- src/base/http/server.h
- src/base/preferences.cpp
- src/base/preferences.h
- src/base/utils/net.cpp
- src/base/utils/net.h
- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.h
- src/gui/optionsdialog.ui
- src/webui/api/appcontroller.cpp
- src/webui/webui.cpp
- src/webui/www/private/preferences_content.html
* Load WebUI certificate & key from file path
This allow users to update certificate & key more easily, i.e. without the need to import them into qbt.
Closes #6675, #7547, #8315, #8564.
* Cleanup header inclusion
This will break WebUI users who have https setup, I think it is best suited for qbt v4.2.0 which comes with other WebUI break/changes.
Screenshots:
* ![GUI](https://user-images.githubusercontent.com/9395168/51296404-1519cc80-1a57-11e9-81f6-a153daf76b34.png)
* ![WebUI](https://user-images.githubusercontent.com/9395168/51296405-15b26300-1a57-11e9-8b4c-8bcbb7c5d90a.png)
> Load WebUI certificate & key from file path

- src/app/application.cpp
https://github.com/flathub/org.qbittorrent.qBittorrent/issues/18
Otherwise, only a generic icon is shown.
This must match the naming scheme of `dist/unix/org.qbittorrent.qBittorrent.desktop`.
Also `QGuiApplication::setDesktopFileName("org.qbittorrent.qBittorrent");` needs to be added somewhere.
> Linux/Wayland: make window title bar icon work

- src/gui/search/searchjobwidget.cpp
- src/gui/search/searchwidget.cpp
qbittorrent closes itself without any error message when a search tab
should be notified of a status change: fixed bad pointer variable catch
in lambda code.
Added also default tooltip "Searching..." on tab creation.
> Avoid crashes on torrent search

- src/app/application.cpp
- src/app/cmdoptions.cpp
- src/app/main.cpp
- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
- src/base/bittorrent/torrentinfo.cpp
- src/base/bittorrent/torrentinfo.h
- src/base/utils/misc.cpp
- src/base/utils/misc.h
- src/gui/addnewtorrentdialog.cpp
- src/gui/macutilities.h
- src/gui/macutilities.mm
- src/gui/mainwindow.cpp
- src/gui/properties/propertieswidget.cpp
- src/gui/search/searchjobwidget.cpp
- src/gui/search/searchjobwidget.h
- src/gui/shutdownconfirmdialog.cpp
- src/gui/transferlistmodel.cpp
- src/gui/transferlistsortmodel.cpp
- src/gui/transferlistwidget.cpp
- src/gui/utils.cpp
- src/gui/utils.h
- src/webui/api/serialize/serialize_torrent.cpp
* Move helper functions to Utils::Gui namespace
Those are moved:
```c++
void Utils::Misc::openPath(const QString &absolutePath);
void Utils::Misc::openFolderSelect(const QString &absolutePath);
QPoint Utils::Misc::screenCenter(const QWidget *w);
```
* Replace deprecated `qt_mac_set_dock_menu()`
> Move helper functions to Utils::Gui namespace

- .travis.yml
- CMakeLists.txt
- INSTALL
- configure
- m4/qbittorrent.m4
- src/app/application.cpp
- src/base/bittorrent/session.cpp
- src/base/net/reverseresolution.cpp
- src/base/search/searchhandler.cpp
- src/gui/utils.cpp
- src/webui/webapplication.cpp
Why Qt 5.9?
It is an LTS version. I would choose the latest one (aka 5.12) but it is too new and mainstream user distros don't support it yet. We could move to it after the next LTS version of Ubuntu comes out that supports it (and probably a few months go by).
> Raise minimum Qt version to 5.9.0

- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
1. Add context to connect().
2. Use QLabel in the left table cell, this allows using rich text formatting, such as HTML links.
This is idea comes from https://github.com/qbittorrent/qBittorrent/pull/10003#issuecomment-447592606
@thalieht you can then have html links in the label, see labelQbtLink.setText for format example.
And perhaps it is better to have the html link in a separate text for easy reading, as such: "label_text <a href="https://www.google.com">(link)</a>" or "label_text <a href="https://www.google.com">(?)</a>"
> Improve AdvancedSettings::addRow()

- src/app/cmdoptions.cpp
- src/app/cmdoptions.h
- src/app/main.cpp
This allows building headless qBittorrent on Windows.
Daemonizing is disabled, AFAIK a direct equivalent doesn't exist in win32. An option to install as a service (similar to NZBGet) would be worth looking into in the future.
Tested with cmake & mingw64.
> Fix building qbittorrent-nox on Windows

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/gui/advancedsettings.cpp
- src/gui/advancedsettings.h
- src/gui/properties/trackerlistwidget.cpp
- src/webui/www/private/scripts/dynamicTable.js
About the central alignment see #10003 for pics.
/Offtopic
I repeat it here from #10003: the "Maximum number of half-open connections" doesn't seem to be interacting with libtorrent anywhere. Neither `Session::maxHalfOpenConnections()` nor `m_maxHalfOpenConnections`.
Libtorrent documentation says `settings_pack::half_open_limit` is deprecated (which qbt used for half open connections about 2 years ago 13b04f8d2db237a667be918f97e201410cea0f14).
Should i remove the option or there is a replacement?
> Add documentation links to some advanced settings 

- src/app/application.cpp
- src/app/filelogger.cpp
- src/app/filelogger.h
- src/base/logger.cpp
- src/base/logger.h
- src/gui/executionlogwidget.cpp
- src/gui/executionlogwidget.ui
- src/gui/loglistwidget.cpp
- src/gui/loglistwidget.h
* Avoid performance penalty when logger is full
I consider paying the cost of a copy when fetching log is more reasonable than the QVector shifting penalty at log full.
Another possible candidate would be `QList` however its memory is not contiguous.
* Use unique_ptr instead of raw pointer
* Utilize parent pointer appropriately
And this PR don't solve #10309, this is merely some cleanup work I did when investigating it.
> Avoid performance penalty when logger is full

- src/webui/www/private/download.html
- src/webui/www/private/preferences_content.html
- src/webui/www/private/setlocation.html
- src/webui/www/private/upload.html
Closes an issue in #9796 the autocorrect and autocapitalise should be removed from filepath inputs, this is a larger issue for mobile devices using the WebUI.
This is the same commit as what should be in #9841 however when trying to rebase I closed that commit.
> Remove autocorrect/autocapitalise in WebUI

- src/gui/optionsdialog.ui
- src/webui/www/private/preferences_content.html
Because it actually prefers non-encryption but allows it if requested.
Closes #10352
> Rename "Prefer encryption" to "Allow encryption"

- src/webui/api/synccontroller.cpp
- src/webui/api/synccontroller.h
See Qt commit:
https://code.qt.io/cgit/qt/qtbase.git/commit/src/corelib/kernel/qtimer.cpp?id=a623fe8d2a60ff333d5779f877e3b20f0e141ff1
Fixes #9985.
Will backport to 4.1.x branch once this is approved.
> Work around the crash occurred in QTimer

- src/base/bittorrent/session.cpp
- src/base/bittorrent/torrentinfo.cpp
- src/base/global.h
- src/gui/addnewtorrentdialog.cpp
As suggested in https://github.com/qbittorrent/qBittorrent/issues/9319#issuecomment-412750091 to allow downloading bigger .torrents.
Closes #8331
> Increase the download request size limit from 10 to 100 MiB 

- src/base/http/server.cpp
- src/base/http/server.h
Previously it relied on a timer to drop dead connections but that proved to be too slow when there is an incoming burst of connections.
Fixes #10487.
> Remove closed connections immediately

- .travis.yml
The `homebrew: update: true` directive updates the whole macOS env which is unnecessary and increases build time excessively. This commit reverts back to the old way.
Also the pre-installed cmake & pkg-config version is sufficient so no need to outdate them.
> Reduce macOS CI build time

- src/gui/properties/speedplotview.cpp
- src/gui/properties/speedplotview.h
- src/gui/properties/speedwidget.cpp
Also change number of time axe divisions from 5 to 6 for convenience.
> Add 12 hour and 24 hour speed graphs. Closes #9686

- src/base/bittorrent/session.cpp
- src/base/bittorrent/session.h
- src/base/settingvalue.h
- src/gui/torrentcategorydialog.cpp
- src/gui/torrentcontentmodel.cpp
- src/webui/webapplication.cpp
- src/webui/webapplication.h
* Avoid performance penalty from type erasure
On average the *`class`* initialization is 0.1% faster and the result binary is 10 KB smaller.
* Replace QMap with QHash when sensible
* Remove unused headers
> Minor cleanups

- src/gui/mainwindow.cpp
- src/gui/transferlistfilterswidget.cpp
- src/gui/transferlistfilterswidget.h
The workaround comes from:
https://github.com/qbittorrent/qBittorrent/issues/9667#issuecomment-464445025
Closes #9667.
Will backport to 4.1.x branch once approved.
This would be another blocker before 4.1.x release.
> Work around crashing in Qt networking library

- src/base/bittorrent/torrenthandle.cpp
- src/base/bittorrent/torrenthandle.h
- src/base/bittorrent/torrentinfo.cpp
- src/base/net/private/geoipdatabase.cpp
* Migrate to update-to-date libtorrent functions
This PR only targets torrenthandle.cpp
* Fix displaying invalid creation date
The bug is only observed when using libtorrent 1.2.
* Replace obsoleted QDateTime::fromTime_t()
> Migrate to update-to-date libtorrent functions

- src/webui/www/private/scripts/client.js
Background
----------------
As far as I know, currently adding magnet links for download in the WebUI means copying and pasting the magnet link manually. This PR adds some code to register the WebUI as a handler for magnet links. I just looked and apparently an issue was opened for this at #945, but was never implemented. This seemed easy enough to do so I did it and am currently using it via the alternative WebUI feature.
Changes
------------
- Modified `client.js` to call `navigator.registerProtocolHandler`, allowing the WebUI to be registered as a handler for magnet links. As I have coded it, magnet links will open the WebUI and encode the magnet link into a query parameter named "magnet".
- Also added some logic to check for the "magnet" query parameter, and if present open the …
> Register protocol handler in WebUI for magnet links

- src/base/bittorrent/tracker.cpp
- src/base/bittorrent/tracker.h
- src/base/http/requestparser.cpp
- src/base/http/types.h
- src/webui/webapplication.cpp
* Fix '+' char not decoded to space correctly
Closes #10606.
* Refactor HTTP query parsing
The parsing of HTTP query is well defined and it is the same in both places, thus it can be refactored into one.
> Fix '+' char not decoded to space correctly

- src/base/rss/private/rss_parser.cpp
Since the RSS DTD defines `type` as IMPLIED, there's no guarantee that a valid RSS feed will have it. qBittorrent fails to download torrents from feeds that decide not to add "application/x-bittorrent".
> Download RSS "enclosure" element if no proper MIME type is found

- src/webui/www/private/download.html
- src/webui/www/private/upload.html
Closes #10017.
Reasons:
1. Nowadays the Internet speed is usually in KiB/s or MiB/s, so it would be more reasonable to use KiB/s as the basic speed unit.
2. The speed limit dialogs use the speed unit KiB/s. For consistency, using KiB/s in the adding torrent dialogs will be better.
PR #10617 touches the WebAPI, and it is closed. In this version the conversion finishes in the front end, the speed limit that will be transferred to the back end is still in `Bytes/s`.
Screenshots:
**Before:**
**After:**
> Replace Bytes/s with KiB/s in the adding torrent dialogs in WebUI

- src/base/unicodestrings.h
- src/gui/addnewtorrentdialog.cpp
- src/gui/addnewtorrentdialog.h
- src/gui/addnewtorrentdialog.ui
This is adopted from PR #9591, I reverted some (many actually) changes and also improved a bit.
Main difference to PR #9591 are:
* It doesn't add additional widgets (clickable labels, checkbox word warps), all widgets are from stock, IMO it is inappropriate to introduce them in layout-change PR.
* Avoid setting widgets attributes explicitly when it is the same as the default.
* Correctly remember the horizontal splitter state.
* Follow previous settings layout closely, I don't think qbt should 100% copy utorrent's layout and reverted some questionable widget placements.
Screenshots:
Old: ![old](https://user-images.githubusercontent.com/9395168/57352943-8f529600-7199-11e9-84fd-a65bbd25791e.png)
New: ![new2](https://user-images.githubusercontent.com/9395168/57421477-97184600-723e-11e9-9722-f …
> Change "Add new torrent" dialog to horizontal layout
